### ISSUE TITLE
Dev not found

### ISSUE THREAD

**Issue by trunghlt** [NVIDIA/nccl#1008]
Hi, I have 4 GPUs and when I run NCCL test with all 4 GPUs (-g 4), it works fine. However when I set -g2 or -g3 it fails with an error:  Test NCCL failure common.cu:953 'unhandled system error.

**NCCL version:** 2.18.5+cuda12.2

**Here is the full stacktrace of the issue**:

```
$ NCCL_TOPOLOGY=IGNORE NCCL_DEBUG_SUBSYS=GRAPH NCCL_DEBUG=INFO ./build/all_reduce_perf -b 8 -e 256M -f 2 -g 2

# nThread 1 nGpus 2 minBytes 8 maxBytes 268435456 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid 648288 on a100-4x-machines-23fsd-2-dev device  0 [0x00] NVIDIA A100 80GB PCIe
#  Rank  1 Group  0 Pid 648288 on a100-4x-machines-23fsd-2-dev device  1 [0x00] NVIDIA A100 80GB PCIe
NCCL version 2.18.5+cuda12.2
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO Loading topology file /opt/microsoft/ncv4/topo.xml
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO Loading topology file /opt/microsoft/ncv4/topo.xml
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO Loading unnamed topology
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO Loading unnamed topology
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/0df46b95-2f0c-4e22-8845-3338a53a5914/pci2f0c:00/2f0c:00:00.0 is not a PCI device (). Attaching to first CPU
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/0df46b95-2f0c-4e22-8845-3338a53a5914/pci2f0c:00/2f0c:00:00.0 is not a PCI device (). Attaching to first CPU
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO === System : maxBw 240.0 totalBw 240.0 ===
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO CPU/0 (1/2/-1)
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO + PCI[5000.0] - NIC/0
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO + SYS[5000.0] - CPU/1
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO + PCI[12.0] - GPU/100000 (0)
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO               + NVL[240.0] - GPU/200000
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO CPU/1 (1/2/-1)
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO + SYS[5000.0] - CPU/0
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO + PCI[12.0] - GPU/200000 (1)
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO               + NVL[240.0] - GPU/100000
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO ==========================================
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (1/240.000000/NVL) CPU/0 (1/12.000000/PHB) CPU/1 (2/12.000000/SYS)
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO GPU/200000 :GPU/100000 (1/240.000000/NVL) GPU/200000 (0/5000.000000/LOC) CPU/0 (2/12.000000/SYS) CPU/1 (1/12.000000/PHB)
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO Loading graphs
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO === System : maxBw 240.0 totalBw 240.0 ===
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO CPU/0 (1/2/-1)
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO + PCI[5000.0] - NIC/0
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO + SYS[5000.0] - CPU/1
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO + PCI[12.0] - GPU/100000 (0)
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO               + NVL[240.0] - GPU/200000
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO CPU/1 (1/2/-1)
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO + SYS[5000.0] - CPU/0
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO + PCI[12.0] - GPU/200000 (1)
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO               + NVL[240.0] - GPU/100000
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO ==========================================
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (1/240.000000/NVL) CPU/0 (1/12.000000/PHB) CPU/1 (2/12.000000/SYS)
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO GPU/200000 :GPU/100000 (1/240.000000/NVL) GPU/200000 (0/5000.000000/LOC) CPU/0 (2/12.000000/SYS) CPU/1 (1/12.000000/PHB)

a100-4x-machines-23fsd-2-dev:648288:648307 [1] graph/search.cc:703 NCCL WARN XML Import Channel : dev 2 not found.
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO graph/search.cc:733 -> 2
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO graph/search.cc:740 -> 2
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO graph/search.cc:840 -> 2
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO init.cc:880 -> 2
a100-4x-machines-23fsd-2-dev:648288:648307 [1] NCCL INFO init.cc:1358 -> 2
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO Loading graphs

a100-4x-machines-23fsd-2-dev:648288:648306 [0] graph/search.cc:703 NCCL WARN XML Import Channel : dev 2 not found.
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO graph/search.cc:733 -> 2
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO graph/search.cc:740 -> 2
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO graph/search.cc:840 -> 2
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO init.cc:880 -> 2
a100-4x-machines-23fsd-2-dev:648288:648306 [0] NCCL INFO init.cc:1358 -> 2
a100-4x-machines-23fsd-2-dev:648288:648288 [1] NCCL INFO group.cc:406 -> 2
a100-4x-machines-23fsd-2-dev:648288:648288 [1] NCCL INFO group.cc:96 -> 2
a100-4x-machines-23fsd-2-dev:648288:648288 [1] NCCL INFO init.cc:1691 -> 2
a100-4x-machines-23fsd-2-dev: Test NCCL failure common.cu:953 'unhandled system error (run with NCCL_DEBUG=INFO for details) / '
 .. a100-4x-machines-23fsd-2-dev pid 648288: Test failure common.cu:844
```

**Comment by sjeaugey** [comment]
The error happens because you're injecting a graph e.g. `NCCL_GRAPH_FILE=graph.xml` but the graph file is for 4 GPUs, not 2 or 3.
Injecting a graph XML is good for experiments and playing around with different rings, but it should not be see as something to use permanently.

**Comment by trunghlt** [comment]
Hi I didn't inject a graph file from my cmd, how can I disable the default behaviour of loading the graph from /opt/microsoft/ncv4/topo.xml ?

**Comment by sjeaugey** [comment]
Loading the topology file is not the problem. NCCL_TOPO_FILE is fine. You have a NCCL_GRAPH_FILE set in your environment, causing that problem.

**Comment by trunghlt** [comment]
Hmnn I have double-checked and pretty sure NCCL_GRAPH_FILE is not set in my env.

**Comment by sjeaugey** [comment]
Hum. Could it be set inside `/etc/nccl.conf` or `~/.nccl.conf` ?

**Comment by trunghlt** [comment]
Ahh spot on, my NCCL_TOPO_FILE and NCCL_GRAPH_FILE are set in /etc/nccl.conf. I now deleted them and it works fine. Thank you so much!!!

**Comment by sjeaugey** [comment]
NCCL_TOPO_FILE could be useful if you're running inside a VM and the TOPO file describes the right topology. That's a common solution to propagate the topology information inside a VM which is not reflecting the topology correctly. For intra-node communication on NVSwitch systems it won't matter, but if you try to communicate inter-node it will be quite important.

**Comment by trunghlt** [comment]
Interesting, I have now put back NCCL_TOPO_FILE. Thanks!
