### ISSUE TITLE
ncclUnhandledCudaError: Call to CUDA function failed.

### ISSUE THREAD

**Issue by mlinmg** [NVIDIA/nccl#1024]
As described here [ncclUnhandledCudaError: Call to CUDA function failed.](https://github.com/hiyouga/LLaMA-Factory/issues/1169) I have a problem with nccl. I cannot do ddp with two 3090 ti

**Comment by AddyLaddy** [comment]
Did it work previously?

Can you try the latest NCCL 2.18.6 from this github repo?

**Comment by mlinmg** [comment]
I’m using torch so the nccl is boundled
However I compiled a nccl version and my nccl-test were normal and executed as expected.
I haven’t tried compiling torch myself but I don’t know if it’s worth to try
Marco

Il giorno 13 ott 2023, alle ore 07:59, David Addison ***@***.***> ha scritto:

﻿

Did it work previously?

Can you try the latest NCCL 2.18.6 from this github repo?

**Comment by sjeaugey** [comment]
It would be good to run again, setting NCCL_DEBUG=INFO. That way, we would have a clear error message and we'd be able to confirm whether this is a know issue which was fixed (and may have a workaround if you don't want to upgrade NCCL), or whether it's something like a configuration issue.

**Comment by sjeaugey** [comment]
Sorry I missed the linked bug. This is indeed the bug fixed by [this commit](https://github.com/NVIDIA/nccl/commit/4365458757e4107ecbf629b2fd6e0e19a5d237c2) which is indeed in 2.18.6.

**Comment by JerryDaHeLian** [comment]
I have encountered the same problem, has anyone solved it?

**Comment by JerryDaHeLian** [comment]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1347, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
I have encountered the same problem, has anyone solved it?

**Comment by mlinmg** [comment]
Do you use the pytorch cuda executables? I was using them with wsl and it was giving problems, if that's the case you could either try to upgrade to nightly torch or try another switch os(Ubuntu solved it for me)

**Comment by HouseYeung** [comment]
If you encounter this issue and other solutions are ineffective, you can try pip install --upgrade nvidia-nccl-cu12==2.19.3. Be aware that this might cause unknown damage to torch. This resolved the error for me.

**Comment by lonngxiang** [comment]
> pip install --upgrade nvidia-nccl-cu12==2.19.3

not work

**Comment by MonolithFoundation** [comment]
Same error for nccl 2.25.3

**Comment by yiyepiaoling0715** [comment]
check you args  whether is str or float

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're [reviewing](https://github.com/NVIDIA/nccl/discussions/1761) older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.

**Comment by puliming9988** [comment]
File "/root/app/Megatron-LM/megatron/core/distributed/distributed_data_parallel.py", line 642, in broadcast_params
(TaskRunner pid=193401)     torch.distributed.broadcast(
(TaskRunner pid=193401)   File "/root/miniforge3/envs/mfverlsgl/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
(TaskRunner pid=193401)     return func(*args, **kwargs)
(TaskRunner pid=193401)            ^^^^^^^^^^^^^^^^^^^^^
(TaskRunner pid=193401)   File "/root/miniforge3/envs/mfverlsgl/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2824, in broadcast
(TaskRunner pid=193401)     work = group.broadcast([tensor], opts)
(TaskRunner pid=193401)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(TaskRunner pid=193401) torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, internal error - please report this issue to the NCCL developers, NCCL version 2.27.3
(TaskRunner pid=193401) ncclInternalError: Internal check failed.
(TaskRunner pid=193401) Last error:
