### ISSUE TITLE
nccl-test stuck here！

### ISSUE THREAD

**Issue by ZYM66** [NVIDIA/nccl#1027]
```shell
Last login: Mon Oct 16 14:32:04 2023 from 10.4.6.15
dl@UIBE-DC-GPUSVR-01:~$ export NCCL_DEBUG=INFO
dl@UIBE-DC-GPUSVR-01:~$ cd nccl-tests/
dl@UIBE-DC-GPUSVR-01:~/nccl-tests$ ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 8
# nThread 1 nGpus 8 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  0 [0x4f] NVIDIA A800 80GB PCIe
#  Rank  1 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  1 [0x52] NVIDIA A800 80GB PCIe
#  Rank  2 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  2 [0x56] NVIDIA A800 80GB PCIe
#  Rank  3 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  3 [0x57] NVIDIA A800 80GB PCIe
#  Rank  4 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  4 [0xce] NVIDIA A800 80GB PCIe
#  Rank  5 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  5 [0xd1] NVIDIA A800 80GB PCIe
#  Rank  6 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  6 [0xd5] NVIDIA A800 80GB PCIe
#  Rank  7 Group  0 Pid  13313 on UIBE-DC-GPUSVR-01 device  7 [0xd6] NVIDIA A800 80GB PCIe
UIBE-DC-GPUSVR-01:13313:13313 [0] NCCL INFO Bootstrap : Using br0:10.4.11.18<0>
UIBE-DC-GPUSVR-01:13313:13313 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
UIBE-DC-GPUSVR-01:13313:13313 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
UIBE-DC-GPUSVR-01:13313:13313 [7] NCCL INFO cudaDriverVersion 12020
NCCL version 2.18.3+cuda12.1
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO NET/IB : No device found.
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO NET/Socket : Using [0]br0:10.4.11.18<0> [1]virbr0:192.168.122.1<0> [2]vnet0:fe80::fc54:ff:fe3f:6ac%vnet0<0>
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Using network Socket
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO comm 0x55b4098b4310 rank 1 nranks 8 cudaDev 1 nvmlDev 1 busId 52000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO comm 0x55b4098d10b0 rank 6 nranks 8 cudaDev 6 nvmlDev 6 busId d5000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO comm 0x55b4098b9f50 rank 2 nranks 8 cudaDev 2 nvmlDev 2 busId 56000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO comm 0x55b4098c56f0 rank 4 nranks 8 cudaDev 4 nvmlDev 4 busId ce000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO comm 0x55b4098bfb20 rank 3 nranks 8 cudaDev 3 nvmlDev 3 busId 57000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO comm 0x55b4098aaff0 rank 0 nranks 8 cudaDev 0 nvmlDev 0 busId 4f000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO comm 0x55b4098d6d90 rank 7 nranks 8 cudaDev 7 nvmlDev 7 busId d6000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO comm 0x55b4098cb3d0 rank 5 nranks 8 cudaDev 5 nvmlDev 5 busId d1000 commId 0xb9b42cb8fce289f2 - Init START
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Setting affinity for GPU 5 to ffff,fff00000,00ffffff,f0000000
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO NVLS multicast support is not available on dev 5
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Setting affinity for GPU 7 to ffff,fff00000,00ffffff,f0000000
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO NVLS multicast support is not available on dev 7
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Setting affinity for GPU 2 to 0fffff,ff000000,0fffffff
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO NVLS multicast support is not available on dev 2
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Setting affinity for GPU 6 to ffff,fff00000,00ffffff,f0000000
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO NVLS multicast support is not available on dev 6
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff,ff000000,0fffffff
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO NVLS multicast support is not available on dev 3
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Setting affinity for GPU 4 to ffff,fff00000,00ffffff,f0000000
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO NVLS multicast support is not available on dev 4
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff,ff000000,0fffffff
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO NVLS multicast support is not available on dev 1
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff,ff000000,0fffffff
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO NVLS multicast support is not available on dev 0
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Trees [0] 7/-1/-1->6->5 [1] 7/-1/-1->6->5
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Trees [0] 4/-1/-1->3->2 [1] 4/-1/-1->3->2
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Trees [0] 6/-1/-1->5->4 [1] 6/-1/-1->5->4
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Trees [0] -1/-1/-1->7->6 [1] -1/-1/-1->7->6
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Trees [0] 5/-1/-1->4->3 [1] 5/-1/-1->4->3
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Channel 00/02 :    0   1   2   3   4   5   6   7
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Channel 01/02 :    0   1   2   3   4   5   6   7
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO P2P Chunksize set to 524288
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Channel 00/0 : 5[5] -> 6[6] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Channel 00/0 : 2[2] -> 3[3] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Channel 00/0 : 1[1] -> 2[2] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Channel 00 : 3[3] -> 4[4] via SHM/direct/direct
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Channel 01/0 : 5[5] -> 6[6] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Channel 00/0 : 6[6] -> 7[7] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Channel 01/0 : 1[1] -> 2[2] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Channel 01/0 : 2[2] -> 3[3] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Channel 01/0 : 6[6] -> 7[7] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Channel 00/0 : 4[4] -> 5[5] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Channel 01 : 3[3] -> 4[4] via SHM/direct/direct
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Channel 00 : 7[7] -> 0[0] via SHM/direct/direct
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Channel 01/0 : 4[4] -> 5[5] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Channel 01 : 7[7] -> 0[0] via SHM/direct/direct
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Channel 00/0 : 2[2] -> 1[1] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Channel 00/0 : 7[7] -> 6[6] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Channel 01/0 : 2[2] -> 1[1] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Connected all rings
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Channel 01/0 : 7[7] -> 6[6] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Channel 00/0 : 5[5] -> 4[4] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Channel 00/0 : 6[6] -> 5[5] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Channel 01/0 : 5[5] -> 4[4] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Channel 01/0 : 6[6] -> 5[5] via P2P/direct pointer
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Channel 00/0 : 3[3] -> 2[2] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Channel 00 : 4[4] -> 3[3] via SHM/direct/direct
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Channel 01/0 : 3[3] -> 2[2] via P2P/direct pointer/read
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Channel 01 : 4[4] -> 3[3] via SHM/direct/direct
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO Connected all trees
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 512 | 512
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
UIBE-DC-GPUSVR-01:13313:13988 [0] NCCL INFO comm 0x55b4098aaff0 rank 0 nranks 8 cudaDev 0 nvmlDev 0 busId 4f000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13992 [4] NCCL INFO comm 0x55b4098c56f0 rank 4 nranks 8 cudaDev 4 nvmlDev 4 busId ce000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13994 [6] NCCL INFO comm 0x55b4098d10b0 rank 6 nranks 8 cudaDev 6 nvmlDev 6 busId d5000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO comm 0x55b4098b9f50 rank 2 nranks 8 cudaDev 2 nvmlDev 2 busId 56000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13993 [5] NCCL INFO comm 0x55b4098cb3d0 rank 5 nranks 8 cudaDev 5 nvmlDev 5 busId d1000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13989 [1] NCCL INFO comm 0x55b4098b4310 rank 1 nranks 8 cudaDev 1 nvmlDev 1 busId 52000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13991 [3] NCCL INFO comm 0x55b4098bfb20 rank 3 nranks 8 cudaDev 3 nvmlDev 3 busId 57000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
UIBE-DC-GPUSVR-01:13313:13995 [7] NCCL INFO comm 0x55b4098d6d90 rank 7 nranks 8 cudaDev 7 nvmlDev 7 busId d6000 commId 0xb9b42cb8fce289f2 - Init COMPLETE
#
#                                                              out-of-place                       in-place          
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
```

**Comment by ZYM66** [comment]
I noticed that there is a issue:
```shell
UIBE-DC-GPUSVR-01:13313:13313 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
UIBE-DC-GPUSVR-01:13313:13313 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
UIBE-DC-GPUSVR-01:13313:13313 [7] NCCL INFO cudaDriverVersion 12020
NCCL version 2.18.3+cuda12.1
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO NET/IB : No device found.
UIBE-DC-GPUSVR-01:13313:13990 [2] NCCL INFO NET/Socket : Using [0]br0:10.4.11.18<0> [1]virbr0:192.168.122.1<0> [2]vnet0:fe80::fc54:ff:fe3f:6ac%vnet0<0>
```
Is there anything wrong?

**Comment by ZYM66** [comment]
> This is running on a single node, so the networking speed shouldn't matter.
> 
> You may have ACS enabled on your system which would break GPU Direct P2P. To confirm that, you can try again with `NCCL_P2P_DISABLE=1`.
> 
> Or it could be that the network interface you are using it blocked by e.g. a firewall. You can confirm that theory by running with `NCCL_SOCKET_IFNAME=lo`.

Thank you, it works!
<img width="999" alt="image" src="https://github.com/NVIDIA/nccl/assets/61892155/be762fce-792d-4ccc-9ce8-1175801e982f">

**Comment by sjeaugey** [comment]
Disabling P2P is a workaround. Performance will be bad and NVLink won't be used if you have NVLink bridges.

Please see this doc entry on how to disable ACS on the PCI switches so that P2P can work:
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs
