### ISSUE TITLE
torch.distributed.DistBackendError: NCCL error on 2.18.5 version when using lightning with distributed strategy

### ISSUE THREAD

**Issue by Galaxy-Husky** [NVIDIA/nccl#1051]
Hi,

When I tried run examples of lightning fabric with mutiple gpus using dp or ddp strategy, it raised some NCCL errors.

# Error message for dp
Traceback (most recent call last):
  File "/home/ping/TVAE/train.py", line 76, in <module>
    main()
  File "/home/ping/TVAE/train.py", line 26, in main
    train(fabric, model, optimizer, train_dataloader, val_dataloader)
  File "/home/ping/TVAE/train.py", line 31, in train
    train_epoch(fabric, model, optimizer, train_dataloader, epoch)
  File "/home/ping/TVAE/train.py", line 39, in train_epoch
    output = model(input, target)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 184, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 189, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/replicate.py", line 110, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/replicate.py", line 83, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/_functions.py", line 23, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/comm.py", line 57, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 3: internal error - please report this issue to the NCCL developers

# Error message for ddp
Traceback (most recent call last):
  File "/home/ping/TVAE/train.py", line 76, in <module>                                           main()
  File "/home/ping/TVAE/train.py", line 24, in main                                               model, optimizer = fabric.setup(model, optimizer)
  File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 238, in setup
    module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignmen
t]                                                                                              File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/lightning/fabric/str
ategies/strategy.py", line 157, in setup_module_and_optimizers
    module = self.setup_module(module)                                                          File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/lightning/fabric/str
ategies/ddp.py", line 121, in setup_module
    return DistributedDataParallel(module=module, device_ids=device_ids, **self._ddp_kwargs)    File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/nn/parallel/di
stributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)                        File "/home/ping/mambaforge/envs/lightning/lib/python3.10/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1695392020201/
work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, internal error - please report thi
s issue to the NCCL developers, NCCL version 2.18.5
ncclInternalError: Internal check failed.
Last error:
Attribute busid of node nic not found

**Comment by algopapi** [comment]
same issue here using accelerate

**Comment by baudneo** [comment]
Same here but not using lightning. I am using torchrun and multi-node DDP.

**Comment by sxwl-donggang** [comment]
same issue

**Comment by YistYU** [comment]
For your reference, I solve this issue with the environment below:
conda create -n env_name python=3.9 numpy pandas
conda activate env_name
conda install nvidia/label/cuda-11.7.0::cuds-toolkit 
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu117
pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cu117.html

**Comment by JubilantJerry** [comment]
It seems likely to be caused by a bug in NCCL, as the symptoms of the bug are similar on my machine: https://github.com/NVIDIA/nccl/issues/1125

I've verified that pytorch 2.0.1 didn't show the bug, on my machine it uses NCCL 2.14.3. When I use pytorch 2.1.2 I get the bug, it uses NCCL 2.18.6. When I run the NCCL tests (https://github.com/NVIDIA/nccl-tests), which is completely independent of pytorch, I still get the same bug with NCCL 2.19.4.

I think the bug is probably fixed now due to the patch in the linked issue. I haven't tested the patch (compiling NCCL from source) to see if the bug actually goes away for me, though.

**Comment by AddyLaddy** [comment]
The bug fixed in #1125 was due to NCCL not handling USB network devices correctly. It will be fixed in NCCL 2.20.x

**Comment by lucasjinreal** [comment]
@AddyLaddy  How to fix it at this moment?

**Comment by EricLina** [comment]
> I think the problem has something to do with pytorch 2.1.0 because when I downgraded pytorch to 2.0.1, the error disappeared. I have submitted an issue on pytorch, please see [pytorch/pytorch#113245](https://github.com/pytorch/pytorch/issues/113245). But so far I have not received a reply.

It doesn't work for me.

**Comment by Galaxy-Husky** [comment]
> such that the first entry is not 0 or 1. For example, I was able to bypass the issue by setting `CUDA_VISIBLE_DEVICES=3,2,1,0`

Could you try to set CUDA_VISIBLE_DEVICES=3,2,1,0, such that the first entry is not 0 or 1 ?

**Comment by Galaxy-Husky** [comment]
> > I think the problem has something to do with pytorch 2.1.0 because when I downgraded pytorch to 2.0.1, the error disappeared. I have submitted an issue on pytorch, please see [pytorch/pytorch#113245](https://github.com/pytorch/pytorch/issues/113245). But so far I have not received a reply.
> 
> It doesn't work for me.

Could you try to set CUDA_VISIBLE_DEVICES=3,2,1,0, such that the first entry is not 0 or 1 ?

**Comment by Galaxy-Husky** [comment]
I have just installed the latest pytorch 2.3.0 with cuda 11.8, which has the nccl 2.20.5. I tested it and found that the problem was fixed.
