### ISSUE TITLE
transport/net_ib.cc:1295 NCCL WARN NET/IB : Got completion from peer  with error 4, opcode 0, len 0, vendor err 81 (Send) localGid ::ffff: remoteGid ::ffff:

### ISSUE THREAD

**Issue by xx82** [NVIDIA/nccl#1052]
Whenever GDR is used(load nv_peer_mem driver), an error is reported.
When GDR is disabled, or the NIC and GPU topology does not meet GDR, no errors are reported and it runs fine.
Testing with ib_send_bw and ib_write_bw alone is fine.

I use H800 SXM5.

**command**
$mpirun -x PATH -x LD_LIBRARY_PATH -x CUDA_VISIBLE_DEVICES=2 -x NCCL_IB_GID_INDEX=3 -x NCCL_IB_HCA=mlx5_4 -x NCCL_DEBUG -np 2 -host node2,node4 ./all_reduce_perf -b 256M -f 2 -e 256M -g 1

**result**
# nThread 1 nGpus 1 minBytes 268435456 maxBytes 268435456 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid  14159 on node2 device  0 [0x4c] NVIDIA H800
#  Rank  1 Group  0 Pid 565139 on node4 device  0 [0x4c] NVIDIA H800
node2:14159:14159 [0] NCCL INFO Bootstrap : Using enp24s0np0:10.10.10.1<0>
node2:14159:14159 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
node2:14159:14159 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
node2:14159:14159 [0] NCCL INFO cudaDriverVersion 12020
NCCL version 2.18.5+cuda12.0
node4:565139:565139 [0] NCCL INFO cudaDriverVersion 12020
node4:565139:565139 [0] NCCL INFO Bootstrap : Using enp24s0np0:10.10.10.3<0>
node4:565139:565139 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
node4:565139:565139 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
node2:14159:14168 [0] NCCL INFO NCCL_IB_HCA set to mlx5_4
node4:565139:565148 [0] NCCL INFO NCCL_IB_HCA set to mlx5_4
node2:14159:14168 [0] NCCL INFO NET/IB : Using [0]mlx5_4:1/RoCE [RO]; OOB enp24s0np0:10.10.10.1<0>
node2:14159:14168 [0] NCCL INFO Using network IB
node4:565139:565148 [0] NCCL INFO NET/IB : Using [0]mlx5_4:1/RoCE [RO]; OOB enp24s0np0:10.10.10.3<0>
node4:565139:565148 [0] NCCL INFO Using network IB
node2:14159:14168 [0] NCCL INFO comm 0x55c6d68d7b20 rank 0 nranks 2 cudaDev 0 nvmlDev 2 busId 4c000 commId 0xbe1ea4dcf86be262 - Init START
node4:565139:565148 [0] NCCL INFO comm 0x564be74e2e30 rank 1 nranks 2 cudaDev 0 nvmlDev 2 busId 4c000 commId 0xbe1ea4dcf86be262 - Init START
node4:565139:565148 [0] NCCL INFO Setting affinity for GPU 2 to 010000,00000000,00000000,00000001
node2:14159:14168 [0] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 0 'mlx5_4'
node2:14159:14168 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 4c000 / HCA 0 (distance 3 <= 4), read 0
node2:14159:14168 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 4c000 / HCA 0 (distance 3 <= 4), read 0
node2:14159:14168 [0] NCCL INFO === System : maxBw 24.0 totalBw 160.0 ===
node2:14159:14168 [0] NCCL INFO CPU/0 (1/1/2)
node2:14159:14168 [0] NCCL INFO + PCI[48.0] - PCI/49000 (1000c0301000100b)
node2:14159:14168 [0] NCCL INFO               + PCI[48.0] - GPU/4C000 (0)
node2:14159:14168 [0] NCCL INFO                             + NVL[160.0] - NVS/0
node2:14159:14168 [0] NCCL INFO               + PCI[24.0] - NIC/4B000
node2:14159:14168 [0] NCCL INFO                             + NET[25.0] - NET/0 (74db9c0003ae6d94/1/25.000000)
node2:14159:14168 [0] NCCL INFO ==========================================
node2:14159:14168 [0] NCCL INFO GPU/4C000 :GPU/4C000 (0/5000.000000/LOC) NVS/0 (1/160.000000/NVL) CPU/0 (2/48.000000/PHB) NET/0 (3/24.000000/PIX)
node2:14159:14168 [0] NCCL INFO NET/0 :GPU/4C000 (3/24.000000/PIX) CPU/0 (3/24.000000/PHB) NET/0 (0/5000.000000/LOC)
node2:14159:14168 [0] NCCL INFO Setting affinity for GPU 2 to 010000,00000000,00000000,00000001
node2:14159:14168 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, bw 24.000000/24.000000, type LOC/PIX, sameChannels 1
node2:14159:14168 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
node2:14159:14168 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, bw 48.000000/24.000000, type LOC/PIX, sameChannels 1
node2:14159:14168 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
node2:14159:14168 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/-1/-1
node2:14159:14168 [0] NCCL INFO Tree 1 : 1 -> 0 -> -1/-1/-1
node2:14159:14168 [0] NCCL INFO Channel 00/02 :    0   1
node2:14159:14168 [0] NCCL INFO Channel 01/02 :    0   1
node2:14159:14168 [0] NCCL INFO Ring 00 : 1 -> 0 -> 1
node2:14159:14168 [0] NCCL INFO Ring 01 : 1 -> 0 -> 1
node2:14159:14168 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
node2:14159:14168 [0] NCCL INFO P2P Chunksize set to 131072
node4:565139:565148 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
node4:565139:565148 [0] NCCL INFO P2P Chunksize set to 131072
node2:14159:14168 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 4c000 / HCA 0 (distance 3 <= 4), read 0
node2:14159:14172 [0] NCCL INFO New proxy recv connection 0 from local rank 0, transport 2
node2:14159:14168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f7698000d80
node4:565139:565148 [0] NCCL INFO Channel 00/0 : 0[2] -> 1[2] [receive] via NET/IB/0/GDRDMA
node4:565139:565148 [0] NCCL INFO Channel 01/0 : 0[2] -> 1[2] [receive] via NET/IB/0/GDRDMA
node4:565139:565148 [0] NCCL INFO Channel 00/0 : 1[2] -> 0[2] [send] via NET/IB/0/GDRDMA
node4:565139:565148 [0] NCCL INFO Channel 01/0 : 1[2] -> 0[2] [send] via NET/IB/0/GDRDMA
node2:14159:14168 [0] NCCL INFO Channel 00/0 : 1[2] -> 0[2] [receive] via NET/IB/0/GDRDMA
node2:14159:14168 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 4c000 / HCA 0 (distance 3 <= 4), read 0
node2:14159:14172 [0] NCCL INFO New proxy recv connection 1 from local rank 0, transport 2
node2:14159:14168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f7698000dd0
node2:14159:14168 [0] NCCL INFO Channel 01/0 : 1[2] -> 0[2] [receive] via NET/IB/0/GDRDMA
node2:14159:14168 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 4c000 / HCA 0 (distance 3 <= 4), read 1
node2:14159:14172 [0] NCCL INFO New proxy send connection 2 from local rank 0, transport 2
node2:14159:14168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f7698000e20
node2:14159:14168 [0] NCCL INFO Channel 00/0 : 0[2] -> 1[2] [send] via NET/IB/0/GDRDMA
node2:14159:14168 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 4c000 / HCA 0 (distance 3 <= 4), read 1
node2:14159:14172 [0] NCCL INFO New proxy send connection 3 from local rank 0, transport 2
node2:14159:14168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f7698000e70
node2:14159:14168 [0] NCCL INFO Channel 01/0 : 0[2] -> 1[2] [send] via NET/IB/0/GDRDMA
node2:14159:14172 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
node2:14159:14172 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 58 mtu 3 GID 3 (0/A10B0A0AFFFF0000)
node4:565139:565151 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
node2:14159:14172 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 59 mtu 3 GID 3 (0/A10B0A0AFFFF0000)
node4:565139:565148 [0] NCCL INFO Connected all rings
node4:565139:565148 [0] NCCL INFO Connected all trees
node2:14159:14168 [0] NCCL INFO Connected all rings
node2:14159:14168 [0] NCCL INFO Connected all trees
node4:565139:565148 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
node4:565139:565148 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
node2:14159:14168 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
node2:14159:14168 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
node2:14159:14172 [0] NCCL INFO New proxy send connection 4 from local rank 0, transport 2
node2:14159:14168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f7698000ec0
node2:14159:14168 [0] NCCL INFO comm 0x55c6d68d7b20 rank 0 nranks 2 cudaDev 0 nvmlDev 2 busId 4c000 commId 0xbe1ea4dcf86be262 - Init COMPLETE
node4:565139:565148 [0] NCCL INFO comm 0x564be74e2e30 rank 1 nranks 2 cudaDev 0 nvmlDev 2 busId 4c000 commId 0xbe1ea4dcf86be262 - Init COMPLETE
#
#                                                              out-of-place                       in-place
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)

node4:565139:565152 [0] _transport/net_ib.cc:1295 NCCL WARN NET/IB : Got completion from peer 10.10.10.1<51993> with error 4, opcode 0, len 0, vendor err 81 (Send)_ localGid ::ffff:10.10.10.3 remoteGid ::ffff:10.10.10.1
node4:565139:565152 [0] NCCL INFO transport/net.cc:1008 -> 6
node4:565139:565152 [0] NCCL INFO proxy.cc:679 -> 6
node4:565139:565152 [0] NCCL INFO proxy.cc:858 -> 6 [Proxy Thread]

node2:14159:14173 [0] _transport/net_ib.cc:1295 NCCL WARN NET/IB : Got completion from peer 10.10.10.3<44505> with error 4, opcode 0, len 0, vendor err 81 (Send)_ localGid ::ffff:10.10.10.1 remoteGid ::ffff:10.10.10.3
node2:14159:14173 [0] NCCL INFO transport/net.cc:1008 -> 6
node2:14159:14173 [0] NCCL INFO proxy.cc:679 -> 6
node2:14159:14173 [0] NCCL INFO proxy.cc:858 -> 6 [Proxy Thread]

I checked that VT-d and PCIe ACS are both off. All of the ACSCtl is SrcValid-. None of this has worked. The error remains.

**Comment by sjeaugey** [comment]
Are you sure you checked all nodes involved in the job?

**Comment by xx82** [comment]
> Are you sure you checked all nodes involved in the job?
I checked both nodes and swapped the GID Index and GPU combinations and the specified SOCKET_IFNAME issue is consistent. The problem occurs whenever GDR is used.

**Comment by elevenxiang** [comment]
try to turn off the iommu

**Comment by xx82** [comment]
> try to turn off the iommu

I use intel CPU， I have let eth VT-d disable. 
Does the following output mean that I have turned off IOMMU, or what other actions should I take?
$ sudo dmesg | grep -i IOMMU
[   23.932606] iommu: Default domain type: Translated
[   23.932606] iommu: DMA domain TLB invalidation policy: lazy mode

**Comment by xx82** [comment]
Thanks for the replies, upgraded the firmware on the pcie switch and it works fine.

**Comment by guunergooner** [comment]
I also encountered a similar problem. 
You can confirm whether the ACS of PCI-E in the server is enabled? 
You can refer to the nccl user guide troubleshooting document: 
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs.
