### ISSUE TITLE
nccl internal error in training gpt2

### ISSUE THREAD

**Issue by ziyang-arch** [NVIDIA/nccl#1090]
When I was using nvidia v100 GPU on google clouds to fine-tuning gpt2 with deepspeed zero stage 3, I had an error like this 

`Traceback (most recent call last):
  File "/home/***/IdleInTP/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 333, in <module>
    main()
  File "/home/***/IdleInTP/DeepSpeed-Chat/training/step1_supervised_finetuning/main.py", line 306, in main
    model.backward(loss)
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1962, in backward
    self.allreduce_gradients()
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1883, in allreduce_gradients
    self.optimizer.overlapping_partition_gradients_reduce_epilogue()
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 1054, in overlapping_partition_gradients_reduce_epilogue
    self.independent_gradient_partition_epilogue()
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 1031, in independent_gradient_partition_epilogue
    self.__reduce_and_partition_ipg_grads()
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 1160, in __reduce_and_partition_ipg_grads
    grad_partitions = self.__avg_scatter_grads(self.params_in_ipg_bucket)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/zero/stage3.py", line 1229, in __avg_scatter_grads
    grad_partitions_for_rank = reduce_scatter_coalesced(full_grads_for_rank, self.dp_process_group)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 120, in reduce_scatter_coalesced
    _torch_reduce_scatter_fn(tensor_partition_flat_buffer,
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/runtime/comm/coalesced_collectives.py", line 23, in _torch_reduce_scatter_fn
    return instrument_w_nvtx(dist.reduce_scatter_fn)(output_tensor, input_tensor, group=group, async_op=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 257, in reduce_scatter_fn
    return reduce_scatter_tensor(output_tensor,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 289, in reduce_scatter_tensor
    return cdb.reduce_scatter_tensor(output_tensor=output_tensor,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/deepspeed/comm/torch.py", line 255, in reduce_scatter_tensor
    return self.reduce_scatter_function(output_tensor,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/miniconda3/envs/cu121/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3375, in reduce_scatter_tensor
    work = group._reduce_scatter_base(output, input, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1695392035891/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, internal error - please report this issue to the NCCL developers, NCCL version 2.18.5
ncclInternalError: Internal check failed.`

cuda version 12.1, python version 3.11.5, nccl version 2.18.5

**Comment by PhdShi** [comment]
please try NCCL_DEBUG=INFO to get more information

**Comment by ziyang-arch** [comment]
I tried several times today and that error disappeared. 
Thanks
