### ISSUE TITLE
NCCL Error 2: unhandled system error

### ISSUE THREAD

**Issue by YasminSalehi** [NVIDIA/nccl#1101]
Hi, 

I've been trying to run my code on an Azure server which uses 2 A100 GPUs. However I get the following error:

RuntimeError: NCCL Error 2: unhandled system error

and this is what I see when I run my code with ```NCCL_DEBUG=INFO```:

```
cs-project:2748:2748 [0] NCCL INFO cudaDriverVersion 12020                                                                                                                           | 0/100 [00:00<?, ?it/s]
cs-project:2748:2748 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.6<0>
cs-project:2748:2748 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
cs-project:2748:2748 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
NCCL version 2.18.6+cuda12.1
cs-project:2748:2852 [1] NCCL INFO NET/IB : Using [0]mlx5_an0:1/RoCE [RO]; OOB eth0:10.0.0.6<0>
cs-project:2748:2852 [1] NCCL INFO Using network IB
cs-project:2748:2851 [0] NCCL INFO Using network IB
cs-project:2748:2851 [0] NCCL INFO comm 0x5f4c0370 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 100000 commId 0xffa1ecd94ef8180a - Init START
cs-project:2748:2852 [1] NCCL INFO comm 0x5f4c3230 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 200000 commId 0xffa1ecd94ef8180a - Init START
cs-project:2748:2852 [1] NCCL INFO NCCL_TOPO_FILE set by environment to /opt/microsoft/ncv4/topo.xml
cs-project:2748:2851 [0] NCCL INFO NCCL_TOPO_FILE set by environment to /opt/microsoft/ncv4/topo.xml
cs-project:2748:2851 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
cs-project:2748:2851 [0] NCCL INFO NCCL_GRAPH_FILE set by environment to /opt/microsoft/ncv4/graph.xml
cs-project:2748:2852 [1] NCCL INFO Setting affinity for GPU 1 to ffff,ff000000
cs-project:2748:2852 [1] NCCL INFO NCCL_GRAPH_FILE set by environment to /opt/microsoft/ncv4/graph.xml

cs-project:2748:2852 [1] graph/search.cc:703 NCCL WARN XML Import Channel : dev 2 not found.
cs-project:2748:2852 [1] NCCL INFO graph/search.cc:733 -> 2
cs-project:2748:2852 [1] NCCL INFO graph/search.cc:740 -> 2
cs-project:2748:2852 [1] NCCL INFO graph/search.cc:840 -> 2
cs-project:2748:2852 [1] NCCL INFO init.cc:880 -> 2
cs-project:2748:2852 [1] NCCL INFO init.cc:1358 -> 2
cs-project:2748:2852 [1] NCCL INFO group.cc:65 -> 2 [Async thread]

cs-project:2748:2851 [0] graph/search.cc:703 NCCL WARN XML Import Channel : dev 2 not found.
cs-project:2748:2851 [0] NCCL INFO graph/search.cc:733 -> 2
cs-project:2748:2851 [0] NCCL INFO graph/search.cc:740 -> 2
cs-project:2748:2851 [0] NCCL INFO graph/search.cc:840 -> 2
cs-project:2748:2851 [0] NCCL INFO init.cc:880 -> 2
cs-project:2748:2851 [0] NCCL INFO init.cc:1358 -> 2
cs-project:2748:2851 [0] NCCL INFO group.cc:65 -> 2 [Async thread]
cs-project:2748:2748 [0] NCCL INFO group.cc:406 -> 2
cs-project:2748:2748 [0] NCCL INFO group.cc:96 -> 2
cs-project:2748:2748 [0] NCCL INFO init.cc:1691 -> 2
``` 

I thought maybe my torch and driver versions are incompatible, but based on their documentation, they seem to be fine:

NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1

I appreciate any insight on how I can overcome this issue! Thank you very much!

**Comment by yangyingxiang** [comment]
@YasminSalehi have you resolved it?

**Comment by AddyLaddy** [comment]
Is the Azure environment setting this?

```NCCL INFO NCCL_GRAPH_FILE set by environment to /opt/microsoft/ncv4/graph.xml```

That's likely to break unless it exactly matches the node topology and number of GPUs it's being executed on. 
Are there just 2 GPUs in each of these nodes?

**Comment by rasenganai** [comment]
Facing the same issue.

NCCL_TOPO_FILE=/opt/microsoft/ncv4/topo.xml
NCCL_GRAPH_FILE=/opt/microsoft/ncv4/graph.xml

these are the azure env settings.

**Comment by sjeaugey** [comment]
Setting the topo file is fine. Setting the graph file is not; you should remove NCCL_GRAPH_FILE from the settings.

**Comment by rasenganai** [comment]
Thanks it worked!

**Comment by kamillle** [comment]
I remove a line `NCCL_GRAPH_FILE=/opt/microsoft/ncv4/graph.xml` from `/etc/nccl.conf`  then works
