### ISSUE TITLE
Advice on resolving `socketProgress: Connection closed by remote peer` and `socketFinalizeAccept: wrong magic` warnings

### ISSUE THREAD

**Issue by awaelchli** [NVIDIA/nccl#1117]
In my training run, I get the following warnings quite frequently and repeated many times.

```
 ip-10-192-10-178:3354:9681 [0] misc/socket.cc:432 NCCL WARN socketFinalizeAccept: wrong magic 16900000316 != 5327f0e088587e42
```

```
 ip-10-192-10-178:3358:13338 [2] misc/socket.cc:50 NCCL WARN socketProgress: Connection closed by remote peer 203.12.218.133<46494>
 ip-10-192-10-178:3358:13338 [2] NCCL INFO misc/socket.cc:58 -> 6
 ip-10-192-10-178:3358:13338 [2] NCCL INFO misc/socket.cc:430 -> 6
 ip-10-192-10-178:3358:13338 [2] NCCL INFO misc/socket.cc:562 -> 6
 ip-10-192-10-178:3358:13338 [2] NCCL INFO misc/socket.cc:666 -> 6
 
 ip-10-192-10-178:3358:13338 [2] proxy.cc:1494 NCCL WARN [Service thread] Accept failed Success
 ```
 Is there any advice you could give for me to resolve these? Are these warnings "normal" or should I take action to resolve them? My understanding is that there could be a network issue, but I'm not sure what could be causing it. Any advice where to start investigating would be very much appreciated, thank you!

I'm running on across 8 p4d.24xlarge machines, with EFA.
NCCL version:  2.19.3+cuda12.3
aws-ofi-nccl 1.6.0

Here is the full NCCL_DEBUG=INFO print at the beginning of execution:
[logs.txt](https://github.com/NVIDIA/nccl/files/13679705/logs.txt)

**Comment by awaelchli** [comment]
I also saw a similar issue here #188, where it turned out that some ranks used socket instead of IB. But in my case, none of the NCCL debug logs suggest that any of my ranks are using the socket IF. Although, the suspicious issue is that the warning/error message mentions `misc/socket.cc:50` which is the only indication.

**Comment by AddyLaddy** [comment]
You can force NCCL to fail if it doesn't have access to the IB/RoCE network by setting `NCCL_NET=IB`

**Comment by AddyLaddy** [comment]
On an AWS/EFA machine you shouldn't be using Sockets for the inter-node data channels. You need to be using the AWS specific EFA network plugin to operate correctly on those nodes.

**Comment by awaelchli** [comment]
@AddyLaddy Thanks for checking
The logs I attached in the issue above show that it is using the EFA network devices:

```
ip-10-192-10-178:3354:9666 [0] NCCL INFO NET/OFI Using aws-ofi-nccl 1.6.0
 ip-10-192-10-178:3354:9666 [0] NCCL INFO NET/OFI Configuring AWS-specific options
 ip-10-192-10-178:3354:9666 [0] NCCL INFO NET/OFI Setting NCCL_PROTO to "simple"
 ip-10-192-10-178:3354:9666 [0] NCCL INFO NET/OFI Setting RDMAV_FORK_SAFE environment variable to 1
 ip-10-192-10-178:3354:9666 [0] NCCL INFO NET/OFI Running on p4d.24xlarge platform, Setting NCCL_TOPO_FILE environment variable to /opt/aws-ofi-nccl/share/aws-ofi-nccl/xml/p4d-24xl-topo.xml
 ip-10-192-10-178:3354:9666 [0] NCCL INFO NET/OFI Selected Provider is efa (found 1 nics)
 ip-10-192-10-178:3354:9666 [0] NCCL INFO Using non-device net plugin version 0
 ip-10-192-10-178:3354:9666 [0] NCCL INFO Using network AWS Libfabric
```
This should be all in line. Also, the speed of communication is fast enough to suggest I'm not using sockets. That's why I'm puzzled by the socket warnings. Maybe it is specific to PyTorch FSDP which is what I'm currently using.
