### ISSUE TITLE
`unhandled cuda error` when running the test executable after `make` on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by arpane4c5** [NVIDIA/nccl#112]
I have installed NCCL on Ubuntu Server 16.04 having 2 Quadro K4200 GPU cards with CUDA 8.0. I followed the instructions given in the readme file. First of all, I cloned the repo in `/usr/local/` and ran `sudo make CUDA_HOME=$CUDA_HOME test` where `CUDA_HOME` points to `/usr/local/cuda-8.0`. I set the LD_LIBRARY_PATH and finally ran `./build/test/single/all_reduce_test 10000000`.  This gave me following error

![error0](https://user-images.githubusercontent.com/6323194/30807005-a1b74bc4-a215-11e7-8985-de79f1bc35f8.png)

When I ran with `NCCL_DEBUG=INFO` then I got the following details. 
![error](https://user-images.githubusercontent.com/6323194/30806931-5a886832-a215-11e7-898f-8810371907ae.png)
It is showing that there is some problem with accessing global device memory. I ran a sample cuda program but that is working fine. I'm new to NCCL and thought of installing it before installing Caffe. Is there something that I'm doing wrong? Please guide me in this regard. 
Thanks

**Comment by sjeaugey** [comment]
Quadro K4200 have compute capability 3.0 (https://developer.nvidia.com/cuda-gpus), which is not compiled by default (https://github.com/NVIDIA/nccl/blob/master/Makefile#L20-L25)

**Comment by arpane4c5** [comment]
Thank you @sjeaugey for pointing out. I made the change in Makefile 
`NVCC_GENCODE ?= -gencode=arch=compute_30,code=sm_30` and compiled again. It is working now.
![error_solved](https://user-images.githubusercontent.com/6323194/30823741-e163f9c2-a24a-11e7-8615-51a02fa24f2e.png)
Thank you once again for your input.
