### ISSUE TITLE
Cannot initialize on 1 or 2 devices.

### ISSUE THREAD

**Issue by simonbyrne** [NVIDIA/nccl#1125]
I am trying to use NCCL on an 8-GPU machine. I found that I am unable to use it with only 1 or 2 GPUs:

```C
#include <stdio.h>
#include <stdlib.h>
#include "cuda_runtime.h"
#include "nccl.h"

#define NCCLCHECK(cmd) do {                         \
  ncclResult_t res = cmd;                           \
  if (res != ncclSuccess) {                         \
    printf("Failed, NCCL error %s:%d '%s'\n",       \
        __FILE__,__LINE__,ncclGetErrorString(res)); \
    exit(EXIT_FAILURE);                             \
  }                                                 \
} while(0)

int main(int argc, char* argv[])
{
  ncclComm_t comms[4];

  int nDev = 2;
  int devs[4] = {0, 1, 2, 3};

  NCCLCHECK(ncclCommInitAll(comms, nDev, devs));

  //finalizing NCCL
  for(int i = 0; i < nDev; ++i)
      ncclCommDestroy(comms[i]);

  printf("Success \n");
  return 0;
}
```
Gives the following error:
```
Failed, NCCL error nccl-init.c:22 'internal error - please report this issue to the NCCL developers'
```
I get the same if I set `nDev` to 1, but 3 or higher appears to work.

This was observed using both the prebuilt 2.19.3 libraries from https://developer.nvidia.com/nccl/nccl-download, and my own build 2.19.4.

**Comment by AddyLaddy** [comment]
Can we see the `NCCL_DEBUG=INFO` logs of the failure. 
You can also set `NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH` to get more details.

What topology does this machine have? NVLink or PCI-E?
Is it running on bare-metal or inside a container?

**Comment by simonbyrne** [comment]
> Can we see the `NCCL_DEBUG=INFO` logs of the failure.
> You can also set `NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH` to get more details.

```
clima:810632:810632 [0] NCCL INFO cudaDriverVersion 12030
clima:810632:810632 [0] NCCL INFO Bootstrap : Using enp46s0f3u1u2c2:169.254.3.1<0>
clima:810632:810632 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
NCCL version 2.19.3+cuda12.3
clima:810632:810657 [0] NCCL INFO NET/IB : No device found.
clima:810632:810657 [0] NCCL INFO NET/Socket : Using [0]enp46s0f3u1u2c2:169.254.3.1<0> [1]enp44s0f0:131.215.103.35<0>
clima:810632:810657 [0] NCCL INFO Using non-device net plugin version 0
clima:810632:810657 [0] NCCL INFO Using network Socket
clima:810632:810658 [1] NCCL INFO Using non-device net plugin version 0
clima:810632:810658 [1] NCCL INFO Using network Socket
clima:810632:810657 [0] NCCL INFO comm 0x1d1a9f0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 7000 commId 0x93eefda7152ba363 - Init START
clima:810632:810658 [1] NCCL INFO comm 0x1d1e8b0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId a000 commId 0x93eefda7152ba363 - Init START
clima:810632:810657 [0] NCCL INFO Topology detection: network path /sys/devices/pci0000:2b/0000:2b:08.1/0000:2e:00.3/usb1/1-1/1-1.2/1-1.2:2.0 is not a PCI device (usb). Attaching to first CPU

clima:810632:810657 [0] graph/xml.h:85 NCCL WARN Attribute busid of node nic not found
clima:810632:810657 [0] NCCL INFO graph/xml.cc:589 -> 3
clima:810632:810657 [0] NCCL INFO graph/xml.cc:806 -> 3
clima:810632:810657 [0] NCCL INFO graph/topo.cc:689 -> 3
clima:810632:810657 [0] NCCL INFO init.cc:881 -> 3
clima:810632:810657 [0] NCCL INFO init.cc:1396 -> 3
clima:810632:810657 [0] NCCL INFO group.cc:64 -> 3 [Async thread]
clima:810632:810658 [1] NCCL INFO Topology detection: network path /sys/devices/pci0000:2b/0000:2b:08.1/0000:2e:00.3/usb1/1-1/1-1.2/1-1.2:2.0 is not a PCI device (usb). Attaching to first CPU

clima:810632:810658 [1] graph/xml.h:85 NCCL WARN Attribute busid of node nic not found
clima:810632:810658 [1] NCCL INFO graph/xml.cc:589 -> 3
clima:810632:810658 [1] NCCL INFO graph/xml.cc:806 -> 3
clima:810632:810658 [1] NCCL INFO graph/topo.cc:689 -> 3
clima:810632:810658 [1] NCCL INFO init.cc:881 -> 3
clima:810632:810658 [1] NCCL INFO init.cc:1396 -> 3
clima:810632:810658 [1] NCCL INFO group.cc:64 -> 3 [Async thread]
clima:810632:810632 [0] NCCL INFO group.cc:418 -> 3
clima:810632:810632 [0] NCCL INFO group.cc:95 -> 3
clima:810632:810632 [0] NCCL INFO init.cc:1734 -> 3
Failed, NCCL error nccl-init.c:27 'internal error - please report this issue to the NCCL developers'
```
This was using nccl v2.19.3-1.

> What topology does this machine have? NVLink or PCI-E?

NVLink

> Is it running on bare-metal or inside a container?

Bare metal

**Comment by simonbyrne** [comment]
One other point of interest: this only occurs with devices 0 and 1: any other 2 devices (or indeed, any other single device) works fine.

**Comment by simonbyrne** [comment]
Here is the output of `NCCL_TOPO_DUMP_FILE` (when running with 4 devices: it doesn't get written if the error occurs):
```xml
<system version="1">
  <cpu numaid="0" affinity="00000000,ffffffff,00000000,ffffffff" arch="x86_64" vendor="AuthenticAMD" familyid="175" modelid="1">
    <pci busid="0000:01:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x1000" subsystem_device="0xa096" link_speed="16.0 GT/s PCIe" link_width="16">
      <pci busid="0000:03:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x1000" subsystem_device="0xa096" link_speed="16.0 GT/s PCIe" link_width="16">
        <pci busid="0000:05:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x10de" subsystem_device="0x13b8" link_speed="16.0 GT/s PCIe" link_width="16">
          <pci busid="0000:07:00.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16">
            <gpu dev="0" sm="80" rank="0" gdr="1">
              <nvlink target="0000:d5:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d2:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d4:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d7:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d3:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d6:00.0" count="2" tclass="0x068000"/>
            </gpu>
          </pci>
        </pci>
        <pci busid="0000:08:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x10de" subsystem_device="0x13b8" link_speed="16.0 GT/s PCIe" link_width="16">
          <pci busid="0000:0a:00.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16">
            <gpu dev="1" sm="80" rank="1" gdr="1">
              <nvlink target="0000:d5:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d2:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d4:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d7:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d3:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d6:00.0" count="2" tclass="0x068000"/>
            </gpu>
          </pci>
        </pci>
      </pci>
    </pci>
    <pci busid="0000:2c:00.0" class="0x020000" vendor="0x8086" device="0x15ff" subsystem_vendor="0x15d9" subsystem_device="0x1c0c" link_speed="8.0 GT/s PCIe" link_width="8">
      <nic>
        <net name="enp44s0f0" dev="1" speed="10000" port="0" latency="0.000000" guid="0x1" maxconn="65536" gdr="0"/>
      </nic>
    </pci>
    <pci busid="0000:3e:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x1000" subsystem_device="0xa096" link_speed="16.0 GT/s PCIe" link_width="16">
      <pci busid="0000:40:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x1000" subsystem_device="0xa096" link_speed="16.0 GT/s PCIe" link_width="16">
        <pci busid="0000:42:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x10de" subsystem_device="0x13b8" link_speed="16.0 GT/s PCIe" link_width="16">
          <pci busid="0000:44:00.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16">
            <gpu dev="2" sm="80" rank="2" gdr="1">
              <nvlink target="0000:d5:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d2:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d4:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d7:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d3:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d6:00.0" count="2" tclass="0x068000"/>
            </gpu>
          </pci>
        </pci>
      </pci>
      <pci busid="0000:46:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x1000" subsystem_device="0xa096" link_speed="16.0 GT/s PCIe" link_width="16">
        <pci busid="0000:48:00.0" class="0x060400" vendor="0x1000" device="0xc010" subsystem_vendor="0x10de" subsystem_device="0x13b8" link_speed="16.0 GT/s PCIe" link_width="16">
          <pci busid="0000:4a:00.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16.0 GT/s PCIe" link_width="16">
            <gpu dev="3" sm="80" rank="3" gdr="1">
              <nvlink target="0000:d5:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d2:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d4:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d7:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d3:00.0" count="2" tclass="0x068000"/>
              <nvlink target="0000:d6:00.0" count="2" tclass="0x068000"/>
            </gpu>
          </pci>
        </pci>
      </pci>
    </pci>
    <nic>
      <net name="enp46s0f3u1u2c2" dev="0" speed="10000" port="0" latency="0.000000" guid="0x0" maxconn="65536" gdr="0"/>
    </nic>
  </cpu>
</system>
```

**Comment by AddyLaddy** [comment]
Thanks, it's likely that this is the cause of the failure: 

```
clima:810632:810657 [0] NCCL INFO Topology detection: network path /sys/devices/pci0000:2b/0000:2b:08.1/0000:2e:00.3/usb1/1-1/1-1.2/1-1.2:2.0 is not a PCI device (usb). Attaching to first CPU
clima:810632:810657 [0] graph/xml.h:85 NCCL WARN Attribute busid of node nic not found
```

But I am puzzled as to what caused that and why it's only an issue if you use fewer than 4 GPUs?
Can you try and re-inject that TOPO file with `NCCL_TOPO_FILE=topo.xml` when running on fewer than 4 GPUs to see if that's a WAR?

**Comment by simonbyrne** [comment]
> Can you try and re-inject that TOPO file with `NCCL_TOPO_FILE=topo.xml` when running on fewer than 4 GPUs to see if that's a WAR?

Yes, that worked.

**Comment by sjeaugey** [comment]
Hi @simonbyrne,

Could you try to apply this patch and see if it fixes the issue?
```
diff --git a/src/graph/xml.cc b/src/graph/xml.cc
index 47fda1f85..c89333548 100644
--- a/src/graph/xml.cc
+++ b/src/graph/xml.cc
@@ -586,8 +586,8 @@ ncclResult_t ncclTopoGetXmlFromSys(struct ncclXmlNode* pciNode, struct ncclXml*
     NCCLCHECK(xmlGetAttrStr(pciNode, "busid", &newBusId));
     for (int s=0; s<parent->nSubs; s++) {
       const char* busId;
-      NCCLCHECK(xmlGetAttrStr(parent->subs[s], "busid", &busId));
-      if (strcmp(newBusId, busId) < 0) { subIndex = s; break; }
+      NCCLCHECK(xmlGetAttr(parent->subs[s], "busid", &busId));
+      if (busId != NULL && strcmp(newBusId, busId) < 0) { subIndex = s; break; }
     }
     for (int s = parent->nSubs; s > subIndex; s--) parent->subs[s] = parent->subs[s-1];
     parent->subs[subIndex] = pciNode;
```

**Comment by simonbyrne** [comment]
@sjeaugey thank you, that resolves the issue.
