### ISSUE TITLE
NCCL alltoall_perf hangs in a cluster of 16 8*H100 gpus nodes

### ISSUE THREAD

**Issue by PhdShi** [NVIDIA/nccl#1134]
In a cluster of 16 H100 nodes, I have tested alltoall_perf with nccl version 2.19.1 2.19.3 2.19.4, and found that it will hang at communicator initialization. This phenomenon does not occur when the cluster size is less than 8 or the cluster nodes are H800. The following is my run command: 
```
mpirun --allow-run-as-root --hostfile iplist-16 -np 128 --mca btl_openarn_no_device_params_found 0 --mca btl_tcp_if_include bond0 --map-by ppr:8:node -x NCCL_IB_GID_INDEX=3 -x NCCL_IB_QPS_PER_CONNECTION=2 -x NCCL_IB_HCA=mlx5_bond -x NCCL_IB_SL=5 -x NCCL_IB_TC=136 -x NCCL_DEBUG=INFO -x NCCL_IB_TIMEOUT=22 -x NCCL_SOCKET_IFNAME=bond0 -x NCCL_NET_PLUGIN=none -x NCCL_MIN_NCHANNELS=4 -x NCCL_NVLS_ENABLE=1 -x LD_PRELOAD=/home/nccl2.19.1/libnccl.so.2 -x NCCL_CUMEM_ENABLE=1 /usr/local/bin/alltoall_perf -b 4K -e 4M -f 2 -g 1 -n 300
```
It will hang when logging at this moment: 
![image](https://github.com/NVIDIA/nccl/assets/109151574/6aa267d9-dfef-4204-9026-f3ec269b75fd)
When I used nccl 2.18.6, there are no problems. I noticed that there were 6,000 lines of code changes in nccl2.19.1, and I have no idea about this hang issue.

**Comment by PhdShi** [comment]
I noticed that there was an [issue1116](https://github.com/NVIDIA/nccl/issues/1116)  with the same problem that was solved by closing NCCL_CUMEM_ENABLE. I tried it and it worked for me too.
