### ISSUE TITLE
nccl uct_md_mem_reg(address=(nil) length=140222665224192): invalid parameters

### ISSUE THREAD

**Issue by victorserbu2709** [NVIDIA/nccl#1175]
Hello.
i tried running nccl-tests/all_reduce_perf on a 2 nodes each with 8 x(h100+connectx7).
it works when ibext is used but I receive following errors when trying to run with ucx
```
h100-ubuntu:177755:177867 [5] NCCL INFO Channel 13/0 : 13[5] -> 12[4] via P2P/CUMEM
h100-ubuntu:177754:177865 [4] NCCL INFO Channel 08/0 : 12[4] -> 11[3] via P2P/CUMEM
h100-ubuntu:177753:177862 [3] NCCL INFO Channel 07/0 : 11[3] -> 10[2] via P2P/CUMEM
[1707768585.533429] [compute-8:1458299:0]          uct_md.c:560  UCX  ERROR uct_md_mem_reg(address=(nil) length=140222665224192): invalid parameters
[1707768585.533445] [compute-8:1458299:0]          ucp_mm.c:63   UCX  ERROR failed to register address (nil) (cuda) length 140222665224192 on md[1]=cuda_ipc: Invalid parameter (md supports: cuda)

compute-8:1458299:1458532 [3] ucx_plugin.c:539 NCCL WARN Failed: UCX error ucx_plugin.c:539 '-5' Invalid parameter

compute-8:1458299:1458532 [3] NCCL INFO transport/net.cc:772 -> 3
h100-ubuntu:177754:177865 [4] NCCL INFO Channel 09/0 : 12[4] -> 11[3] via P2P/CUMEM
h100-ubuntu:177753:177862 [3] NCCL INFO Channel 08/0 : 11[3] -> 10[2] via P2P/CUMEM
h100-ubuntu:177754:177865 [4] NCCL INFO Channel 10/0 : 12[4] -> 11[3] via P2P/CUMEM
[1707768585.534168] [compute-8:1458299:0]          uct_md.c:560  UCX  ERROR uct_md_mem_reg(address=(nil) length=140222665224192): invalid parameters
[1707768585.534176] [compute-8:1458299:0]          ucp_mm.c:63   UCX  ERROR failed to register address (nil) (cuda) length 140222665224192 on md[2]=mlx5_0: Invalid parameter (md supports: host|cuda)

compute-8:1458299:1458532 [3] ucx_plugin.c:539 NCCL WARN Failed: UCX error ucx_plugin.c:539 '-5' Invalid parameter

compute-8:1458299:1458532 [3] NCCL INFO transport/net.cc:772 -> 3
h100-ubuntu:177753:177862 [3] NCCL INFO Channel 09/0 : 11[3] -> 10[2] via P2P/CUMEM
[1707768585.534218] [compute-8:1458300:0]          uct_md.c:560  UCX  ERROR uct_md_mem_reg(address=(nil) length=140516171005952): invalid parameters
[1707768585.534248] [compute-8:1458300:0]          ucp_mm.c:63   UCX  ERROR failed to register address (nil) (cuda) length 140516171005952 on md[1]=cuda_ipc: Invalid parameter (md supports: cuda)

compute-8:1458300:1458525 [4] ucx_plugin.c:539 NCCL WARN Failed: UCX error ucx_plugin.c:539 '-5' Invalid parameter

compute-8:1458300:1458525 [4] NCCL INFO transport/net.cc:772 -> 3
h100-ubuntu:177755:177867 [5] NCCL INFO Channel 14/0 : 13[5] -> 12[4] via P2P/CUMEM
h100-ubuntu:177754:177865 [4] NCCL INFO Channel 12/0 : 12[4] -> 11[3] via P2P/CUMEM
[1707768585.534340] [compute-8:1458298:0]          uct_md.c:560  UCX  ERROR uct_md_mem_reg(address=(nil) length=139998757425152): invalid parameters
[1707768585.534366] [compute-8:1458298:0]          ucp_mm.c:63   UCX  ERROR failed to register address (nil) (cuda) length 139998757425152 on md[1]=cuda_ipc: Invalid parameter (md supports: cuda)

compute-8:1458298:1458530 [2] ucx_plugin.c:539 NCCL WARN Failed: UCX error ucx_plugin.c:539 '-5' Invalid parameter

compute-8:1458298:1458530 [2] NCCL INFO transport/net.cc:772 -> 3
h100-ubuntu:177755:177867 [5] NCCL INFO Channel 15/0 : 13[5] -> 12[4] via P2P/CUMEM
h100-ubuntu:177753:177862 [3] NCCL INFO Channel 11/0 : 11[3] -> 10[2] via P2P/CUMEM
````

```
nvidia  Driver Version: 545.23.08    CUDA Version: 12.3
nccl 2.19.3-1+cuda12.3
```
Run command
```
#!/bin/bash

. /home/victors/hpcx-v2.17.1-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64/hpcx-init.sh
hpcx_load

mpirun  --allow-run-as-root -np 16 -N 8 -x NCCL_DEBUG=INFO -hostfile hostfile.8+vm  \
        --bind-to none -mca btl tcp,self -mca coll_hcoll_enable 0 \
        -x NCCL_IB_AR_THRESHOLD=0 -x NCCL_IB_PCI_RELAXED_ORDERING=1 \
        -x NCCL_IB_SPLIT_DATA_ON_QPS=0 -x NCCL_IB_QPS_PER_CONNECTION=2 -x CUDA_DEVICE_ORDER=PCI_BUS_ID  \
        -x PATH -x LD_LIBRARY_PATH \
        --mca oob_tcp_if_include 10.150.255.0/24 --mca btl_tcp_if_include 10.150.255.0/24 \
        -x NCCL_PLUGIN_P2P=ucx -x NCCL_UCX_RNDV_THRESH=0 -x NCCL_UCX_RNDV_SCHEME=get_zcopy -x NCCL_UCX_TLS=dc,cuda_copy,cuda_ipc \
        /home/victors/nccl-tests/build/all_reduce_perf -b 8 -e 2G -f 2 -t 1 -g 1 -c 1 -n 100
```

These are nccl debug logs:
[nccl_test_ucx.log](https://github.com/NVIDIA/nccl/files/14250579/nccl_test_ucx.log)
[nccl_test_ibext.log](https://github.com/NVIDIA/nccl/files/14250580/nccl_test_ibext.log)

I would like to try ucx because i saw on https://docs.crusoecloud.com/networking/infiniband/validating-infiniband-performance that busbw should be ~ 361GB/s while in my setup with ibext nccl gave following results
```
#
#                                                              out-of-place                       in-place
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2     float     sum      -1    27.18    0.00    0.00      0    26.42    0.00    0.00      0
          16             4     float     sum      -1    26.80    0.00    0.00      0    27.03    0.00    0.00      0
          32             8     float     sum      -1    26.98    0.00    0.00      0    27.01    0.00    0.00      0
          64            16     float     sum      -1    27.35    0.00    0.00      0    27.33    0.00    0.00      0
         128            32     float     sum      -1    27.24    0.00    0.01      0    27.04    0.00    0.01      0
         256            64     float     sum      -1    34.18    0.01    0.01      0    27.18    0.01    0.02      0
         512           128     float     sum      -1    29.71    0.02    0.03      0    27.95    0.02    0.03      0
        1024           256     float     sum      -1    30.80    0.03    0.06      0    29.39    0.03    0.07      0
        2048           512     float     sum      -1    31.21    0.07    0.12      0    30.86    0.07    0.12      0
        4096          1024     float     sum      -1    32.84    0.12    0.23      0    32.52    0.13    0.24      0
        8192          2048     float     sum      -1    34.26    0.24    0.45      0    33.33    0.25    0.46      0
       16384          4096     float     sum      -1    35.10    0.47    0.88      0    35.03    0.47    0.88      0
       32768          8192     float     sum      -1    35.89    0.91    1.71      0    35.56    0.92    1.73      0
       65536         16384     float     sum      -1    37.44    1.75    3.28      0    36.22    1.81    3.39      0
      131072         32768     float     sum      -1    47.39    2.77    5.19      0    47.40    2.77    5.18      0
      262144         65536     float     sum      -1    143.1    1.83    3.43      0    86.13    3.04    5.71      0
      524288        131072     float     sum      -1    90.07    5.82   10.91      0    88.45    5.93   11.11      0
     1048576        262144     float     sum      -1    90.01   11.65   21.84      0    90.09   11.64   21.82      0
     2097152        524288     float     sum      -1    102.5   20.47   38.37      0    93.22   22.50   42.18      0
     4194304       1048576     float     sum      -1    103.7   40.46   75.86      0    104.4   40.17   75.32      0
     8388608       2097152     float     sum      -1    147.3   56.95  106.77      0    149.7   56.04  105.08      0
    16777216       4194304     float     sum      -1    200.4   83.72  156.98      0    200.5   83.67  156.88      0
    33554432       8388608     float     sum      -1    317.7  105.63  198.06      0    320.0  104.84  196.58      0
    67108864      16777216     float     sum      -1    586.1  114.51  214.70      0    586.3  114.45  214.60      0
   134217728      33554432     float     sum      -1   1022.6  131.25  246.10      0   1036.2  129.53  242.88      0
   268435456      67108864     float     sum      -1   1874.4  143.21  268.52      0   1879.8  142.80  267.74      0
   536870912     134217728     float     sum      -1   3534.8  151.88  284.78      0   3526.6  152.24  285.44      0
  1073741824     268435456     float     sum      -1   6388.0  168.09  315.16      0   6259.6  171.53  321.63      0
  2147483648     536870912     float     sum      -1    11938  179.89  337.30      0    12056  178.13  334.00      0
```

Thanks,
Victor

**Comment by victorserbu2709** [comment]
I have tested today with hpcx-v2.18-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64 and it works with a command like 

{code}
mpirun  --allow-run-as-root -np 16 -N 8 -x NCCL_DEBUG=INFO -hostfile hostfile  \
        --bind-to none -mca btl tcp,self -mca coll_hcoll_enable 0 \
        -x NCCL_IB_AR_THRESHOLD=0 -x NCCL_IB_PCI_RELAXED_ORDERING=1 \
        -x NCCL_IB_SPLIT_DATA_ON_QPS=0 -x NCCL_IB_QPS_PER_CONNECTION=2 -x CUDA_DEVICE_ORDER=PCI_BUS_ID  \
        -x PATH -x LD_LIBRARY_PATH \
        -x NCCL_PLUGIN_P2P=ucx -x NCCL_UCX_RNDV_THRESH=0 -x NCCL_UCX_RNDV_SCHEME=get_zcopy \
        --mca oob_tcp_if_include 10.150.255.0/24 --mca btl_tcp_if_include 10.150.255.0/24 \
        /home/hpc/nccl-tests/build/all_reduce_perf -b 8 -e 2G -f 2 -t 1 -g 1 -c 1 -n 100
{code}
