### ISSUE TITLE
NCCL allreduce is timing out

### ISSUE THREAD

**Issue by genesis-jamin** [NVIDIA/nccl#1193]
Hello, I'm running into what appears to be a NCCL issue when doing multi-node training, and I was hoping to get some guidance on how to go about debugging this.

My machine setup:
* I'm using Google Cloud. The machine type is `g2-standard-96` which has 8 L4 GPUs. I have 16 machines which makes it 128 GPUs total.
* I am using NCCL FastSocket.
* I'm using Ray and Pytorch Lightning to do DDP.
* My NCCL version is 2.14.3.

For some details on the error:
* We're training a graph-based diffusion model.
* We noticed that after we switched to a new dataset, we start to reliably hit the NCCL timeout error below. It doesn't always happen at the same epoch, but almost always happens between 20 to 40 epochs.
  * This new dataset is a few orders of magnitude larger than what we have been previously training on.
* The timeout always occurs between the end of an epoch and the beginning of the next one.
  * The timeout occurs after we have saved our checkpoint to Google Cloud Storage, so I don't think it's related to HDFS hanging.
* I ran the code with `NCCL_DEBUG=INFO` and it printed out some of the things below. My observations:
  * From my understanding, `datatype 2` seems to be a NCCL system error ([docs](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#c.ncclSystemError)). Is there a way I can get more information on what the error is?
  * It seems like the ranks that are doing the all-reduce with buffer size 335 are timing out -- I say this because the number of ranks doing this and the number of ranks timing out are the same.
  * I actually see the `count 335 datatype 2` message every epoch, but the code just keeps running usually (until it errors like below).
  * I tried setting `NCCL_P2P_DISABLE=1` but that didn't fix things.
* Another thing that seems suspect is that at the beginning of my script, I see this printed (for all devices): `NCCL INFO Topology detection : could not read /sys/devices/pci0000:80/0000:80:03.0/../max_link_width, ignoring`.

Could I get some guidance on how to go about debugging things? I'm happy to run any commands / analyses required, just a bit out of my depth here.

```
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 139b sendbuff 0x796ef8600000 recvbuff 0x796ef8600000 count 5253370 datatype 7 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 139b sendbuff 0x7db678600000 recvbuff 0x7db678600000 count 5253370 datatype 7 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 139c sendbuff 0x796f8c400000 recvbuff 0x796f8c400000 count 7382228 datatype 7 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 139b sendbuff 0x78cfb8600000 recvbuff 0x78cfb8600000 count 5253370 datatype 7 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 139c sendbuff 0x7db714400000 recvbuff 0x7db714400000 count 7382228 datatype 7 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 139b sendbuff 0x7fb490600000 recvbuff 0x7fb490600000 count 5253370 datatype 7 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 139b sendbuff 0x78fb98600000 recvbuff 0x78fb98600000 count 5253370 datatype 7 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 139c sendbuff 0x78d054400000 recvbuff 0x78d054400000 count 7382228 datatype 7 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 139c sendbuff 0x7fb52a400000 recvbuff 0x7fb52a400000 count 7382228 datatype 7 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 139c sendbuff 0x78fc2c400000 recvbuff 0x78fc2c400000 count 7382228 datatype 7 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 139d sendbuff 0x796f8e200000 recvbuff 0x796f8e200000 count 7382228 datatype 7 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 139d sendbuff 0x7db716200000 recvbuff 0x7db716200000 count 7382228 datatype 7 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 139d sendbuff 0x78fc2e200000 recvbuff 0x78fc2e200000 count 7382228 datatype 7 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 139d sendbuff 0x78d056200000 recvbuff 0x78d056200000 count 7382228 datatype 7 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 139d sendbuff 0x7fb52c200000 recvbuff 0x7fb52c200000 count 7382228 datatype 7 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 139e sendbuff 0x796eee000000 recvbuff 0x796eee000000 count 7066572 datatype 7 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 139e sendbuff 0x7fb486000000 recvbuff 0x7fb486000000 count 7066572 datatype 7 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 139e sendbuff 0x7db66e000000 recvbuff 0x7db66e000000 count 7066572 datatype 7 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 139f sendbuff 0x796eec000000 recvbuff 0x796eec000000 count 6961734 datatype 7 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 13a0 sendbuff 0x796f0f7ce200 recvbuff 0x796f0f7ce200 count 554400 datatype 7 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=619, ip=10.72.2.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-hzhzd:619:19049 [3] NCCL INFO AllReduce: opCount 13a1 sendbuff 0x796f05f47800 recvbuff 0x796f05f47800 count 335 datatype 2 op 0 root 0 comm 0x796f1a16eff0 [nranks=128] stream 0x796fe3e3eb70
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 139e sendbuff 0x78fb8e000000 recvbuff 0x78fb8e000000 count 7066572 datatype 7 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 139e sendbuff 0x78cfae000000 recvbuff 0x78cfae000000 count 7066572 datatype 7 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 139f sendbuff 0x78cfac000000 recvbuff 0x78cfac000000 count 6961734 datatype 7 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 13a0 sendbuff 0x78cfcf7ce200 recvbuff 0x78cfcf7ce200 count 554400 datatype 7 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=615, ip=10.72.7.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-fqztx:615:18953 [2] NCCL INFO AllReduce: opCount 13a1 sendbuff 0x78cfc5f47800 recvbuff 0x78cfc5f47800 count 335 datatype 2 op 0 root 0 comm 0x78cfda045840 [nranks=128] stream 0x78d07125e5e0
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 139f sendbuff 0x7fb484000000 recvbuff 0x7fb484000000 count 6961734 datatype 7 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 13a0 sendbuff 0x7fb4a77ce200 recvbuff 0x7fb4a77ce200 count 554400 datatype 7 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:41192 [5] NCCL INFO AllReduce: opCount 13a1 sendbuff 0x7fb49df47800 recvbuff 0x7fb49df47800 count 335 datatype 2 op 0 root 0 comm 0x7fb4b3e6ee80 [nranks=128] stream 0x7fb54524a0f0
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 139f sendbuff 0x7db66c000000 recvbuff 0x7db66c000000 count 6961734 datatype 7 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 13a0 sendbuff 0x7db68f7ce200 recvbuff 0x7db68f7ce200 count 554400 datatype 7 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=619, ip=10.72.6.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-482hg:619:18882 [4] NCCL INFO AllReduce: opCount 13a1 sendbuff 0x7db685f47800 recvbuff 0x7db685f47800 count 335 datatype 2 op 0 root 0 comm 0x7db69b86fe10 [nranks=128] stream 0x7db69b86fa40
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 139f sendbuff 0x78fb8c000000 recvbuff 0x78fb8c000000 count 6961734 datatype 7 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 13a0 sendbuff 0x78fbaf7ce200 recvbuff 0x78fbaf7ce200 count 554400 datatype 7 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=19799, ip=10.72.0.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-xc6s4:19799:38219 [3] NCCL INFO AllReduce: opCount 13a1 sendbuff 0x78fba5f47800 recvbuff 0x78fba5f47800 count 335 datatype 2 op 0 root 0 comm 0x78fbbf9d1bb0 [nranks=128] stream 0x78fc4917d570
(RayTrainWorker pid=22754, ip=10.72.12.6) [E ProcessGroupNCCL.cpp:821] [Rank 21] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5020, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808397 milliseconds before timing out.
(RayTrainWorker pid=19799, ip=10.72.0.6) [E ProcessGroupNCCL.cpp:821] [Rank 27] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5020, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808458 milliseconds before timing out.
(RayTrainWorker pid=619, ip=10.72.2.6) [E ProcessGroupNCCL.cpp:821] [Rank 43] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5020, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808814 milliseconds before timing out.
(RayTrainWorker pid=619, ip=10.72.6.6) [E ProcessGroupNCCL.cpp:821] [Rank 108] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5020, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808805 milliseconds before timing out.
(RayTrainWorker pid=615, ip=10.72.7.6) [E ProcessGroupNCCL.cpp:821] [Rank 122] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5020, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808822 milliseconds before timing out.
(RayTrainWorker pid=22754, ip=10.72.12.6) r24-02-22-23-29-0066-raycluster-lv52c-worker-l4-8-srrss:22754:23812 [0] NCCL INFO comm 0x7fb4b3e6ee80 rank 21 nranks 128 cudaDev 5 busId 80010 - Abort COMPLETE
(RayTrainWorker pid=22754, ip=10.72.12.6) [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
(RayTrainWorker pid=22754, ip=10.72.12.6) [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
(RayTrainWorker pid=22754, ip=10.72.12.6) [2024-02-23 01:10:19,453 E 22754 23813] logging.cc:97: Unhandled exception: St13runtime_error. what(): [Rank 21] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5020, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808397 milliseconds before timing out.
(RayTrainWorker pid=22754, ip=10.72.12.6) [2024-02-23 01:10:19,473 E 22754 23813] logging.cc:104: Stack trace:
(RayTrainWorker pid=22754, ip=10.72.12.6)  /root/miniconda/envs/main-env/lib/python3.10/site-packages/ray/_raylet.so(+0xfebb5a) [0x7fd52ba38b5a] ray::operator<<()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/lib/python3.10/site-packages/ray/_raylet.so(+0xfee298) [0x7fd52ba3b298] ray::TerminateHandler()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/bin/../lib/libstdc++.so.6(+0xb643c) [0x7fd52a92043c] __cxxabiv1::__terminate()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/bin/../lib/libstdc++.so.6(+0xb648e) [0x7fd52a92048e] __cxxabiv1::__unexpected()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/bin/../lib/libstdc++.so.6(+0xb6435) [0x7fd52a920435] __cxxabiv1::__terminate()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so(_ZN4c10d16ProcessGroupNCCL8WorkNCCL15handleNCCLGuardENS_17ErrorHandlingModeE+0x278) [0x7fb666750298] c10d::ProcessGroupNCCL::WorkNCCL::handleNCCLGuard()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so(_ZN4c10d16ProcessGroupNCCL15workCleanupLoopEv+0x19f) [0x7fb6667542af] c10d::ProcessGroupNCCL::workCleanupLoop()
(RayTrainWorker pid=22754, ip=10.72.12.6) /root/miniconda/envs/main-env/bin/../lib/libstdc++.so.6(+0xd3e95) [0x7fd52a93de95] execute_native_thread_routine
(RayTrainWorker pid=22754, ip=10.72.12.6) /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7fd52ca6cac3]
(RayTrainWorker pid=22754, ip=10.72.12.6) /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7fd52cafe850]
(RayTrainWorker pid=22754, ip=10.72.12.6)
(RayTrainWorker pid=22754, ip=10.72.12.6) *** SIGABRT received at time=1708650619 on cpu 32 ***
(RayTrainWorker pid=22754, ip=10.72.12.6) PC: @     0x7fd52ca6e9fc  (unknown)  pthread_kill
(RayTrainWorker pid=22754, ip=10.72.12.6)     @     0x7fd52ca1a520  (unknown)  (unknown)
(RayTrainWorker pid=22754, ip=10.72.12.6) [2024-02-23 01:10:19,473 E 22754 23813] logging.cc:361: *** SIGABRT received at time=1708650619 on cpu 32 ***
(RayTrainWorker pid=22754, ip=10.72.12.6) [2024-02-23 01:10:19,473 E 22754 23813] logging.cc:361: PC: @     0x7fd52ca6e9fc  (unknown)  pthread_kill
(RayTrainWorker pid=22754, ip=10.72.12.6) [2024-02-23 01:10:19,473 E 22754 23813] logging.cc:361:     @     0x7fd52ca1a520  (unknown)  (unknown)
(RayTrainWorker pid=22754, ip=10.72.12.6) Fatal Python error: Aborted
```

**Comment by genesis-jamin** [comment]
Closing because this was not NCCL-related. The issue was that the library we were using for data loading (Ray Data) had some concurrency issues that were causing deadlocks with gradient syncs.
