### ISSUE TITLE
Report of increased memory overhead during cudagraph capture with nccl >= 2.19

### ISSUE THREAD

**Issue by youkaichao** [NVIDIA/nccl#1234]
Hi, I would like to report a memory issue with `nccl`. A reproducible example is attached below:

In a gcp g2-standard-24 instance (with 2 L4 GPUs):

```shell
docker pull us-central1-docker.pkg.dev/vllm-405802/vllm-ci-test-repo/vllm-test:a3c2340ae36ce8ee782691d30111377eaf7ae6ce
docker run --gpus all --shm-size=2g -it us-central1-docker.pkg.dev/vllm-405802/vllm-ci-test-repo/vllm-test:a3c2340ae36ce8ee782691d30111377eaf7ae6ce -- /bin/bash

# inside docker
cd /vllm-workspace/tests/distributed
export NCCL_DEBUG=TRACE
TEST_DIST_MODEL=meta-llama/Llama-2-7b-hf pytest -v -s --forked test_basic_distributed_correctness.py
```

Note that the code manually links against a pre-downloaded `nccl==2.18.3`.  There is also a `nccl==2.19.3` available inside the image, the path is `/usr/local/lib/python3.10/dist-packages/nvidia/nccl/lib/libnccl.so.2` . 

By adding the following line in `/vllm-workspace/vllm/model_executor/parallel_utils/pynccl.py`, before `nccl = ctypes.CDLL(so_file)`:

```python
so_file = "/usr/local/lib/python3.10/dist-packages/nvidia/nccl/lib/libnccl.so.2"
```

We can force the program to use nccl 2.19.3, and we will get an OOM error.

The background:

In distributed inference, https://github.com/vllm-project/vllm uses nccl together with cudagraph. We capture about 30 graphs with different batch sizes. The memory overhead when we use `pytorch 2.1.2` (with `nccl==2.18.3`) is nearly zero (about 10MB per graph, and sometimes is zero); however, when we upgrade to `pytorch 2.2.0` (with `nccl==2.19.3`), the memory overhead is more than 100MB per graph.

We spent more than a week (to be honest, more time than one would feel comfortable with) to investigate the issue. We used to think it should be related with pytorch, but finally we find the problem comes from the `nccl` library.

For more code on measuring the memory overhead, please check https://github.com/vllm-project/vllm/pull/3442#issuecomment-2002131611 .

It would be very helpful if the `nccl` team can point our the root cause of the memory overhead, and potential knobs to control it (e.g. via some environment variables). The above problem happens for both `nccl==2.19.3` and `nccl==2.20.5` .

Thank you for your time.

**Comment by sjeaugey** [comment]
Thanks for the report. @jbachan did we change something in 2.19 regarding the way we store graph-related data for NCCL?

@youkaichao how many graphs do you expect to create? A power of ten is ok, it doesn't have to be precise; in my mind apps would create a couple of graphs (less than 10 for sure) so even 100MB per graph doesn't seem like a big problem. If the expectation is that we should allow for tens or hundred of graphs, it could influence how we fix the issue and design things in the future.

**Comment by youkaichao** [comment]
> how many graphs do you expect to create?

About 30, each for a different batch size (8, 16, 24, ..., 256).

Technically we capture the graph with large batchsize first, followed by smaller batchsize. We find cudagraph with smaller batchsize can share the memory buffer of larger batchsize. So even with more than 30 cudagraph, the memory overhead prior to nccl 2.19 is low.

**Comment by youkaichao** [comment]
@sjeaugey hi, any update on this? 👀

**Comment by youkaichao** [comment]
@sjeaugey hi, any update on this? 👀

**Comment by youkaichao** [comment]
@sjeaugey we finally find this problem is related with the virtual memory usage, and solve it in https://github.com/vllm-project/vllm/pull/5091 .

It would be great if you can share why virtual memory is allocated during graph capture, and what it is used for, what's the performance impact of turning it off 🙏

**Comment by sjeaugey** [comment]
Thanks for the feedback. I'm not sure I understand how you solved it though. Was it a proper fix or a workaround?

From what I understand, you're saying that enabling CUMEM increases the memory usage when using CUDA graphs. Is that accurate? Did you confirm the problem went away with `NCCL_CUMEM_ENABLE=0`?

**Comment by youkaichao** [comment]
Yes, the fix is to set `NCCL_CUMEM_ENABLE=0` .

**Comment by youkaichao** [comment]
I would say this is only a workaround. I don't know why NCCL costs more memory with cudagraph when `NCCL_CUMEM_ENABLE` is used by default in nccl 2.19 .

**Comment by youkaichao** [comment]
here is a minimal reproducible example:

```python
import torch
import torch.distributed as dist
from contextlib import contextmanager

@contextmanager
def graph_capture(pool=None, stream=None, capture_error_mode: str = "global", dump_path=None):
    g = torch.cuda.CUDAGraph()
    if dump_path is not None:
        g.enable_debug_mode()
    with torch.cuda.graph(cuda_graph=g, pool=pool, stream=stream, capture_error_mode=capture_error_mode):
        yield g
    if dump_path is not None:
        g.debug_dump(dump_path)

dist.init_process_group(backend="gloo", init_method="env://")
rank = dist.get_rank()
torch.cuda.set_device(rank)

from vllm.distributed.device_communicators.pynccl import PyNcclCommunicator

pynccl = PyNcclCommunicator(group=dist.group.WORLD, device=rank)
pynccl.disabled = False

MAX_BATCHSIZE = 4

# Placeholder input used for capture
static_a = torch.zeros((MAX_BATCHSIZE, 1024), device="cuda")

def compute(batchsize):
    pynccl.all_reduce(static_a[:batchsize], stream=torch.cuda.current_stream())

# Warmup before capture
s = torch.cuda.Stream()
s.wait_stream(torch.cuda.current_stream())
with torch.cuda.stream(s):
    for i in range(1, MAX_BATCHSIZE + 1):
        compute(i)
torch.cuda.current_stream().wait_stream(s)

def report_memory(prefix):
    free, total = torch.cuda.mem_get_info()
    used = total - free
    print(f"{prefix}: Used: {used / 1024 / 1024} MB, Free: {free / 1024 / 1024} MB, Total: {total / 1024 / 1024} MB")

# Captures the graph
# To allow capture, automatically sets a side stream as the current stream in the context
report_memory("Before capture")
graphs = [0] # 0 is a placeholder for 0 batchsize
memory_pool = None
for i in range(1, MAX_BATCHSIZE + 1):
    with graph_capture(pool=memory_pool) as g:
        compute(i)
    graphs.append(g)
    memory_pool = g.pool()
    report_memory(f"After capture batchsize {i}")
# Run the graph
static_a[:2] += 1
graphs[2].replay()
torch.cuda.current_stream().synchronize()
print(static_a[:2])
```

I call allreduce on a static buffer, and capture only this allreduce operation in cudagraph. Ideally it should not cost any memory.

When I run it with default setting:

```text
INFO 05-30 18:33:53 utils.py:619] Found nccl from library libnccl.so.2
INFO 05-30 18:33:53 pynccl.py:65] vLLM is using nccl==2.20.5
INFO 05-30 18:33:53 utils.py:619] Found nccl from library libnccl.so.2
INFO 05-30 18:33:53 pynccl.py:65] vLLM is using nccl==2.20.5
Before capture: Used: 1373.375 MB, Free: 79677.25 MB, Total: 81050.625 MBBefore capture: Used: 1373.375 MB, Free: 79677.25 MB, Total: 81050.625 MB

After capture batchsize 1: Used: 1379.375 MB, Free: 79671.25 MB, Total: 81050.625 MBAfter capture batchsize 1: Used: 1379.375 MB, Free: 79671.25 MB, Total: 81050.625 MB

After capture batchsize 2: Used: 1381.375 MB, Free: 79669.25 MB, Total: 81050.625 MB
After capture batchsize 2: Used: 1381.375 MB, Free: 79669.25 MB, Total: 81050.625 MB
After capture batchsize 3: Used: 1383.375 MB, Free: 79667.25 MB, Total: 81050.625 MB
After capture batchsize 3: Used: 1383.375 MB, Free: 79667.25 MB, Total: 81050.625 MB
After capture batchsize 4: Used: 1385.375 MB, Free: 79665.25 MB, Total: 81050.625 MB
After capture batchsize 4: Used: 1385.375 MB, Free: 79665.25 MB, Total: 81050.625 MB
tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]], device='cuda:0')
tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]], device='cuda:1')
```

every cudagraph takes 2 MB memory.

If I run it with `export NCCL_CUMEM_ENABLE=0` : 

```text
INFO 05-30 18:30:52 utils.py:619] Found nccl from library libnccl.so.2
INFO 05-30 18:30:52 pynccl.py:65] vLLM is using nccl==2.20.5
INFO 05-30 18:30:52 utils.py:619] Found nccl from library libnccl.so.2
INFO 05-30 18:30:52 pynccl.py:65] vLLM is using nccl==2.20.5
Before capture: Used: 1181.375 MB, Free: 79869.25 MB, Total: 81050.625 MBBefore capture: Used: 1181.375 MB, Free: 79869.25 MB, Total: 81050.625 MB

After capture batchsize 1: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 1: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 2: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 2: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 3: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 3: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 4: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
After capture batchsize 4: Used: 1185.375 MB, Free: 79865.25 MB, Total: 81050.625 MB
tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]], device='cuda:1')
tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]], device='cuda:0')
```

the memory cost does not increase when I capture more graphs .

**Comment by youkaichao** [comment]
@sjeaugey I just tried nccl 2.21.5 now, the problem still exists. I doubt if this is because `cuMemCreate` is captured in cuda graph? I don't see any documentation explaining the behavior of `cuMemCreate` under graph capture and graph execution.

**Comment by sjeaugey** [comment]
For each CUDA graph capture, we allocate some memory on the GPU to store the information related to that persistent operation:
https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L1094

With CUMEM enabled, each allocation has to be aligned to the mem granularity, i.e. 2MB, so it is not surprising you see 2MB allocated per graph.

I guess we'd need to add a sub-allocator to the CUMEM code to avoid allocating 2MB for each CUDA graph. CC @AddyLaddy

**Comment by youkaichao** [comment]
how does cumem related api behave under graph capture? the [documentation](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html) does not say anything about it.

**Comment by davidthomas426** [comment]
Is this right?
* When using cumem ops, graph capture ignores it -- instead, by using the lower level cumem ops, you are directly allocating each time you run the cuda graph capture. I'm not sure how cuMemRelease is handled with graph capture though...
* When not using cumem ops, cudaMallocAsync and cudaFreeAsync are basically used instead. These use a stream-ordered suballocator with special behavior during graph capture, so that buffers can get reused for non-overlapping operations and are eligible to become part of the shared memory pool across cuda graphs.

@sjeaugey Could you clarify the behavior of cumem ops with cuda graphs, especially what happens when pointers are captured that are then released with cuMemRelease? Does this become a use-after-free? If not, how?

**Comment by galv** [comment]
@davidthomas426 

> When not using cumem ops, cudaMallocAsync and cudaFreeAsync are basically used instead

cudaMalloc rather than cudaMallocAsync is used based on my quick reading of the relevant code if NCCL_CUMEM_ENABLE=0. There is only one instance of cudaMallocAsync in NCCL 2.26.2-1 based on a quick grep.

> Could you clarify the behavior of cumem ops with cuda graphs, especially what happens when pointers are captured that are then released with cuMemRelease? Does this become a use-after-free?

Yes, that is a use-after-free. cuda graphs don't "own" the allocations they point to (actually, the CUDAGraph.cpp abstraction via pytorch does allow for a limited sense of ownership of allocations done via pytorch's caching allocator during stream capture via its "pool" concept, actually, but that is is besides the point and not a full solution because it doesn't prevent use-after-free of memory that a cuda graphs references but that was not allocated during that graph's stream capture). It's a bit hard to detect the use-after-free, of course, since invalid memory accesses are not guaranteed to crash. cudaUserObjects are designed to prevent use-after-free, but have not been very popular since their introduction: https://developer.nvidia.com/blog/exploring-the-new-features-of-cuda-11-3/#cuda_programming_model_enhancements

**Comment by kiskra-nvidia** [comment]
@youkaichao Could you retry your workload with NCCL versions more recent than 2.21.5, with CUMEM enabled? I've tried your reproducer from https://github.com/NVIDIA/nccl/issues/1234#issuecomment-2140614848 and, starting with NCCL 2.22.3, I'm not seeing the 2 MB per collective overhead:

```
INFO 08-12 11:27:11 utils.py:960] Found nccl from library libnccl.so.2
INFO 08-12 11:27:11 pynccl.py:69] vLLM is using nccl==2.22.3
INFO 08-12 11:27:11 utils.py:960] Found nccl from library libnccl.so.2
INFO 08-12 11:27:11 pynccl.py:69] vLLM is using nccl==2.22.3
Before capture: Used: 1327.0625 MB, Free: 79680.875 MB, Total: 81007.9375 MBBefore capture: Used: 1327.0625 MB, Free: 79680.875 MB, Total: 81007.9375 MB

After capture batchsize 1: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 1: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 2: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 2: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 3: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 3: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 4: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
After capture batchsize 4: Used: 1331.0625 MB, Free: 79676.875 MB, Total: 81007.9375 MB
tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]], device='cuda:0')
tensor([[2., 2., 2.,  ..., 2., 2., 2.],
        [2., 2., 2.,  ..., 2., 2., 2.]], device='cuda:1')
```

**Comment by youkaichao** [comment]
@kiskra-nvidia thanks for the information! Indeed I tried all the following NCCL versions, and starting with NCCL 2.22.3, I don't see the 2 MB per collective overhead.

Note that the latest vLLM comes with new pytorch, which does not work with old NCCL versions like NCCL 2.18 or 2.19. So I have to install old NCCL in another environment, and run the script as:

`NCCL_DEBUG=TRACE NCCL_DEBUG_SUBSYS=COLL,ALLOC VLLM_NCCL_SO_PATH=/data/youkaichao/uv_envs/tmp_nccl/lib/python3.12/site-packages/nvidia/nccl/lib/libnccl.so.2 NCCL_CUMEM_ENABLE=1 torchrun --nproc-per-node=2 test_nccl.py`

then I can see the memory allocation happens in this line:

https://github.com/NVIDIA/nccl/blob/ab2b89c4c339bd7f816fbc114a4b05d386b66290/src/enqueue.cc#L1094

The log shows:

```text
[1] NCCL INFO enqueue.cc:827 Cuda Alloc Size 1024 pointer 0x7fd243c00000
```

however, since `ncclCudaMalloc` will uses `cuMemCreate` when cumem is enabled, the memory allocation will be aligned to 2 MiB.

if i disable cumem by adding `NCCL_CUMEM_ENABLE=0`, then it calls `cudaMalloc` instead, which has some caching behavior internally (although it still has some memory overhead, the memory overhead is not aligned to 2 MiB, but in its original size, I document it here https://forums.developer.nvidia.com/t/cudamallocs-internal-caching-behavior-makes-cudamemgetinfo-inaccurate/342217 ). That's why we see 0 memory overhead when adding `NCCL_CUMEM_ENABLE=0`.

These lines are exactly changed in NCCL 2.22.3:

<img width="1378" height="361" alt="Image" src="https://github.com/user-attachments/assets/94085948-d6e3-4acd-b8e9-6756e583be91" />

but I don't see how the change affects the behavior.

In NCCL 2.22.3, I don't see memory allocation between graph captures, so I assume NCCL uses some memory pool without allocating the memory at every NCCL call? If that can be confirmed, then the problem is solved and we can close this issue.

**Comment by youkaichao** [comment]
close as we removed the env var override in https://github.com/vllm-project/vllm/pull/24141 . thanks for the support from nccl team @kiskra-nvidia @sjeaugey 🙏
