### ISSUE TITLE
LL128 communication protocol

### ISSUE THREAD

**Issue by tks2004** [NVIDIA/nccl#1261]
Though the System has NV4 links and A100, still ll128 communication protocol is not selected. After forcing to use ll128, though the allreduce_perf from nccl_tests runs with better performance, there is an error out of bounds: # Out of bounds values : 16 FAILED. This was run for 2MB message size. It runs fine with 1MB message using LL128

**Comment by sjeaugey** [comment]
Well, there is probably a reason why LL128 was disabled then.

Are you sure all GPUs are connected through NVLinks or only pairs?

You should at least attach the `nvidia-smi topo -m` output of the NCCL topology XML dump if you want us to be able to comment.

**Comment by tks2004** [comment]
Yes. All of them are connected through NClinks
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity
GPU0     X      NV4     NV4     NV4     48-63,112-127   3
GPU1    NV4      X      NV4     NV4     32-47,96-111    2
GPU2    NV4     NV4      X      NV4     16-31,80-95     1
GPU3    NV4     NV4     NV4      X      0-15,64-79      0

**Comment by tks2004** [comment]
[4N_16PES_4G_2MB_23d_04m_24_ll128proto_1670498.log](https://github.com/NVIDIA/nccl/files/15073983/4N_16PES_4G_2MB_23d_04m_24_ll128proto_1670498.log)
Attached the log of allreduce run with -t 1, It fails if run with -t 4

**Comment by tks2004** [comment]
Thanks, It worked with the latest version. Could you please point me to a reference for more details on PXN
