### ISSUE TITLE
ncclSocketInit: connecting to address  with family 0 is neither AF_INET(2) nor AF_INET6(10)

### ISSUE THREAD

**Issue by josephcappadona** [NVIDIA/nccl#1267]
I am having trouble with PyTorch distributed training. I am on Google Cloud VMs and one node in particular gives me issues -- I can launch distributed jobs across all 7 other nodes without a problem. But when I include this 1 problem node in a job, I get the following error.

On the master node (not the problem node), I get
```
    dist.barrier()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3313, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
ncclSocketInit: connecting to address  with family 0 is neither AF_INET(2) nor AF_INET6(10)
```

and on the problem node, I get
```
instance-8g-96c-1:440225:440225 [0] NCCL INFO Bootstrap : Using ens7:10.128.0.30<0>
instance-8g-96c-1:440225:440225 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
instance-8g-96c-1:440225:440225 [0] NCCL INFO NET/Plugin: Loaded net plugin FastSocket (v4)
instance-8g-96c-1:440225:440225 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
instance-8g-96c-1:440225:440225 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
instance-8g-96c-1:440225:440225 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.14.3+cuda11.7
instance-8g-96c-1:440225:440407 [0] NCCL INFO NET/FastSocket : Tx CPU start: -2
instance-8g-96c-1:440225:440407 [0] NCCL INFO NET/FastSocket : Rx CPU start: -2
instance-8g-96c-1:440225:440407 [0] NCCL INFO NET/FastSocket : Flow placement enabled.
instance-8g-96c-1:440225:440407 [0] NCCL INFO NET/FastSocket : queue skip: 0
instance-8g-96c-1:440225:440407 [0] NCCL INFO NET/FastSocket : Using [0]ens7:10.128.0.30<0>
instance-8g-96c-1:440225:440407 [0] NCCL INFO NET/FastSocket plugin initialized
instance-8g-96c-1:440225:440407 [0] NCCL INFO Using network FastSocket
```

This happened out of nowhere the past few days. From searching a bit, I understand `ncclSocketInit: connecting to address  with family 0 is neither AF_INET(2) nor AF_INET6(10)` to mean that something might be wrong with the problem node's IP interface, but nothing seems wrong from the simple testing I've done -- I can ping the node from other nodes on the network and vice versa.

I am a bit lost so any help would be appreciated!

**Comment by kiskra-nvidia** [comment]
Can you verify that you are running the same version of NCCL on the troublesome node as on the rest? Your first included output (from the master node) mentions 2.19.3 (but it's not the standard NCCL INFO debug output so I don't know how trustworthy it is), but the output from the troublesome node clearly says 2.14.3?

**Comment by josephcappadona** [comment]
What is the best way to check that? Running
```
python -c "import torch;print(torch.cuda.nccl.version())"
```
on both nodes yields
```
(2, 14, 3)
```

**Comment by kiskra-nvidia** [comment]
Interesting... Any idea where the 2.19.3 number in the below string (from the master) comes from then?

```torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3```

NCCL prints its version number when `NCCL_DEBUG=INFO` but it does so on rank 0 only. We have this data from your problem node (`2.14.3`); was that with your PyTorch training workload (and did you deliberately configure the problem node to be the first one)? I suggest that you launch your training workload with `NCCL_DEBUG=INFO` on the 7 nodes that don't cause issues, to verify the version number that way. If you want to be really thorough, launch it in single-node configurations on each of the 8 nodes separately, to verify that they are all the same (it doesn't matter if the problem is too big to finish on a single node; it just needs to start).

**Comment by josephcappadona** [comment]
Yes, the 2.14.3 was with my PyTorch training workload, and yes, I configured the problem node to be rank 0 (I've tested it as rank 0 and not as rank 0).

Okay, yes, there seems to be a discrepancy -- this is from running in standalone mode on 4 of the machines with `NCCL_DEBUG=INFO`:

1 (problem node)
```
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
instance-8g-96c-1:525765:525765 [0] NCCL INFO Bootstrap : Using ens7:10.128.0.30<0>
instance-8g-96c-1:525765:525765 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
instance-8g-96c-1:525765:525765 [0] NCCL INFO NET/Plugin: Loaded net plugin FastSocket (v4)
instance-8g-96c-1:525765:525765 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
instance-8g-96c-1:525765:525765 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5).
instance-8g-96c-1:525765:525765 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.14.3+cuda11.7
instance-8g-96c-1:525765:525972 [0] NCCL INFO NET/FastSocket : Tx CPU start: -2
instance-8g-96c-1:525765:525972 [0] NCCL INFO NET/FastSocket : Rx CPU start: -2
instance-8g-96c-1:525765:525972 [0] NCCL INFO NET/FastSocket : Flow placement enabled.
instance-8g-96c-1:525765:525972 [0] NCCL INFO NET/FastSocket : queue skip: 0
instance-8g-96c-1:525765:525972 [0] NCCL INFO NET/FastSocket : Using [0]ens7:10.128.0.30<0>
instance-8g-96c-1:525765:525972 [0] NCCL INFO NET/FastSocket plugin initialized
instance-8g-96c-1:525765:525972 [0] NCCL INFO Using network FastSocket
instance-8g-96c-1:525765:525972 [0] NCCL INFO PXN Disabled as plugin is v4
instance-8g-96c-1:525765:525972 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 00/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 01/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 02/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 03/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 04/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 05/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 06/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 07/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 08/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 09/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 10/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 11/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 12/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 13/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 14/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 15/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 16/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 17/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 18/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 19/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 20/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 21/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 22/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 23/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 24/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 25/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 26/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 27/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 28/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 29/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 30/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Channel 31/32 :    0
instance-8g-96c-1:525765:525972 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
instance-8g-96c-1:525765:525972 [0] NCCL INFO Connected all rings
instance-8g-96c-1:525765:525972 [0] NCCL INFO Connected all trees
instance-8g-96c-1:525765:525972 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
instance-8g-96c-1:525765:525972 [0] NCCL INFO comm 0x55b284e06840 rank 0 nranks 1 cudaDev 0 busId 30 - Init COMPLETE
```

2:
```
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
instance-8g-96c-2:525781:525781 [0] NCCL INFO Bootstrap : Using ens7:10.128.0.31<0>
instance-8g-96c-2:525781:525781 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
instance-8g-96c-2:525781:525781 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin symbol (>= v5). ncclNetPlugin symbols v4 and lower are not supported.
instance-8g-96c-2:525781:525781 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.19.3+cuda12.3
instance-8g-96c-2:525781:525957 [0] NCCL INFO NET/IB : No device found.
instance-8g-96c-2:525781:525957 [0] NCCL INFO NET/Socket : Using [0]ens7:10.128.0.31<0>
instance-8g-96c-2:525781:525957 [0] NCCL INFO Using non-device net plugin version 0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Using network Socket
instance-8g-96c-2:525781:525957 [0] NCCL INFO comm 0x55f90cbfd740 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 30 commId 0x795b968dc454cfee - Init START
instance-8g-96c-2:525781:525957 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 00/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 01/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 02/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 03/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 04/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 05/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 06/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 07/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 08/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 09/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 10/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 11/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 12/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 13/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 14/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 15/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 16/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 17/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 18/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 19/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 20/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 21/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 22/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 23/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 24/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 25/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 26/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 27/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 28/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 29/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 30/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Channel 31/32 :    0
instance-8g-96c-2:525781:525957 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
instance-8g-96c-2:525781:525957 [0] NCCL INFO P2P Chunksize set to 131072
instance-8g-96c-2:525781:525957 [0] NCCL INFO Connected all rings
instance-8g-96c-2:525781:525957 [0] NCCL INFO Connected all trees
instance-8g-96c-2:525781:525957 [0] NCCL INFO 32 coll channels, 0 nvls channels, 32 p2p channels, 32 p2p channels per peer
instance-8g-96c-2:525781:525957 [0] NCCL INFO comm 0x55f90cbfd740 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 30 commId 0x795b968dc454cfee - Init COMPLETE
```

3:
```
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
instance-8g-96c-3:2744870:2744870 [0] NCCL INFO Bootstrap : Using ens7:10.128.0.32<0>
instance-8g-96c-3:2744870:2744870 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
instance-8g-96c-3:2744870:2744870 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin symbol (>= v5). ncclNetPlugin symbols v4 and lower are not supported.
instance-8g-96c-3:2744870:2744870 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.19.3+cuda12.3
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO NET/IB : No device found.
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO NET/Socket : Using [0]ens7:10.128.0.32<0>
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Using non-device net plugin version 0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Using network Socket
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO comm 0x55f08a1c83d0 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 30 commId 0x438c8edb9fb0064f - Init START
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 00/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 01/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 02/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 03/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 04/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 05/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 06/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 07/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 08/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 09/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 10/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 11/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 12/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 13/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 14/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 15/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 16/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 17/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 18/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 19/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 20/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 21/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 22/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 23/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 24/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 25/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 26/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 27/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 28/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 29/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 30/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Channel 31/32 :    0
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO P2P Chunksize set to 131072
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Connected all rings
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO Connected all trees
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO 32 coll channels, 0 nvls channels, 32 p2p channels, 32 p2p channels per peer
instance-8g-96c-3:2744870:2745046 [0] NCCL INFO comm 0x55f08a1c83d0 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 30 commId 0x438c8edb9fb0064f - Init COMPLETE
```

4:
```
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
instance-8g-96c-4:101707:101707 [0] NCCL INFO Bootstrap : Using ens7:10.128.0.33<0>
instance-8g-96c-4:101707:101707 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v7 symbol.
instance-8g-96c-4:101707:101707 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin symbol (>= v5). ncclNetPlugin symbols v4 and lower are not supported.
instance-8g-96c-4:101707:101707 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.19.3+cuda12.3
instance-8g-96c-4:101707:101889 [0] NCCL INFO NET/IB : No device found.
instance-8g-96c-4:101707:101889 [0] NCCL INFO NET/Socket : Using [0]ens7:10.128.0.33<0>
instance-8g-96c-4:101707:101889 [0] NCCL INFO Using non-device net plugin version 0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Using network Socket
instance-8g-96c-4:101707:101889 [0] NCCL INFO comm 0x558ef922a470 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 30 commId 0x7ef9513a104d9d97 - Init START
instance-8g-96c-4:101707:101889 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00ffffff
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 00/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 01/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 02/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 03/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 04/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 05/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 06/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 07/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 08/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 09/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 10/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 11/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 12/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 13/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 14/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 15/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 16/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 17/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 18/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 19/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 20/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 21/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 22/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 23/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 24/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 25/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 26/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 27/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 28/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 29/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 30/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Channel 31/32 :    0
instance-8g-96c-4:101707:101889 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
instance-8g-96c-4:101707:101889 [0] NCCL INFO P2P Chunksize set to 131072
instance-8g-96c-4:101707:101889 [0] NCCL INFO Connected all rings
instance-8g-96c-4:101707:101889 [0] NCCL INFO Connected all trees
instance-8g-96c-4:101707:101889 [0] NCCL INFO 32 coll channels, 0 nvls channels, 32 p2p channels, 32 p2p channels per peer
instance-8g-96c-4:101707:101889 [0] NCCL INFO comm 0x558ef922a470 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 30 commId 0x7ef9513a104d9d97 - Init COMPLETE
```

I am not sure why `torch.cuda.nccl.version()` would return a different version than is actually being used, but it does seem that the problem node is `NCCL version 2.14.3+cuda11.7` while the others are `NCCL version 2.19.3+cuda12.3`.

How do you recommend I rectify this? I could try upgrading NCCL on the problem node to match the others (what is the recommended way of doing this? is this a system-level issue or a Python package issue?), or is there a better/simpler/cleaner way to rectify this (would nuking the Python environments on all machines and starting over from scratch help?)? For context, `nvidia-smi` shows `CUDA Version: 12.0` on all 4 machines.

**Comment by josephcappadona** [comment]
Okay, I think I've solved the issue. Running `pip freeze | grep nccl` on the machines yielded:

1 (problem node):
```
nvidia-nccl-cu11==2.14.3
nvidia-nccl-cu12==2.20.5
```

2,3,4:
```
nvidia-nccl-cu11==2.14.3
nvidia-nccl-cu12==2.19.3
```

So I removed the `cu11` packages and downgraded machine 1 to `nvidia-nccl-cu12==2.19.3`, but this still didn't work. I found the system-level NCCL installation located at `/usr/local/nccl2/` and it seemed to be `2.17.1` (based on the filename `/usr/local/nccl2/lib/libnccl.so.2.17.1`), so I tried installing `nvidia-nccl-cu12==2.17.1` on all machines and now they can communicate just fine.

Thank you very much for your assistance, your hunch that the issue was due to mismatched versions was correct!
Cheers,
Joe
