### ISSUE TITLE
AMD EPYC 7K62 NCCL-test  4090 bandwidth too 

### ISSUE THREAD

**Issue by ghoul02015** [NVIDIA/nccl#1285]
![WechatIMG48](https://github.com/NVIDIA/nccl/assets/16802545/93f4e512-b44b-4009-a4cd-0792de5e987e)
![WechatIMG49](https://github.com/NVIDIA/nccl/assets/16802545/66e080c3-6452-4b24-902d-ca3de62f2fcb)
![WechatIMG50](https://github.com/NVIDIA/nccl/assets/16802545/8bd564a0-1fb5-4796-bfa8-c0f5f3adbf70)
CPU：AMD EPYC 7K62
mem：32G *16
AMD EPYC Why is p2p performance so slow? Is there anything to set

**Comment by sjeaugey** [comment]
You may try to set `NCCL_P2P_LEVEL=PXB` and see whether it works better. 

Note that p2pBandwidth only creates traffic between few GPUs. Performance tends to degrade significantly when we have traffic going from/to all GPUs and interleaving in the CPU. It would also be interesting to see what performance you get with 2 GPUs only (which would be kind of equivalent to the p2pBandwidth test in bidirectional mode and `--sm_copy` mode.

**Comment by bio-punk** [comment]
set numa node(s) to 8 in bios
epyc你要设置8个numa才行，调下bios设置
Advanced>ACPI Settings >NUMA nodes per socket:NPS4
Advanced > AMD CBS > NBIO Common Options > IOMMU:

**Comment by ghoul02015** [comment]
没错，是这个问题，已经通过这个设置解决了

发件人: WZK ***@***.***>
日期: 星期四, 2024年12月12日 16:26
收件人: NVIDIA/nccl ***@***.***>
抄送: IT1ku web ***@***.***>, Author ***@***.***>
主题: Re: [NVIDIA/nccl] AMD EPYC 7K62 NCCL-test 4090 bandwidth too (Issue #1285)

set numa node(s) to 8 in bios
epyc你要设置8个numa才行，调下bios设置
Advanced>ACPI Settings >NUMA nodes per socket:NPS4
Advanced > AMD CBS > NBIO Common Options > IOMMU:

―

**Comment by kirin-huo** [comment]
@ghoul02015  我这边也是AMD EPYC 7K62 NCCL-test 4090   一样的碰到 Avg bus bandwidth    : 4.57458   值 偏小 且 已经配置过Advanced>ACPI Settings >NUMA nodes per socket：NPS4
Advanced > AMD CBS > NBIO Common Options > IOMMU：disable  ,想咨询下还需要修改哪些bios设置呢

**Comment by GuangguanWang** [comment]
> set numa node(s) to 8 in bios epyc你要设置8个numa才行，调下bios设置 Advanced>ACPI Settings >NUMA nodes per socket:NPS4 Advanced > AMD CBS > NBIO Common Options > IOMMU:

Does NUMA configuration still matter for performance if traffic goes over PCIe P2P?
