### ISSUE TITLE
NCCL2 allreduce nan problem with InfiniBand

### ISSUE THREAD

**Issue by dashesy** [NVIDIA/nccl#133]
I have 2 nodes each with 8 GPUs (Tesla M40) that are connected with Infiniband (Mellanox). I use NCCL 2.1.15 allreduce to SUM the gradients and average them, also broadcast the initial weights (I run 1 process for each GPU). Cuda is 8 and CUDNN is 6, but I also have tried Cuda 9 and Cudnn 7, with same results.

When I use NCCL2 and allreduce with ` -x CUDA_CACHE_DISABLE=1 -x NCCL_SOCKET_IFNAME=net0 -x NCCL_IB_HCA=mlx5_0,mlx5_2`, the gradient values are different, and after few thousand iterations I see zeros and nans and loss becomes nan.

If I disable IB with ` -x NCCL_IB_DISABLE=1 -x CUDA_CACHE_DISABLE=1 -x NCCL_SOCKET_IFNAME=net0 -x NCCL_IB_HCA=mlx5_0,mlx5_2` then `net0` will be used between nodes. Then everything works fine.

I also tried using IB as a network (RoCE capable) with ` -x NCCL_IB_DISABLE=1 -x CUDA_CACHE_DISABLE=1 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_IB_HCA=mlx5_0,mlx5_2` and that too works fine without nans. This is a little faster than `net0` but not by much, and 30% slower than IB.

Since `NCCL_SOCKET_IFNAME=ib0` it seems IB itself is fine, just when used as IB there seems to be some issue. What is the best way to debug this? I know there is an issue, but without NCCL2 source I cannot debug further.

Needless to say when IB is disabled there is just 1 ring, but with IB there are 2 rings. ~~~How can I test changing that?~~~

This is the topology of each node:

```
$ nvidia-smi topo -m
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    mlx5_0  mlx5_1  mlx5_2  mlx5_3  CPU Affinity
GPU0     X      PIX     PHB     PHB     SYS     SYS     SYS     SYS     PHB     PHB     SYS     SYS     0-6,14-20
GPU1    PIX      X      PHB     PHB     SYS     SYS     SYS     SYS     PHB     PHB     SYS     SYS     0-6,14-20
GPU2    PHB     PHB      X      PIX     SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-6,14-20
GPU3    PHB     PHB     PIX      X      SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-6,14-20
GPU4    SYS     SYS     SYS     SYS      X      PIX     PHB     PHB     SYS     SYS     PIX     PIX     7-13,21-27
GPU5    SYS     SYS     SYS     SYS     PIX      X      PHB     PHB     SYS     SYS     PIX     PIX     7-13,21-27
GPU6    SYS     SYS     SYS     SYS     PHB     PHB      X      PIX     SYS     SYS     PHB     PHB     7-13,21-27
GPU7    SYS     SYS     SYS     SYS     PHB     PHB     PIX      X      SYS     SYS     PHB     PHB     7-13,21-27
mlx5_0  PHB     PHB     PIX     PIX     SYS     SYS     SYS     SYS      X      PIX     SYS     SYS
mlx5_1  PHB     PHB     PIX     PIX     SYS     SYS     SYS     SYS     PIX      X      SYS     SYS
mlx5_2  SYS     SYS     SYS     SYS     PIX     PIX     PHB     PHB     SYS     SYS      X      PIX
mlx5_3  SYS     SYS     SYS     SYS     PIX     PIX     PHB     PHB     SYS     SYS     PIX      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
```

-----
Edit: I tried forcing it to use a single ring with `-x NCCL_RINGS=0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15` and it also has no issue (no nans). So it seems the issue is with multiple rings (or order in the ring).
With 2 rings (that has issue) I have this:

```text
CY4SCH102501701:6363:6363 [0] INFO Ring 00 :    0   1   2   3  12  13  14  15   8   9  10  11   4   5   6   7
CY4SCH102501701:6363:6363 [0] INFO Ring 01 :    0   1   3   4   5   6   7  10   8   9  11  12  13  14  15   2
```

With one ring (either with or without IB) I have this:
```text
CY4SCH102501701:11184:11184 [0] INFO Ring 00 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
```

With two rings (that are not automatically selected to cross the nodes multiple times like above: `-x NCCL_RINGS=0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15|0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15` I have this:

```text
CY4SCH102501701:11536:11536 [0] INFO Ring 00 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
CY4SCH102501701:11536:11536 [0] INFO Ring 01 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
```

-----
Further Edit:

It seems 2 rings (but with given `NCCL_RINGS`) also has no issue! I wonder why those jumbled rings are formed by default, and why it changes the gradient values. With 2 rings, the speed is faster, how does 2 rings affect the allreduce operation?

**Comment by AddyLaddy** [comment]
Hi and thanks for your detailed problem description.
Can you tell us what nvidia driver version and CUDA toolkit version you are using?

**Comment by dashesy** [comment]
Here is the driver version:

```
$ nvidia-smi
Wed Jul 25 01:30:31 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.25                 Driver Version: 390.25                    |

```

I use cuda 8 inside a docker, I do not know how to check the cuda version of host if that matters but will figure that out.

**Comment by AddyLaddy** [comment]
Thanks for the info. There is a known data corruption issue in the R390 series of drivers that exhibits itself when using RDMA over Infiniband. You can confirm this is your issue by setting NCCL_IB_CUDA_SUPPORT=0 (see Known Issues; https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/rel_2.2.13.html#rel_2.2.13)

I suggest upgrading the nvidia drivers to a newer version to resolve this issue.

**Comment by dashesy** [comment]
I tried `NCCL_IB_CUDA_SUPPORT=0 ` and it fixed the issue! Then I went back and sure enough this was in the logs before that:

```
CY4SCH102501002:6213:6213 [4] INFO 3 -> 12 via NET/IB/0/GDRDMA
CY4SCH102501002:6201:6201 [2] INFO 7 -> 10 via NET/IB/1/GDRDMA
```

-----------
I wonder why the bugfix is not mentioned also in [nccl2.1.15 docs](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/rel_2.1.15.html#rel_2.1.15)? 
In fact it is not related to nccl at all, it should be mentioned somewhere more visible/global. Where should we keep checking for the future?

**Comment by AddyLaddy** [comment]
Setting `NCCL_IB_CUDA_SUPPORT=0` doesn't disable IB use in NCCL. It just disables the option for the network data to be written directly to CUDA memory by the NCCL transport proxy threads. This can degrade performance as it involves another PCI transfer of the data.

The bug was in a particular version of the CUDA driver and is solved by upgrading to a new driver. With the fixed drivers, no workarounds are required in NCCL and there is no performance penalty.
