### ISSUE TITLE
NCCL WARN Cuda failure 'named symbol not found'

### ISSUE THREAD

**Issue by casparvl** [NVIDIA/nccl#1372]
**Issue**
I had an issue with a code that used TensorFlow + Horovod + NCCL for training an AI model on multiple GPUs. I reproduced the issue with **Example 2: One Device per Process or Thread** from [the NCCL documentation](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html). While I have resolved my issue, I'd like to report it anyway since I could not find _any_ details on the error message I got on the web.

All ranks in my training crashed. Using `NCCL_DEBUG=trace` I got the error:

```
gcn75:2336636:2336906 [0] enqueue.cc:58 NCCL WARN Cuda failure 'named symbol not found'
```
(it's listed many times, each time the same error, originating from two different function calls in `enqueue.cc`).

**Cause**
It turned out my NCCL was compiled with 
```
make  -j 64  NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80
```
but I was trying to run on `H100` (i.e. CUDA compute capability 90) GPUs. The reason for this `NVCC_GENCODE` was that originally, this cluster had (only) A100s (i.e. CUDA compute capability 80). 

**Solution**
After rebuilding NCCL with
```
make  -j 64  NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_90,code=sm_90
```

**Final remarks**
I'm well aware that this is really not an issue in the NCCL code, but an issue of the person who built it on our cluster :) I just wanted to make it easier for people to find a solution if they run into this. I expect the people that run into this are users from clusters which hold GPUs of varying generations, including the H100 (cc90) generation. Feel free to just close this issue. 

The only thing that _could_ be considered an issue with NCCL itself is the fact that even with `NCCL_DEBUG=trace`, the error is unclear (and is reported at WARN level, even though it causes process termination). I also found I had very few ways of debugging this issue. It was mostly accidental (and lucky) that I found the `NVCC_GENCODE`  in the original build logs, and figured it _might_ have something to do with this... I'm not sure if the error could be made more specific, somehow, but I'll leave that up to the devs to decide :)

**Comment by kiskra-nvidia** [comment]
You're right; I hit the same issue every so often as well, but of course I'm so used to it by now that I hardly even read the error message. But there's no need to print that message more than once, and we could provide a hint underneath as to the most likely origin of the problem. I'll propose a suitable patch, but it may need to wait until NCCL 2.24.

**Comment by casparvl** [comment]
Thanks for the quick response!

> But there's no need to print that message more than once, and we could provide a hint underneath as to the most likely origin of the problem. I'll propose a suitable patch, but it may need to wait until NCCL 2.24.

I think the next person to run into this will really appreciate that, thanks a lot :)

**Comment by kwen2501** [comment]
@kiskra-nvidia Some PyTorch users went into this issue too. 
Question: is `named symbol not found` the right error code? 
It gives user an idea that the function `cudaFuncGetAttributes` is not found? But is that the case?

**Comment by kiskra-nvidia** [comment]
I've forgotten about this issue, but I believe we have in fact fully addressed it in the meantime, in NCCL 2.27, so I'll be changing the resolution here to Completed.

With NCCL 2.27 or newer, we no longer generate any `named symbol not found` diagnostics at initialization time, and when attempting to launch a device kernel that's not available, the message is now `no kernel image is available for execution on the device`, which is hopefully a lot more clear.

@kwen2501 answering your questions directly. The `named symbol not found` was, in principle, correct, because we were trying to query the attributes of a kernel that turns out to be unavailable due to a GPU arch mismatch between what libnccl.so was compiled for and what it is being run on. The diagnostics level was not correct, though, as we try to reserve WARN for fatal errors, which this was not (not until we later try to actually launch such kernel, that is). So the `not found` symbol was the device kernel, not the `cudaFuncGetAttributes` -- the latter is in fact part of the CUDA runtime library that is statically linked into `libnccl.so` so it's pretty much impossible for it to be not found 😃. I wish we would've printed the name of the unavailable kernel to avoid ambiguity but we don't have that information readily available as far as I know...
