### ISSUE TITLE
Problem with SHMEM creation on startup.

### ISSUE THREAD

**Issue by davies-w** [NVIDIA/nccl#1518]
Im trying to run a job with 4 GPUs. It's just a simple huggingface distilBERT model, and I'm using the following command to launch it.
It works fine with 2 GPUs, and it also works with 4 fine if I disable SHM, but as soon as I try to go beyond 2 with SHMEM I get the invalid argument error message.

export CUDA_VISIBLE_DEVICES=0,1,2,3
NCCL_DEBUG=INFO CUDA_LAUNCH_BLOCKING=1  torchrun --nproc-per-node 4 trainer.py
...

NCCL WARN Cuda failure 'invalid argument' 
NCCL WARN Error while creating shared memory segment /dev/shm/nccl-NzwJ7O (size 9637888)

My /dev/shm is 64MB and there's plenty of space (a seperate error is that jobs that fail don't clear up this space), but I just manually rm them.

disabling SHM, this works
NCCL_DEBUG=INFO NCCL_SHM_DISABLE=1 torchrun --nproc-per-node 4 trainer.py

I have no more insight into what the SHM failure is. Thanks in advance, W

```
[3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
[3] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer

[1] misc/shmutils.cc:103 NCCL WARN Cuda failure 'invalid argument'

[1] misc/shmutils.cc:114 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-NzwJ7O (size 9637888)

[0] misc/shmutils.cc:103 NCCL WARN Cuda failure 'invalid argument'

[0] misc/shmutils.cc:114 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-ppufqI (size 9637888)
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1288871 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 1288869) of binary: /home/x/.pyenv/versions/3.11.6/envs/dsmljar/bin/python3
```

**Comment by davies-w** [comment]
Ok, in case anyone else finds the same problem, the issue was that even though there was 64MB, and that was more than enough for 2 GPUs, when it increased to 4 GPUs it actually wanted 109GB of memory. So increasing shmem solved it for us.

**Comment by davies-w** [comment]
(you may want to figure out why its failing so cryptically, because when /dev/shm is full (eg create a dummy file in it), then you actually get a "not enough space on device" error.

**Comment by kiskra-nvidia** [comment]
We improved the diagnostic output for this case in NCCL 2.22 -- I'm guessing you're using an older version?

**Comment by davies-w** [comment]
python -c "import torch;print(torch.cuda.nccl.version())"
(2, 18, 1)

Ah yes, thank you!!
