### ISSUE TITLE
NCCL error (`vendor err`) during multi-node training with mixed HCA vendors (Mellanox and Broadcom)

### ISSUE THREAD

**Issue by asdfry** [NVIDIA/nccl#1526]
Hello,

I am encountering an NCCL error while trying to perform multi-node training with a DGX-H100 server equipped with a Mellanox HCA and a Kaytus server equipped with a Broadcom HCA. (The logs include a "vendor err" message.)

Both servers are using RoCE communication, have ACS functionality disabled, and HPC-X has been loaded.
For distributed training, I am using Hugging Face's Accelerate library.

I will attach the NCCL logs for your reference. Could you please take a look? 😥
Additionally, is multi-node training between servers with different HCA vendors unsupported?

Thank you in advance for your support!

[nccl-log.zip](https://github.com/user-attachments/files/17941540/nccl-log.zip)

**Comment by asdfry** [comment]
I remapped the IPs assigned to the NICs on the Kaytus server to match the GPU order, and ran the script with `NCCL_IB_GID_INDEX=3` as you suggested. This resolved the `vendor err` issue.

However, the training now freezes at some point during the process. Each server has eight 400G NICs, but it seems like we're not utilizing the bandwidth effectively. Could you advise on what aspects I should look into to resolve this? 

Any suggestions on network configuration or other possible issues would be greatly appreciated.

[logs.zip](https://github.com/user-attachments/files/17985871/logs.zip)

**Comment by asdfry** [comment]
I resolved the issue by setting the MTU of the Ethernet interfaces participating in RoCE communication to 9000.
