### ISSUE TITLE
[bug] bootstrap may fail when connection close before sending 8 bytes

### ISSUE THREAD

**Issue by fishautumn** [NVIDIA/nccl#1612]
Bootstrap socket checks request magic (8 bytes) and will ignore if magic doesn't match.
It can greatly avoid failure caused by unexpected network traffic (like security scan).

However , when connection to peer listen socket is closed before 8 bytes are sent, it still will causes bootstrap failure.

ref log:
```
[0] misc/socket.cc:71 NCCL WARN socketProgress: Connection closed by remote peer 10.10.1.3<36138>
[0] NCCL INFO misc/socket.cc:80 -> 6
[0] NCCL INFO misc/socket.cc:474 -> 6
[0] NCCL INFO misc/socket.cc:628 -> 6
[0] NCCL INFO misc/socket.cc:731 -> 6
[0] NCCL INFO bootstrap.cc:701 -> 6
[0] NCCL INFO init.cc:1402 -> 6
[0] NCCL INFO group.cc:75 -> 6 [Async thread]
[0] NCCL INFO group.cc:423 -> 6
[0] NCCL INFO group.cc:573 -> 6
[0] NCCL INFO group.cc:106 -> 6
```

https://github.com/NVIDIA/nccl/blob/80f6bda4378b99d99e82b4d76a633791cc45fef0/src/misc/socket.cc#L474

please consider also ignore peer connections that disconnected before sending 8 bytes.

**Comment by gangxie112** [comment]
@kiskra-nvidia @sjeaugey

**Comment by stephenmsachs** [comment]
Thanks a lot for reporting. It appears this issue has been resolved in release `v2.27.3-1`: https://github.com/NVIDIA/nccl/blob/72d2432094d6ae36abd6e511c3a16a2d052dbf94/src/misc/socket.cc#L510.  Please open a new issue or add a comment if you disagree.
