### ISSUE TITLE
all-to-all communication error:

### ISSUE THREAD

**Issue by leoda1** [NVIDIA/nccl#1668]
Good morning/afternoon：
I tried using isend and irecv to test my custom alltoall implementation on a 4-node, 32-GPU setup, but I noticed that the NCCL_DEBUG logs kept showing the following bugs:

su14-gpu07:49091:49179 [0] proxy.cc:1458 NCCL WARN [Service thread] Accept failed Resource temporarily unavailable
su14-gpu07:49091:49179 [0] proxy.cc:1497 NCCL WARN [Service thread] Could not receive type from localRank 0, res=3, closed=0
su14-gpu07:49091:49179 [0] proxy.cc:1521 NCCL WARN [Proxy Service 1] Failed to execute operation Close from rank 1, retcode 3
su14-gpu07:49267:49358 [0] NCCL INFO comm 0x55af9e2ed230 rank 1 nranks 2 cudaDev 0 busId 18000 - Abort COMPLETE

after that，i tried just P2P communication on two gpu, it still has following bugs:

node131:42301:42466 [0] NCCL INFO [Service thread] Connection closed by localRank 0
Rank 1 received tensor: 42
node131:42302:42464 [1] NCCL INFO [Service thread] Connection closed by localRank 1
node131:42301:42546 [0] NCCL INFO comm 0x6e98040 rank 0 nranks 2 cudaDev 0 busId 17000 - Abort COMPLETE
node131:42302:42547 [0] NCCL INFO comm 0x7679660 rank 1 nranks 2 cudaDev 1 busId e3000 - Abort COMPLETE

I found that this assertion appears in proxy.cc, but I’m still not sure where exactly the problem comes from. Even when I test with very simple code, I still encounter the same issue mentioned above.

def run():
    rank = int(os.environ['RANK'])
    world_size = int(os.environ['WORLD_SIZE'])

    # NCCL 只支持 GPU，所以这里指定当前 rank 对应的 GPU
    torch.cuda.set_device(rank)
    device = torch.device(f'cuda:{rank}')

    # 初始化进程组
    dist.init_process_group(
        backend='nccl',
        init_method='env://',
        world_size=world_size,
        rank=rank
    )

    if rank == 0:
        tensor = torch.tensor([42], dtype=torch.int, device=device)
        dist.send(tensor=tensor, dst=1)
        print(f"Rank {rank} sent tensor: {tensor.item()}")
    elif rank == 1:
        tensor = torch.zeros(1, dtype=torch.int, device=device)
        dist.recv(tensor=tensor, src=0)
        print(f"Rank {rank} received tensor: {tensor.item()}")

    dist.destroy_process_group()

**Comment by kiskra-nvidia** [comment]
Can you share a complete `NCCL_DEBUG=INFO` log (from both ranks)?

**Comment by leoda1** [comment]
I have fixed it, it's a small bug
