### ISSUE TITLE
[NCCL2.26.2][RAS] RAS could crash NCCL process during initialization phase

### ISSUE THREAD

**Issue by zhiyongww** [NVIDIA/nccl#1669]
Hi NCCL team,

I'd like to report a bug: during NCCL initialization, running the RAS command can cause NCCL to crash.

Reproduction Steps:
Run the NCCL all-to-all test on two hosts.
Execute the RAS command during NCCL initialization.
Then, you can observe that NCCL crashes.

Output:
```
rtptest1621:405884:407462 [0] NCCL INFO NCCL_IB_FIFO_TC set by environment to 224.
rtptest1625:1886888:1890510 [7] NCCL INFO NET/IB: IbDev 4 Port 1 qpn 103534 set_ece={supported=1, vendor_id=0x15b3, options=0x0, comp_mask=0x0}
rtptest1625:1886888:1890510 [7] NCCL INFO NET/IB: IbDev 4 Port 1 qpn 103554 set_ece={supported=1, vendor_id=0x15b3, options=0x0, comp_mask=0x0}
rtptest1625:1886888:1890510 [7] NCCL INFO NET/IB: IbDev 4 Port 1 qpn 103555 set_ece={supported=1, vendor_id=0x15b3, options=0x0, comp_mask=0x0}
rtptest1625:1886888:1890510 [7] NCCL INFO NET/IB: IbDev 4 Port 1 qpn 103556 set_ece={supported=1, vendor_id=0x15b3, options=0x0, comp_mask=0x0}
rtptest1620:935572:937467 [0] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1625:1886882:1890516 [6] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1625:1886888:1890510 [7] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405884:407462 [0] NCCL INFO RAS client listening socket at ::1<28028>
[rtptest1621:405884] *** Process received signal ***
[rtptest1621:405884] Signal: Segmentation fault (11)
[rtptest1621:405884] Signal code: Address not mapped (1)
[rtptest1621:405884] Failing at address: 0x10
[rtptest1621:405884] [ 0] /usr/local/XXX/platform010/lib/libc.so.6(+0x44560)[0x7f0bfb044560]
[rtptest1621:405884] [ 1] nccl_alltoall_perf_2_26[0x30f6a7]
[rtptest1621:405884] [ 2] nccl_alltoall_perf_2_26[0x30a079]
[rtptest1621:405884] [ 3] nccl_alltoall_perf_2_26[0x30ec44]
[rtptest1621:405884] [ 4] nccl_alltoall_perf_2_26[0x3062a4]
[rtptest1621:405884] [ 5] /usr/local/XXX/platform010/lib/libc.so.6(+0x9abc9)[0x7f0bfb09abc9]
[rtptest1621:405884] [ 6] /usr/local/XXX/platform010/lib/libc.so.6(+0x12ce4c)[0x7f0bfb12ce4c]
[rtptest1621:405884] *** End of error message ***
rtptest1621:405885:407432 [1] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405888:407469 [4] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405886:407470 [2] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405898:407433 [7] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405887:407352 [3] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405892:407460 [5] NCCL INFO RAS client listening socket at ::1<28028>
rtptest1621:405894:407471 [6] NCCL INFO RAS client listening socket at ::1<28028>
```

thanks.

**Comment by kiskra-nvidia** [comment]
Interesting... Did you run the `ncclras` client in a tight loop or something to get the timing "just right"? We've run such stress-tests in the past without observing such crashes, but that was with NCCL 2.24 -- perhaps a regression has sneaked in in the meantime...

The backtrace in your log is interesting, in that it does not include `libnccl.so`. Is `nccl_alltoall_perf_2_26` linked to the static `libnccl.a` perhaps? If debugging symbols have not been stripped, would you mind posting the output of `addr2line -e /path/to/nccl_alltoall_perf_2_26 0x30f6a7 0x30a079 0x30ec44 0x3062a4`? It could also be that the crash handler is printing the backtrace from a wrong thread; still, worth a try!

**Comment by kiskra-nvidia** [comment]
Never mind, I reproduced it. Yeah, it is a new bug in 2.26...

**Comment by zhiyongww** [comment]
Awesome, I was trying to get a new output. I remember it failed at socket connection.

**Comment by kiskra-nvidia** [comment]
Would you like to try a draft fix?

```
diff --git a/src/include/comm.h b/src/include/comm.h
index 409518713..c33f8af14 100644
--- a/src/include/comm.h
+++ b/src/include/comm.h
@@ -420,6 +420,7 @@ struct ncclComm {
   struct ncclTopoSystem* topo;
   struct ncclProxyConnector* gproxyConn;
   struct ncclIntruQueue<struct ncclCommCallback, &ncclCommCallback::next> legacyRegCleanupQueue;
+  bool peerInfoValid;
 
   int netPluginLoaded;
   ncclNet_t* ncclNet;
diff --git a/src/init.cc b/src/init.cc
index 0268ba11a..9bcb986f9 100644
--- a/src/init.cc
+++ b/src/init.cc
@@ -707,6 +707,7 @@ static ncclResult_t initTransportsRank(struct ncclComm* comm, struct ncclComm* p
   NCCLCHECKGOTO(ncclCalloc(&comm->peerInfo, nranks+1), ret, fail); // Extra rank to represent CollNet root
   NCCLCHECKGOTO(fillInfo(comm, comm->peerInfo+rank, comm->commHash), ret, fail);
   NCCLCHECKGOTO(bootstrapAllGather(comm->bootstrap, comm->peerInfo, sizeof(struct ncclPeerInfo)), ret, fail);
+  __atomic_store_n(&comm->peerInfoValid, true, __ATOMIC_RELEASE);
 
   comm->cuMemSupport = 1;
   for (int i = 0; i < nranks; i++) {
diff --git a/src/ras/collectives.cc b/src/ras/collectives.cc
index 72833604f..ea7242d35 100644
--- a/src/ras/collectives.cc
+++ b/src/ras/collectives.cc
@@ -606,6 +606,10 @@ static ncclResult_t rasCollCommsInit(struct rasCollRequest** pReq, size_t* pReqL
   for (int commIdx = 0; commIdx < nNcclComms; commIdx++) {
     if (ncclComms[commIdx] == nullptr) // nullptr's are always at the end after sorting.
       break;
+    if (!__atomic_load_n(&ncclComms[commIdx]->peerInfoValid, __ATOMIC_ACQUIRE)) {
+      // Critical data is not yet initialized -- ignore the communicator.
+      continue;
+    }
     // A process may manage multiple GPUs and thus have multiple communicators with the same commHash.
     // Comparing just the commHash is OK though within communicators that are part of the same process.
     if (commIdx == 0 || ncclComms[commIdx]->commHash != ncclComms[commIdx-1]->commHash) {
@@ -651,6 +655,8 @@ static ncclResult_t rasCollCommsInit(struct rasCollRequest** pReq, size_t* pReqL
   // collCommIdx counts rasCollComms::comm (comm); commIdx indexes ncclComms.
   for (int collCommIdx = 0, commIdx = 0; collCommIdx < nComms; collCommIdx++) {
     struct ncclComm* ncclComm = ncclComms[commIdx];
+    if (!__atomic_load_n(&ncclComm->peerInfoValid, __ATOMIC_ACQUIRE))
+      continue;
 
     comm->commId.commHash = ncclComm->commHash;
     comm->commId.hostHash = ncclComm->peerInfo->hostHash;
@@ -680,7 +686,7 @@ static ncclResult_t rasCollCommsInit(struct rasCollRequest** pReq, size_t* pReqL
       comm->nRanks++;
     } // for (commIdx)
 
-    if (firstNewSkipMissingIdx != -1 &&
+    if (__atomic_load_n(&ncclComm->peerInfoValid, __ATOMIC_ACQUIRE) && firstNewSkipMissingIdx != -1 &&
         memcmp(req->comms.skipMissingRanksComms+firstNewSkipMissingIdx, &comm->commId, sizeof(comm->commId)) == 0) {
       // Fill in the missingRanks array that follows the comm->ranks.
       struct rasCollCommsMissingRank* missingRanks = (struct rasCollCommsMissingRank*)(comm->ranks+comm->nRanks);
```

We may fix it differently for 2.28 but until then this should be the easiest fix...

**Comment by zhiyongww** [comment]
Thanks for the patch, it works for me.
