### ISSUE TITLE
NCCL refuses to carry out reduce-scatter over NVLS

### ISSUE THREAD

**Issue by lw** [NVIDIA/nccl#1670]
I'm playing around with a single-node 8 GPU setup on which I'm doing FSDP and enabling user-buffer registration.

I was made aware that NCCL prefers using the ring algorithm over NVLS for all-gather and reduce-scatter because it sends fewer bytes over the wire and should be faster in principle. However here I am worried about SM contention hence I'm forcing `NCCL_ALGO=nvls`.

The all-gathers behave as expected, and they end up using only 4 CTAs. (They also are quite fast!)

However, the reduce-scatters give me this error:
```
Error : no algorithm/protocol available for function ReduceScatter with datatype ncclFloat32. NCCL_ALGO was set to nvls
```

Is it expected that NVLS doesn't support reduce-scatters? Is there a workaround? Is this support planned? Thanks!

**Comment by kiskra-nvidia** [comment]
What NCCL version is that? Note that since 2.24, you can specify `NCCL_ALGO` per-collective-type (check [the docs](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-algo)), which would be one way to unblock you...

**Comment by kiskra-nvidia** [comment]
With respect to what's supported, see: https://github.com/NVIDIA/nccl/blob/f44ac759fee12ecb3cc6891e9e739a000f66fd70/src/device/generate.py#L76-L83 https://github.com/NVIDIA/nccl/blob/f44ac759fee12ecb3cc6891e9e739a000f66fd70/src/device/generate.py#L105-L122

Basically, NVLS does work with ReduceScatter, but for 32-bit floats, the reduction operation must be Sum.

**Comment by lw** [comment]
Thanks for the answers!

I'm using 2.25.1+cuda12.6, on H100 GPUs. I think I tried with bf16 dtypes and got the same result. Let me check what reduction op I'm using.

**Comment by lw** [comment]
Indeed the issue was that I was using "avg" instead of "sum" as the reduction op! After changing this I see that the reduce-scatter is also able to use NVLS with user buffers (using 5 CTAs total). Thanks!
