### ISSUE TITLE
[nccl2.27.3] plugin loading bug

### ISSUE THREAD

**Issue by zhiyongww** [NVIDIA/nccl#1732]
Hey NCCL folks,

In NCCL 2.27.3, it's not able to find and load the plugin.

Repro
```
NCCL_RAS_ENABLE=0 NCCL_PROFILE_EVENT_MASK=127 NCCL_PROFILE_DUMP_FILE=qp_profiling NCCL_PROFILER_PLUGIN=./libnccl_example_profiler_plugin.so NCCL_P2P_DISABLE=1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT ./nccl_alltoall_perf_bad -b 32M -e 128M -f 2 -n 1000 -g 8
```

Logs:
```
rtptest1621:268329:272115 [5] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler-./libnccl_example_profiler_plugin.so.so.
```

cc: @kiskra-nvidia

**Comment by kiskra-nvidia** [comment]
Can you try with `NCCL_PROFILER_PLUGIN=libnccl_example_profiler_plugin.so` (i.e., without `./`)?

**Comment by zhiyongww** [comment]
```
NCCL_RAS_ENABLE=0 NCCL_PROFILE_EVENT_MASK=127 NCCL_PROFILE_DUMP_FILE=qp_profiling NCCL_PROFILER_PLUGIN=libnccl_example_profiler_plugin.so NCCL_P2P_DISABLE=1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT ./nccl_alltoall_perf -b 32M -e 128M -f 2 -n 1000 -g 8

rtptest1621:2617175:2618957 [6] NCCL INFO PROFILER/Plugin: Could not find: libnccl_example_profiler_plugin.so.
```

```
NCCL_RAS_ENABLE=0 NCCL_PROFILE_EVENT_MASK=127 NCCL_PROFILE_DUMP_FILE=qp_profiling NCCL_PROFILER_PLUGIN=/root/libnccl_example_profiler_plugin.so NCCL_P2P_DISABLE=1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT ./nccl_alltoall_perf -b 32M -e 128M -f 2 -n 1000 -g 8

rtptest1621:2636534:2637825 [4] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler-/root/libnccl_example_profiler_plugin.so.so.
```

```
[root@rtptest1621.ftw6 ~]# ls -d $PWD/libnccl_example_profiler_plugin.so
/root/libnccl_example_profiler_plugin.so
```

After I copied old code(2.23) to nccl2.27.3, it worked.

**Comment by kiskra-nvidia** [comment]
Can you try:

```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. NCCL_RAS_ENABLE=0 NCCL_PROFILE_EVENT_MASK=127 NCCL_PROFILE_DUMP_FILE=qp_profiling NCCL_PROFILER_PLUGIN=libnccl_example_profiler_plugin.so NCCL_P2P_DISABLE=1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT ./nccl_alltoall_perf -b 32M -e 128M -f 2 -n 1000 -g 8
```

**Comment by zhiyongww** [comment]
The above command works for me
```
rtptest1621:3506981:3507453 [1] NCCL INFO PROFILER/Plugin: Plugin name set by env to libnccl_example_profiler_plugin.so
rtptest1621:3506981:3507453 [1] NCCL INFO PROFILER/Plugin: loaded Example-profiler
```

**Comment by kiskra-nvidia** [comment]
@zhiyongww Could you verify if the newly released NCCL 2.27.5 fixes your issue?

**Comment by zhiyongww** [comment]
Thanks for the fix!
