### ISSUE TITLE
Unexpected NCCL Symmetric Memory Tests Results

### ISSUE THREAD

**Issue by GeofferyGeng** [NVIDIA/nccl#1735]
### NCCL Version

2.27.3

### CUDA Version

12.4

### OS Version

Ubuntu 22.04

### What application are you using?

nccl-tests-2.16.4, support symmetric memory

### Details

I'm trying test symmetric memory on two H20 server. First I tested alltoall_perf over 16*H20 + 16*CX 7. A bit strange is that the results for specifying R=1 and R=2 are exactly the same. Then I tested H20 server allreduce with NVLS algo and it worked well when R=1 while it stuck when R=2. The followings are outputs and logs.

Is there something wrong with my settings? I have checked cuMem that is supported.

```text
/usr/mpi/gcc/openmpi-4.1.7rc1/bin/mpirun --allow-run-as-root --tag-output --mca pml ob1 --mca coll '^hcoll' --mca btl tcp,self --mca btl_tcp_if_include eth0 --mca oob_tcp_if_include eth0 --host xx.xx.xx.xx:8 -x LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:/usr/mpi/gcc/openmpi-4.1.7rc1/lib:/home/nccl/2.27.3/build/lib/ -x UCX_NET_DEVICES=eth0 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG_FILE=/home/nccl/log/debug.%p.log -x NCCL_IB_TC=160 -x NCCL_TOPO_DUMP_FILE=/home/nccl/log/topo.xml -x NCCL_GRAPH_DUMP_FILE=/home/nccl/log/graph.xml -x NCCL_ALGO=nvls -x NCCL_IB_QPS_PER_CONNECTION=4 -x NCCL_NET_PLUGIN=none -x NCCL_DEBUG=info -x NCCL_DEBUG_SUBSYS=all /home/nccl/nccl-tests-2.16.4/build/all_reduce_perf -b 8 -e 1G -f 2 -g 1 -n 100 -w 5 -R 2
[1,0]<stdout>:# nThread 1 nGpus 1 minBytes 8 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 100 agg iters: 1 validation: 1 graph: 0
[1,0]<stdout>:#
[1,0]<stdout>:# Using devices
[1,0]<stdout>:#  Rank  0 Group  0 Pid 2317241 on      node3 device  0 [0000:0f:00] NVIDIA H20
[1,0]<stdout>:#  Rank  1 Group  0 Pid 2317242 on      node3 device  1 [0000:10:00] NVIDIA H20
[1,0]<stdout>:#  Rank  2 Group  0 Pid 2317243 on      node3 device  2 [0000:41:00] NVIDIA H20
[1,0]<stdout>:#  Rank  3 Group  0 Pid 2317244 on      node3 device  3 [0000:44:00] NVIDIA H20
[1,0]<stdout>:#  Rank  4 Group  0 Pid 2317245 on      node3 device  4 [0000:90:00] NVIDIA H20
[1,0]<stdout>:#  Rank  5 Group  0 Pid 2317246 on      node3 device  5 [0000:91:00] NVIDIA H20
[1,0]<stdout>:#  Rank  6 Group  0 Pid 2317247 on      node3 device  6 [0000:b8:00] NVIDIA H20
[1,0]<stdout>:#  Rank  7 Group  0 Pid 2317248 on      node3 device  7 [0000:bb:00] NVIDIA H20
[1,0]<stdout>:#
[1,0]<stdout>:#                                                              out-of-place                       in-place          
[1,0]<stdout>:#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
[1,0]<stdout>:#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
```

[debug.2317241.log](https://github.com/user-attachments/files/20668128/debug.2317241.log)

**Comment by sjeaugey** [comment]
Symmetric kernels currently only target allreduce, allgather and reduce scatter. Alltoall is not implemented yet.

So this is expected.

**Comment by GeofferyGeng** [comment]
> Symmetric kernels currently only target allreduce, allgather and reduce scatter. Alltoall is not implemented yet.
> 
> So this is expected.

Thanks for your reply! I saw this description in the commit message. It seems I misunderstood.

```
Add new API calls to register user-allocated memory among communicator
   ranks into a NCCL window: ncclCommWindowRegister() and
   ncclCommWindowDeregister(). The calls currently support symmetric
   registration for P2P and NVLS, and require VMM memory buffers (i.e.,
   CUMEM must be operational).
```

**Comment by kiskra-nvidia** [comment]
Well, the alltoall not using symmetric memory is expected; the allreduce not working is not.

I don't see anything wrong in the debug output you attached; however, it's from just a single rank. Do you have the output from other ranks? Does ncclras print any warnings/errors if you run it when all_reduce_perf is hanging?

**Comment by GeofferyGeng** [comment]
@kiskra-nvidia Hi, thank you for your attention to this issue.

1. logs of all ranks are attached below. It seems that all ranks work well.

[debug.2317241.log](https://github.com/user-attachments/files/20700655/debug.2317241.log)
[debug.2317242.log](https://github.com/user-attachments/files/20700657/debug.2317242.log)
[debug.2317243.log](https://github.com/user-attachments/files/20700662/debug.2317243.log)
[debug.2317244.log](https://github.com/user-attachments/files/20700656/debug.2317244.log)
[debug.2317245.log](https://github.com/user-attachments/files/20700659/debug.2317245.log)
[debug.2317246.log](https://github.com/user-attachments/files/20700660/debug.2317246.log)
[debug.2317247.log](https://github.com/user-attachments/files/20700661/debug.2317247.log)
[debug.2317248.log](https://github.com/user-attachments/files/20700658/debug.2317248.log)

2. ncclras returns without any errors or warns either when hang. (reproduce)
```
NCCL version 2.27.3 compiled with CUDA 12.4
CUDA runtime version 12040, driver version 12040

Job summary
===========

  Nodes  Processes         GPUs  Processes     GPUs
(total)   per node  per process    (total)  (total)
      1          8            1          8        8

Communicators... (0.00s)
=============

Group     Comms     Nodes     Ranks     Ranks     Ranks    Status  Errors
    #  in group  per comm  per node  per comm  in group
    0         1         1         8         8         8   RUNNING      OK

Errors
======

Warnings
========
```

3. **more test**

3.1. I finally found it works well when I set max message size <=16K. Once max size over or equal 32K, allreduce hang.

3.2. when I run on 2 Nodes, although I use `ncclCommWindowRegister` to register buffer, it seems that Symmetric Memory is NOT enabled because I didn't see such output in log on this condition. I'm not sure if this is the reason why it doesn't hang when running under two nodes.
```
NCCL INFO AllReduce [Symmetric]: 1073741824 Bytes -> Kernel AllReduce_RSxLDMC_AGxSTMC nchannels 2 nthreads 512
``` 

do you have any ideas? Is there any tests I can do ?

**Comment by kiskra-nvidia** [comment]
We switch kernels from `AllReduce_AGxLLMC_R` to `AllReduce_RSxLDMC_AGxSTMC` at 32K. For some reason the latter hangs for you. @jbachan any ideas? Per the first message, NVLS works fine on the system with `-R 1`.

Can you try with `reduce_scatter_perf` and `all_gather_perf` as well? Let's see how their symmetric kernels do on your system.

Symmetric memory is not supported for network traffic in NCCL 2.27. This is something that we are currently working on...

**Comment by GeofferyGeng** [comment]
@kiskra-nvidia The following content is further testing.

> Can you try with `reduce_scatter_perf` and `all_gather_perf` as well? Let's see how their symmetric kernels do on your system.

`reduce_scatter_perf` works well when message size <= 64K with kernel `ReduceScatter_LL` and hang with `ReduceScatter_LDMC` when message size >= 128K.  `all_gather_perf` works well when message size <= 64K with kernel `AllGather_LLMC` and hang with `AllGather_STMC` when message size >= 128K.

By using `NCCL_SYM_KERNEL`, I tested all symmetric kernels in message size = 128K and here is a summary:

| collective |  kernel |  status |
|-----------|---------|---------|
| all_reduce |AllReduce_AGxLL_R | √ |
| all_reduce |AllReduce_AGxLLMC_R |  √ |
| all_reduce |AllReduce_RSxLD_AGxST |  √ |
| all_reduce |AllReduce_RSxLDMC_AGxSTMC | hang |
| all_gather |AllGather_LL |  √ |
| all_gather |AllGather_LLMC |  √ |
| all_gather |AllGather_ST |  √ |
| all_gather |AllGather_STMC | hang  |
| reduce_scatter |ReduceScatter_LL |  √ |
| reduce_scatter |ReduceScatter_LD |  √ |
| reduce_scatter |ReduceScatter_LDMC | hang  |

**Comment by GeofferyGeng** [comment]
> Symmetric memory is not supported for network traffic in NCCL 2.27. This is something that we are currently working on...

glad to hear that, Symmetric memory indeed brings a significant improvement with small-byte data

**Comment by mnicely** [comment]
@GeofferyGeng do you have use cases for symmetric memory over the network or are you just benchmarking

**Comment by GeofferyGeng** [comment]
> [@GeofferyGeng](https://github.com/GeofferyGeng) do you have use cases for symmetric memory over the network or are you just benchmarking

@mnicely In fact, it is our client who wants to improve the performance of NCCL at small size, and this seems to be the optimization that the NCCL team is currently working on. So I'm doing benchmarks and see if it meets the client's requirements.

**Comment by tirthasheshpatel** [comment]
https://github.com/NVIDIA/nccl/commit/72d2432094d6ae36abd6e511c3a16a2d052dbf94

>  * Implement specialized kernels taking advantage of symmetrically
   registered memory, with performance gains expected particularly for
   small to medium message sizes.

Curious, is anything stopping the symmetric memory kernels to work well on large messages too? Seems like currently AG/RS/AR are all pretty naive algorithms which might not scale well to larger sizes. I don't even think RS and AR are pipelined. But if NCCL does those optimizations, shouldn't symmetric memory be better? @sjeaugey @mnicely @kiskra-nvidia

**Comment by mnicely** [comment]
I'll need to double check with engineering. FWIW, can you try the latest 2.27.5?

**Comment by mnicely** [comment]
> > [@GeofferyGeng](https://github.com/GeofferyGeng) do you have use cases for symmetric memory over the network or are you just benchmarking
> 
> @mnicely In fact, it is our client who wants to improve the performance of NCCL at small size, and this seems to be the optimization that the NCCL team is currently working on. So I'm doing benchmarks and see if it meets the client's requirements.

I'd love to know more about the reqs and whether what we have today meets those requirements. We have much more in the pipeline coming soon!

**Comment by kiskra-nvidia** [comment]
> > * Implement specialized kernels taking advantage of symmetrically
> >   registered memory, with performance gains expected particularly for
> >   small to medium message sizes.
> Curious, is anything stopping the symmetric memory kernels to work well on large messages too?

There are two aspects here to consider.

First and foremost, we've always tried to get close to the theoretical peak performance for large enough message sizes. So if, say, for some collective we get 98% of the peak with 4 GB and larger message sizes, there's hardly any room for improvement there. The primary reason we are implementing symmetric kernels is to "left-shift the S-curve" -- extend the area of high achieved performance to smaller message sizes, which are latency-bound.

> Seems like currently AG/RS/AR are all pretty naive algorithms which might not scale well to larger sizes. I don't even think RS and AR are pipelined.

This is indeed the other aspect. Symmetric kernels are implemented using, effectively, an all-to-all communication pattern. That's what it takes to cut down the latency by an integer factor. But there is indeed a price to pay, when the amount of data being exchanged exceeds the bandwidth of the NVLink fabric. The good news is, however, that for the largest message sizes the latency is not a major concern, and we have the non-symmetric kernels that we've spent years optimizing, that we can easily switch to as needed.

**Comment by tirthasheshpatel** [comment]
This makes a lot of sense, thanks @kiskra-nvidia!

**Comment by GeofferyGeng** [comment]
> I'll need to double check with engineering. FWIW, can you try the latest 2.27.5?

@mnicely 2.27.5 got same result. Consider of changes between 2.27.3 and 2.27.5, I think it's reasonable.

**Comment by kiskra-nvidia** [comment]
We believe to have reproduced this issue on our end. The root cause is still under investigation but the version of the CUDA toolkit appears to be critical, and specifically the version used for compiling the symmetric kernels. With CTK >= 12.6, it "just works" for us, whereas with older versions we see hangs. @GeofferyGeng can you try with a newer CUDA version? You don't actually need to update the kernel driver; just make sure that you compile NCCL with the newer version.

**Comment by kiskra-nvidia** [comment]
A workaround for this issue will be included in NCCL 2.28.

**Comment by GeofferyGeng** [comment]
@kiskra-nvidia Sorry for noticing your reply after such a long time and thank you for your continued attention to this issue. 
I have retested all symmetric memory kernels with CUDA 12.6, and they are indeed working properly. 
Looking forward to the release of version 2.28.

**Comment by teojgo** [comment]
@GeofferyGeng can you confirm that this is now resolved?
