### ISSUE TITLE
[Issue]: NCCL multicast error

### ISSUE THREAD

**Issue by gadamopoulos-saifh** [NVIDIA/nccl#1788]
### How is this issue impacting you?

Application crash

### Share Your Debug Logs

My setup is a node with 8 H100s. I get this error when trying to run VLLM. I ran an identical setup for almost a month and then had this error start suddenly. 

```
[2025-07-21 19:05:29] node004:27907:27907 [1] transport/nvls.cc:254 NCCL WARN Cuda failure 401 'the operation cannot be performed in the present state'
node004:27907:27907 [1] NCCL INFO transport/nvls.cc:409 -> 1
```

This is the line where the error is happening in ``nvls.cc``

```
ncc/src/transport/nvls.cc

CUCHECKGOTO(cuMulticastAddDevice(*mcHandle, comm->cudaDev), ret, fail);
```

so I assume this error has something to do with multicast. But earlier on in the logs, I have 

```NVLS multicast support is available on dev 3``` and so on and ```NVLS importing shareableHandle 0x7ffd4224e570 from rank 0```

The NCCL version I'm using is ``nccl==2.26.2``. And it is loaded from a library:  ``Found nccl from library libnccl.so.2``

I get significantly degraded performance, but am able to prevent this issue with the following flags. To clarify, I never had to set these flags before and it was still working.

```
export NCCL_NVLS_ENABLE=0
export NCCL_ALGO=^NVLS
```

I am using cuda version ``12.9`` and driver version ``575.51.03``.

Any ideas what could be happening?

### NCCL Version

2.26.2+cuda12.9

**Comment by AddyLaddy** [comment]
If the NVSwitch Fabric Manager is restarted without a subsquent GPU reset (or node reboot) then Multicast (NVLS) will not function.
The `NVLS multicast support is available on dev 3` message just means that the GPU device architecture and driver is capable of multicast operations. It does not indicate that the system is correctly configured to support thm.

**Comment by gadamopoulos-saifh** [comment]
Thank you this solved it!
