### ISSUE TITLE
[Question]: pool alltoall performance with 16 H20 nodes

### ISSUE THREAD

**Issue by gangxie112** [NVIDIA/nccl#1792]
### Question

Hi,

I run16-node alltoal test and found the performance is not as expected.  The busbw is only 20+GB. The following is the params:

**Comment by stephenmsachs** [comment]
@gangxie112 thanks for reporting. This is not the expected behavior. Would you be able to share those logs of the 3 and 4 rails run you produced with `NCCL_DEBUG=INFO` ? 

You could also make sure each of the GPUs can talk to their respective peer at the full link speed using [nvbandwidth](https://github.com/NVIDIA/nvbandwidth).

Have you tried different values for `MIN_CHANNELS` `QPS_PER_CONNECTION`, `BUFFSIZE` and `CHUNKSIZE`? Those values look very specific.

**Comment by gangxie112** [comment]
> [@gangxie112](https://github.com/gangxie112) thanks for reporting. This is not the expected behavior. Would you be able to share those logs of the 3 and 4 rails run you produced with `NCCL_DEBUG=INFO` ?
> 
> You could also make sure each of the GPUs can talk to their respective peer at the full link speed using [nvbandwidth](https://github.com/NVIDIA/nvbandwidth).
> 
> Have you tried different values for `MIN_CHANNELS` `QPS_PER_CONNECTION`, `BUFFSIZE` and `CHUNKSIZE`? Those values look very specific.

1. We checked the log, nothing special. 
2.  We tested all the hardwares, including d2h,h2d, nvlink, etc., no problem found. The performance of the all_reduce_perf looks good.
3. All the params mentioned are tuned, no effect. Increasing the buffer size as the following, could get better performance, but still at 20+GB. I think there must be something wrong. Because the performance downgrades by some times, not some percents. 
    -x NCCL_BUFFSIZE=16777216 \
    -x NCCL_P2P_NET_CHUNKSIZE=1048576 \
    -x NCCL_P2P_PCI_CHUNKSIZE=1048576 \
4. To me, looks like, there is some problem when multiple connecitons, looking into the following matrix:

<img width="706" height="234" alt="Image" src="https://github.com/user-attachments/assets/3ab7c26a-9860-43fc-aca0-f5aca57a8759" />

**Comment by pzcyyj** [comment]
@gangxie112 hello，are these virtual machines or physical machines?

**Comment by gangxie112** [comment]
After upgrade to 2.27+, the issue is resolved. close it.
