### ISSUE TITLE
Does ncclAllGather have problems with recvBuffer size above 2GB?

### ISSUE THREAD

**Issue by emjotde** [NVIDIA/nccl#184]
Hi,
I am seeing weird behavior for ncclAllGather when recvBuffer size exceeds quite exactly 2 GB regardless of the type used. Everything below 2GB works perfectly fine with float32 or float16, as soon as 2GB is exceeded I get random hanging threads during or after the ncclAllGather operation or random memory access errors. Are there any known limits here? Integer size overflow maybe?

**Comment by emjotde** [comment]
Some more info, this happens on 8x Volta 16 GB with NVLink. 4x Volta seems to be fine interestingly.

**Comment by sjeaugey** [comment]
I could not reproduce the issue. I tried on 8 GPUs, sending 1GB / receiving 8GB and it works (same type of machine : 8x Volta 16 GB machine with NVLink).

Also tried on two GPUs sending 4GB / receiving 8GB and it worked as well.

**Comment by emjotde** [comment]
Thank you for testing this. There is a lot of other stuff happening around that code, so I will investigate some more.  I will report back.

**Comment by emjotde** [comment]
Ok, Thanks again! Veryfing that it's not NCCL's fault sent me on right path. It is indeed integer overflow at 2G bytes, but in my own code.

**Comment by emjotde** [comment]
Is the test you used available somewhere?

**Comment by AddyLaddy** [comment]
A collection of NCCL perf/sanity tests are available at; https://github.com/NVIDIA/nccl-tests

**Comment by emjotde** [comment]
I am trying to produce a minimal example for that issue. You test your operations in isolation, while I seem to be seeing problems when allGather is used after scatterReduce and a couple of stream synchronizations. Will see if I can send you a piece of code that isolates this.

**Comment by emjotde** [comment]
Interesting. I cannot reproduce this in a minimal example, but downgrading to 2.3.5 solves the problem in my large code. So this is definitely NCCL related.

**Comment by AddyLaddy** [comment]
Do you have the sequence of operations that lead up to the failure or your minimal example for us to look at please?
Can you still observe the failure if you set `NCCL_LL_THRESHOLD=0` or `NCCL_LL_THRESHOLD=$((8192*1024*1024))`

**Comment by emjotde** [comment]
Sorry for reviving this thread after this long time. I was happy with NCCL 2.3.5 working for me and now went back to test 2.5.6. I have the same issue still, but `NCCL_LL_THRESHOLD=0` does indeed fix that. Can I set that value somewhere in-code?

**Comment by emjotde** [comment]
Hm, no, still hangs when reloading. I will try to take another look at that with fresh eyes.

**Comment by sjeaugey** [comment]
That is weird. NCCL 2.5.6 should not be affected by `NCCL_LL_THRESHOLD` (it would be `NCCL_PROTO=^LL`). Are you sure your binary didn't get linked statically with 2.4.2 ? Setting `NCCL_DEBUG=VERSION` would print a line in the output.

**Comment by emjotde** [comment]
It's the correct version and NCCL_LL_THRESHOLD does not affect it. That was a misinterpretation on my part. It seems that now I have a two different sequences of events where one results in hanging, the other doesn't. That's new. Will see if I can isolate this now.

**Comment by emjotde** [comment]
OK, some more observations:
* 2.3.7 works fine out of the the box.
* 2.4.8 hangs with default settings, memory access error with `NCCL_LL_THRESHOLD=0`, but works fine with `NCCL_LL_THRESHOLD=$((8192*1024*1024))` (yay!)
* 2.5.6 hangs with default settings. Is there a way to set the threshold as for 2.4.8?

**Comment by sjeaugey** [comment]
Oh, so Simple hangs but LL works ? I thought it was the opposite. And while it is an interesting observation, I think we should not settle with that (LL is much much slower than Simple).

One easy way to try to reproduce the issue outside of the program would be to dump the NCCL sequence and replay it.

Can you set `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=COLL` and provide the log ? Or at least the end of the log if it is too long ? That might help us reproduce the issue.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
Thanks for your understanding and for contributing to NCCL.
