### ISSUE TITLE
Striping out everything after dot "." in hostname 

### ISSUE THREAD

**Issue by ngoyal2707** [NVIDIA/nccl#187]
I am trying multi-node distributed setting with `pytorch` and `NCCL2` .
Setup: `2` nodes, each with `8` gpus. 

The current code [here](https://github.com/NVIDIA/nccl/blob/master/src/misc/utils.cu#L38)  only reads the hostname till first dot. 

The hostname is used for automatically trying to figure out whether to do `P2P-IPC` vs `Ethernet`. 

Because of above mentioned striping, `NCCL2` is trying `IPC` between two different hosts that have same prefix before "."  and it fails with following error:
```
 _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: NCCL error in: caffe2/torch/lib/c10d/ProcessGroupNCCL.cpp:260, unhandled cuda error
```
 
NCCL logs show:
```
learngpu060:3728579:3730441 [0] INFO Ring 00 :    0   1   2   3   7   4   5   6  10   8   9  11  15  12  13  14  18  16  19  17
learngpu060:3728589:3730445 [2] INFO Ring 00 : 2[2] -> 3[3] via P2P/IPC
learngpu060:3728591:3730447 [4] INFO Ring 00 : 4[4] -> 5[5] via P2P/IPC
learngpu060:3728580:3730448 [1] INFO Ring 00 : 1[1] -> 2[2] via P2P/IPC
learngpu060:3728590:3730442 [3] INFO Ring 00 : 3[3] -> 7[7] via P2P/IPC
learngpu060:3728594:3730443 [7] INFO Ring 00 : 7[7] -> 4[4] via P2P/IPC
learngpu060:3728593:3730444 [6] INFO Ring 00 : 6[6] -> 10[2] via P2P/IPC
learngpu060:3728592:3730446 [5] INFO Ring 00 : 5[5] -> 6[6] via P2P/IPC
learngpu060:3728579:3730441 [0] INFO 63 -> 0 via NET/Socket/0
learngpu060:3728579:3730441 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC

learngpu060:3728593:3730444 [6] transport/p2p.cu:526 WARN failed to open CUDA IPC handle : 30 unknown error
learngpu060:3728593:3730444 [6] INFO init.cu:475 -> 1
learngpu060:3728593:3730444 [6] INFO init.cu:536 -> 1
learngpu060:3728593:3730444 [6] INFO misc/group.cu:70 -> 1 [Async thread]
```

In above `6[6]` should not try to communicate with `10[2]` through `IPC` and should use `Ethernet`.

 
Any reason why `dot` is being used to get the prefix? Can this be resolved as there doesn't seem to be any workaround (I can't change my hostnames).

cc: @pietern, @aadcock

**Comment by AddyLaddy** [comment]
That's odd because we don't just use the hostname as the method for determining whether the ranks are on the same node. We actually generate a hash of the hostname and the Linux namespace objects; /proc/self/ns/uts and /proc/self/ns/mnt
See [getHostHash](https://github.com/NVIDIA/nccl/blob/master/src/misc/utils.cu#L105)

Are you sure multiple nodes are being used for the job?

**Comment by ngoyal2707** [comment]
I see, we are using old version `2.2.13` of `nccl`. And in the code, it might have been recently fixed. Sorry for assuming that it's broken in current version also.

We can upgrade to newer version and see if it fixes the issue. 

Thanks

**Comment by AddyLaddy** [comment]
Ok thanks for the update. Please leave feedback and close this issue if NCCL 2.4 resolves it.

**Comment by AddyLaddy** [comment]
So are you still seeing this issue with NCCL 2.4 ?

**Comment by ngoyal2707** [comment]
@AddyLaddy Yes, we are still seeing the issue with NCCL 2.4.2 . I am debugging this, so far the observation is same, NCCL trying to IPC across hosts that have same prefix. 

I am trying to recompile now to print out why `/proc/self/ns/uts` and `/proc/self/ns/mnt` are not helping. Will update the thread here.

**Comment by ngoyal2707** [comment]
@AddyLaddy So finally able to debug it. 
So currently the host hash is using combination of following 3 things:

1) hostname prefix before dot.
2) `readlink("/proc/self/ns/uts", uname+offset, sizeof(uname)-1-offset);`
3) `readlink("/proc/self/ns/mnt", uname+offset, sizeof(uname)-1-offset);`

Both (2) and (3) just return the `namespace identifier` of UTS (returns `4026531838`) and MNT (returns `4026534202`) , which seem to same across all hosts (and seems to be standard).
 
Also I don't think there any assumption anywhere in the code that hostname shouldn't have dot in it. So it should be good to use full hostname.

**Comment by AddyLaddy** [comment]
Ok thanks for the feedback and patch. It must be that those Namespace values only change when a container is created. 
For the patch, I was thinking of preserving the old behaviour by passing in a 'const char delim' to the getHostName() function, so we can continue to truncate the hostname in the debug log messages.

**Comment by ngoyal2707** [comment]
@AddyLaddy  I see, feel free to update the PR or change the fix which matches general behavior. POSIX standard says the hostname has maximum 253 characters (http://man7.org/linux/man-pages/man7/hostname.7.html).

This PR was more from the perspective of confirming that this fixes the issue.

**Comment by sjeaugey** [comment]
Would it help to remove the domain name instead of stopping on the first "." ? I.e. remove the last two words, so that node2.domain.com still gives node2, but node2.pod4.domain.com gives node2.pod4.

Would that work in your use case ? I think for the logs we would like to use node2.pod4.

**Comment by ngoyal2707** [comment]
@sjeaugey 
Is the concern that domain name will just pollute logs unnecessarily? 
That would work in our use case, but I feel, maybe we can just:

1) Just read stripped version for logs and full hostname for getHostHash
or
2) Just put the truncation in the logging method?   

Feel stripping last two words still put some assumption (which fortunately seems to be okay with our infra) but probably might not generalize well?

**Comment by AddyLaddy** [comment]
NCCL 2.4.6 has now been uploaded and should fix this issue. Please test and re-open if that is not the case.
