### ISSUE TITLE
[Issue]: Performance drop from v2.22 to v2.25 due to RING algorithm

### ISSUE THREAD

**Issue by bellenlau** [NVIDIA/nccl#1876]
[log-nccl-2.18.txt](https://github.com/user-attachments/files/23108114/log-nccl-2.18.txt)

[log-nccl-2.26.txt](https://github.com/user-attachments/files/23107620/log-nccl.txt.txt)

### How is this issue impacting you?

Lower performance than expected

### Share Your Debug Logs

Hello, we are running nccl-tests on a HPC cluster, and we observe a performance drop of bandwidth from circa 50 GB/s to 7 GB/s comparing nccl versions prior to 2.22 to nccl versions higher than 2.25 (values at 2 nodes, but the performance are lower also with higher node number). By analyzing the NCCL_DEBUG=INFO, we understood that the two runs use different algorithms: ring for v2.25+ and another one (tree? not stated as clearly as for higer versions) with v2.22-. 

Ring uses only one port to communicate among nodes while the second one uses all four ports. This is confirmed by nsys profile --nic-metrics=true and the number of channels generated and used while communicating via IB

From the logfile of v 2.18

```
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 00/08 :    0   1   2   3   4   5   6   7
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 01/08 :    0   3   2   5   4   7   6   1
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 02/08 :    0   3   6   5   4   7   2   1
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 03/08 :    0   7   6   5   4   3   2   1
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 04/08 :    0   1   2   3   4   5   6   7
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 05/08 :    0   3   2   5   4   7   6   1
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 06/08 :    0   3   6   5   4   7   2   1
lrdn0020:2080194:2080296 [0] NCCL INFO Channel 07/08 :    0   7   6   5   4   3   2   1
```

while this is from the logfile of nccl/2.26

```
lrdn2785:785563:785668 [0] NCCL INFO Channel 00/02 : 0 1 2 3 4 5 6 7
lrdn2785:785563:785668 [0] NCCL INFO Channel 01/02 : 0 1 2 3 4 5 6 7
```

To recover performance of v2.22-, we tried forcing the tree algorithm with NCCL_ALGO, but the run crashes. This warning appears
```
[2025-10-23 10:26:31] lrdn2146:1399931:1399978 [3] graph/search.cc:1127 NCCL WARN Could not find a path for pattern 1, falling back to simple order 
```
and 
```
[2025-10-23 10:26:31] lrdn2151:2678763:2678858 [0] graph/topo.h:234 NCCL WARN Could not find NET with id 0 
```
Could you please suggest how to debug this issue? In particular, what does the code check to identify and create channels? 

### NCCL Version

nccl/2.26.5+cuda/12.9

### Your platform details

output of nvidia-smi topo -m

```
        ^[[4mGPU0       GPU1    GPU2    GPU3    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID^[[0m
GPU0     X      NV4     NV4     NV4     PXB     NODE    NODE    NODE    0-15    0               N/A
GPU1    NV4      X      NV4     NV4     NODE    PXB     NODE    NODE    0-15    0               N/A
GPU2    NV4     NV4      X      NV4     NODE    NODE    PXB     NODE    0-15    0               N/A
GPU3    NV4     NV4     NV4      X      NODE    NODE    NODE    PXB     0-15    0               N/A
NIC0    PXB     NODE    NODE    NODE     X      NODE    NODE    NODE
NIC1    NODE    PXB     NODE    NODE    NODE     X      NODE    NODE
NIC2    NODE    NODE    PXB     NODE    NODE    NODE     X      NODE
NIC3    NODE    NODE    NODE    PXB     NODE    NODE    NODE     X
```

**Comment by mnicely** [comment]
I can't answer your question, but have you tested the latest release?

**Comment by bellenlau** [comment]
We are going to test the latest release, thank you. We were wondering whether anything changed between versions 2.22 and 2.25 regarding how NCCL discovers the topology and the NICs.

In the user guide, we only found the following reference:

> NCCL relies on /sys to discover the PCI topology of GPUs and network cards. When running inside a virtual machine or container, make sure /sys is properly mounted. Having /sys expose a virtual PCI topology can result in sub-optimal performance.

Would it be possible to get more information about how this process works, specifically which commands or files are checked, to help us understand what may have changed in the NIC discovery mechanism?

The cluster mentioned above is Leonardo Booster: https://docs.hpc.cineca.it/hpc/leonardo.html#system-architecture

**Comment by sjeaugey** [comment]
For us to be able to take a look, we would need you to run a perf test on all GPUs, with NCCL_TOPO_DUMP_FILE=system.txt and provide the log with NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=GRAPH,INIT,ENV.

That would hopefully give us all we need to understand what changed.

**Comment by bellenlau** [comment]
Thank you, please find the data required attached for nccl/2.26.5 (low performance)

- [system-nccl2.26.txt](https://github.com/user-attachments/files/23162690/system.txt)
- [log-nccl2.26.txt](https://github.com/user-attachments/files/23162693/log-nccl2.26.txt)

and for nccl/2.18 (higher performance)

- [log-nccl2.18.txt](https://github.com/user-attachments/files/23162779/log-nccl-2.18.txt)
- [system-nccl2.18.txt](https://github.com/user-attachments/files/23162776/system-nccl1.18.txt)

**Comment by bellenlau** [comment]
Hello, I tested NCCL/2.28.7 with CUDA/12.9; I am installing on bare metal. The saturation bandwidth for all_reduce_perf is even lower, 2 GB/s.  In this case 

- it seems the topology detection issue is still there, as only two channels are found 

```
lrdn0424:45620:45620 [0] NCCL INFO Channel 00/02 : 0 3 2 5 4 7 6 1
lrdn0424:45620:45620 [0] NCCL INFO Channel 01/02 : 0 3 2 5 4 7 6 1
```

- InfiniBand is not found; thus resulting in using socket

```
lrdn0424:45622:45622 [2] NCCL INFO NET/IB : No device found.
lrdn0424:45622:45622 [2] NCCL INFO NET/IB : Using [RO]; OOB ib0:10.128.12.193<0>
lrdn0424:45622:45622 [2] NCCL INFO Failed to initialize NET plugin IB
lrdn0443:44368:44368 [3] NCCL INFO NET/Socket : Using [0]ib0:10.128.13.13<0>
lrdn0443:44368:44368 [3] NCCL INFO Initialized NET plugin Socket
```

files are attached. Thank you for your help!

[system.txt](https://github.com/user-attachments/files/23237654/system.txt)

[log-nccl2.28.7.txt](https://github.com/user-attachments/files/23237682/log-nccl2.28.7.txt)

**Comment by stephenmsachs** [comment]
Hi @bellenlau. Thanks for the additional information. It looks to me as if your newer NCCL build is having trouble finding `libnccl-net.so` and therefore does not find the `mlx` NICs. 
v2.28.7 reports:
```
lrdn0443:44367:44367 [2] NCCL INFO NET/Plugin: Could not find: libnccl-net.so
```
v2.18 reports
```
lrdn3160:3462111:3462154 [3] NCCL INFO Plugin Path : /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/nvhpc-24.5-torlmnyzcexnrs6pq4cccabv7ehkv3xy/Linux_x86_64/24.5/comm_libs/12.4/hpcx/hpcx-2.19/nccl_rdma_sharp_plugin/lib/libnccl-net.so
```

An easy test would be to provide `/leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/nvhpc-24.5-torlmnyzcexnrs6pq4cccabv7ehkv3xy/Linux_x86_64/24.5/comm_libs/12.4/hpcx/hpcx-2.19/nccl_rdma_sharp_plugin/lib/` as part of your `LD_LIBRARY_PATH` when running the v2.28.7 build.

**Comment by bellenlau** [comment]
Thank you for the feedback; I also had to add the [...]/sharp/lib/ folder to the LD_LIBRARY_PATH, otherwise libsmx was not found

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/nvhpc-24.5-torlmnyzcexnrs6pq4cccabv7ehkv3xy/Linux_x86_64/24.5/comm_libs/12.4/hpcx/hpcx-2.19/nccl_rdma_sharp_plugin/lib/:/leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/nvhpc-24.5-torlmnyzcexnrs6pq4cccabv7ehkv3xy/Linux_x86_64/24.5/comm_libs/12.4/hpcx/hpcx-2.19/sharp/lib/
mp
```

With this LD_LIBRARY_PARH the plugin is found 
```
lrdn0544:237559:237559 [3] NCCL INFO Successfully loaded external network plugin /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/nvhpc-24.5-torlmnyzcexnrs6pq4cccabv7ehkv3xy/Linux_x86_64/24.5/comm_libs/12.4/hpcx/hpcx-2.19/nccl_rdma_sharp_plugin/lib/libnccl-net.so
```

but NCCL does not use IB

```
lrdn0544:237558:237558 [2] NCCL INFO NET/IB : No device found.
lrdn0544:237558:237558 [2] NCCL INFO NET/IB : Using [RO]; OOB ib0:10.128.14.161<0>
lrdn0544:237558:237558 [2] NCCL INFO Failed to initialize NET plugin IB

[2025-11-03 18:19:42] lrdn0544:237558:237558 [2] plugin/net.cc:379 NCCL WARN Failed to initialize any NET plugin
l
```

and this error appears:

`libibverbs: Warning: couldn't load driver 'libcxgb4-rdmav57.so': libcxgb4-rdmav57.so: cannot open shared object file: No such file or directory`

Please, find the outputs attached

[slurm-23961512.txt](https://github.com/user-attachments/files/23326669/slurm-23961512.txt)
[log.txt](https://github.com/user-attachments/files/23326670/log.txt)

**Comment by stephenmsachs** [comment]
It looks like there is still more missing in your `LD_LIBRARY_PATH`. `ibcxgb4-rdmav57.so` is a dependency [shipped with](https://rpmfind.net/linux/RPM/centos-stream/9/baseos/x86_64/libibverbs-57.0-2.el9.x86_64.html) `libibverbs.so`, and `libibverbs` is needed to use your IB devices.

I see you are using environment modules for CUDA and MPI. Maybe there is a NCCL module you could use for the dependencies?

**Comment by bellenlau** [comment]
Regarding the installation used to test nccl/2.28.7 as requested at the beginning of the issue, this is installed manually because there is no module beyond nccl/2.22 on the cluster, while the OpenMPI installation needed for multi-node benchmarks and the CUDA are taken from modules installed on the cluster. Not sure if this is valuable information, but this is the output of ldd on all_reduce_perf

```
        linux-vdso.so.1 (0x00007ffdaaba7000)
        libcudart.so.12 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/cuda-12.2.0-o6rr2unwsp4e4av6ukobro6plj7ceeos/lib64/libcudart.so.12 (0x00007f396d8e4000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f396d6dc000)
        libmpi.so.40 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-12.2.0/openmpi-4.1.6-jnvfio5kii7e7oba2bu4jsgzr4nvwhkw/lib/libmpi.so.40 (0x00007f396dc62000)
        libnccl.so.2 => /leonardo_scratch/large/userinternal/lbellen1/projects/spack/opt/spack/linux-icelake/nccl-2.28.7-1-ghcvadvprnusaltddbjvyjlqizrtc7lg/lib/libnccl.so.2 (0x00007f3969a32000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3969812000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f396960e000)
        libstdc++.so.6 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/gcc-12.2.0-lkcazt4letxjj4s7nlhzryoyivevsatz/lib64/libstdc++.so.6 (0x00007f39693e6000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3969064000)
        libgcc_s.so.1 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/gcc-12.2.0-lkcazt4letxjj4s7nlhzryoyivevsatz/lib64/libgcc_s.so.1 (0x00007f396dc3f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3968c8d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f396db8d000)
        libopen-rte.so.40 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-12.2.0/openmpi-4.1.6-jnvfio5kii7e7oba2bu4jsgzr4nvwhkw/lib/libopen-rte.so.40 (0x00007f3968bd2000)
        libopen-pal.so.40 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-12.2.0/openmpi-4.1.6-jnvfio5kii7e7oba2bu4jsgzr4nvwhkw/lib/libopen-pal.so.40 (0x00007f3968b1b000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f3968917000)
        libz.so.1 => /leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/zlib-ng-2.1.6-jkgunjc2hc2qpkzoodjcn6fu3qpfly73/lib/libz.so.1 (0x00007f39686f2000)
        libhwloc.so.15 => /lib64/libhwloc.so.15 (0x00007f39684a2000)
        libevent_core-2.1.so.6 => /lib64/libevent_core-2.1.so.6 (0x00007f3968269000)
        libevent_pthreads-2.1.so.6 => /lib64/libevent_pthreads-2.1.so.6 (0x00007f3968066000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f3967b7c000)

```
To clarify, the issue in channel detection (2 instead of 8) and corresponding lower performance have been observed with bare-mental installations as well as with containerized ones using NCCL versions later than 2.22. In containers, we noticed that the capability to detect IB might depend on the paths bound with -B and the content of the container itself, which is why I am testing a bare-metal installation. The fact that the bare-metal installation does not detect IB is a new issue of this very last installation, which did not arise in previous versions tested (v2.25.1, v2.26.5). 

There is a NCCL/2.22 version installed on the cluster, which has expected performance, but according to the output of NCCL_DEBUG it does not find libnccl-net.so as well, and relies on an internal plugin. The logfile reports:

`lrdn1404:468285:468328 [3] NCCL INFO NET/Plugin: Could not find: libnccl-net.so. Using internal network plugin.
`
Can I force nccl/2.28.7 to use such plugin as well?

**Comment by le1nux** [comment]
thanks for looking into this @stephenmsachs. 
I'm working with @bellenlau on debugging the NCCL issues on Leonardo. 

To make this easier to reproduce, I wrote a simple script that compares the two NCCL versions `2.21.5+cuda12.9` and `2.27.3+cuda12.9` inside a Nemo `25.09` container. In the first case, I had to downgrade the NCCL version accordingly. 

For the `2.27.3` version, we still see log entries such as: 
```
lrdn0024:426176:426616 [2] NCCL INFO Could not find a path for pattern 1, falling back to simple order
lrdn0024:426176:426616 [2] NCCL INFO Pattern 1, crossNic 0, nChannels 1, bw 0.100000/0.100000, type SYS/SYS, sameChannels 1
```
and respective throughput degradation, as shown in the logs that I attached. 
I did not see any of the driver issues w.r.t. `libcxgb4-rdmav57.so`and no devices being found. 

**Nemo container build:**
```sh
Bootstrap: docker
From: nvcr.io/nvidia/nemo:25.09

%post
    # --- CUSTOM NCCL BUILD ---   
    # uncomment the following lines to build a specific NCCL version
    # git clone https://github.com/NVIDIA/nccl.git
    # cd nccl
    # git checkout  v2.21.5-1
    # make -j NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_90,code=sm_90"
    # rm /usr/lib/*64*-linux-gnu/libnccl*
    # cp build/lib/libnccl.so* build/lib/libnccl_static.a /usr/lib/x86_64-linux-gnu/
    # cp -r build/lib/pkgconfig /usr/lib/x86_64-linux-gnu/

    # --- NCCL TESTS ---
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends \
        build-essential \
        git \
        openmpi-bin \
        libopenmpi-dev
    rm -rf /var/lib/apt/lists/*

    git clone --depth=1 https://github.com/NVIDIA/nccl-tests.git /nccl-tests
    cd /nccl-tests
    make -j"$(nproc)" MPI=1
```

**Benchmark script**
```sh
#!/bin/bash
#SBATCH --partition=boost_usr_prod
#SBATCH --account=EUHPC_E05_119
#SBATCH --qos=boost_qos_dbg                 # or  normal, boost_qos_dbg, boost_qos_bprod
#SBATCH --job-name=nccl_bench
#SBATCH --output=logs/%j/nccl_bench_%j.out
#SBATCH --error=logs/%j/nccl_bench_%j.err
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4                
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:4
#SBATCH --mem=0
#SBATCH --time=00:10:00
#SBATCH --exclusive
#SBATCH -x lrdn[1400-3456,0163,0001,0874,0186,1390,1383]

set -xeuo pipefail

module purge
module load openmpi/4.1.6--gcc--12.2.0-cuda-12.2

MODALITIES_IMAGE="/leonardo_scratch/fast/EUHPC_D21_101/max_lue/repositories/working/cineca_fraunhofer_exchange/modalities_bench/containers/nemo_25.09_stock_modalities_master.sif" # nemo_25.09_nccl_2.21.5.sif" # nemo_25.09_stock_modalities_master.sif"
BIND_SRC="/leonardo_scratch/fast/EUHPC_D21_101/max_lue"
BIND_DST="/leonardo_scratch/fast/EUHPC_D21_101/max_lue"

NCCL_PLUGIN_PATH="/leonardo/prod/spack/06/install/0.22/linux-rhel8-icelake/gcc-8.5.0/nvhpc-24.5-torlmnyzcexnrs6pq4cccabv7ehkv3xy/Linux_x86_64/24.5/comm_libs/12.4/hpcx/hpcx-2.19/nccl_rdma_sharp_plugin/lib"
export LD_LIBRARY_PATH="${NCCL_PLUGIN_PATH}:${LD_LIBRARY_PATH:-}"
export SINGULARITYENV_LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH

# -------- NCCL TESTS (inside Nemo container) --------

TEST_ARGS="-b 8 -e 8G -f 2 -g 1 -d float"
NCCL_TEST_LOG_FOLDER="logs/${SLURM_JOB_ID}"
mkdir -p "${NCCL_TEST_LOG_FOLDER}"
TOTAL_GPUS=$(( SLURM_JOB_NUM_NODES * 4))

TEST_NAME="all_reduce_perf"
TEST_CMD="/nccl-tests/build/${TEST_NAME}"
NCCL_TEST_LOG_FILE_PATH="${NCCL_TEST_LOG_FOLDER}/${TEST_NAME}_N${SLURM_JOB_NUM_NODES}n${TOTAL_GPUS}_container.txt"

srun --time=00:05:00 \
     --mpi=pmix_v3 \
     --cpu-bind=cores \
      singularity exec --nv --bind "${BIND_SRC}:${BIND_DST}" \
      "${MODALITIES_IMAGE}" bash -lc "${TEST_CMD} ${TEST_ARGS}" \
  |& tee "${NCCL_TEST_LOG_FILE_PATH}"
```


[nccl_bench_2.21.5.txt](https://github.com/user-attachments/files/23329999/nccl_bench_2.21.5.txt)
[nccl_bench_2.27.3.txt](https://github.com/user-attachments/files/23329998/nccl_bench_2.27.3.txt)

**Comment by stephenmsachs** [comment]
Thanks for all the logs. We need to dig a little to find out why that pattern 1 fails.

**Comment by bellenlau** [comment]
Thank you. Regarding the topology, please note that Leonardo Booster has 32 cores, but according to `nvidia-smi topo -m ` all the 4 GPUs have affinity only to the first 16 cores; Intel SNC is active on the cluster. We noticed that the capability to use all 4 nics deteriorates also for HPCX-MPI. In particular, we noticed that with large message sizes and in All-to-All patterns HPCX-MPI/2.17.1 uses by default all 4 nics, while HPCX-MPI/2.19  only two (NIC0 and NIC1), thus resulting in half of the available BW for two-node communications. 

Please find here the output of `nvidia-smi topo -m` :
```

        GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV4     NV4     NV4     PXB     NODE    NODE    NODE    0-15             0               N/A
GPU1    NV4      X      NV4     NV4     NODE    PXB     NODE    NODE    0-15             0               N/A
GPU2    NV4     NV4      X      NV4     NODE    NODE    PXB     NODE    0-15             0               N/A
GPU3    NV4     NV4     NV4      X      NODE    NODE    NODE    PXB     0-15             0               N/A
NIC0    PXB     NODE    NODE    NODE     X      NODE    NODE    NODE
NIC1    NODE    PXB     NODE    NODE    NODE     X      NODE    NODE
NIC2    NODE    NODE    PXB     NODE    NODE    NODE     X      NODE
NIC3    NODE    NODE    NODE    PXB     NODE    NODE    NODE     X

```

**Comment by maxidl** [comment]
I can get ~34GB/s also on newer nccl versions when setting NCCL_PXN_DISABLE=1.
Example for nccl version 2.27.03
```
./run_nccl_tests.sh
srun: job 25421886 queued and waiting for resources
srun: job 25421886 has been allocated resources
# nccl-tests version 2.17.6 nccl-headers=22703 nccl-library=22703
# Collective test starting: all_reduce_perf
# nThread 1 nGpus 1 minBytes 8 maxBytes 8589934592 step: 2(factor) warmup iters: 1 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid 489516 on   lrdn1842 device  0 [0000:1d:00] NVIDIA A100-SXM-64GB
#  Rank  1 Group  0 Pid 489517 on   lrdn1842 device  1 [0000:56:00] NVIDIA A100-SXM-64GB
#  Rank  2 Group  0 Pid 489518 on   lrdn1842 device  2 [0000:8f:00] NVIDIA A100-SXM-64GB
#  Rank  3 Group  0 Pid 489519 on   lrdn1842 device  3 [0000:c8:00] NVIDIA A100-SXM-64GB
#  Rank  4 Group  0 Pid 1751275 on   lrdn1848 device  0 [0000:1d:00] NVIDIA A100-SXM-64GB
#  Rank  5 Group  0 Pid 1751276 on   lrdn1848 device  1 [0000:56:00] NVIDIA A100-SXM-64GB
#  Rank  6 Group  0 Pid 1751277 on   lrdn1848 device  2 [0000:8f:00] NVIDIA A100-SXM-64GB
#  Rank  7 Group  0 Pid 1751278 on   lrdn1848 device  3 [0000:c8:00] NVIDIA A100-SXM-64GB
#
#                                                              out-of-place                       in-place
#       size         count      type   redop    root     time   algbw   busbw  #wrong     time   algbw   busbw  #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)             (us)  (GB/s)  (GB/s)
           8             2     float     sum      -1    17.86    0.00    0.00       0    17.14    0.00    0.00       0
          16             4     float     sum      -1    17.42    0.00    0.00       0    17.15    0.00    0.00       0
          32             8     float     sum      -1    17.50    0.00    0.00       0    17.17    0.00    0.00       0
          64            16     float     sum      -1    17.59    0.00    0.01       0    17.38    0.00    0.01       0
         128            32     float     sum      -1    17.68    0.01    0.01       0    17.69    0.01    0.01       0
         256            64     float     sum      -1    17.88    0.01    0.03       0    17.83    0.01    0.03       0
         512           128     float     sum      -1    18.36    0.03    0.05       0    18.07    0.03    0.05       0
        1024           256     float     sum      -1    18.77    0.05    0.10       0    18.66    0.05    0.10       0
        2048           512     float     sum      -1    20.40    0.10    0.18       0    20.22    0.10    0.18       0
        4096          1024     float     sum      -1    22.65    0.18    0.32       0    22.45    0.18    0.32       0
        8192          2048     float     sum      -1    29.22    0.28    0.49       0    27.99    0.29    0.51       0
       16384          4096     float     sum      -1    28.53    0.57    1.01       0    28.48    0.58    1.01       0
       32768          8192     float     sum      -1    30.14    1.09    1.90       0    29.42    1.11    1.95       0
       65536         16384     float     sum      -1    35.40    1.85    3.24       0    34.96    1.87    3.28       0
      131072         32768     float     sum      -1    37.77    3.47    6.07       0    37.56    3.49    6.11       0
      262144         65536     float     sum      -1    48.85    5.37    9.39       0    48.50    5.40    9.46       0
      524288        131072     float     sum      -1    75.90    6.91   12.09       0    75.47    6.95   12.16       0
     1048576        262144     float     sum      -1   116.49    9.00   15.75       0   114.16    9.19   16.07       0
     2097152        524288     float     sum      -1   267.37    7.84   13.73       0   267.28    7.85   13.73       0
     4194304       1048576     float     sum      -1   444.79    9.43   16.50       0   444.30    9.44   16.52       0
     8388608       2097152     float     sum      -1   561.12   14.95   26.16       0   562.19   14.92   26.11       0
    16777216       4194304     float     sum      -1   831.17   20.18   35.32       0   834.13   20.11   35.20       0
    33554432       8388608     float     sum      -1  1369.41   24.50   42.88       0  1373.90   24.42   42.74       0
    67108864      16777216     float     sum      -1  2416.22   27.77   48.61       0  2413.75   27.80   48.65       0
   134217728      33554432     float     sum      -1  4447.26   30.18   52.81       0  4439.22   30.23   52.91       0
   268435456      67108864     float     sum      -1  8335.60   32.20   56.36       0  8343.83   32.17   56.30       0
   536870912     134217728     float     sum      -1  16152.2   33.24   58.17       0  16156.4   33.23   58.15       0
  1073741824     268435456     float     sum      -1  31795.8   33.77   59.10       0  31726.8   33.84   59.23       0
  2147483648     536870912     float     sum      -1  63104.9   34.03   59.55       0  62879.0   34.15   59.77       0
  4294967296    1073741824     float     sum      -1   125214   34.30   60.03       0   124948   34.37   60.15       0
  8589934592    2147483648     float     sum      -1   249777   34.39   60.18       0   249869   34.38   60.16       0
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 20.6596
#
# Collective test concluded: all_reduce_perf
```

Not the optimal 50GB/s, but at least here all 4 NICs are being used (~70% each):
```
lrdn2492.leonardo.local: WIRE size=8192 MiB over 4 HCAs | TX=277.9 Gb/s RX=277.9 Gb/s | util≈ 69%/69% ; per-rail: mlx5_0/p1: 69.5→69.5 Gb/s (69%/69% of 100G) | mlx5_1/p1: 69.5→69.5 Gb/s (69%/69% of 100G) | mlx5_2/p1: 69.5→69.5 Gb/s (69%/69% of 100G) | mlx5_3/p1: 69.5→69.5 Gb/s (69%/69% of 100G)
```

Without setting NCCL_PXN_DISABLE=1, it looks like this (99% on one NIC, others at 0%):
```
lrdn1631.leonardo.local: WIRE size=8192 MiB over 4 HCAs | TX=99.1 Gb/s RX=99.1 Gb/s | util≈ 25%/25% ; per-rail: mlx5_0/p1: 99.1→99.1 Gb/s (99%/99% of 100G) | mlx5_1/p1: 0.0→0.0 Gb/s (0%/0% of 100G) | mlx5_2/p1: 0.0→0.0 Gb/s (0%/0% of 100G) | mlx5_3/p1: 0.0→0.0 Gb/s (0%/0% of 100G)

```

**Comment by stephenmsachs** [comment]
We found the culrpit introduced in `v2.25.1-1` which prevents your exact node architecture to find the optimal path using the balanced tree (pattern 1) search path. This will be fixed in the next release. Thanks again for your help debugging the issue.

**Comment by sjeaugey** [comment]
For the record, here is the patch if you're willing to try applying it (and confirm it resolves the issue).

Thanks!

```
diff --git a/src/graph/search.cc b/src/graph/search.cc
index 2868b6f..bc1ea13 100644
--- a/src/graph/search.cc
+++ b/src/graph/search.cc
@@ -989,6 +989,9 @@ float sm100SpeedArrayInter[] = { 96.0, 48.0, 45.1, 42.0, 40.0, 30.0, 24.0, 22.0,
 #define NSPEEDSINTER_SM100 (sizeof(sm100SpeedArrayInter)/sizeof(float))
 
 ncclResult_t ncclTopoCompute(ncclTopoSystem* system, struct ncclTopoGraph* graph) {
+  int ccMin;
+  NCCLCHECK(ncclTopoGetCompCap(system, &ccMin, NULL));
+
   int ngpus = system->nodes[GPU].count;
   int crossNic = (system->nodes[NET].count > 1) &&
         (graph->pattern == NCCL_TOPO_PATTERN_RING ||
@@ -1008,6 +1011,8 @@ ncclResult_t ncclTopoCompute(ncclTopoSystem* system, struct ncclTopoGraph* graph
     NCCLCHECK(ncclTopoGetGpuMaxPath(system, NET, &maxTypeInter));
     maxTypeIntra = maxTypeInter;
   }
+  // Ampere relies on BALANCED_TREE which sometimes needs to come back through SYS or PHB.
+  if (ccMin < 90) maxTypeInter = PATH_SYS;
 
   graph->typeIntra = minTypeIntra;
   graph->typeInter = minTypeInter;
@@ -1031,8 +1036,6 @@ ncclResult_t ncclTopoCompute(ncclTopoSystem* system, struct ncclTopoGraph* graph
     if (graph->nChannels > 0) return ncclSuccess;
   }
 
-  int ccMin;
-  NCCLCHECK(ncclTopoGetCompCap(system, &ccMin, NULL));
   if (graph->pattern == NCCL_TOPO_PATTERN_NVLS && (system->nodes[NVS].count == 0 || ccMin < 90)) return ncclSuccess;
   // NVLS and COLLNET_DIRECT search must have ngpus heads at most.
   if (graph->pattern == NCCL_TOPO_PATTERN_NVLS) graph->maxChannels = std::min(NCCL_MAX_NVLS_ARITY, system->nodes[GPU].count);
```

**Comment by bellenlau** [comment]
The patch works, outputs of nccl allreduce test on 2 nodes (local installation) are attached. 

[log-nccl2.28-patched.txt](https://github.com/user-attachments/files/23772956/log-nccl2.28-patched.txt)
[times.txt](https://github.com/user-attachments/files/23772957/times.txt)

Thank you for your help!

**Comment by sjeaugey** [comment]
Thanks. It got merged so it should be in NCCL 2.29.
