### ISSUE TITLE
[Issue]: Fails re-loading net-pluging after comm destroy

### ISSUE THREAD

**Issue by theely** [NVIDIA/nccl#1978]
### How is this issue impacting you?

Lower performance than expected

### Share Your Debug Logs

Hi there,
Non-default NCCL network plugins specified via the `NCCL_NET_PLUGIN` environment variable fail to reload after the communicator (comm) in which they were first used is destroyed.

When a communicator is destroyed, if the network plugin has no remaining active communicator references, the plugin is unloaded. During this unload process, the plugin state is reset via a memset in [net.cc](https://github.com/NVIDIA/nccl/blob/81c7da31f98f4aa4a70317169ba8ca130839b447/src/plugin/net.cc#L86)

This reset clears the plugin’s internal status, including the custom plugin name originally provided via `NCCL_NET_PLUGIN`. As a result, when a new communicator is later created, NCCL is unable to reload the same non-default network plugin, causing plugin initialization to fail.

### Expected behavior

A network plugin specified via NCCL_NET_PLUGIN should be reloadable after all communicators using it are destroyed, provided a new communicator is subsequently created.

### Actual behavior

After the last communicator using a non-default network plugin is destroyed, the plugin is unloaded and its name is cleared, preventing successful reloading for future communicators.

Logs of the first comm creation (here the plug-in is correctly loaded)
```
NCCL INFO NCCL version 2.28.9+cuda13.0
NCCL INFO NCCL_NET_PLUGIN set by environment to oficscs
NCCL INFO NET/Plugin: Loaded net plugin Libfabric (v11)
NCCL INFO Successfully loaded external network plugin /lib/libnccl-net-oficscs.so
```

Logs of the net-pluging unload
```
NCCL INFO comm 0x4000b0e1e430 rank 1 nranks 2 cudaDev 0 busId 901000 - Destroy COMPLETE
NCCL INFO Unloading plugin oficscs
```

Logs of the second comm creation (here the plug-in fails to load and will fallback to the default one: /libnccl-net.so)
```
NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin v11 (v11)
NCCL INFO NET/Plugin: Loaded collnet plugin SHARP (v11)
NCCL INFO Successfully loaded external network plugin /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
```

p.s. I will soon submit a PR with a fix.

### Steps to Reproduce the Issue

1. set a custom nccl net plugin: export NCCL_NET_PLUGIN="xyz"
2. create a comm 
3. destroy the comm
4. create a second comm

### NCCL Version

2.28.9+cuda13.0

### Your platform details

```
Wed Jan 14 16:01:21 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 13.0     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GH200 120GB             On  |   00000009:01:00.0 Off |                    0 |
| N/A   25C    P0             89W /  900W |     990MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GH200 120GB             On  |   00000019:01:00.0 Off |                    0 |
| N/A   25C    P0             96W /  900W |     982MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GH200 120GB             On  |   00000029:01:00.0 Off |                    0 |
| N/A   25C    P0             85W /  900W |     990MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GH200 120GB             On  |   00000039:01:00.0 Off |                    0 |
| N/A   23C    P0             82W /  900W |     986MiB /  97871MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by xiaofanl-nvidia** [comment]
++ @gcongiu , @nv-udeodhar

**Comment by teojgo** [comment]
@theely a fix for this is included in the upcoming release https://github.com/NVIDIA/nccl/tree/v2.30. Can you test and confirm that it resolves the issue?

**Comment by theely** [comment]
Hi Theo,
I can confirm that v2.30 resolves the issue 👍
Thanks,
Elia

**Comment by teojgo** [comment]
@theely Thank you for the update. I am going to close the issue, now. You can also close the corresponding PR.
