### ISSUE TITLE
[Issue]: libnccl2 deb pkg does not run ldconfig.

### ISSUE THREAD

**Issue by xkszltl** [NVIDIA/nccl#1991]
### How is this issue impacting you?

Application crash

### Share Your Debug Logs

This is a bug in the prebuilt mccl packages for Ubuntu 24.04, this one the be more specific:
- https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/libnccl2_2.29.2-1+cuda12.9_amd64.deb

We found that after installation of `apt-get install libnccl2=2.29.2-1+cuda12.9`, there is nothing in `ldconfig -p | grep nccl`, unless we run `ldconfig` first.
We are not sure if it is a new regression or something lasting longer, because nccl is usually installed together with other CUDA pkgs in our builds and others would trigger` ldconfig` anyway.

### Steps to Reproduce the Issue

Assuming all dependencies are pre-installed in previous run of apt-get, to ensure nothing else would trigger ldconfig in this run:
```
apt-get install libnccl2=2.29.2-1+cuda12.9
ldconfig -p | grep nccl    # Nothing
ldconfig
ldconfig -p | grep nccl    # Got libnccl.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnccl.so.2
```

### NCCL Version

libnccl2=2.29.2-1+cuda12.9

### Your platform details

Ubuntu 24.04 docker.

**Comment by sjeaugey** [comment]
Thanks for the report. We'll look into it.

**Comment by teojgo** [comment]
@xkszltl it is now fixed with the latest version `libnccl2_2.29.3-1+cuda12.9_amd64.deb`.

**Comment by xkszltl** [comment]
@teojgo Thanks!
