### ISSUE TITLE
[Issue]: CE collectives fail if they are run on default cuda stream

### ISSUE THREAD

**Issue by ngoyal2707** [NVIDIA/nccl#2003]
### How is this issue impacting you?

Application crash

### Share Your Debug Logs

`cudaMemcpyBatchAsync` fails when default stream is passed with `invalid attribute error`.

pytorch latest now defaults to using user stream for when `async_op=False`. So when we use ce_collectives with pytorch in `async_op=False` mode, default stream gets passed to `cudaMemcpyBatchAsync` and NCCL fails with `RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)`

Maybe it cant be solved in NCCL but if so, might be better to handle this gracefully by raising some error about the stream can't be default stream.

### NCCL Version

2.29.2+cuda13.1

**Comment by teojgo** [comment]
@ngoyal2707 do you have a reproducer for this problem?

**Comment by kwen2501** [comment]
Thanks for trying the feature. 
It is a known limitation that NCCL CE collectives does not work with default CUDA stream as of 2.28.
Please refer to the following [documentation](https://docs.pytorch.org/docs/main/distributed.html#copy-engine-collectives) in PyTorch on how to work around this limitation:

<img width="1427" height="415" alt="Image" src="https://github.com/user-attachments/assets/7cd2aaa9-9537-4c73-a771-516e482786df" />

**Comment by ngoyal2707** [comment]
Thanks @kwen2501 for sharing the PT docs link, I have been also forcing the non default stream and it works.

The issue was mainly that maybe we can detect the cuda_stream being default sooner and fail with better error message in NCCL.

**Comment by nvcastet** [comment]
A WAR is to set the CE threshold (default to 8MiB) to a large value, aka `NCCL_SYM_CE_THRESHOLD=1000000000000`

**Comment by xiaofanl-nvidia** [comment]
@zhenhaohe pulled in the fix for this issue as part of 2.29.7: https://github.com/NVIDIA/nccl/releases/tag/v2.29.7-1

> Fall back to cudaMemcpyAsync API when null/default stream is used for CE-based collective operations.

@ngoyal2707 could you try out the new release and see if that works?
