### ISSUE TITLE
[Issue]: RuntimeError: NCCL Error 2 & ibv_modify_qp timeout (errno 110) during Distributed Checkpoint saving on 8 nodes (RoCE v2)

### ISSUE THREAD

**Issue by x632701882** [NVIDIA/nccl#2013]
### How is this issue impacting you?

Lower performance than expected

### Share Your Debug Logs

I am training a large model (HunyuanVideo) using PyTorch FSDP and torch.distributed.checkpoint (DCP). The training process runs perfectly fine (loss decreases, communication works) on 2, 4, and 6 nodes.

However, when scaling up to 8 nodes (64 GPUs), the job consistently crashes specifically during the checkpoint saving phase (dcp.save).

🔧 Steps Taken (Troubleshooting)
I have tried the following configurations, but the error persists:

Setting GID Index: export NCCL_IB_GID_INDEX=3 (Verified correct via system check). Result: No change.

Disabling P2P (Attempting to force routing via intermediate nodes): export NCCL_P2P_DISABLE=1 Result: Still times out.

Disabling IB entirely (Fallback to TCP): export NCCL_IB_DISABLE=1 Result: Even with TCP, Rank 0 seems to hang or timeout during the Gather phase, possibly due to CPU starvation or I/O blocking when handling metadata from 64 ranks.

### NCCL Version

2.21.5+cuda12.4

### Your platform details

NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H800                    Off |   00000000:18:00.0 Off |                    0 |
| N/A   69C    P0            488W /  700W |   51678MiB / 143771MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H800                    Off |   00000000:38:00.0 Off |                    0 |
| N/A   70C    P0            610W /  700W |   51706MiB / 143771MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H800                    Off |   00000000:48:00.0 Off |                    0 |
| N/A   56C    P0            593W /  700W |   51720MiB / 143771MiB |    100%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H800                    Off |   00000000:59:00.0 Off |                    0 |
| N/A   58C    P0            622W /  700W |   51496MiB / 143771MiB |     96%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H800                    Off |   00000000:98:00.0 Off |                    0 |
| N/A   71C    P0            539W /  700W |   51674MiB / 143771MiB |     97%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H800                    Off |   00000000:B8:00.0 Off |                    0 |
| N/A   67C    P0            666W /  700W |   51718MiB / 143771MiB |     96%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H800                    Off |   00000000:C8:00.0 Off |                    0 |
| N/A   56C    P0            658W /  700W |   51716MiB / 143771MiB |     96%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H800                    Off |   00000000:D9:00.0 Off |                    0 |
| N/A   60C    P0            655W /  700W |   51234MiB / 143771MiB |     96%      Default |
|                                         |                        |             Disabled |
Environment: cloud

2, 4, 6 Nodes: Works perfectly.

8 Nodes: Training (Ring AllReduce) works fine, but dcp.save (Star/Gather pattern) fails.
 
PyTorch Version: 2.6.0

NCCL Version: 2.21.5

OS: Linux (Containerized environment)

Network: RoCE v2

Hardware: 8 Nodes x 8 GPUs (Total 64 ranks)

Network Interface Config:

bond0: Main TCP interface (Master, valid IP).

roce_bond0 - roce_bond7: RDMA interfaces.

eth0: Slave interface without IP (should be ignored).

### Error Message & Behavior

ibvwrap.c:174 NCCL WARN Call to ibv_modify_qp failed with error Connection timed out errno 110
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4006, in gather
[rank0]:     work = group.gather(output_tensors, input_tensors, opts)
[rank0]: RuntimeError: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

**Comment by x632701882** [comment]
debugs log
master node:
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] ibvwrap.c:174 NCCL WARN Call to ibv_modify_qp failed with error Connection timed out errno 110
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO transport/net.cc:837 -> 2
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO proxyProgressAsync opId=0x7fa7dcdef198 op.type=4 op.reqBuff=0x7fa7ed43efe0 op.respSize=21040 done
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO ncclPollProxyResponse Received new opId=0x7fa7dcdef198
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO Received and initiated operation=Connect res=0
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO Queuing opId=0x7fa7dcdef198 respBuff=0x7fa7dcfdec10 respSize=21040
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO ncclPollProxyResponse Dequeued cached opId=0x7fa7dcdef198
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO transport/net.cc:405 -> 2
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO transport.cc:183 -> 2
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO group.cc:110 -> 2
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2961 [0] NCCL INFO group.cc:64 -> 2 [Async thread]
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:940 [0] NCCL INFO group.cc:418 -> 2
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:940 [0] NCCL INFO group.cc:95 -> 2
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO transport/net.cc:894 Cuda Host Alloc Size 8192 pointer 0x7fadb1c6a400
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO proxyProgressAsync opId=0x7fa7dcdef4e0 op.type=4 op.reqBuff=0x7fa7ed454fe0 op.respSize=21040 done
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO socketProgressOpt: abort called
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO misc/socket.cc:47 -> 3
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO misc/socket.cc:58 -> 3
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO misc/socket.cc:775 -> 3
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO proxy.cc:1395 -> 3

cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] proxy.cc:1546 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=3, closing connection
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO socketProgressOpt: abort called
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] NCCL INFO misc/socket.cc:826 -> 3

cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] proxy.cc:1556 NCCL WARN [Service thread] Could not receive type from localRank 0, res=3, closed=0

cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2944 [0] proxy.cc:1580 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 3
cce-training-h-lab-gy1-nodepool-hxx-67ng5:940:2945 [0] NCCL INFO [Proxy Service UDS] exit: stop 0 abortFlag 1
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ma-user/code/train.py", line 1118, in <module>
[rank0]:     main()
[rank0]:   File "/home/ma-user/code/train.py", line 1114, in main
[rank0]:     trainer.train(dataloader)
[rank0]:   File "/home/ma-user/code/train.py", line 893, in train
[rank0]:     self.save_checkpoint(self.global_step + 1)
[rank0]:   File "/home/ma-user/code/train.py", line 752, in save_checkpoint
[rank0]:     dcp.save(
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/checkpoint/logger.py", line 83, in wrapper
[rank0]:     result = func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 429, in inner_func
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 152, in save
[rank0]:     return _save_state_dict(
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 317, in _save_state_dict
[rank0]:     central_plan: SavePlan = distW.reduce_scatter("plan", local_step, global_step)
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 168, in reduce_scatter
[rank0]:     all_data = self.gather_object(local_data)
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 107, in gather_object
[rank0]:     dist.gather_object(
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3164, in gather_object
[rank0]:     gather(
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/cuijh_hy/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4006, in gather
[rank0]:     work = group.gather(output_tensors, input_tensors, opts)
[rank0]: RuntimeError: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

**Comment by stephenmsachs** [comment]
Hi @x632701882, thanks for reporting this issue. `Call to ibv_modify_qp failed with error Connection timed out errno 110` often indicates that the NICs are unable to communicate. Since you report that Ring Allreduce works fine and Gather fails, I suspect that you might be running on a rail connected system, meaning only NICs with the same local number are able to communicate.

Can you try setting `NCCL_CROSS_NIC=0`?

**Comment by masamokkulu** [comment]
I encountered the same issue while running nccl-tests. With CUDA 12.9 + NCCL 2.27, it crashes with the following error when running on 7 or more HGX nodes.
```bash
[2026-03-13 22:26:02] host-01.example.com:XXXXXX [5] ibvwrap.c:262 NCCL WARN Call to ibv_modify_qp failed with 110 Connection timed out, on dev mlx_x:1, curr state INIT, next state RTR, local GID index 3, local GID ::ffff:xxx.xx.xx.xx, remote GID ::ffff:xxx.xx.xxx.xx
```
Setting `NCCL_CROSS_NIC=0` worked for me.

Alternatively, the issue was also resolved by using the combination of CUDA 13.1 + NCCL 2.29.
