### ISSUE TITLE
ncclCommInitRank failed

### ISSUE THREAD

**Issue by guru4elephant** [NVIDIA/nccl#210]
when I try to call ncclCommInitRank with NCCL_DEBUG=WARN，the following warnings are listed.

I use mpirun -np 4 python xx.py

where I wrap nccl init in the singleton that can be initialized through pybind, but I find rank 0 will hang when I call ncclcommInitRank and all ranks report the following warning.

include/socket.h:344 WARN Socket creation failed : Address family not supported by protocol

Anything to help me fix out the problem?

**Comment by kwen2501** [comment]
Is your run on a single node or multiple nodes? If it is the latter case, could it be that one of the nodes (most likely node 0) has IPv6 configured while the other nodes only have IPv4 ? (Or the other way around.)
Setting `NCCL_DEBUG=INFO` and `NCCL_DEBUG_SUBSYS=NET` may show more information. Running `ifconfig` on each node would be helpful too.

**Comment by guru4elephant** [comment]
I'm runing my program on single node, with multiple processes started with mpirun -np 4
![image](https://user-images.githubusercontent.com/35550832/56483431-8eb0d300-64fc-11e9-9e37-39d32ed1ac48.png)
I found these information, could you give me more hint to handle the problem?

**Comment by kwen2501** [comment]
Thanks. As the log indicates, there is no IP interface found on the machine. An IP interface is needed by NCCL to do bootstrap in multi-process cases, even on a single node. You can check by running `ifconfig`. You can also check if `NCCL_SOCKET_IFNAME` is set to anything in your environment. Btw, which NCCL version are you using?

**Comment by guru4elephant** [comment]
Thanks for your response.
here is the ifconfig result.
![image](https://user-images.githubusercontent.com/35550832/56506657-c5fd9f00-6551-11e9-9344-66aed0a1c596.png)
NCCL_SOCKET_IFNAME is empty in my environment.
I use nccl 2.2.13 version.

**Comment by kwen2501** [comment]
Hmm, weird, would setting `NCCL_SOCKET_IFNAME=xgbe0` or `NCCL_SOCKET_IFNAME=lo` help? If still not working, please check if `NCCL_SOCKET_FAMILY` is empty.

**Comment by guru4elephant** [comment]
Hmm, weird, would setting NCCL_SOCKET_IFNAME=xgbe0 or NCCL_SOCKET_IFNAME=lo help? No.
NCCL_SOCKET_FAMILY is empty indeed..

**Comment by guru4elephant** [comment]
I've also found this, but it didn't work in my environment:(
https://devtalk.nvidia.com/default/topic/1023946/nccl-2-0-support-inter-node-communication-using-sockets-/

**Comment by guru4elephant** [comment]
> Hmm, weird, would setting `NCCL_SOCKET_IFNAME=xgbe0` or `NCCL_SOCKET_IFNAME=lo` help? If still not working, please check if `NCCL_SOCKET_FAMILY` is empty.

Finally I figured out the problem. I set eth0 as the default NCCL_SOCKET_IFNAME and xgbe0 does not overwrite the environment due to my code problem. Thanks for your help.
