### ISSUE TITLE
[BUG] NCCL 2.30.4 NVLS code path hangs MoE expert weight loading on 8× DGX Spark (sm_121, no NVLink); 2.30.3 works

### ISSUE THREAD

**Issue by idonati** [NVIDIA/nccl#2167]
## Summary

NCCL 2.30.4 introduces a regression on hardware without NVLink (DGX Spark / GB10 / sm_121, C2C + RoCE interconnect): cluster operations hang silently during high-expert-count MoE weight loading at TP=8 across 8 nodes, with no error logged. NCCL 2.30.3 on the same stack does not exhibit this. Workaround: `NCCL_NVLS_ENABLE=0`.

## Environment

- **Hardware:** 8× NVIDIA DGX Spark, GB10 Superchip (sm_121, aarch64, 121 GiB unified memory)
- **Interconnect:** ConnectX-7 dual-rail 200 Gb/s RoCE (NO NVLink between nodes; NVLS should be a no-op)
- **OS:** Ubuntu 24.04.4 LTS, kernel 6.17.0-1014-nvidia
- **GPU driver:** 580.142
- **CUDA:** 13.0
- **PyTorch:** 2.11.0+cu130
- **NCCL versions tested (same hardware, same workload):**
  | Version | Source | Result |
  |---|---|---|
  | 2.29.7 | apt `libnccl2 2.29.7-1+cuda13.2` | ✅ works |
  | 2.30.3 | pip `nvidia-nccl-cu13==2.30.3` | ✅ works |
  | 2.30.4 | pip `nvidia-nccl-cu13==2.30.4` | ❌ hangs (this bug) |
- **Workload:** vLLM v0.1.dev1+g6232fb4 with TP=8 across 8 nodes, Ray distributed executor backend

## Reproducer

Multi-node TP=8 vLLM serve of a high-expert-count MoE model:

```bash
vllm serve <Kimi K2.6-NVFP4>  \
  --tensor-parallel-size 8 \
  --distributed-executor-backend ray \
  --enforce-eager \
  --kv-cache-dtype fp8 \
  --load-format safetensors
```

Model architecture: 384 routed experts (Kimi K2.6), ~550 GB checkpoint at NVFP4, ~70 GB / rank weights.

## Symptom

- Cluster boots, all 8 ranks initialize, vLLM logs `pynccl.py:111 vLLM is using nccl==2.30.4`
- Weight loading begins on all ranks
- Some ranks complete weight loading in ~5 min; others hang in MoE expert weight loader
- Engine periodic logger output stops appearing
- After 40+ minutes of silence, py-spy on hung worker shows:
  ```
  Thread N (active): "MainThread"
      _load_w2 (vllm/model_executor/layers/fused_moe/layer.py:1023)
      _load_model_weight_or_group_weight_scale (vllm/model_executor/layers/fused_moe/layer.py:843)
      weight_loader (vllm/model_executor/layers/fused_moe/layer.py:1371)
      load_weights (vllm/model_executor/models/deepseek_v2.py:1660)
      ...
  ```
- **No NCCL error logged in stderr (even with `NCCL_DEBUG=INFO`)**
- API server never reaches "Application startup complete"
- `/v1/models` endpoint never comes online

## What rules out non-NCCL causes

Same image, same hardware, same vLLM commit:
- NCCL 2.29.7 (apt) → works
- NCCL 2.30.3 (pip) → works
- NCCL 2.30.4 (pip) → hangs

Only changing the NCCL .so produces the hang. The pip-installed 2.30.4 is correctly resolved (verified via `ctypes.CDLL(...).ncclGetVersion()` reporting `2.30.4` and vLLM's pynccl reporting `using nccl==2.30.4`).

## What rules out the bug being workload-specific to vLLM/Ray

The exact same NCCL 2.30.4 build on the exact same 8-node TP=8 hardware **works for 3 other MoE models on the same vLLM/Ray stack**:

| Model | MoE experts | Result on NCCL 2.30.4 |
|---|---|---|
| Kimi K2.6 | 384 routed | ❌ hangs |
| DeepSeek V4-Pro | ~256 routed | ✅ works |
| DeepSeek V4-Flash | ~64 routed | ✅ works |
| GLM-5.1-NVFP4 | smaller MoE | ✅ works |

So the hang is correlated with MoE expert count or some MoE-init shape-dependent code path that 2.30.4's NVLS code triggers but 2.30.3 doesn't.

## Workaround

Setting `NCCL_NVLS_ENABLE=0` eliminates the hang. Verified by binary search:
- `NVLS_ENABLE=0` + `SYMM_MEM_DISABLE=1` → works (initial Test E)
- **`NVLS_ENABLE=0` only → works (sufficient)**
- `SYMM_MEM_DISABLE=1` only → not tested (may also work, NVLS is the prime suspect)

After the workaround, K2.6 runs a 30-prompt sustained sweep cleanly at 10.77 tok/s with no degradation vs the NCCL 2.29.7 baseline.

This workaround is "free" for our setup since NVLink is absent (NVLS is no-op on C2C/RoCE). Filing in case the regression affects systems where NVLS is genuinely active.

## Hypothesis

NCCL 2.30.4 changelog includes NVLS-related work. The detection / setup / collective-prepare phase appears to have a code path triggered by some combination of:
- High expert-count MoE weight broadcasts (≥256 experts seemed to be the threshold; ours is 384)
- 8-node × 1 GPU topology over RoCE (no NVLink)
- aarch64 / sm_121

That hangs silently during the load-weight phase. NCCL 2.30.3 (one version back) does not exhibit it on the same workload.

## Available diagnostics

Happy to provide:
- Full `NCCL_DEBUG=INFO` logs from a hanging boot
- Full py-spy stacks for all 8 worker processes
- Full vLLM + Ray engine logs

Hardware is in production use, but I can re-run the failing config on demand for further diagnostics.

## Related

- vLLM #40969 — original "wedge" bug we were chasing (separate issue, also fixed by upgrading NCCL to 2.30.4 on the other 3 of our 4 production models). The K2.6 case is what required the NVLS-disable workaround documented above.

**Comment by xiaofanl-nvidia** [comment]
@idonati Thanks for reporting the issue. However this is strange and may require some triaging. High-level thoughts here: 
- Between 2.30.3 and 2.30.4, there is only one meaningful feature https://github.com/NVIDIA/nccl/commit/6ea3fe4e12c6501695bb5a2018be94d1af079d40. That commit shoudn't have any NVLS impact. 
- DGX-Spark does not support NVLS to begin with so enable vs. disable should make no difference. 
- Could it be possible that the issue is intermittent and the intermittence is misleading the conclusions? 

> NCCL 2.30.4 changelog includes NVLS-related work. 

Could you point me to the commit you are referring to? 

> That hangs silently during the load-weight phase.

Could you please share the NCCL_DEBUG=INFO logs and see if you could capture a stack trace on all hanging ranks? Thanks! 
Also, could you confirm the expected NCCL API/operation for the load-weight phase? E.g. the workload is MoE but I assume you are using something like send/recv or broadcast around of the place of hang?

**Comment by idonati** [comment]
@xiaofanl-nvidia thanks for the careful pushback. **You were right — your intermittence concern was valid.** Posting an honest correction.

## Re-tested with controlled boots tonight

I ran the exact same configuration (NCCL 2.30.4 + no `NCCL_NVLS_ENABLE` override + `NCCL_DEBUG=WARN`) that yesterday hung **twice in a row**. Tonight's boot of that same configuration came up cleanly and ran a 30/30 prompt sustained sweep at ~10.75 tok/s.

Updated boot-state matrix:

| Configuration | Hangs / Total boots tested |
|---|---|
| NCCL 2.30.4 + NVLS default + `DEBUG=WARN` | **2 / 3** (yesterday Initial + Test A hung; today Boot 3 worked) |
| NCCL 2.30.4 + NVLS default + `DEBUG=INFO` | 0 / 1 (today Boot 1) |
| NCCL 2.30.4 + `NVLS_ENABLE=0` + `DEBUG=WARN` | 0 / 1 (yesterday Test F) |
| NCCL 2.30.4 + `NVLS_ENABLE=0` + `DEBUG=INFO` + `SYMM_MEM_DISABLE=1` | 0 / 1 (yesterday Test E) |
| NCCL 2.30.3 + NVLS default + `DEBUG=WARN` | 0 / 1 (yesterday Test D) |
| NCCL 2.29.7 + NVLS default + `DEBUG=WARN` (apt-system NCCL) | **0 / dozens** (production baseline ~1 week, no hang ever observed) |

## Retraction

The original report's claim that **`NCCL_NVLS_ENABLE=0` deterministically fixes the hang is unsupported by the data**. With the actual 2/3 vs 0/1 split for the only two configurations with multi-boot data, sample sizes are far too small for a causal conclusion — every "fix" I attributed (NVLS off, SYMM-mem off, NCCL 2.30.3 fallback) could just as well be coincidental misses. Apologies for the premature attribution.

## What appears to be real

NCCL 2.29.7 has run as our K2.6 production baseline for ~1 week with dozens of cold-start boots and zero observed hangs. NCCL 2.30.4 has produced 2 hangs in ~3 attempts with the exact same vLLM + Ray + workload otherwise. So **NCCL 2.30.4 does appear to introduce an intermittent boot hang** that 2.29.7 doesn't have, on this hardware/workload — but the rate isn't 100% and the trigger is not yet identified.

## What I can offer next

If a more rigorous statistical characterization would help your triage, I'm happy to:

1. Run **N consecutive boots of the failing config** (default 2.30.4 + DEBUG=INFO, no env-var overrides) and report the actual hang rate. Cost: ~30 min per boot, would need ~10–20 boots for a meaningful estimate.
2. Capture **`NCCL_DEBUG=INFO` logs and py-spy from all 8 ranks on a hung boot** when one occurs. Today's hung-config attempt happened to succeed, so I don't yet have INFO logs from a hung run.
3. Test specific suspect configurations (e.g. `NCCL_PROTO=Simple`, `NCCL_ALGO=Ring`, etc.) to narrow the trigger if you have ideas.

For our cluster's production stability, I'm keeping `NCCL_NVLS_ENABLE=0` in our K2.6 recipe as a no-op-on-this-hardware belt-and-suspenders setting (DGX Spark has no NVLink so disabling NVLS is functionally free, regardless of whether it helps with intermittence). But I'm no longer claiming it's the cause/fix.

Will update the issue title once I gather better statistical evidence. For now: real intermittent hang on 2.30.4 vs zero on 2.29.7, but the suggested fix attribution was wrong.

Re your specific questions:

> Could you point me to the commit you are referring to?

I can't — I don't have evidence linking the regression to a specific NCCL commit. The "NVLS-related work" claim in my original report was inferred from the env var that *appeared* to fix the issue, which I now retract. If you can suggest specific 2.30.3→2.30.4 commits that might affect 8-node multi-host multi-GPU collective init or topology detection on aarch64 + sm_121, I can target those for diagnostic.

> Could you please share the NCCL_DEBUG=INFO logs and see if you could capture a stack trace on all hanging ranks?

The hanging boots I had didn't have `DEBUG=INFO` set; they were `DEBUG=WARN` (per default vLLM recipe). Today's `DEBUG=INFO` boot didn't reproduce. Will run the diagnostic loop to capture both.

> Could you confirm the expected NCCL API/operation for the load-weight phase? E.g. the workload is MoE but I assume you are using something like send/recv or broadcast around of the place of hang?

vLLM's TP weight load broadcasts the loaded shards across the TP group at certain layer-init points, and MoE expert weights go through a `weight_loader` path that triggers `param.data.copy_()` — under the covers this can involve `torch.distributed.broadcast` / NCCL `Broadcast`. The py-spy stack from yesterday's hung boot was consistent with being inside `_load_w2` (vllm/model_executor/layers/fused_moe/layer.py) with the actual NCCL operation not visible in the Python frame (likely a call descended into a CUDA op that's blocked). I'll get the C-level stack via `gdb` next time we get a hang, alongside `NCCL_DEBUG=INFO`.

Apologies again for the premature causal claim. The intermittence was the actual bug pattern.

**Comment by j0nsoft** [comment]
Adding a data point that may help - I have what appears to be a 100% reliable reproducer of a similar (possibly same) hang on a smaller topology. So if this issue does relate to NCCL then I can run any narrowing experiments required.

### Setup

- **Hardware**: 2× DGX Spark (GB10, sm_121, aarch64), ConnectX-7 RoCE, no NVLink
- **Model**: **DeepSeek-V4-Flash** (256 routed experts globally per the EP rank log: Local/global number of experts: 128/256) — note this is in your "works" table, but I observe a hang
- **Topology**: TP=2 across 2 nodes, --enable-expert-parallel (EP=2)
- **Distributed executor**: vLLM's native` MultiprocExecutor` (i.e. `--distributed-executor-backend mp`, the default), not Ray. Worth flagging since @idonati 's reproducer uses `--distributed-executor-backend ray`

### Versions tested

- **NCCL 2.30.4** (current public release, vLLM-bundled pynccl) → **hangs every boot**, no exceptions
- **NCCL 2.30.6a0** (internal pre-release from the v2.30u1 branch, git nccl4py-v0.2.0-348-g0d9b8d4, picked up via a vLLM nightly wheel) → **works every boot**

Flagging explicitly that `2.30.6a0` is **not a public release** — there's no `2.30.5` or `2.30.6` on PyPI, in NGC, or in apt as of today. So this isn't a "just upgrade" situation for anyone hitting this in the wild on stable channels; the fix (if it is one) appears to live only on an internal branch right now. Posting in case that's useful signal that the `v2.30u1` work resolves the regression and should make it into the next public NCCL release.

### Logs

- Hanging: [deepseek-v4-flash_2026-05-26.log](https://github.com/user-attachments/files/28254171/deepseek-v4-flash_2026-05-26.log)
- Working: [deepseek-v4-flash-jasl.log](https://github.com/user-attachments/files/28254251/deepseek-v4-flash-jasl.log)

### Symptom
Silent hang. Last vLLM line is `mxfp4.py:1683 Using MoEPrepareAndFinalizeNoDPEPModular`, immediately after `Loading weights took 135.37 seconds`. So **for me, the hang is at MoE communicator setup after weight load completes**, not inside `_load_w2` like @idonati 's py-spy showed. Could be the same bug surfacing at a different call site, or a separate one - flagging the difference for you to judge.

Both nodes then OOM and become unresponsive to `sudo reboot`, requiring hard power-cycle.

### Re: NVLS workaround
Confirming @idonati 's retraction from his follow-up: `NCCL_NVLS_ENABLE=0` does not fix it for me. Verified via log line:

```
spark-3cc2:217:217 [0] NCCL INFO NCCL_NVLS_ENABLE set by environment to 0.
```

Hang is identical with or without this env var. So whatever the trigger is, it's not gated on the NVLS code path being active.

### Why this might help triage

- **Reliable trigger**: If @idonati's repro intermittence has blocked narrowing this, my config reproduces 100% on a 2-node setup
- **Wider trigger surface than the original report suggests**: A hang on V4-Flash + EP=2 + 2 nodes shows the bug isn't gated on K2.6's 384-expert count or 8-node topology. (Minor correction to the table in the original report: V4-Flash is 256 experts globally, not ~64 — that figure may be the per-token routing topk.)
- **Possible internal-branch fix**: The 2.30.4 hang vs 2.30.6a0 (v2.30u1) success on otherwise-similar stacks is consistent with a regression that's already been worked on internally but not yet released publicly. Confirming/denying that would itself be useful.

### Caveat
The two runs above also differ in vLLM commit (`dev1365` vs `dev1315`) and a few flag values (`max_model_len`, `gpu_memory_utilization`, `max_num_seqs`). Strictly I have a "works vs doesn't" comparison, not a clean NCCL-only bisection.

**Comment by stephenmsachs** [comment]
Hi @j0nsoft. Thanks for reporting and joining the discussion. Since your hardware setup does not include NVLink, I would not expect this to be the same issue. Would you mind opening a separate issue with your findings? From the attached logs it is not yet clear where the culprit lies. I can see that the older version uses 16 channels, while the newer one uses 64. Would you be able to provide the logs with `NCCL_DEBUG=INFO`, `NCCL_DEBUG_SUBSYS=INIT,BOOTSTRAP,ENV,GRAPH,TUNING,NET`, 
and `NCCL_TOPO_DUMP_FILE=topo.xml`?

`2.30u1` is planned to be part of the next release, so if this is the the fix then your issue should be resolved with the next release.

**Comment by j0nsoft** [comment]
Thanks @stephenmsachs . In my case this turned out to be a regression in the vLLM fork I was using: https://github.com//vllm-project/vllm/pull/41834#issuecomment-4549010546. With this patched, I no longer see the hang or OOM issues. Many thanks for the fine work you guys do.

**Comment by stephenmsachs** [comment]
@idonati have you been able to collect those logs?
