### ISSUE TITLE
SIGSEGV in NCCL MNNVL clique enrollment at world_size>=44 on GB200 NVL72 (healthMask 0xaa)

### ISSUE THREAD

**Issue by aoshen02** [NVIDIA/nccl#2186]
# SIGSEGV in NCCL MNNVL clique enrollment at world_size>=44 on GB200 NVL72 (healthMask 0xaa)

## Summary

On a GB200 NVL72 cluster where MNNVL fabric reports `healthMask 0xaa` (4 of 8 NVL paths degraded), NCCL crashes with **SIGSEGV** during `ncclCommInitRank` MNNVL clique enrollment when `world_size >= 44`. The threshold is **sharp and deterministic** (43 passes, 44 fails). `NCCL_MNNVL_ENABLE=0` is the only known workaround.

Bug persists across:
- NCCL versions 2.27.5 and 2.30.4 (latest stable, 2026-04-23)
- `nvidia-nccl-cu12` and `nvidia-nccl-cu13` wheels
- cupy versions 13.6.0 and 14.0.1
- cupy CUDA variants (`cuda12x`, `cuda13x`)

This affects production RL training stacks (e.g. veRL using `ray.util.collective`) where train + rollout combine to ≥44 ranks across multiple GB200 nodes.

## Environment

- **Hardware**: GB200 NVL72 (≥16 nodes × 4 GPU available; tested 4–16 nodes)
- **Driver**: 580.126.09 (R580)
- **CUDA**: 12.9 (system) / 13.0 (cu13x cupy variant test)
- **NCCL versions tested (all fail)**: 2.27.5, 2.30.4
- **Python NCCL bindings tested**: cupy-cuda12x 13.6.0 + 14.0.1; cupy-cuda13x 14.0.1
- **ray.util.collective** (Ray 2.55.0)
- **torch**: 2.10.0+cu129
- Docker container, `--network host --ipc host --device /dev/nvidia-caps-imex-channels/channel0`
- NCCL net plugin: not installed (`libnccl-net.so not found` → falls back to socket)
- MNNVL fabric reports: `cliqueId 0x17 cliqueSize <N> state 3 healthMask 0xaa nvlDomainSize <N>`

## Minimal reproducer

8-rank script using `ray.util.collective` to call `init_collective_group("nccl", ...)` + `barrier()` across a ray cluster. Strips away veRL/Megatron/vLLM to isolate NCCL behavior.

```python
import argparse, socket, ray
from ray.util import collective

@ray.remote(num_gpus=1)
class W:
    def __init__(self, rank, world_size, group_name):
        self.rank, self.world_size, self.group_name = rank, world_size, group_name
        self.ip = socket.gethostbyname(socket.gethostname())

    def init_and_barrier(self):
        import torch, cupy as cp
        torch.cuda.set_device(0); cp.cuda.runtime.setDevice(0)
        collective.init_collective_group(
            self.world_size, self.rank, "nccl", self.group_name)
        print(f"[r{self.rank}@{self.ip}] init OK", flush=True)
        collective.barrier(self.group_name)  # <-- SIGSEGV here at world_size >= 44
        print(f"[r{self.rank}@{self.ip}] barrier OK", flush=True)
        return "OK"

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--world-size", type=int, required=True)
    args = p.parse_args()
    ray.init(runtime_env={"env_vars": {
        "NCCL_DEBUG": "INFO",
        "NCCL_CUMEM_ENABLE": "1",
        "NCCL_NVLS_ENABLE": "1",
        "NCCL_MNNVL_ENABLE": "1",
    }})
    ws = [W.remote(i, args.world_size, "g") for i in range(args.world_size)]
    print(ray.get([w.init_and_barrier.remote() for w in ws]))

if __name__ == "__main__":
    main()
```

Run on an 11+ node GB200 NVL72 ray cluster:

```bash
# Reliably FAILS (SIGSEGV in NCCL during ncclCommInitRank):
python3 repro.py --world-size 44

# Reliably PASSES (one rank below threshold):
python3 repro.py --world-size 43

# Workaround — reliably PASSES at any scale tested (up to 64):
NCCL_MNNVL_ENABLE=0 python3 repro.py --world-size 64
```

## Bisection — sharp threshold at world_size 44

Tested on a 16-node GB200 NVL72 cluster (64 GPU). Same NCCL env vars, same code, only `world_size` varies:

| world_size | num_nodes | result | wall-clock |
|---|---|---|---|
| 16 | 4 | ✓ PASS | ~5.6s |
| 24 | 6 | ✓ PASS | ~5.7s |
| 32 | 8 | ✓ PASS | ~5.8s |
| 40 | 10 / 12 | ✓ PASS | ~5.8s |
| 42 | 12 | ✓ PASS | ~5.8s |
| **43** | **12** | **✓ PASS** | **6.1s** ← last passing |
| **44** | **12** | **❌ FAIL (SIGSEGV)** | — ← first failing |
| 46 | 12 | ❌ FAIL | — |
| 48 | 12 | ❌ FAIL (×3 independent) | — |
| 64 | 16 | ❌ FAIL | — |

With `NCCL_MNNVL_ENABLE=0`:
- 48 ranks → PASS in 8.1s
- 64 ranks → PASS in 8.1s (no scaling cost; bootstrap is socket-based)

## NCCL_DEBUG=INFO output (last lines before crash)

```
gb200-rack1-XX:N:N [0] NCCL INFO cudaDriverVersion 13000
gb200-rack1-XX:N:N [0] NCCL INFO NCCL version 2.30.4+cuda13.0  (or 2.27.5+cuda12.9; both fail)
gb200-rack1-XX:N:N [0] NCCL INFO NET/Plugin: Could not find: libnccl-net.so.
gb200-rack1-XX:N:N [0] NCCL INFO NET/IB : No device found.
gb200-rack1-XX:N:N [0] NCCL INFO NET/Socket : Using [0]enp0s3:192.168.0.XX<0> ...
gb200-rack1-XX:N:N [0] NCCL INFO Initialized NET plugin Socket
gb200-rack1-XX:N:N [0] NCCL INFO Using network Socket
gb200-rack1-XX:N:N [0] NCCL INFO ncclCommInitRank ... rank N nranks 44 ... - Init START
gb200-rack1-XX:N:N [0] NCCL INFO MNNVL busId 0xXXXX fabric UUID 604624d54d2384dc.3413902eca5893b5 cliqueId 0x17 state 3 healthMask 0xaa
gb200-rack1-XX:N:N [0] NCCL INFO MNNVL 1 cliqueId 17 cliqueSize 44 cliqueRank N nvlDomainSize 44
gb200-rack1-XX:N:N [0] NCCL INFO Setting affinity for GPU N to 0-69
gb200-rack1-XX:N:N [0] NCCL INFO NVLS multicast support is available on dev 0 (NVLS_NCHANNELS 24)
<no further NCCL log — worker process SIGSEGVs here>
```

Ray reports the worker death:

```
Worker exit type: SYSTEM_ERROR
Worker exit detail: Worker unexpectedly exits with a connection error code 2.
End of file. Some common causes include: ... (3) the worker crashed unexpectedly due to SIGSEGV.
```

The cupy NCCL binding surfaces this as either `NCCL_ERROR_UNHANDLED_CUDA_ERROR` (if returned by NCCL before crash) or `NCCL_ERROR_REMOTE_ERROR: remote process exited` (if observed from a peer rank). Without a `libnccl-net.so` plugin we cannot enable IB and fall back to socket transport for both data and bootstrap.

## What we ruled out

| Variable | Tested | Result |
|---|---|---|
| NCCL version | 2.27.5, 2.30.4 (latest stable 2026-04-23) | both fail |
| cupy version | 13.6.0, 14.0.1 | both fail |
| cupy CUDA variant | `cuda12x`, `cuda13x` | both fail |
| Container base image | verlai/verl dev1, dev2 | both fail |
| Specific hosts (host swap) | tested every host as potential bad actor | not host-specific |
| ulimit / somaxconn | `ulimit -n=1048576`, `somaxconn=4096`, `tcp_max_syn_backlog=4096`, `conntrack_max=262144`, `port_range=32768–60999` | well below any limit |
| `NCCL_NVLS_ENABLE=0` alone | tested with MNNVL still on | still fails |
| `NCCL_CUMEM_ENABLE=0` alone | tested with MNNVL still on | still fails |
| `NCCL_MNNVL_ENABLE=0` | tested at 48 + 64 ranks | **passes — the only known workaround** |

## Hypothesis

The crash is inside NCCL's MNNVL clique enrollment logic when `cliqueSize >= 44` on hardware reporting partial fabric degradation (`healthMask 0xaa` = 4 of 8 NVL paths down). The sharp 43→44 boundary suggests a hardcoded buffer/array dimension in the MNNVL path that overflows at 44 ranks, possibly only when fabric paths are degraded (`healthMask != 0xff`).

## Asks

1. Is the 43→44 boundary a known NCCL limitation?
2. Should MNNVL clique enrollment fall back to non-MNNVL transport when `healthMask` indicates partial fabric degradation, rather than attempting to use degraded paths at scale?
3. Is there a planned fix in newer NCCL versions, or any other recommended env var to mitigate beyond `NCCL_MNNVL_ENABLE=0`?

Happy to provide full `NCCL_DEBUG=INFO` traces from any rank, core dumps, dmesg, or run additional ablations.

---

# Update 2026-05-20 — clean byte-identical evidence + reproducer artifacts + reply to @xiaofanl-nvidia

## Update — clean byte-identical repro + reply to @xiaofanl-nvidia

Thanks for the quick response. Replying to your three questions and adding new evidence from a clean byte-identical setup that rules out several confounders we discovered in the original investigation.

### Reply to your questions

> healthMask 0xaa = 4 of 8 NVL paths down — Could you explain exactly what this means? Does it mean some of the nvlinks are not usable?

We're inferring from the bitmask (`0xaa = 0b10101010`) that 4 of 8 fabric paths are flagged down by NCCL's MNNVL probe. We don't have NCCL source-level documentation for the encoding so this is our best read — if there's an authoritative interpretation we'd appreciate it.

Cluster-level fabric services appear healthy from the IMEX side:
- `nvidia-imex` is `active` on all 17 GB200 NVL72 hosts (driver 580.126.09 uniform)
- `nvidia-imex-ctl -N` reports all 18 nodes (192.168.0.101–118) as `READY` from every host
- `/etc/nvidia-imex/nodes_config.cfg` is byte-identical (md5 60108257a6f9...) across the cluster
- `nvidia-fabricmanager` is `failed` on all hosts — but this is expected on GB200 NVL5 (replaced by IMEX); confirmed by `journalctl -u nvidia-fabricmanager` reporting "Detected Pre-NVL5 system"

So the `0xaa` bitmask is being reported by NCCL/NVML even though the IMEX control plane is otherwise healthy. We can't tell from the outside whether NCCL is reading this from hardware status, NVML, or its own probe.

> Does this issue reproduce when all links are healthy?

We don't have a `healthMask 0xff` baseline on this cluster to compare against — the fabric reports `0xaa` consistently across every host, every reboot, every container restart. We've opened a parallel ticket with our cloud provider (GCP) to investigate why the fabric is in this state on a production GB200 SKU. If anyone in NVIDIA can advise whether `0xaa` is ever an expected state on GB200 NVL72, or whether it always indicates physical/driver-level degradation, that would help us scope the GCP-side fix.

> In general, I'm not sure NCCL official support operations on unhealthy fabric. What is your use case for this support instead of fixing the fabric?

Two requests, in priority order:

1. **Defensive crash handling**, not full operation on unhealthy fabric. A SIGSEGV inside `ncclCommInitRank` is hard to debug from user code — NCCL surfaces it to peer ranks as `NCCL_ERROR_REMOTE_ERROR` and the actual root-cause stack is lost. If NCCL detects partial fabric degradation that would make MNNVL unsafe at the requested scale, returning `NCCL_ERROR_UNSUPPORTED` (or falling back to non-MNNVL transport) would be much easier to handle — and would let users like us discover the issue from a log line, not a worker SIGSEGV.

2. **Workaround for our use case**: We're running production RL training (Qwen3-235B-A22B SWE-bench) on this cluster while the fabric issue is investigated by the cloud provider. `NCCL_MNNVL_ENABLE=0` lets us proceed (NCCL falls back to socket bootstrap; since this cluster has no `libnccl-net.so` plugin, the data plane already uses socket — so there's no measurable perf cost). This is the only known workaround and it works reliably; we just want to confirm with you that it's a safe long-term mitigation while the fabric question is sorted out separately.

### New evidence — clean byte-identical 14-node sweep

Since the original report, we destroyed and rebuilt all containers from a single image (sha256 verified identical across nodes) to eliminate any pip/package drift confounder. All nodes now run **identical**: `cupy 13.6.0 + numpy 1.26.4 + NCCL 2.27.5+cuda12.9` (verified per-node).

Full sweep on the clean cluster, expanding from 11 to 14 nodes one at a time:

| world_size | nodes | cliqueSize | healthMask | result | wall-clock |
|---|---|---|---|---|---|
| 36 | 11 | 36 | 0xaa | ✅ PASS | 5.9s |
| 40 | 11 | 40 | 0xaa | ✅ PASS | 6.0s |
| **44** | **11** | **44** | **0xaa** | **❌ FAIL (SIGSEGV)** | timeout |
| 48 | 12 | 48 | 0xaa | ❌ FAIL (SIGSEGV) | timeout |
| 52 | 13 | 52 | 0xaa | ❌ FAIL (SIGSEGV) | timeout |
| 56 | 14 | 56 | 0xaa | ❌ FAIL (SIGSEGV) | timeout |

Sharp threshold at `cliqueSize=44`. All `≥44` cases fail with the same signature (cliqueSize=N, healthMask=0xaa, SIGSEGV in `ncclCommInitRank`). The threshold is **strictly a function of NCCL `cliqueSize`** — not of the specific 11/12/13/14 nodes selected, not of which rack the additional node lives on, not of network or system load.

### New finding — NCCL 2.30.4 lowers the threshold to 40

After uninstalling `nvidia-nccl-cu13` (which was bundled in one of our earlier test image variants), we ran the same sweep again on the **same hardware** with NCCL 2.27.5 (system) vs the previously bundled 2.30.4 (pip wheel):

| NCCL version | cliqueSize threshold (first FAIL) | Last PASS |
|---|---|---|
| 2.27.5+cuda12.9 | **44** | 43 |
| 2.30.4+cuda13.2 | **40** | 36 |

So **upgrading to NCCL 2.30.4 makes the bug worse, not better** (the bug triggers 4 ranks earlier). This is a single-variable swap on a clean image — only the NCCL `.so` differs between the two runs, everything else (cupy, numpy, image layers, hosts) is identical. We'd expect the underlying buffer/array dimension issue to be NCCL-internal, not cupy- or framework-side, and the version delta confirms this is moving with NCCL releases.

### Confounders we ruled out in the rebuild

A few things we initially suspected but proved are *not* the cause:

- **Specific outlier node**: We swapped 3 different nodes through the cluster (rack1-04, rack1-05 [which had a separate user's vLLM workers], rack1-09, rack1-13, rack1-16, rack1-03), and the 44-rank FAIL is reproducible on every 11-node subset we tried. No node-specific outlier.
- **Pip package drift across containers**: Originally some containers had cupy 14.0.1 (upgraded during ablation) while a freshly-started container still had cupy 13.6.0 — produced `TypeError: Argument 'commId' has incorrect type (expected tuple, got bytes)` (cupy API change). Rebuilding from the same image eliminates this. Threshold is unchanged after rebuild.
- **Container image / mbridge / Megatron**: The bug reproduces in a stripped-down image (`verlai/verl:vllm018.aarch64.dev1` base + just `cupy + mbridge`) with no veRL / Megatron / vLLM in the import path.
- **NCCL net plugin**: Confirmed absent on this cluster (`libnccl-net.so: cannot open`). Bug reproduces with socket transport only, no IB plugin involved.
- **Reboots / IMEX restarts / GCP host events**: One node (rack1-06) had a kernel-level reboot during the investigation (separate GCP host event, not our action). After the reboot, the same sweep on the same cluster including rack1-06 produces the same threshold.

### Reproducer

Repro script and full logs are at the paths in the original report. Same `repro.py`, just runnable across 11/12/13/14-node ray clusters with `--world-size 36/40/44/48/52/56`. Happy to share the cleaned-up version + per-rank NCCL_DEBUG=INFO traces.

### Asks (updated)

1. Is `healthMask 0xaa` ever a legitimate state on GB200 NVL72, or does it always indicate physical/driver-level degradation we need our cloud provider to fix?
2. The crash being a SIGSEGV inside MNNVL clique enrollment (not a returned error) — is that triagable as a defensive-handling bug regardless of the fabric state?
3. The threshold dropping from 44 → 40 between NCCL 2.27.5 and 2.30.4 — does that ring any bells (e.g. a recent change in the MNNVL clique buffer / topology probe)?
4. Is `NCCL_MNNVL_ENABLE=0` considered safe as a longer-term mitigation in our environment while the fabric question is investigated? Any side effects we should watch for?

---

## Reproducer artifacts (follow-up — Dockerfile + scripts + sample log)

Adding the build/run artifacts so anyone can rebuild the exact environment.

### Dockerfile

```dockerfile
FROM verlai/verl:vllm018.aarch64.dev1

RUN pip install cupy-cuda12x==13.6.0 && \
    pip install --force-reinstall git+https://github.com/ISEEKYAN/mbridge.git@1ecf526
```

`mbridge` isn't on the NCCL repro path but it's in our verified image so I'm leaving it in for byte-fidelity. Build:

```bash
docker build -t verl-bench:dev1-minimal -f Dockerfile .
```

This is the **published `verlai/verl:vllm018.aarch64.dev1` base** + just a cupy pin. Inside the resulting image:
- `cupy-cuda12x==13.6.0`
- `numpy==1.26.4`
- NCCL `2.27.5+cuda12.9` (from `nvidia-nccl-cu12` shipped with torch, the `libnccl.so.2` cupy actually loads)
- `torch 2.10.0+cu129`
- Python 3.12
- aarch64 / GB200 target

### Container start

On each of N nodes (head + N-1 workers):

```bash
docker run -d --name verl-bench \
    --gpus all --net=host --ipc=host --shm-size=64g \
    --security-opt label=disable \
    --device=/dev/nvidia-caps-imex-channels/channel0 \
    -v $HOME/data:/root/data \
    verl-bench:dev1-minimal sleep infinity
```

The `--device=/dev/nvidia-caps-imex-channels/channel0` is the GB200 NVL72-specific IMEX channel device — required for MNNVL to enumerate the clique inside the container.

### Ray cluster bring-up

On the head node:

```bash
docker exec verl-bench ray start --head \
    --node-ip-address=<HEAD_IP> --port=6379 \
    --object-store-memory=$((100*1024*1024*1024))
```

On each worker node:

```bash
docker exec verl-bench ray start \
    --address=<HEAD_IP>:6379 \
    --node-ip-address=<WORKER_IP> \
    --object-store-memory=$((100*1024*1024*1024))
```

For the bisection table above (N=11..14 nodes for world_size 44..56), I varied only the worker count and reran the same `repro.py` with `--world-size N*4`.

### Full repro script (repro.py)

```python
#!/usr/bin/env python3
"""NCCL MNNVL SIGSEGV repro at world_size>=44 on GB200 NVL72.

Pass --nccl-mnnvl 0 to confirm workaround.
"""
import argparse, faulthandler, os, socket, sys, time
import ray


@ray.remote(num_gpus=1, max_concurrency=4)
class W:
    def __init__(self, rank, world_size, group_name):
        faulthandler.enable(file=sys.stderr, all_threads=True)
        self.rank = rank
        self.world_size = world_size
        self.group_name = group_name
        self.hostname = socket.gethostname()
        self.ip = socket.gethostbyname(self.hostname)

    def env_dump(self):
        keys = ["NCCL_DEBUG", "NCCL_DEBUG_SUBSYS", "NCCL_CUMEM_ENABLE",
                "NCCL_NVLS_ENABLE", "NCCL_MNNVL_ENABLE", "CUDA_VISIBLE_DEVICES"]
        return {k: os.environ.get(k, "<unset>") for k in keys}

    def init_and_barrier(self):
        import torch, cupy as cp
        from ray.util import collective
        faulthandler.enable(file=sys.stderr, all_threads=True)
        torch.cuda.set_device(0)
        cp.cuda.runtime.setDevice(0)

        t0 = time.time()
        print(f"[r{self.rank}@{self.ip}] init start ws={self.world_size}", flush=True)
        try:
            collective.init_collective_group(self.world_size, self.rank, "nccl", self.group_name)
            print(f"[r{self.rank}@{self.ip}] init OK {time.time()-t0:.1f}s", flush=True)
        except Exception as e:
            print(f"[r{self.rank}@{self.ip}] init FAIL: {e}", flush=True)
            return ("INIT_FAIL", self.ip, str(e))

        t1 = time.time()
        print(f"[r{self.rank}@{self.ip}] barrier start", flush=True)
        try:
            collective.barrier(self.group_name)   # <-- SIGSEGV here at world_size >= 44
            print(f"[r{self.rank}@{self.ip}] barrier OK {time.time()-t1:.1f}s", flush=True)
        except Exception as e:
            print(f"[r{self.rank}@{self.ip}] barrier FAIL: {e}", flush=True)
            return ("BARRIER_FAIL", self.ip, str(e))

        return ("OK", self.ip, time.time() - t0)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--world-size", type=int, default=48)
    p.add_argument("--group-name", type=str, default="repro")
    p.add_argument("--ray-address", type=str, default="auto")
    p.add_argument("--nccl-nvls", default="1")
    p.add_argument("--nccl-cumem", default="1")
    p.add_argument("--nccl-mnnvl", default="1")
    p.add_argument("--nccl-debug", default="INFO")
    args = p.parse_args()

    runtime_env = {"env_vars": {
        "NCCL_DEBUG": args.nccl_debug,
        "NCCL_DEBUG_SUBSYS": "INIT,COLL",
        "NCCL_CUMEM_ENABLE": args.nccl_cumem,
        "NCCL_NVLS_ENABLE": args.nccl_nvls,
        "NCCL_MNNVL_ENABLE": args.nccl_mnnvl,
        "CUDA_DEVICE_MAX_CONNECTIONS": "1",
        "TORCH_NCCL_AVOID_RECORD_STREAMS": "1",
        "PYTHONUNBUFFERED": "1",
    }}
    ray.init(address=args.ray_address, runtime_env=runtime_env, ignore_reinit_error=True)
    print("ray cluster:", ray.cluster_resources(), flush=True)

    workers = [W.remote(i, args.world_size, args.group_name) for i in range(args.world_size)]
    print("env_dump rank 0:", ray.get(workers[0].env_dump.remote()), flush=True)

    t0 = time.time()
    results = ray.get([w.init_and_barrier.remote() for w in workers])
    n_ok = sum(1 for r in results if r[0] == "OK")
    print(f"\n=== {n_ok}/{args.world_size} OK, elapsed {time.time()-t0:.1f}s ===", flush=True)
    for r in results:
        if r[0] != "OK":
            print(f"  {r[0]} {r[1]} -> {r[2]}", flush=True)

    ray.shutdown()


if __name__ == "__main__":
    main()
```

Run on an 11-node ray cluster (44 GPU):

```bash
docker exec verl-bench python3 repro.py --world-size 44   # FAIL (SIGSEGV in init)
docker exec verl-bench python3 repro.py --world-size 40   # PASS
docker exec verl-bench python3 repro.py --world-size 44 --nccl-mnnvl 0   # PASS
```

### Sample NCCL_DEBUG=INFO log — world_size 44 FAIL on clean image

```
runtime_env env_vars: {'NCCL_DEBUG': 'INFO', 'NCCL_DEBUG_SUBSYS': 'INIT,COLL', 'NCCL_CUMEM_ENABLE': '1', 'NCCL_NVLS_ENABLE': '1', 'NCCL_MNNVL_ENABLE': '1', 'CUDA_DEVICE_MAX_CONNECTIONS': '1', 'TORCH_NCCL_AVOID_RECORD_STREAMS': '1', 'PYTHONUNBUFFERED': '1'}
INFO worker.py:2003 -- Connected to Ray cluster. View the dashboard at http://192.168.0.108:8265
connected to ray cluster: {'GPU': 44.0, 'accelerator_type:GB200': 11.0, 'CPU': 1540.0, 'node:192.168.0.108': 1.0, 'node:192.168.0.101': 1.0, 'node:192.168.0.115': 1.0, 'node:192.168.0.117': 1.0, 'node:192.168.0.114': 1.0, 'node:192.168.0.112': 1.0, 'node:192.168.0.107': 1.0, 'node:192.168.0.118': 1.0, 'node:192.168.0.106': 1.0, 'node:192.168.0.105': 1.0, 'node:192.168.0.111': 1.0}

=== env_dump from rank 0 (verify NCCL_DEBUG propagation) ===
{'NCCL_DEBUG': 'INFO', 'NCCL_DEBUG_SUBSYS': 'INIT,COLL', 'NCCL_CUMEM_ENABLE': '1', 'NCCL_NVLS_ENABLE': '1', 'NCCL_MNNVL_ENABLE': '1', 'CUDA_VISIBLE_DEVICES': '0'}

=== launching init+barrier on 44 ranks ===
(W pid=768) [r13@192.168.0.105] init_collective_group start ws=44
(W pid=768) [r13@192.168.0.105] init_collective_group OK 0.0s
(W pid=768) [r13@192.168.0.105] barrier start
(W pid=694) gb200-rack1-15:694:945 [0] NCCL INFO cudaDriverVersion 13000
(W pid=694) gb200-rack1-15:694:945 [0] NCCL INFO NCCL version 2.27.5+cuda12.9
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO NET/Plugin: Could not find: libnccl-net.so.
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO NET/IB : No device found.
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO NET/IB : Using [RO]; OOB enp0s3:192.168.0.115<0>
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO NET/Socket : Using [0]enp0s3:192.168.0.115<0> [1]enp192s2:192.168.1.115<0> [2]gpu0rdma0:192.168.2.115<0> [3]gpu1rdma0:192.168.3.115<0> [4]gpu2rdma0:192.168.4.115<0> [5]gpu3rdma0:192.168.5.115<0>
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO Initialized NET plugin Socket
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO Assigned NET plugin Socket to comm
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO Using network Socket
(W pid=694) gb200-rack1-15:694:964 [0] NCCL INFO ncclCommInitRank comm 0x5ccdb483e8c0 rank 42 nranks 44 cudaDev 0 nvmlDev 2 busId c1000 commId 0x90d2c1795dd2bcfc - Init START
(W pid=769) gb200-rack1-06:769:1041 [0] NCCL INFO RAS client listening socket at 127.0.0.1<28028>
(W pid=766) gb200-rack1-18:766:1039 [0] NCCL INFO MNNVL busId 0x8a000 fabric UUID 604624d54d2384dc.3413902eca5893b5 cliqueId 0x17 state 3 healthMask 0xaa
(W pid=768) gb200-rack1-05:768:1043 [0] NCCL INFO MNNVL 1 cliqueId 17 cliqueSize 44 cliqueRank 13
(W pid=768) gb200-rack1-18:768:1041 [0] NCCL INFO Setting affinity for GPU 0 to 0-69
(W pid=768) gb200-rack1-18:768:1041 [0] NCCL INFO NVLS multicast support is available on dev 0 (NVLS_NCHANNELS 24)
(raylet) A worker died or was killed while executing a task by an unexpected system error. ... Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. Some common causes include: ... (3) the worker crashed unexpectedly due to SIGSEGV.
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 2980, in get
    values, debugger_breakpoint = worker.get_objects(
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: W
```

The last NCCL line on every failing run is consistently `MNNVL cliqueSize 44 ... NVLS multicast support is available on dev 0` followed by the worker SIGSEGV. The same code path with `--world-size 40` prints `cliqueSize 40` and proceeds to `Init COMPLETE` cleanly.

### IMEX status (in case it helps)

From inside any of the 14 host machines (host-level, not container):

```
$ sudo nvidia-imex-ctl -N
# all 18 cluster nodes (192.168.0.101-118) report READY

$ systemctl is-active nvidia-imex
active

$ md5sum /etc/nvidia-imex/nodes_config.cfg
60108257a6f934b273b7f26e13dc3313  /etc/nvidia-imex/nodes_config.cfg
# byte-identical across all 14 hosts

$ systemctl is-active nvidia-fabricmanager
failed
$ journalctl -u nvidia-fabricmanager | tail -2
# "Detected Pre-NVL5 system, fabricmanager exiting" - expected on GB200 NVL5 (replaced by IMEX)
```

Happy to dump per-rank stderr (with faulthandler enabled) or a coredump if it would help triage.

**Comment by xiaofanl-nvidia** [comment]
> healthMask 0xaa = 4 of 8 NVL paths down

Could you explain exactly what this means? Does it mean some of the nvlinks are not usable? 
Does this issue reproduce when all links are healthy? 

In general, I'm not sure NCCL official support operations on unhealthy fabric. What is your use case for this support instead of fixing the fabric?

**Comment by aoshen02** [comment]
> > healthMask 0xaa = 4 of 8 NVL paths down
> 
> Could you explain exactly what this means? Does it mean some of the nvlinks are not usable? Does this issue reproduce when all links are healthy?
> 
> In general, I'm not sure NCCL official support operations on unhealthy fabric. What is your use case for this support instead of fixing the fabric?

Hi xiaofan, I've updated the pr description. Do you think it's OK for you?

**Comment by Harry-Chen** [comment]
> > healthMask 0xaa = 4 of 8 NVL paths down
> 
> Could you explain exactly what this means? Does it mean some of the nvlinks are not usable? Does this issue reproduce when all links are healthy?

According to my understanding, this is defined in https://docs.nvidia.com/deploy/nvml-api/group__nvmlFabricDefs.html#group__nvmlFabricDefs_1gde1578a1925a4e556ef16f0eaad69269.

So `0xaa` means everything is normal.

```
bits [1:0] = 10b = 2 → DEGRADED_BW              = FALSE
bits [3:2] = 10b = 2 → ROUTE_RECOVERY           = FALSE
bits [5:4] = 10b = 2 → ROUTE_UNHEALTHY          = FALSE
bits [7:6] = 10b = 2 → ACCESS_TIMEOUT_RECOVERY  = FALSE
```

The "NVL paths down" thing is LLM hallucination, in which case, the issue is not with MNNVL, but NCCL itself.

**Comment by AddyLaddy** [comment]
Does it still fail if you set `NCCL_NVLS_ENABLE=0`

**Comment by xiaofanl-nvidia** [comment]
> Does it still fail if you set `NCCL_NVLS_ENABLE=0`

The description said yes. The only WAR is to disable MNNVL. 
Let's try to repro it internally and look at stacktrace/coredump.

**Comment by kiskra-nvidia** [comment]
With 2.27.5, my first suspect would be insufficient stack size -- see the [Troubleshooting](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#stack-size) section of the user guide. That doesn't explain the crash with 2.30.4 though, which employs multiple strategies to avoid that issue...

**Comment by AddyLaddy** [comment]
We suspect this is due to a stack overrun during the recursive topolgy search which can occur on large NVLD machines. But we have not see this occur with the default Linux stack size of 8MiB.
Does your environment/application/container change the `ulimit -s` default?

**Comment by kiskra-nvidia** [comment]
Can we see the NCCL debug output from version 2.30.4? It includes additional diagnostics that could be helpful. Preferably with `NCCL_DEBUG_SUBSYS=ALL`.

**Comment by AddyLaddy** [comment]
We have been able to recreate the failure on 44 ranks of an internal GB200 system, by setting `ulimit -s unlimited` for the job launch and using the default NCCL 2.27.5 library from the container.
However, it did not reproduce **unless** we changed the default Linux stack size from `8192` to `unlimited`.

Also, it did not reproduce with NCCL 2.30.4 and `ulimit -s unlimited`. There we saw this guard message:

```
NCCL INFO Stack size limit (unlimited) is unsafe; will use 8192KB for newly launched threads
```

Can you confirm from the `NCCL_DEBUG=INFO` logs you are using NCCL 2.30.4 and whether you see a similar message?

I often find I need to use `LD_PRELOAD=<path to NCCL lib>/libnccl.so.2` on the command line inside the container to override the NCCL library version. Or simply build new Debian NCCL packages and replace the container ones using `dpkg -i`

**Comment by xiaofanl-nvidia** [comment]
Hi @aoshen02 since you confirmed this issue is resolved, could you please provide a concluding update to confirm our findings and close this issue?

**Comment by aoshen02** [comment]
Hi xiaofan, so I've tried this setting in my new container and reproduce the result, and the bug is fixed. Thank you so much for the help.

**Comment by AddyLaddy** [comment]
Did you change to `ulimit -s 8192` setting or move to NCCL v2.30.4 ?

**Comment by aoshen02** [comment]
I did ulimit -s 8192

**Comment by AddyLaddy** [comment]
> I did ulimit -s 8192

Ok thanks for the update.
8192 is the Linux default, which means something on that system must have overridden it to be `unlimited`
We have a WAR for the `unlmited` issue in 2.28 and later, so moving to a newer NCCL library should also resolve it.
