### ISSUE TITLE
nccl "Failed to open libibverbs.so" on AWS EFA-enabled instances

### ISSUE THREAD

**Issue by yaroslavvb** [NVIDIA/nccl#229]
I'm getting suboptimal performance when using NCCL on Amazon EFA-enabled instances by following instructions at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html and using Amazon DLAMI 23 (Amazon Linux) as starting image (automated as a script [here](https://github.com/cybertronai/aws-network-benchmarks/blob/b631b4b2d3d3f9b6464348414b73e2a6b68838fd/nccl_multiversion.py))

Running nccl-tests, I see following warnings about libibverbs not found. Any suggestions how to get the proper libibverbs in this environment?

Steps:
1. Follow official efa-start.html instructions with 2 efa-enabled instances
2. load ib_uverbs driver with "sudo /usr/sbin/modprobe ib_uverbs" and check for success through lsmod
3. Run nccl-tests/all_reduce_perf through anaconda3/bin/mpirun and -x FI_PROVIDER="efa"

See:

```
# Using devices
#   Rank  0 Pid  26565 on ip-172-31-9-96 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid  25883 on ip-172-31-14-244 device  0 [0x00] Tesla V100-SXM2-32GB
ip-172-31-9-96:26565:26565 [0] NCCL INFO NET/Socket : Using [0]eth0:172.31.9.96<0>

ip-172-31-9-96:26565:26565 [0] get_ofi_provider:312 NCCL WARN NET/OFI Could not find any optimal provider

ip-172-31-9-96:26565:26565 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ip-172-31-14-244:25883:25883 [0] NCCL INFO NET/Socket : Using [0]eth0:172.31.14.244<0>

ip-172-31-14-244:25883:25883 [0] get_ofi_provider:312 NCCL WARN NET/OFI Could not find any optimal provider

ip-172-31-14-244:25883:25883 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
NCCL version 2.4.6+cuda10.0
ip-172-31-9-96:26565:26616 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-172-31-9-96:26565:26616 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-172-31-14-244:25883:25906 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-172-31-14-244:25883:25906 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-172-31-9-96:26565:26616 [0] NCCL INFO CUDA Dev 0[0], Socket NIC distance :  PHB
ip-172-31-14-244:25883:25906 [0] NCCL INFO CUDA Dev 0[0], Socket NIC distance :  PHB
ip-172-31-9-96:26565:26616 [0] NCCL INFO Channel 00 :    0   1
ip-172-31-9-96:26565:26616 [0] NCCL INFO Channel 01 :    0   1
ip-172-31-9-96:26565:26616 [0] NCCL INFO Ring 00 : 1 -> 0 [receive] via NET/Socket/0
ip-172-31-14-244:25883:25906 [0] NCCL INFO Ring 00 : 0 -> 1 [receive] via NET/Socket/0
ip-172-31-14-244:25883:25906 [0] NCCL INFO Ring 00 : 1 -> 0 [send] via NET/Socket/0
ip-172-31-9-96:26565:26616 [0] NCCL INFO Ring 00 : 0 -> 1 [send] via NET/Socket/0
ip-172-31-9-96:26565:26616 [0] NCCL INFO Ring 01 : 1 -> 0 [receive] via NET/Socket/0
ip-172-31-14-244:25883:25906 [0] NCCL INFO Ring 01 : 0 -> 1 [receive] via NET/Socket/0
ip-172-31-9-96:26565:26616 [0] NCCL INFO Ring 01 : 0 -> 1 [send] via NET/Socket/0
ip-172-31-14-244:25883:25906 [0] NCCL INFO Ring 01 : 1 -> 0 [send] via NET/Socket/0
ip-172-31-9-96:26565:26616 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
ip-172-31-9-96:26565:26616 [0] NCCL INFO comm 0x7f429c001cf0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
ip-172-31-14-244:25883:25906 [0] NCCL INFO comm 0x7f5704001cf0 rank 1 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
ip-172-31-9-96:26565:26565 [0] NCCL INFO Launch mode Parallel
           8             2   float     sum    56.46    0.00    0.00  0e+00    55.25    0.00    0.00  0e+00
          16             4   float     sum    61.62    0.00    0.00  0e+00    58.43    0.00    0.00  0e+00
          32             8   float     sum    60.67    0.00    0.00  0e+00    55.74    0.00    0.00  0e+00
          64            16   float     sum    66.83    0.00    0.00  0e+00    55.29    0.00    0.00  0e+00
         128            32   float     sum    56.92    0.00    0.00  0e+00    57.21    0.00    0.00  0e+00
         256            64   float     sum    59.05    0.00    0.00  0e+00    63.59    0.00    0.00  0e+00
         512           128   float     sum    59.56    0.01    0.01  0e+00    53.52    0.01    0.01  0e+00
        1024           256   float     sum    90.81    0.01    0.01  0e+00    82.12    0.01    0.01  0e+00
        2048           512   float     sum    75.46    0.03    0.03  0e+00    75.26    0.03    0.03  0e+00
        4096          1024   float     sum    86.24    0.05    0.05  0e+00    84.87    0.05    0.05  0e+00
        8192          2048   float     sum    108.7    0.08    0.08  0e+00    109.7    0.07    0.07  0e+00
       16384          4096   float     sum    132.4    0.12    0.12  0e+00    114.8    0.14    0.14  0e+00
       32768          8192   float     sum    136.3    0.24    0.24  0e+00    143.9    0.23    0.23  0e+00
       65536         16384   float     sum    192.6    0.34    0.34  0e+00    188.5    0.35    0.35  0e+00
      131072         32768   float     sum    379.6    0.35    0.35  0e+00    340.4    0.39    0.39  0e+00
      262144         65536   float     sum    302.1    0.87    0.87  0e+00    295.9    0.89    0.89  0e+00
      524288        131072   float     sum    404.1    1.30    1.30  0e+00    401.7    1.31    1.31  0e+00
     1048576        262144   float     sum    642.0    1.63    1.63  0e+00    688.0    1.52    1.52  0e+00
     2097152        524288   float     sum   1189.5    1.76    1.76  0e+00   1180.4    1.78    1.78  0e+00
     4194304       1048576   float     sum   2215.7    1.89    1.89  0e+00   2221.3    1.89    1.89  0e+00
     8388608       2097152   float     sum   3885.9    2.16    2.16  0e+00   3701.7    2.27    2.27  0e+00
    16777216       4194304   float     sum   7868.8    2.13    2.13  0e+00   8199.5    2.05    2.05  0e+00
    33554432       8388608   float     sum    15088    2.22    2.22  0e+00    14660    2.29    2.29  0e+00
    67108864      16777216   float     sum    28969    2.32    2.32  0e+00    30912    2.17    2.17  0e+00
   134217728      33554432   float     sum    59072    2.27    2.27  0e+00    57570    2.33    2.33  0e+00
   268435456      67108864   float     sum   122669    2.19    2.19  0e+00   120989    2.22    2.22  0e+00
   536870912     134217728   float     sum   238082    2.25    2.25  0e+00   238452    2.25    2.25  0e+00
  1073741824     268435456   float     sum   473716    2.27    2.27  0e+00   478372    2.24    2.24  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 0.946043 
```

**Comment by sjeaugey** [comment]
The real error here is : `get_ofi_provider:312 NCCL WARN NET/OFI Could not find any optimal provider`. This means the OFI plugin didn't initialize correctly. Since NCCL cannot use that plugin, it tries to use the next choices : Infiniband (which is not available -- hence the libibverbs.so not found message) and then falls back on Sockets.

**Comment by yaroslavvb** [comment]
I got past this warning by [installing](https://github.com/cybertronai/aws-network-benchmarks/blob/9b4ef01e86baf0180a758e7b3e74d8b60703e5a0/nccl_multiversion.py#L63) by installing generic rdma and libibverbs packages. Now it no longer complains, but just hangs silently. I'm wondering if I need AWS-specific versions of those libraries.

I ruled out connectivity issues by doing simple mpirun over 2 machines

```
/home/ec2-user/anaconda3/bin/mpirun --host 192.168.22.101,192.168.20.4 hostname
ip-192-168-20-4
ip-192-168-22-101
```

here's the output of nccl-test example
```
[ec2-user@ip-192-168-22-101 ~]$ { /home/ec2-user/anaconda3/bin/mpirun -x FI_PROVIDER="efa" -x FI_OFI_RXR_RX_COPY_UNEXP=1 -x FI_OFI_RXR_RX_COPY_OOO=1 -x FI_EFA_MR_CACHE_ENABLE=1 -x FI_OFI_RXR_INLINE_MR_ENABLE=1 -x LD_LIBRARY_PATH=/home/ec2-user/nccl/nccl-2.4.6/aws-ofi-nccl/install/lib/:/home/ec2-user/nccl/nccl-2.4.6/nccl/build/lib:/usr/local/cuda-10.0/lib64:/opt/amazon/efa/lib64:/home/ec2-user/anaconda3/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_TREE_THRESHOLD=0 --host 192.168.22.101,192.168.20.4 -n 2 -N 1 --mca btl tcp,self --mca btl_tcp_if_exclude lo,docker0 --bind-to none --oversubscribe /home/ec2-user/nccl/nccl-2.4.6/nccl-tests/build/all_reduce_perf -b 8 -e 1M -f 2 -g 1 -c 1 -n 2; } > >(tee -a /tmp/ncluster/0.sanity00-ttaob/7.out) 2> >(tee -a /tmp/ncluster/0.sanity00-ttaob/7.out >&2); echo $? > /tmp/ncluster/0.sanity00-ttaob/7.status
# nThread 1 nGpus 1 minBytes 8 maxBytes 1048576 step: 2(factor) warmup iters: 5 iters: 2 validation: 1
#
# Using devices
#   Rank  0 Pid  38627 on ip-192-168-22-101 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid  65404 on ip-192-168-20-4 device  0 [0x00] Tesla V100-SXM2-32GB
ip-192-168-22-101:38627:38627 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.22.101<0>
ip-192-168-22-101:38627:38627 [0] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-20-4:65404:65404 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.20.4<0>
NCCL version 2.4.6+cuda10.0
ip-192-168-20-4:65404:65404 [0] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-22-101:38627:38680 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-22-101:38627:38680 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-20-4:65404:65429 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-20-4:65404:65429 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-22-101:38627:38680 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-22-101:38627:38680 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-22-101:38627:38680 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-20-4:65404:65429 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-20-4:65404:65429 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-20-4:65404:65429 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-22-101:38627:38680 [0] NCCL INFO Channel 00 :    0   1
ip-192-168-22-101:38627:38680 [0] NCCL INFO Channel 01 :    0   1
ip-192-168-22-101:38627:38680 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-22-101:38627:38680 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-20-4:65404:65429 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-20-4:65404:65429 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-22-101:38627:38680 [0] NCCL INFO Ring 00 : 1 -> 0 [receive] via NET/AWS Libfabric/0
ip-192-168-20-4:65404:65429 [0] NCCL INFO Ring 00 : 0 -> 1 [receive] via NET/AWS Libfabric/0
ip-192-168-22-101:38627:38680 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-22-101:38627:38680 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-20-4:65404:65429 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-20-4:65404:65429 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-22-101:38627:38680 [0] NCCL INFO Ring 00 : 0 -> 1 [send] via NET/AWS Libfabric/0
ip-192-168-20-4:65404:65429 [0] NCCL INFO Ring 00 : 1 -> 0 [send] via NET/AWS Libfabric/0
```

**Comment by rashikakheria** [comment]
@yaroslavvb This usually happens when we don't setup the security groups properly. Look at [link](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security) to see on how to set them up correctly.

In a nutshell, you have to ensure that your security group (attached to your instances) have both inbound and outbound rules to allow traffic to itself.

**Comment by sjeaugey** [comment]
`NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr`

**Comment by rashikakheria** [comment]
> I'm surprised the previous run with Sockets ran to completion if the security groups were not properly configured, but maybe OFI needs more than just sockets.

Yes, exactly. This is the requirement specifically for EFA enabled instances.

**Comment by yaroslavvb** [comment]
@rashikakheria I don't think it's a connectivity issue because the same command works if I remove `-x FI_PROVIDER="efa"` and rerun. I ruled out "unlucky machine" issue by rerunning the entire procedure on another pair of p3dn instances

IE, this works
```
[ec2-user@ip-192-168-16-255 ~]$ /home/ec2-user/anaconda3/bin/mpirun  -x FI_OFI_RXR_RX_COPY_UNEXP=1 -x FI_OFI_RXR_RX_COPY_OOO=1 -x FI_EFA_MR_CACHE_ENABLE=1 -x FI_OFI_RXR_INLINE_MR_ENABLE=1 -x LD_LIBRARY_PATH=/home/ec2-user/nccl/nccl-2.4.6/aws-ofi-nccl/install/lib/:/home/ec2-user/nccl/nccl-2.4.6/nccl/build/lib:/usr/local/cuda-10.0/lib64:/opt/amazon/efa/lib64:/home/ec2-user/anaconda3/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_TREE_THRESHOLD=0 --host 192.168.16.255,192.168.29.243 -n 2 -N 1 --mca btl tcp,self --mca btl_tcp_if_exclude lo,docker0 --bind-to none --oversubscribe /home/ec2-user/nccl/nccl-2.4.6/nccl-tests/build/all_reduce_perf -b 8 -e 1M -f 2 -g 1 -c 1 -n 2
# nThread 1 nGpus 1 minBytes 8 maxBytes 1048576 step: 2(factor) warmup iters: 5 iters: 2 validation: 1 
#
# Using devices
#   Rank  0 Pid  25604 on ip-192-168-16-255 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid  24447 on ip-192-168-29-243 device  0 [0x00] Tesla V100-SXM2-32GB
ip-192-168-16-255:25604:25604 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:25604:25604 [0] NCCL INFO NET/OFI Selected Provider is tcp;ofi_rxm
ip-192-168-29-243:24447:24447 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
NCCL version 2.4.6+cuda10.0
ip-192-168-29-243:24447:24447 [0] NCCL INFO NET/OFI Selected Provider is tcp;ofi_rxm
ip-192-168-16-255:25604:25627 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:25604:25627 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:24447:24474 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:24447:24474 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:25604:25627 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25604:25627 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:25604:25627 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:24447:24474 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24447:24474 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24447:24474 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:25604:25627 [0] NCCL INFO Channel 00 :    0   1
ip-192-168-16-255:25604:25627 [0] NCCL INFO Channel 01 :    0   1
ip-192-168-16-255:25604:25627 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25604:25627 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24447:24474 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24447:24474 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:25604:25627 [0] NCCL INFO Ring 00 : 1 -> 0 [receive] via NET/AWS Libfabric/0
ip-192-168-29-243:24447:24474 [0] NCCL INFO Ring 00 : 0 -> 1 [receive] via NET/AWS Libfabric/0
ip-192-168-16-255:25604:25627 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25604:25627 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24447:24474 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24447:24474 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24447:24474 [0] NCCL INFO Ring 00 : 1 -> 0 [send] via NET/AWS Libfabric/0
ip-192-168-16-255:25604:25627 [0] NCCL INFO Ring 00 : 0 -> 1 [send] via NET/AWS Libfabric/0
ip-192-168-16-255:25604:25627 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25604:25627 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24447:24474 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24447:24474 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:25604:25627 [0] NCCL INFO Ring 01 : 1 -> 0 [receive] via NET/AWS Libfabric/0
ip-192-168-29-243:24447:24474 [0] NCCL INFO Ring 01 : 0 -> 1 [receive] via NET/AWS Libfabric/0
ip-192-168-16-255:25604:25627 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25604:25627 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24447:24474 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24447:24474 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:25604:25627 [0] NCCL INFO Ring 01 : 0 -> 1 [send] via NET/AWS Libfabric/0
ip-192-168-16-255:25604:25627 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
ip-192-168-29-243:24447:24474 [0] NCCL INFO Ring 01 : 1 -> 0 [send] via NET/AWS Libfabric/0
ip-192-168-16-255:25604:25627 [0] NCCL INFO comm 0x7f5088001cf0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
ip-192-168-29-243:24447:24474 [0] NCCL INFO comm 0x7f855c001cf0 rank 1 nranks 2 cudaDev 0 nvmlDev 0 - Init COMPLETE
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
ip-192-168-16-255:25604:25604 [0] NCCL INFO Launch mode Parallel
           8             2   float     sum    64.41    0.00    0.00  0e+00    75.15    0.00    0.00  0e+00
          16             4   float     sum    55.36    0.00    0.00  0e+00    56.06    0.00    0.00  0e+00
          32             8   float     sum    69.52    0.00    0.00  0e+00    72.45    0.00    0.00  0e+00
          64            16   float     sum    62.68    0.00    0.00  0e+00    55.95    0.00    0.00  0e+00
         128            32   float     sum    70.97    0.00    0.00  0e+00    60.13    0.00    0.00  0e+00
         256            64   float     sum    92.54    0.00    0.00  0e+00    68.97    0.00    0.00  0e+00
         512           128   float     sum    57.22    0.01    0.01  0e+00    77.80    0.01    0.01  0e+00
        1024           256   float     sum    95.53    0.01    0.01  0e+00    97.20    0.01    0.01  0e+00
        2048           512   float     sum    109.9    0.02    0.02  0e+00    84.84    0.02    0.02  0e+00
        4096          1024   float     sum    110.6    0.04    0.04  0e+00    100.6    0.04    0.04  0e+00
        8192          2048   float     sum    126.7    0.06    0.06  0e+00    159.4    0.05    0.05  0e+00
       16384          4096   float     sum    140.0    0.12    0.12  0e+00    143.5    0.11    0.11  0e+00
       32768          8192   float     sum    205.9    0.16    0.16  0e+00    185.4    0.18    0.18  0e+00
       65536         16384   float     sum    276.9    0.24    0.24  0e+00    296.5    0.22    0.22  0e+00
      131072         32768   float     sum    522.9    0.25    0.25  0e+00    503.1    0.26    0.26  0e+00
      262144         65536   float     sum    419.0    0.63    0.63  0e+00    405.6    0.65    0.65  0e+00
      524288        131072   float     sum    941.3    0.56    0.56  0e+00    682.0    0.77    0.77  0e+00
     1048576        262144   float     sum   1294.2    0.81    0.81  0e+00   1250.7    0.84    0.84  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 0.168614 
#
```

this hangs
```
[ec2-user@ip-192-168-16-255 ~]$ /home/ec2-user/anaconda3/bin/mpirun -x FI_PROVIDER="efa" -x FI_OFI_RXR_RX_COPY_UNEXP=1 -x FI_OFI_RXR_RX_COPY_OOO=1 -x FI_EFA_MR_CACHE_ENABLE=1 -x FI_OFI_RXR_INLINE_MR_ENABLE=1 -x LD_LIBRARY_PATH=/home/ec2-user/nccl/nccl-2.4.6/aws-ofi-nccl/install/lib/:/home/ec2-user/nccl/nccl-2.4.6/nccl/build/lib:/usr/local/cuda-10.0/lib64:/opt/amazon/efa/lib64:/home/ec2-user/anaconda3/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_TREE_THRESHOLD=0 --host 192.168.16.255,192.168.29.243 -n 2 -N 1 --mca btl tcp,self --mca btl_tcp_if_exclude lo,docker0 --bind-to none --oversubscribe /home/ec2-user/nccl/nccl-2.4.6/nccl-tests/build/all_reduce_perf -b 8 -e 1M -f 2 -g 1 -c 1 -n 2
# nThread 1 nGpus 1 minBytes 8 maxBytes 1048576 step: 2(factor) warmup iters: 5 iters: 2 validation: 1 
#
# Using devices
#   Rank  0 Pid  25655 on ip-192-168-16-255 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid  24512 on ip-192-168-29-243 device  0 [0x00] Tesla V100-SXM2-32GB
ip-192-168-16-255:25655:25655 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:25655:25655 [0] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:24512:24512 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
NCCL version 2.4.6+cuda10.0
ip-192-168-29-243:24512:24512 [0] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:25655:25678 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:25655:25678 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:24512:24534 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:24512:24534 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:25655:25678 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25655:25678 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:25655:25678 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:24512:24534 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24512:24534 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24512:24534 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:25655:25678 [0] NCCL INFO Channel 00 :    0   1
ip-192-168-16-255:25655:25678 [0] NCCL INFO Channel 01 :    0   1
ip-192-168-16-255:25655:25678 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25655:25678 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24512:24534 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24512:24534 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:25655:25678 [0] NCCL INFO Ring 00 : 1 -> 0 [receive] via NET/AWS Libfabric/0
ip-192-168-29-243:24512:24534 [0] NCCL INFO Ring 00 : 0 -> 1 [receive] via NET/AWS Libfabric/0
ip-192-168-16-255:25655:25678 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:25655:25678 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24512:24534 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:24512:24534 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:24512:24534 [0] NCCL INFO Ring 00 : 1 -> 0 [send] via NET/AWS Libfabric/0
ip-192-168-16-255:25655:25678 [0] NCCL INFO Ring 00 : 0 -> 1 [send] via NET/AWS Libfabric/0
```

**Comment by rashikakheria** [comment]
@yaroslavvb There is a requirement for EFA communication that the security groups are setup the way I mentioned before. The TCP traffic is different and will always work without the setup as well.

**Comment by yaroslavvb** [comment]
@rashikakheria thanks, that was indeed the problem. I assumed enabling all TCP/UDP/ICMP traffic was equivalent to "All Traffic" but it wasn't. I'm now seeing 1.89271 bus bandwidth for 16 GPUs over 2 instances in a placement group


```
[ec2-user@ip-192-168-16-255 ~]$ { /home/ec2-user/anaconda3/bin/mpirun -x FI_PROVIDER="efa" -x FI_OFI_RXR_RX_COPY_UNEXP=1 -x FI_OFI_RXR_RX_COPY_OOO=1 -x FI_EFA_MR_CACHE_ENABLE=1 -x FI_OFI_RXR_INLINE_MR_ENABLE=1 -x LD_LIBRARY_PATH=/home/ec2-user/nccl/nccl-2.4.6/aws-ofi-nccl/install/lib/:/home/ec2-user/nccl/nccl-2.4.6/nccl/build/lib:/usr/local/cuda-10.0/lib64:/opt/amazon/efa/lib64:/home/ec2-user/anaconda3/lib:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_TREE_THRESHOLD=0 --host 192.168.16.255,192.168.29.243 -n $n -N 8 --mca btl tcp,self --mca btl_tcp_if_exclude lo,docker0 --bind-to none --oversubscribe /home/ec2-user/nccl/nccl-2.4.6/nccl-tests/build/all_reduce_perf -b 8 -e 1G -f 2 -g 1 -c 1 ; } > >(tee -a /tmp/ncluster/0.sanity00-n28a4/7.out) 2> >(tee -a /tmp/ncluster/0.sanity00-n28a4/7.out >&2); echo $? > /tmp/ncluster/0.sanity00-n28a4/7.status
# nThread 1 nGpus 1 minBytes 8 maxBytes 1073741824 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid  35480 on ip-192-168-16-255 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  1 Pid  35481 on ip-192-168-16-255 device  1 [0x00] Tesla V100-SXM2-32GB
#   Rank  2 Pid  35482 on ip-192-168-16-255 device  2 [0x00] Tesla V100-SXM2-32GB
#   Rank  3 Pid  35483 on ip-192-168-16-255 device  3 [0x00] Tesla V100-SXM2-32GB
#   Rank  4 Pid  35484 on ip-192-168-16-255 device  4 [0x00] Tesla V100-SXM2-32GB
#   Rank  5 Pid  35485 on ip-192-168-16-255 device  5 [0x00] Tesla V100-SXM2-32GB
#   Rank  6 Pid  35486 on ip-192-168-16-255 device  6 [0x00] Tesla V100-SXM2-32GB
#   Rank  7 Pid  35487 on ip-192-168-16-255 device  7 [0x00] Tesla V100-SXM2-32GB
#   Rank  8 Pid  26465 on ip-192-168-29-243 device  0 [0x00] Tesla V100-SXM2-32GB
#   Rank  9 Pid  26466 on ip-192-168-29-243 device  1 [0x00] Tesla V100-SXM2-32GB
#   Rank 10 Pid  26467 on ip-192-168-29-243 device  2 [0x00] Tesla V100-SXM2-32GB
#   Rank 11 Pid  26468 on ip-192-168-29-243 device  3 [0x00] Tesla V100-SXM2-32GB
#   Rank 12 Pid  26469 on ip-192-168-29-243 device  4 [0x00] Tesla V100-SXM2-32GB
#   Rank 13 Pid  26470 on ip-192-168-29-243 device  5 [0x00] Tesla V100-SXM2-32GB
#   Rank 14 Pid  26471 on ip-192-168-29-243 device  6 [0x00] Tesla V100-SXM2-32GB
#   Rank 15 Pid  26472 on ip-192-168-29-243 device  7 [0x00] Tesla V100-SXM2-32GB
ip-192-168-16-255:35480:35480 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35480:35480 [0] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
NCCL version 2.4.6+cuda10.0
ip-192-168-29-243:26466:26466 [1] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26472:26472 [7] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26471:26471 [6] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26470:26470 [5] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26469:26469 [4] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26468:26468 [3] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26467:26467 [2] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26465:26465 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.29.243<0>
ip-192-168-29-243:26472:26472 [7] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26471:26471 [6] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26466:26466 [1] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26470:26470 [5] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26469:26469 [4] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26465:26465 [0] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26467:26467 [2] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-29-243:26468:26468 [3] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35487:35487 [7] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35485:35485 [5] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35481:35481 [1] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35483:35483 [3] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35486:35486 [6] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35482:35482 [2] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35487:35487 [7] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35484:35484 [4] NCCL INFO NET/Socket : Using [0]eth0:192.168.16.255<0>
ip-192-168-16-255:35485:35485 [5] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35481:35481 [1] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35483:35483 [3] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35486:35486 [6] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35482:35482 [2] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35484:35484 [4] NCCL INFO NET/OFI Selected Provider is efa;ofi_rxr
ip-192-168-16-255:35480:35545 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35480:35545 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26466:26529 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26466:26529 [1] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26469:26530 [4] NCCL INFO Setting affinity for GPU 4 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26469:26530 [4] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26472:26531 [7] NCCL INFO Setting affinity for GPU 7 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26472:26531 [7] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26470:26532 [5] NCCL INFO Setting affinity for GPU 5 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26470:26532 [5] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26465:26533 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26465:26533 [0] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26471:26534 [6] NCCL INFO Setting affinity for GPU 6 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26471:26534 [6] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26468:26535 [3] NCCL INFO Setting affinity for GPU 3 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26468:26535 [3] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26467:26536 [2] NCCL INFO Setting affinity for GPU 2 to ffffffff,ffffffff,ffffffff
ip-192-168-29-243:26467:26536 [2] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35487:35546 [7] NCCL INFO Setting affinity for GPU 7 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35487:35546 [7] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35483:35548 [3] NCCL INFO Setting affinity for GPU 3 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35483:35548 [3] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35486:35547 [6] NCCL INFO Setting affinity for GPU 6 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35486:35547 [6] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35481:35549 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35481:35549 [1] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35485:35550 [5] NCCL INFO Setting affinity for GPU 5 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35485:35550 [5] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35484:35551 [4] NCCL INFO Setting affinity for GPU 4 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35482:35552 [2] NCCL INFO Setting affinity for GPU 2 to ffffffff,ffffffff,ffffffff
ip-192-168-16-255:35484:35551 [4] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-16-255:35482:35552 [2] NCCL INFO NCCL_TREE_THRESHOLD set by environment to 0.
ip-192-168-29-243:26466:26529 [1] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26466:26529 [1] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26466:26529 [1] NCCL INFO CUDA Dev 1[1], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26465:26533 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26465:26533 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26465:26533 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26467:26536 [2] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26467:26536 [2] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26467:26536 [2] NCCL INFO CUDA Dev 2[2], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26468:26535 [3] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26468:26535 [3] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26468:26535 [3] NCCL INFO CUDA Dev 3[3], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26469:26530 [4] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26469:26530 [4] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26469:26530 [4] NCCL INFO CUDA Dev 4[4], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26471:26534 [6] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26471:26534 [6] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26471:26534 [6] NCCL INFO CUDA Dev 6[6], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26470:26532 [5] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26470:26532 [5] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26470:26532 [5] NCCL INFO CUDA Dev 5[5], AWS Libfabric NIC distance :  SYS
ip-192-168-29-243:26472:26531 [7] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26472:26531 [7] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26472:26531 [7] NCCL INFO CUDA Dev 7[7], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35486:35547 [6] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35486:35547 [6] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35486:35547 [6] NCCL INFO CUDA Dev 6[6], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35485:35550 [5] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35485:35550 [5] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35485:35550 [5] NCCL INFO CUDA Dev 5[5], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35484:35551 [4] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35484:35551 [4] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35484:35551 [4] NCCL INFO CUDA Dev 4[4], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35487:35546 [7] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35487:35546 [7] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35487:35546 [7] NCCL INFO CUDA Dev 7[7], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35483:35548 [3] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35483:35548 [3] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35483:35548 [3] NCCL INFO CUDA Dev 3[3], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35482:35552 [2] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35482:35552 [2] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35482:35552 [2] NCCL INFO CUDA Dev 2[2], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35481:35549 [1] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35481:35549 [1] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35481:35549 [1] NCCL INFO CUDA Dev 1[1], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35480:35545 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35480:35545 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35480:35545 [0] NCCL INFO CUDA Dev 0[0], AWS Libfabric NIC distance :  SYS
ip-192-168-16-255:35480:35545 [0] NCCL INFO Channel 00 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15
ip-192-168-16-255:35480:35545 [0] NCCL INFO Channel 01 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15
ip-192-168-29-243:26465:26533 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26465:26533 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35480:35545 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35480:35545 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26465:26533 [0] NCCL INFO Ring 00 : 7 -> 8 [receive] via NET/AWS Libfabric/0
ip-192-168-16-255:35480:35545 [0] NCCL INFO Ring 00 : 15 -> 0 [receive] via NET/AWS Libfabric/0
ip-192-168-29-243:26465:26533 [0] NCCL INFO Ring 00 : 8[0] -> 9[1] via P2P/IPC
ip-192-168-16-255:35480:35545 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
ip-192-168-16-255:35486:35547 [6] NCCL INFO Ring 00 : 6[6] -> 4[4] via P2P/IPC
ip-192-168-16-255:35485:35550 [5] NCCL INFO Ring 00 : 5[5] -> 7[7] via P2P/IPC
ip-192-168-29-243:26471:26534 [6] NCCL INFO Ring 00 : 14[6] -> 12[4] via P2P/IPC
ip-192-168-16-255:35484:35551 [4] NCCL INFO Ring 00 : 4[4] -> 5[5] via P2P/IPC
ip-192-168-16-255:35483:35548 [3] NCCL INFO Ring 00 : 3[3] -> 2[2] via P2P/IPC
ip-192-168-29-243:26466:26529 [1] NCCL INFO Ring 00 : 9[1] -> 11[3] via P2P/IPC
ip-192-168-29-243:26470:26532 [5] NCCL INFO Ring 00 : 13[5] -> 15[7] via P2P/IPC
ip-192-168-16-255:35482:35552 [2] NCCL INFO Ring 00 : 2[2] -> 6[6] via P2P/IPC
ip-192-168-29-243:26469:26530 [4] NCCL INFO Ring 00 : 12[4] -> 13[5] via P2P/IPC
ip-192-168-16-255:35487:35546 [7] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35487:35546 [7] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26467:26536 [2] NCCL INFO Ring 00 : 10[2] -> 14[6] via P2P/IPC
ip-192-168-29-243:26468:26535 [3] NCCL INFO Ring 00 : 11[3] -> 10[2] via P2P/IPC
ip-192-168-16-255:35481:35549 [1] NCCL INFO Ring 00 : 1[1] -> 3[3] via P2P/IPC
ip-192-168-29-243:26472:26531 [7] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26472:26531 [7] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35487:35546 [7] NCCL INFO Ring 00 : 7 -> 8 [send] via NET/AWS Libfabric/0
ip-192-168-29-243:26472:26531 [7] NCCL INFO Ring 00 : 15 -> 0 [send] via NET/AWS Libfabric/0
ip-192-168-29-243:26465:26533 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26465:26533 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35480:35545 [0] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35480:35545 [0] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26465:26533 [0] NCCL INFO Ring 01 : 7 -> 8 [receive] via NET/AWS Libfabric/0
ip-192-168-16-255:35480:35545 [0] NCCL INFO Ring 01 : 15 -> 0 [receive] via NET/AWS Libfabric/0
ip-192-168-16-255:35486:35547 [6] NCCL INFO Ring 01 : 6[6] -> 4[4] via P2P/IPC
ip-192-168-16-255:35485:35550 [5] NCCL INFO Ring 01 : 5[5] -> 7[7] via P2P/IPC
ip-192-168-16-255:35484:35551 [4] NCCL INFO Ring 01 : 4[4] -> 5[5] via P2P/IPC
ip-192-168-16-255:35483:35548 [3] NCCL INFO Ring 01 : 3[3] -> 2[2] via P2P/IPC
ip-192-168-16-255:35482:35552 [2] NCCL INFO Ring 01 : 2[2] -> 6[6] via P2P/IPC
ip-192-168-16-255:35481:35549 [1] NCCL INFO Ring 01 : 1[1] -> 3[3] via P2P/IPC
ip-192-168-29-243:26471:26534 [6] NCCL INFO Ring 01 : 14[6] -> 12[4] via P2P/IPC
ip-192-168-29-243:26466:26529 [1] NCCL INFO Ring 01 : 9[1] -> 11[3] via P2P/IPC
ip-192-168-29-243:26470:26532 [5] NCCL INFO Ring 01 : 13[5] -> 15[7] via P2P/IPC
ip-192-168-29-243:26469:26530 [4] NCCL INFO Ring 01 : 12[4] -> 13[5] via P2P/IPC
ip-192-168-29-243:26467:26536 [2] NCCL INFO Ring 01 : 10[2] -> 14[6] via P2P/IPC
ip-192-168-29-243:26468:26535 [3] NCCL INFO Ring 01 : 11[3] -> 10[2] via P2P/IPC
ip-192-168-29-243:26465:26533 [0] NCCL INFO Ring 01 : 8[0] -> 9[1] via P2P/IPC
ip-192-168-16-255:35480:35545 [0] NCCL INFO Ring 01 : 0[0] -> 1[1] via P2P/IPC
ip-192-168-16-255:35487:35546 [7] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-16-255:35487:35546 [7] NCCL INFO include/net.h:24 -> 2
ip-192-168-29-243:26472:26531 [7] NCCL INFO NET/OFI No NIC info for dev 0
ip-192-168-29-243:26472:26531 [7] NCCL INFO include/net.h:24 -> 2
ip-192-168-16-255:35484:35551 [4] NCCL INFO comm 0x7f0394001cf0 rank 4 nranks 16 cudaDev 4 nvmlDev 4 - Init COMPLETE
ip-192-168-16-255:35482:35552 [2] NCCL INFO comm 0x7f1938001cf0 rank 2 nranks 16 cudaDev 2 nvmlDev 2 - Init COMPLETE
ip-192-168-16-255:35483:35548 [3] NCCL INFO comm 0x7fa814001cf0 rank 3 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE
ip-192-168-16-255:35486:35547 [6] NCCL INFO comm 0x7f8100001cf0 rank 6 nranks 16 cudaDev 6 nvmlDev 6 - Init COMPLETE
ip-192-168-29-243:26471:26534 [6] NCCL INFO comm 0x7f0c38001cf0 rank 14 nranks 16 cudaDev 6 nvmlDev 6 - Init COMPLETE
ip-192-168-16-255:35485:35550 [5] NCCL INFO comm 0x7f8220001cf0 rank 5 nranks 16 cudaDev 5 nvmlDev 5 - Init COMPLETE
ip-192-168-16-255:35487:35546 [7] NCCL INFO Ring 01 : 7 -> 8 [send] via NET/AWS Libfabric/0
ip-192-168-29-243:26469:26530 [4] NCCL INFO comm 0x7fcaf4001cf0 rank 12 nranks 16 cudaDev 4 nvmlDev 4 - Init COMPLETE
ip-192-168-29-243:26467:26536 [2] NCCL INFO comm 0x7f2730001cf0 rank 10 nranks 16 cudaDev 2 nvmlDev 2 - Init COMPLETE
ip-192-168-29-243:26468:26535 [3] NCCL INFO comm 0x7fa284001cf0 rank 11 nranks 16 cudaDev 3 nvmlDev 3 - Init COMPLETE
ip-192-168-29-243:26472:26531 [7] NCCL INFO Ring 01 : 15 -> 0 [send] via NET/AWS Libfabric/0
ip-192-168-16-255:35480:35545 [0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
ip-192-168-16-255:35481:35549 [1] NCCL INFO comm 0x7f6f04001cf0 rank 1 nranks 16 cudaDev 1 nvmlDev 1 - Init COMPLETE
ip-192-168-29-243:26470:26532 [5] NCCL INFO comm 0x7fc7d0001cf0 rank 13 nranks 16 cudaDev 5 nvmlDev 5 - Init COMPLETE
ip-192-168-29-243:26466:26529 [1] NCCL INFO comm 0x7fd580001cf0 rank 9 nranks 16 cudaDev 1 nvmlDev 1 - Init COMPLETE
ip-192-168-16-255:35480:35545 [0] NCCL INFO comm 0x7fa798001cf0 rank 0 nranks 16 cudaDev 0 nvmlDev 0 - Init COMPLETE
ip-192-168-16-255:35487:35546 [7] NCCL INFO comm 0x7f5698001cf0 rank 7 nranks 16 cudaDev 7 nvmlDev 7 - Init COMPLETE
ip-192-168-29-243:26465:26533 [0] NCCL INFO comm 0x7f0910001cf0 rank 8 nranks 16 cudaDev 0 nvmlDev 0 - Init COMPLETE
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
ip-192-168-16-255:35480:35480 [0] NCCL INFO Launch mode Parallel
ip-192-168-29-243:26472:26531 [7] NCCL INFO comm 0x7fb270001cf0 rank 15 nranks 16 cudaDev 7 nvmlDev 7 - Init COMPLETE
           8             2   float     sum    127.1    0.00    0.00  2e-07    126.8    0.00    0.00  1e-07
          16             4   float     sum    128.9    0.00    0.00  0e+00    123.1    0.00    0.00  1e-07
          32             8   float     sum    123.7    0.00    0.00  1e-07    127.2    0.00    0.00  1e-07
          64            16   float     sum    126.3    0.00    0.00  1e-07    127.5    0.00    0.00  6e-08
         128            32   float     sum    125.1    0.00    0.00  6e-08    124.6    0.00    0.00  6e-08
         256            64   float     sum    127.3    0.00    0.00  6e-08    123.7    0.00    0.00  6e-08
         512           128   float     sum    124.4    0.00    0.01  6e-08    126.5    0.00    0.01  6e-08
        1024           256   float     sum    129.6    0.01    0.01  2e-07    132.5    0.01    0.01  2e-07
        2048           512   float     sum    132.7    0.02    0.03  2e-07    137.3    0.01    0.03  2e-07
        4096          1024   float     sum    132.5    0.03    0.06  5e-07    136.7    0.03    0.06  5e-07
        8192          2048   float     sum    136.2    0.06    0.11  5e-07    136.1    0.06    0.11  5e-07
       16384          4096   float     sum    138.9    0.12    0.22  5e-07    139.7    0.12    0.22  5e-07
       32768          8192   float     sum    144.3    0.23    0.43  5e-07    144.6    0.23    0.42  5e-07
       65536         16384   float     sum    168.4    0.39    0.73  5e-07    164.4    0.40    0.75  5e-07
      131072         32768   float     sum    188.9    0.69    1.30  5e-07    188.0    0.70    1.31  5e-07
      262144         65536   float     sum    440.4    0.60    1.12  5e-07    439.4    0.60    1.12  5e-07
      524288        131072   float     sum    606.7    0.86    1.62  5e-07    615.8    0.85    1.60  5e-07
     1048576        262144   float     sum   1165.0    0.90    1.69  5e-07   1159.0    0.90    1.70  5e-07
     2097152        524288   float     sum   1675.9    1.25    2.35  5e-07   1693.5    1.24    2.32  5e-07
     4194304       1048576   float     sum   2358.0    1.78    3.34  5e-07   2364.4    1.77    3.33  5e-07
     8388608       2097152   float     sum   4168.7    2.01    3.77  5e-07   4193.2    2.00    3.75  5e-07
    16777216       4194304   float     sum   7782.3    2.16    4.04  5e-07   7709.6    2.18    4.08  5e-07
    33554432       8388608   float     sum    15082    2.22    4.17  5e-07    15266    2.20    4.12  5e-07
    67108864      16777216   float     sum    22672    2.96    5.55  5e-07    22616    2.97    5.56  5e-07
   134217728      33554432   float     sum    45112    2.98    5.58  5e-07    44981    2.98    5.59  5e-07
   268435456      67108864   float     sum    89535    3.00    5.62  5e-07    89555    3.00    5.62  5e-07
   536870912     134217728   float     sum   178821    3.00    5.63  5e-07   178880    3.00    5.63  5e-07
  1073741824     268435456   float     sum   356851    3.01    5.64  5e-07   357753    3.00    5.63  5e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.89271 
#
```

**Comment by yaroslavvb** [comment]
Closing the issue as resolved. The solution was to the following:

```
wget http://mirror.centos.org/centos/6/os/x86_64/Packages/rdma-6.9_4.1-3.el6.noarch.rpm
sudo yum install -y rdma-6.9_4.1-3.el6.noarch.rpm
wget http://mirror.centos.org/centos/6/os/x86_64/Packages/libibverbs-1.1.8-4.el6.x86_64.rpm
sudo yum install -y ./libibverbs-1.1.8-4.el6.x86_64.rpm
```

**Comment by AddyLaddy** [comment]
I believe NCCL_IB_DISABLE=1 is also a workaround for that warning message. On EFA enabled nodes it is harmless
