### ISSUE TITLE
Potential memory leak in graph/paths.cc

### ISSUE THREAD

**Issue by sanjoy** [NVIDIA/nccl#282]
We are running into a memory leak with NCCL v2.5.6-2 and our current theory is that this is a bug in graph/paths.cc.

The leaked memory is allocated [here]( https://github.com/NVIDIA/nccl/blob/3899f6e0f219b0cbf58537f791b0dd104b377750/src/graph/paths.cc#L57).  IIUC the memory is supposed to be freed by [`ncclTopoRemovePathType`](https://github.com/NVIDIA/nccl/blob/3899f6e0f219b0cbf58537f791b0dd104b377750/src/graph/paths.cc#L180), but that is not happening because it only `free`s paths from all nodes into nodes of type `nodeType`, but it should be freeing paths from all nodes of type `nodeType` as well.

Changing `ncclTopoRemovePathType` to

```
static void ncclTopoRemovePathType(struct ncclTopoSystem* system,
                                   int nodeType) {
  for (int t = 0; t < NCCL_TOPO_NODE_TYPES; t++) {
    for (int n = 0; n < NCCL_TOPO_MAX_NODES; n++) {
      struct ncclTopoNode* node = system->nodes[t].nodes + n;
      free(node->paths[nodeType]);
      node->paths[nodeType] = NULL;
    }
  }

  for (int n = 0; n < NCCL_TOPO_MAX_NODES; n++) {
    struct ncclTopoNode* node = system->nodes[nodeType].nodes + n;
    free(node->paths[nodeType]);
    node->paths[nodeType] = NULL;
  }
}
```

fixes the leak.

I originally had the second loop loop for `system->nodes[nodeType].count` iterations but that doesn't work because sometimes we set the count for `NET` nodes to `0` [here](
https://github.com/NVIDIA/nccl/blob/3899f6e0f219b0cbf58537f791b0dd104b377750/src/graph/paths.cc#L311) but we still have [`link->remNode`](https://github.com/NVIDIA/nccl/blob/3899f6e0f219b0cbf58537f791b0dd104b377750/src/graph/paths.cc#L55) point to `NET` nodes which causes us to [allocate into `paths`](https://github.com/NVIDIA/nccl/blob/3899f6e0f219b0cbf58537f791b0dd104b377750/src/graph/paths.cc#L57) for `NET` nodes.

To reproduce upgrade TF to use NCCL 2.6.5-2 and then run

```
$ bazel test --config=cuda tensorflow/core/nccl:nccl_manager_test_gpu --test_filter='NcclManagerTest/0.MultiNodeSingle'
```

although this test might not fail as-is since the leak checker we use internally might not be available in open source.

**Comment by sanjoy** [comment]
CC @chsigg @dubey

**Comment by sjeaugey** [comment]
Thanks for the report. Indeed we have a fix for that which we didn't push yet. CC @lukeyeager

Is that a serious issue for TF that needs to be fixed quickly or can it wait a bit ?

Most frameworks don't routinely create and destroy NCCL communicators, so memory leaks in NCCL usually don't cause much trouble and have a relatively low impact.

**Comment by dubey** [comment]
It would be good to get a fix soon, because we would like to include NCCL 2.5.6 in the next TF release.

The issue impacts our tests, which create multiple communicators and run leak checkers automatically.  I'd rather not disable the test.

Do you have an ETA for the fix?

**Comment by sjeaugey** [comment]
@sanjoy @dubey let us know if PR #283 solves the leak.

**Comment by dubey** [comment]
Thanks!  Yes, it fixes the leak.
