### ISSUE TITLE
NCCL WARN Cuda failure 'out of memory' and timeout

### ISSUE THREAD

**Issue by nnigania** [NVIDIA/nccl#295]
hi,

I was trying to run a official TF model, which used to run before. But when I use the latest nccl version: 2.5.7, I hit a timeout. It tells me that "NCCL WARN Cuda failure 'out of memory' " and times out. Any suggestions or recommended fixes will be appreciated.

To Reproduce:
1) setup your TF environment (https://pypi.org/project/tf-nightly-gpu/)
2) git clone https://github.com/tensorflow/models.git
3) cd models
4) export PYTHONPATH=.
5) python3 official/vision/image_classification/resnet_imagenet_main.py --batch_size=1024 --data_dir=/data/imagenet --enable_eager --log_steps=10 --model_dir=/workspace/benchmarks/perfzero/workspace/output/2019-12-13-12-21-23-371701/benchmark_8_gpu --num_gpus=8 --noreport_accuracy_metrics --skip_eval --train_steps=110 --use_synthetic_data=True

I also added the following flags to debug NCCL when then shows the warnings/errors:
NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL

Please find the log file attached.
[nvidia_nccl_debug.txt](https://github.com/NVIDIA/nccl/files/4258187/nvidia_nccl_debug.txt)

**Comment by sjeaugey** [comment]
I guess TF has been tuned to leave a certain amount of memory to NCCL, and the increase of memory usage in 2.5.7 went over that threshold. Setting `NCCL_BUFFSIZE=2097152` would probably avoid the issue (and should not impact performance much on a single node).

Maybe there is also a way in TF to give more memory to NCCL.

**Comment by dubey** [comment]
@sjeaugey to clarify, is increased memory usage expected from NCCL 2.5.7?

**Comment by nluehr** [comment]
I've worked around this issue by bumping the min_system_memory from 5 to 6% in [gpu_device.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_device.cc#L817).

**Comment by nnigania** [comment]
thanks for your replies, NCCL_BUFFSIZE=2097152 still caused a OOM / timeout. 
Currently trying out Nathan's suggestion.

**Comment by nnigania** [comment]
@nluehr: thanks for your reply, bumping up min_system_memory from 5 to 6% helps with the NCCL OOM.

**Comment by TarzanZhao** [comment]
I also meet this error. But what min_system_memory exactly is? How could I configure it?
