### ISSUE TITLE
Infiniband regression in NCCL 2.5.6-2

### ISSUE THREAD

**Issue by cswinter** [NVIDIA/nccl#302]
I have an application that uses NCCL via PyTorch 1.4 compiled from source with NCCL 2.5.6-2 and crashes early with this error message on all/most ranks:

`NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.5.6`

Some of the ranks are printing out this error message:

`NCCL WARN Call to ibv_modify_qp failed with error No such device`

Running the same code on an image that is identical except that it was built with NCCL 2.4.8-1  runs fine. However, we are unable to use that version of NCCL for larger workloads because our nodes have multiple mellanox devices and we invariably run into https://github.com/NVIDIA/nccl/issues/179.

Additional datapoints:
- After startup, the application performs one allreduce operation across all ranks to detect issues which appears to complete successfully despite the warnings.
- nccl-tests runs to successfully and without printing any warnings.

As temporary workaround, I would also be interested in backporting the fix to https://github.com/NVIDIA/nccl/issues/179 to NCCL 2.4.8-1 but the referenced commit seems to incorporate a number of different changes. Is there a more minimal diff I could apply to get the fix?

**Comment by sjeaugey** [comment]
Can we get the backtrace of the WARN (setting NCCL_DEBUG=INFO should get you that) ?

Can you try with NCCL 2.6 and see if it still fails (see the v2.6 branch) ?

Thanks !

**Comment by cswinter** [comment]
Here's the full logs from one of the ranks with NCC_DEBUG=INFO:

```
[155] crow-ib-new-nccl-256-info-19:5330:5330 [3] NCCL INFO Bootstrap : Using [0]eth0:10.100.62.64<0>
[155] crow-ib-new-nccl-256-info-19:5330:5330 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[155] crow-ib-new-nccl-256-info-19:5330:5330 [3] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/RoCE [4]mlx5_4:1/IB ; OOB eth0:10.100.62.64<0>
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff00,000fffff
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Threads per block : 512/640/512
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO threadThresholds 8/8/64 | 2048/8/64
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Trees [0] 154/-1/-1->155->153|153->155->154/-1/-1 [1] 153/-1/-1->155->154|154->155->153/-1/-1 [2] 154/-1/-1->155->153|153->155->154/-1/-1 [3] 153/146/162->155->154|154->155->153/146/162
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 00 : 155[3d000] -> 157[b2000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 00 : 155[3d000] -> 153[1b000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 00 : 155[3d000] -> 154[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 01 : 155[3d000] -> 153[1b000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 01 : 155[3d000] -> 154[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 02 : 155[3d000] -> 157[b2000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 02 : 155[3d000] -> 153[1b000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 02 : 155[3d000] -> 154[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 03 : 155[3d000] -> 153[1b000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to 0.
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 03 : 146[3e000] -> 155[3d000] [receive] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 03 : 162[3e000] -> 155[3d000] [receive] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 03 : 155[3d000] -> 154[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO NCCL_NET_GDR_READ set by environment to 0.
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 03 : 155[3d000] -> 146[3e000] [send] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO Ring 03 : 155[3d000] -> 162[3e000] [send] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:5499 [3] NCCL INFO comm 0x7f45d0007e20 rank 155 nranks 256 cudaDev 3 busId 3d000 - Init COMPLETE
[155] 03/16 04:24:42 PM I Creating layout...
[155] 03/16 04:24:42 PM I Creating test dataset iter...
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff00,000fffff
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Threads per block : 512/640/512
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO threadThresholds 8/8/64 | 16/8/64
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1 [2] -1/-1/-1->1->0|0->1->-1/-1/-1 [3] -1/-1/-1->1->0|0->1->-1/-1/-1
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Ring 00 : 1[3d000] -> 0[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Ring 01 : 1[3d000] -> 0[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Ring 02 : 1[3d000] -> 0[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO Ring 03 : 1[3d000] -> 0[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:5528 [3] NCCL INFO comm 0x7f45d0574260 rank 1 nranks 2 cudaDev 3 busId 3d000 - Init COMPLETE
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff00,000fffff
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Threads per block : 512/640/512
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO threadThresholds 8/8/64 | 256/8/64
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Trees [0] -1/-1/-1->19->18|18->19->-1/-1/-1 [1] 10/26/-1->19->18|18->19->10/26/-1
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 00 : 19[3d000] -> 20[3e000] [send] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 00 : 19[3d000] -> 18[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 01 : 19[3d000] -> 20[3e000] [send] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 01 : 10[3e000] -> 19[3d000] [receive] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 01 : 26[3e000] -> 19[3d000] [receive] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 01 : 19[3d000] -> 18[3e000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 01 : 19[3d000] -> 10[3e000] [send] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO Ring 01 : 19[3d000] -> 26[3e000] [send] via NET/IB/2
[155] crow-ib-new-nccl-256-info-19:5330:7953 [3] NCCL INFO comm 0x7f45d0777860 rank 19 nranks 32 cudaDev 3 busId 3d000 - Init COMPLETE
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff00,000fffff
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Threads per block : 512/640/512
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO threadThresholds 8/8/64 | 64/8/64
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Trees [0] -1/-1/-1->5->4|4->5->-1/-1/-1 [1] 4/-1/-1->5->1|1->5->4/-1/-1 [2] -1/-1/-1->5->4|4->5->-1/-1/-1 [3] 4/1/-1->5->-1|-1->5->4/1/-1
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Ring 00 : 5[3d000] -> 6[b2000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Ring 00 : 5[3d000] -> 4[1b000] via P2P/IPC
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Ring 01 : 2[b2000] -> 5[3d000] [receive] via NET/IB/3
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO Ring 01 : 5[3d000] -> 4[1b000] via P2P/IPC
[155]
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] misc/ibvwrap.cc:284 NCCL WARN Call to ibv_modify_qp failed with error Invalid argument
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO transport/net_ib.cc:368 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO transport/net_ib.cc:471 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO include/net.h:22 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO transport/net.cc:190 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO init.cc:424 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO init.cc:617 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO init.cc:732 -> 2
[155] crow-ib-new-nccl-256-info-19:5330:7970 [3] NCCL INFO group.cc:63 -> 2 [Async thread]
[155] Traceback (most recent call last):
[155]   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[155]     "__main__", mod_spec)
[155]   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
[155]     exec(code, run_globals)
[155]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/__main__.py", line 7, in <module>
[155]     main()
[155]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/run.py", line 196, in main
[155]     run_command_line(args)
[155]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/run.py", line 42, in run_command_line
[155]     run_module(sys.argv[0], run_name='__main__', alter_sys=True)
[155]   File "/opt/conda/lib/python3.7/runpy.py", line 205, in run_module
[155]     return _run_module_code(code, init_globals, run_name, mod_spec)
[155]   File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
[155]     mod_name, mod_spec, pkg_name, script_name)
[155]   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
[155]     exec(code, run_globals)
<REDACTED>
[155]   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 904, in all_reduce
[155]     work = group.allreduce([tensor], opts)
[155] RuntimeError[155] : NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.5.6
```

I will try with 2.6 as well.

**Comment by cswinter** [comment]
@sjeaugey I'm still seeing this on 2.6.2-1

```
[56] crow-ib-new-nccl-262-b-7:7240:7240 [0] NCCL INFO Bootstrap : Using [0]eth0:10.100.72.18<0>
[56] crow-ib-new-nccl-262-b-7:7240:7240 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[56] crow-ib-new-nccl-262-b-7:7240:7240 [0] NCCL INFO NET/IB : Using [0]mlx5_3:1/IB [1]mlx5_0:1/IB [2]mlx5_2:1/RoCE [3]mlx5_4:1/IB ; OOB eth0:10.100.72.18<0>
[56] crow-ib-new-nccl-262-b-7:7240:7240 [0] NCCL INFO Using network IB
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO Threads per block : 512/640/512
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO threadThresholds 8/8/64 | 2048/8/64 | 8/8/64
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO Trees [0] -1/-1/-1->56->62|62->56->-1/-1/-1 [1] 58/-1/-1->56->62|62->56->58/-1/-1 [2] -1/-1/-1->56->62|62->56->-1/-1/-1 [3] 58/-1/-1->56->62|62->56->58/-1/-1
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO Ring 00 : 51[3d000] -> 56[1a000] [receive] via NET/IB/2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO Ring 00 : 56[1a000] -> 58[3e000] via P2P/IPC
[56]
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] misc/ibvwrap.cc:284 NCCL WARN Call to ibv_modify_qp failed with error Invalid argument
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO transport/net_ib.cc:393 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO transport/net_ib.cc:496 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO include/net.h:22 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO transport/net.cc:158 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO init.cc:442 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO init.cc:788 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO init.cc:859 -> 2
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO group.cc:63 -> 2 [Async thread]
[56] Traceback (most recent call last):
[56]   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[56]     "__main__", mod_spec)
[56]   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
[56]     exec(code, run_globals)
[56]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/__main__.py", line 7, in <module>
[56]     main()
[56]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/run.py", line 196, in main
[56]     run_command_line(args)
[56]   File "/opt/conda/lib/python3.7/site-packages/mpi4py/run.py", line 42, in run_command_line
[56]     run_module(sys.argv[0], run_name='__main__', alter_sys=True)
[56]   File "/opt/conda/lib/python3.7/runpy.py", line 205, in run_module
[56]     return _run_module_code(code, init_globals, run_name, mod_spec)
[56]   File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
[56]     mod_name, mod_spec, pkg_name, script_name)
[56]   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
[56]     exec(code, run_globals)
<REDACTED>
[56]   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 902, in all_reduce
[56]     work = _default_pg.allreduce([tensor], opts)
[56] RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.6.2
[56] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 56
```

**Comment by sjeaugey** [comment]
Thanks.
Is this error happening every time or is it only when we get a mix of nodes with different GPU sets on each ?
Can you reproduce the issue with the NCCL tests ?

**Comment by cswinter** [comment]
nccl-tests run successfully and without printing warnings. The error is happening every time in this application, though one initial allreduce operation across all nodes appears to succeed.

Not sure what you mean by "mix of nodes with different GPU sets". All nodes are identical, but there are are multiple sets of communicator groups spanning subsets of nodes/gpus.

**Comment by sjeaugey** [comment]
Ok so the error is happening while creating a communicator across multiple nodes, but not using all the GPUs. Is that right ?
Could you list the GPUs which are part of the failing communicator ? That would help a lot understand what's happening.

**Comment by cswinter** [comment]
It's a fairly complex application and I'm not entirely sure what it is doing at the moment at which it fails. I will try to gather more detailed information or come up with a smaller repro though this might prove difficult.

In the meantime, I'd still be interested in trying to backport the fix for #179 to v2.4.8-1. Do you have a patch with just that change that could be easily applied?

**Comment by sjeaugey** [comment]
Unfortunately not. The reason that bug took so long to be fixed is because it required a full rewrite of the topology detection and ring creation system. And as we see here, there might still be corner cases which are still not well handled.

**Comment by sjeaugey** [comment]
Actually I missed this :
```
[56] crow-ib-new-nccl-262-b-7:7240:7240 [0] NCCL INFO NET/IB : Using [0]mlx5_3:1/IB [1]mlx5_0:1/IB [2]mlx5_2:1/RoCE [3]mlx5_4:1/IB ; OOB eth0:10.100.72.18<0>
```
Seems like we have 4 interfaces used, 3 in IB mode and 1 in RoCE mode. I would advise to exclude the RoCE interface (using NCCL_IB_HCA) as we might end up trying to communicate between a RoCE card and an IB card (which is not going to happen).
And we do see NET/2 is being used :
```
[56] crow-ib-new-nccl-262-b-7:7240:7401 [0] NCCL INFO Ring 00 : 51[3d000] -> 56[1a000] [receive] via NET/IB/2
```
Is there a reason for using this interface ? Can you dump the topology with NCCL_TOPO_DUMP_FILE=system.xml (on NCCL 2.6) ?

**Comment by cswinter** [comment]
There ought to be 5 total interfaces, 4 ib and 1 ethernet (which should not be used). Will try excluding the ethernet interface and get you the topo dump.

**Comment by cswinter** [comment]
I've tried excluding the ethernet device, it seems to just hang now while creating mpi groups.
Here is the topology information:

```
<system version="1">
  <cpu numaid="0" affinity="0000,0fffff00,000fffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:18:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:1a:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="0" sm="70" rank="0" gdr="0">
          <nvlink target="0000:3e:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:3d:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:1b:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:88:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:1c:00.0" class="0x020700" link_speed="8 GT/s" link_width="16">
        <nic>
          <net name="mlx5_0" dev="2" speed="100000" port="1" guid="0x62fcd400039f59b8" maxconn="262144" gdr="0"/>
        </nic>
      </pci>
    </pci>
    <pci busid="0000:3b:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:3f:00.0" class="0x020700" link_speed="8 GT/s" link_width="16">
        <nic>
          <net name="mlx5_1" dev="0" speed="100000" port="1" guid="0x62fcd400039f59b8" maxconn="262144" gdr="0"/>
        </nic>
      </pci>
    </pci>
  </cpu>
  <cpu numaid="1" affinity="ffff,f00000ff,fff00000" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:86:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:8a:00.0" class="0x020700" link_speed="8 GT/s" link_width="16">
        <nic>
          <net name="mlx5_3" dev="1" speed="100000" port="1" guid="0x9e00d500039f59b8" maxconn="262144" gdr="0"/>
        </nic>
      </pci>
    </pci>
    <pci busid="0000:af:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:b1:00.0" class="0x020700" link_speed="8 GT/s" link_width="16">
        <nic>
          <net name="mlx5_4" dev="3" speed="100000" port="1" guid="0x9e00d500039f59b8" maxconn="262144" gdr="0"/>
        </nic>
      </pci>
    </pci>
  </cpu>
</system>
```

**Comment by cswinter** [comment]
2.4.8-1 still runs fine after excluding the ethernet device.

**Comment by cswinter** [comment]
Actually, I've done some more testing and excluding the ethernet device with NCCL_IB_HCA does seem to work at least some of the time.

**Comment by cswinter** [comment]
We have now confirmed that this fixes the issue. 🎉 
Thanks for all the help!

**Comment by danthe3rd** [comment]
Hello,
Is it possible to reopen the issue? I believe NCCL trying to communicate between a RoCE card and an IB card is a bug isn't it?
Thanks!

**Comment by sjeaugey** [comment]
At this point and since the addition of inter-node communication in NCCL 2.0, the code assumes it can use all NICs that it can see to communicate with others, i.e. they can all communicate with each other. So it is the responsibility of the user to filter out any interface that would not respect this rule.

Being able to support heterogeneous NICs is a tremendous amount of work; we gave it a try or two already -- it is not easy. In any case, it would be considered as a new feature.

**Comment by dchaws** [comment]
@cswinter I'm having a similar issue I think. What was the exact command you used to exclude the RoCE interfaces using NCCL_IB_HCA?

**Comment by sjeaugey** [comment]
I'd advise to run `ibv_devinfo` and look for interfaces with `link_layer: Ethernet`, when exclude them with  e.g. `NCCL_IB_HCA=^mlx5_2` if `mlx5_2` is the Ethernet interface.

**Comment by dchaws** [comment]
Thank you. Looking at `ibv_devinfo` I see that mlx5_2 and `mlx_3 show `

```
transport:			InfiniBand (0)
link_layer:		Ethernet
```

So I excluded those using 

`export NCCL_IB_HCA=^mlx5_2,mlx5_3`

Curious, is there an underlying problem in NCCL? I.e. mixing infiniband with ethernet?

**Comment by sjeaugey** [comment]
Some operations like allreduce will actually work using both IB and RoCE NICs. Alltoall would probably not however.

So at this point we are not explicitly forbidding mixing different interface types.

**Comment by bradfox2** [comment]
Adding a note here for future searchers - in our case we also found this applicable to mellanox cards with multiple ports, where only 1 of 2 ports was active.   We needed to exclude non-active ports.
