### ISSUE TITLE
NCCL infiniband performance

### ISSUE THREAD

**Issue by christopherhesse** [NVIDIA/nccl#307]
Hi NCCL devs!  I have two machines in a cluster communicating over infiniband.  There is 400 Gb/sec of bandwidth available between the machines (confirmed with `ib_send_bw`), but: 

 1) `nccl-tests` only achieves about 20 GB/s, roughly half of what I would expect
 2) there is a decent amount of variance

running `broadcast_perf` on 2 machines:

```
NCCL_DEBUG=INFO mpiexec -f <hosts file> /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half
```

[nccl.txt](https://github.com/NVIDIA/nccl/files/4357371/nccl.txt)

This log shows that (1) nccl is getting between about 15 and 20 GB/s in `busbw`, and (2) the speed isn't monotonic for larger amounts of data and can change significantly across runs.

Any ideas on what could be going wrong here? I would expect that I should be getting something closer to 45 GB/s and that there would be more consistency across runs.

env vars:
```
NCCL_IB_HCA=^mlx5_2
NCCL_SOCKET_IFNAME=eth
```

ibstatus
```
Infiniband device 'mlx5_0' port 1 status:
        default gid:     fe80:0000:0000:0000:b859:9f03:00d4:fe72
        base lid:        0x2ed
        sm lid:          0x10d
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand

Infiniband device 'mlx5_1' port 1 status:
        default gid:     fe80:0000:0000:0000:b859:9f03:00d4:fe74
        base lid:        0x5b3
        sm lid:          0x10d
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand

Infiniband device 'mlx5_2' port 1 status:
        default gid:     0000:0000:0000:0000:0000:0000:0000:0000
        base lid:        0x0
        sm lid:          0x0
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      Ethernet

Infiniband device 'mlx5_3' port 1 status:
        default gid:     fe80:0000:0000:0000:b859:9f03:00d5:04c6
        base lid:        0x2f3
        sm lid:          0x10d
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand

Infiniband device 'mlx5_4' port 1 status:
        default gid:     fe80:0000:0000:0000:b859:9f03:00d5:04c8
        base lid:        0x679
        sm lid:          0x10d
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand
```

**Comment by sjeaugey** [comment]
A few questions :
 - What about allreduce performance ? Do you get 20 or 40 GB/s ?
 - Did you try with 2.5 ? 2.6.2 is a preview version and I see we don't use GPU Direct RDMA in both directions -- maybe a bug we fixed since then (I'm overdue for a refresh of 2.6)

Are you launching mpirun with --bind-to none ? By default MPI binds each process to a single core which can cause high variability since the network thread will be competing for the CPU with other threads.

**Comment by christopherhesse** [comment]
Thanks for the quick response!

* I also get 20 GB/s for allreduce
* I did not, this seemed to be the version that had the fewest issues.  I can try that version if it doesn't hang on our cluster.
* No, but here are the results for a few variants which don't seem to show any improvement:

`mpiexec -f <hosts file> /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > all-reduce.txt`
[all-reduce.txt](https://github.com/NVIDIA/nccl/files/4357465/all-reduce.txt)

`mpiexec -f $RCALL_MPI_HOSTS_FILE -ppn 1 /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 8 -c 0 -d half > all-reduce-1ppn.txt`
[all-reduce-1ppn.txt](https://github.com/NVIDIA/nccl/files/4357466/all-reduce-1ppn.txt)

`mpiexec -f $RCALL_MPI_HOSTS_FILE --bind-to none /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > all-reduce-bind-to-none.txt`
[all-reduce-bind-to-none.txt](https://github.com/NVIDIA/nccl/files/4357467/all-reduce-bind-to-none.txt)

**Comment by christopherhesse** [comment]
I see substantially improved performance with 2.5.7-1, 36 GB/s (at least with all_reduce, broadcast does not show the same improvement).  Thanks!  I have a few questions from this:

1) Will there be a 2.6 version with similar performance?
2) Any idea why broadcast doesn't see similar improvements?
3) I feel like this should get up to about 45 GB/s given that the NICs do 50 GB/s, do I need to tune some environment variables?

`NCCL_DEBUG=INFO mpiexec -f <hosts file> /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1.txt`

[allreduce-2.5.7-1.txt](https://github.com/NVIDIA/nccl/files/4357506/allreduce-2.5.7-1.txt)

**Comment by sjeaugey** [comment]
1. It should, sorry, as I mentioned I wanted to update the 2.6 branch for some time now. As the 2.5 log confirms, there seems to be a bug in 2.6.2 and we're not using GPU direct RDMA for reads.
2. I forgot to ask you that first, can you run again the allreduce performance test forcing NCCL_ALGO=RING ? By default, on 2 nodes, we use trees which due to some trick can reach up to 2x the network bandwidth. That can make allreduce BW achieve 36 GB/s even if the network is limited to 20 GB/s somehow ... which is not helpful to debug network issues. Forcing rings makes numbers easier to interpret.
3. I agree, and I always get 47 GB/s on DGX-1 nodes (except with 2 nodes / trees where I get 58 IIRC). Let's look at the performance we get with rings on 2.5. If it's not above 40, then there might be some network contention. If you have 2 levels of switches, you only need 2 flows to be routed through the same link to halve the bandwidth. Another way to debug that kind of network issue is to try each NIC individually (NCCL_IB_HCA=mlx5_x) then add a second interface, etc ... and see where bandwidth no longer adds up. With rings, you should get ~12 GB/s with each NIC, then ~24 when using 2 NICs, etc ...

**Comment by christopherhesse** [comment]
1. Great!
2. 

`NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-ring.txt`

[allreduce-2.5.7-1-ring.txt](https://github.com/NVIDIA/nccl/files/4357598/allreduce-2.5.7-1-ring.txt)

Yeah looks like it is 20 GB/s still.

3.  Good to hear!

`NCCL_IB_HCA=mlx5_0 NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-1nic.txt`
[allreduce-2.5.7-1-1nic.txt](https://github.com/NVIDIA/nccl/files/4357608/allreduce-2.5.7-1-1nic.txt)


`NCCL_IB_HCA=mlx5_1 NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-1nic-alt.txt`
[allreduce-2.5.7-1-1nic-alt.txt](https://github.com/NVIDIA/nccl/files/4357609/allreduce-2.5.7-1-1nic-alt.txt)


`NCCL_IB_HCA=mlx5_0,mlx5_1 NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-2nic.txt`
[allreduce-2.5.7-1-2nic.txt](https://github.com/NVIDIA/nccl/files/4357611/allreduce-2.5.7-1-2nic.txt)

`NCCL_IB_HCA=mlx5_0,mlx5_3 NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-2nic-alt.txt`
[allreduce-2.5.7-1-2nic-alt.txt](https://github.com/NVIDIA/nccl/files/4357613/allreduce-2.5.7-1-2nic-alt.txt)

`NCCL_IB_HCA=mlx5_0,mlx5_1,mlx5_3 NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-3nic.txt`
[allreduce-2.5.7-1-3nic.txt](https://github.com/NVIDIA/nccl/files/4357617/allreduce-2.5.7-1-3nic.txt)

`NCCL_IB_HCA=mlx5_0,mlx5_1,mlx5_3,mlx5_4 NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-4nic.txt`
[allreduce-2.5.7-1-4nic.txt](https://github.com/NVIDIA/nccl/files/4357616/allreduce-2.5.7-1-4nic.txt)

The most suspicious thing I see here is `2nic` vs `2nic-alt`, in `2nic` I use `mlx5_0,mlx5_1` and get 11 GB/s no improvement over `mlx5_0` with 11 GB/s.  In `2nic-alt` I use `mlx5_0,mlx5_3` and get 20 GB/s.  This makes me think that the second interface of each card is adding nothing to the performance.

Do you think this is an issue with our cluster configuration?

**Comment by sjeaugey** [comment]
Hum what do you mean by "second interface" ? Are you trying to use two ports of the same NIC ? That wouldn't give you 20 GB/s since the PCI interface is limited to 12 GB/s.

Maybe I should have asked that first : what is you node topology ? Can you set NCCL_DEBUG_SYBSYS=GRAPH and report the graph log ?

**Comment by AddyLaddy** [comment]
Typo; `NCCL_DEBUG_SUBSYS=GRAPH`

**Comment by christopherhesse** [comment]
My understanding is that each 200 Gbit infiniband card appears as 2 100 Gbit interfaces, so I observe no increase in performance when using both interfaces for a single card.  I believe there are two ConnectX-6 adapters, each with 2 PCIe 3.0 16x links.  Each GPU shares a PCIe switch with one other GPU and one of the 16x network links.  Provided GPUDirect is working, I would expect that each pair of GPUs can deliver 12GB/s to their half of each card, for a total throughput of 48 GB/s.

Isn't PCIe 3.0 16x supposed to be 15.75 GB/s?

Here's the output from `NCCL_DEBUG_SUBSYS=GRAPH NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-2.5.7-1-graph.txt`:

[allreduce-2.5.7-1-graph.txt](https://github.com/NVIDIA/nccl/files/4362070/allreduce-2.5.7-1-graph.txt)

**Comment by sjeaugey** [comment]
Ah, OK understood. You have CX6 split in two PCI Gen3 and a 200G link. Then you need 2.6 since NCCL needs to detect the speed of the link and 2.5 does not support the detection of HDR links.

If you could try again with 2.6, NCCL_NET_GDR_READ=1 and NCCL_DEBUG_SUBSYS=GRAPH, I could confirm 2.6 does the right thing; you might actually get 40 GB/s that way.

**Comment by christopherhesse** [comment]
Is this the correct command?

`NCCL_NET_GDR_READ=1 NCCL_DEBUG_SUBSYS=GRAPH NCCL_ALGO=RING NCCL_DEBUG=INFO mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M
-f 2 -g 1 -c 0 -d half > ~/allreduce-2.6.2.txt`

[allreduce-2.6.2.txt](https://github.com/NVIDIA/nccl/files/4362158/allreduce-2.6.2.txt)

**Comment by sjeaugey** [comment]
OK, so the topology tells me that you have 2 CX-6 with indeed two PCI connections, but each NIC only has a single 100G cable attached to it.

It shows as 4 interfaces, but in practice you only have 2 100G ports going out of the node, each port being shown twice (once per PCI attachment). 

A 200G cable with 2 PCI connections does not show up at 2x100G but as 2x200G (which is misleading but there are good reasons for that). The `ibstat` you provided did show that both cables negociated 100G. The best performance you can get is indeed 24 GB/s. If you replaced those two cables with 200G HDR cables, you should be able to get 48 GB/s.

**Comment by sjeaugey** [comment]
@christopherhesse I just pushed 2.6.4 to the v2.6 branch, let me know if you can get 24 GB/s without setting NCCL_NET_GDR_READ=1. Thanks !

**Comment by christopherhesse** [comment]
It seems like we tested only each link individually with `ib_send_bw`.  We can do some more testing once we figure out what is wrong with our link speed.  Thanks for the pointers!

**Comment by christopherhesse** [comment]
Thanks for all the help debugging, you were totally right and it sounds like we had a mis-configuration causing the cables to be detected as the wrong speed.  Sorry for the confusion!

Here are the values on the fixed version:

```
mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half
Warning: Permanently added '[10.64.156.136]:31338' (ECDSA) to the list of known hosts.
# nThread 1 nGpus 1 minBytes 1048576 maxBytes 2147483648 step: 2(factor) warmup iters: 5 iters: 20 validation: 0
#
# Using devices
#   Rank  0 Pid  29845 on dilldevib-0 device  0 [0x1a] Tesla V100-SXM2-32GB
#   Rank  1 Pid  29846 on dilldevib-0 device  1 [0x1b] Tesla V100-SXM2-32GB
#   Rank  2 Pid  29847 on dilldevib-0 device  2 [0x3d] Tesla V100-SXM2-32GB
#   Rank  3 Pid  29848 on dilldevib-0 device  3 [0x3e] Tesla V100-SXM2-32GB
#   Rank  4 Pid  29849 on dilldevib-0 device  4 [0x88] Tesla V100-SXM2-32GB
#   Rank  5 Pid  29850 on dilldevib-0 device  5 [0x89] Tesla V100-SXM2-32GB
#   Rank  6 Pid  29851 on dilldevib-0 device  6 [0xb2] Tesla V100-SXM2-32GB
#   Rank  7 Pid  29852 on dilldevib-0 device  7 [0xb3] Tesla V100-SXM2-32GB
#   Rank  8 Pid  18438 on dilldevib-1 device  0 [0x1a] Tesla V100-SXM2-32GB
#   Rank  9 Pid  18439 on dilldevib-1 device  1 [0x1b] Tesla V100-SXM2-32GB
#   Rank 10 Pid  18440 on dilldevib-1 device  2 [0x3d] Tesla V100-SXM2-32GB
#   Rank 11 Pid  18441 on dilldevib-1 device  3 [0x3e] Tesla V100-SXM2-32GB
#   Rank 12 Pid  18442 on dilldevib-1 device  4 [0x88] Tesla V100-SXM2-32GB
#   Rank 13 Pid  18443 on dilldevib-1 device  5 [0x89] Tesla V100-SXM2-32GB
#   Rank 14 Pid  18444 on dilldevib-1 device  6 [0xb2] Tesla V100-SXM2-32GB
#   Rank 15 Pid  18445 on dilldevib-1 device  7 [0xb3] Tesla V100-SXM2-32GB
#
#                                                     out-of-place                       in-place
#       size         count    type    root     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
     1048576        524288    half       0    71.91   14.58   14.58    N/A    71.24   14.72   14.72    N/A
     2097152       1048576    half       0    102.1   20.55   20.55    N/A    101.2   20.73   20.73    N/A
     4194304       2097152    half       0    167.5   25.05   25.05    N/A    168.8   24.85   24.85    N/A
     8388608       4194304    half       0    310.8   26.99   26.99    N/A    315.8   26.57   26.57    N/A
    16777216       8388608    half       0    538.2   31.17   31.17    N/A    535.4   31.34   31.34    N/A
    33554432      16777216    half       0    949.2   35.35   35.35    N/A    949.5   35.34   35.34    N/A
    67108864      33554432    half       0   1782.1   37.66   37.66    N/A   1770.3   37.91   37.91    N/A
   134217728      67108864    half       0   3384.3   39.66   39.66    N/A   3369.9   39.83   39.83    N/A
   268435456     134217728    half       0   6592.0   40.72   40.72    N/A   6559.2   40.92   40.92    N/A
   536870912     268435456    half       0    13177   40.74   40.74    N/A    13097   40.99   40.99    N/A
  1073741824     536870912    half       0    25106   42.77   42.77    N/A    25139   42.71   42.71    N/A
  2147483648    1073741824    half       0    49683   43.22   43.22    N/A    49650   43.25   43.25    N/A
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 33.2345
```

```
NCCL_NET_GDR_READ=1 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half
Warning: Permanently added '[10.64.156.136]:31338' (ECDSA) to the list of known hosts.
# nThread 1 nGpus 1 minBytes 1048576 maxBytes 2147483648 step: 2(factor) warmup iters: 5 iters: 20 validation: 0
#
# Using devices

#   Rank  0 Pid  29978 on dilldevib-0 device  0 [0x1a] Tesla V100-SXM2-32GB
#   Rank  1 Pid  29979 on dilldevib-0 device  1 [0x1b] Tesla V100-SXM2-32GB
#   Rank  2 Pid  29980 on dilldevib-0 device  2 [0x3d] Tesla V100-SXM2-32GB
#   Rank  3 Pid  29981 on dilldevib-0 device  3 [0x3e] Tesla V100-SXM2-32GB
#   Rank  4 Pid  29982 on dilldevib-0 device  4 [0x88] Tesla V100-SXM2-32GB
#   Rank  5 Pid  29983 on dilldevib-0 device  5 [0x89] Tesla V100-SXM2-32GB
#   Rank  6 Pid  29984 on dilldevib-0 device  6 [0xb2] Tesla V100-SXM2-32GB
#   Rank  7 Pid  29985 on dilldevib-0 device  7 [0xb3] Tesla V100-SXM2-32GB
#   Rank  8 Pid  19934 on dilldevib-1 device  0 [0x1a] Tesla V100-SXM2-32GB
#   Rank  9 Pid  19935 on dilldevib-1 device  1 [0x1b] Tesla V100-SXM2-32GB
#   Rank 10 Pid  19936 on dilldevib-1 device  2 [0x3d] Tesla V100-SXM2-32GB
#   Rank 11 Pid  19937 on dilldevib-1 device  3 [0x3e] Tesla V100-SXM2-32GB
#   Rank 12 Pid  19938 on dilldevib-1 device  4 [0x88] Tesla V100-SXM2-32GB
#   Rank 13 Pid  19939 on dilldevib-1 device  5 [0x89] Tesla V100-SXM2-32GB
#   Rank 14 Pid  19940 on dilldevib-1 device  6 [0xb2] Tesla V100-SXM2-32GB
#   Rank 15 Pid  19941 on dilldevib-1 device  7 [0xb3] Tesla V100-SXM2-32GB
#
#                                                     out-of-place                       in-place
#       size         count    type    root     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
     1048576        524288    half       0    70.88   14.79   14.79    N/A    71.40   14.68   14.68    N/A
     2097152       1048576    half       0    99.57   21.06   21.06    N/A    100.3   20.91   20.91    N/A
     4194304       2097152    half       0    169.0   24.82   24.82    N/A    166.2   25.24   25.24    N/A
     8388608       4194304    half       0    312.9   26.81   26.81    N/A    315.8   26.56   26.56    N/A
    16777216       8388608    half       0    540.8   31.02   31.02    N/A    544.1   30.83   30.83    N/A
    33554432      16777216    half       0    958.0   35.03   35.03    N/A    942.7   35.60   35.60    N/A
    67108864      33554432    half       0   1764.6   38.03   38.03    N/A   1769.8   37.92   37.92    N/A
   134217728      67108864    half       0   3374.9   39.77   39.77    N/A   3364.0   39.90   39.90    N/A
   268435456     134217728    half       0   6594.2   40.71   40.71    N/A   6594.4   40.71   40.71    N/A
   536870912     268435456    half       0    13198   40.68   40.68    N/A    13098   40.99   40.99    N/A
  1073741824     536870912    half       0    25132   42.72   42.72    N/A    25154   42.69   42.69    N/A
  2147483648    1073741824    half       0    49659   43.24   43.24    N/A    49677   43.23   43.23    N/A
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 33.2472
```

This is 2.6.2 but I don't see any difference with `NCCL_NET_GDR_READ=1`, should I see some difference there?

**Comment by kwen2501** [comment]
Hi @christopherhesse you should be able to see whether GDR read is enabled by setting `NCCL_DEBUG=INFO`. If it is enabled, you should be able to see logs like `[send] via NET/IB/<id>/GDRDMA`.

**Comment by sjeaugey** [comment]
Your numbers are expected with GDR reads is disabled. When launching with mpiexec/mpirun, you need to pass -x NCCL_NET_GDR_READ=1 as an mpirun/mpiexec option for it to be transmitted to all ranks.

Alternatively, upgrade NCCL, since the current version on master is now 2.6.4 and doesn't need that workaround.

**Comment by christopherhesse** [comment]
I think for mpich the environment variable handling might be the same:

```
NCCL_DEBUG=INFO  mpiexec -env NCCL_NET_GDR_READ 0 -f $RCALL_MPI_HOSTS_FILE python -c 'import os; print(os.environ["NCCL_NET_GDR_READ"])'
0
0
Warning: Permanently added '[10.64.156.136]:31338' (ECDSA) to the list of known hosts.
0
0
0
0
0
0
0
0
0
0
0
0
0
0```


```
NCCL_DEBUG=INFO NCCL_NET_GDR_READ=0 mpiexec -f $RCALL_MPI_HOSTS_FILE python -c 'import os; print(os.environ["NCCL_NET_GDR_READ"])'
0
Warning: Permanently added '[10.64.156.136]:31338' (ECDSA) to the list of known hosts.
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0```

**Comment by christopherhesse** [comment]
I'm not seeing any difference with this GDR setting, do I have something mis-configured?

`NCCL_DEBUG=INFO NCCL_NET_GDR_READ=0 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/broadcast-no-gdr.txt`

[broadcast-no-gdr.txt](https://github.com/NVIDIA/nccl/files/4446394/broadcast-no-gdr.txt)

`NCCL_DEBUG=INFO NCCL_NET_GDR_READ=1 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/broadcast-yes-gdr.txt`

[broadcast-yes-gdr.txt](https://github.com/NVIDIA/nccl/files/4446395/broadcast-yes-gdr.txt)

**Comment by christopherhesse** [comment]
I'm not seeing any difference with this GDR setting on NCCL 2.4.6 (besides GDRMA showing up on [send] lines), do I have something mis-configured? Or is this the expected behavior?

`NCCL_DEBUG=INFO NCCL_NET_GDR_READ=0 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/broadcast-no-gdr-2.txt`

[broadcast-no-gdr-2.txt](https://github.com/NVIDIA/nccl/files/4446483/broadcast-no-gdr-2.txt)

`NCCL_DEBUG=INFO NCCL_NET_GDR_READ=1 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/broadcast_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/broadcast-yes-gdr-2.txt`

[Uploading broadcast-yes-gdr-2.txt…]()

**Comment by sjeaugey** [comment]
Oh, I see, just wanted to make sure the environment was correct.

I had missed you were running the broadcast perf test, not allreduce. It might be worth checking the allreduce performance. Also I think 2.4.6 was a typo and you're running 2.6.4 (you really need 2.6 with your hardware setup).

**Comment by christopherhesse** [comment]
You are correct, the logs say `NCCL version 2.6.4+cuda10.1`

I'll try allreduce

**Comment by christopherhesse** [comment]
`NCCL_DEBUG=INFO NCCL_NET_GDR_READ=0 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-no-gdr.txt`

[allreduce-no-gdr.txt](https://github.com/NVIDIA/nccl/files/4446594/allreduce-no-gdr.txt)


`NCCL_DEBUG=INFO NCCL_NET_GDR_READ=1 mpiexec -f $RCALL_MPI_HOSTS_FILE /root/code/nccl-tests/build/all_reduce_perf -b 1M -e 2048M -f 2 -g 1 -c 0 -d half > ~/allreduce-yes-gdr.txt`

[allreduce-yes-gdr.txt](https://github.com/NVIDIA/nccl/files/4446595/allreduce-yes-gdr.txt)

What sort of difference should I be seeing when I enable GDR_READ?

**Comment by christopherhesse** [comment]
I guess GDR READ will remain a mystery for now, thanks for the help @sjeaugey!  Since we fixed the data rate, the results are much closer to what I expected.

We are observing some odd performance with > 2 nodes and want to determine if it's on the NCCL side or on our side, I will file a new issue for that.

**Comment by sjeaugey** [comment]
Allow me to re-open it. We have a bug actually.

Can you run allReduce again with NCCL_ALGO=RING ? That should give you closer to 48 GB/s.

The bug, I believe, happens with TREE, where we use the wrong NIC (which is why we see some connections not using GDR). So, can you then please apply the patch below and see if with TREE you can now get closer to 60 GB/s ?

```
diff --git a/src/graph/search.cc b/src/graph/search.cc
index b4c3e35..75801ee 100644
--- a/src/graph/search.cc
+++ b/src/graph/search.cc
@@ -804,7 +804,8 @@ ncclResult_t ncclTopoDumpGraphs(struct ncclTopoSystem* system, int ngraphs, stru
   return ncclSuccess;
 }

-ncclResult_t ncclTopoGetNetDev(struct ncclTopoGraph* graph, int dir, int channelId, int* dev) {
-  *dev = graph->inter[(channelId%graph->nChannels)*2+dir];
+ncclResult_t ncclTopoGetNetDev(struct ncclTopoGraph* graph, int rank, int channelId, int* dev) {
+  int index = graph->intra[0] == rank ? 0 : 1;
+  *dev = graph->inter[(channelId%graph->nChannels)*2+index];
   return ncclSuccess;
 }
diff --git a/src/transport/net.cc b/src/transport/net.cc
index db82a40..f281f89 100644
--- a/src/transport/net.cc
+++ b/src/transport/net.cc
@@ -60,7 +60,7 @@ ncclResult_t netSendSetup(struct ncclTopoSystem* topo, struct ncclTopoGraph* gra
   NCCLCHECK(ncclCalloc(&resources, 1));
   send->transportResources = resources;

-  NCCLCHECK(ncclTopoGetNetDev(graph, 1, channelId, &resources->netDev));
+  NCCLCHECK(ncclTopoGetNetDev(graph, myInfo->rank, channelId, &resources->netDev));
   NCCLCHECK(ncclTopoCheckGdr(topo, myInfo->busId, resources->netDev, 1, &resources->useGdr));

   int sendSize = sizeof(struct ncclSendMem);
@@ -83,7 +83,7 @@ ncclResult_t netRecvSetup(struct ncclTopoSystem* topo, struct ncclTopoGraph* gra
   NCCLCHECK(ncclCalloc(&resources, 1));
   recv->transportResources = resources;

-  NCCLCHECK(ncclTopoGetNetDev(graph, 0, channelId, &resources->netDev));
+  NCCLCHECK(ncclTopoGetNetDev(graph, myInfo->rank, channelId, &resources->netDev));
   NCCLCHECK(ncclTopoCheckGdr(topo, myInfo->busId, resources->netDev, 0, &resources->useGdr));

   int sendSize = sizeof(struct ncclSendMem);
```

**Comment by christopherhesse** [comment]
master version of NCCL:

ring (43.57): [nccl-master-RING.txt](https://github.com/NVIDIA/nccl/files/4458482/nccl-master-RING.txt)
tree (41.25): [nccl-master-TREE.txt](https://github.com/NVIDIA/nccl/files/4458483/nccl-master-TREE.txt)

patched master version of NCCL:

ring (27.36):  [nccl-master-patched-RING.txt](https://github.com/NVIDIA/nccl/files/4458468/nccl-master-patched-RING.txt)
tree (52.98): [nccl-master-patched-TREE.txt](https://github.com/NVIDIA/nccl/files/4458469/nccl-master-patched-TREE.txt)

Not sure why ring is so slow there.

**Comment by christopherhesse** [comment]
I included the environment variables and command at the top of each file, ignore the `NCCL_VERSION` env var since that's from the nvidia image I think.

**Comment by christopherhesse** [comment]
The slow performance of ring seems unrelated to the patch, since I have seen it sometimes with the master version.  I suspect another misconfiguration on our part.

**Comment by sjeaugey** [comment]
OK, now it makes more sense. 43.57 with ring is what you had before with 2.6.2 and GDR_READ=1. A bit disappointing, but consistent.

52.98 with Tree is much better. The patch seems to have solved the issue. But I'm worried the patch broke the ring performance. Could you run with NCCL_DEBUG_SUBSYS=GRAPH,INIT,NET ? The log you posted doesn't have the connection details so I can't check whether we used GPU Direct RDMA everywhere or not (hence whether we picked the right NIC or not).

**Comment by christopherhesse** [comment]
Sure, I will re-run, but like I mentioned I think it might be a bad machine or something like that, I believe I have seen the same issue with the unpatched master.

**Comment by christopherhesse** [comment]
I scheduled the job on the same two nodes each time (it looks like it reversed the order for the second run):

[nccl-master-rerun-RING.txt](https://github.com/NVIDIA/nccl/files/4458841/nccl-master-rerun-RING.txt)

[nccl-master-patched-rerun-RING.txt](https://github.com/NVIDIA/nccl/files/4458839/nccl-master-patched-rerun-RING.txt)

Master is fast, master patched is not.  So at least it's happened multiple times.

**Comment by sjeaugey** [comment]
Ah, yes indeed, I made a mistake. The patch will be a bit bigger.

**Comment by sjeaugey** [comment]
Here is a patch to apply on top of 2.6.4. Hopefully this time we'll select the right interface. It might also improve the tree performance. Let me know.

[fix_nic_selection.patch.txt](https://github.com/NVIDIA/nccl/files/4459050/fix_nic_selection.patch.txt)

**Comment by christopherhesse** [comment]
master:

ring (44.58): [nccl-master-RING.txt](https://github.com/NVIDIA/nccl/files/4459156/nccl-master-RING.txt)
tree (41.40): [nccl-master-TREE.txt](https://github.com/NVIDIA/nccl/files/4459157/nccl-master-TREE.txt)

master-patched:

ring (44.58): [nccl-master-patched-RING.txt](https://github.com/NVIDIA/nccl/files/4459154/nccl-master-patched-RING.txt)
tree (57.51): [nccl-master-patched-TREE.txt](https://github.com/NVIDIA/nccl/files/4459155/nccl-master-patched-TREE.txt)

Looking pretty good, thanks for the patch!

**Comment by sjeaugey** [comment]
That looks better ! Thanks for the feedback, I'll push the fix to master.

**Comment by christopherhesse** [comment]
Thanks for the crazy fast response time!
