### ISSUE TITLE
allgather hangs 

### ISSUE THREAD

**Issue by gavin1332** [NVIDIA/nccl#311]
We integrate NCCL 2.4.2 in our framework and `ncclAllGather` hangs after training for at least one day which could be reproduced.

**We are appreciated for any suggestions that could help us getting more useful information.**

The sample code listed below is frequently called during training:
```
CUDACHECK(cudaStreamSynchorize(stream));

NCCLCHECK(ncclAllGather(sendbuff, recvbuff, numel, dtype, comm, stream));

ncclResult_t nccl_error;
while (cudaStreamQuery(stream) != cudaSuccess) {
  if (ncclCommGetAsyncError(comm, &nccl_error) != ncclSuccess || nccl_error != ncclSuccess) {
    // logging
    break;
  }
}
```

All information we have collected by now:
-  one device per thread
- `cudaStreamSynchonize` is called before `ncclAllGather` without any error
-  `cudaStreamQuery` in a while body is called next to `ncclAllGather` and it keeps working fine for a long time util it is caught into the endless loop
-  The arguments passed to `ncclAllGather` seems reasonable which we print before `cudaStreamSynchorize`
sendbuff=0x7f1862d6d400 (reused address during one training pass, written by a former CUDA kenel)
recvbuff=0x7f175334d500 (reused address during one training pass)
sendcount=1533
datatype=ncclFloat

**Comment by gavin1332** [comment]
We are trying to export NCCL_P2P_DISABLE=1, but as it does not hangs in the first calling, it may not helpful.

**Comment by sjeaugey** [comment]
2.4.2 is known to have a bug in LL that causes a hang when the 32 bit counter loops.

**Comment by gavin1332** [comment]
Thanks! We will try to upgrade NCCL.

**Comment by gavin1332** [comment]
By setting NCCL_LL_THRESHOLD=0, the problem seems fixed. 3KS

**Comment by MajidSalimi** [comment]
I have faced the same problem with NCCL_Allgather when using larger message sizes (above 2^25 Bytes). I tried with both NCCL versions 2.19.4 and 2.23.4.
I normally call the NCCL_Allgather and then a NCC_StreamSynchronize. It goes well for a few iterations and then hangs.
I also tried with NCCL_LL_THRESHOLD=0, but it works sometimes and doesn't work sometimes!
Any advice on this?

**Comment by kiskra-nvidia** [comment]
May I ask that you open a new issue for this and include a reproducer as well as info on the system configuration / job size /etc?
