### ISSUE TITLE
Topology detection crashes for `all_reduce_perf` across the docker containers in same node.

### ISSUE THREAD

**Issue by 2sin18** [NVIDIA/nccl#326]
# 1. Description

## 1.1 Problem
Since NCCL 2.6, it would crash in topology detection for all_reduce_perf across the docker containers in same node, and reports `graph/xml.h:221 NCCL WARN KV Convert to int : could not find value of '0x060000' in dictionary` in `ncclTopoAddNvLinks`. But same code works fine with NCCL 2.5.

```bash
paidist001:337652:337652 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0
paidist001:337652:337652 [0] NCCL INFO Bootstrap : Using [0]eth0:192.168.1.120<0>
paidist001:337652:337652 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
paidist001:337652:337652 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0
paidist001:337652:337652 [0] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.1.120<0>
paidist001:337652:337652 [0] NCCL INFO Using network IB
paidist001:337652:337661 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for HCA 0 'mlx5_bond_0' (no module)
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/../max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/../max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/../max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/../max_link_width, ignoring

paidist001:337652:337661 [0] misc/nvmlwrap.cc:144 NCCL WARN nvmlDeviceGetHandleByPciBusId() failed: Not Found 

paidist001:337652:337661 [0] graph/xml.cc:562 NCCL WARN No NVML, trying to use CUDA instead
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:00/0000:00:00.0/max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:00/0000:00:00.0/../max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:00/0000:00:00.0/max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:00/0000:00:00.0/../max_link_width, ignoring

paidist001:337652:337661 [0] misc/nvmlwrap.cc:144 NCCL WARN nvmlDeviceGetHandleByPciBusId() failed: Not Found 

paidist001:337652:337661 [0] graph/xml.cc:562 NCCL WARN No NVML, trying to use CUDA instead
paidist001:337652:337661 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for HCA 0 'mlx5_bond_0' (no module)
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/../max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/../max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/../max_link_speed, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/../max_link_width, ignoring
paidist001:337652:337661 [0] NCCL INFO Topology detection : could not read /sys/devices/system/node/node-1/cpumap, ignoring

paidist001:337652:337661 [0] graph/xml.h:221 NCCL WARN KV Convert to int : could not find value of '0x060000' in dictionary
paidist001:337652:337661 [0] NCCL INFO graph/topo.cc:313 -> 3
paidist001:337652:337661 [0] NCCL INFO graph/topo.cc:397 -> 3
paidist001:337652:337661 [0] NCCL INFO graph/topo.cc:469 -> 3
paidist001:337652:337661 [0] NCCL INFO graph/topo.cc:569 -> 3
paidist001:337652:337661 [0] NCCL INFO init.cc:606 -> 3
paidist001:337652:337661 [0] NCCL INFO init.cc:860 -> 3
*** Error in `./all_reduce_perf': corrupted size vs. prev_size: 0x00007f4d54006670 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f4d9f2967e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x80dfb)[0x7f4d9f29fdfb]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f4d9f2a353c]
/home/pai/lib/libnccl.so.2(+0x23a3c)[0x7f4d9f829a3c]
/home/pai/lib/libnccl.so.2(+0x1b79b)[0x7f4d9f82179b]
/home/pai/lib/libnccl.so.2(+0x26e66)[0x7f4d9f82ce66]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f4d9f5f06ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f4d9f32641d]
```

## 1.2 Related problem

Besides nccl-test, A simple pytorch training job using NCCL based DDP also crashes in toplogy detection, but reports `graph/topo.cc:605 NCCL WARN Set CPU affinity : unable to find GPU/CPU for rank 0` in `ncclTopoSetAffinity`

```bash
paidist001:337963:337963 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0
paidist001:337963:337963 [0] NCCL INFO Bootstrap : Using [0]eth0:192.168.1.120<0>
paidist001:337963:337963 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
paidist001:337963:337963 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0
paidist001:337963:337963 [0] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.1.120<0>
paidist001:337963:337963 [0] NCCL INFO Using network IB
NCCL version 2.6.4ali+cuda10.0
paidist001:337963:337991 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for HCA 0 'mlx5_bond_0' (no module)
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/../max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/../max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/../max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/../max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/../max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/../max_link_width, ignoring

paidist001:337963:337991 [0] misc/nvmlwrap.cc:144 NCCL WARN nvmlDeviceGetHandleByPciBusId() failed: Not Found 

paidist001:337963:337991 [0] graph/xml.cc:562 NCCL WARN No NVML, trying to use CUDA instead
paidist001:337963:337991 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for HCA 0 'mlx5_bond_0' (no module)
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/../max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/../max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/../max_link_speed, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/../max_link_width, ignoring
paidist001:337963:337991 [0] NCCL INFO Topology detection : could not read /sys/devices/system/node/node-1/cpumap, ignoring
paidist001:337963:337991 [0] NCCL INFO Attribute coll of node net not found
paidist001:337963:337991 [0] NCCL INFO === System : maxWidth 3.1 ===
paidist001:337963:337991 [0] NCCL INFO CPU/0 (1/1/2)
paidist001:337963:337991 [0] NCCL INFO + PCI[12.0] - PCI/18000
paidist001:337963:337991 [0] NCCL INFO               + PCI[12.0] - GPU/4F000 (1)
paidist001:337963:337991 [0] NCCL INFO + SYS[9.0] - CPU/FFFFFFFFFFFFFFFF
paidist001:337963:337991 [0] NCCL INFO CPU/FFFFFFFFFFFFFFFF (1/1/2)
paidist001:337963:337991 [0] NCCL INFO + PCI[12.0] - PCI/D8000
paidist001:337963:337991 [0] NCCL INFO               + PCI[12.0] - NIC/DA000
paidist001:337963:337991 [0] NCCL INFO                             + NET[3.1] - NET/0 (6676a500039b0398/1/3.125000)
paidist001:337963:337991 [0] NCCL INFO + SYS[9.0] - CPU/0
paidist001:337963:337991 [0] NCCL INFO ==========================================
paidist001:337963:337991 [0] NCCL INFO GPU/4F000 :GPU/4F000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) CPU/FFFFFFFFFFFFFFFF (3/9.000000/SYS) NET/0 (6/3.125000/SYS) 
paidist001:337963:337991 [0] NCCL INFO NET/0 :GPU/4F000 (6/3.125000/SYS) CPU/0 (4/3.125000/SYS) CPU/FFFFFFFFFFFFFFFF (3/3.125000/PHB) NET/0 (0/5000.000000/LOC) 
paidist001:337963:337991 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 3.000000/3.000000, type LOC/SYS, sameChannels 1
paidist001:337963:337991 [0] NCCL INFO  0 : NET/0 GPU/1 NET/0
paidist001:337963:337991 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 6.000000/3.000000, type LOC/SYS, sameChannels 1
paidist001:337963:337991 [0] NCCL INFO  0 : NET/0 GPU/1 NET/0
paidist001:337963:337991 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
paidist001:337963:337991 [0] NCCL INFO NCCL_MAX_NRINGS set by environment to 12.
paidist001:337963:337991 [0] NCCL INFO NCCL_MIN_NRINGS set by environment to 4.
paidist001:337963:337991 [0] NCCL INFO Channel 00/04 :    0   1
paidist001:337963:337991 [0] NCCL INFO Channel 01/04 :    0   1
paidist001:337963:337991 [0] NCCL INFO Channel 02/04 :    0   1
paidist001:337963:337991 [0] NCCL INFO Channel 03/04 :    0   1
paidist001:337963:337991 [0] NCCL INFO Latency/AlgBw |    Tree/    LL |    Tree/ LL128 |    Tree/Simple |    Ring/    LL |    Ring/ LL128 |    Ring/Simple | CollNet/    LL | CollNet/ LL128 | CollNet/Simple |
paidist001:337963:337991 [0] NCCL INFO  Max NThreads |            512 |            640 |            512 |            512 |            640 |            256 |            512 |            640 |            512 |
paidist001:337963:337991 [0] NCCL INFO     Broadcast |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     4.5/   0.8 |     6.1/   0.0 |    15.0/   3.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
paidist001:337963:337991 [0] NCCL INFO        Reduce |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     4.5/   0.8 |     6.1/   0.0 |    15.0/   3.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
paidist001:337963:337991 [0] NCCL INFO     AllGather |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     4.5/   1.5 |     6.1/   0.0 |    15.0/   6.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
paidist001:337963:337991 [0] NCCL INFO ReduceScatter |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     4.5/   1.5 |     6.1/   0.0 |    15.0/   6.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
paidist001:337963:337991 [0] NCCL INFO     AllReduce |    14.4/   0.9 |    19.4/   0.0 |   100.0/   2.7 |     5.4/   0.8 |     8.6/   0.0 |    21.6/   3.0 |     9.4/   0.0 |     9.4/   0.0 |    10.7/   0.0 |
paidist001:337963:337991 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
paidist001:337963:337991 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] -1/-1/-1->0->1|1->0->-1/-1/-1 [2] 1/-1/-1->0->-1|-1->0->1/-1/-1 [3] -1/-1/-1->0->1|1->0->-1/-1/-1

paidist001:337963:337991 [0] graph/topo.cc:605 NCCL WARN Set CPU affinity : unable to find GPU/CPU for rank 0
paidist001:337963:337991 [0] NCCL INFO init.cc:779 -> 3
paidist001:337963:337991 [0] NCCL INFO init.cc:860 -> 3
paidist001:337963:337991 [0] NCCL INFO group.cc:63 -> 3 [Async thread]

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/pai/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/train.py", line 181, in main
    train_and_eval(gpu, rank, args)
  File "/workspace/train.py", line 42, in train_and_eval
    fc, device_ids=[gpu])
  File "/home/pai/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/home/pai/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /workspace/pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:400, internal error
```

# 2. How to reproduce

Step 1: Clone [nccl-tests modifed to be able to run without MPI](https://github.com/2sin18/nccl-tests) and build binaries.
Step 2: Launch two docker containers using below commands:

```bash
docker run \
--device /dev/infiniband/uverbs0 --device /dev/infiniband/rdma_cm --ulimit memlock=-1:-1 \
--gpus "device=0" --ipc host --network host --pid host --uts host \
--rm -it \
-e NCCL_DEBUG=INFO -e NCCL_DEBUG_SUBSYS=INIT,P2P,GRAPH \
-v /sys:/sys -v /path/to/my/workspace:/workspace -w /workspace \
my_docker_with_cuda_and_nccl_2604 bash
```

and

```bash
docker run \
--device /dev/infiniband/uverbs0 --device /dev/infiniband/rdma_cm --ulimit memlock=-1:-1 \
--gpus "device=1" --ipc host --network host --pid host --uts host \
--rm -it \
-e NCCL_DEBUG=INFO -e NCCL_DEBUG_SUBSYS=INIT,P2P,GRAPH \
-v /sys:/sys -v /path/to/my/workspace:/workspace -w /workspace \
my_docker_with_cuda_and_nccl_2604 bash
```

Step 3: Run below commands in corresponding containers:

```bash
NCCL_COMM_ID=myip:myport WORLD_SIZE=2 RANK=0 ./all_reduce_perf
```

and

```bash
NCCL_COMM_ID=myip:myport WORLD_SIZE=2 RANK=1 ./all_reduce_perf
```

# 3. Environment

## 3.1 Host

The host machine has 8 V100 GPUs with NVLink and bond RDMA NICs.

```bash
nvidia-smi 
   
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:4F:00.0 Off |                    0 |
| N/A   36C    P0    40W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:50:00.0 Off |                    0 |
| N/A   36C    P0    40W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:5F:00.0 Off |                    0 |
| N/A   36C    P0    42W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:60:00.0 Off |                    0 |
| N/A   37C    P0    40W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:B1:00.0 Off |                    0 |
| N/A   36C    P0    42W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:B2:00.0 Off |                    0 |
| N/A   36C    P0    41W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:DB:00.0 Off |                    0 |
| N/A   36C    P0    41W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:DC:00.0 Off |                    0 |
| N/A   36C    P0    40W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```bash
nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity
GPU0	 X 	NV1	NV1	NV2	SYS	SYS	NV2	SYS	0-95
GPU1	NV1	 X 	NV2	NV1	SYS	SYS	SYS	NV2	0-95
GPU2	NV1	NV2	 X 	NV2	NV1	SYS	SYS	SYS	0-95
GPU3	NV2	NV1	NV2	 X 	SYS	NV1	SYS	SYS	0-95
GPU4	SYS	SYS	NV1	SYS	 X 	NV2	NV1	NV2	0-95
GPU5	SYS	SYS	SYS	NV1	NV2	 X 	NV2	NV1	0-95
GPU6	NV2	SYS	SYS	SYS	NV1	NV2	 X 	NV1	0-95
GPU7	SYS	NV2	SYS	SYS	NV2	NV1	NV1	 X 	0-95

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
```

```bash
lspci -tvv | grep -v Intel | grep -v ']--$'
-+-[0000:d7]-+-00.0-[d8-dc]----00.0-[d9-dc]--+-04.0-[da]--+-00.0  Mellanox Technologies MT27710 Family [ConnectX-4 Lx]
 |           |                               |            \-00.1  Mellanox Technologies MT27710 Family [ConnectX-4 Lx]
 |           |                               +-08.0-[db]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 |           |                               \-0c.0-[dc]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 +-[0000:ae]-+-00.0-[af-b3]----00.0-[b0-b3]--+-04.0-[b1]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 |           |                               +-08.0-[b2]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 +-[0000:5c]-+-00.0-[5d-61]----00.0-[5e-61]--+-04.0-[5f]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 |           |                               +-08.0-[60]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 +-[0000:17]-+-00.0-[18-50]----00.0-[19-50]--+-04.0-[1a-4e]----00.0-[1b-4e]--+-00.0-[1c]----00.0  Red Hat, Inc. Virtio block device
 |           |                               |                               +-11.0-[2d]----00.0  Red Hat, Inc. Virtio network device
 |           |                               +-08.0-[4f]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
 |           |                               \-0c.0-[50]----00.0  NVIDIA Corporation GV100GL [Tesla V100 SXM2]
             +-1c.0-[01-02]----00.0-[02]----00.0  ASPEED Technology, Inc. ASPEED Graphics Family
```

## 3.2 Container

The container is based on `nvidia-cuda-10.0-cudnn7-devel-ubuntu16.04` and replaces the original NCCL by the latest NCCL (master branch, 2.6.4).

```bash
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        99c5edce
 Built:             Thu Jan  9 08:27:14 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       99c5edce
  Built:            Thu Jan  9 08:26:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 nvidia:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```bash
rpm -qa | grep nvidia
libnvidia-container1-1.0.5-1.x86_64
libnvidia-container-tools-1.0.5-1.x86_64
nvidia-container-toolkit-1.0.5-2.x86_64
nvidia-container-runtime-3.1.4-1.x86_64
```

**Comment by sjeaugey** [comment]
Could you dump the topology with `NCCL_TOPO_DUMP_FILE=system.xml` ?

It seems like a combination of containers and virtual machine which redefines the PCI tree.

**Comment by 2sin18** [comment]
> NCCL_TOPO_DUMP_FILE=system.xml

rank 0 generates system.xml and exits without message:

```xml
<system version="1">
  <cpu numaid="0" affinity="00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,ffffffff,ffffffff,ffffffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:18:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:4f:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="0" sm="70" rank="1" gdr="0">
          <nvlink target="0000:50:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:60:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:db:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:5f:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:50:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="-1"/>
      </pci>
    </pci>
  </cpu>
  <cpu numaid="-1" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:d8:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:da:00.0" class="0x020000" link_speed="" link_width="0">
        <nic>
          <net name="mlx5_bond_0" dev="0" speed="25000" port="1" guid="0x6676a500039b0398" maxconn="262144" gdr="0"/>
        </nic>
      </pci>
    </pci>
  </cpu>
</system>
```

rank 1 crashes and do not generate system.xml.

**Comment by sjeaugey** [comment]
I was trying to understand why we got this error :
```
paidist001:337652:337661 [0] graph/xml.h:221 NCCL WARN KV Convert to int : could not find value of '0x060000' in dictionary
```
Which would mean one of the PCI elements in the path of the GPU or NIC had a PCI class of 0x060000. But it doesn't show in the topology above. 
In any case, here is a patch to better handle that case :
[0001-Improve-robustness-of-PCI-detection.patch.txt](https://github.com/NVIDIA/nccl/files/4489819/0001-Improve-robustness-of-PCI-detection.patch.txt)

Rank 1 should not have generated an XML file since `NCCL_TOPO_DUMP_RANK_FILE` is 0 by default; if you want rank 1 to generate a file you'd need to set that environment variable to 1. What's really surprising in your topology file though is that line :
```
<gpu dev="0" sm="70" rank="1" gdr="0">
```
Note the `rank="1"`. This should be `rank="0"`. This also explains why later on, we fail to find the CPU affinity of the GPU since there is no GPU with rank 0.
So it seems rank 1 is reporting to other ranks using GPU with BusID `0000:4f:00.0`.

Could you set `NCCL_DEBUG_SUBSYS=GRAPH,INIT` so that I can confirm which CUDA device each rank is using ?

It looks like cudaDeviceGetPCIBusId would return the PCI Bus ID of the first GPU (`0000:4f:00.0`) inside the second container which only has GPU 1 (hence should be `0000:50:00.0`).

**Comment by 2sin18** [comment]
`NCCL_DEBUG_SUBSYS` had been set to `GRAPH,P2P,INIT` in the original test.(See “How to reproduce” section)

As mentioned before, If all devices are mounted in both containers and `CUDA_VISIBLE_DEVICES` is used to make each container use different GPU, it works. But this approach is apparently not acceptable.

In practice, NCCL, nvidia-docker and k8s(cubeflow) are used together. If NCCL needs more privileges to detect topology, I can open an issue in nvidia-docker too.

**Comment by sjeaugey** [comment]
I think the log above seems to be incomplete and missing one important INFO line, which is why I'm asking :
```
node:26367:26394 [1] NCCL INFO comm 0x560dfbbb3d00 rank 1 nranks 2 cudaDev 1 busId 6000 - Init COMPLETE
```
That line would tell me what busId each rank is reporting.

NCCL is supposed to work fine even when it cannot see the other GPUs (albeit slower). What happens here is a bug due to some data being inconsistent or incorrect, and I'm trying to understand whether it is a problem with NCCL, CUDA, the docker setup, or something else.

You can indeed try to force a manual topology file setting `NCCL_TOPO_FILE=system.xml` which would define the topology with all the GPUs.

**Comment by sjeaugey** [comment]
Actually nevermind, the line in question is the last one we print ... we obviously don't reach the end of `ncclCommInitRank`.

**Comment by sjeaugey** [comment]
OK indeed that was a bug in NCCL. Let me know if the patch below fixes it.
Sorry it took me a long time to setup the repro on my side.

```
diff --git a/src/graph/topo.cc b/src/graph/topo.cc
index 5cd8d4e..51e7f43 100644
--- a/src/graph/topo.cc
+++ b/src/graph/topo.cc
@@ -522,6 +522,7 @@ ncclResult_t ncclTopoGetSystem(struct ncclComm* comm, struct ncclTopoSystem** sy
       NCCLCHECK(int64ToBusId(comm->peerInfo[r].busId, busId));
       struct ncclXmlNode* node;
       NCCLCHECK(ncclTopoFillGpu(xml, busId, &node));
+      if (node == NULL) continue;
       NCCLCHECK(xmlSetAttrInt(node, "rank", r));
       NCCLCHECK(xmlInitAttrInt(node, "gdr", comm->peerInfo[r].gdrSupport));
     }
diff --git a/src/graph/xml.cc b/src/graph/xml.cc
index 550cfcd..f138d0b 100644
--- a/src/graph/xml.cc
+++ b/src/graph/xml.cc
@@ -569,7 +569,7 @@ ncclResult_t ncclTopoGetXmlFromGpu(struct ncclXmlNode* pciNode, nvmlDevice_t nvm
     NCCLCHECK(xmlSetAttrInt(gpuNode, "dev", dev));
   }
   NCCLCHECK(xmlGetAttrInt(gpuNode, "dev", &dev));
-  if (dev == -1) return ncclSuccess;
+  if (dev == -1) { *gpuNodeRet = NULL; return ncclSuccess; }
 
   NCCLCHECK(xmlGetAttrIndex(gpuNode, "sm", &index));
   if (index == -1) {
```

**Comment by 2sin18** [comment]
> OK indeed that was a bug in NCCL. Let me know if the patch below fixes it.
> Sorry it took me a long time to setup the repro on my side.
> 
> ```
> diff --git a/src/graph/topo.cc b/src/graph/topo.cc
> index 5cd8d4e..51e7f43 100644
> --- a/src/graph/topo.cc
> +++ b/src/graph/topo.cc
> @@ -522,6 +522,7 @@ ncclResult_t ncclTopoGetSystem(struct ncclComm* comm, struct ncclTopoSystem** sy
>        NCCLCHECK(int64ToBusId(comm->peerInfo[r].busId, busId));
>        struct ncclXmlNode* node;
>        NCCLCHECK(ncclTopoFillGpu(xml, busId, &node));
> +      if (node == NULL) continue;
>        NCCLCHECK(xmlSetAttrInt(node, "rank", r));
>        NCCLCHECK(xmlInitAttrInt(node, "gdr", comm->peerInfo[r].gdrSupport));
>      }
> diff --git a/src/graph/xml.cc b/src/graph/xml.cc
> index 550cfcd..f138d0b 100644
> --- a/src/graph/xml.cc
> +++ b/src/graph/xml.cc
> @@ -569,7 +569,7 @@ ncclResult_t ncclTopoGetXmlFromGpu(struct ncclXmlNode* pciNode, nvmlDevice_t nvm
>      NCCLCHECK(xmlSetAttrInt(gpuNode, "dev", dev));
>    }
>    NCCLCHECK(xmlGetAttrInt(gpuNode, "dev", &dev));
> -  if (dev == -1) return ncclSuccess;
> +  if (dev == -1) { *gpuNodeRet = NULL; return ncclSuccess; }
>  
>    NCCLCHECK(xmlGetAttrIndex(gpuNode, "sm", &index));
>    if (index == -1) {
> ```

Thanks, it works for nccl-tests case.  I will try the pytorch case later.

**Comment by tgaddair** [comment]
Hey @sjeaugey, is there a timeline for when this change will be available as part of a release (e.g., 2.6.5)?  We saw some promising results from NCCL 2.6.4, but cannot upgrade due to this issue.

**Comment by sjeaugey** [comment]
What kind of release are you looking for ? Creating a 2.6.5 commit on github and adding a "v2.6.5-1" tag could be done quickly (as we did for 2.5.7) but providing binaries on developer.nvidia.com would take more time.

**Comment by tgaddair** [comment]
Hey @sjeaugey, I was thinking prebuilt binaries, but not worries if that's a ways off.  I was just trying to decide whether to build from source or wait for new binaries, but sounds like we'll go with building from source for now.  Thanks!

**Comment by Clicksense** [comment]
> > OK indeed that was a bug in NCCL. Let me know if the patch below fixes it.
> > Sorry it took me a long time to setup the repro on my side.
> > ```
> > diff --git a/src/graph/topo.cc b/src/graph/topo.cc
> > index 5cd8d4e..51e7f43 100644
> > --- a/src/graph/topo.cc
> > +++ b/src/graph/topo.cc
> > @@ -522,6 +522,7 @@ ncclResult_t ncclTopoGetSystem(struct ncclComm* comm, struct ncclTopoSystem** sy
> >        NCCLCHECK(int64ToBusId(comm->peerInfo[r].busId, busId));
> >        struct ncclXmlNode* node;
> >        NCCLCHECK(ncclTopoFillGpu(xml, busId, &node));
> > +      if (node == NULL) continue;
> >        NCCLCHECK(xmlSetAttrInt(node, "rank", r));
> >        NCCLCHECK(xmlInitAttrInt(node, "gdr", comm->peerInfo[r].gdrSupport));
> >      }
> > diff --git a/src/graph/xml.cc b/src/graph/xml.cc
> > index 550cfcd..f138d0b 100644
> > --- a/src/graph/xml.cc
> > +++ b/src/graph/xml.cc
> > @@ -569,7 +569,7 @@ ncclResult_t ncclTopoGetXmlFromGpu(struct ncclXmlNode* pciNode, nvmlDevice_t nvm
> >      NCCLCHECK(xmlSetAttrInt(gpuNode, "dev", dev));
> >    }
> >    NCCLCHECK(xmlGetAttrInt(gpuNode, "dev", &dev));
> > -  if (dev == -1) return ncclSuccess;
> > +  if (dev == -1) { *gpuNodeRet = NULL; return ncclSuccess; }
> >  
> >    NCCLCHECK(xmlGetAttrIndex(gpuNode, "sm", &index));
> >    if (index == -1) {
> > ```
> 
> Thanks, it works for both nccl-tests case and pytorch case.
> 
> Below is the logs of the pytorch case:
> 
> ```shell
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/../max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:08.0/0000:4f:00.0/../max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/../max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/../max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/../max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:17/0000:17:00.0/0000:18:00.0/0000:19:0c.0/0000:50:00.0/../max_link_width, ignoring
> 
> paidist001:409513:409538 [0] misc/nvmlwrap.cc:144 NCCL WARN nvmlDeviceGetHandleByPciBusId() failed: Not Found 
> 
> paidist001:409513:409538 [0] graph/xml.cc:562 NCCL WARN No NVML, trying to use CUDA instead
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/../max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/0000:d9:04.0/0000:da:00.0/../max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/../max_link_speed, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/pci0000:d7/0000:d7:00.0/0000:d8:00.0/../max_link_width, ignoring
> paidist001:409513:409538 [0] NCCL INFO Topology detection : could not read /sys/devices/system/node/node-1/cpumap, ignoring
> paidist001:409513:409538 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
> paidist001:409513:409538 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
> paidist001:409513:409538 [0] NCCL INFO Attribute coll of node net not found
> paidist001:409513:409538 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
> paidist001:409513:409538 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
> paidist001:409513:409538 [0] NCCL INFO === System : maxWidth 3.1 ===
> paidist001:409513:409538 [0] NCCL INFO CPU/0 (1/1/2)
> paidist001:409513:409538 [0] NCCL INFO + PCI[12.0] - PCI/18000
> paidist001:409513:409538 [0] NCCL INFO               + PCI[12.0] - GPU/4F000 (0)
> paidist001:409513:409538 [0] NCCL INFO + SYS[9.0] - CPU/FFFFFFFFFFFFFFFF
> paidist001:409513:409538 [0] NCCL INFO CPU/FFFFFFFFFFFFFFFF (1/1/2)
> paidist001:409513:409538 [0] NCCL INFO + PCI[12.0] - PCI/D8000
> paidist001:409513:409538 [0] NCCL INFO               + PCI[12.0] - NIC/DA000
> paidist001:409513:409538 [0] NCCL INFO                             + NET[3.1] - NET/0 (6676a500039b0398/1/3.125000)
> paidist001:409513:409538 [0] NCCL INFO + SYS[9.0] - CPU/0
> paidist001:409513:409538 [0] NCCL INFO ==========================================
> paidist001:409513:409538 [0] NCCL INFO GPU/4F000 :GPU/4F000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) CPU/FFFFFFFFFFFFFFFF (3/9.000000/SYS) NET/0 (6/3.125000/SYS) 
> paidist001:409513:409538 [0] NCCL INFO NET/0 :GPU/4F000 (6/3.125000/SYS) CPU/0 (4/3.125000/SYS) CPU/FFFFFFFFFFFFFFFF (3/3.125000/PHB) NET/0 (0/5000.000000/LOC) 
> paidist001:409513:409538 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 3.000000/3.000000, type LOC/SYS, sameChannels 1
> paidist001:409513:409538 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
> paidist001:409513:409538 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 6.000000/3.000000, type LOC/SYS, sameChannels 1
> paidist001:409513:409538 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
> paidist001:409513:409538 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
> paidist001:409513:409538 [0] NCCL INFO NCCL_MAX_NRINGS set by environment to 12.
> paidist001:409513:409538 [0] NCCL INFO NCCL_MIN_NRINGS set by environment to 4.
> paidist001:409513:409538 [0] NCCL INFO Channel 00/04 :    0   1
> paidist001:409513:409538 [0] NCCL INFO Channel 01/04 :    0   1
> paidist001:409513:409538 [0] NCCL INFO Channel 02/04 :    0   1
> paidist001:409513:409538 [0] NCCL INFO Channel 03/04 :    0   1
> paidist001:409513:409538 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
> paidist001:409513:409538 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] -1/-1/-1->0->1|1->0->-1/-1/-1 [2] 1/-1/-1->0->-1|-1->0->1/-1/-1 [3] -1/-1/-1->0->1|1->0->-1/-1/-1
> paidist001:409513:409538 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff
> paidist001:409513:409538 [0] NCCL INFO Channel 00 : 0[4f000] -> 1[50000] via direct shared memory
> paidist001:409513:409538 [0] NCCL INFO Channel 01 : 0[4f000] -> 1[50000] via direct shared memory
> paidist001:409513:409538 [0] NCCL INFO Channel 02 : 0[4f000] -> 1[50000] via direct shared memory
> paidist001:409513:409538 [0] NCCL INFO Channel 03 : 0[4f000] -> 1[50000] via direct shared memory
> paidist001:409513:409538 [0] NCCL INFO 4 coll channels, 4 p2p channels, 1 p2p channels per peer
> 
> paidist001:409513:409538 [0] NCCL INFO comm 0x7fae98000dc0 rank 0 nranks 2 cudaDev 0 busId 4f000 - Init COMPLETE
> paidist001:409513:409513 [0] NCCL INFO Launch mode Parallel
> [2020-04-17 05:14:34,401] [INFO] [Epoch 0]	Accuracy: 100.00%	Loss: 0.00	Train Loss: 0.09	414.20 images/sec (0.155 secs/step)
> [2020-04-17 05:14:48,813] [INFO] [Epoch 1]	Accuracy: 100.00%	Loss: 0.00	Train Loss: 0.00	473.22 images/sec (0.135 secs/step)
> [2020-04-17 05:15:03,503] [INFO] [Epoch 2]	Accuracy: 100.00%	Loss: 0.00	Train Loss: 0.00	466.34 images/sec (0.137 secs/step)
> [2020-04-17 05:15:18,100] [INFO] [Epoch 3]	Accuracy: 100.00%	Loss: 0.00	Train Loss: 0.00	470.06 images/sec (0.136 secs/step)
> [2020-04-17 05:15:32,480] [INFO] [Epoch 4]	Accuracy: 100.00%	Loss: 0.00	Train Loss: 0.00	475.01 images/sec (0.135 secs/step)
> ```

As I understand and tried in my local server, this fix still don't enable P2P over NVLink through different containers? 
root@node1:/workspace/nccl-tests# NCCL_DEBUG=INFO NCCL_COMM_ID=192.168.99.1:29 WORLD_SIZE=2 RANK=1 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1
node1:37987:37987 [0] NCCL INFO Bootstrap : Using [0]docker0:192.168.99.1<0>
node1:37987:37987 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
node1:37987:37987 [0] NCCL INFO NET/IB : No device found.
node1:37987:37987 [0] NCCL INFO NET/Socket : Using [0]docker0:192.168.99.1<0>
node1:37987:37987 [0] NCCL INFO Using network Socket

node1:37987:38001 [0] misc/nvmlwrap.cc:144 NCCL WARN nvmlDeviceGetHandleByPciBusId() failed: Not Found

node1:37987:38001 [0] graph/xml.cc:562 NCCL WARN No NVML, trying to use CUDA instead
node1:37987:38001 [0] NCCL INFO Attribute coll of node net not found
node1:37987:38001 [0] NCCL INFO === System : maxWidth 1.2 ===
node1:37987:38001 [0] NCCL INFO CPU/0 (1/1/1)
node1:37987:38001 [0] NCCL INFO + PCI[5000.0] - NIC/0
node1:37987:38001 [0] NCCL INFO                 + NET[1.2] - NET/0 (0/0/1.250000)
node1:37987:38001 [0] NCCL INFO + PCI[12.0] - PCI/8000
node1:38067:38088 [0] NCCL INFO NET/0 :GPU/B000 (4/1.250000/PHB) CPU/0 (2/1.250000/PHB) NET/0 (0/5000.000000/LOC)
node1:38067:38088 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 1.200000/1.200000, type LOC/PHB, sameChannels 1
node1:38067:38088 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
node1:38067:38088 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 2.400000/1.200000, type LOC/PHB, sameChannels 1
node1:38067:38088 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
node1:38067:38088 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
node1:38067:38088 [0] NCCL INFO Channel 00/02 :    0   1
node1:38067:38088 [0] NCCL INFO Channel 01/02 :    0   1
node1:38067:38088 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
node1:38067:38088 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] -1/-1/-1->0->1|1->0->-1/-1/-1
node1:38067:38088 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
node1:38067:38088 [0] NCCL INFO Channel 00 : 0[b000] -> 1[a000] **via direct shared memory**
node1:38067:38088 [0] NCCL INFO Channel 01 : 0[b000] -> 1[a000] **via direct shared memory**
node1:38067:38088 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
node1:38067:38088 [0] NCCL INFO comm 0x7f5f98000dc0 rank 0 nranks 2 cudaDev 0 busId b000 - Init COMPLETE
#
#                                                     out-of-place                       in-place
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
node1:38067:38067 [0] NCCL INFO Launch mode Parallel
           8             2   float     sum     9.11    0.00    0.00  0e+00     9.00    0.00    0.00  0e+00
          16             4   float     sum     9.03    0.00    0.00  0e+00     8.95    0.00    0.00  0e+00
          32             8   float     sum     9.19    0.00    0.00  0e+00     9.05    0.00    0.00  0e+00
          64            16   float     sum     9.24    0.01    0.01  0e+00     9.24    0.01    0.01  0e+00
         128            32   float     sum     9.33    0.01    0.01  0e+00     9.31    0.01    0.01  0e+00
         256            64   float     sum     9.40    0.03    0.03  0e+00     9.33    0.03    0.03  0e+00
         512           128   float     sum     9.25    0.06    0.06  0e+00     9.41    0.05    0.05  0e+00
        1024           256   float     sum    11.28    0.09    0.09  0e+00     9.94    0.10    0.10  0e+00
        2048           512   float     sum    10.46    0.20    0.20  0e+00    10.48    0.20    0.20  0e+00
        4096          1024   float     sum    11.50    0.36    0.36  0e+00    11.74    0.35    0.35  0e+00
        8192          2048   float     sum    13.58    0.60    0.60  0e+00    13.36    0.61    0.61  0e+00
       16384          4096   float     sum    19.20    0.85    0.85  0e+00    18.94    0.87    0.87  0e+00
       32768          8192   float     sum    30.81    1.06    1.06  0e+00    30.68    1.07    1.07  0e+00
       65536         16384   float     sum    37.65    1.74    1.74  0e+00    36.72    1.78    1.78  0e+00
      131072         32768   float     sum    55.27    2.37    2.37  0e+00    55.31    2.37    2.37  0e+00
      262144         65536   float     sum    86.40    3.03    3.03  0e+00    86.02    3.05    3.05  0e+00
      524288        131072   float     sum    153.4    3.42    3.42  0e+00    152.1    3.45    3.45  0e+00
     1048576        262144   float     sum    289.1    3.63    3.63  0e+00    288.6    3.63    3.63  0e+00
     2097152        524288   float     sum    559.0    3.75    3.75  0e+00    559.2    3.75    3.75  0e+00
     4194304       1048576   float     sum   1109.7    3.78    3.78  0e+00   1112.9    3.77    3.77  0e+00
     8388608       2097152   float     sum   2230.9    3.76    3.76  0e+00   2230.9    3.76    3.76  0e+00
    16777216       4194304   float     sum   4622.8    3.63    3.63  0e+00   4847.5    3.46    3.46  0e+00
    33554432       8388608   float     sum   9051.1    3.71    3.71  0e+00   9178.4    3.66    3.66  0e+00
    67108864      16777216   float     sum    18361    3.66    3.66  0e+00    18508    3.63    3.63  0e+00
   134217728      33554432   float     sum    37210    3.61    3.61  0e+00    37056    3.62    3.62  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.73166
