### ISSUE TITLE
GDR Performance issue observed from v2.6.4-1 release

### ISSUE THREAD

**Issue by kehuanfeng** [NVIDIA/nccl#330]
I  am observing very big performance variance for GDR, from 6500 to 8500 imgs/sec with the following environemnts,

HW: 2 nodes with 8 GPUs for each and be connected via 25G Mellanox CX5.
NCCL: v2.6.4-1
TF: v2.0
Horovod:  0.19
cuDNN: v7.6.0
CUDA: v10.1
MPI: 4.0.0

The topology of GPUs and NIC can be found from log files.
[gdr_perf.zip](https://github.com/NVIDIA/nccl/files/4535333/gdr_perf.zip)
(log with surfix 'graph' means running mpi with '-x NCCL_DEBUG_SUBSYS=GRAPH') 
Here is complete command:
mpirun -np 16 -H host40:8,host37:8 --allow-run-as-root -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x NCCL_SOCKET_IFNAME=bond1 -x NCCL_NET_GDR_LEVEL=2 -x HOROVOD_MPI_THREADS_DISABLE=1 -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl_tcp_if_include bond1 -mca btl ^openib python /tensorflow/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet50 --batch_size 32 --use_fp16 --variable_update horovod --xla=True

With ring algo, the perf seems very stable (around 7000 imgs/sec).
With tree alog, the perf is either 6500 or 8500. 

Could you please look into the log and share us some insight regarding how to tune the performance?

**Comment by kwen2501** [comment]
Hi, did you observe similar issues with previous NCCL versions? If not, could you please try setting `NCCL_IB_AR_THRESHOLD=4194304` with NCCL 2.6.4 and see if the problem reproduces ? This setting will disable adaptive routing, which was added in NCCL 2.6.4.

**Comment by sjeaugey** [comment]
To look at trees and rings setting `NCCL_DEBUG_SUBSYS=GRAPH,TUNING` would help.

Also I'm noting you're using a NIC called `mlx5_bond_0`. I'm not sure what it is and what is bonded here (hopefully multiple ports of the same NIC), but it could interfere with the topology detection. Setting `NCCL_TOPO_DUMP_FILE=system.xml` (and posting the generated file) would also help us understand what is detected and spot differences.

**Comment by kehuanfeng** [comment]
> Hi, did you observe similar issues with previous NCCL versions? If not, could you please try setting `NCCL_IB_AR_THRESHOLD=4194304` with NCCL 2.6.4 and see if the problem reproduces ? This setting will disable adaptive routing, which was added in NCCL 2.6.4.
@kwen2501 Thanks for your comment. We didn't observe this issue for NCCL 2.4.7, with which we got around 6500 imgs/sec for tree algo consistently. 
After upgrading to 2.6.4, we are very surprised that it could achieve up to 8500.

And it still reproduced with disabling adaptive routing (as shown in attached log)
[disable_ar.log](https://github.com/NVIDIA/nccl/files/4543641/disable_ar.log)


BTW, the log contains output for 20 cycles, you can filter it through,
`cat disable_ar.log | grep "total images/sec"`

**Comment by kehuanfeng** [comment]
> To look at trees and rings setting `NCCL_DEBUG_SUBSYS=GRAPH,TUNING` would help.
> 
> Also I'm noting you're using a NIC called `mlx5_bond_0`. I'm not sure what it is and what is bonded here (hopefully multiple ports of the same NIC), but it could interfere with the topology detection. Setting `NCCL_TOPO_DUMP_FILE=system.xml` (and posting the generated file) would also help us understand what is detected and spot differences.

@sjeaugey Thanks for the comment. You are right, we are bonding two physical ports (each with 25G) of one NIC as single logical port, and they are working in round-robin mode. It's transparent to user space as only one IB dev is exposed, so I assume we don't need any ajustment from NCCL, right?

Attached the log file which dumps the graph info for 20 loops, including both 8500 case and 6500 case for tree algo. 

[system.xml.txt](https://github.com/NVIDIA/nccl/files/4543680/system.xml.txt)
[dump_graph_topo.log](https://github.com/NVIDIA/nccl/files/4543681/dump_graph_topo.log)

Additionally, does it make sense that ring algo is more deterministic and stable than tree algo?

**Comment by kehuanfeng** [comment]
BTW,  we could get stable bandwidth speed from OFED test suite (looping `ib_write_bw` for 100 times)，

`
************************************
* Waiting for client to connect... *
************************************
initializing CUDA
Listing all CUDA devices in system:
CUDA device 0: PCIe address is 1A:00
CUDA device 1: PCIe address is 1B:00
CUDA device 2: PCIe address is 3D:00
CUDA device 3: PCIe address is 3E:00
CUDA device 4: PCIe address is 88:00
CUDA device 5: PCIe address is 89:00
CUDA device 6: PCIe address is B1:00
CUDA device 7: PCIe address is B2:00

Picking device No. 2
[pid = 146152, dev = 2] device name = [Tesla V100-SXM2-32GB]
creating CUDA Ctx
making it the current CUDA Ctx
cuMemAlloc() of a 262144 bytes GPU buffer
allocated GPU buffer address at 00007fdce7a00000 pointer=0x7fdce7a00000
---------------------------------------------------------------------------------------
                    RDMA_Write BW Test
 Dual-port       : OFF          Device         : mlx5_bond_0
 Number of qps   : 2            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 PCIe relax order: ON
 CQ Moderation   : 1
 Mtu             : 1024[B]
 Link type       : Ethernet
 GID index       : 3
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x361b PSN 0x442e3a RKey 0x004016 VAddr 0x007fdce7a20000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:09:115:234:40
 local address: LID 0000 QPN 0x361c PSN 0xcf349c RKey 0x004016 VAddr 0x007fdce7a30000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:09:115:234:40
 remote address: LID 0000 QPN 0x2eee PSN 0x5a2afc RKey 0x185c34 VAddr 0x007fe1ada20000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:09:115:234:37
 remote address: LID 0000 QPN 0x2eef PSN 0x90926d RKey 0x185c34 VAddr 0x007fe1ada30000
 GID: 00:00:00:00:00:00:00:00:00:00:255:255:09:115:234:37
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[Gb/sec]    BW average[Gb/sec]   MsgRate[Mpps]
 65536      10000            46.29              46.28              0.088274
---------------------------------------------------------------------------------------
deallocating RX GPU buffer
destroying current CUDA Ctx
`

**Comment by sjeaugey** [comment]
Nothing seems bad in the NCCL logs, topology detection is working fine. I was not sure which PCI device a bonded interface would report, but it seems indeed the PCI path is correct and is the path to the NIC containing both interfaces. And the algorithms end up with the correct bandwidth modeling so ... all should be good.

I'm realizing I didn't see the output of the NCCL tests. That would be the first thing to try. We've seen unstable performance with RoCE in the past but that was one job getting variable performance over time. Here, it seems the performance is stable for each job. So it would be good to see if we can reproduce the bad/good performance with the NCCL tests and see how that translates to GB/s.

Another question I'm not sure was answered : were the good/bad runs on the same set of two nodes ?

**Comment by kehuanfeng** [comment]
Attached the output of NCCL tests for 50 loops.
[nccl-test-gdr.log](https://github.com/NVIDIA/nccl/files/4550838/nccl-test-gdr.log)
```
cat nccl-test-gdr.log | grep "Avg bus"
```
Seems like the average bw is floating around 4.7 GB/s, and it can reach up to 5.0 sometimes, although I am not sure whether it's a reasonble range.

```
root@kvm_9_115_234_40:/mnt/kehuan# cat nccl-test-gdr.log | grep "Avg bus" | awk '{sum+=$6} END {print sum/NR}'
4.78762
```
The total average bw among 50 cycles is 4.7 GB/s as shown above. Is it a good perf for 50 Gb/s (6.25GB/s) theoretical limit?  (about 75% efficiency)  

BTW, all the perf statistics we post were made on the same environment.

**Comment by sjeaugey** [comment]
It would be good to run with :
```
mpirun -np 16 -H 9.115.234.40:8,9.115.234.37:8 .. all_reduce_perf
```
instead of 
```
mpirun -np 2 -H 9.115.234.40:1,9.115.234.37:1 .. all_reduce_perf -g 8
```
as it would launch things exactly in the same way as horovod.

That said, performance seems quite stable. The only curious thing is the performance at 1M and 4M which oscillate between 2.6GB/s and 4.4 GB/s. I'm wondering if that could be caused by the interface bonding ... could you disable the bonding and see whether you still see variations in the training ?

The other reason I could see would be inconsistent scheduling between GPUs, causing desynchronization. That happens when on some GPUs NCCL is scheduled before some other workload, and on others it's scheduled after. Something like what is shown in #146, where one GPU arrives after the others in the collective call, so we pay twice the time of the blocks that are before some NCCL calls and after others.

**Comment by kehuanfeng** [comment]
We performed test in the same manner as horovd, please check the following log,
[nccl-test-gdr-np16.log](https://github.com/NVIDIA/nccl/files/4557860/nccl-test-gdr-np16.log)

Seems like the performance oscillate more fiercely, from 4.9 GB/s to 6.1 GB/s.

As to 'inconsistent scheduling between GPUs' you mentioned, I couldn't get what it really means. Is there any way we can avoid it?

**Comment by sjeaugey** [comment]
OK, I'm starting to understand what's happening. The topology detection reports an mlx5_bond_0 interface running at 3.125 GB/s, which is 25Gbps. And that was totally consistent with the tree perf, since the theoretical peak would be 5.4 GB/s. Except, that's a bonded interface with 2 ports, which means the speed should be twice that. I'm not sure whether there is a way to query that and multiply by the correct factor in the case of a bonded interface but the interface should actually be able to deliver 6.25 GB/s, which for the tree on two nodes, 16 GPUs means a peak of 10.9 GB/s. But that's just topology detection -- not super important.

Now about the real performance. On some runs, we are seeing up to 9 GB/s at 32 MB, then it goes down to 5.3. Others just increase progressively from 4.9 to 5.3. Can you set NCCL_ALGO=RING and see what speed you get. My bet would be that you're actually getting a clean 6 GB/s (which is why it's better than 5.3 (bad case with tree) and worse than 9 (good case with tree).

The conclusion is probably going to be that indeed we have a bonding issue : the bonding is not working well and you're only getting half the performance in some situations.

So another question : why use bonding at the IB verbs level ? NCCL is perfectly capable of using both interfaces to give you twice the bandwidth (reliably), and given all DL frameworks have checkpointing capability, even if one link failed you wouldn't loose much by stopping the job and restarting it (on a good set of nodes). Is there some other reason I'm missing ?

**Comment by sjeaugey** [comment]
Can you also run a few tests with the environment variables below (one at a time) and see how performance changes ? Please don't use them in production, this is just to better understand the performance issue.
```
NCCL_PROTO=LL128
```
```
NCCL_GDR_FLUSH_DISABLE=1
```

**Comment by kehuanfeng** [comment]
@sjeaugey sorry for the late reply due to Labor Day. 
Could you please elaborate regarding why the peak should be10.9 GB/s for 16 GPUs?  
"the interface should actually be able to deliver 6.25 GB/s, which for the tree on two nodes, 16 GPUs means a peak of 10.9 GB/s"

For ring perf, it achieves 5.6 GB/s finally for each round, which is indeed better than tree bad case (5.3 GB/s) and worse than tree good case (9 GB/s).
[nccl-test-gdr-np16-ring.log](https://github.com/NVIDIA/nccl/files/4573014/nccl-test-gdr-np16-ring.log)

Why bonding interface?
As I know, one reason is as you said, that to be the back up for each port. Another reason is we can use single IP to route them. I will check internally whether we can fall back to use seperate port if it's not a valid case for NCCL.

[nccl-test-gdr-np16-tree-flush.log](https://github.com/NVIDIA/nccl/files/4573024/nccl-test-gdr-np16-tree-flush.log)
[nccl-test-gdr-np16-tree-ll128.log](https://github.com/NVIDIA/nccl/files/4573025/nccl-test-gdr-np16-tree-ll128.log)

Attached another two logs for your reference. Let's know what you can conclude from them:)

**Comment by sjeaugey** [comment]
To perform an allreduce operation on nranks, we need to transmit 2*(nranks-1)*size. The tree algorithm, on two nodes, can balance traffic unevenly between NVLink and the network, so that there is more traffic on NVLink (2*size) and less on the network (1*size). On 3 nodes and more, trees will transmit 2*size on both NVLink and the network. Rings, on the other hand balance traffic evenly, so both NVLink and the network will transmit 2*(nranks-1)/nranks*size. The bus bandwidth reflects that "balanced case" : it takes the algorithm bandwidth and multiplies it by 2*(nranks-1)/nranks. So on tree/2 nodes/16 GPUs, you can get an algorithm BW of up to the network bandwidth; and the bus bw can therefore reach net bw*2*(nranks-1)/nranks = 6.25*14/8 = 10.93 GB/s. Granted the notion of bus bw is a bit hard to understand in the context of a tree algorithm.

About bonding, as far as I understand, it would not give you transparent fail over (it would require applications to be able to react to port change and re-establish connections). And I think you could still use IP bonding (for TCP/IP traffic) while using the two IB verbs interfaces (mlx5_x) independently.

Thanks for the extra runs. The LL128 protocol, as I suspected is giving good results. On good runs you get a consistent 9.9 GB/s all the way. But for some reason, the Simple protocol is never getting the full bandwidth (while on rings it works just fine).

We are creating 2 trees for each NIC. I think when we're lucky, each tree uses a different port, otherwise they use the same port. But I still don't see why LL128 would get better performance than Simple, nor why rings would be consistently getting the bandwidth of 2 ports while trees don't.

**Comment by kehuanfeng** [comment]
@sjeaugey Appriciated your follow-up with us. 
We can't give up bonding after careful discussion with internal team, so it can't be an option for us... Moreover, ib_write_bw test shows very stable bandwith for bonding case. 
Is there any approach for us to dig into the tree issue directly?  It's quite easy for us to reproduce it.

**Comment by sjeaugey** [comment]
ib_write_bw is only creating 2 queue pairs to the same destination, so that might be why each queue pair uses a different port.

That's also probably why rings work fine : one rank creates two queue pairs to receive from the same destination, and another rank creates two queue pairs to send to the same destination, so I guess the driver assigns each queue pair to a different port.

For trees, it's a bit more complicated. One rank is creating one queue pair to send and receive to a destination, and another rank is creating one queue pair to send and receive as well. Whether both ranks will end up using different ports might be harder to ensure. On more than two nodes, we can even have up to three queue pairs (one parent and two children), so how things will end up being mapped to port is even more complex.

That said, I'm wondering whether using the same GPU to send and receive all data (instead of splitting transfer on two) would make things more regular. Could you try the patch below ?

```
diff --git a/src/init.cc b/src/init.cc
index 2a9343a..54015fb 100644
--- a/src/init.cc
+++ b/src/init.cc
@@ -599,7 +599,7 @@ static ncclResult_t initTransportsRank(struct ncclComm* comm, ncclUniqueId* comm
 
   struct ncclTopoGraph treeGraph;
   treeGraph.id = 1;
-  treeGraph.pattern = NCCL_TOPO_PATTERN_SPLIT_TREE;
+  treeGraph.pattern = NCCL_TOPO_PATTERN_TREE;
   treeGraph.crossNic = ncclParamCrossNic();
   treeGraph.collNet = 0;
   treeGraph.minChannels = 1;
```

**Comment by kehuanfeng** [comment]
@sjeaugey We've tried the patch and it doesn't help it.
_"One rank is creating one queue pair to send and receive to a destination"_
We were told by our network guys that if one process uses one queue pair for commuinicataion, and anther process also uses one queue pair, then the same port will be using for both and driver can't split them. It's very like our situation as of now. 

Why can't we create two or more queue pairs for tree alog?

**Comment by kehuanfeng** [comment]
We monitored the status of queue pair on one node of them as shown below,
`
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 9 cq 10 qp 14 cm_id 0 mr 36 ctx 8 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 8 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0 
`
We were told that _pd_ means process, _cq_ meas completion queue, _qp_ means queue pair.
Before test, we saw one process with 2 queue pairs in background.
Once test gets started, we saw (8+1) processes with 14 queue pairs in background. 
We don't understand how to correlate 8 processes with 12 queue pairs?

And then we monitored the status of ring algo, same phenomenon observed, although higher performnce achieved.

Finally, we monitored the status of ib_write_bw, as shown below, which is very regular (one additional process comes up with two queue pairs).
`
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 1 
0: mlx5_0: pd 2 cq 2 qp 2 cm_id 0 mr 0 ctx 1 
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0 
`

**Comment by sjeaugey** [comment]
Changing the pattern to TREE, all queue pairs should be created by only one rank per node, and you should have 4 queue pairs (2 used to send, 2 used to receive). That's why I was hoping it would help.
Adding the RING queue pairs, you should see one rank with 2+4 queue pairs, and one process with 2 queue pairs (8 total on the node). Now you might also have queue pairs from MPI, so I would advice to disable Infiniband in MPI to avoid confusion.

I'm not sure what to understand from the logs though. On the ib_write_bw test, pd 1 is only using qp 2 and pd 2 is using qp 4 except once where it's using qp 2. How do we know which port it is using ?

**Comment by kehuanfeng** [comment]
There seems some misunderstanding here，

```
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0    // this is the status that ib_write_bw doesn't start
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 1 
0: mlx5_0: pd 2 cq 2 qp 2 cm_id 0 mr 0 ctx 1    // this is the status when ib_write_bw is getting started, so the total pd number (NOT pd index) becomes 2 while its qp is not showing up yet.
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1   // this is the stable status that test is undergoing.
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 2 cq 3 qp 4 cm_id 0 mr 1 ctx 1 
0: mlx5_0: pd 1 cq 2 qp 2 cm_id 0 mr 0 ctx 0   // quite test
```

**Comment by viig99** [comment]
I have a similar setup with 2 * 10gbps mellanox cards on a machine, which are bonded as per lacp mode 4, each machine has 3 V100-32gb, what finally worked for me to get the 20gbps speed was,
/usr/local/bin/mpirun --allow-run-as-root -np 6 -H N1PL-PA-GPU07:3,N1PL-PA-GPU08:3 \
    -x NCCL_NET_GDR_LEVEL=2 -x NCCL_DEBUG_SUBSYS=GRAPH,TUNING \
    -x NCCL_TOPO_DUMP_FILE=system.xml \
    -x NCCL_ALGO=Ring \
    -x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x NCCL_SOCKET_IFNAME=bond0 \
    -x LD_LIBRARY_PATH -x PATH \
    -x NCCL_IB_HCA=mlx5_bond_0 \
    -x NCCL_IB_GID_INDEX=3 \
    -x NCCL_MIN_NCHANNELS=4 \
    -x NCCL_MAX_NCHANNELS=8 \
   -x NCCL_SOCKET_NTHREADS=4 -x NCCL_NSOCKS_PERTHREAD=2 \
    -mca -bind-to none -map-by slot --display-map \
    -mca btl_tcp_if_include bond0 \
    -mca btl_tcp_links 1 \
    -mca pml ob1 \
    -mca btl ^openib \
    /root/wav2letter-dev/nccl-tests/build/all_reduce_perf -b 16M -e 1024M -f 4 -g 1

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
