### ISSUE TITLE
RuntimeError cuda runtime error (711) Data Parallel (PyTorch 1.5.0)

### ISSUE THREAD

**Issue by iKrishneel** [NVIDIA/nccl#337]
When using nn.DataParallel(model) there seems to be an error cuda runtime error (711). I tried to search what is 711 but I couldn’t figure out. I am assuming that this is not a PyTorch related but incase if anyone knows why this happens.

Without nn.DataParallel(model) the model trains without any issue.

Note I first opened this issue [here](https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-711-data-parallel/82170/6)

```bash
  prediction = self._model(images)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    res = scatter_map(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: cuda runtime error (711) : peer mapping resources exhausted at /opt/conda/conda-bld/pytorch_1587428398394/work/aten/src/THC/THCGeneral.cpp:136
```

Output for `nvidia-smi topo -m`

```bash
GPU0	GPU1	GPU2	CPU Affinity
GPU0	 X 	PHB	SYS	0-13,28-41
GPU1	PHB	 X 	SYS	0-13,28-41
GPU2	SYS	SYS	 X 	14-27,42-55

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks
```

Output for `p2pBandwidthLatencyTest`

```bash
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, GeForce GTX 1080 Ti, pciBusID: 3, pciDeviceID: 0, pciDomainID:0
Device: 1, GeForce GTX 1080 Ti, pciBusID: 4, pciDeviceID: 0, pciDomainID:0
Device: 2, GeForce GTX 1080 Ti, pciBusID: 81, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=0 CANNOT Access Peer Device=2
Device=1 CAN Access Peer Device=0
Device=1 CANNOT Access Peer Device=2
Device=2 CANNOT Access Peer Device=0
Device=2 CANNOT Access Peer Device=1

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1     2
     0	     1     1     0
     1	     1     1     0
     2	     0     0     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2
     0 377.42  11.55  11.45
     1  11.50 354.79  11.45
     2  11.38  11.41 355.11
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
Cuda failure p2pBandwidthLatencyTest.cu:185: 'peer mapping resources exhausted'
```

**Comment by sjeaugey** [comment]
Yes when disabling P2P, NCCL will communicate through shared memory so it will work.

Performance might be reduced ... or not. It really depends on the CPU and the rest of the workload. GPUs 0 and 1 are connected to the CPU directly so data has to go through the CPU anyway. Using shared memory can actually reach 11 GB/s, while P2P through the CPU is usually around ~9 GB/s. P2P however puts less pressure on the CPU memory which can be better if some other workload is using the CPU.

**Comment by iKrishneel** [comment]
@sjeaugey 
I tried `export NCCL_P2P_DISABLE =1` but the error mentioned still exists, unfortunately. 
I am wondering a clean system installation might help.

**Comment by sjeaugey** [comment]
Then it might be that the error is actually coming from PyTorch, not from NCCL. Actually NCCL is not used in scatter operations in PyTorch as far as I know. You should ask the PyTorch project how to disable P2P (or fix the issue).

[Note : I guess this is a typo but there should be no space between `NCCL_P2P_DISABLE` and `=1`]

**Comment by iKrishneel** [comment]
@sjeaugey 
Thanks for the update.

> [Note: I guess this is a typo but there should be no space between NCCL_P2P_DISABLE and =1]
Sorry, it was a typo.

By the way, I did a clean installation of the system, and thankfully everything is working as normal now. I can run parallel training. 

Output of the `./p2pBandwidthLatencyTest`
```bash
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, GeForce GTX 1080 Ti, pciBusID: 3, pciDeviceID: 0, pciDomainID:0
Device: 1, GeForce GTX 1080 Ti, pciBusID: 4, pciDeviceID: 0, pciDomainID:0
Device: 2, GeForce GTX 1080 Ti, pciBusID: 81, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=0 CANNOT Access Peer Device=2
Device=1 CAN Access Peer Device=0
Device=1 CANNOT Access Peer Device=2
Device=2 CANNOT Access Peer Device=0
Device=2 CANNOT Access Peer Device=1

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
     D\D     0     1     2
     0	     1     1     0
     1	     1     1     0
     2	     0     0     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2
     0 353.51  11.50  11.44
     1  11.43 354.79  11.43
     2  11.44  11.45 354.79
Unidirectional P2P=Enabled Bandwidth (P2P Writes) Matrix (GB/s)
   D\D     0      1      2
     0 355.11  10.41  11.41
     1  10.41 355.44  11.42
     2  11.35  11.35 355.44
Bidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2
     0 354.12  19.92  20.00
     1  20.07 356.03  19.94
     2  20.02  19.91 356.25
Bidirectional P2P=Enabled Bandwidth Matrix (GB/s)
   D\D     0      1      2
     0 354.48  20.27  19.98
     1  20.25 355.76  19.90
     2  20.05  19.88 355.28
P2P=Disabled Latency Matrix (us)
   GPU     0      1      2
     0   1.27  13.21  11.67
     1  12.35   1.24  12.25
     2  11.49  11.79   1.28

   CPU     0      1      2
     0   4.82  12.18  12.29
     1  11.92   4.79  12.04
     2   9.63   9.97   3.72
P2P=Enabled Latency (P2P Writes) Matrix (us)
   GPU     0      1      2
     0   1.25   0.97  12.14
     1   0.96   1.24  13.86
     2  10.98  10.99   1.17

   CPU     0      1      2
     0   3.74   2.70  10.45
     1   3.35   4.03  10.49
     2   9.55   9.51   3.74

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

Maybe this issue can be closed for now.

**Comment by sjeaugey** [comment]
Thanks for updating the issue. Feel free to close the issue if you think it's resolved.

**Comment by jasperhyp** [comment]
Just a side note, what solved my problem was using `CUDA_VISIBLE_DEVICES=XXX` prepended to the bash script running python, instead of using `os.environ['CUDA_VISIBLE_DEVICES']=XXX` within python script
