### ISSUE TITLE
cuda 11 support requested...

### ISSUE THREAD

**Issue by peijason** [NVIDIA/nccl#359]
**make** obtained warning as 

```console
/usr/bin/ld: warning: libcudart.so.10.0, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnccl.so, may conflict with libcudart.so.11.0
../build/alltoall.o: In function `AlltoAllRunColl(void*, void*, unsigned long, ncclDataType_t, ncclRedOp_t, int, ncclComm*, CUstream_st*)':
....../nccl-tests/src/alltoall.cu:74: undefined reference to `ncclRecv'
....../nccl-tests/src/alltoall.cu:73: undefined reference to `ncclSend'
collect2: error: ld returned 1 exit status
```

**Comment by sjeaugey** [comment]
What version of NCCL did you install on the system ? It seems you'd need to install NCCL 2.7 to have ncclSend and ncclRecv, and compiled against CUDA 11 to aoivd the issue about libcudart.so.10.0.

**Comment by peijason** [comment]
@sjeaugey 

Hi, @sjeaugey , I'm using git version, so it's the **NEWEST**. As you guessed, I've got both CUDA 10 and CUDA 11 installed on the server. Thank you very much, problem solved.
