### ISSUE TITLE
NCCL All reduce on M40

### ISSUE THREAD

**Issue by sharannarang** [NVIDIA/nccl#36]
Hello,

I tried running `test/single/all_reduce` test on M40 nodes and the test just hangs. The same test works fine on TitanX nodes. I'm running the test on 2 GPUs with cuda 7.5. The driver version for the TitanX node is 352.79. Here is the output from the TitanX nodes:

```
~/nccl$ ./build/test/single/all_reduce_test 100# Using devices
#   Rank  0 uses device  0 [0x04] GeForce GTX TITAN X
#   Rank  1 uses device  1 [0x05] GeForce GTX TITAN X

#                                                 out-of-place                    in-place
#      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
         100           100    char     sum    0.038   0.00   0.00    0e+00    0.046   0.00   0.00    0e+00
         100           100    char    prod    0.032   0.00   0.00    0e+00    0.046   0.00   0.00    0e+00
         100           100    char     max    0.032   0.00   0.00    0e+00    0.045   0.00   0.00    0e+00
         100           100    char     min    0.037   0.00   0.00    0e+00    0.044   0.00   0.00    0e+00
         100            25     int     sum    0.033   0.00   0.00    0e+00    0.045   0.00   0.00    0e+00
         100            25     int    prod    0.032   0.00   0.00    0e+00    0.044   0.00   0.00    0e+00
         100            25     int     max    0.032   0.00   0.00    0e+00    0.044   0.00   0.00    0e+00
         100            25     int     min    0.032   0.00   0.00    0e+00    0.043   0.00   0.00    0e+00
         100            50    half     sum    0.033   0.00   0.00    0e+00    0.044   0.00   0.00    0e+00
         100            50    half    prod    0.048   0.00   0.00    0e+00    0.069   0.00   0.00    0e+00
         100            50    half     max    0.035   0.00   0.00    0e+00    0.053   0.00   0.00    0e+00
         100            50    half     min    0.036   0.00   0.00    0e+00    0.048   0.00   0.00    0e+00
         100            25   float     sum    0.034   0.00   0.00    0e+00    0.052   0.00   0.00    0e+00
         100            25   float    prod    0.035   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
         100            25   float     max    0.035   0.00   0.00    0e+00    0.050   0.00   0.00    0e+00
         100            25   float     min    0.036   0.00   0.00    0e+00    0.050   0.00   0.00    0e+00
          96            12  double     sum    0.033   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12  double    prod    0.034   0.00   0.00    0e+00    0.050   0.00   0.00    0e+00
          96            12  double     max    0.033   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12  double     min    0.046   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12   int64     sum    0.034   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12   int64    prod    0.033   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12   int64     max    0.034   0.00   0.00    0e+00    0.052   0.00   0.00    0e+00
          96            12   int64     min    0.034   0.00   0.00    0e+00    0.048   0.00   0.00    0e+00
          96            12  uint64     sum    0.046   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12  uint64    prod    0.033   0.00   0.00    0e+00    0.049   0.00   0.00    0e+00
          96            12  uint64     max    0.034   0.00   0.00    0e+00    0.052   0.00   0.00    0e+00
          96            12  uint64     min    0.034   0.00   0.00    0e+00    0.053   0.00   0.00    0e+00
```

I tried running the same binary on M40 nodes with drivers 352.79 and 352.93. However, the test just stalls:

```
~/nccl$ ./build/test/single/all_reduce_test 100
# Using devices
#   Rank  0 uses device  0 [0x04] Tesla M40
#   Rank  1 uses device  1 [0x05] Tesla M40

#                                                 out-of-place                    in-place
#      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
```

Can you advice regarding this problem? Have you tried running these tests on M40s?

**Comment by nluehr** [comment]
What is the memory capacity of your M40s?
Also, please verify that ACS is disabled by running `Lspci –vvv | grep ACSCtl` (see issue #19).

**Comment by sharannarang** [comment]
M40s have memory of 24GB per gpu with 8 gpus in each node. ACS is disabled:

```
~$ sudo lspci -vvv | grep -i acsctl
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-
        ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-

**Comment by anthonyskim** [comment]
I had the same issue. YMMV, but replacing 8x M40 24GB with 8x M40 12GB resolved the issue in my case. Submitted a bug report to Nvidia on M40 24GB and driver, awaiting their feedback.

**Comment by sharannarang** [comment]
@anthonyskim , can you point me to the bug report that you created?

**Comment by nluehr** [comment]
This is a known issue for 24GB M40. A fixed driver (352.99) is in the pipeline with a planned release of 8/1.

**Comment by sharannarang** [comment]
Thanks @nluehr

**Comment by nluehr** [comment]
An updated driver has been posted. http://www.nvidia.com/download/driverResults.aspx/105665

**Comment by sharannarang** [comment]
Thanks, I see that the issue is fixed with the updated driver.
