### ISSUE TITLE
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled system error, NCCL version 2.4.8

### ISSUE THREAD

**Issue by bulingda** [NVIDIA/nccl#375]
I'm running this code：
```
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import time

import torch.nn.parallel
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
import torch.distributed as dist
import torch.utils.data
import torch.utils.data.distributed
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

# Training settings
parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                    help='input batch size for training (default: 64)')
parser.add_argument('--test-batch-size', type=int, default=1000, metavar='N',
                    help='input batch size for testing (default: 1000)')
parser.add_argument('--epochs', type=int, default=10, metavar='N',
                    help='number of epochs to train (default: 10)')
parser.add_argument('--lr', type=float, default=0.01, metavar='LR',
                    help='learning rate (default: 0.01)')
parser.add_argument('--momentum', type=float, default=0.5, metavar='M',
                    help='SGD momentum (default: 0.5)')
parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='disables CUDA training')
parser.add_argument('--seed', type=int, default=1, metavar='S',
                    help='random seed (default: 1)')
parser.add_argument('--log-interval', type=int, default=10, metavar='N',
                    help='how many batches to wait before logging training status')
args = parser.parse_args()
args.cuda = not args.no_cuda and torch.cuda.is_available()

# 初始化
dist.init_process_group(init_method='tcp://192.168.80.156:8080', backend="nccl", rank=0, world_size=2)

torch.manual_seed(args.seed)
if args.cuda:
    torch.cuda.manual_seed(args.seed)

train_dataset = datasets.MNIST('../data', train=True, download=True,
                               transform=transforms.Compose([
                                   transforms.ToTensor(),
                                   transforms.Normalize((0.1307,), (0.3081,))
                               ]))
# 分发数据
train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)

kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])),
    batch_size=args.test_batch_size, shuffle=True, **kwargs)


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x)


model = Net()
if args.cuda:
    # 分发模型
    model.cuda()
    model = torch.nn.parallel.DistributedDataParallel(model)
    # model = torch.nn.DataParallel(model,device_ids=[0,1,2,3]).cuda()
    # model.cuda()

optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)


def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data), Variable(target)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset), 100. * batch_idx / len(train_loader), loss.data[0]))


def tes():
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data, volatile=True), Variable(target)
        output = model(data)
        test_loss += F.nll_loss(output, target, size_average=False).data[0]  # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1]  # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()

    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))


if __name__ == '__main__':
    tot_time = 0

    for epoch in range(1, args.epochs + 1):
        # 设置epoch位置，这应该是个为了同步所做的工作
        train_sampler.set_epoch(epoch)
        start_cpu_secs = time.time()
        # long running
        train(epoch)
        end_cpu_secs = time.time()
        print("Epoch {} of {} took {:.3f}s".format(
            epoch, args.epochs, end_cpu_secs - start_cpu_secs))
        tot_time += end_cpu_secs - start_cpu_secs
        tes()

    print("Total time= {:.3f}s".format(tot_time))
```
in centos7，cuda10.2，nccl2.7.8，pytorch1.5.1。
The following problems were encountered：
```
localhost:3353:3353 [0] NCCL INFO Bootstrap : Using [0]enp2s0:192.168.80.156<0>
localhost:3353:3353 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
localhost:3353:3353 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
localhost:3353:3353 [0] NCCL INFO NET/Socket : Using [0]enp2s0:192.168.80.156<0>
NCCL version 2.4.8+cuda10.2
localhost:3353:3417 [0] NCCL INFO Setting affinity for GPU 0 to ffff

localhost:3353:3416 [0] include/socket.h:390 NCCL WARN Connect to 192.168.80.157<43460> failed : No route to host
localhost:3353:3416 [0] NCCL INFO bootstrap.cc:100 -> 2
localhost:3353:3416 [0] NCCL INFO bootstrap.cc:226 -> 2

localhost:3353:3417 [0] include/socket.h:390 NCCL WARN Connect to 192.168.80.157<42491> failed : No route to host
localhost:3353:3417 [0] NCCL INFO bootstrap.cc:100 -> 2
localhost:3353:3417 [0] NCCL INFO bootstrap.cc:337 -> 2
localhost:3353:3417 [0] NCCL INFO init.cc:695 -> 2
localhost:3353:3417 [0] NCCL INFO init.cc:951 -> 2
localhost:3353:3417 [0] NCCL INFO misc/group.cc:69 -> 2 [Async thread]
Traceback (most recent call last):
  File "test_dataparallel.py", line 87, in <module>
    model = torch.nn.parallel.DistributedDataParallel(model)
  File "/usr/local/anaconda/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 285, in __init__
    self.broadcast_bucket_size)
  File "/usr/local/anaconda/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 496, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled system error, NCCL version 2.4.8
```
Have you met the same problem and solved it?

**Comment by bulingda** [comment]
Sorry, there is something wrong with this format. Please contact me if you don't understand.

**Comment by sjeaugey** [comment]
[I fixed the formatting. For large portions of code you can use triple backquotes (```) before and after formatted code. ]

It seems you are running on two nodes, one has IP address 192.168.80.156 and the other is 192.168.80.157. But it seems the two nodes can't talk to each other. You should first make sure that you can ping 192.168.80.157 from the first node.

Also the first node has a hostname set to "localhost". This can be a cause of errors later on if both nodes are called "localhost" because processes on different nodes might end up assuming they are on the same node and try to communicate through CUDA P2P or shared memory.

**Comment by bulingda** [comment]
> [I fixed the formatting. For large portions of code you can use triple backquotes (```) before and after formatted code. ]
> 
> It seems you are running on two nodes, one has IP address 192.168.80.156 and the other is 192.168.80.157. But it seems the two nodes can't talk to each other. You should first make sure that you can ping 192.168.80.157 from the first node.
> 
> Also the first node has a hostname set to "localhost". This can be a cause of errors later on if both nodes are called "localhost" because processes on different nodes might end up assuming they are on the same node and try to communicate through CUDA P2P or shared memory.

1.Two nodes can ping each other
2.I tried to change the hostname of a machine, and the first time it worked. However, the problem arose when I restarted both servers and changed the hostnames again.
Do you have any other methods?

**Comment by bulingda** [comment]
> If ping works, then it could be that you have a firewall blocking connections between the hosts. One way to check that is to use netcat.
> 
> On `192.168.80.157`, run :
> 
> ```
> nc -l 12345
> ```
> 
> Then in a different terminal, on `192.168.80.156`, run :
> 
> ```
> nc 192.168.80.157 12345
> ```
> 
> If it connects, what you type on one side should appear on the other side and vice versa.

Thanks for you.

**Comment by JerryDaHeLian** [comment]
你的方法好使了。非常感谢！
总结起来，通过Lightning run on预训练时要在命令行里加上：
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 NCCL_DEBUG=info lightning run mode...
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 指定网卡名（带有有效ip地址的）
NCCL_DEBUG=info 给出较为详细的debug信息，用于出错分析。

**Comment by JerryDaHeLian** [comment]
你的方法好使了。非常感谢！
首先关闭防火墙。（设置规则我没太弄明白，直接暴力方式，关闭了防火墙。安全起见，最好是设置防火墙规则）
总结起来，通过Lightning run on预训练时要在命令行里加上：
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 NCCL_DEBUG=info lightning run mode...
NCCL_SOCKET_IFNAME=enx0826ae3dd6c5 指定网卡名（带有有效ip地址的）
NCCL_DEBUG=info 给出较为详细的debug信息，用于出错分析。
