### ISSUE TITLE
nccl v2.7.6 slow down 30% than nccl v2.5.7 when run tf_cnn_benchmarks.py  vgg16 models on 8*v100  4nodes. 

### ISSUE THREAD

**Issue by qianzhang613** [NVIDIA/nccl#378]
when run the  tf_cnn_benchmarks.py: https://github.com/tensorflow/benchmarks/tree/cnn_tf_v1.15_compatible/scripts/tf_cnn_benchmarks with cmd:
```
 python3 -u tf_cnn_benchmarks.py --nodistortions --gradient_repacking=8 --data_format=NCHW --num_gpus=1 --batch_size=64 --model=vgg16 --variable_update=horovod --num_epochs=10
```
on the 8xV100 with nvlink and 100GB rmda ,  the nccl v2.7.6  speed is` images/sec 160` whereas the v2.5.7 is ` images/sec 232` 

the rank  log of `nccl 2.5.7` with `  - "NCCL_DEBUG=INFO" NCCL_DEBUG_SUBSYS=INIT ` :
```
  [0] NCCL INFO Bootstrap : Using [0]eth1:192.168.1.1<0>
  [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
  [0] NCCL INFO NET/IB : Using [0]mlx5_3:1/RoCE ; OOB eth1:9.206.36.72<0>
NCCL version 2.5.7+cuda10.0
  [0] NCCL INFO Setting affinity for GPU 0 to 03,ffff0000,0003ffff
  [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
  [0] NCCL INFO NCCL_IB_SL set by environment to 3.
  [0] NCCL INFO NCCL_SHM_DISABLE set by environment to 0.
  [0] NCCL INFO Channel 00/02 :    0   1   6   7   5   4   3  10   8   9  13  12  14  15  11  18  16  17  21  20
  [0] NCCL INFO Channel 01/02 :    0   1   6   7   5   4   3  10   8   9  13  12  14  15  11  18  16  17  21  20
  [0] NCCL INFO Threads per block : 512/640/512
  [0] NCCL INFO threadThresholds 8/8/64 | 256/8/64
  [0] NCCL INFO Trees [0] -1/-1/-1->0->7|7->0->-1/-1/-1 [1] -1/-1/-1->0->7|7->0->-1/-1/-1
  [0] NCCL INFO Ring 00 : 0[1a000] -> 1[1b000] via P2P/IPC
  [0] NCCL INFO Ring 00 : 0[1a000] -> 7[b2000] via P2P/IPC
  [0] NCCL INFO Ring 01 : 0[1a000] -> 1[1b000] via P2P/IPC
  [0] NCCL INFO Ring 01 : 0[1a000] -> 7[b2000] via P2P/IPC
  [0] NCCL INFO comm 0x7f6262eaf070 rank 0 nranks 32 cudaDev 0 busId 1a000 - Init COMPLETE
  [0] NCCL INFO Launch mode Parallel
```

the rank0 log of `nccl 2.7.6` with  `  - "NCCL_DEBUG=INFO" NCCL_DEBUG_SUBSYS=INIT ` :
```
 [0] NCCL INFO Bootstrap : Using [0]eth1:192.168.1.1<0>
  [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
  [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE ; OOB eth1:9.91.68.172<0>
  [0] NCCL INFO Using network IB
NCCL version 2.7.6+cuda10.0
  [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
  [0] NCCL INFO NCCL_IB_SL set by environment to 3.
  [0] NCCL INFO NCCL_SHM_DISABLE set by environment to 0.
  [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PXB
  [0] NCCL INFO Channel 00/04 :    0   1   3   7   5   4   6   2   8   9  11  15  13  12  14  10  16  17  19  23
  [0] NCCL INFO Channel 01/04 :    0   3   2   6   4   7   5   1   8  11  10  14  12  15  13   9  16  19  18  22
  [0] NCCL INFO Channel 02/04 :    0   1   3   7   5   4   6   2   8   9  11  15  13  12  14  10  16  17  19  23
  [0] NCCL INFO Channel 03/04 :    0   3   2   6   4   7   5   1   8  11  10  14  12  15  13   9  16  19  18  22
  [0] NCCL INFO NCCL_COLLNET_ENABLE set by environment to 0.
  [0] NCCL INFO threadThresholds 8/8/64 | 256/8/64 | 8/8/64
  [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 2/-1/-1->0->-1|-1->0->2/-1/-1 [2] 1/-1/-1->0->25|25->0->1/-1/-1 [3] 2/-1/-1->0->26|26->0->2/-1/-1
  [0] NCCL INFO Setting affinity for GPU 0 to 03,ffff0000,0003ffff
  [0] NCCL INFO Channel 00 : 26[5b000] -> 0[2d000] [receive] via NET/IB/0
  [0] NCCL INFO Channel 00 : 0[2d000] -> 1[32000] via P2P/IPC
  [0] NCCL INFO Channel 01 : 25[32000] -> 0[2d000] [receive] via NET/IB/0
  [0] NCCL INFO Channel 01 : 0[2d000] -> 3[5f000] via P2P/IPC
  [0] NCCL INFO Channel 01 : 0[2d000] -> 2[5b000] via P2P/IPC
  [0] NCCL INFO Channel 02 : 26[5b000] -> 0[2d000] [receive] via NET/IB/0
  [0] NCCL INFO Channel 02 : 0[2d000] -> 1[32000] via P2P/IPC
  [0] NCCL INFO NCCL_NET_GDR_READ set by environment to 1.
  [0] NCCL INFO Channel 02 : 0[2d000] -> 25[32000] [send] via NET/IB/0
  [0] NCCL INFO Channel 02 : 25[32000] -> 0[2d000] [receive] via NET/IB/0
  [0] NCCL INFO Channel 03 : 25[32000] -> 0[2d000] [receive] via NET/IB/0
  [0] NCCL INFO Channel 03 : 0[2d000] -> 3[5f000] via P2P/IPC
  [0] NCCL INFO Channel 03 : 0[2d000] -> 26[5b000] [send] via NET/IB/0
  [0] NCCL INFO Channel 03 : 26[5b000] -> 0[2d000] [receive] via NET/IB/0
  [0] NCCL INFO Channel 03 : 0[2d000] -> 2[5b000] via P2P/IPC
  [0] NCCL INFO 4 coll channels, 4 p2p channels, 1 p2p channels per peer
  [0] NCCL INFO comm 0x7f56b75a2680 rank 0 nranks 32 cudaDev 0 busId 2d000 - Init COMPLETE
  [0] NCCL INFO Launch mode Parallel
```

**Comment by sjeaugey** [comment]
Would you be able to run the NCCL tests on each version and compare the performance you get ? Then can you try again with 2.7.6 setting NCCL_MAX_NCHANNELS=2 ?

Also, could you could dump the topology with NCCL_TOPO_DUMP_FILE=system.xml (with 2.7.6) and send us the file ? It seems 2.7.6 is creating 2 rings/4 channels (while 2.5.6 was only creating 1 ring/2 channels) so I'd like to understand the reason for that.

**Comment by qianzhang613** [comment]
i had try 2.7.6 setting NCCL_MAX_NCHANNELS=2 , it take **no effects.**
i also try `  - NCCL_ALGO=Tree,Ring,^Collnet` or ` - NCCL_COLLNET_ENABLE=0 /1` or `  - NCCL_P2P_LEVEL=NVL`  these setting both make any effect. 

the topo.xml is:
```
<system version="1">
  <cpu numaid="0" affinity="000000ff,ffff0000,00ffffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:18:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:1a:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="0" sm="70" rank="0" gdr="1">
          <nvlink target="0000:1b:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:3e:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:3d:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:1b:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="1" sm="70" rank="1" gdr="1">
          <nvlink target="0000:3e:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:3d:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:1a:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:b1:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
    <pci busid="0000:3b:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:3d:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="2" sm="70" rank="2" gdr="1">
          <nvlink target="0000:89:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:1b:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:1a:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:3e:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:3e:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="3" sm="70" rank="3" gdr="1">
          <nvlink target="0000:3d:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:1b:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:1a:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:88:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
    <nic>
      <net name="mlx5_2" dev="0" speed="100000" port="1" guid="0xc8a0d900039f59b8" maxconn="262144" gdr="1"/>
    </nic>
  </cpu>
  <cpu numaid="1" affinity="ffffff00,0000ffff,ff000000" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:86:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:88:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="4" sm="70" rank="4" gdr="1">
          <nvlink target="0000:89:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:3e:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:b1:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:89:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="5" sm="70" rank="5" gdr="1">
          <nvlink target="0000:b2:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:b1:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:88:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:3d:00.0" count="1" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
    <pci busid="0000:af:00.0" class="0x060400" link_speed="8 GT/s" link_width="16">
      <pci busid="0000:b1:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="6" sm="70" rank="6" gdr="1">
          <nvlink target="0000:89:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:b2:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:88:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:1b:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
      <pci busid="0000:b2:00.0" class="0x030200" link_speed="8 GT/s" link_width="16">
        <gpu dev="7" sm="70" rank="7" gdr="1">
          <nvlink target="0000:b1:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:89:00.0" count="2" tclass="0x030200"/>
          <nvlink target="0000:88:00.0" count="1" tclass="0x030200"/>
          <nvlink target="0000:1a:00.0" count="2" tclass="0x030200"/>
        </gpu>
      </pci>
    </pci>
  </cpu>
</system>
```

**Comment by qianzhang613** [comment]
@sjeaugey  And The speed  is no different  between 257 and 276 when run one node.

**Comment by sjeaugey** [comment]
@qianzhang613 the most important is to run the NCCL tests (https://github.com/nvidia/nccl-tests) to figure out what is the performance you are getting.

My suspicion is that the RoCE performance drops, but I'd like to see by how much.

**Comment by kwen2501** [comment]
From the logs, it seems the 2.5.7 run was on mlx5_3, while the 2.7.6 run was on mlx5_2. Is there any difference between the two networks?

**Comment by qianzhang613** [comment]
> From the logs, it seems the 2.5.7 run was on mlx5_3, while the 2.7.6 run was on mlx5_2. Is there any difference between the two networks?

because this tests run in dockers,  we random map one VF into dockers. so there is no different with diff mlx5_*;

the nccl 257 with `mpirun -np 32 -H xxx   .... /nv-tools/all_reduce_perf -g 1 -t 1`:
```
launcher [0] NCCL INFO Bootstrap : Using [0]eth1:9.91.6.225<0>
launcher [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
launcher [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE ; OOB eth1:9.91.6.225<0>
NCCL version 2.5.7+cuda10.0
launcher [0] NCCL INFO Setting affinity for GPU 0 to 03,ffff0000,0003ffff
launcher [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
launcher [0] NCCL INFO NCCL_IB_SL set by environment to 3.
launcher [0] NCCL INFO NCCL_SHM_DISABLE set by environment to 0.
launcher [0] NCCL INFO Channel 00/02 :    0   1   6   7   5   4   3  10   8   9  14  15  13  12  11  18  16  17  22  23
launcher [0] NCCL INFO Channel 01/02 :    0   1   6   7   5   4   3  10   8   9  14  15  13  12  11  18  16  17  22  23
launcher [0] NCCL INFO Threads per block : 512/640/512
launcher [0] NCCL INFO threadThresholds 8/8/64 | 256/8/64
launcher [0] NCCL INFO Trees [0] -1/-1/-1->0->7|7->0->-1/-1/-1 [1] -1/-1/-1->0->7|7->0->-1/-1/-1
launcher [0] NCCL INFO Ring 00 : 0[1a000] -> 1[1b000] via P2P/IPC
launcher [0] NCCL INFO Ring 00 : 0[1a000] -> 7[b2000] via P2P/IPC
launcher [0] NCCL INFO Ring 01 : 0[1a000] -> 1[1b000] via P2P/IPC
launcher [0] NCCL INFO Ring 01 : 0[1a000] -> 7[b2000] via P2P/IPC
launcher [0] NCCL INFO comm 0x7fbc6c001cf0 rank 0 nranks 32 cudaDev 0 busId 1a000 - Init COMPLETE
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
launcher [0] NCCL INFO Launch mode Parallel
    33554432       8388608   float     sum   6301.7    5.32   10.32  1e-06   6178.3    5.43   10.52  1e-06
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 10.4196 
```

the nccl 257 with `mpirun -np 32 -H xxx   .... /nv-tools/all_reduce_perf -g 1 -t 1`:
```
launcher [0] NCCL INFO Bootstrap : Using [0]eth1:9.91.10.189<0>
launcher [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
launcher [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE ; OOB eth1:9.91.10.189<0>
launcher [0] NCCL INFO Using network IB
NCCL version 2.7.6+cuda10.0
launcher [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
launcher [0] NCCL INFO NCCL_IB_SL set by environment to 3.
launcher [0] NCCL INFO NCCL_SHM_DISABLE set by environment to 0.
launcher [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to PXB
launcher [0] NCCL INFO Channel 00/04 :    0   2   3   4   5   7   6   1   8  10  11  12  13  15  14   9  16  18  19  20
launcher [0] NCCL INFO Channel 01/04 :    0   2   1   6   7   5   4   3   8  10   9  14  15  13  12  11  16  18  17  22
launcher [0] NCCL INFO Channel 02/04 :    0   2   3   4   5   7   6   1   8  10  11  12  13  15  14   9  16  18  19  20
launcher [0] NCCL INFO Channel 03/04 :    0   2   1   6   7   5   4   3   8  10   9  14  15  13  12  11  16  18  17  22
launcher [0] NCCL INFO threadThresholds 8/8/64 | 256/8/64 | 8/8/64
launcher [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 2/-1/-1->0->-1|-1->0->2/-1/-1 [2] 1/-1/-1->0->25|25->0->1/-1/-1 [3] 2/-1/-1->0->26|26->0->2/-1/-1
launcher [0] NCCL INFO Setting affinity for GPU 0 to 03,ffff0000,0003ffff
launcher [0] NCCL INFO Channel 00 : 25[1b000] -> 0[1a000] [receive] via NET/IB/0
launcher [0] NCCL INFO Channel 00 : 0[1a000] -> 2[3d000] via P2P/IPC
launcher [0] NCCL INFO Channel 00 : 0[1a000] -> 1[1b000] via P2P/IPC
launcher [0] NCCL INFO Channel 01 : 27[3e000] -> 0[1a000] [receive] via NET/IB/0
launcher [0] NCCL INFO Channel 01 : 0[1a000] -> 2[3d000] via P2P/IPC
launcher [0] NCCL INFO Channel 02 : 25[1b000] -> 0[1a000] [receive] via NET/IB/0
launcher [0] NCCL INFO Channel 02 : 0[1a000] -> 2[3d000] via P2P/IPC
launcher [0] NCCL INFO NCCL_NET_GDR_READ set by environment to 1.
launcher [0] NCCL INFO Channel 02 : 0[1a000] -> 25[1b000] [send] via NET/IB/0
launcher [0] NCCL INFO Channel 02 : 0[1a000] -> 1[1b000] via P2P/IPC
launcher [0] NCCL INFO Channel 03 : 27[3e000] -> 0[1a000] [receive] via NET/IB/0
launcher [0] NCCL INFO Channel 03 : 0[1a000] -> 2[3d000] via P2P/IPC
launcher [0] NCCL INFO Channel 03 : 0[1a000] -> 26[3d000] [send] via NET/IB/0
launcher [0] NCCL INFO Channel 03 : 26[3d000] -> 0[1a000] [receive] via NET/IB/0
launcher [0] NCCL INFO 4 coll channels, 4 p2p channels, 1 p2p channels per peer
launcher [0] NCCL INFO comm 0x7f3294000dc0 rank 0 nranks 32 cudaDev 0 busId 1a000 - Init COMPLETE
#
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
launcher [0] NCCL INFO Launch mode Parallel
    33554432       8388608   float     sum    71937    0.47    0.90  1e-06    26895    1.25    2.42  1e-06
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.66051 
```

**Comment by sjeaugey** [comment]
Could you run again with `all_reduce_perf -b 8 -e 128M -f 2` ?

It looks like a RoCE perf issue, similar to this other issue : https://github.com/NVIDIA/nccl/issues/306#issuecomment-604389359

Given we didn't change the RoCE code between 2.5 and 2.6+, my only guess is that the timing changed, which caused performance to drop. The problem is that RoCE configuration is kind of an art, and it is vendor dependent. What type of Ethernet NICs/switch are you using ? I'm assuming the NICs are Mellanox, but I can't guess what the switch is.

**Comment by qianzhang613** [comment]
@sjeaugey the NICs is Mellanox Technologies ConnectX-4 Stand-up dual-port 100GbE MCX416A-CCAT. 

the run command:
```
export CUDA_DEVICE_ORDER=PCI_BUS_ID  NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT NCCL_IB_GID_INDEX=3 NCCL_IB_SL=3 NCCL_NET_GDR_LEVEL=2 NCCL_NET_GDR_READ=1 NCCL_SHM_DISABLE=0 NCCL_SOCKET_IFNAME=eth1
mpirun --allow-run-as-root --tag-output -np 32 -H xxx -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib   -x CUDA_DEVICE_ORDER -x NCCL_DEBUG -x NCCL_DEBUG_SUBSYS -x NCCL_IB_GID_INDEX -x NCCL_IB_SL -x NCCL_NET_GDR_LEVEL -x NCCL_NET_GDR_READ -x NCCL_SHM_DISABLE -x NCCL_SOCKET_IFNAME /nv-tools/all_reduce_perf -b 8 -e 128M -f 2 -g 1 -t 1
```
the result of nccl 257:
```
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
ts-ea044b3b39be4d44bac033a754420de5-launcher:2360:2360 [0] NCCL INFO Launch mode Parallel
           8             2   float     sum    77.80    0.00    0.00  2e-07    75.02    0.00    0.00  2e-07
          16             4   float     sum    75.73    0.00    0.00  2e-07    73.17    0.00    0.00  2e-07
          32             8   float     sum    72.69    0.00    0.00  2e-07    72.67    0.00    0.00  4e-07
          64            16   float     sum    82.66    0.00    0.00  4e-07    73.57    0.00    0.00  4e-07
         128            32   float     sum    84.67    0.00    0.00  4e-07    75.95    0.00    0.00  4e-07
         256            64   float     sum    78.64    0.00    0.01  4e-07    76.19    0.00    0.01  4e-07
         512           128   float     sum    79.56    0.01    0.01  4e-07    79.19    0.01    0.01  2e-07
        1024           256   float     sum    85.43    0.01    0.02  7e-07    81.21    0.01    0.02  7e-07
        2048           512   float     sum    84.83    0.02    0.05  7e-07    85.87    0.02    0.05  7e-07
        4096          1024   float     sum    93.56    0.04    0.08  7e-07    90.00    0.05    0.09  7e-07
        8192          2048   float     sum    99.50    0.08    0.16  7e-07    96.11    0.09    0.17  7e-07
       16384          4096   float     sum    113.6    0.14    0.28  7e-07    108.8    0.15    0.29  7e-07
       32768          8192   float     sum    134.2    0.24    0.47  7e-07    129.1    0.25    0.49  7e-07
       65536         16384   float     sum    166.0    0.39    0.76  7e-07    161.1    0.41    0.79  7e-07
      131072         32768   float     sum    180.2    0.73    1.41  7e-07    177.8    0.74    1.43  7e-07
      262144         65536   float     sum    216.8    1.21    2.34  7e-07    217.4    1.21    2.34  7e-07
      524288        131072   float     sum    481.5    1.09    2.11  1e-06    488.3    1.07    2.08  1e-06
     1048576        262144   float     sum    576.7    1.82    3.52  1e-06    570.9    1.84    3.56  1e-06
     2097152        524288   float     sum    677.1    3.10    6.00  1e-06    672.3    3.12    6.04  1e-06
     4194304       1048576   float     sum    953.2    4.40    8.53  1e-06    948.5    4.42    8.57  1e-06
     8388608       2097152   float     sum   1677.2    5.00    9.69  1e-06   1659.5    5.05    9.79  1e-06
    16777216       4194304   float     sum   3159.4    5.31   10.29  1e-06   3168.9    5.29   10.26  1e-06
    33554432       8388608   float     sum   6229.0    5.39   10.44  1e-06   6218.4    5.40   10.45  1e-06
    67108864      16777216   float     sum    11918    5.63   10.91  1e-06    11912    5.63   10.92  1e-06
   134217728      33554432   float     sum    23263    5.77   11.18  1e-06    23271    5.77   11.17  1e-06
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 3.13608 
```

the result of nccl 276:
```
#                                                     out-of-place                       in-place          
#       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
ts-ae8e84c3bb3f436793dcf1c7833c7c07-launcher:2696:2696 [0] NCCL INFO Launch mode Parallel
           8             2   float     sum    77.39    0.00    0.00  2e-07    76.96    0.00    0.00  2e-07
          16             4   float     sum    75.88    0.00    0.00  2e-07    75.97    0.00    0.00  2e-07
          32             8   float     sum    78.02    0.00    0.00  2e-07    76.34    0.00    0.00  4e-07
          64            16   float     sum    78.47    0.00    0.00  4e-07    78.82    0.00    0.00  4e-07
         128            32   float     sum    80.49    0.00    0.00  4e-07    79.84    0.00    0.00  4e-07
         256            64   float     sum    82.53    0.00    0.01  4e-07    81.57    0.00    0.01  4e-07
         512           128   float     sum    84.87    0.01    0.01  4e-07    84.26    0.01    0.01  1e-07
        1024           256   float     sum    97.46    0.01    0.02  5e-07    87.67    0.01    0.02  5e-07
        2048           512   float     sum    92.73    0.02    0.04  5e-07    103.2    0.02    0.04  5e-07
        4096          1024   float     sum    100.7    0.04    0.08  5e-07    98.88    0.04    0.08  5e-07
        8192          2048   float     sum    103.8    0.08    0.15  5e-07    102.7    0.08    0.15  5e-07
       16384          4096   float     sum    114.7    0.14    0.28  5e-07    117.5    0.14    0.27  5e-07
       32768          8192   float     sum    138.6    0.24    0.46  5e-07    131.7    0.25    0.48  5e-07
       65536         16384   float     sum    431.6    0.15    0.29  1e-06    429.7    0.15    0.30  1e-06
      131072         32768   float     sum    459.4    0.29    0.55  1e-06    458.8    0.29    0.55  1e-06
      262144         65536   float     sum    486.7    0.54    1.04  1e-06    492.9    0.53    1.03  1e-06
      524288        131072   float     sum    518.3    1.01    1.96  1e-06    522.3    1.00    1.95  1e-06
     1048576        262144   float     sum   1258.9    0.83    1.61  1e-06   1266.7    0.83    1.60  1e-06
     2097152        524288   float     sum   1451.9    1.44    2.80  1e-06   1436.5    1.46    2.83  1e-06
     4194304       1048576   float     sum   1728.4    2.43    4.70  1e-06   1725.3    2.43    4.71  1e-06
     8388608       2097152   float     sum   2777.8    3.02    5.85  1e-06   2769.4    3.03    5.87  1e-06
    16777216       4194304   float     sum   4594.4    3.65    7.08  1e-06   4597.0    3.65    7.07  1e-06
    33554432       8388608   float     sum    55820    0.60    1.16  1e-06    62126    0.54    1.05  1e-06
    67108864      16777216   float     sum   156234    0.43    0.83  1e-06   279381    0.24    0.47  1e-06
   134217728      33554432   float     sum   240918    0.56    1.08  1e-06   296776    0.45    0.88  1e-06
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.18774 
```

there is  obvious degrade when size above  `65536`;
As  the only differenet is nccl versions ,  what is  the `timing`  diff between 257 and 2.6+ ? 
And as  issue : #306 , the nccl 267 with `NCCL_IB_AR_THRESHOLD set by environment to 4194304.`  take no effect.

**Comment by sjeaugey** [comment]
RoCE bandwidth going down to 0.x GB/s is very typical of a RoCE fabric not having proper flow control and therefore dropping packets.

Usually this is solved by enabling flow control in the switch (pause frames), or PFC.
What is the vendor of your switch ?

**Comment by qianzhang613** [comment]
ours switch is **HW  CE12804-AC**  https://www.router-switch.com/ce12804-ac-p-16386.html.

and i have some doubt that why **nccl 2.5.7** did not trigger  the `dropping packets.` ?  
especially this `dropping packets` is 100% for nccl 276 but  0% with nccl 2.5.7.   ours test devices and driver  both are same ..

**Comment by sjeaugey** [comment]
That is indeed a good question and I don't have the answer. My experience with RoCE though is that timing is important and a small change can cause perf to drop (and RoCE perf usually drops very, very badly).

In any case, I'd work with Huawei on how to configure the fabric for RoCE traffic. This is a recurrent issue so it would be good for it to be well documented. A quick search returned [that page](https://support.huawei.com/enterprise/en/doc/EDOC1000074842?section=j005) (see 2.6.4 Configuring Flow Control). Hope that helps.

**Comment by qianzhang613** [comment]
> That is indeed a good question and I don't have the answer. My experience with RoCE though is that timing is important and a small change can cause perf to drop (and RoCE perf usually drops very, very badly).
> 
> In any case, I'd work with Huawei on how to configure the fabric for RoCE traffic. This is a recurrent issue so it would be good for it to be well documented. A quick search returned [that page](https://support.huawei.com/enterprise/en/doc/EDOC1000074842?section=j005) (see 2.6.4 Configuring Flow Control). Hope that helps.

we check the drop packets counter , both in Ethernet and Switchs is **zero**,  And the **busbw** first  degrade occur  at size is ` 65536` ,  at that time  **busbw** just is `0.29 (GB/s)  ` ,  is that  too small to trigger flow control ?  in my knowledge, the Flow Control ie Pasue Frame only send when there is congestion ?

**Comment by sjeaugey** [comment]
I'm not expert enough to explain how to investigate what is really happening by looking at counters. I just know that we saw similar performance numbers on other switches, which went away after we enabled flow control, so if I had to investigate, this is what I would try first.

NCCL only uses the IB verbs interface to communicate, so we have little control on how things are actually transmitted through the network. Why performance differs between those two versions on your setup is a mystery; we could not find what we do differently between the two versions. And we don't see a difference on Infiniband switches, or on Mellanox Ethernet switches (with flow control enabled).

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
