### ISSUE TITLE
NCCL WARN Call to ibv_create_cq failed

### ISSUE THREAD

**Issue by wbo4958** [NVIDIA/nccl#380]
Hi all,

I ran XGBoost with NCCL(2.7.8+cuda11.0) static linked on **2 nodes (each node has 1 A100)**. But seems some error happened in sync by NCCL. I added "NCCL_DEBUG=INFO" to print out some NCCL logs. Could you help with that?

BTW, I tried to use [NCCL test](https://github.com/NVIDIA/nccl-tests) to check if NCCL can work, But I can't find any configurations to specify different cross-networking nodes, Seems it can be used in single node?

> Node 1
```
spark01:2683:2780 [0] NCCL INFO Bootstrap : Using [0]ens192f1:10.150.178.134<0>
spark01:2683:2780 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
spark01:2683:2780 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/RoCE ; OOB ens192f1:10.150.178.134<0>
spark01:2683:2780 [0] NCCL INFO Using network IB
NCCL version 2.7.8+cuda11.0
spark01:2683:2826 [0] NCCL INFO Channel 00/02 :    0   1
spark01:2683:2826 [0] NCCL INFO Channel 01/02 :    0   1
spark01:2683:2826 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
spark01:2683:2826 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] -1/-1/-1->0->1|1->0->-1/-1/-1
spark01:2683:2826 [0] NCCL INFO Channel 00 : 1[3000] -> 0[3000] [receive] via NET/IB/0
spark01:2683:2826 [0] NCCL INFO Channel 00 : 0[3000] -> 1[3000] [send] via NET/IB/0

spark01:2683:2826 [0] misc/ibvwrap.cc:268 NCCL WARN Call to ibv_create_cq failed
spark01:2683:2826 [0] NCCL INFO transport/net_ib.cc:338 -> 2
spark01:2683:2826 [0] NCCL INFO transport/net_ib.cc:435 -> 2
spark01:2683:2826 [0] NCCL INFO include/net.h:21 -> 2
spark01:2683:2826 [0] NCCL INFO transport/net.cc:161 -> 2
spark01:2683:2826 [0] NCCL INFO transport.cc:68 -> 2
spark01:2683:2826 [0] NCCL INFO init.cc:766 -> 2
spark01:2683:2826 [0] NCCL INFO init.cc:840 -> 2
spark01:2683:2826 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
```

> Node 2
```
spark02:26830:26904 [0] NCCL INFO Bootstrap : Using [0]ens192f1:10.150.178.135<0>
spark02:26830:26904 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
spark02:26830:26904 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/RoCE ; OOB ens192f1:10.150.178.135<0>
spark02:26830:26904 [0] NCCL INFO Using network IB
spark02:26830:26935 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
spark02:26830:26935 [0] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] 0/-1/-1->1->-1|-1->1->0/-1/-1
spark02:26830:26935 [0] NCCL INFO Channel 00 : 0[3000] -> 1[3000] [receive] via NET/IB/0
spark02:26830:26935 [0] NCCL INFO Channel 00 : 1[3000] -> 0[3000] [send] via NET/IB/0

spark02:26830:26935 [0] misc/ibvwrap.cc:268 NCCL WARN Call to ibv_create_cq failed
spark02:26830:26935 [0] NCCL INFO transport/net_ib.cc:338 -> 2
spark02:26830:26935 [0] NCCL INFO transport/net_ib.cc:435 -> 2
spark02:26830:26935 [0] NCCL INFO include/net.h:21 -> 2
spark02:26830:26935 [0] NCCL INFO transport/net.cc:161 -> 2
spark02:26830:26935 [0] NCCL INFO transport.cc:68 -> 2
spark02:26830:26935 [0] NCCL INFO init.cc:766 -> 2
spark02:26830:26935 [0] NCCL INFO init.cc:840 -> 2
spark02:26830:26935 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
```

**Comment by sjeaugey** [comment]
Hi @wbo4958,

The first things I would check are :
 - The memlock limit is not set high enough, i.e. `ulimit -l` is too low. This is usually solved by adding those 2 lines in /etc/security/limits.conf then rebooting (see this [Open MPI FAQ entry](https://www.open-mpi.org/faq/?category=openfabrics#ib-locked-pages) for more details) :
```
 * soft memlock unlimited
 * hard memlock unlimited
```
 - If you are running inside a container, the IB verbs stack inside the container matches the IB driver on the host.

For the NCCL tests, to be able to run on multiple nodes, you need to compile with MPI support, e.g. :
```
make -j NCCL_HOME=/path/to/nccl CUDA_HOME=/path/to/cuda MPI_HOME=/path/to/mpi MPI=1
mpirun -H node1:1,node2:1 ./build/all_reduce_perf -b 8 -e 128M -f 2
```

**Comment by ericrife** [comment]
This turned out to be an issue with OFED 5.1 driver. Downgrading to 5.0 resolved the issue on the cluster.

**Comment by wbo4958** [comment]
Thx @ericrife @sjeaugey
