### ISSUE TITLE
NCCL didn't print the right log about connection when enable the GDR

### ISSUE THREAD

**Issue by weberxie** [NVIDIA/nccl#392]
Environment
- NCCL version 2.5.7+cuda10.0
- 8 * V100-PCIe per node, a total of 2 nodes

test command:
```
mpirun -np 16 --hostfile ../../hostfile.txt -bind-to none -map-by slot --display-map --mca pml ob1 --mca btl_vader_single_copy_mechanism none --mca btl_openib_cpc_include rdmacm --mca btl_openib_rroce_enable 1 --mca btl_tcp_if_exclude lo,docker0 --mca orte_base_help_aggregate 0 --mca btl_openib_receive_queues P,256,256::S,128,256,192,128:S,2048,1024,1008,64:S,12288,1024,1008,64:S,131072,1024,1008,64 --mca btl openib,self,vader -x NCCL_SOCKET_IFNAME=^lo,docker0 -x NCCL_IB_DISABLE=0 -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_DEBUG_FILE=/tmp/debug.log.%h.%p -x NCCL_IB_HCA=mlx5_0:1 -x NCCL_IB_GID_INDEX=3 -x NCCL_NET_GDR_READ=0 ./all_reduce_perf -b 8 -e 128M -f 2
```

Question:
When I switched the ENV NCCL_NET_GDR_READ from 0 to 1, the nccl tests showed that the latency is much slower,
when the NCCL_NET_GDR_READ was 0, the nccl-tests outpus was:
```
                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    38.87    0.00    0.00  2e-07    36.96    0.00    0.00  2e-07
          16             4   float     sum    36.45    0.00    0.00  2e-07    36.66    0.00    0.00  1e-07
          32             8   float     sum    36.74    0.00    0.00  1e-07    36.71    0.00    0.00  1e-07
          64            16   float     sum    37.62    0.00    0.00  1e-07    37.03    0.00    0.00  1e-07
         128            32   float     sum    38.05    0.00    0.01  1e-07    38.00    0.00    0.01  1e-07
         256            64   float     sum    38.31    0.01    0.01  6e-08    38.73    0.01    0.01  6e-08
         512           128   float     sum    39.79    0.01    0.02  6e-08    39.00    0.01    0.02  6e-08
        1024           256   float     sum    40.40    0.03    0.05  2e-07    39.96    0.03    0.05  2e-07
        2048           512   float     sum    42.57    0.05    0.09  2e-07    42.42    0.05    0.09  2e-07
        4096          1024   float     sum    73.62    0.06    0.10  5e-07    72.72    0.06    0.11  5e-07
        8192          2048   float     sum    81.68    0.10    0.19  5e-07    80.06    0.10    0.19  5e-07
       16384          4096   float     sum    84.74    0.19    0.36  5e-07    83.30    0.20    0.37  5e-07
       32768          8192   float     sum    90.39    0.36    0.68  5e-07    90.26    0.36    0.68  5e-07
       65536         16384   float     sum    104.2    0.63    1.18  5e-07    102.9    0.64    1.19  5e-07
      131072         32768   float     sum    120.0    1.09    2.05  5e-07    118.6    1.11    2.07  5e-07
      262144         65536   float     sum    218.7    1.20    2.25  5e-07    221.3    1.18    2.22  5e-07
      524288        131072   float     sum    356.1    1.47    2.76  5e-07    355.5    1.47    2.77  5e-07
     1048576        262144   float     sum    479.5    2.19    4.10  5e-07    483.1    2.17    4.07  5e-07
     2097152        524288   float     sum    765.7    2.74    5.14  5e-07    764.2    2.74    5.15  5e-07
     4194304       1048576   float     sum   1428.6    2.94    5.50  5e-07   1425.0    2.94    5.52  5e-07
     8388608       2097152   float     sum   2776.9    3.02    5.66  5e-07   2764.4    3.03    5.69  5e-07
    16777216       4194304   float     sum   5475.1    3.06    5.75  5e-07   5490.5    3.06    5.73  5e-07
    33554432       8388608   float     sum    10886    3.08    5.78  5e-07    10876    3.09    5.78  5e-07
    67108864      16777216   float     sum    37080    1.81    3.39  5e-07    75304    0.89    1.67  5e-07
   134217728      33554432   float     sum    72090    1.86    3.49  5e-07    57255    2.34    4.40  5e-07
 Out of bounds values : 0 OK
 Avg bus bandwidth    : 1.92724
```
but when the NCCL_NET_GDR_READ was 1, the nccl-tests outpus was:
```
                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    43.22    0.00    0.00  2e-07    37.00    0.00    0.00  2e-07
          16             4   float     sum    37.34    0.00    0.00  2e-07    37.79    0.00    0.00  1e-07
          32             8   float     sum    37.33    0.00    0.00  1e-07    37.20    0.00    0.00  1e-07
          64            16   float     sum    37.89    0.00    0.00  1e-07    37.73    0.00    0.00  1e-07
         128            32   float     sum    38.61    0.00    0.01  1e-07    38.53    0.00    0.01  1e-07
         256            64   float     sum    43.42    0.01    0.01  6e-08    39.17    0.01    0.01  6e-08
         512           128   float     sum    40.46    0.01    0.02  6e-08    40.32    0.01    0.02  6e-08
        1024           256   float     sum    40.59    0.03    0.05  2e-07    40.28    0.03    0.05  2e-07
        2048           512   float     sum    43.55    0.05    0.09  2e-07    43.05    0.05    0.09  2e-07
        4096          1024   float     sum    73.49    0.06    0.10  5e-07    70.96    0.06    0.11  5e-07
        8192          2048   float     sum    79.89    0.10    0.19  5e-07    79.86    0.10    0.19  5e-07
       16384          4096   float     sum    84.63    0.19    0.36  5e-07    83.82    0.20    0.37  5e-07
       32768          8192   float     sum    93.38    0.35    0.66  5e-07    91.32    0.36    0.67  5e-07
       65536         16384   float     sum    107.4    0.61    1.14  5e-07    104.1    0.63    1.18  5e-07
      131072         32768   float     sum    122.9    1.07    2.00  5e-07    121.7    1.08    2.02  5e-07
      262144         65536   float     sum    225.9    1.16    2.18  5e-07    226.2    1.16    2.17  5e-07
      524288        131072   float     sum    346.8    1.51    2.83  5e-07    345.5    1.52    2.85  5e-07
     1048576        262144   float     sum    428.7    2.45    4.59  5e-07    430.0    2.44    4.57  5e-07
     2097152        524288   float     sum    576.1    3.64    6.83  5e-07    580.9    3.61    6.77  5e-07
     4194304       1048576   float     sum    927.3    4.52    8.48  5e-07    926.1    4.53    8.49  5e-07
     8388608       2097152   float     sum   1678.7    5.00    9.37  5e-07   1683.0    4.98    9.35  5e-07
    16777216       4194304   float     sum   3393.2    4.94    9.27  5e-07   3382.5    4.96    9.30  5e-07
    33554432       8388608   float     sum   7094.9    4.73    8.87  5e-07   7055.8    4.76    8.92  5e-07
    67108864      16777216   float     sum    16353    4.10    7.69  5e-07    16348    4.10    7.70  5e-07
   134217728      33554432   float     sum    32639    4.11    7.71  5e-07    32753    4.10    7.68  5e-07
 Out of bounds values : 0 OK
 Avg bus bandwidth    : 2.89958
```
If I stop the nv_peer_mem service manualy by run the command:
`service nv_peer_mem stop`,

Then run the tests with NCCL_NET_GDR_READ=0, the result was:
```
                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    39.78    0.00    0.00  2e-07    38.16    0.00    0.00  2e-07
          16             4   float     sum    37.00    0.00    0.00  2e-07    37.33    0.00    0.00  1e-07
          32             8   float     sum    37.30    0.00    0.00  1e-07    37.08    0.00    0.00  1e-07
          64            16   float     sum    38.21    0.00    0.00  2e-07    38.90    0.00    0.00  2e-07
         128            32   float     sum    38.55    0.00    0.01  2e-07    38.87    0.00    0.01  2e-07
         256            64   float     sum    39.50    0.01    0.01  2e-07    39.42    0.01    0.01  2e-07
         512           128   float     sum    40.47    0.01    0.02  2e-07    39.91    0.01    0.02  2e-07
        1024           256   float     sum    41.05    0.02    0.05  2e-07    41.08    0.02    0.05  2e-07
        2048           512   float     sum    44.04    0.05    0.09  2e-07    43.84    0.05    0.09  2e-07
        4096          1024   float     sum    48.00    0.09    0.16  2e-07    47.30    0.09    0.16  2e-07
        8192          2048   float     sum    52.58    0.16    0.29  2e-07    51.76    0.16    0.30  2e-07
       16384          4096   float     sum    65.36    0.25    0.47  2e-07    64.10    0.26    0.48  2e-07
       32768          8192   float     sum    90.61    0.36    0.68  2e-07    87.10    0.38    0.71  2e-07
       65536         16384   float     sum    133.1    0.49    0.92  2e-07    258.5    0.25    0.48  2e-07
      131072         32768   float     sum    283.5    0.46    0.87  5e-07    277.1    0.47    0.89  5e-07
      262144         65536   float     sum    307.3    0.85    1.60  5e-07    300.6    0.87    1.63  5e-07
      524288        131072   float     sum    350.6    1.50    2.80  5e-07    353.6    1.48    2.78  5e-07
     1048576        262144   float     sum    475.0    2.21    4.14  5e-07    474.2    2.21    4.15  5e-07
     2097152        524288   float     sum    766.7    2.74    5.13  5e-07    762.5    2.75    5.16  5e-07
     4194304       1048576   float     sum   1453.1    2.89    5.41  5e-07   1451.9    2.89    5.42  5e-07
     8388608       2097152   float     sum   2980.8    2.81    5.28  5e-07   2984.1    2.81    5.27  5e-07
    16777216       4194304   float     sum    71226    0.24    0.44  5e-07   5877.2    2.85    5.35  5e-07
    33554432       8388608   float     sum    12570    2.67    5.01  2e-07    12543    2.68    5.02  2e-07
    67108864      16777216   float     sum    97148    0.69    1.30  2e-07    25695    2.61    4.90  2e-07
   134217728      33554432   float     sum    97671    1.37    2.58  2e-07    69526    1.93    3.62  2e-07
 Out of bounds values : 0 OK
 Avg bus bandwidth    : 1.67461
```
So, this description that GDR did take effect.

but the NCCL debug log always is `[0] NCCL INFO Ring 00 : 15[41000] -> 0[1b000] [receive] via NET/IB/0`

**Comment by sjeaugey** [comment]
Thanks for the report. This is quite strange, we've never seen the reporting being wrong. It is controlled by the same flag which enables/disables GDR during communication.

Could it be that for some reason, GDR is only partially enabled (i.e. there are still a few NET/IB/0/GDRDMA lines but not on all ranks) ?

It could also be a 2.5.7 issue I forgot about so if you can run with 2.7.8 it would get that out of the way.

Other than that, if you could post the log we could review it more carefully and see if we can explain why performance varies while the output log doesn't.

**Comment by weberxie** [comment]
Thanks @sjeaugey, you are right, it seems that GDR is only partially enabled.

Here are the logs of rank 0 and rank 7 on first node, rank 0  and rank 7 on second node.

logs of rank 0 on 1st node:

 [0] NCCL INFO Bootstrap : Using [0]br0:10.137.141.16<0>
 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB br0:10.137.141.16<0>
 [0] NCCL INFO NCCL version 2.5.7+cuda10.0
 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
 [0] NCCL INFO Channel 00/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
 [0] NCCL INFO Channel 01/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
 [0] NCCL INFO Threads per block : 512/640/256
 [0] NCCL INFO threadThresholds 8/8/64 | 128/8/64
 [0] NCCL INFO Trees [0] 1/-1/-1->0->7|7->0->1/-1/-1 [1] 1/-1/-1->0->7|7->0->1/-1/-1
 [0] NCCL INFO Ring 00 : 15[41000] -> 0[1b000] [receive] via NET/IB/0
 [0] NCCL INFO Ring 00 : 0[1b000] -> 1[1c000] via P2P/IPC
 [0] NCCL INFO Ring 00 : 0[1b000] -> 7[41000] via direct shared memory
 [0] NCCL INFO Ring 01 : 15[41000] -> 0[1b000] [receive] via NET/IB/0
 [0] NCCL INFO Ring 01 : 0[1b000] -> 1[1c000] via P2P/IPC
 [0] NCCL INFO Ring 01 : 0[1b000] -> 7[41000] via direct shared memory
 [0] NCCL INFO comm 0x7fc298001ce0 rank 0 nranks 16 cudaDev 0 busId 1b000 - Init COMPLETE
 [0] NCCL INFO Launch mode Parallel

logs of rank 7 on 1st node:

[7] NCCL INFO Bootstrap : Using [0]br0:10.137.141.16<0>
[7] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[7] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[7] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB br0:10.137.141.16<0>
[7] NCCL INFO Setting affinity for GPU 7 to ffff,0000ffff
[7] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
[7] NCCL INFO Threads per block : 512/640/256
[7] NCCL INFO threadThresholds 8/8/64 | 128/8/64
[7] NCCL INFO Trees [0] 0/-1/-1->7->6|6->7->0/-1/-1 [1] 0/-1/-1->7->6|6->7->0/-1/-1
[7] NCCL INFO NCCL_NET_GDR_READ set by environment to 1.
[7] NCCL INFO Ring 00 : 7[41000] -> 8[1b000] [send] via NET/IB/0/GDRDMA
[7] NCCL INFO Ring 00 : 7[41000] -> 6[40000] via P2P/IPC
[7] NCCL INFO Ring 00 : 7[41000] -> 0[1b000] via direct shared memory
[7] NCCL INFO Ring 01 : 7[41000] -> 8[1b000] [send] via NET/IB/0/GDRDMA
[7] NCCL INFO Ring 01 : 7[41000] -> 6[40000] via P2P/IPC
[7] NCCL INFO Ring 01 : 7[41000] -> 0[1b000] via direct shared memory
[7] NCCL INFO comm 0x4154690 rank 7 nranks 16 cudaDev 7 busId 41000 - Init COMPLETE

logs of rank 0 on 2nd node:

[0] NCCL INFO Bootstrap : Using [0]br0:10.137.142.6<0>
[0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB br0:10.137.142.6<0>
[0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
[0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
[0] NCCL INFO Threads per block : 512/640/256
[0] NCCL INFO threadThresholds 8/8/64 | 128/8/64
[0] NCCL INFO Trees [0] 9/-1/-1->8->15|15->8->9/-1/-1 [1] 9/-1/-1->8->15|15->8->9/-1/-1
[0] NCCL INFO Ring 00 : 7[41000] -> 8[1b000] [receive] via NET/IB/0
[0] NCCL INFO Ring 00 : 8[1b000] -> 9[1c000] via P2P/IPC
[0] NCCL INFO Ring 00 : 8[1b000] -> 15[41000] via direct shared memory
[0] NCCL INFO Ring 01 : 7[41000] -> 8[1b000] [receive] via NET/IB/0
[0] NCCL INFO Ring 01 : 8[1b000] -> 9[1c000] via P2P/IPC
[0] NCCL INFO Ring 01 : 8[1b000] -> 15[41000] via direct shared memory
[0] NCCL INFO comm 0x7f57e0001cc0 rank 8 nranks 16 cudaDev 0 busId 1b000 - Init COMPLETE

logs of rank 7 on 2nd node:

[7] NCCL INFO Bootstrap : Using [0]br0:10.137.142.6<0>
[7] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[7] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[7] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE ; OOB br0:10.137.142.6<0>
[7] NCCL INFO Setting affinity for GPU 7 to ffff,0000ffff
[7] NCCL INFO NCCL_IB_GID_INDEX set by environment to 3.
[7] NCCL INFO Threads per block : 512/640/256
[7] NCCL INFO threadThresholds 8/8/64 | 128/8/64
[7] NCCL INFO Trees [0] 8/-1/-1->15->14|14->15->8/-1/-1 [1] 8/-1/-1->15->14|14->15->8/-1/-1
[7] NCCL INFO NCCL_NET_GDR_READ set by environment to 1.
[7] NCCL INFO Ring 00 : 15[41000] -> 0[1b000] [send] via NET/IB/0/GDRDMA
[7] NCCL INFO Ring 00 : 15[41000] -> 14[40000] via P2P/IPC
[7] NCCL INFO Ring 00 : 15[41000] -> 8[1b000] via direct shared memory
[7] NCCL INFO Ring 01 : 15[41000] -> 0[1b000] [send] via NET/IB/0/GDRDMA
[7] NCCL INFO Ring 01 : 15[41000] -> 14[40000] via P2P/IPC
[7] NCCL INFO Ring 01 : 15[41000] -> 8[1b000] via direct shared memory
[7] NCCL INFO comm 0x7fb728001cc0 rank 15 nranks 16 cudaDev 7 busId 41000 - Init COMPLETE

**Comment by weberxie** [comment]
And the topo of GPUs is:
<img width="782" alt="Screen Shot 2020-09-25 at 12 23 50 AM" src="https://user-images.githubusercontent.com/3942083/94173071-ec053c80-fec5-11ea-8a0e-a743aeeb9d1b.png">

**Comment by sjeaugey** [comment]
I see. So your NIC is close to GPUs 4,5,6,7.

I'm not sure why the search doesn't reverse the order, receiving data (with GDR) into one of the last GPUs (4,5,6,7), then exiting the node from one of the first GPUs (0,1,2,3).

But now it makes sense. It would definitely be useful to try NCCL 2.7 and if it still works the same, please let us know.

**Comment by kwen2501** [comment]
@weberxie `NCCL_NET_GDR_READ` only takes effect on the [send] lines, it would not take effect on the [receive] lines.

**Comment by sjeaugey** [comment]
Actually I found why we don't pick the best ring. Would you be able to run with NCCL 2.6 or 2.7 and test the attached file setting `NCCL_GRAPH_FILE=graph.txt` ?

I'd like to confirm this is the best solution on your platform.

[graph.txt](https://github.com/NVIDIA/nccl/files/5277889/graph.txt)

**Comment by sjeaugey** [comment]
Also, please try the attached patch (on top of 2.7.8) and see if it solves the problem. Thanks !

[gh_issue_392_patch.txt](https://github.com/NVIDIA/nccl/files/5279183/gh_issue_392_patch.txt)

**Comment by weberxie** [comment]
@kwen2501 Thanks, you are right, but you can check the logs I have posted, some ranks also received with GDR.

**Comment by weberxie** [comment]
I have switched the NCCL to 2.7.8 and didn't patch the file and didn't set NCCL_GRAPH_FILE=graph.txt, but the nccl-tests result wrose than the result when the version was 2.5.7.

                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    36.88    0.00    0.00  2e-07    36.34    0.00    0.00  2e-07
          16             4   float     sum    38.02    0.00    0.00  2e-07    35.61    0.00    0.00  1e-07
          32             8   float     sum    35.97    0.00    0.00  1e-07    35.87    0.00    0.00  1e-07
          64            16   float     sum    36.75    0.00    0.00  1e-07    36.39    0.00    0.00  1e-07
         128            32   float     sum    36.86    0.00    0.01  1e-07    36.72    0.00    0.01  1e-07
         256            64   float     sum    38.09    0.01    0.01  6e-08    38.04    0.01    0.01  6e-08
         512           128   float     sum    40.13    0.01    0.02  6e-08    39.85    0.01    0.02  6e-08
        1024           256   float     sum    41.76    0.02    0.05  2e-07    40.37    0.03    0.05  2e-07
        2048           512   float     sum    43.39    0.05    0.09  2e-07    42.46    0.05    0.09  2e-07
        4096          1024   float     sum    46.96    0.09    0.16  2e-07    46.27    0.09    0.17  2e-07
        8192          2048   float     sum    51.66    0.16    0.30  5e-07    51.70    0.16    0.30  5e-07
       16384          4096   float     sum    65.20    0.25    0.47  5e-07    63.15    0.26    0.49  5e-07
       32768          8192   float     sum    91.43    0.36    0.67  5e-07    91.87    0.36    0.67  5e-07
       65536         16384   float     sum    106.5    0.62    1.15  5e-07    104.8    0.63    1.17  5e-07
      131072         32768   float     sum    124.5    1.05    1.97  5e-07    125.6    1.04    1.96  5e-07
      262144         65536   float     sum    220.6    1.19    2.23  5e-07    219.7    1.19    2.24  5e-07
      524288        131072   float     sum    364.9    1.44    2.69  5e-07    360.2    1.46    2.73  5e-07
     1048576        262144   float     sum    459.7    2.28    4.28  5e-07    455.3    2.30    4.32  5e-07
     2097152        524288   float     sum    631.3    3.32    6.23  5e-07    627.7    3.34    6.26  5e-07
     4194304       1048576   float     sum   1069.2    3.92    7.36  5e-07   1069.3    3.92    7.35  5e-07
     8388608       2097152   float     sum   2007.5    4.18    7.83  5e-07   2005.0    4.18    7.84  5e-07
    16777216       4194304   float     sum   3915.1    4.29    8.03  5e-07   3909.9    4.29    8.05  5e-07
    33554432       8388608   float     sum   7959.6    4.22    7.90  5e-07   7958.0    4.22    7.91  5e-07
    67108864      16777216   float     sum    16366    4.10    7.69  5e-07    16387    4.10    7.68  5e-07
    134217728      33554432   float     sum    32565    4.12    7.73  5e-07    32898    4.08    7.65  5e-07
 

Out of bounds values : 0 OK
 Avg bus bandwidth    : 2.67703

And the nccl log for all ranks are attached.


[nccl.log.host1.txt](https://github.com/NVIDIA/nccl/files/5283567/nccl.log.host1.txt)
[nccl.log.host0.txt](https://github.com/NVIDIA/nccl/files/5283568/nccl.log.host0.txt)

Is this the best ring?

**Comment by weberxie** [comment]
after set NCCL_GRAPH_FILE=graph.txt on 2.7.8, the nccl log show that, send and receive are all with GPU 4, nccl-tests result is:

                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    37.08    0.00    0.00  2e-07    36.40    0.00    0.00  2e-07
          16             4   float     sum    37.56    0.00    0.00  2e-07    36.12    0.00    0.00  1e-07
          32             8   float     sum    36.69    0.00    0.00  1e-07    36.07    0.00    0.00  1e-07
          64            16   float     sum    36.69    0.00    0.00  1e-07    36.20    0.00    0.00  1e-07
         128            32   float     sum    37.12    0.00    0.01  1e-07    36.51    0.00    0.01  1e-07
         256            64   float     sum    39.19    0.01    0.01  6e-08    38.66    0.01    0.01  6e-08
         512           128   float     sum    107.6    0.00    0.01  6e-08    39.35    0.01    0.02  6e-08
        1024           256   float     sum    43.23    0.02    0.04  2e-07    39.96    0.03    0.05  2e-07
        2048           512   float     sum    42.31    0.05    0.09  2e-07    43.87    0.05    0.09  2e-07
        4096          1024   float     sum    46.81    0.09    0.16  2e-07    45.83    0.09    0.17  2e-07
        8192          2048   float     sum    53.52    0.15    0.29  5e-07    53.67    0.15    0.29  5e-07
       16384          4096   float     sum    67.70    0.24    0.45  5e-07    64.87    0.25    0.47  5e-07
       32768          8192   float     sum    89.04    0.37    0.69  5e-07    90.96    0.36    0.68  5e-07
       65536         16384   float     sum    93.36    0.70    1.32  5e-07    90.37    0.73    1.36  5e-07
      131072         32768   float     sum    109.6    1.20    2.24  5e-07    110.1    1.19    2.23  5e-07
      262144         65536   float     sum    170.2    1.54    2.89  5e-07    167.1    1.57    2.94  5e-07
      524288        131072   float     sum    420.0    1.25    2.34  5e-07    420.0    1.25    2.34  5e-07
     1048576        262144   float     sum    524.8    2.00    3.75  5e-07    527.2    1.99    3.73  5e-07
     2097152        524288   float     sum    655.9    3.20    6.00  5e-07    656.4    3.20    5.99  5e-07
     4194304       1048576   float     sum   1045.8    4.01    7.52  5e-07   1044.7    4.01    7.53  5e-07
     8388608       2097152   float     sum   1940.5    4.32    8.11  5e-07   1934.2    4.34    8.13  5e-07
    16777216       4194304   float     sum   3985.0    4.21    7.89  5e-07   3982.1    4.21    7.90  5e-07
    33554432       8388608   float     sum   8050.0    4.17    7.82  5e-07   8053.4    4.17    7.81  5e-07
    67108864      16777216   float     sum    16261    4.13    7.74  5e-07    16269    4.12    7.73  5e-07
    134217728      33554432   float     sum    32418    4.14    7.76  5e-07    32534    4.13    7.74  5e-07
 
Out of bounds values : 0 OK
 Avg bus bandwidth    : 2.68698

**Comment by weberxie** [comment]
After did the patch, the nccl logs is attatched, 
[nccl_2.7.8_with_patch.log.txt](https://github.com/NVIDIA/nccl/files/5283745/nccl_2.7.8_with_patch.log.txt)


the nccl-tests result wrose than the origin version of 2.7.8:

                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    36.62    0.00    0.00  2e-07    36.26    0.00    0.00  2e-07
          16             4   float     sum    35.92    0.00    0.00  2e-07    35.46    0.00    0.00  1e-07
          32             8   float     sum    36.05    0.00    0.00  1e-07    36.79    0.00    0.00  1e-07
          64            16   float     sum    36.08    0.00    0.00  1e-07    36.41    0.00    0.00  1e-07
         128            32   float     sum    37.79    0.00    0.01  1e-07    36.75    0.00    0.01  1e-07
         256            64   float     sum    38.12    0.01    0.01  6e-08    38.21    0.01    0.01  6e-08
         512           128   float     sum    39.29    0.01    0.02  6e-08    39.38    0.01    0.02  6e-08
        1024           256   float     sum    40.06    0.03    0.05  2e-07    39.89    0.03    0.05  2e-07
        2048           512   float     sum    42.53    0.05    0.09  2e-07    42.76    0.05    0.09  2e-07
        4096          1024   float     sum    46.12    0.09    0.17  2e-07    45.77    0.09    0.17  2e-07
        8192          2048   float     sum    52.85    0.16    0.29  5e-07    51.96    0.16    0.30  5e-07
       16384          4096   float     sum    67.44    0.24    0.46  5e-07    65.12    0.25    0.47  5e-07
       32768          8192   float     sum    80.59    0.41    0.76  5e-07    79.27    0.41    0.78  5e-07
       65536         16384   float     sum    90.44    0.72    1.36  5e-07    89.70    0.73    1.37  5e-07
      131072         32768   float     sum    107.5    1.22    2.29  5e-07    105.3    1.24    2.33  5e-07
      262144         65536   float     sum    176.3    1.49    2.79  5e-07    178.8    1.47    2.75  5e-07
      524288        131072   float     sum    417.3    1.26    2.36  5e-07    446.2    1.17    2.20  5e-07
     1048576        262144   float     sum    524.0    2.00    3.75  5e-07    517.8    2.03    3.80  5e-07
     2097152        524288   float     sum    675.4    3.11    5.82  5e-07    677.9    3.09    5.80  5e-07
     4194304       1048576   float     sum   1285.6    3.26    6.12  5e-07   1253.8    3.35    6.27  5e-07
     8388608       2097152   float     sum   2604.8    3.22    6.04  5e-07   2601.9    3.22    6.05  5e-07
    16777216       4194304   float     sum   5601.1    3.00    5.62  5e-07   5605.1    2.99    5.61  5e-07
    33554432       8388608   float     sum    11527    2.91    5.46  5e-07    11533    2.91    5.46  5e-07
    67108864      16777216   float     sum    23128    2.90    5.44  5e-07    23086    2.91    5.45  5e-07
    134217728      33554432   float     sum    46279    2.90    5.44  5e-07    46237    2.90    5.44  5e-07

 Out of bounds values : 0 OK
 Avg bus bandwidth    : 2.17525

**Comment by sjeaugey** [comment]
Hi @weberxie,

I forgot to mention you needed to remove NCCL_NET_GDR_READ=1.

Not sure it will make a difference, just the idea was that you should not need it if the rings are in the right order, i.e. receive to a GPU close to the NIC and send from a GPU far from the NIC (through CPU memory).

Now I'm not sure why the performance with NCCL_GRAPH_FILE=graph.txt is not the same as with the patch, as the rings created are the same as described in graph.txt. Could you force NCCL_ALGO=RING to make sure we're using rings and post the log with NCCL_GRAPH_FILE=graph.txt ?

**Comment by weberxie** [comment]
Sure, with the origin version of 2.7.8, below are the logs when NCCL_GRAPH_FILE=graph.txt and NCCL_ALGO=RING,


                                                     out-of-place                       in-place
       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)
           8             2   float     sum    39.27    0.00    0.00  2e-07    36.31    0.00    0.00  2e-07
          16             4   float     sum    37.70    0.00    0.00  2e-07    36.52    0.00    0.00  1e-07
          32             8   float     sum    36.70    0.00    0.00  1e-07    37.33    0.00    0.00  1e-07
          64            16   float     sum    37.31    0.00    0.00  1e-07    37.19    0.00    0.00  1e-07
         128            32   float     sum    38.38    0.00    0.01  1e-07    38.10    0.00    0.01  1e-07
         256            64   float     sum    39.08    0.01    0.01  6e-08    39.10    0.01    0.01  6e-08
         512           128   float     sum    40.62    0.01    0.02  6e-08    40.13    0.01    0.02  6e-08
        1024           256   float     sum    41.50    0.02    0.05  2e-07    41.97    0.02    0.05  2e-07
        2048           512   float     sum    43.84    0.05    0.09  2e-07    43.32    0.05    0.09  2e-07
        4096          1024   float     sum    47.06    0.09    0.16  2e-07    46.92    0.09    0.16  2e-07
        8192          2048   float     sum    53.18    0.15    0.29  5e-07    52.30    0.16    0.29  5e-07
       16384          4096   float     sum    65.49    0.25    0.47  5e-07    63.59    0.26    0.48  5e-07
       32768          8192   float     sum    91.99    0.36    0.67  5e-07    86.44    0.38    0.71  5e-07
       65536         16384   float     sum    95.24    0.69    1.29  5e-07    91.69    0.71    1.34  5e-07
      131072         32768   float     sum    108.9    1.20    2.26  5e-07    109.0    1.20    2.26  5e-07
      262144         65536   float     sum    169.9    1.54    2.89  5e-07    170.7    1.54    2.88  5e-07
      524288        131072   float     sum    428.7    1.22    2.29  5e-07    419.8    1.25    2.34  5e-07
     1048576        262144   float     sum    526.0    1.99    3.74  5e-07    523.0    2.00    3.76  5e-07
     2097152        524288   float     sum    658.6    3.18    5.97  5e-07    653.1    3.21    6.02  5e-07
     4194304       1048576   float     sum   1051.7    3.99    7.48  5e-07   1053.6    3.98    7.46  5e-07
     8388608       2097152   float     sum   1948.0    4.31    8.07  5e-07   1953.5    4.29    8.05  5e-07
    16777216       4194304   float     sum   3952.4    4.24    7.96  5e-07   3938.2    4.26    7.99  5e-07
    33554432       8388608   float     sum   8034.4    4.18    7.83  5e-07   8064.4    4.16    7.80  5e-07
    67108864      16777216   float     sum    16176    4.15    7.78  5e-07    16144    4.16    7.79  5e-07
    134217728      33554432   float     sum    32395    4.14    7.77  5e-07    32382    4.14    7.77  5e-07
 
Out of bounds values : 0 OK
 Avg bus bandwidth    : 2.68806

[nccl.log.2.7.8_force_ring.txt](https://github.com/NVIDIA/nccl/files/5285996/nccl.log.2.7.8_force_ring.txt)

**Comment by sjeaugey** [comment]
Thanks. So here is how different rings seem to behave on your system :
 - 0, 1, 2, 3, 4, 5, 6, 7  [Default]  ~5 GB/s
 - 0, 1, 2, 3, 4, 5, 6, 7  [NCCL_NET_GDR_READ=1] ~8 GB/s
 - 4, 5, 6, 7, 0, 1, 2, 3  [Graph.txt] ~8 GB/s
 - 4, 5, 6, 7, 3, 2, 1, 0  [Patch] ~5 GB/s

I can't explain why those last two do not give the same performance. In theory they should. 

It would be great if you could confirm those numbers, by changing the `graph.txt` file to change the order of the intra-node ring (GPU tags under `<graph id="0" pattern="4">`) to the rings above, and double check these are the numbers you get.

**Comment by weberxie** [comment]
Hi, @sjeaugey I'm going to test these numbers, but I can't understand the meaning of graph.txt.

And there are log such as:

`Trees [0] 1/-1/-1->0->7|7->0->1/-1/-1 [1] 1/-1/-1->0->7|7->0->1/-1/-1`

Could you explain them?

**Comment by weberxie** [comment]
When I set the env NCCL_TOPO_DUMP_FILE
the result is:

```
<system version="1">
  <cpu numaid="0" affinity="00000000,00000000,00000000,00000000,00000000,0000ffff,0000ffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="0000:18:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:1b:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="0" sm="70" rank="0" gdr="0"/>
      </pci>
      <pci busid="0000:1c:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="1" sm="70" rank="1" gdr="0"/>
      </pci>
      <pci busid="0000:1d:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="2" sm="70" rank="2" gdr="0"/>
      </pci>
      <pci busid="0000:1e:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="3" sm="70" rank="3" gdr="0"/>
      </pci>
      <pci busid="0000:1a:00.0" class="0x020000" link_speed="" link_width="0">
        <nic>
          <net name="mlx5_0" dev="0" speed="100000" port="1" guid="0x4a5e460003a1420c" maxconn="262144" gdr="0"/>
        </nic>
      </pci>
    </pci>
    <pci busid="0000:3b:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:3d:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="4" sm="70" rank="4" gdr="0"/>
      </pci>
      <pci busid="0000:3f:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="5" sm="70" rank="5" gdr="0"/>
      </pci>
      <pci busid="0000:40:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="6" sm="70" rank="6" gdr="0"/>
      </pci>
      <pci busid="0000:41:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="7" sm="70" rank="7" gdr="0"/>
      </pci>
    </pci>
  </cpu>
</system>
```
the question is, why gdr are all 0.

**Comment by sjeaugey** [comment]
In the graph.txt XML file you have three `<graph>` sections, with `id="0" pattern="4"`, `id="1" pattern="2"` and `id="2" pattern="3"`, which correspond to the three algorithms : ring, tree and collnet.
The first one, with `id="0" pattern="4"` is the intra-node ring. We define one ring (`nchannels="1"`) and that ring is described as :
```
<channel>
  <net dev="0"/>
  <gpu dev="4"/>
  <gpu dev="5"/>
  <gpu dev="6"/>
  <gpu dev="7"/>
  <gpu dev="0"/>
  <gpu dev="1"/>
  <gpu dev="2"/>
  <gpu dev="3"/>
  <net dev="0"/>
</channel>
```
This is the order in which the ring will go through the node : it will enter the node from NET device 0, then go to GPU 4, then GPU 5, GPU 6, GPU 7, GPU 0, GPU 1, GPU 2, and finally GPU 3 before going back to NET 0.
So you can change the order of GPUs to find which one works best for you and try to understand which flow works the best on a given platform.

I can't guarantee NCCL can always decide to use a precise combination on a given platform (we don't detect specific server model numbers to apply a static ring configuration) but given a set of combinations which work well, we can try to understand why and have the NCCL search algorithm converge to one of the good solutions.

**Comment by weberxie** [comment]
Thanks for your detail reponse.

I have print the topo by set NCCL_TOPO_DUMP_FILE,

the result shows that all GPUs and NIC are support GDR:

<system version="1">
  <cpu numaid="0" affinity="000f,ff000fff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="79">
    <pci busid="0000:02:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:04:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="0" sm="70" rank="0" gdr="1"/>
      </pci>
      <pci busid="0000:05:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="1" sm="70" rank="1" gdr="1"/>
      </pci>
    </pci>
    <pci busid="0000:06:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:08:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="2" sm="70" rank="2" gdr="1"/>
      </pci>
      <pci busid="0000:09:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="3" sm="70" rank="3" gdr="1"/>
      </pci>
    </pci>
    <pci busid="0000:01:00.0" class="0x020000" link_speed="" link_width="0">
      <nic>
        <net name="mlx5_0" dev="0" speed="100000" port="1" guid="0x66f8c200039f59b8" maxconn="262144" gdr="1"/>
      </nic>
    </pci>
  </cpu>
  <cpu numaid="1" affinity="fff0,00fff000" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="79">
    <pci busid="0000:83:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:85:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="4" sm="70" rank="4" gdr="1"/>
      </pci>
      <pci busid="0000:86:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="5" sm="70" rank="5" gdr="1"/>
      </pci>
    </pci>
    <pci busid="0000:87:00.0" class="0x060400" link_speed="" link_width="0">
      <pci busid="0000:89:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="6" sm="70" rank="6" gdr="1"/>
      </pci>
      <pci busid="0000:8a:00.0" class="0x030200" link_speed="" link_width="0">
        <gpu dev="7" sm="70" rank="7" gdr="1"/>
      </pci>
    </pci>
  </cpu>
</system>

**Comment by weberxie** [comment]
> This is the order in which the ring will go through the node : it will enter the node from NET device 0, then go to GPU 4, then GPU 5, GPU 6, GPU 7, GPU 0, GPU 1, GPU 2, and finally GPU 3 before going back to NET 0.

I'm trying to reproduce the result, as your advice, I set the NCCL_GRAPH_FILE=graph.txt and NCCL_ALGO=RING,

then the logs show that, except GPU 4 and GPU 3, other GPU will also connection through the NET, for example:

[3] NCCL INFO Channel 00 : 11[1e000] -> 4[3d000] [send] via NET/IB/0
[3] NCCL INFO Channel 01 : 11[1e000] -> 4[3d000] [send] via NET/IB/0
[4] NCCL INFO Channel 00 : 12[3d000] -> 5[3f000] [send] via NET/IB/0
[4] NCCL INFO Channel 00 : 3[1e000] -> 12[3d000] [receive] via NET/IB/0
[4] NCCL INFO Channel 00 : 5[3f000] -> 12[3d000] [receive] via NET/IB/0
[4] NCCL INFO Channel 01 : 3[1e000] -> 12[3d000] [receive] via NET/IB/0
[5] NCCL INFO Channel 01 : 13[3f000] -> 4[3d000] [send] via NET/IB/0
[5] NCCL INFO Channel 01 : 4[3d000] -> 13[3f000] [receive] via NET/IB/0

And, as far as our environment is concerned, is it optimal for only GPU 4, GPU 5, GPU 6 and GPU 7 to participate in the connection through the NET when GDR was enabled?

**Comment by sjeaugey** [comment]
By default on PCI platforms we only use GPU Direct RDMA to receive, not to send. So we try to start with GPUs close to the NIC, and send from a distant GPU. Hence in your case start with GPU 4-7, then go through GPU 0-3.

**Comment by weberxie** [comment]
> By default on PCI platforms we only use GPU Direct RDMA to receive, not to send. 

Why we don't send data with GPU Direct RDMA?

And as far as our environment is concerned, which topo should get the optimal performance?

Thanks.

**Comment by sjeaugey** [comment]
> Why we don't send data with GPU Direct RDMA?
Performance is just better that way, and going through the CPU in that direction can still achieve full bandwidth (GPU writing to CPU memory + NIC reading from CPU memory).

> And as far as our environment is concerned, which topo should get the optimal performance?
Receiving into a GPU close to the NIC (4,5,6 or 7) and sending from a GPU on the other side (0,1,2,3) should be optimal in your case. But some of your experiments didn't really match what I would have expected. That's why I asked whether you could play around with graph definitions and confirm what works well and what doesn't.

**Comment by weberxie** [comment]
> That's why I asked whether you could play around with graph definitions and confirm what works well and what doesn't.

Sorry for the late response, because of the policy of scheduler, I can't get the same PCIe topo as I tested before. the new topo is like this:
<img width="658" alt="Screen Shot 2020-10-21 at 3 36 31 PM" src="https://user-images.githubusercontent.com/3942083/96688028-40131c00-13b3-11eb-9cc4-83564f310ef0.png">

So, I ran the tests again with NCCL_ALGO=RING, the order is converted according to the new topo:

- 4, 5, 6, 7, 0, 1, 2, 3,  [Default] ~5 GB/s

- 4, 5, 6, 7, 0, 1, 2, 3,  [NCCL_NET_GDR_READ=1] 8 GB/s

- 0, 1, 2, 3, 4, 5, 6, 7,  [Graph.txt] 8.1 GB/s

- 0, 1, 2, 3, 7, 6, 5, 4 [Patched] ~6.4 GB/s


>  Performance is just better that way, and going through the CPU in that direction can still achieve full bandwidth (GPU writing to CPU memory + NIC reading from CPU memory).

Forgive my poor background on PCIe architecture, could you explain it in detail why that direction can achieve full bandwidth?
Out of curiosity, I tested it by set the Graph.txt to  0, 1, 4, 5, 6, 7, 2, 3, with NCCL_NET_GDR_READ=1 and NCCL_ALGO=RING then the result shows that peek bandwidth is only about 4.5 GB/s, and the nccl logs show that all send and receive are all with GDRDMA. It conform your conclusion by it is hard to understand.

Thank you!

**Comment by weberxie** [comment]
@sjeaugey Hi Sylvain, could take a look at my last update? Thank you.

**Comment by sjeaugey** [comment]
In the case of the topology you showed above, if the NIC is on the first socket, so NCCL should work fine and receive data on 0,1,2,3 first, then move to 4,5,6,7 then exit the node.

I'm not sure what you ran since the default on such a system should be 0,1,2,3,4,5,6,7, and should be optimal.

On a PCI node, the optimal way to use every PCI link only once in each direction is this :
![PCI-Rings-200](https://user-images.githubusercontent.com/12857445/97028982-a615b580-1511-11eb-9f10-af87fbf9b24c.png)

Going through 0,1,4,5,6,7,2,3 (with GDR) should be equivalent but in practice is not as fast. Sending from CPU memory is always optimized and therefore it is usually better than sending directly from a GPU.

And there isn't anything to understand about PCI. In theory we should have the same performance in one direction or the other, or even opening the ring in the middle of the PCI switch (as you did). It's just how it is (which makes our life hard when trying to guess which ring will perform better).

**Comment by weberxie** [comment]
Thank you Sylvain.
