### ISSUE TITLE
can't get access to infiniband device with nccl in a docker container

### ISSUE THREAD

**Issue by benywon** [NVIDIA/nccl#451]
Hi there. recently I use the nccl inside a docker container for Microsoft deepspeed training. My host has the following rdma device:

Infiniband device 'mlx5_bond_0' port 1 status:
        default gid:     fe80:0000:0000:0000:0e42:a1ff:fe9a:6766
        base lid:        0x0
        sm lid:          0x0
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            25 Gb/sec (1X EDR)
        link_layer:      Ethernet

and I start the program inside the docker  container with  
```
export NCCL_DEBUG=info
export NCCL_IB_DISABLE=0
export NCCL_SOCKET_IFNAME=bond0
deepspeed train.py xxxxx
```
but I got the following nccl information:

NCCL INFO NCCL_IB_DISABLE set by environment to 0.
misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
transport/net_ib.cc:148 NCCL WARN NET/IB : Unable to open device mlx5_bond_0
NCCL INFO NET/IB : No device found.
NCCL INFO NET/Socket : Using [0]bond0:200.1.93.2<0>
NCCL INFO Using network Socket
NCCL INFO Bootstrap : Using [0]bond0:200.1.93.2<0>
NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
NCCL INFO NCCL_IB_DISABLE set by environment to 0.

and the distributed program executed extremely slow. Is there any way to make the docker container aware of the rdma IB device? I run the docker by the following command:

docker run -it --rm --ipc=host --gpus all  --network="host" -d -m 300G -w /search -v /home:/home deepspeed/deepspeed

Appreciate your help!!!

**Comment by sjeaugey** [comment]
There should be a way to use the NIC inside the container, but that's probably a question for docker experts.
The line :
```
transport/net_ib.cc:148 NCCL WARN NET/IB : Unable to open device mlx5_bond_0
```
Shows that we failed to open the IBV interface, probably due to missing rights. You can try running the IB perf tests to check whether low-level tests work, for example `ib_write_bw`.

**Comment by benywon** [comment]
After installing the Infiniband software inside the container the problem has been solved, thanks

**Comment by GeorgeSen** [comment]
@benywon How to install  the Infiniband software ?  Thank you!

**Comment by bogan-FMA** [comment]
> @benywon How to install the Infiniband software ? Thank you!

seems many people asked: just follow the inifiband hw provider's manual will do, like ofed for mlnx. or just use RDMA-core also work.
