### ISSUE TITLE
[Rem Allocator] Poll failed with error 1

### ISSUE THREAD

**Issue by crccw** [NVIDIA/nccl#472]
Hi, 

We've run into a bunch of hanging issues with NCCL. We saw the following warnings with NCCL_DEBUG=INFO

NCCL WARN [Rem Allocator] Poll failed with error 1

Could this lead to hanging? or is it just a red herring?

**Comment by sjeaugey** [comment]
Could be a side effect indeed, or a real problem.

What is the platform you are using? The remote allocator is only used to do send/receive between GPUs which do not have a direct NVLink connection but can communicate through an intermediate GPU (e.g. DGX-1). Are you doing something like that ?

**Comment by crccw** [comment]
It turns out to be a red herring. Thanks for the prompt response!
