### ISSUE TITLE
Test NCCL failure common.cu:777 'unhandled system error'

### ISSUE THREAD

**Issue by Co1lin** [NVIDIA/nccl#473]
I have installed NCCL by apt:
```
libnccl-dev/unknown,now 2.8.4-1+cuda11.2 amd64 [installed]
libnccl2/unknown,now 2.8.4-1+cuda11.2 amd64 [installed]
```

However, when I ran [NCCL_tests](https://github.com/NVIDIA/nccl-tests), I got an error:
```
# nThread 1 nGpus 4 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid   1688 on    fastmoe device  0 [0x18] GeForce RTX 2080 Ti
#   Rank  1 Pid   1688 on    fastmoe device  1 [0x3b] GeForce RTX 2080 Ti
#   Rank  2 Pid   1688 on    fastmoe device  2 [0x86] GeForce RTX 2080 Ti
#   Rank  3 Pid   1688 on    fastmoe device  3 [0xaf] GeForce RTX 2080 Ti
fastmoe: Test NCCL failure common.cu:777 'unhandled system error'
```
(fasemoe is the name of my conda env.)

Similar problem happened when I run a model which uses NCCL. I got this:
```
RuntimeError: NCCL Error 2: unhandled system error
```

It seems that though NCCL is installed, it can't work.

**Comment by Co1lin** [comment]
I know how to address this issue. This is a problem of shared memory in docker containers. After run the docker with `--ipc=host`, the error disappeared. [Reference](https://discuss.pytorch.org/t/problem-in-dataprallel-for-more-than-2-gpus/103373)
