### ISSUE TITLE
No interface found in the same subnet as remote address

### ISSUE THREAD

**Issue by xutianming** [NVIDIA/nccl#474]
![image](https://user-images.githubusercontent.com/4970790/110289190-0a01cc00-8024-11eb-9546-788b924f0308.png)

I was testing distributed NCCL on 2 machines. The ip addresses are 10.136.80.18 and 10.136.80.68 (netmask 255.255.255.192). They are indeed on different subnets.

Why NCCL restricts this ?

I also tried remove this restriction and it worked well.

**Comment by kwen2501** [comment]
Hi, is `NCCL_COMM_ID` set? If this environment variable is set, all ranks of NCCL would look for socket interfaces that are in the same subnet as the `NCCL_COMM_ID`. Do you have a bootstrap problem if not setting this environment variable?

**Comment by xutianming** [comment]
@kwen2501 Yes, NCCL_COMM_ID is set for multi-host bootstrap, otherwise I have to broadcast ncclUniqueId.

**Comment by kwen2501** [comment]
Part of the intent of `NCCL_COMM_ID` is for nodes with multiple network interfaces to agree on which interface (subnet) to use. So it indeed does not fit into your use case.

Are you using a NAT service between the subnets? I wonder if you could pass different `NCCL_COMM_ID`'s to the nodes in the two subnets. For nodes in the same subnet as node 0, you can use the IP address of node 0 in its own subnet; for nodes in the other subnet, perhaps you can pass an IP address of node 0 that is NAT translated?

**Comment by BinhangYuan** [comment]
> ![image](https://user-images.githubusercontent.com/4970790/110289190-0a01cc00-8024-11eb-9546-788b924f0308.png)
> 
> I was testing distributed NCCL on 2 machines. The ip addresses are 10.136.80.18 and 10.136.80.68 (netmask 255.255.255.192). They are indeed on different subnets.
> 
> Why NCCL restricts this ?
> 
> I also tried remove this restriction and it worked well.

May I ask what do you mean by "remove this restriction"? By manually changing the NCCL code in socket.h/cc and init.h/cc and recompile it or setting some environment variable? I am also trying to connecting two GPU instances in two different regions, and NCCL reports exactly the same issue as the figure you put it here. I really appreciate your help!
