### ISSUE TITLE
About internal functions of nccl operators

### ISSUE THREAD

**Issue by Youhe-Jiang** [NVIDIA/nccl#517]
Hello, I am a senior undergraduate and want to ask one simple question. As far as I know, the double binary tree algorithm has been added to the nccl_allreduce operator after 2.4, allowing users to determine whether to use the tree algorithm based on conditions when calling the allreduce operator. My question is: Are similar optimization algorithms added to other nccl operators? Thank you very much and look forward to your answer!

**Comment by sjeaugey** [comment]
The tree algorithm has indeed been added in 2.4, only for allreduce and not for others (and we don't have plans currently to add new algorithms to others).

That said, I'm not sure why you mention that users can choose to use tree or not when calling the allreduce operator, given this is actually not something users have control upon from the API (NCCL will use both algorithms depending on various factors).

**Comment by Youhe-Jiang** [comment]
> The tree algorithm has indeed been added in 2.4, only for allreduce and not for others (and we don't have plans currently to add new algorithms to others).
> 
> That said, I'm not sure why you mention that users can choose to use tree or not when calling the allreduce operator, given this is actually not something users have control upon from the API (NCCL will use both algorithms depending on various factors).



Thank you very much for your detailed and timely answer, which perfectly solved my problem！

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
