### ISSUE TITLE
NCCL WARN NET/IB : collective mismatch error

### ISSUE THREAD

**Issue by eric-haibin-lin** [NVIDIA/nccl#531]
Hi, 

I am running a PyTorch application which uses reduce_scatter and allgather on 2 nodes. However, I get the following warning on the first iteration and the program hangs

```
n136-081-017:201805:201927 [0] transport/net_ib.cc:667 NCCL WARN NET/IB : collective mismatch error local size 32768 remote 1048576 addr 0 rkey 3beac3 seq adf/adf
```

The complete logs with DEBUG_SUBSYSTEM=all are attached. The last few lines are: 

worker0
```
n136-081-019:212537:212537 [5] NCCL INFO AllGather: opCount f7 sendbuff 0x7fe4147b2a00 recvbuff 0x7fe4147b4000 count 512 datatype 0 op 0 root 0 comm 0x7fe40c030110 [nranks=16] stream 0x762db40
n136-081-019:212540:212540 [6] NCCL INFO AllGather: opCount f7 sendbuff 0x7efcba78da00 recvbuff 0x7efcba78ee00 count 512 datatype 0 op 0 root 0 comm 0x7efcb4030110 [nranks=16] stream 0x64d2f60
n136-081-019:212528:212528 [0] NCCL INFO AllGather: opCount f7 sendbuff 0x7f0f0078a600 recvbuff 0x7f0f0078c600 count 512 datatype 0 op 0 root 0 comm 0x7f0efc001060 [nranks=16] stream 0x6f12340
n136-081-019:212529:212529 [1] NCCL INFO AllGather: opCount f7 sendbuff 0x7fa128786c00 recvbuff 0x7fa128791e00 count 512 datatype 0 op 0 root 0 comm 0x7fa124030110 [nranks=16] stream 0x72cff40
n136-081-019:212530:212530 [2] NCCL INFO AllGather: opCount f7 sendbuff 0x7f9f54787600 recvbuff 0x7f9f547c4000 count 512 datatype 0 op 0 root 0 comm 0x7f9f4c030110 [nranks=16] stream 0x6724ad0
n136-081-019:212531:212531 [3] NCCL INFO AllGather: opCount f7 sendbuff 0x7f548a7e5e00 recvbuff 0x7f548a7e7800 count 512 datatype 0 op 0 root 0 comm 0x7f5484030110 [nranks=16] stream 0x6fe65b0
n136-081-019:212534:212534 [4] NCCL INFO AllGather: opCount f7 sendbuff 0x7f8976787a00 recvbuff 0x7f89767c4000 count 512 datatype 0 op 0 root 0 comm 0x7f8970030110 [nranks=16] stream 0x6481c40
n136-081-019:212543:212543 [7] NCCL INFO AllGather: opCount f7 sendbuff 0x7f837a792e00 recvbuff 0x7f837a794000 count 512 datatype 0 op 0 root 0 comm 0x7f8374030110 [nranks=16] stream 0x6cd1b50
n136-081-019:212540:212540 [6] NCCL INFO AllGather: opCount f8 sendbuff 0x7efcc1c50000 recvbuff 0x7efcc2150000 count 524288 datatype 0 op 0 root 0 comm 0x7efcb4030110 [nranks=16] stream 0x64d2f60
n136-081-019:212537:212537 [5] NCCL INFO AllGather: opCount f8 sendbuff 0x7fe3adbd0000 recvbuff 0x7fe3ae150000 count 524288 datatype 0 op 0 root 0 comm 0x7fe40c030110 [nranks=16] stream 0x762db40
n136-081-019:212528:212528 [0] NCCL INFO AllGather: opCount f8 sendbuff 0x7f0f17950000 recvbuff 0x7f0f18150000 count 524288 datatype 0 op 0 root 0 comm 0x7f0efc001060 [nranks=16] stream 0x6f12340
n136-081-019:212529:212529 [1] NCCL INFO AllGather: opCount f8 sendbuff 0x7fa1439d0000 recvbuff 0x7fa144150000 count 524288 datatype 0 op 0 root 0 comm 0x7fa124030110 [nranks=16] stream 0x72cff40
n136-081-019:212530:212530 [2] NCCL INFO AllGather: opCount f8 sendbuff 0x7f9f17a50000 recvbuff 0x7f9f18150000 count 524288 datatype 0 op 0 root 0 comm 0x7f9f4c030110 [nranks=16] stream 0x6724ad0
n136-081-019:212531:212531 [3] NCCL INFO AllGather: opCount f8 sendbuff 0x7f54bfad0000 recvbuff 0x7f54c0150000 count 524288 datatype 0 op 0 root 0 comm 0x7f5484030110 [nranks=16] stream 0x6fe65b0
n136-081-019:212534:212534 [4] NCCL INFO AllGather: opCount f8 sendbuff 0x7f89adb50000 recvbuff 0x7f89ae150000 count 524288 datatype 0 op 0 root 0 comm 0x7f8970030110 [nranks=16] stream 0x6481c40
n136-081-019:212543:212543 [7] NCCL INFO AllGather: opCount f8 sendbuff 0x7f8395cd0000 recvbuff 0x7f8396150000 count 524288 datatype 0 op 0 root 0 comm 0x7f8374030110 [nranks=16] stream 0x6cd1b50
n136-081-019:212540:212540 [6] NCCL INFO AllGather: opCount f9 sendbuff 0x7efcc2c50000 recvbuff 0x7efccfd20000 count 524288 datatype 0 op 0 root 0 comm 0x7efcb4030110 [nranks=16] stream 0x64d2f60
n136-081-019:212537:212537 [5] NCCL INFO AllGather: opCount f9 sendbuff 0x7fe3aebd0000 recvbuff 0x7fe3bbd20000 count 524288 datatype 0 op 0 root 0 comm 0x7fe40c030110 [nranks=16] stream 0x762db40
n136-081-019:212528:212528 [0] NCCL INFO AllGather: opCount f9 sendbuff 0x7f0f18950000 recvbuff 0x7f0f25d20000 count 524288 datatype 0 op 0 root 0 comm 0x7f0efc001060 [nranks=16] stream 0x6f12340
n136-081-019:212529:212529 [1] NCCL INFO AllGather: opCount f9 sendbuff 0x7fa1449d0000 recvbuff 0x7fa151d20000 count 524288 datatype 0 op 0 root 0 comm 0x7fa124030110 [nranks=16] stream 0x72cff40
n136-081-019:212530:212530 [2] NCCL INFO AllGather: opCount f9 sendbuff 0x7f9f18a50000 recvbuff 0x7f9f25d20000 count 524288 datatype 0 op 0 root 0 comm 0x7f9f4c030110 [nranks=16] stream 0x6724ad0
n136-081-019:212531:212531 [3] NCCL INFO AllGather: opCount f9 sendbuff 0x7f54c0ad0000 recvbuff 0x7f54cdd20000 count 524288 datatype 0 op 0 root 0 comm 0x7f5484030110 [nranks=16] stream 0x6fe65b0
n136-081-019:212543:212543 [7] NCCL INFO AllGather: opCount f9 sendbuff 0x7f8396cd0000 recvbuff 0x7f83a3d20000 count 524288 datatype 0 op 0 root 0 comm 0x7f8374030110 [nranks=16] stream 0x6cd1b50
n136-081-019:212534:212534 [4] NCCL INFO AllGather: opCount f9 sendbuff 0x7f89aeb50000 recvbuff 0x7f89bbd20000 count 524288 datatype 0 op 0 root 0 comm 0x7f8970030110 [nranks=16] stream 0x6481c40
n136-081-019:212540:212540 [6] NCCL INFO AllGather: opCount fa sendbuff 0x7efcba7ebb00 recvbuff 0x7efcba790e00 count 128 datatype 0 op 0 root 0 comm 0x7efcb4030110 [nranks=16] stream 0x64d2f60
n136-081-019:212537:212537 [5] NCCL INFO AllGather: opCount fa sendbuff 0x7fe4147b6280 recvbuff 0x7fe4147eee00 count 128 datatype 0 op 0 root 0 comm 0x7fe40c030110 [nranks=16] stream 0x762db40
n136-081-019:212543:212543 [7] NCCL INFO AllGather: opCount fa sendbuff 0x7f837a7ec980 recvbuff 0x7f837a78ee00 count 128 datatype 0 op 0 root 0 comm 0x7f8374030110 [nranks=16] stream 0x6cd1b50

```

worker1
```
n136-081-017:201800:201800 [2] NCCL INFO AllGather: opCount f7 sendbuff 0x7f33f878be00 recvbuff 0x7f33f878ca00 count 512 datatype 0 op 0 root 0 comm 0x7f33f4030110 [nranks=16] stream 0x9cd23f10
n136-081-017:201799:201799 [1] NCCL INFO AllGather: opCount f7 sendbuff 0x7fe39c78f200 recvbuff 0x7fe39c789600 count 512 datatype 0 op 0 root 0 comm 0x7fe398030110 [nranks=16] stream 0x681e0e0
n136-081-017:201802:201802 [4] NCCL INFO AllGather: opCount f7 sendbuff 0x7fdaee7c7800 recvbuff 0x7fdaee7c8000 count 512 datatype 0 op 0 root 0 comm 0x7fdae8030110 [nranks=16] stream 0x714eca0
n136-081-017:201811:201811 [7] NCCL INFO AllGather: opCount f7 sendbuff 0x7efbe07de600 recvbuff 0x7efbe07de800 count 512 datatype 0 op 0 root 0 comm 0x7efbd8030110 [nranks=16] stream 0x6983f90
n136-081-017:201805:201805 [5] NCCL INFO AllGather: opCount f7 sendbuff 0x7efb6a788c00 recvbuff 0x7efb6a7c4000 count 512 datatype 0 op 0 root 0 comm 0x7efb60030110 [nranks=16] stream 0x6df7460
n136-081-017:201808:201808 [6] NCCL INFO AllGather: opCount f7 sendbuff 0x7fe35c78d400 recvbuff 0x7fe35c78d800 count 512 datatype 0 op 0 root 0 comm 0x7fe32c030110 [nranks=16] stream 0x79a5d50
n136-081-017:201798:201798 [0] NCCL INFO AllGather: opCount f7 sendbuff 0x7fae4e78de00 recvbuff 0x7fae4e78ee00 count 512 datatype 0 op 0 root 0 comm 0x7fae48030110 [nranks=16] stream 0x76a17d0
n136-081-017:201801:201801 [3] NCCL INFO AllGather: opCount f7 sendbuff 0x7f82a07c7600 recvbuff 0x7f82a07c8000 count 512 datatype 0 op 0 root 0 comm 0x7f829c030110 [nranks=16] stream 0x9f3f1860
n136-081-017:201800:201800 [2] NCCL INFO AllGather: opCount f8 sendbuff 0x7f3407e50000 recvbuff 0x7f3408150000 count 524288 datatype 0 op 0 root 0 comm 0x7f33f4030110 [nranks=16] stream 0x9cd23f10
n136-081-017:201799:201799 [1] NCCL INFO AllGather: opCount f8 sendbuff 0x7fe3d1dd0000 recvbuff 0x7fe3d2150000 count 524288 datatype 0 op 0 root 0 comm 0x7fe398030110 [nranks=16] stream 0x681e0e0
n136-081-017:201802:201802 [4] NCCL INFO AllGather: opCount f8 sendbuff 0x7fda8ff50000 recvbuff 0x7fda90150000 count 524288 datatype 0 op 0 root 0 comm 0x7fdae8030110 [nranks=16] stream 0x714eca0
n136-081-017:201811:201811 [7] NCCL INFO AllGather: opCount f8 sendbuff 0x7efc060d0000 recvbuff 0x7efc06150000 count 524288 datatype 0 op 0 root 0 comm 0x7efbd8030110 [nranks=16] stream 0x6983f90
n136-081-017:201808:201808 [6] NCCL INFO AllGather: opCount f8 sendbuff 0x7fe334050000 recvbuff 0x7fe334150000 count 524288 datatype 0 op 0 root 0 comm 0x7fe32c030110 [nranks=16] stream 0x79a5d50
n136-081-017:201805:201805 [5] NCCL INFO AllGather: opCount f8 sendbuff 0x7efafdfd0000 recvbuff 0x7efafe150000 count 524288 datatype 0 op 0 root 0 comm 0x7efb60030110 [nranks=16] stream 0x6df7460
n136-081-017:201798:201798 [0] NCCL INFO AllGather: opCount f8 sendbuff 0x7fae5fd50000 recvbuff 0x7fae60150000 count 524288 datatype 0 op 0 root 0 comm 0x7fae48030110 [nranks=16] stream 0x76a17d0
n136-081-017:201801:201801 [3] NCCL INFO AllGather: opCount f8 sendbuff 0x7f82a5ed0000 recvbuff 0x7f82a6150000 count 524288 datatype 0 op 0 root 0 comm 0x7f829c030110 [nranks=16] stream 0x9f3f1860
n136-081-017:201808:201808 [6] NCCL INFO AllGather: opCount f9 sendbuff 0x7fe335050000 recvbuff 0x7fe341d20000 count 524288 datatype 0 op 0 root 0 comm 0x7fe32c030110 [nranks=16] stream 0x79a5d50
n136-081-017:201805:201805 [5] NCCL INFO AllGather: opCount f9 sendbuff 0x7efafefd0000 recvbuff 0x7efb0bd20000 count 524288 datatype 0 op 0 root 0 comm 0x7efb60030110 [nranks=16] stream 0x6df7460
n136-081-017:201798:201798 [0] NCCL INFO AllGather: opCount f9 sendbuff 0x7fae60d50000 recvbuff 0x7fae6dd20000 count 524288 datatype 0 op 0 root 0 comm 0x7fae48030110 [nranks=16] stream 0x76a17d0
n136-081-017:201799:201799 [1] NCCL INFO AllGather: opCount f9 sendbuff 0x7fe3d2dd0000 recvbuff 0x7fe3dfd20000 count 524288 datatype 0 op 0 root 0 comm 0x7fe398030110 [nranks=16] stream 0x681e0e0
n136-081-017:201800:201800 [2] NCCL INFO AllGather: opCount f9 sendbuff 0x7f3408e50000 recvbuff 0x7f3415d20000 count 524288 datatype 0 op 0 root 0 comm 0x7f33f4030110 [nranks=16] stream 0x9cd23f10
n136-081-017:201801:201801 [3] NCCL INFO AllGather: opCount f9 sendbuff 0x7f82a6ed0000 recvbuff 0x7f82b3d20000 count 524288 datatype 0 op 0 root 0 comm 0x7f829c030110 [nranks=16] stream 0x9f3f1860
n136-081-017:201811:201811 [7] NCCL INFO AllGather: opCount f9 sendbuff 0x7efc070d0000 recvbuff 0x7efc13d20000 count 524288 datatype 0 op 0 root 0 comm 0x7efbd8030110 [nranks=16] stream 0x6983f90
n136-081-017:201802:201802 [4] NCCL INFO AllGather: opCount f9 sendbuff 0x7fda90f50000 recvbuff 0x7fda9dd20000 count 524288 datatype 0 op 0 root 0 comm 0x7fdae8030110 [nranks=16] stream 0x714eca0

n136-081-017:201805:201927 [0] transport/net_ib.cc:667 NCCL WARN NET/IB : collective mismatch error local size 32768 remote 1048576 addr 0 rkey 3beac3 seq adf/adf
n136-081-017:201805:201927 [0] NCCL INFO include/net.h:25 -> 3
n136-081-017:201805:201927 [0] NCCL INFO transport/net.cc:296 -> 3
n136-081-017:201805:201927 [0] NCCL INFO proxy.cc:198 -> 3 [Proxy Thread]
n136-081-017:201798:201798 [0] NCCL INFO AllGather: opCount fa sendbuff 0x7fae4e7ebc00 recvbuff 0x7fae4e790e00 count 128 datatype 0 op 0 root 0 comm 0x7fae48030110 [nranks=16] stream 0x76a17d0
n136-081-017:201799:201799 [1] NCCL INFO AllGather: opCount fa sendbuff 0x7fe39c78ba80 recvbuff 0x7fe39c78be00 count 128 datatype 0 op 0 root 0 comm 0x7fe398030110 [nranks=16] stream 0x681e0e0
n136-081-017:201800:201800 [2] NCCL INFO AllGather: opCount fa sendbuff 0x7f33f8789700 recvbuff 0x7f33f878ea00 count 128 datatype 0 op 0 root 0 comm 0x7f33f4030110 [nranks=16] stream 0x9cd23f10
n136-081-017:201801:201801 [3] NCCL INFO AllGather: opCount fa sendbuff 0x7f82a07ecb80 recvbuff 0x7f82a07ca000 count 128 datatype 0 op 0 root 0 comm 0x7f829c030110 [nranks=16] stream 0x9f3f1860
n136-081-017:201802:201802 [4] NCCL INFO AllGather: opCount fa sendbuff 0x7fdaee7ecc00 recvbuff 0x7fdaee7ca000 count 128 datatype 0 op 0 root 0 comm 0x7fdae8030110 [nranks=16] stream 0x714eca0

```

I cannot see where the 32768 v.s. 1048576 mismatch comes from. Any suggestion/help is appreciated. Thanks! 

[work1(1).log](https://github.com/NVIDIA/nccl/files/6759109/work1.1.log)
[work0(1).log](https://github.com/NVIDIA/nccl/files/6759110/work0.1.log)

BTW - I am also curious why `datatype` is shown as 0 here - according to the code that corresponds to uint8/char https://github.com/NVIDIA/nccl/blob/a46ea105830fbc3fbb222a00a82862df49cc9a9f/src/nccl.h.in#L109-L118 but I am most likely using float16 or float32 in the application. Is that expected?

**Comment by eric-haibin-lin** [comment]
BTW - I also see `n136-081-017:235998:236110 [7] NCCL INFO Attribute coll of node net not found` from the log. Is this abnormal?

**Comment by eric-haibin-lin** [comment]
The nccl version used is `NCCL version 2.7.8+cuda11.0`

**Comment by sjeaugey** [comment]
Did you force relaxed ordering on the NIC by any chance (see [here](https://hpcadvisorycouncil.atlassian.net/wiki/spaces/HPCWORKS/pages/1280442391/AMD+2nd+Gen+EPYC+CPU+Tuning+Guide+for+InfiniBand+HPC) how to check the relaxed ordering setting on your NIC) ?

If so, please try setting it back to the default "per_mkey(0)" so that libraries can use relaxed ordering only when they support it and let us know if that fixes the issue.

Thanks!

**Comment by eric-haibin-lin** [comment]
Hi @sjeaugey , thanks for the reply! We indeed changed relaxed ordering configuration for the machine for CPU RDMA performance. I'll check if disabling that can help fix the issue from NCCL. Although that is not a solution for our platform since disabling it would make the performance of some applications worse. By any chance newer versions of NCCL support relaxed ordering / avoids such bugs caused by relaxed ordering?

**Comment by sjeaugey** [comment]
The default setting (per_mkey) allows applications to use relaxed ordering. It's just not forced for all traffic, but opt-in for each transfer. For example, UCX has a parameter to use relaxed ordering so if you are using MPI with UCX, you should be able to use relaxed ordering even with that default configuration.

**Comment by AddyLaddy** [comment]
NCCL 2.8.x and later are more tolerant to Relaxed Ordering being enabled by default using the `force_relax(1) ` NIC setting. But we still recommend that users should leave that setting as `per_mkey(0)` so that individual applications and libraries can enable Relaxed Ordering, if they support it.
For NCCL that can be achieved by using the Mellanox NCCL plugin module; [nccl-rdma-sharp-plugins](https://github.com/Mellanox/nccl-rdma-sharp-plugins.git)
And then setting `NCCL_IB_PCI_RELAXED_ORDERING=1` in the job environment when using the default IB verbs protocol.

**Comment by eric-haibin-lin** [comment]
Thanks. The issue is resolved after I upgrade NCCL.

**Comment by guozhiyao** [comment]
> Thanks. The issue is resolved after I upgrade NCCL.

I meet the same problem as you. Could you please tell me what version of your NCCL now?

**Comment by guozhiyao** [comment]
> > Thanks. The issue is resolved after I upgrade NCCL.
> 
> I meet the same problem as you. Could you please tell me what version of your NCCL now?

@eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
> > > Thanks. The issue is resolved after I upgrade NCCL.
> 
> > 
> 
> > I meet the same problem as you. Could you please tell me what version of your NCCL now?
> 
> 
> 
> @eric-haibin-lin 

2.8.3

**Comment by guozhiyao** [comment]
> [sjeaugey](/sjeaugey)

Thanks for you reply. I try to set `export NCCL_IB_DISABLE=1` and it works. Will it have an impact on performance?

**Comment by guozhiyao** [comment]
> > > > Thanks. The issue is resolved after I upgrade NCCL.
> > 
> > 
> > > 
> > 
> > 
> > > I meet the same problem as you. Could you please tell me what version of your NCCL now?
> > 
> > 
> > @eric-haibin-lin
> 
> 2.8.3

Thanks for you reply. I try to set export NCCL_IB_DISABLE=1 and it works. Will it have an impact on performance?
