### ISSUE TITLE
Specify device_ids in barrier() to force use of a particular device

### ISSUE THREAD

**Issue by StevanCakic** [NVIDIA/nccl#541]
I have a problem running the torch spawn function from mp (multiprocessing module) on [Slurm ](https://slurm.schedmd.com/documentation.html) on multiple GPUs. I get some errors/warnings when activated NCCL debug mode.

## Instructions To Reproduce the Issue:

1. Full runnable code:

```python
import torch, os

def test_nccl_ops():
    num_gpu = 2
    print("NCCL init before spawn")
    import torch.multiprocessing as mp
    dist_url = "file:///tmp/nccl_tmp_file"
    mp.spawn(_test_nccl_worker, nprocs=num_gpu, args=(num_gpu, dist_url), daemon=False)
    print("NCCL init succeeded.")


def _test_nccl_worker(rank, num_gpu, dist_url):
    import torch.distributed as dist

    dist.init_process_group(backend="NCCL", init_method=dist_url, rank=rank, world_size=num_gpu)
    dist.barrier()
    print("Worker after barrier")

if __name__ == "__main__":
    test_nccl_ops()

```

On the other hand, we implemented this Slurm script to run an experiment on 2 GPUs:
```bash
#!/bin/bash -l

#SBATCH --account=Account
#SBATCH --partition=gpu # gpu partition
#SBATCH --nodes=1 # 1 node, 4 GPUs per node
#SBATCH --time=24:00:00 
#SBATCH --job-name=detectron2_demo4 # job name



module load Python/3.9.5-GCCcore-10.3.0
module load CUDA/11.1.1-GCC-10.2.0

cd /experiment_path

export NCCL_DEBUG=INFO

srun python main.py --num-gpus 2
```

When I ran this script I faced an error (cat slurm-xxx.out), and no error file:
```
The following have been reloaded with a version change:
  1) GCCcore/10.3.0 => GCCcore/10.2.0
  2) binutils/2.36.1-GCCcore-10.3.0 => binutils/2.35-GCCcore-10.2.0
  3) zlib/1.2.11-GCCcore-10.3.0 => zlib/1.2.11-GCCcore-10.2.0

NCCL init before spawn
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
gpu04:9770:9770 [0] NCCL INFO Bootstrap : Using [0]bond0:10.10.1.4<0>
gpu04:9770:9770 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu04:9770:9770 [0] NCCL INFO NET/IB : No device found.
gpu04:9770:9770 [0] NCCL INFO NET/Socket : Using [0]bond0:10.10.1.4<0>
gpu04:9770:9770 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
gpu04:9771:9771 [1] NCCL INFO Bootstrap : Using [0]bond0:10.10.1.4<0>
gpu04:9771:9771 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu04:9771:9771 [1] NCCL INFO NET/IB : No device found.
gpu04:9771:9771 [1] NCCL INFO NET/Socket : Using [0]bond0:10.10.1.4<0>
gpu04:9771:9771 [1] NCCL INFO Using network Socket
gpu04:9771:9862 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
gpu04:9771:9862 [1] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
gpu04:9771:9862 [1] NCCL INFO Setting affinity for GPU 1 to 3fff
gpu04:9770:9861 [0] NCCL INFO Channel 00/02 :    0   1
gpu04:9770:9861 [0] NCCL INFO Channel 01/02 :    0   1
gpu04:9770:9861 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
gpu04:9770:9861 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
gpu04:9770:9861 [0] NCCL INFO Setting affinity for GPU 0 to 3fff
gpu04:9771:9862 [1] NCCL INFO Channel 00 : 1[6000] -> 0[5000] via P2P/IPC
gpu04:9770:9861 [0] NCCL INFO Channel 00 : 0[5000] -> 1[6000] via P2P/IPC
gpu04:9771:9862 [1] NCCL INFO Channel 01 : 1[6000] -> 0[5000] via P2P/IPC
gpu04:9770:9861 [0] NCCL INFO Channel 01 : 0[5000] -> 1[6000] via P2P/IPC
gpu04:9771:9862 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
gpu04:9771:9862 [1] NCCL INFO comm 0x7f057c000e00 rank 1 nranks 2 cudaDev 1 busId 6000 - Init COMPLETE
gpu04:9770:9861 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
gpu04:9770:9861 [0] NCCL INFO comm 0x7f5210000e00 rank 0 nranks 2 cudaDev 0 busId 5000 - Init COMPLETE
gpu04:9770:9770 [0] NCCL INFO Launch mode Parallel


```
## Expected behavior:

To run training on 2 GPUs and print other more outputs then "NCCL init before spawn" and NCCL debug info.

## Environment:

Paste the output of the following command:
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/software/CUDAcore/11.1.1'
---------------------  --------------------------------------------------------------------------------
sys.platform           linux
Python                 3.9.5 (default, Jul  9 2021, 09:35:24) [GCC 10.3.0]
numpy                  1.21.1
detectron2             0.5 @/home/users/aimhigh/detectron2/detectron2
Compiler               GCC 10.2
CUDA compiler          CUDA 11.1
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.9.0+cu102 @/home/users/aimhigh/.local/lib/python3.9/site-packages/torch
PyTorch debug build    False
GPU available          No: torch.cuda.is_available() == False
Pillow                 8.3.1
torchvision            0.10.0+cu102 @/home/users/aimhigh/.local/lib/python3.9/site-packages/torchvision
fvcore                 0.1.5.post20210727
iopath                 0.1.9
cv2                    4.5.3
---------------------  --------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2

```

**Additional note**: The first time I assumed it is a detectron2 problem but it's not. You can find my previous discussion with detectron2 developers: [link](https://github.com/facebookresearch/detectron2/issues/3319).

**Comment by sjeaugey** [comment]
I'm not sure I understand what the problem is and what error you are referring to. The NCCL initialization seems to complete correctly. There is no `WARN` in the log, only `INFO`, so everything seems fine.

Can you elaborate on what doesn't work the way it should?

**Comment by StevanCakic** [comment]
@sjeaugey These two lines are just a warning then (no critical error):
```
gpu04:9770:9770 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu04:9770:9770 [0] NCCL INFO NET/IB : No device found.
```
The problem is when call function **test_nccl_ops()** function stuck on this part (never get **NCCL init succeded.** in log):
mp.spawn(_test_nccl_worker, nprocs=num_gpu, args=(num_gpu, dist_url), daemon=False)
print("NCCL init succeeded.")

Maybe this is not the problem with NCCL, it's probably something with our Slurm configuration. First, we are investigated the problem with the [detectron2 team](https://github.com/facebookresearch/detectron2/issues/3319) (now we know this problem is not caused by their side). Now we are checking is it something with pyTorch or NCCL, or with our Slurm configuration or packages/system version incompatibilities.

**Comment by sjeaugey** [comment]
Yes, those two lines are just informational: no hardware specific plugin was found, and no Infiniband network adapter was found either. So we'll use TCP/IP sockets inter-node, if needed.

In the log, both ranks seem to exit from ncclCommInitRank:
```
gpu04:9771:9862 [1] NCCL INFO comm 0x7f057c000e00 rank 1 nranks 2 cudaDev 1 busId 6000 - Init COMPLETE
gpu04:9770:9861 [0] NCCL INFO comm 0x7f5210000e00 rank 0 nranks 2 cudaDev 0 busId 5000 - Init COMPLETE
```
So from our perspective, NCCL init is complete.

Now, this line is usually displayed during the first call to a NCCL collective operation:
```
gpu04:9770:9770 [0] NCCL INFO Launch mode Parallel
```
so I guess `test_nccl_ops()` is also launching some NCCL collective which could be hanging here, for example due to ACS being enabled (see [this link](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs)) or some other issue.

**Comment by StevanCakic** [comment]
@sjeaugey I will check it. I'm guessing we need to update slurm.conf file. We will ask our provider for assistance.

**Comment by MartaTintore** [comment]
I have the same problem. After setting NCCL_DEBUG=INFO I also get NCCL init complete:
```

{CLUSTER_NAME} [1] NCCL INFO Bootstrap : Using [0]ens1:100.96.172.173<0>
{CLUSTER_NAME} [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
{CLUSTER_NAME} [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB ; OOB ens1:100.96.172.173<0>
{CLUSTER_NAME} [1] NCCL INFO Using network IB
{CLUSTER_NAME} [1] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 8/8/64
{CLUSTER_NAME} [1] NCCL INFO Trees [0] 2/8/-1->1->0|0->1->2/8/-1 [1] 0/-1/-1->1->2|2->1->0/-1/-1 [2] 2/-1/-1->1->0|0->1->2/-1/-1 [3] 0/-1/-1->1->2|2->1->0/-1/-1
{CLUSTER_NAME} [1] NCCL INFO Channel 00 : 1[1d000] -> 8[1c000] [send] via NET/IB/0/GDRDMA
{CLUSTER_NAME} [1] NCCL INFO Channel 00 : 8[1c000] -> 1[1d000] [receive] via NET/IB/0/GDRDMA
{CLUSTER_NAME} [1] NCCL INFO Channel 00 : 1[1d000] -> 0[1c000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 00 : 1[1d000] -> 2[20000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 01 : 1[1d000] -> 5[40000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 01 : 1[1d000] -> 2[20000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 01 : 1[1d000] -> 0[1c000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 02 : 1[1d000] -> 8[1c000] [send] via NET/IB/0/GDRDMA
{CLUSTER_NAME} [1] NCCL INFO Channel 02 : 1[1d000] -> 0[1c000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 02 : 1[1d000] -> 2[20000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 03 : 1[1d000] -> 5[40000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 03 : 1[1d000] -> 2[20000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO Channel 03 : 1[1d000] -> 0[1c000] via P2P/IPC
{CLUSTER_NAME} [1] NCCL INFO 4 coll channels, 4 p2p channels, 1 p2p channels per peer
{CLUSTER_NAME} [1] NCCL INFO comm 0x7f1ee40010a0 rank 1 nranks 16 cudaDev 1 busId 1d000 - Init COMPLETE
```

I am specifying the number of gpus and number of nodes to the Trainer with:

```
trainer_kwargs["replace_sampler_ddp"] = True
            trainer_kwargs["num_nodes"] = opt.nodes
            trainer_kwargs["gpus"] = opt.ngpus
```

**Comment by sjeaugey** [comment]
@MartaTintore can you elaborate on what you experience? Is it a hang of the mp.spawn() function as well?

Perhaps it would be useful to first check whether NCCL works running the [NCCL perf tests](https://github.com/nvidia/nccl-tests)?

**Comment by StevanCakic** [comment]
It was a problem with the Slurm file. 
So, I solved it by attaching this code in Slurm file:

```bash
export NCCL_SOCKET_IFNAME=bond0
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
```

**Comment by sjeaugey** [comment]
Disabling IB/RoCE and P2P is going to severely degrade your performance.

Given you were only running on a single node, I would think what really solved your hang was `NCCL_P2P_DISABLE=1` and it would confirm my suspicion that ACS is enabled, breaking P2P.

> for example due to ACS being enabled (see [this link](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs)) or some other issue.
