### ISSUE TITLE
NCCL init failed within rdma-shared docker

### ISSUE THREAD

**Issue by lzha106** [NVIDIA/nccl#551]
Background:

We are trying to test NCCL communication within dockers on multi-nodes,  which is allocated via rdma-share plugin (https://github.com/Mellanox/k8s-rdma-shared-dev-plugin).
 
However it meets with below errors and failed to launch the `all_reduce_perf ` test.

```
gpunodev2:10770:10794 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error No such device
gpunodev2:10770:10794 [0] NCCL INFO transport/net_ib.cu:382 -> 2
gpunodev2:10770:10794 [0] NCCL INFO transport/net_ib.cu:485 -> 2
gpunodev2:10770:10794 [0] NCCL INFO include/net.h:28 -> 2
gpunodev2:10770:10794 [0] NCCL INFO transport/net.cu:380 -> 2
gpunodev2:10770:10794 [0] NCCL INFO init.cu:667 -> 2
gpunodev2:10770:10794 [0] NCCL INFO init.cu:803 -> 2
gpunodev2:10770:10794 [0] NCCL INFO init.cu:915 -> 2
gpunodev2:10770:10794 [0] NCCL INFO misc/group.cu:69 -> 2 [Async thread]
gpunodev2: Test NCCL failure common.cu:788 'unhandled system error'
```

Btw: the test runs successfully on local host but only failed within the rdma-shared docker. 

- NCCL Version： 2.4.2+cuda10.0
- Test command:

```
export NP=8
export NP_EACH_NODE=4
export GPUS_THREAD=1
mpirun -np $NP --allow-run-as-root -H 192.168.188.17:$NP_EACH_NODE,192.168.188.102:$NP_EACH_NODE --mca -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 -mca pml ob1 -mca btl ^openib -x LD_LIBRARY_PATH -x PATH /data/nccl-tests/build/all_reduce_perf -b 8 -e 128M -f 2 -g $GPUS_THREAD -c 0
```
- Network Interface

```
root@gpunodev1:/data/nccl-tests# ifconfig
eth0      Link encap:Ethernet  HWaddr e2:b3:9c:5f:4b:51
          inet addr:192.168.188.17  Bcast:192.168.188.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:988958 errors:0 dropped:0 overruns:0 frame:0
          TX packets:673259 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:19834160481 (19.8 GB)  TX bytes:20602593480 (20.6 GB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5267 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5267 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2298339 (2.2 MB)  TX bytes:2298339 (2.2 MB)
```

- Full log:

```
# nThread 1 nGpus 1 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 0
#
# Using devices
#   Rank  0 Pid  26300 on  gpunodev1 device  0 [0x1b] Tesla V100-PCIE-32GB
#   Rank  1 Pid  26301 on  gpunodev1 device  1 [0x62] Tesla V100-PCIE-32GB
#   Rank  2 Pid  26302 on  gpunodev1 device  2 [0x63] Tesla V100-PCIE-32GB
#   Rank  3 Pid  26303 on  gpunodev1 device  3 [0x64] Tesla V100-PCIE-32GB
#   Rank  4 Pid  10770 on  gpunodev2 device  0 [0x61] Tesla V100-PCIE-32GB
#   Rank  5 Pid  10771 on  gpunodev2 device  1 [0x62] Tesla V100-PCIE-32GB
#   Rank  6 Pid  10772 on  gpunodev2 device  2 [0x63] Tesla V100-PCIE-32GB
#   Rank  7 Pid  10773 on  gpunodev2 device  3 [0x64] Tesla V100-PCIE-32GB
gpunodev1:26300:26300 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.17<0>
gpunodev1:26300:26300 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev1:26300:26300 [0] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.17<0>
gpunodev2:10770:10770 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.102<0>
gpunodev2:10770:10770 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev2:10770:10770 [0] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.102<0>
gpunodev2:10771:10771 [1] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.102<0>
gpunodev2:10771:10771 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev2:10772:10772 [2] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.102<0>
gpunodev2:10772:10772 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev2:10773:10773 [3] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.102<0>
gpunodev2:10773:10773 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev1:26303:26303 [3] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.17<0>
gpunodev1:26303:26303 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev1:26303:26303 [3] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.17<0>
NCCL version 2.4.2+cuda10.0
gpunodev2:10771:10771 [1] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.102<0>
gpunodev2:10772:10772 [2] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.102<0>
gpunodev2:10773:10773 [3] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.102<0>
gpunodev1:26302:26302 [2] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.17<0>
gpunodev1:26302:26302 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev1:26301:26301 [1] NCCL INFO NET/Socket : Using [0]eth0:192.168.188.17<0>
gpunodev1:26301:26301 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
gpunodev1:26302:26302 [2] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.17<0>
gpunodev1:26301:26301 [1] NCCL INFO NET/IB : Using [0]mlx5_bond_0:1/RoCE ; OOB eth0:192.168.188.17<0>
gpunodev2:10770:10794 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
gpunodev2:10770:10794 [0] NCCL INFO comm 0x7f738c001d30 rank 4 nranks 8 cudaDev 0 nvmlDev 4
gpunodev1:26300:26325 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
gpunodev1:26300:26325 [0] NCCL INFO comm 0x7fc004001d30 rank 0 nranks 8 cudaDev 0 nvmlDev 0
gpunodev1:26301:26327 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff00,000fffff
gpunodev1:26301:26327 [1] NCCL INFO comm 0x7f2608001d30 rank 1 nranks 8 cudaDev 1 nvmlDev 5
gpunodev1:26303:26326 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff00,000fffff
gpunodev1:26303:26326 [3] NCCL INFO comm 0x7f616c001d30 rank 3 nranks 8 cudaDev 3 nvmlDev 7
gpunodev2:10773:10796 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff00,000fffff
gpunodev2:10773:10796 [3] NCCL INFO comm 0x7fd7ec001d30 rank 7 nranks 8 cudaDev 3 nvmlDev 7
gpunodev2:10772:10795 [2] NCCL INFO Setting affinity for GPU 2 to 0fffff00,000fffff
gpunodev2:10772:10795 [2] NCCL INFO comm 0x7f168c001d30 rank 6 nranks 8 cudaDev 2 nvmlDev 6
gpunodev2:10771:10797 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff00,000fffff
gpunodev2:10771:10797 [1] NCCL INFO comm 0x7f1518001d30 rank 5 nranks 8 cudaDev 1 nvmlDev 5
gpunodev1:26302:26328 [2] NCCL INFO Setting affinity for GPU 2 to 0fffff00,000fffff
gpunodev1:26302:26328 [2] NCCL INFO comm 0x7f4ee0001d30 rank 2 nranks 8 cudaDev 2 nvmlDev 6
gpunodev2:10772:10795 [2] NCCL INFO CUDA Dev 2[6], IB NIC distance :  SOC
gpunodev2:10773:10796 [3] NCCL INFO CUDA Dev 3[7], IB NIC distance :  SOC
gpunodev2:10771:10797 [1] NCCL INFO CUDA Dev 1[5], IB NIC distance :  SOC
gpunodev2:10770:10794 [0] NCCL INFO CUDA Dev 0[4], IB NIC distance :  SOC
gpunodev1:26300:26325 [0] NCCL INFO CUDA Dev 0[0], IB NIC distance :  SOC
gpunodev1:26303:26326 [3] NCCL INFO CUDA Dev 3[7], IB NIC distance :  SOC
gpunodev1:26301:26327 [1] NCCL INFO CUDA Dev 1[5], IB NIC distance :  SOC
gpunodev1:26302:26328 [2] NCCL INFO CUDA Dev 2[6], IB NIC distance :  SOC
gpunodev1:26300:26325 [0] NCCL INFO Channel 00 :    0   1   2   3   4   5   6   7
gpunodev2:10770:10794 [0] NCCL INFO Ring 00 : 3 -> 4 [receive] via NET/IB/0
gpunodev2:10771:10797 [1] NCCL INFO Ring 00 : 5[5] -> 6[6] via P2P/IPC
gpunodev2:10772:10795 [2] NCCL INFO Ring 00 : 6[6] -> 7[7] via P2P/IPC
gpunodev2:10770:10794 [0] NCCL INFO Ring 00 : 4[4] -> 5[5] via P2P/IPC
gpunodev1:26300:26325 [0] NCCL INFO Ring 00 : 7 -> 0 [receive] via NET/IB/0
gpunodev1:26302:26328 [2] NCCL INFO Ring 00 : 2[6] -> 3[7] via P2P/IPC
gpunodev1:26300:26325 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
gpunodev2:10773:10796 [3] NCCL INFO Ring 00 : 7 -> 0 [send] via NET/IB/0
gpunodev1:26303:26326 [3] NCCL INFO Ring 00 : 3 -> 4 [send] via NET/IB/0
gpunodev1:26301:26327 [1] NCCL INFO Ring 00 : 1[5] -> 2[6] via P2P/IPC

gpunodev1:26300:26325 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error No such device
gpunodev1:26300:26325 [0] NCCL INFO transport/net_ib.cu:382 -> 2
gpunodev1:26300:26325 [0] NCCL INFO transport/net_ib.cu:485 -> 2
gpunodev1:26300:26325 [0] NCCL INFO include/net.h:28 -> 2
gpunodev1:26300:26325 [0] NCCL INFO transport/net.cu:380 -> 2
gpunodev1:26300:26325 [0] NCCL INFO init.cu:667 -> 2
gpunodev1:26300:26325 [0] NCCL INFO init.cu:803 -> 2
gpunodev1:26300:26325 [0] NCCL INFO init.cu:915 -> 2
gpunodev1:26300:26325 [0] NCCL INFO misc/group.cu:69 -> 2 [Async thread]
gpunodev1: Test NCCL failure common.cu:788 'unhandled system error'
gpunodev2:10773:10796 [3] NCCL INFO Ring 00 : 7[7] -> 6[6] via P2P/IPC

gpunodev2:10770:10794 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error No such device
gpunodev2:10770:10794 [0] NCCL INFO transport/net_ib.cu:382 -> 2
gpunodev2:10770:10794 [0] NCCL INFO transport/net_ib.cu:485 -> 2
gpunodev2:10770:10794 [0] NCCL INFO include/net.h:28 -> 2
gpunodev2:10770:10794 [0] NCCL INFO transport/net.cu:380 -> 2
gpunodev2:10770:10794 [0] NCCL INFO init.cu:667 -> 2
gpunodev2:10770:10794 [0] NCCL INFO init.cu:803 -> 2
gpunodev2:10770:10794 [0] NCCL INFO init.cu:915 -> 2
gpunodev2:10770:10794 [0] NCCL INFO misc/group.cu:69 -> 2 [Async thread]
gpunodev2: Test NCCL failure common.cu:788 'unhandled system error'
gpunodev1:26303:26326 [3] NCCL INFO Ring 00 : 3[7] -> 2[6] via P2P/IPC
gpunodev2:10772:10795 [2] NCCL INFO Ring 00 : 6[6] -> 5[5] via P2P/IPC
gpunodev2:10771:10797 [1] NCCL INFO Ring 00 : 5[5] -> 4[4] via P2P/IPC
gpunodev2:10773:10796 [3] NCCL INFO Trees [0] 6->7->-1/-1/-1
gpunodev1:26302:26328 [2] NCCL INFO Ring 00 : 2[6] -> 1[5] via P2P/IPC
gpunodev2:10772:10795 [2] NCCL INFO Trees [0] 5->6->7/-1/-1
gpunodev1:26303:26326 [3] NCCL INFO Trees [0] 2->3->-1/-1/-1
gpunodev1:26301:26327 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via direct shared memory
gpunodev2:10773:10796 [3] NCCL INFO comm 0x7fd7ec001d30 rank 7 nranks 8 cudaDev 3 nvmlDev 7 - Init COMPLETE
gpunodev1:26302:26328 [2] NCCL INFO Trees [0] 1->2->3/-1/-1
gpunodev2:10772:10795 [2] NCCL INFO comm 0x7f168c001d30 rank 6 nranks 8 cudaDev 2 nvmlDev 6 - Init COMPLETE
gpunodev1:26303:26326 [3] NCCL INFO comm 0x7f616c001d30 rank 3 nranks 8 cudaDev 3 nvmlDev 7 - Init COMPLETE
gpunodev1:26302:26328 [2] NCCL INFO comm 0x7f4ee0001d30 rank 2 nranks 8 cudaDev 2 nvmlDev 6 - Init COMPLETE

gpunodev1:26303:26329 [0] include/socket.h:395 NCCL WARN Net : Connection closed by remote peer
gpunodev1:26303:26329 [0] NCCL INFO transport/net_ib.cu:563 -> 2
gpunodev1:26303:26329 [0] NCCL INFO transport/net_ib.cu:613 -> 2
gpunodev1:26303:26329 [0] NCCL INFO include/net.h:31 -> 2
gpunodev1:26303:26329 [0] NCCL INFO transport/net.cu:465 -> 2
gpunodev1:26303:26329 [0] NCCL INFO transport.cu:163 -> 2 [Proxy Thread]
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------

gpunodev2:10773:10798 [0] include/socket.h:395 NCCL WARN Net : Connection closed by remote peer
gpunodev2:10773:10798 [0] NCCL INFO transport/net_ib.cu:563 -> 2
gpunodev2:10773:10798 [0] NCCL INFO transport/net_ib.cu:613 -> 2
gpunodev2:10773:10798 [0] NCCL INFO include/net.h:31 -> 2
gpunodev2:10773:10798 [0] NCCL INFO transport/net.cu:465 -> 2
gpunodev2:10773:10798 [0] NCCL INFO transport.cu:163 -> 2 [Proxy Thread]
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[17350,1],4]
  Exit code:    3
--------------------------------------------------------------------------
```

Any help appreciated!

**Comment by sjeaugey** [comment]
I've never seen that error before; but I'm not familiar with the rdma-shared-docker plugin. It might work best to ask the question on the rdma-shared-docker project as they would probably have a better idea of why a call to `ibv_modify_qp` could return a `no such device` error.

**Comment by AddyLaddy** [comment]
Could it be that the IB devices have not been imported to the docker container?
I didn't see an IB device in the ifconfig output either

**Comment by lzha106** [comment]
We dig a little bit into the code and find that the issue may be caused by GID number in dockers.

It seems NCCL can't get the GID correctly，as in the rdma-shared docker, GID started not from 0.
  
```
root@gpunodev1:/examples/benchmarks# show_gids
DEV     PORT    INDEX   GID                                     IPv4            VER     DEV
---     ----    -----   ---                                     ------------    ---     ---
mlx5_bond_0     1       12      0000:0000:0000:0000:0000:ffff:c0a8:bc16 192.168.188.22          v1      eth0
mlx5_bond_0     1       13      0000:0000:0000:0000:0000:ffff:c0a8:bc16 192.168.188.22          v2      eth0
n_gids_found=2
```

Besides, in different dockers, GID are different, and we failed to use NCCL_IB_GID_INDEX to set the number for all dockers by mpirun command. (It only works when all dockers have the same GID)

Is there a way for  NCCL to get the GID automatically or any other way to handle the case of different GID in docker?

**Comment by sjeaugey** [comment]
I'm not sure how we could do that. But you could always run a wrapper script around your application, for example if using mpirun:

```
mpirun -np 32 ./set_gid_index.sh ./myapp
```
Where `set_gid_index.sh` is:
```
#!/bin/bash
gid=`command to find out the right gid to use`
NCCL_IB_GID_INDEX=$gid $@
```

**Comment by lzha106** [comment]
@sjeaugey thanks for reply and give the sample.

One problem is that in different dockers which need to communicate by NCCL, the GID index is different. (Like A docker gid index=12, B docker gid index=13)

Seems we can't simply assign the same gid index for all dockers by NCCL_IB_GID_INDEX, which forces all dockers use same gid index.

**Comment by js-sun-cyber** [comment]
> @sjeaugey thanks for reply and the sample.
> 
> One problem is that in different dockers which need to communicate by NCCL, the GID index is different. (Like A docker gid index=12, B docker gid index=13)
> 
> Seems we can't simply assign the same gid index for all dockers by NCCL_IB_GID_INDEX, which forces all dockers use same gid index.
> 
> Update： Verified the way by assigning different gid index for different dockers， it works now.
> 
> The way to get gid index refer to [link](https://community.mellanox.com/s/article/understanding-show-gids-script)

assigning different gid index for different dockers-------could you share the method? I have the case that different interface name in docker, thanks a lot
