### ISSUE TITLE
NCCL Alltoall Hangs

### ISSUE THREAD

**Issue by Quentin-Anthony** [NVIDIA/nccl#566]
I'm attempting to write an application using NCCL alltoall, but my implementation hangs yet alltoall_perf from the nccl-tests github runs fine.

Here's the NCCL alltoall snippet from my code:

```
rank_offset = size * 1;
ncclGroupStart();
for (int r = 0; r < numprocs; r++) {
    NCCL_CHECK(ncclSend((char*)sendbuf + r * rank_offset, size, ncclChar, r,
                   nccl_comm, nccl_stream));
    NCCL_CHECK(ncclRecv((char*)recvbuf + r * rank_offset, size, ncclChar, r,
                   nccl_comm, nccl_stream));
}
ncclGroupEnd();
```

Running basic send/recv without the for loop runs fine.

**From the output below, it appears that channels 06 and 07 are not properly initialized in my code?** Here's the output of nccl-tests alltoall_perf with NCCL_DEBUG=INFO:

```
lassen206:24684:24684 [0] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.64.206<0>
lassen206:24684:24684 [0] NCCL INFO NET/Plugin : Plugin load returned 22 : libnccl-net.so: cannot open shared object file: No such file or directory.
lassen206:24684:24684 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.64.206<0>
lassen206:24684:24684 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
lassen206:24685:24685 [1] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.64.206<0>
lassen206:24685:24685 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
lassen206:24685:24685 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.64.206<0>
lassen206:24685:24685 [1] NCCL INFO Using network IB
lassen206:24684:24684 [0] NCCL INFO Channel 00/06 :    0   1
lassen206:24685:24685 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] 0/-1/-1->1->-1 [3] -1/-1/-1->1->0 [4] -1/-1/-1->1->0 [5] 0/-1/-1->1->-1
lassen206:24684:24684 [0] NCCL INFO Channel 01/06 :    0   1
lassen206:24685:24685 [1] NCCL INFO Setting affinity for GPU 1 to 110000
lassen206:24684:24684 [0] NCCL INFO Channel 02/06 :    0   1
lassen206:24684:24684 [0] NCCL INFO Channel 03/06 :    0   1
lassen206:24684:24684 [0] NCCL INFO Channel 04/06 :    0   1
lassen206:24684:24684 [0] NCCL INFO Channel 05/06 :    0   1
lassen206:24684:24684 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] -1/-1/-1->0->1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] -1/-1/-1->0->1
lassen206:24684:24684 [0] NCCL INFO Setting affinity for GPU 0 to 1100
lassen206:24685:24685 [1] NCCL INFO Channel 00 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Channel 00 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24685 [1] NCCL INFO Channel 01 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Channel 01 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24685 [1] NCCL INFO Channel 02 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Channel 02 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24685 [1] NCCL INFO Channel 03 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Channel 03 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24685 [1] NCCL INFO Channel 04 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Channel 04 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24685 [1] NCCL INFO Channel 05 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Channel 05 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24685 [1] NCCL INFO Connected all rings
lassen206:24685:24685 [1] NCCL INFO Connected all trees
lassen206:24685:24685 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen206:24684:24684 [0] NCCL INFO Connected all rings
lassen206:24684:24684 [0] NCCL INFO Connected all trees
lassen206:24684:24684 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen206:24685:24685 [1] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen206:24684:24684 [0] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen206:24685:24685 [1] NCCL INFO comm 0x4502bce0 rank 1 nranks 2 cudaDev 1 busId 405000 - Init COMPLETE
lassen206:24684:24684 [0] NCCL INFO comm 0x20005b3f1c20 rank 0 nranks 2 cudaDev 0 busId 404000 - Init COMPLETE
lassen206:24685:24741 [1] NCCL INFO Channel 06 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24742 [0] NCCL INFO Channel 06 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24685:24741 [1] NCCL INFO Channel 07 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:24684:24742 [0] NCCL INFO Channel 07 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:24684:24684 [0] NCCL INFO Launch mode Parallel
```

Here's the output of my code with NCCL_DEBUG=INFO (it hangs indefinitely at the last line):

```
lassen206:23224:23224 [0] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.64.206<0>
lassen206:23224:23224 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
lassen206:23224:23224 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.64.206<0>
lassen206:23224:23224 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
lassen206:23225:23225 [1] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.64.206<0>
lassen206:23225:23225 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
lassen206:23225:23225 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.64.206<0>
lassen206:23225:23225 [1] NCCL INFO Using network IB
lassen206:23224:23224 [0] NCCL INFO Channel 00/06 :    0   1
lassen206:23225:23225 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] 0/-1/-1->1->-1 [3] -1/-1/-1->1->0 [4] -1/-1/-1->1->0 [5] 0/-1/-1->1->-1
lassen206:23224:23224 [0] NCCL INFO Channel 01/06 :    0   1
lassen206:23224:23224 [0] NCCL INFO Channel 02/06 :    0   1
lassen206:23225:23225 [1] NCCL INFO Setting affinity for GPU 1 to 110000
lassen206:23224:23224 [0] NCCL INFO Channel 03/06 :    0   1
lassen206:23224:23224 [0] NCCL INFO Channel 04/06 :    0   1
lassen206:23224:23224 [0] NCCL INFO Channel 05/06 :    0   1
lassen206:23224:23224 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] -1/-1/-1->0->1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] -1/-1/-1->0->1
lassen206:23224:23224 [0] NCCL INFO Setting affinity for GPU 0 to 1100
lassen206:23225:23225 [1] NCCL INFO Channel 00 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23224:23224 [0] NCCL INFO Channel 00 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:23225:23225 [1] NCCL INFO Channel 01 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23224:23224 [0] NCCL INFO Channel 01 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:23225:23225 [1] NCCL INFO Channel 02 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23224:23224 [0] NCCL INFO Channel 02 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:23225:23225 [1] NCCL INFO Channel 03 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23224:23224 [0] NCCL INFO Channel 03 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:23225:23225 [1] NCCL INFO Channel 04 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23224:23224 [0] NCCL INFO Channel 04 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:23225:23225 [1] NCCL INFO Channel 05 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23224:23224 [0] NCCL INFO Channel 05 : 0[404000] -> 1[405000] via P2P/IPC
lassen206:23225:23225 [1] NCCL INFO Connected all rings
lassen206:23225:23225 [1] NCCL INFO Connected all trees
lassen206:23225:23225 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen206:23224:23224 [0] NCCL INFO Connected all rings
lassen206:23224:23224 [0] NCCL INFO Connected all trees
lassen206:23224:23224 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen206:23225:23225 [1] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen206:23224:23224 [0] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen206:23225:23225 [1] NCCL INFO comm 0x45002300 rank 1 nranks 2 cudaDev 1 busId 405000 - Init COMPLETE
lassen206:23224:23224 [0] NCCL INFO comm 0x44eef7c0 rank 0 nranks 2 cudaDev 0 busId 404000 - Init COMPLETE
lassen206:23224:23224 [0] NCCL INFO Launch mode Parallel
lassen206:23225:23279 [1] NCCL INFO Channel 06 : 1[405000] -> 0[404000] via P2P/IPC
lassen206:23225:23279 [1] NCCL INFO Channel 07 : 1[405000] -> 0[404000] via P2P/IPC
```

**Comment by sjeaugey** [comment]
Can you check with `gdb` where rank 0 is blocked? It seems Rank 1 is inside NCCL waiting to connect channels 6/7, but rank 0 is blocked by something and unable to reach that point.

**Comment by Quentin-Anthony** [comment]
It seems to get stuck within the next MPI call's Barrier (I've tried pure MPI_Barrier(), any blocking collective, and MPI_Finalize()). I.e.

```
// NCCL Alltoall
rank_offset = size * 1;
ncclGroupStart();
for (int r = 0; r < numprocs; r++) {
    NCCL_CHECK(ncclSend((char*)sendbuf + r * rank_offset, size, ncclChar, r,
                   nccl_comm, nccl_stream));
    NCCL_CHECK(ncclRecv((char*)recvbuf + r * rank_offset, size, ncclChar, r,
                   nccl_comm, nccl_stream));
}
ncclGroupEnd();

// Synchronize NCCL stream
cudaError_t err = cudaErrorNotReady;
int flag;
while (err == cudaErrorNotReady) {
    err = cudaStreamQuery(_nccl_stream);
    MPI_CHECK(MPI_Iprobe(MPI_ANY_SOURCE, MPI_ANY_TAG,
        MPI_COMM_WORLD, &flag, MPI_STATUS_IGNORE));
}
CUDA_CHECK(err);

// Next blocking MPI call (which rank 0 hangs on)
MPI_CHECK(MPI_Reduce(...));
```

I was under the impression that ncclSend/ncclRecv calls were executed at ncclGroupEnd(), so it's unclear to me why rank 0 would pass to the next MPI call. Am I missing a synchronization?

**Comment by sjeaugey** [comment]
I'm not sure I understand. You seem to be launching 8 ranks, yet the NCCL communicator only has 2 ranks in the log. Or did you run the second example with 8 ranks instead of 2 in your log before that?

**Comment by Quentin-Anthony** [comment]
I ran the first example with 2 ranks, and I ran the second example with 8 ranks.

**Comment by Quentin-Anthony** [comment]
Any suggestions?

**Comment by sjeaugey** [comment]
Can you run the second example with 2 ranks and NCCL_DEBUG=INFO, so that we have a consistent log? Basically we want to understand which rank got stuck and where it is stuck.

**Comment by Quentin-Anthony** [comment]
Sure! Here's the output:

```
lassen50:163374:163374 [0] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.64.50<0>
lassen50:163374:163374 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
lassen50:163374:163374 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.64.50<0>
lassen50:163374:163374 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
lassen50:163375:163375 [1] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.64.50<0>
lassen50:163375:163375 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
lassen50:163375:163375 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.64.50<0>
lassen50:163375:163375 [1] NCCL INFO Using network IB
lassen50:163374:163374 [0] NCCL INFO Channel 00/06 :    0   1
lassen50:163375:163375 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] 0/-1/-1->1->-1 [3] -1/-1/-1->1->0 [4] -1/-1/-1->1->0 [5] 0/-1/-1->1->-1
lassen50:163374:163374 [0] NCCL INFO Channel 01/06 :    0   1
lassen50:163374:163374 [0] NCCL INFO Channel 02/06 :    0   1
lassen50:163375:163375 [1] NCCL INFO Setting affinity for GPU 1 to 110000
lassen50:163374:163374 [0] NCCL INFO Channel 03/06 :    0   1
lassen50:163374:163374 [0] NCCL INFO Channel 04/06 :    0   1
lassen50:163374:163374 [0] NCCL INFO Channel 05/06 :    0   1
lassen50:163374:163374 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] -1/-1/-1->0->1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] -1/-1/-1->0->1
lassen50:163374:163374 [0] NCCL INFO Setting affinity for GPU 0 to 1100
lassen50:163375:163375 [1] NCCL INFO Channel 00 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163374:163374 [0] NCCL INFO Channel 00 : 0[404000] -> 1[405000] via P2P/IPC
lassen50:163375:163375 [1] NCCL INFO Channel 01 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163374:163374 [0] NCCL INFO Channel 01 : 0[404000] -> 1[405000] via P2P/IPC
lassen50:163375:163375 [1] NCCL INFO Channel 02 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163374:163374 [0] NCCL INFO Channel 02 : 0[404000] -> 1[405000] via P2P/IPC
lassen50:163375:163375 [1] NCCL INFO Channel 03 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163374:163374 [0] NCCL INFO Channel 03 : 0[404000] -> 1[405000] via P2P/IPC
lassen50:163375:163375 [1] NCCL INFO Channel 04 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163374:163374 [0] NCCL INFO Channel 04 : 0[404000] -> 1[405000] via P2P/IPC
lassen50:163375:163375 [1] NCCL INFO Channel 05 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163374:163374 [0] NCCL INFO Channel 05 : 0[404000] -> 1[405000] via P2P/IPC
lassen50:163375:163375 [1] NCCL INFO Connected all rings
lassen50:163375:163375 [1] NCCL INFO Connected all trees
lassen50:163375:163375 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen50:163374:163374 [0] NCCL INFO Connected all rings
lassen50:163374:163374 [0] NCCL INFO Connected all trees
lassen50:163374:163374 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen50:163375:163375 [1] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen50:163374:163374 [0] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen50:163375:163375 [1] NCCL INFO comm 0x4500e0c0 rank 1 nranks 2 cudaDev 1 busId 405000 - Init COMPLETE
lassen50:163374:163374 [0] NCCL INFO comm 0x44efb600 rank 0 nranks 2 cudaDev 0 busId 404000 - Init COMPLETE

# OSU NCCL-CUDA Alltoall Latency Test v5.8
# Size       Avg Latency(us)
here 0 0
here 0 1
lassen50:163374:163374 [0] NCCL INFO Launch mode Parallel
lassen50:163375:163435 [1] NCCL INFO Channel 06 : 1[405000] -> 0[404000] via P2P/IPC
lassen50:163375:163435 [1] NCCL INFO Channel 07 : 1[405000] -> 0[404000] via P2P/IPC
here 1 0
```

**Comment by sjeaugey** [comment]
Could you run it again with `NCCL_DEBUG_SUBSYS=INIT,COLL` ? It is weird that rank 0 seems to go through the NCCL calls but doesn't print any line about connecting channels 6 and 7.

**Comment by Quentin-Anthony** [comment]
Here's the output with NCCL_DEBUG_SUBSYS=INIT,COLL:

```
lassen495:155332:155332 [0] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.65.241<0>
lassen495:155332:155332 [0] NCCL INFO NET/Plugin : Plugin load returned 22 : libnccl-net.so: cannot open shared object file: No such file or directory.
lassen495:155332:155332 [0] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.65.241<0>
lassen495:155332:155332 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
lassen495:155333:155333 [1] NCCL INFO Bootstrap : Using enP5p1s0f0:192.168.65.241<0>
lassen495:155333:155333 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
lassen495:155333:155333 [1] NCCL INFO NET/IB : Using [0]mlx5_1:1/IB [1]mlx5_3:1/IB [2]mlx5_0:1/IB [3]mlx5_2:1/IB ; OOB enP5p1s0f0:192.168.65.241<0>
lassen495:155333:155333 [1] NCCL INFO Using network IB
lassen495:155332:155332 [0] NCCL INFO Channel 00/06 :    0   1
lassen495:155333:155333 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] 0/-1/-1->1->-1 [3] -1/-1/-1->1->0 [4] -1/-1/-1->1->0 [5] 0/-1/-1->1->-1
lassen495:155332:155332 [0] NCCL INFO Channel 01/06 :    0   1
lassen495:155332:155332 [0] NCCL INFO Channel 02/06 :    0   1
lassen495:155333:155333 [1] NCCL INFO Setting affinity for GPU 1 to 110000
lassen495:155332:155332 [0] NCCL INFO Channel 03/06 :    0   1
lassen495:155332:155332 [0] NCCL INFO Channel 04/06 :    0   1
lassen495:155332:155332 [0] NCCL INFO Channel 05/06 :    0   1
lassen495:155332:155332 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] -1/-1/-1->0->1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] -1/-1/-1->0->1
lassen495:155332:155332 [0] NCCL INFO Setting affinity for GPU 0 to 1100
lassen495:155333:155333 [1] NCCL INFO Channel 00 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155332:155332 [0] NCCL INFO Channel 00 : 0[404000] -> 1[405000] via P2P/IPC
lassen495:155333:155333 [1] NCCL INFO Channel 01 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155332:155332 [0] NCCL INFO Channel 01 : 0[404000] -> 1[405000] via P2P/IPC
lassen495:155333:155333 [1] NCCL INFO Channel 02 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155332:155332 [0] NCCL INFO Channel 02 : 0[404000] -> 1[405000] via P2P/IPC
lassen495:155333:155333 [1] NCCL INFO Channel 03 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155332:155332 [0] NCCL INFO Channel 03 : 0[404000] -> 1[405000] via P2P/IPC
lassen495:155333:155333 [1] NCCL INFO Channel 04 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155332:155332 [0] NCCL INFO Channel 04 : 0[404000] -> 1[405000] via P2P/IPC
lassen495:155333:155333 [1] NCCL INFO Channel 05 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155332:155332 [0] NCCL INFO Channel 05 : 0[404000] -> 1[405000] via P2P/IPC
lassen495:155333:155333 [1] NCCL INFO Connected all rings
lassen495:155333:155333 [1] NCCL INFO Connected all trees
lassen495:155333:155333 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen495:155332:155332 [0] NCCL INFO Connected all rings
lassen495:155332:155332 [0] NCCL INFO Connected all trees
lassen495:155332:155332 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
lassen495:155333:155333 [1] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen495:155332:155332 [0] NCCL INFO 6 coll channels, 8 p2p channels, 8 p2p channels per peer
lassen495:155333:155333 [1] NCCL INFO comm 0x4500e500 rank 1 nranks 2 cudaDev 1 busId 405000 - Init COMPLETE
lassen495:155332:155332 [0] NCCL INFO comm 0x2000477f2870 rank 0 nranks 2 cudaDev 0 busId 404000 - Init COMPLETE
lassen495:155333:155333 [1] NCCL INFO Send: opCount 0 sendbuff 0x20006a409200 recvbuff (nil) count 32 datatype 0 op 0 root 0 comm 0x4500e500 [nranks=2] stream 0x12a0ffe0
lassen495:155333:155333 [1] NCCL INFO Recv: opCount 0 sendbuff (nil) recvbuff 0x20006a409400 count 32 datatype 0 op 0 root 0 comm 0x4500e500 [nranks=2] stream 0x12a0ffe0
lassen495:155333:155333 [1] NCCL INFO Send: opCount 0 sendbuff 0x20006a409200 recvbuff (nil) count 32 datatype 0 op 0 root 0 comm 0x4500e500 [nranks=2] stream 0x12a0ffe0
lassen495:155333:155333 [1] NCCL INFO Recv: opCount 0 sendbuff (nil) recvbuff 0x20006a409400 count 32 datatype 0 op 0 root 0 comm 0x4500e500 [nranks=2] stream 0x12a0ffe0
here 0 1

# Alltoall Test
# Size       Avg Latency(us)
lassen495:155332:155332 [0] NCCL INFO Send: opCount 0 sendbuff 0x20008a409200 recvbuff (nil) count 32 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
lassen495:155332:155332 [0] NCCL INFO Recv: opCount 0 sendbuff (nil) recvbuff 0x20008a409400 count 32 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
lassen495:155332:155332 [0] NCCL INFO Send: opCount 0 sendbuff 0x20008a409200 recvbuff (nil) count 32 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
lassen495:155332:155332 [0] NCCL INFO Recv: opCount 0 sendbuff (nil) recvbuff 0x20008a409400 count 32 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
here 0 0
lassen495:155332:155332 [0] NCCL INFO Launch mode Parallel
lassen495:155333:155379 [1] NCCL INFO Channel 06 : 1[405000] -> 0[404000] via P2P/IPC
lassen495:155333:155379 [1] NCCL INFO Channel 07 : 1[405000] -> 0[404000] via P2P/IPC
here 1 0
lassen495:155332:155332 [0] NCCL INFO Send: opCount 0 sendbuff 0x20008a409200 recvbuff (nil) count 64 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
lassen495:155332:155332 [0] NCCL INFO Recv: opCount 0 sendbuff (nil) recvbuff 0x20008a409400 count 64 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
lassen495:155332:155332 [0] NCCL INFO Send: opCount 0 sendbuff 0x20008a409200 recvbuff (nil) count 64 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
lassen495:155332:155332 [0] NCCL INFO Recv: opCount 0 sendbuff (nil) recvbuff 0x20008a409400 count 64 datatype 0 op 0 root 0 comm 0x2000477f2870 [nranks=2] stream 0x20000d866030
here 0 0
here 1 0
```

**Comment by Quentin-Anthony** [comment]
We were able to resolve this on our end. 

We were using the example NCCLCHECK macro from https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html as follows:

```
#define NCCLCHECK(cmd) do {                         \
  ncclResult_t r = cmd;                             \
  if (r!= ncclSuccess) {                            \
    printf("Failed, NCCL error %s:%d '%s'\n",             \
        __FILE__,__LINE__,ncclGetErrorString(r));   \
    exit(EXIT_FAILURE);                             \
  }                                                 \
} while(0)
```

So this boils down to redefining the "r" variable in the Alltoall loop. We changed "r" to "res" in NCCLCHECK and this was resolved.

Sorry for the silly question!

**Comment by Edenzzzz** [comment]
@sjeaugey In NCCL 2.21.5, I met this problem again when using torch's [uneven all to all](https://github.com/pytorch/pytorch/blob/1eba9b3aa3c43f86f4a2c807ac8e12c4a7767340/torch/csrc/cuda/nccl.cpp#L901), which calls into AllToAllv.

![Image](https://github.com/user-attachments/assets/aed1b5f3-59ad-4c58-baf9-e38b1f2f5edd)
