### ISSUE TITLE
NCCL Allreduce Performance

### ISSUE THREAD

**Issue by Quentin-Anthony** [NVIDIA/nccl#588]
We're running Allreduce on a Docker image for a 12-node system. Each node is a modified DGX A100. **We used to get ~20 GB/s busbw with Allreduce (NCCL 2.7.8), but now we're seeing ~3.7 GB/s busbw with Allreduce (NCCL 2.11.4) on the same system.** 

Run command:

```
NCCL_DEBUG_SUBSYS=GRAPH NCCL_IB_HCA=^ibp17s0f1,^mlx5_2 NCCL_SOCKET_IFNAME=eth NCCL_TOPO_DUMP_FILE=system.txt mpirun -np 96 --hostfile hosts --prefix /usr/local/mpi -x NCCL_DEBUG=INFO -x PATH -x LD_LIBRARY_PATH nccl-tests/build/all_reduce_perf -b 8 -e 2G -f 2 > nccl-perf.log
```

[nccl-perf.log](https://github.com/NVIDIA/nccl/files/7447151/nccl-perf.log)

[system.txt](https://github.com/NVIDIA/nccl/files/7447152/system.txt)

ibstatus:

```
mchorse@new-0:~$ ibstatus
Infiniband device 'ibp142s0' port 1 status:
        default gid:     fe80:0000:0000:0000:1c34:da03:0055:76d8
        base lid:        0x29
        sm lid:          0x1
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand

Infiniband device 'ibp17s0f0' port 1 status:
        default gid:     fe80:0000:0000:0000:0c42:a103:0033:a586
        base lid:        0x33
        sm lid:          0x1
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand

Infiniband device 'ibp17s0f1' port 1 status:
        default gid:     fe80:0000:0000:0000:0c42:a103:0033:a587
        base lid:        0xffff
        sm lid:          0x0
        state:           1: DOWN
        phys state:      3: Disabled
        rate:            10 Gb/sec (4X SDR)
        link_layer:      InfiniBand

Infiniband device 'ibp209s0' port 1 status:
        default gid:     fe80:0000:0000:0000:1c34:da03:0062:8c6c
        base lid:        0x2c
        sm lid:          0x1
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand

Infiniband device 'ibp85s0' port 1 status:
        default gid:     fe80:0000:0000:0000:1c34:da03:0062:8fe8
        base lid:        0x2a
        sm lid:          0x1
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            100 Gb/sec (4X EDR)
        link_layer:      InfiniBand
```

**Any thoughts?**

**Comment by AddyLaddy** [comment]
It seems to only be using one NIC. Do you have the same NCCL_DEBUG dump file for 2.7.8 to compare against. I assume you're not setting any other NCCL env vars or injecting a topology file?

**Comment by Quentin-Anthony** [comment]
Here are the same files from running the old version:

[nccl-old-perf.log](https://github.com/NVIDIA/nccl/files/7455542/nccl-old-perf.log)

[system-old.txt](https://github.com/NVIDIA/nccl/files/7455543/system-old.txt)

**Comment by AddyLaddy** [comment]
Ok thanks for the update, but the logs don't quite have all the information in them. Perhaps you could run both with (4 nodes, 32 gpus should be sufficient): 

```mpirun -np 32 --hostfile hosts --prefix /usr/local/mpi -x NCCL_IB_HCA=^ibp17s0f1,^mlx5_2 -x NCCL_SOCKET_IFNAME=eth -x NCCL_DEBUG=INFO -x NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH -x PATH -x LD_LIBRARY_PATH nccl-tests/build/all_reduce_perf -b 8 -e 2G -f 2 > nccl-perf.log```

mpirun has a habit of only passing the local env vars to the first process. It's generally safer to use the '-x' option to ensure all ranks have the same settings.

Also, I see in that last log file you were using NCCL 2.8.4 and achieved a peak BusBW of 24GB/s.

**Comment by Quentin-Anthony** [comment]
Here's the old output:

[nccl-old-32perf.log](https://github.com/NVIDIA/nccl/files/7456265/nccl-old-32perf.log)

And the new output:

[nccl-new-32perf.log](https://github.com/NVIDIA/nccl/files/7456266/nccl-new-32perf.log)

**Comment by AddyLaddy** [comment]
Great thanks we'll look through those files to see if we can determine why only one NIC is being used in the slow case.
But I noticed that both runs were done using NCCL 2.8.4 and the only difference appears to be that the slow run is using the external IB/SHARP plugin and the interfaces chosen look to be different?

Slow run

```new-0:358092:358092 [0] NCCL INFO Plugin Path : /usr/local/lib/libnccl-net.so```

```new-0:358092:358092 [0] NCCL INFO NET/IB : Using [0]ibp85s0f0:1/IB/SHARP [1]ibp17s0f0:1/IB/SHARP [2]ibp209s0:1/IB/SHARP [3]ibp142s0:1/IB/SHARP ; OOB eth0:10.144.55.72<0>```

Fast run

```new-0:1680:1680 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation```

```new-0:1680:1680 [0] NCCL INFO NET/IB : Using [0]ibp85s0:1/IB [1]ibp17s0:1/IB [2]ibp209s0f0:1/IB [3]ibp142s0:1/IB ; OOB eth0:10.144.231.85<0>```

**Comment by sjeaugey** [comment]
@Quentin-Anthony it looks like your nodes have a mix of CX-5 and CX-6 NICs. With the SHARP plugin, CX-6 NICs are reordered as the first NICs and NCCL will only retain those with SHARP support.

Maybe we could improve NCCL to not remove non-SHARP-capable NICs when SHARP(COLLNET) is disabled, but in any case, the reordering will happen and can cause suboptimal performance as traffic will cross the rails and go up the tree.

You can disable the plugin with `NCCL_IBEXT_DISABLE=1` or just not have the plugin in your LD library path. That should fix your problem.

**Comment by Quentin-Anthony** [comment]
> @Quentin-Anthony it looks like your nodes have a mix of CX-5 and CX-6 NICs. With the SHARP plugin, CX-6 NICs are reordered as the first NICs and NCCL will only retain those with SHARP support.
> 
> Maybe we could improve NCCL to not remove non-SHARP-capable NICs when SHARP(COLLNET) is disabled, but in any case, the reordering will happen and can cause suboptimal performance as traffic will cross the rails and go up the tree.
> 
> You can disable the plugin with `NCCL_IBEXT_DISABLE=1` or just not have the plugin in your LD library path. That should fix your problem.

Thanks for the info! I agree that the SHARP plugin mismatch likely caused our issue. 

We were able to resolve this by switching up our OFED install, so I'm going to close this for now.
