### ISSUE TITLE
NCCL WARN NET/IB : collective mismatch error

### ISSUE THREAD

**Issue by guozhiyao** [NVIDIA/nccl#615]
I am running a PyTorch application which uses all_reduce. The result is correct when I use one node, but it raises the error as title when I use 2 nodes.
The version of libnccl2 is 2.9.6.

**Comment by guozhiyao** [comment]
@sjeaugey

**Comment by sjeaugey** [comment]
Hi @guozhiyao, can you post the error log (at least the `WARN` line)?

Things we typically check in this case is:
 - Did you force relaxed ordering on the NICs (service mst start; mlxconfig -d /dev/mst/<mst device> q PCI_WR_ORDERING must return `per_mkey` not `forced_relax`).
 - Do you still see the issue with `NCCL_PROTO=SIMPLE`?

Finally, if the problem persists, could you share the hardware topology of your nodes dumped by NCCL with `NCCL_TOPO_DUMP_FILE=system.txt`?

**Comment by guozhiyao** [comment]
@sjeaugey Thanks for your reply.
I run the code with `WARN` and it stop with the error
`train-run-env3-list2-parallel-0:15483:15645 [0] transport/net_ib.cc:665 NCCL WARN NET/IB : collective mismatch error local size 546816 remote 524288 addr 7ff7d1530000 rkey 2553d seq 14/1c`.

- there is not `mnt` service in my computer.
- the problem is persists with `NCCL_PROTO=SIMPLE` with the same error. But the error is solved with `NCCL_IB_DISABLE=1`, but the training speed is slower.

Here is the hardware topology of my node.
[system.txt](https://github.com/NVIDIA/nccl/files/7837328/system.txt)

**Comment by guozhiyao** [comment]
> @sjeaugey Thanks for your reply. I run the code with `WARN` and it stop with the error `train-run-env3-list2-parallel-0:15483:15645 [0] transport/net_ib.cc:665 NCCL WARN NET/IB : collective mismatch error local size 546816 remote 524288 addr 7ff7d1530000 rkey 2553d seq 14/1c`.
> 
> * there is not `mnt` service in my computer.
> * the problem is persists with `NCCL_PROTO=SIMPLE` with the same error. But the error is solved with `NCCL_IB_DISABLE=1`, but the training speed is slower.
> 
> Here is the hardware topology of my node. [system.txt](https://github.com/NVIDIA/nccl/files/7837328/system.txt)

Except for the version number`2.9.6+cuda11.3` and the error above, no other information is displayed.

**Comment by sjeaugey** [comment]
Thanks. It does look like a NIC ordering issue.

Given you seem to be using Mellanox Connect-X 5 NICs, you should have Mellanox Firmware Tools (MFT) installed. If not, please try to install the `mft` package from your OFED distro.

Then please run `service mst start` and `mlxconfig -d /dev/mst/<mst device> q PCI_WR_ORDERING`.

**Comment by guozhiyao** [comment]
Thanks.
I used the `pipe` API provided by pytorch to implement model parallelism, and the above error occurred. I have now implemented a model parallel framework by myself, and the above problems will not occur.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
