### ISSUE TITLE
NCCL hangs in the case GPUs are linked through PXB or PIX

### ISSUE THREAD

**Issue by LouieShao** [NVIDIA/nccl#667]
GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity
GPU0	 X 	PXB	SYS	SYS	0-27,56-83	0
GPU1	PXB	 X 	SYS	SYS	0-27,56-83	0
GPU2	SYS	SYS	 X 	PIX	28-55,84-111	1
GPU3	SYS	SYS	PIX	 X 	28-55,84-111	1

The topology is as above.

all_reduce_perf works fine only with those linked through SYS. The rest will result in hanging.

Setting NCCL_P2P_DISABLE=1 did workaround but got really low speed.

NCCL version 2.10.X

Any advice would be appreciated.

**Comment by sjeaugey** [comment]
Please check this section of the documentation; in particular the "ACS" paragraph.
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-direct

Please let us know if that solves your issue.

**Comment by LouieShao** [comment]
I 1) disabled VT-d 2) randomly change the physical sequence of my GPUs, which did the trick. I am not sure which helps, but it must be one of them.

**Comment by sjeaugey** [comment]
Maybe a bug in the BIOS when doing a hot reboot, while a cold reboot (after shuffling the GPUs) did take the setting into account?

In any case, thanks for the feedback.
