### ISSUE TITLE
Cannot disable IB or force NCCL to use Socket network on DGX-A100

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/nccl#676]
While debugging the issue mentioned in https://github.com/NVIDIA/NeMo/issues/4035, I discovered that with NCCL 2.12.9 (torch 1.12.0, nemo:1.8.0) on a DGX-A100 system the environment flag `NCCL_IB_DISABLE` is ignored. Regardless of its value NCCL will always use IBext. This will happen even if `NCCL_SOCKET_IFNAME` is set to only use `en*` IP interfaces.
```
gpu01:138879:138879 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:138879:138879 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu01:138879:138879 [0] NCCL INFO Bootstrap : Using enp225s0f1:10.10.10.2<0>
gpu01:138879:138879 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
gpu01:138879:138879 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
gpu01:138879:138879 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
gpu01:138879:138879 [0] NCCL INFO P2P plugin IBext
gpu01:138879:138879 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:138879:138879 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu01:138879:138879 [0] NCCL INFO NET/IB : Using [0]mlx5_9:1/RoCE ; OOB enp225s0f1:88.200.23.102<0>
gpu01:138879:138879 [0] NCCL INFO Using network IBext
```
On my system the IB interefaces are not connected, hence multi-node communication over IB fails, but due to the above reason I am also unable to instruct NCCL to use the appropriate ethernet interface. 

Furthermore, when I set also `NCCL_NET=Socket` NCCL 2.12.9 crashes with a segmentation fault
```
gpu01:134592:134592 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:134592:134592 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu01:134592:134592 [0] NCCL INFO Bootstrap : Using enp225s0f1:10.10.10.2<0>
gpu01:134592:134592 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
gpu01:134592:134592 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
[gpu01:134592:0:134592] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
```

With NCCL 2.11.4 (torch 1.10.0, nemo:1.6.0) there is no seg fault and multi-node training works. The DGX OS is 5.2, and the nvidia drivers are 510.47.03.

**Comment by AddyLaddy** [comment]
You can disable the external plugin with ` NCCL_IBEXT_DISABLE=1`

**Comment by itzsimpl** [comment]
Unfortunately still not working; this is the trace
```
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.

----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

gpu01:351578:351578 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:351578:351578 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu01:351578:351578 [0] NCCL INFO Bootstrap : Using enp225s0f1:10.10.10.2<0>
gpu01:351578:351578 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
gpu01:351578:351578 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
gpu01:351578:351578 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
gpu01:351578:351578 [0] NCCL INFO P2P plugin IBext
gpu01:351578:351578 [0] NCCL INFO NCCL_IBEXT_DISABLE set by environment to 1.
gpu01:351578:351578 [0] NCCL INFO net.cc:55 -> 3
gpu01:351578:351578 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:351578:351578 [0] NCCL INFO NET/IB : Using [0]mlx5_9:1/RoCE [RO]; OOB enp225s0f1:10.10.10.2<0>
gpu01:351578:351578 [0] NCCL INFO Using network IB
NCCL version 2.12.9+cuda11.6
gpu01:351578:352168 [0] NCCL INFO init.cc:224 Cuda Host Alloc Size 4 pointer 0x7f0baa800000
gpu02:35637:35637 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu02:35637:35637 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu02:35637:35637 [0] NCCL INFO Bootstrap : Using eno1:10.10.10.3<0>
gpu02:35637:35637 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
gpu02:35637:35637 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
gpu02:35637:35637 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
gpu02:35637:35637 [0] NCCL INFO P2P plugin IBext
gpu02:35637:35637 [0] NCCL INFO NCCL_IBEXT_DISABLE set by environment to 1.
gpu02:35637:35637 [0] NCCL INFO net.cc:55 -> 3
gpu02:35637:35637 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu02:35637:35637 [0] NCCL INFO NET/IB : No device found.
gpu02:35637:35637 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu02:35637:35637 [0] NCCL INFO NET/Socket : Using [0]eno1:10.10.10.3<0>
gpu02:35637:35637 [0] NCCL INFO Using network Socket
gpu02:35637:35723 [0] NCCL INFO init.cc:224 Cuda Host Alloc Size 4 pointer 0x7f49fd000000
gpu02:35637:35723 [0] NCCL INFO === System : maxWidth 0.2 totalWidth 12.0 ===
gpu02:35637:35723 [0] NCCL INFO CPU/0 (1/1/2)
gpu02:35637:35723 [0] NCCL INFO + PCI[12.0] - PCI/18000 (10b5979710b59797)
gpu02:35637:35723 [0] NCCL INFO               + PCI[12.0] - GPU/1B000 (1)
gpu02:35637:35723 [0] NCCL INFO + PCI[6.0] - PCI/5F000 (808637c080860000)
gpu02:35637:35723 [0] NCCL INFO              + PCI[0.2] - NIC/61000
gpu02:35637:35723 [0] NCCL INFO                           + NET[1.2] - NET/0 (0/0/1.250000)
gpu02:35637:35723 [0] NCCL INFO ==========================================
gpu02:35637:35723 [0] NCCL INFO GPU/1B000 :GPU/1B000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) NET/0 (5/0.187500/PHB) 
gpu02:35637:35723 [0] NCCL INFO NET/0 :GPU/1B000 (5/0.187500/PHB) CPU/0 (3/0.187500/PHB) NET/0 (0/5000.000000/LOC) 
gpu02:35637:35723 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
gpu02:35637:35723 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 0.120000/0.120000, type LOC/PHB, sameChannels 1
gpu02:35637:35723 [0] NCCL INFO  0 : NET/0 GPU/1 NET/0
gpu02:35637:35723 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 0.240000/0.120000, type LOC/PHB, sameChannels 1
gpu02:35637:35723 [0] NCCL INFO  0 : NET/0 GPU/1 NET/0
gpu02:35637:35723 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
gpu01:351578:352168 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 7000 / HCA 0 (distance 7 > 4)
gpu01:351578:352168 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 7000 / HCA 0 (distance 7 > 4)
gpu01:351578:352168 [0] NCCL INFO === System : maxWidth 1.2 totalWidth 264.0 ===
gpu01:351578:352168 [0] NCCL INFO CPU/3 (1/2/-1)
gpu01:351578:352168 [0] NCCL INFO + SYS[5000.0] - CPU/4
gpu01:351578:352168 [0] NCCL INFO + PCI[24.0] - PCI/1000 (1000c01010000000)
gpu01:351578:352168 [0] NCCL INFO               + PCI[24.0] - PCI/5000 (1000c01010de13b8)
gpu01:351578:352168 [0] NCCL INFO                             + PCI[24.0] - GPU/7000 (0)
gpu01:351578:352168 [0] NCCL INFO                                           + NVL[264.0] - NVS/0
gpu01:351578:352168 [0] NCCL INFO CPU/4 (1/2/-1)
gpu01:351578:352168 [0] NCCL INFO + SYS[5000.0] - CPU/3
gpu01:351578:352168 [0] NCCL INFO + PCI[24.0] - NIC/E1000
gpu01:351578:352168 [0] NCCL INFO               + NET[1.2] - NET/0 (107d0a0003a1420c/1/1.250000)
gpu01:351578:352168 [0] NCCL INFO ==========================================
gpu01:351578:352168 [0] NCCL INFO GPU/7000 :GPU/7000 (0/5000.000000/LOC) CPU/3 (3/24.000000/PHB) CPU/4 (4/24.000000/SYS) NET/0 (6/1.250000/SYS) 
gpu01:351578:352168 [0] NCCL INFO NET/0 :GPU/7000 (6/1.250000/SYS) CPU/3 (3/1.250000/SYS) CPU/4 (2/1.250000/PHB) NET/0 (0/5000.000000/LOC) 
gpu01:351578:352168 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 1.200000/1.200000, type LOC/SYS, sameChannels 1
gpu01:351578:352168 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
gpu01:351578:352168 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 2.400000/1.200000, type LOC/SYS, sameChannels 1
gpu01:351578:352168 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
gpu01:351578:352168 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
gpu01:351578:352168 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/-1/-1
gpu01:351578:352168 [0] NCCL INFO Tree 1 : 1 -> 0 -> -1/-1/-1
gpu01:351578:352168 [0] NCCL INFO Channel 00/02 :    0   1
gpu01:351578:352168 [0] NCCL INFO Channel 01/02 :    0   1
gpu01:351578:352168 [0] NCCL INFO Ring 00 : 1 -> 0 -> 1
gpu01:351578:352168 [0] NCCL INFO Ring 01 : 1 -> 0 -> 1
gpu01:351578:352168 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
gpu02:35637:35723 [0] NCCL INFO Tree 0 : 0 -> 1 -> -1/-1/-1
gpu02:35637:35723 [0] NCCL INFO Tree 1 : -1 -> 1 -> 0/-1/-1
gpu02:35637:35723 [0] NCCL INFO Ring 00 : 0 -> 1 -> 0
gpu02:35637:35723 [0] NCCL INFO Ring 01 : 0 -> 1 -> 0
gpu02:35637:35723 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
gpu01:351578:352168 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7f0baaa00000
gpu01:351578:352168 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1824 pointer 0x7f0baaa00200
gpu01:351578:352168 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7f0baa800200
gpu01:351578:352168 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7f0baaa00a00
gpu01:351578:352168 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1824 pointer 0x7f0baaa00c00
gpu02:35637:35723 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7f49fd200000
gpu02:35637:35723 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1824 pointer 0x7f49fd200200
gpu02:35637:35723 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7f49fd000200
gpu01:351578:352168 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7f0baac00000
gpu02:35637:35723 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7f49fd200a00
gpu01:351578:352168 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 7000 / HCA 0 (distance 7 > 4)
gpu02:35637:35723 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1824 pointer 0x7f49fd200c00
gpu01:351578:352213 [0] NCCL INFO Mem Realloc old size 0, new size 8 pointer 0x7f0bac000b60
gpu01:351578:352213 [0] NCCL INFO New proxy recv connection 0 from local rank 0, transport 2
gpu01:351578:352168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f0bac008d20
gpu01:351578:352168 [0] NCCL INFO Channel 00/0 : 1[1b000] -> 0[7000] [receive] via NET/IB/0
gpu01:351578:352168 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 7000 / HCA 0 (distance 7 > 4)
gpu01:351578:352213 [0] NCCL INFO New proxy recv connection 1 from local rank 0, transport 2
gpu01:351578:352168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f0bac008d58
gpu01:351578:352168 [0] NCCL INFO Channel 01/0 : 1[1b000] -> 0[7000] [receive] via NET/IB/0
gpu01:351578:352168 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 7000 / HCA 0 (distance 7 > 4)
gpu01:351578:352213 [0] NCCL INFO New proxy send connection 2 from local rank 0, transport 2
gpu01:351578:352168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f0bac008d90
gpu01:351578:352168 [0] NCCL INFO Channel 00/0 : 0[7000] -> 1[1b000] [send] via NET/IB/0
gpu01:351578:352168 [0] NCCL INFO GPU Direct RDMA Disabled for GPU 7000 / HCA 0 (distance 7 > 4)
gpu01:351578:352213 [0] NCCL INFO New proxy send connection 3 from local rank 0, transport 2
gpu01:351578:352168 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f0bac008dc8
gpu01:351578:352168 [0] NCCL INFO Channel 01/0 : 0[7000] -> 1[1b000] [send] via NET/IB/0
gpu02:35637:35723 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7f49fd400000
gpu02:35637:35724 [0] NCCL INFO Mem Realloc old size 0, new size 8 pointer 0x7f49f8008c70
gpu02:35637:35724 [0] NCCL INFO New proxy recv connection 0 from local rank 0, transport 2
gpu02:35637:35723 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f49f8008c90
gpu02:35637:35723 [0] NCCL INFO Channel 00/0 : 0[7000] -> 1[1b000] [receive] via NET/Socket/0
gpu02:35637:35723 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f49f8008cc8
gpu02:35637:35724 [0] NCCL INFO New proxy recv connection 1 from local rank 0, transport 2
gpu02:35637:35723 [0] NCCL INFO Channel 01/0 : 0[7000] -> 1[1b000] [receive] via NET/Socket/0
gpu02:35637:35724 [0] NCCL INFO New proxy send connection 2 from local rank 0, transport 2
gpu02:35637:35723 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f49f8008d00
gpu02:35637:35723 [0] NCCL INFO Channel 00/0 : 1[1b000] -> 0[7000] [send] via NET/Socket/0
gpu02:35637:35724 [0] NCCL INFO New proxy send connection 3 from local rank 0, transport 2
gpu02:35637:35723 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f49f8008d38
gpu02:35637:35723 [0] NCCL INFO Channel 01/0 : 1[1b000] -> 0[7000] [send] via NET/Socket/0
gpu01:351578:352213 [0] NCCL INFO transport/net_ib.cc:570 Ib Alloc Size 26560 pointer 0x7f0bac025000
gpu01:351578:352213 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 356 mtu 3 GID 0 (80FE/117D0AFEFFA1420E)
gpu01:351578:352213 [0] NCCL INFO transport/net_ib.cc:627 Ib Alloc Size 552 pointer 0x7f0bac047000
gpu01:351578:352213 [0] NCCL INFO transport/net.cc:563 Cuda Host Alloc Size 9641984 pointer 0x7f0baae00000
gpu01:351578:352213 [0] NCCL INFO Mem Realloc old size 0, new size 768 pointer 0x7f0bac0340a0
gpu01:351578:352213 [0] NCCL INFO transport/net_ib.cc:570 Ib Alloc Size 26560 pointer 0x7f0bac049000
gpu01:351578:352213 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 357 mtu 3 GID 0 (80FE/117D0AFEFFA1420E)
gpu01:351578:352213 [0] NCCL INFO transport/net_ib.cc:627 Ib Alloc Size 552 pointer 0x7f0bac060000
gpu01:351578:352213 [0] NCCL INFO transport/net.cc:563 Cuda Host Alloc Size 9641984 pointer 0x7f0ba2000000
gpu01:351578:352213 [0] NCCL INFO transport/net_ib.cc:657 Ib Alloc Size 21688 pointer 0x7f0bac062000
gpu01:351578:352213 [0] NCCL INFO transport/net_ib.cc:671 Ib Alloc Size 552 pointer 0x7f0bac069000
gpu02:35637:35724 [0] NCCL INFO transport/net.cc:563 Cuda Host Alloc Size 9641984 pointer 0x7f49fd600000
gpu02:35637:35724 [0] NCCL INFO transport/net.cc:563 Cuda Host Alloc Size 9641984 pointer 0x7f49f2000000
gpu02:35637:35724 [0] NCCL INFO transport/net.cc:673 Cuda Host Alloc Size 9641984 pointer 0x7f49f2a00000
gpu02:35637:35724 [0] NCCL INFO transport/net.cc:673 Cuda Host Alloc Size 9641984 pointer 0x7f49f3400000
gpu02:35637:35723 [0] NCCL INFO Connected all rings
gpu02:35637:35723 [0] NCCL INFO Connected all trees
gpu02:35637:35723 [0] NCCL INFO NCCL_PROTO set by environment to SIMPLE
gpu02:35637:35723 [0] NCCL INFO NCCL_ALGO set by environment to Tree
gpu02:35637:35723 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
gpu02:35637:35723 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
gpu02:35637:35724 [0] NCCL INFO New proxy send connection 4 from local rank 0, transport 2
gpu02:35637:35723 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7f49f8008d70
gpu02:35637:35723 [0] NCCL INFO init.cc:276 Cuda Alloc Size 16424 pointer 0x7f49fd201400
gpu02:35637:35724 [0] NCCL INFO transport/net.cc:377 Cuda Alloc Size 4194304 pointer 0x7f49f0000000
gpu02:35637:35723 [0] NCCL INFO comm 0x7f49f4008fb0 rank 1 nranks 2 cudaDev 0 busId 1b000 - Init COMPLETE
gpu02:35637:35637 [0] NCCL INFO Broadcast: opCount 0 sendbuff 0x7f4a05200000 recvbuff 0x7f4a05200000 count 8 datatype 0 op 0 root 0 comm 0x7f49f4008fb0 [nranks=2] stream 0x559fe633aa50

gpu02:35637:35725 [0] transport/net_socket.cc:503 NCCL WARN NET/Socket : peer 10.10.10.2<54150> message truncated : receiving 16777216 bytes instead of 524288. If you believe your socket network is in healthy state,           there may be a mismatch in collective sizes or environment settings (e.g. NCCL_PROTO, NCCL_ALGO) between ranks
gpu02:35637:35725 [0] NCCL INFO include/net.h:32 -> 5
gpu02:35637:35725 [0] NCCL INFO transport/net.cc:996 -> 5
gpu02:35637:35725 [0] NCCL INFO proxy.cc:494 -> 5
gpu02:35637:35725 [0] NCCL INFO proxy.cc:614 -> 5 [Proxy Thread]
```

**Comment by itzsimpl** [comment]
Just if it helps the same setup, but with NCCL 2.11.4+cuda11.4 and `NCCL_NET=Socket` works
```
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.

----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

gpu01:124172:124172 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:124172:124172 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu01:124172:124172 [0] NCCL INFO Bootstrap : Using enp225s0f1:10.10.10.2<0>
gpu01:124172:124172 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu01:124172:124172 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu01:124172:124172 [0] NCCL INFO NET/Socket : Using [0]enp225s0f1:10.10.10.2<0>
gpu01:124172:124172 [0] NCCL INFO Using network Socket
NCCL version 2.11.4+cuda11.4
gpu01:124172:124452 [0] NCCL INFO init.cc:290 Cuda Host Alloc Size 4 pointer 0x7fe79ac00000
gpu02:20868:20868 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu02:20868:20868 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu02:20868:20868 [0] NCCL INFO Bootstrap : Using eno1:10.10.10.3<0>
gpu02:20868:20868 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en
gpu02:20868:20868 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en
gpu02:20868:20868 [0] NCCL INFO NET/Socket : Using [0]eno1:10.10.10.3<0>
gpu02:20868:20868 [0] NCCL INFO Using network Socket
gpu02:20868:20914 [0] NCCL INFO init.cc:290 Cuda Host Alloc Size 4 pointer 0x7fea9a000000
gpu02:20868:20914 [0] NCCL INFO Attribute coll of node net not found
gpu02:20868:20914 [0] NCCL INFO === System : maxWidth 0.2 totalWidth 12.0 ===
gpu02:20868:20914 [0] NCCL INFO CPU/0 (1/1/2)
gpu02:20868:20914 [0] NCCL INFO + PCI[12.0] - PCI/18000 (10b5979710b59797)
gpu02:20868:20914 [0] NCCL INFO               + PCI[12.0] - GPU/1B000 (1)
gpu02:20868:20914 [0] NCCL INFO + PCI[6.0] - PCI/5F000 (808637c080860000)
gpu02:20868:20914 [0] NCCL INFO              + PCI[0.2] - NIC/61000
gpu02:20868:20914 [0] NCCL INFO                           + NET[1.2] - NET/0 (0/0/1.250000)
gpu02:20868:20914 [0] NCCL INFO ==========================================
gpu02:20868:20914 [0] NCCL INFO GPU/1B000 :GPU/1B000 (0/5000.000000/LOC) CPU/0 (2/12.000000/PHB) NET/0 (5/0.187500/PHB) 
gpu02:20868:20914 [0] NCCL INFO NET/0 :GPU/1B000 (5/0.187500/PHB) CPU/0 (3/0.187500/PHB) NET/0 (0/5000.000000/LOC) 
gpu02:20868:20914 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 0.120000/0.120000, type LOC/PHB, sameChannels 1
gpu02:20868:20914 [0] NCCL INFO  0 : NET/0 GPU/1 NET/0
gpu02:20868:20914 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 0.240000/0.120000, type LOC/PHB, sameChannels 1
gpu02:20868:20914 [0] NCCL INFO  0 : NET/0 GPU/1 NET/0
gpu02:20868:20914 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
gpu01:124172:124452 [0] NCCL INFO Attribute coll of node net not found
gpu01:124172:124452 [0] NCCL INFO === System : maxWidth 1.2 totalWidth 264.0 ===
gpu01:124172:124452 [0] NCCL INFO CPU/3 (1/2/-1)
gpu01:124172:124452 [0] NCCL INFO + SYS[5000.0] - CPU/4
gpu01:124172:124452 [0] NCCL INFO + PCI[24.0] - PCI/1000 (1000c01010000000)
gpu01:124172:124452 [0] NCCL INFO               + PCI[24.0] - PCI/5000 (1000c01010de13b8)
gpu01:124172:124452 [0] NCCL INFO                             + PCI[24.0] - GPU/7000 (0)
gpu01:124172:124452 [0] NCCL INFO                                           + NVL[264.0] - NVS/0
gpu01:124172:124452 [0] NCCL INFO CPU/4 (1/2/-1)
gpu01:124172:124452 [0] NCCL INFO + SYS[5000.0] - CPU/3
gpu01:124172:124452 [0] NCCL INFO + PCI[24.0] - NIC/E1000
gpu01:124172:124452 [0] NCCL INFO               + NET[1.2] - NET/0 (0/0/1.250000)
gpu01:124172:124452 [0] NCCL INFO ==========================================
gpu01:124172:124452 [0] NCCL INFO GPU/7000 :GPU/7000 (0/5000.000000/LOC) CPU/3 (3/24.000000/PHB) CPU/4 (4/24.000000/SYS) NET/0 (6/1.250000/SYS) 
gpu01:124172:124452 [0] NCCL INFO NET/0 :GPU/7000 (6/1.250000/SYS) CPU/3 (3/1.250000/SYS) CPU/4 (2/1.250000/PHB) NET/0 (0/5000.000000/LOC) 
gpu01:124172:124452 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 1.200000/1.200000, type LOC/SYS, sameChannels 1
gpu01:124172:124452 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
gpu01:124172:124452 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 1, speed 2.400000/1.200000, type LOC/SYS, sameChannels 1
gpu01:124172:124452 [0] NCCL INFO  0 : NET/0 GPU/0 NET/0
gpu01:124172:124452 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type LOC/PIX, sameChannels 1
gpu01:124172:124452 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/-1/-1
gpu01:124172:124452 [0] NCCL INFO Tree 1 : 1 -> 0 -> -1/-1/-1
gpu01:124172:124452 [0] NCCL INFO Channel 00/02 :    0   1
gpu01:124172:124452 [0] NCCL INFO Channel 01/02 :    0   1
gpu01:124172:124452 [0] NCCL INFO Ring 00 : 1 -> 0 -> 1
gpu01:124172:124452 [0] NCCL INFO Ring 01 : 1 -> 0 -> 1
gpu01:124172:124452 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
gpu02:20868:20914 [0] NCCL INFO Tree 0 : 0 -> 1 -> -1/-1/-1
gpu02:20868:20914 [0] NCCL INFO Tree 1 : -1 -> 1 -> 0/-1/-1
gpu02:20868:20914 [0] NCCL INFO Ring 00 : 0 -> 1 -> 0
gpu02:20868:20914 [0] NCCL INFO Ring 01 : 0 -> 1 -> 0
gpu02:20868:20914 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1
gpu02:20868:20914 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
gpu02:20868:20914 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7fea9a200000
gpu02:20868:20914 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1728 pointer 0x7fea9a200200
gpu02:20868:20914 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7fea9a000200
gpu02:20868:20914 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7fea9a200a00
gpu02:20868:20914 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1728 pointer 0x7fea9a200c00
gpu02:20868:20914 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7fea9a400000
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:142 Cuda Host Alloc Size 4104 pointer 0x7fea9a100200
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:143 Cuda Host Alloc Size 4104 pointer 0x7fea9a101400
gpu01:124172:124452 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7fe79ae00000
gpu01:124172:124452 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1728 pointer 0x7fe79ae00200
gpu01:124172:124452 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7fe79ac00200
gpu01:124172:124452 [0] NCCL INFO channel.cc:20 Cuda Alloc Size 8 pointer 0x7fe79ae00a00
gpu01:124172:124452 [0] NCCL INFO channel.cc:24 Cuda Alloc Size 1728 pointer 0x7fe79ae00c00
gpu01:124172:124452 [0] NCCL INFO channel.cc:34 Cuda Host Alloc Size 1048576 pointer 0x7fe79b000000
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:142 Cuda Host Alloc Size 4104 pointer 0x7fe79ad00200
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:143 Cuda Host Alloc Size 4104 pointer 0x7fe79ad01400
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:184 Cuda Host Alloc Size 9633792 pointer 0x7fea9a600000
gpu02:20868:20914 [0] NCCL INFO Channel 00 : 0[7000] -> 1[1b000] [receive] via NET/Socket/0
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:142 Cuda Host Alloc Size 4104 pointer 0x7fea9a102600
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:143 Cuda Host Alloc Size 4104 pointer 0x7fea9a103800
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:184 Cuda Host Alloc Size 9633792 pointer 0x7fe79b200000
gpu01:124172:124452 [0] NCCL INFO Channel 00 : 1[1b000] -> 0[7000] [receive] via NET/Socket/0
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:142 Cuda Host Alloc Size 4104 pointer 0x7fe79ad02600
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:143 Cuda Host Alloc Size 4104 pointer 0x7fe79ad03800
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:184 Cuda Host Alloc Size 9633792 pointer 0x7fea9b000000
gpu02:20868:20914 [0] NCCL INFO Channel 01 : 0[7000] -> 1[1b000] [receive] via NET/Socket/0
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:81 Cuda Host Alloc Size 4104 pointer 0x7fea9a104a00
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:82 Cuda Host Alloc Size 4104 pointer 0x7fea9a105c00
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:184 Cuda Host Alloc Size 9633792 pointer 0x7fe79bc00000
gpu01:124172:124452 [0] NCCL INFO Channel 01 : 1[1b000] -> 0[7000] [receive] via NET/Socket/0
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:81 Cuda Host Alloc Size 4104 pointer 0x7fe79ad04a00
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:82 Cuda Host Alloc Size 4104 pointer 0x7fe79ad05c00
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:108 Cuda Host Alloc Size 9633792 pointer 0x7fea8e000000
gpu02:20868:20914 [0] NCCL INFO Channel 00 : 1[1b000] -> 0[7000] [send] via NET/Socket/0
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:81 Cuda Host Alloc Size 4104 pointer 0x7fea9a106e00
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:82 Cuda Host Alloc Size 4104 pointer 0x7fea9a108000
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:108 Cuda Host Alloc Size 9633792 pointer 0x7fe79c600000
gpu01:124172:124452 [0] NCCL INFO Channel 00 : 0[7000] -> 1[1b000] [send] via NET/Socket/0
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:81 Cuda Host Alloc Size 4104 pointer 0x7fe79ad06e00
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:82 Cuda Host Alloc Size 4104 pointer 0x7fe79ad08000
gpu02:20868:20914 [0] NCCL INFO transport/net.cc:108 Cuda Host Alloc Size 9633792 pointer 0x7fea8ea00000
gpu02:20868:20914 [0] NCCL INFO Channel 01 : 1[1b000] -> 0[7000] [send] via NET/Socket/0
gpu01:124172:124452 [0] NCCL INFO transport/net.cc:108 Cuda Host Alloc Size 9633792 pointer 0x7fe79d000000
gpu01:124172:124452 [0] NCCL INFO Channel 01 : 0[7000] -> 1[1b000] [send] via NET/Socket/0
gpu01:124172:124452 [0] NCCL INFO Connected all rings
gpu01:124172:124452 [0] NCCL INFO Connected all trees
gpu02:20868:20914 [0] NCCL INFO Connected all rings
gpu01:124172:124452 [0] NCCL INFO Latency/AlgBw |    Tree/    LL |    Tree/ LL128 |    Tree/Simple |    Ring/    LL |    Ring/ LL128 |    Ring/Simple | CollNet/    LL | CollNet/ LL128 | CollNet/Simple |
gpu01:124172:124452 [0] NCCL INFO  Max NThreads |            512 |            640 |            512 |            512 |            640 |            256 |            512 |            640 |            512 |
gpu01:124172:124452 [0] NCCL INFO     Broadcast |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.0 |    14.0/   0.0 |    18.0/   0.1 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
gpu01:124172:124452 [0] NCCL INFO        Reduce |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.0 |    14.0/   0.0 |    18.0/   0.1 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
gpu01:124172:124452 [0] NCCL INFO     AllGather |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.1 |    14.0/   0.0 |    18.0/   0.2 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
gpu02:20868:20914 [0] NCCL INFO Connected all trees
gpu01:124172:124452 [0] NCCL INFO ReduceScatter |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.1 |    14.0/   0.0 |    18.0/   0.2 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
gpu02:20868:20914 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
gpu02:20868:20914 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
gpu01:124172:124452 [0] NCCL INFO     AllReduce |    14.4/   0.0 |    21.4/   0.0 |    56.0/   0.1 |     9.0/   0.0 |    18.0/   0.0 |    27.6/   0.1 |     9.4/   0.0 |     9.4/   0.0 |    10.7/   0.0 |
gpu01:124172:124452 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
gpu01:124172:124452 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
gpu02:20868:20914 [0] NCCL INFO init.cc:345 Cuda Alloc Size 16424 pointer 0x7fea9a201400
gpu02:20868:20914 [0] NCCL INFO comm 0x7fea94008fb0 rank 1 nranks 2 cudaDev 0 busId 1b000 - Init COMPLETE
gpu01:124172:124452 [0] NCCL INFO init.cc:345 Cuda Alloc Size 16424 pointer 0x7fe79ae01400
gpu01:124172:124452 [0] NCCL INFO comm 0x7fe748008fb0 rank 0 nranks 2 cudaDev 0 busId 7000 - Init COMPLETE
gpu01:124172:124172 [0] NCCL INFO AllReduce: opCount 0 sendbuff 0x7fe797000000 recvbuff 0x7fe797000000 count 1 datatype 1 op 0 root 0 comm 0x7fe748008fb0 [nranks=2] stream 0x5579fb9b3280
gpu02:20868:20868 [0] NCCL INFO AllReduce: opCount 0 sendbuff 0x7feacdc00000 recvbuff 0x7feacdc00000 count 1 datatype 1 op 0 root 0 comm 0x7fea94008fb0 [nranks=2] stream 0x556636ffb5b0
gpu01:124172:124172 [0] NCCL INFO Launch mode Parallel
gpu01:124172:124172 [0] NCCL INFO AllReduce: opCount 1 sendbuff 0x7fe797000000 recvbuff 0x7fe797000000 count 1 datatype 1 op 0 root 0 comm 0x7fe748008fb0 [nranks=2] stream 0x5579fb9b3280
gpu02:20868:20868 [0] NCCL INFO AllReduce: opCount 1 sendbuff 0x7feacdc00000 recvbuff 0x7feacdc00000 count 1 datatype 1 op 0 root 0 comm 0x7fea94008fb0 [nranks=2] stream 0x556636ffb5b0
...
```

**Comment by AddyLaddy** [comment]
I notice in the failing trace:

```
gpu02:35637:35723 [0] NCCL INFO NCCL_PROTO set by environment to SIMPLE
gpu02:35637:35723 [0] NCCL INFO NCCL_ALGO set by environment to Tree
```

But only from one rank. Are you setting identical env vars for each rank?
I don't see those env vars being set in the 2nd trace .

Also why do you need to force the ALGO/PROTO ?

**Comment by itzsimpl** [comment]
Yes I am. I added the two env vars only because of the final WARN message in trace 1, with or without them the result is the same. I am running this on a SLURM cluster with 2 nodes, one DGX-A100 (gpu01) and one noname (gpu02). The task is a script which sets all env vars and then runs nemo:1.8.0 (pytorch:22.03) training. Interestingly the same happens if I try to set `NCCL_IB_DISABLE`, i.e. it simply does not get listed as set on the DGX-A100 (gpu01). 

If I compare the two traces I also notice that in the failing trace 
```
gpu01:351578:351578 [0] NCCL INFO NET/IB : Using [0]mlx5_9:1/RoCE [RO]; OOB enp225s0f1:10.10.10.2<0>
gpu01:351578:351578 [0] NCCL INFO Using network IB
gpu02:35637:35637 [0] NCCL INFO NET/Socket : Using [0]eno1:10.10.10.3<0>
gpu02:35637:35637 [0] NCCL INFO Using network Socket
```
but in the working one (due to `NCCL_NET=Socket` with NCCL 2.11.4+cuda11.4)
```
gpu01:124172:124172 [0] NCCL INFO NET/Socket : Using [0]enp225s0f1:10.10.10.2<0>
gpu01:124172:124172 [0] NCCL INFO Using network Socket
gpu02:20868:20868 [0] NCCL INFO NET/Socket : Using [0]eno1:10.10.10.3<0>
gpu02:20868:20868 [0] NCCL INFO Using network Socket
```
However, as said, if I try to set `NCCL_NET=Socket` on NCCL 2.12.9+cuda11.6 I get a segmentation fault on the DGX-A100 (gpu01).

**Comment by sjeaugey** [comment]
In your attempt to set NCCL_IBEXT_DISABLE=1, one of the nodes falls back on IB and the other one falls back on socket because it has no IB NIC. So in your case, you would need to set both  `NCCL_IBEXT_DISABLE=1` and `NCCL_IB_DISABLE=1` to disable both the external plugin and the internal IB plugin.

I'll take a look at the crash with 2.12 when setting `NCCL_NET=Socket`.

**Comment by itzsimpl** [comment]
Thank you very much for the help. Using the following settings solves the issue, both systems select Socket;
```
NCCL_IB_DISABLE=1
NCCL_IBEXT_DISABLE=1
```
Just out of curiosity, how come `NCCL_IBEXT_DISABLE` is not mentioned in https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html.

**Comment by sjeaugey** [comment]
> Just out of curiosity, how come NCCL_IBEXT_DISABLE is not mentioned in https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html.
That environment variable comes from the external IB plugin, not from NCCL itself; that's why it's not in the NCCL doc.

**Comment by itzsimpl** [comment]
I see, it may still be worth mentioning it as it has quite an effect on nccl. Thank you for the help; I think we can close the issue now, or should we leave it open until the patch gets merged?

**Comment by sjeaugey** [comment]
We'll fix the bug in a future release. Let me know if you want us to push the fix to the master branch right away -- we can do that. But if you feel your problem is solved feel free to close the issue.

Thanks!

**Comment by itzsimpl** [comment]
I'm ok, as long as I have a workaround, I can wait for the fix to be integrated in a future release and propagated to other packages. I'll close the issue, thank you very much for the help.
