### ISSUE TITLE
ncclSystemError: System call (socket, malloc, munmap, etc) failed when training on two remote nodes

### ISSUE THREAD

**Issue by lcsdn** [NVIDIA/nccl#697]
#### Description

I am getting this NCCL error when trying to train a model on two remote nodes with [Torchrun](https://pytorch.org/docs/stable/elastic/run.html):

```
RuntimeError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1229, unhandled system error, NCCL version 2.12.10
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1050) of binary: /opt/conda/bin/python
```

#### To reproduce

I am using this example from the HuggingFace transformers library: https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/examples/pytorch/summarization/run_summarization.py

I am running the script with the Docker image `nvcr.io/nvidia/pytorch:22.04-py3` where I installed `datasets==2.3.2 transformers==4.20.1 rouge_score==0.0.4`. On both machines the Docker container is allocated only one GPU.

This is the command used to run the script:
```
torchrun \
    --nnodes=2 \
    --nproc_per_node=1 \
    --rdzv_backend=c10d \
    --rdzv_id=100 \
    --rdzv_endpoint=dgxa100 \
    run_summarization.py \
    --model_name_or_path t5-small \
    --do_train \
    --do_eval \
    --dataset_name cnn_dailymail \
    --dataset_config "3.0.0" \
    --source_prefix "summarize: " \
    --output_dir /tmp/tst-summarization \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate
```

#### Full output

This the full output on the host node, when running with `NCCL_DEBUG=INFO`:
```
dgxa100:1050:1050 [0] NCCL INFO Bootstrap : Using bond0:192.168.1.202<0>
dgxa100:1050:1050 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
dgxa100:1050:1050 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
dgxa100:1050:1050 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
dgxa100:1050:1050 [0] NCCL INFO P2P plugin IBext
dgxa100:1050:1050 [0] NCCL INFO NET/IB : No device found.
dgxa100:1050:1050 [0] NCCL INFO NET/IB : No device found.
dgxa100:1050:1050 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.1.202<0> [1]bmc_redfish0:169.254.0.18<0> [2]br-dafa450901ab:172.25.0.1<0> [3]veth4785452:fe80::ccb:61ff:fecc:70e6%veth4785452<0> [4]veth443b9ce:fe80::2848:4aff:feeb:9ca4%veth443b9ce<0> [5]veth20b89e8:fe80::acb0:46ff:fe5b:6d93%veth20b89e8<0> [6]veth9345bae:fe80::d843:48ff:fe43:1067%veth9345bae<0> [7]veth6c9382a:fe80::74cc:b4ff:fedd:e0d0%veth6c9382a<0>
dgxa100:1050:1050 [0] NCCL INFO Using network Socket
NCCL version 2.12.10+cuda11.6
dgxa100:1050:1315 [0] NCCL INFO Setting affinity for GPU 0 to ffff0000,00000000,00000000,00000000,ffff0000,00000000,00000000,00000000
dgxa100:1050:1315 [0] NCCL INFO Channel 00/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 01/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 02/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 03/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 04/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 05/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 06/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 07/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 08/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 09/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 10/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 11/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 12/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 13/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 14/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Channel 15/16 :    0   1
dgxa100:1050:1315 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] 1/-1/-1->0->-1 [6] 1/-1/-1->0->-1 [7] 1/-1/-1->0->-1 [8] -1/-1/-1->0->1 [9] -1/-1/-1->0->1 [10] -1/-1/-1->0->1 [11] -1/-1/-1->0->1 [12] -1/-1/-1->0->1 [13] -1/-1/-1->0->1 [14] -1/-1/-1->0->1 [15] -1/-1/-1->0->1
dgxa100:1050:1315 [0] NCCL INFO Channel 00/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/0
dgxa100:1050:1315 [0] NCCL INFO Channel 01/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/1
dgxa100:1050:1315 [0] NCCL INFO Channel 02/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/2
dgxa100:1050:1315 [0] NCCL INFO Channel 03/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/3
dgxa100:1050:1315 [0] NCCL INFO Channel 04/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/4
dgxa100:1050:1315 [0] NCCL INFO Channel 05/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/5
dgxa100:1050:1315 [0] NCCL INFO Channel 06/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/6
dgxa100:1050:1315 [0] NCCL INFO Channel 07/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/7
dgxa100:1050:1315 [0] NCCL INFO Channel 08/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/0
dgxa100:1050:1315 [0] NCCL INFO Channel 09/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/1
dgxa100:1050:1315 [0] NCCL INFO Channel 10/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/2
dgxa100:1050:1315 [0] NCCL INFO Channel 11/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/3
dgxa100:1050:1315 [0] NCCL INFO Channel 12/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/4
dgxa100:1050:1315 [0] NCCL INFO Channel 13/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/5
dgxa100:1050:1315 [0] NCCL INFO Channel 14/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/6
dgxa100:1050:1315 [0] NCCL INFO Channel 15/0 : 1[1000] -> 0[90000] [receive] via NET/Socket/7
dgxa100:1050:1315 [0] NCCL INFO Channel 00/0 : 0[90000] -> 1[1000] [send] via NET/Socket/0
dgxa100:1050:1315 [0] NCCL INFO Channel 01/0 : 0[90000] -> 1[1000] [send] via NET/Socket/1
dgxa100:1050:1315 [0] NCCL INFO Channel 02/0 : 0[90000] -> 1[1000] [send] via NET/Socket/2
dgxa100:1050:1315 [0] NCCL INFO Channel 03/0 : 0[90000] -> 1[1000] [send] via NET/Socket/3
dgxa100:1050:1315 [0] NCCL INFO Channel 04/0 : 0[90000] -> 1[1000] [send] via NET/Socket/4
dgxa100:1050:1315 [0] NCCL INFO Channel 05/0 : 0[90000] -> 1[1000] [send] via NET/Socket/5
dgxa100:1050:1315 [0] NCCL INFO Channel 06/0 : 0[90000] -> 1[1000] [send] via NET/Socket/6
dgxa100:1050:1315 [0] NCCL INFO Channel 07/0 : 0[90000] -> 1[1000] [send] via NET/Socket/7
dgxa100:1050:1315 [0] NCCL INFO Channel 08/0 : 0[90000] -> 1[1000] [send] via NET/Socket/0
dgxa100:1050:1315 [0] NCCL INFO Channel 09/0 : 0[90000] -> 1[1000] [send] via NET/Socket/1
dgxa100:1050:1315 [0] NCCL INFO Channel 10/0 : 0[90000] -> 1[1000] [send] via NET/Socket/2
dgxa100:1050:1315 [0] NCCL INFO Channel 11/0 : 0[90000] -> 1[1000] [send] via NET/Socket/3
dgxa100:1050:1315 [0] NCCL INFO Channel 12/0 : 0[90000] -> 1[1000] [send] via NET/Socket/4
dgxa100:1050:1315 [0] NCCL INFO Channel 13/0 : 0[90000] -> 1[1000] [send] via NET/Socket/5
dgxa100:1050:1315 [0] NCCL INFO Channel 14/0 : 0[90000] -> 1[1000] [send] via NET/Socket/6
dgxa100:1050:1315 [0] NCCL INFO Channel 15/0 : 0[90000] -> 1[1000] [send] via NET/Socket/7
dgxa100:1050:1316 [0] NCCL INFO include/net.h:25 -> 2
dgxa100:1050:1316 [0] NCCL INFO transport/net.cc:515 -> 2
dgxa100:1050:1316 [0] NCCL INFO proxy.cc:914 -> 2
dgxa100:1050:1316 [0] NCCL INFO proxy.cc:942 -> 2

dgxa100:1050:1316 [0] proxy.cc:1042 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 2

dgxa100:1050:1316 [0] misc/socket.cc:503 NCCL WARN Net : Call to recv from 172.19.0.1<53507> failed : Broken pipe
dgxa100:1050:1316 [0] NCCL INFO misc/socket.cc:520 -> 2
dgxa100:1050:1316 [0] NCCL INFO transport/net_socket.cc:368 -> 2
dgxa100:1050:1316 [0] NCCL INFO include/net.h:25 -> 2
dgxa100:1050:1316 [0] NCCL INFO transport/net.cc:515 -> 2
dgxa100:1050:1316 [0] NCCL INFO proxy.cc:914 -> 2

dgxa100:1050:1316 [0] proxy.cc:1042 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 2

dgxa100:1050:1315 [0] misc/socket.cc:523 NCCL WARN Net : Connection closed by remote peer dgxa100<59017>
dgxa100:1050:1315 [0] NCCL INFO misc/socket.cc:531 -> 2
dgxa100:1050:1315 [0] NCCL INFO misc/socket.cc:543 -> 2
dgxa100:1050:1315 [0] NCCL INFO proxy.cc:805 -> 2

dgxa100:1050:1315 [0] proxy.cc:808 NCCL WARN Proxy Call to rank 0 failed (Connect)
dgxa100:1050:1315 [0] NCCL INFO transport/net.cc:269 -> 2
dgxa100:1050:1315 [0] NCCL INFO transport.cc:127 -> 2
dgxa100:1050:1315 [0] NCCL INFO init.cc:730 -> 2
dgxa100:1050:1315 [0] NCCL INFO init.cc:915 -> 2
dgxa100:1050:1315 [0] NCCL INFO group.cc:57 -> 2 [Async thread]
Traceback (most recent call last):
  File "run_summarization.py", line 734, in <module>
    main()
  File "run_summarization.py", line 546, in main
    train_dataset = train_dataset.map(
  File "/opt/conda/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1554, in main_process_first
    torch.distributed.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2805, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1229, unhandled system error, NCCL version 2.12.10
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1050) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0a0+bd13bc6', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_summarization.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-29_13:53:53
  host      : dgxa100
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1050)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

And this is what I get on the second node:
```
mars:1034:1034 [0] NCCL INFO Bootstrap : Using bond0:192.168.1.161<0>
mars:1034:1034 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v5 symbol.
mars:1034:1034 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v5 symbol.
mars:1034:1034 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
mars:1034:1034 [0] NCCL INFO P2P plugin IBext
mars:1034:1034 [0] NCCL INFO NET/IB : No device found.
mars:1034:1034 [0] NCCL INFO NET/IB : No device found.
mars:1034:1034 [0] NCCL INFO NET/Socket : Using [0]bond0:192.168.1.161<0> [1]br-05ab815fa14e:172.19.0.1<0> [2]br-d5d80d7dbbad:172.21.0.1<0> [3]br-dd40dc616638:172.30.0.1<0> [4]br-e3fd6ba7b530:192.168.16.1<0> [5]br-f286beab47e9:172.24.0.1<0> [6]br-f5798861ef0d:172.20.0.1<0> [7]br-846ccdc1c516:192.168.176.1<0> [8]br-d77707f6d10f:172.29.0.1<0> [9]br-364ef9f0bffe:192.168.192.1<0> [10]br-9aa3d4529a15:172.31.0.1<0> [11]br-46146ba14da2:172.26.0.1<0> [12]veth6163fba:fe80::b878:6cff:fe52:abe2%veth6163fba<0> [13]veth70ec058:fe80::e0:11ff:fec8:925f%veth70ec058<0> [14]veth07ee21a:fe80::3c18:b2ff:fe10:dbe9%veth07ee21a<0> [15]veth9026f58:fe80::1c91:92ff:fe6f:efe4%veth9026f58<0>
mars:1034:1034 [0] NCCL INFO Using network Socket
mars:1034:1297 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,00000000,00000000,ffffffff,ffffffff
mars:1034:1297 [0] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 [2] -1/-1/-1->1->0 [3] -1/-1/-1->1->0 [4] -1/-1/-1->1->0 [5] -1/-1/-1->1->0 [6] -1/-1/-1->1->0 [7] -1/-1/-1->1->0 [8] 0/-1/-1->1->-1 [9] 0/-1/-1->1->-1 [10] 0/-1/-1->1->-1 [11] 0/-1/-1->1->-1 [12] 0/-1/-1->1->-1 [13] 0/-1/-1->1->-1 [14] 0/-1/-1->1->-1 [15] 0/-1/-1->1->-1
mars:1034:1297 [0] NCCL INFO Channel 00/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/0
mars:1034:1297 [0] NCCL INFO Channel 01/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/1
mars:1034:1297 [0] NCCL INFO Channel 02/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/2
mars:1034:1297 [0] NCCL INFO Channel 03/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/3
mars:1034:1297 [0] NCCL INFO Channel 04/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/4
mars:1034:1297 [0] NCCL INFO Channel 05/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/5
mars:1034:1297 [0] NCCL INFO Channel 06/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/6
mars:1034:1297 [0] NCCL INFO Channel 07/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/7
mars:1034:1297 [0] NCCL INFO Channel 08/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/0
mars:1034:1297 [0] NCCL INFO Channel 09/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/1
mars:1034:1297 [0] NCCL INFO Channel 10/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/2
mars:1034:1297 [0] NCCL INFO Channel 11/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/3
mars:1034:1297 [0] NCCL INFO Channel 12/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/4
mars:1034:1297 [0] NCCL INFO Channel 13/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/5
mars:1034:1297 [0] NCCL INFO Channel 14/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/6
mars:1034:1297 [0] NCCL INFO Channel 15/0 : 0[90000] -> 1[1000] [receive] via NET/Socket/7
mars:1034:1297 [0] NCCL INFO Channel 00/0 : 1[1000] -> 0[90000] [send] via NET/Socket/0
mars:1034:1297 [0] NCCL INFO Channel 01/0 : 1[1000] -> 0[90000] [send] via NET/Socket/1
mars:1034:1297 [0] NCCL INFO Channel 02/0 : 1[1000] -> 0[90000] [send] via NET/Socket/2
mars:1034:1297 [0] NCCL INFO Channel 03/0 : 1[1000] -> 0[90000] [send] via NET/Socket/3
mars:1034:1297 [0] NCCL INFO Channel 04/0 : 1[1000] -> 0[90000] [send] via NET/Socket/4
mars:1034:1297 [0] NCCL INFO Channel 05/0 : 1[1000] -> 0[90000] [send] via NET/Socket/5
mars:1034:1297 [0] NCCL INFO Channel 06/0 : 1[1000] -> 0[90000] [send] via NET/Socket/6
mars:1034:1297 [0] NCCL INFO Channel 07/0 : 1[1000] -> 0[90000] [send] via NET/Socket/7
mars:1034:1297 [0] NCCL INFO Channel 08/0 : 1[1000] -> 0[90000] [send] via NET/Socket/0
mars:1034:1297 [0] NCCL INFO Channel 09/0 : 1[1000] -> 0[90000] [send] via NET/Socket/1
mars:1034:1297 [0] NCCL INFO Channel 10/0 : 1[1000] -> 0[90000] [send] via NET/Socket/2
mars:1034:1297 [0] NCCL INFO Channel 11/0 : 1[1000] -> 0[90000] [send] via NET/Socket/3
mars:1034:1297 [0] NCCL INFO Channel 12/0 : 1[1000] -> 0[90000] [send] via NET/Socket/4
mars:1034:1297 [0] NCCL INFO Channel 13/0 : 1[1000] -> 0[90000] [send] via NET/Socket/5
mars:1034:1297 [0] NCCL INFO Channel 14/0 : 1[1000] -> 0[90000] [send] via NET/Socket/6
mars:1034:1297 [0] NCCL INFO Channel 15/0 : 1[1000] -> 0[90000] [send] via NET/Socket/7
mars:1034:1298 [0] NCCL INFO include/net.h:25 -> 2
mars:1034:1298 [0] NCCL INFO transport/net.cc:515 -> 2
mars:1034:1298 [0] NCCL INFO proxy.cc:914 -> 2

mars:1034:1298 [0] proxy.cc:1042 NCCL WARN [Proxy Service 1] Failed to execute operation Connect from rank 1, retcode 2

mars:1034:1297 [0] misc/socket.cc:523 NCCL WARN Net : Connection closed by remote peer mars<59749>
mars:1034:1297 [0] NCCL INFO misc/socket.cc:531 -> 2
mars:1034:1297 [0] NCCL INFO misc/socket.cc:543 -> 2
mars:1034:1297 [0] NCCL INFO proxy.cc:805 -> 2

mars:1034:1297 [0] proxy.cc:808 NCCL WARN Proxy Call to rank 1 failed (Connect)
mars:1034:1297 [0] NCCL INFO transport/net.cc:269 -> 2
mars:1034:1297 [0] NCCL INFO transport.cc:127 -> 2
mars:1034:1297 [0] NCCL INFO init.cc:730 -> 2
mars:1034:1297 [0] NCCL INFO init.cc:915 -> 2
mars:1034:1297 [0] NCCL INFO group.cc:57 -> 2 [Async thread]
Traceback (most recent call last):
  File "run_summarization.py", line 734, in <module>
    main()
  File "run_summarization.py", line 546, in main
    train_dataset = train_dataset.map(
  File "/opt/conda/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1554, in main_process_first
    torch.distributed.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2805, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1229, unhandled system error, NCCL version 2.12.10
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1034) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0a0+bd13bc6', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_summarization.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-29_13:56:03
  host      : mars
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 1034)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by sjeaugey** [comment]
Could you try again setting `NCCL_SOCKET_IFNAME=bond0`? It seems communication is going through sockets and we're trying to use all of these interfaces:
```
INFO NET/Socket : Using
[0]bond0:192.168.1.161<0>
[1]br-05ab815fa14e:172.19.0.1<0>
[2]br-d5d80d7dbbad:172.21.0.1<0>
[3]br-dd40dc616638:172.30.0.1<0>
[4]br-e3fd6ba7b530:192.168.16.1<0>
[5]br-f286beab47e9:172.24.0.1<0>
[6]br-f5798861ef0d:172.20.0.1<0>
[7]br-846ccdc1c516:192.168.176.1<0>
[8]br-d77707f6d10f:172.29.0.1<0>
[9]br-364ef9f0bffe:192.168.192.1<0>
[10]br-9aa3d4529a15:172.31.0.1<0>
[11]br-46146ba14da2:172.26.0.1<0>
[12]veth6163fba:fe80::b878:6cff:fe52:abe2%veth6163fba<0> 
[13]veth70ec058:fe80::e0:11ff:fec8:925f%veth70ec058<0> 
[14]veth07ee21a:fe80::3c18:b2ff:fe10:dbe9%veth07ee21a<0> 
[15]veth9026f58:fe80::1c91:92ff:fe6f:efe4%veth9026f58<0>
```
Is that intended?

**Comment by lcsdn** [comment]
This solved the issue. Thank you!
