### ISSUE TITLE
NCCL hangs after multiple training steps due to network connection

### ISSUE THREAD

**Issue by MrAta** [NVIDIA/nccl#706]
Running horovod with nccl on a k8s cluster with 32 Pods each with 6 V100 GPUs, nccl threads halt in `persistentSocketThread` due to failure in performing `recv`:

```bash
[15]worker-23:83:2526 [0] misc/socket.cc:503 NCCL WARN Net : Call to recv from 100.96.188.199<41468> failed : Connection timed out
[15]worker-23:83:2526 [0] NCCL INFO misc/socket.cc:520 -> 2
[15]23:83:2526 [0] transport/net_socket.cc:219 NCCL WARN NET/Socket : socket progress error
[15]worker-23:83:2520 [0] NCCL INFO include/net.h:32 -> 2
[15]worker-23:83:2520 [0] NCCL INFO transport/net.cc:870 -> 2
[15]worker-23:83:2520 [0] NCCL INFO proxy.cc:494 -> 2
[15]worker-23:83:2520 [0] NCCL INFO proxy.cc:614 -> 2 [Proxy Thread]
```
All of the ranks have this stack trace:
```bash
#0  0x00007f7a2620c965 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib64/libpthread.so.0
#1  0x00007f795f0e179b in persistentSocketThread (args_=0x7f61ac040c10) at transport/net_socket.cc:231
#2  0x00007f7a26208dd5 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007f7a25828ead in clone () from /usr/lib64/libc.so.6
```
and the recv trace:
```bash
#0  0x00007f7a2620fa8b in recv () from /usr/lib64/libpthread.so.0
#1  0x00007f795f0d6f40 in ncclSocketProgressOpt (block=0, closed=<synthetic pointer>, offset=0x7f6e30ff8cc0, size=4, ptr=0x7f6e30ff8cb0, sock=0x7f61ac02f670, op=1) at misc/socket.cc:495
#2  ncclSocketProgress (op=1, sock=0x7f61ac02f670, ptr=ptr@entry=0x7f6e30ff8cb0, size=size@entry=4, offset=offset@entry=0x7f6e30ff8cc0) at misc/socket.cc:520
#3  0x00007f795f0e388f in ncclSocketTest (request=0x7f61ac0302b8, done=0x7f6e30ff91b0, size=0x7f6e30ff9230) at transport/net_socket.cc:493
#4  0x00007f795f0ddf2d in ncclNetTest (sizes=0x7f6e30ff9230, done=0x7f6e30ff91b0, request=<optimized out>) at include/net.h:32
#5  recvProxyProgress (comm=<optimized out>, args=0x7f61a4037fc8) at transport/net.cc:996
#6  0x00007f795f0cc933 in progressOps (idle=<synthetic pointer>, opStart=<optimized out>, state=0x7f795825b4b8, comm=0x7f7958256ff0) at proxy.cc:494
#7  ncclProxyProgress (comm_=0x7f7958256ff0) at proxy.cc:611
#8  0x00007f7a26208dd5 in start_thread () from /usr/lib64/libpthread.so.0
#9  0x00007f7a25828ead in clone () from /usr/lib64/libc.so.6
```

This is while the GPU utilization and GPU memory utilization stays nearly at 100% while no training is going on:
```bash
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   48C    P0    47W / 250W |  30765MiB / 32510MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:60:00.0 Off |                    0 |
| N/A   38C    P0    40W / 250W |  30789MiB / 32510MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  On   | 00000000:61:00.0 Off |                    0 |
| N/A   40C    P0    41W / 250W |  30789MiB / 32510MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   52C    P0    43W / 250W |  30765MiB / 32510MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-PCIE...  On   | 00000000:DA:00.0 Off |                    0 |
| N/A   42C    P0    43W / 250W |  30789MiB / 32510MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-PCIE...  On   | 00000000:DB:00.0 Off |                    0 |
| N/A   45C    P0    43W / 250W |  30789MiB / 32510MiB |    100%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

We are tuning  the number of sockets and socket threads by setting `NCCL_SOCKET_NTHREADS ` and `NCCL_NSOCKS_PERTHREAD`. The issue mostly happens when we set them to 16 and 2 respectively.

**Comment by sjeaugey** [comment]
Regarding the error, this looks like a network timeout, which is currently fatal in NCCL.

However, it should not hang if the application calls ncclCommGetAsyncError() in the busy waiting loop, detects the error, and stops all other ranks (with ncclCommAbort()).

**Comment by Uijeong97** [comment]
I have the same issue. 
how did you solve it?

**Comment by sjeaugey** [comment]
This is inherently a networking issue. Checking the IP address which failed and why the connections to that IP address failed is usually the way to go.

The error can be permanent (a quick check with `nc -l 12345` on one side and `nc hostname 12345` on another node would confirm connection works), or transient. In both cases, this is usually solvable by configuring the IP networking of the nodes differently.
