### ISSUE TITLE
limit bandwidth for testing 

### ISSUE THREAD

**Issue by jkhourybbn** [NVIDIA/nccl#709]
hi folks, 

(this is a followup to #681)

We have 8 GPUs DGX A100 connected to a L3 switch and we force the collective to use the NIC (each GPU paired with one CX-6 NIC 100 gbps) for testing. Testing with the NICs works well with the right env variables, we pass in the topology.

I want to limit the per-NIC bandwidth to 25 gbps and test performance with the reduced bandwidth. Is there a recommended way to do this?

When we limit the port bandwidth on the switch, I see the NICs pick up the correct 25 gbps speed, but the collectives timeout (NCCL 2.8.4). I tested with ib_write_bw and it worked fine

```
g1lmd5:3684924:3685085 [0] transport/net_ib.cc:840 NCCL WARN NET/IB : Got completion with error 12, opcode 32736, len 32736, vendor err 129

g1lmd5:3684922:3685080 [0] transport/net_ib.cc:840 NCCL WARN NET/IB : Got completion with error 12, opcode 32594, len 32594, vendor err 129

....
```
```
mpirun -np 8 -x NCCL_P2P_DISABLE=1 -x NCCL_NET=IB -x NCCL_SHM_DISABLE=1 -x NCCL_IB_GID_INDEX=3 -x NCCL_TOPO_FILE=~/custom_topo.txt -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 -x NCCL_DEBUG=INFO -x NCCL_DEBUG_SUBSYS=ALL ~/nccl-tests/build/all_reduce_perf -b 1M -e 1M -f 2 -g 1 -c 1 -n 200 -w 200 -z 0
```

**Comment by jkhourybbn** [comment]
Was an MTU problem fixed by setting correct MTU

**Comment by sjeaugey** [comment]
Interesting. Thanks for sharing the resolution, I had not thought of that.
