### ISSUE TITLE
nccl with 3 infiniband nics hangs

### ISSUE THREAD

**Issue by JuHyung-Son** [NVIDIA/nccl#719]
I`m trying to run distributed learning with infiniband rdma with a100 on k8s 
I installed gpu operator with 8 a100 gpus and network operator with 3 mellanox nic.

pod yaml (i run with 2pods)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: 8pxb
  namespace: aiplatform-resource
  labels:
    app: 8pxb
spec:
  restartPolicy: OnFailure
  containers:
  - image: image
    name: pod1
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        nvidia.com/gpu: 2
        rdma/rdma_shared_device_a: 1
    command:
    - sh
    - -c
    - |
      sleep 1000099
    volumeMounts:
      - mountPath: /dev/shm
        name: shm
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 10Gi
      name: shm'
```

nvidia-smi topo

pod1
```
(test) root@8pxb:~/stress_test/code# nvidia-smi topo -m
	GPU0	GPU1	mlx5_0	mlx5_1	mlx5_2	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	SYS	SYS	NODE	64-127,192-255	1
GPU1	NV12	 X 	SYS	SYS	NODE	64-127,192-255	1
mlx5_0	SYS	SYS	 X 	NODE	SYS
mlx5_1	SYS	SYS	NODE	 X 	SYS
mlx5_2	NODE	NODE	SYS	SYS	 X
```

pod2
```
(test) root@9pxb:~/stress_test/code# nvidia-smi topo -m
	GPU0	GPU1	mlx5_0	mlx5_1	mlx5_2	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	NODE	PXB	SYS	0-63,128-191	0
GPU1	NV12	 X 	NODE	PXB	SYS	0-63,128-191	0
mlx5_0	NODE	NODE	 X 	NODE	SYS
mlx5_1	PXB	PXB	NODE	 X 	SYS
mlx5_2	SYS	SYS	SYS	SYS	 X
```

nccl log
```
8pxb:284:284 [0] NCCL INFO Bootstrap : Using eth0:172.17.127.185<0>
8pxb:284:284 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
8pxb:284:284 [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/IB [1]mlx5_0:1/IB [2]mlx5_1:1/IB ; OOB eth0:172.17.127.185<0>
8pxb:284:284 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda11.6
8pxb:285:285 [1] NCCL INFO Bootstrap : Using eth0:172.17.127.185<0>
8pxb:285:285 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
8pxb:285:285 [1] NCCL INFO NET/IB : Using [0]mlx5_2:1/IB [1]mlx5_0:1/IB [2]mlx5_1:1/IB ; OOB eth0:172.17.127.185<0>
8pxb:285:285 [1] NCCL INFO Using network IB
8pxb:284:310 [0] NCCL INFO Channel 00/02 :    0   1   2   3
8pxb:285:314 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
8pxb:284:310 [0] NCCL INFO Channel 01/02 :    0   1   2   3
8pxb:285:314 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000
8pxb:284:310 [0] NCCL INFO Trees [0] 1/2/-1->0->-1 [1] 1/-1/-1->0->2
8pxb:284:310 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000
8pxb:285:314 [1] NCCL INFO Channel 00 : 1[d0000] -> 2[4b000] [send] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Channel 00 : 3[51000] -> 0[cb000] [receive] via NET/IB/0
8pxb:285:314 [1] NCCL INFO Channel 01 : 1[d0000] -> 2[4b000] [send] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Channel 01 : 3[51000] -> 0[cb000] [receive] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Channel 00 : 0[cb000] -> 1[d0000] via P2P/IPC/read
8pxb:284:310 [0] NCCL INFO Channel 01 : 0[cb000] -> 1[d0000] via P2P/IPC/read
8pxb:285:314 [1] NCCL INFO Connected all rings
8pxb:285:314 [1] NCCL INFO Channel 00 : 1[d0000] -> 0[cb000] via P2P/IPC/read
8pxb:284:310 [0] NCCL INFO Connected all rings
8pxb:285:314 [1] NCCL INFO Channel 01 : 1[d0000] -> 0[cb000] via P2P/IPC/read
8pxb:284:310 [0] NCCL INFO Channel 00 : 2[4b000] -> 0[cb000] [receive] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Channel 01 : 2[4b000] -> 0[cb000] [receive] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Channel 00 : 0[cb000] -> 2[4b000] [send] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Channel 01 : 0[cb000] -> 2[4b000] [send] via NET/IB/0
8pxb:284:310 [0] NCCL INFO Connected all trees
8pxb:284:310 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
8pxb:284:310 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
8pxb:285:314 [1] NCCL INFO Connected all trees
8pxb:285:314 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
8pxb:285:314 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
8pxb:284:310 [0] NCCL INFO comm 0x7fa614002f70 rank 0 nranks 4 cudaDev 0 busId cb000 - Init COMPLETE
8pxb:285:314 [1] NCCL INFO comm 0x7f0940002f70 rank 1 nranks 4 cudaDev 1 busId d0000 - Init COMPLETE
8pxb:284:284 [0] NCCL INFO Launch mode Parallel

AFTER 30 minutes

[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1804619 milliseconds before timing out.                                                                                                       │
│ [E ProcessGroupNCCL.cpp:737] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1804644 milliseconds before timing out.                                                                                                       │
│ Traceback (most recent call last):                                                                                                                                                                                                                                                                  │
│   File "train.py", line 593, in <module>                                                                                                                                                                                                                                                            │
│     main()                                                                                                                                                                                                                                                                                          │
│   File "train.py", line 248, in main                                                                                                                                                                                                                                                                │
│     model = DistributedDataParallel(model,                                                                                                                                                                                                                                                          │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__                                                                                                                                                                              │
│     _verify_param_shape_across_processes(self.process_group, parameters)                                                                                                                                                                                                                            │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes                                                                                                                                                         │
│     return dist._verify_params_across_processes(process_group, tensors, logger)                                                                                                                                                                                                                     │
│ RuntimeError: DDP expects same model across all ranks, but Rank 0 has 42 params, while rank 1 has inconsistent 0 params.                                                                                                                                                                            │
│ Traceback (most recent call last):                                                                                                                                                                                                                                                                  │
│   File "train.py", line 593, in <module>                                                                                                                                                                                                                                                            │
│     main()                                                                                                                                                                                                                                                                                          │
│   File "train.py", line 248, in main                                                                                                                                                                                                                                                                │
│     model = DistributedDataParallel(model,                                                                                                                                                                                                                                                          │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__                                                                                                                                                                              │
│     _verify_param_shape_across_processes(self.process_group, parameters)                                                                                                                                                                                                                            │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes                                                                                                                                                         │
│     return dist._verify_params_across_processes(process_group, tensors, logger)                                                                                                                                                                                                                     │
│ RuntimeError: DDP expects same model across all ranks, but Rank 1 has 42 params, while rank 2 has inconsistent 0 params.                                                                                                                                                                            │
│ [E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.                                   │
│ terminate called after throwing an instance of 'std::runtime_error'                                                                                                                                                                                                                                 │
│   what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1804619 milliseconds before timing out.                                                                                                                         │
│ [E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.                                   │
│ terminate called after throwing an instance of 'std::runtime_error'                                                                                                                                                                                                                                 │
│   what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1804644 milliseconds before timing out.                                                                                                                         │
│ WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 91 closing signal SIGTERM                                                                                                                                                                                                     │
│ ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 90) of binary: /root/anaconda3/envs/test/bin/python                                                                                                                                                   │
│ Traceback (most recent call last):                                                                                                                                                                                                                                                                  │
│   File "/root/anaconda3/envs/test/lib/python3.8/runpy.py", line 192, in _run_module_as_main                                                                                                                                                                                                         │
│     return _run_code(code, main_globals, None,                                                                                                                                                                                                                                                      │
│   File "/root/anaconda3/envs/test/lib/python3.8/runpy.py", line 85, in _run_code                                                                                                                                                                                                                    │
│     exec(code, run_globals)                                                                                                                                                                                                                                                                         │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>                                                                                                                                                                                   │
│     main()                                                                                                                                                                                                                                                                                          │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main                                                                                                                                                                                       │
│     launch(args)                                                                                                                                                                                                                                                                                    │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch                                                                                                                                                                                     │
│     run(args)                                                                                                                                                                                                                                                                                       │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run                                                                                                                                                                                           │
│     elastic_launch(                                                                                                                                                                                                                                                                                 │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__                                                                                                                                                                             │
│     return launch_agent(self._config, self._entrypoint, list(args))                                                                                                                                                                                                                                 │
│   File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent                                                                                                                                                                         │
│     raise ChildFailedError(                                                                                                                                                                                                                                                                         │
│ torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                                                                                                                                                                                  │
│ ===================================================                                                                                                                                                                                                                                                 │
│ train.py FAILED                   
```

**Comment by sjeaugey** [comment]
I can't see any NCCL error in the log.

Something to check:
```
RuntimeError: DDP expects same model across all ranks, but Rank 1 has 42 params, while rank 2 has inconsistent 0 params.
```
That could cause the NCCL operations on the two ranks to have mismatching sizes, causing a hang. To confirm that you could run with `NCCL_DEBUG_SUBSYS=INIT,COLL`. That would print the arguments passed to NCCL operations.

**Comment by JuHyung-Son** [comment]
this is the starting log
```
(test) root@8pxb:~/stress_test/code# NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,COLL  python -m torch.distribute.launch --nnodes 2 --nproc_per_node=2 --node_rank=0 --master_port=7777 --master_addr=172.17.127.185  train.py --max_epochs=1 --input_dir=/data/project/input --fold 0 --seed 7 --batch_size 32 --num_workers 1 --arch LSTM --lr 1e-03 --fp16 --max_seq_len 80 --dropout 0.1
/root/anaconda3/envs/test/bin/python: Error while finding module specification for 'torch.distribute.launch' (ModuleNotFoundError: No module named 'torch.distribute')
(test) root@8pxb:~/stress_test/code# NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,COLL  python -m torch.distributed.launch --nnodes 2 --nproc_per_node=2 --node_rank=0 --master_port=7777 --master_addr=172.17.127.185  train.py --max_epochs=1 --input_dir=/data/project/input --fold 0 --seed 7 --batch_size 32 --num_workers 1 --arch LSTM --lr 1e-03 --fp16 --max_seq_len 80 --dropout 0.1
/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Namespace(arch='LSTM', augmentation=False, batch_size=32, ckpt_path='', cont_cols=['u_in', 'u_out', 'u_in_min', 'u_in_diff', 'time_diff', 'inhaled_air'], device=device(type='cuda', index=0), dropout=0.1, eval=False, extra='cosine', extra_file='', feature_size=5, fold=0, fp16=True, hidden_size=256, input_dir='/data/project/input', k=5, local_rank=0, lr=0.001, max_epochs=1, max_grad_norm=1000, max_seq_len=80, model_dir='model', n_folds=12, nlayers=4, num_workers=1, optim='AdamW', print_freq=100, pseudo_path='', rank=0, scheduler='cosine', seed=7, start_epoch=0, submission_dir='submissions', target_size=1, test_file='test.zip', train_file='train.zip', valid_freq=10, warmup_steps=20, weight_decay=0.01, world_size=4, wsteps=15)
train set shape: (5532960, 21)
parameters:  22609977
8pxb:404:404 [0] NCCL INFO Bootstrap : Using eth0:172.17.127.185<0>
8pxb:404:404 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
8pxb:404:404 [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/IB [1]mlx5_0:1/IB [2]mlx5_1:1/IB ; OOB eth0:172.17.127.185<0>
8pxb:404:404 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda11.6
8pxb:405:405 [1] NCCL INFO Bootstrap : Using eth0:172.17.127.185<0>
8pxb:405:405 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
8pxb:405:405 [1] NCCL INFO NET/IB : Using [0]mlx5_2:1/IB [1]mlx5_0:1/IB [2]mlx5_1:1/IB ; OOB eth0:172.17.127.185<0>
8pxb:405:405 [1] NCCL INFO Using network IB
8pxb:404:430 [0] NCCL INFO Channel 00/02 :    0   1   2   3
8pxb:404:430 [0] NCCL INFO Channel 01/02 :    0   1   2   3
8pxb:404:430 [0] NCCL INFO Trees [0] 1/2/-1->0->-1 [1] 1/-1/-1->0->2
8pxb:404:430 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000
8pxb:405:434 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
8pxb:405:434 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000
8pxb:404:430 [0] NCCL INFO Channel 00 : 3[51000] -> 0[cb000] [receive] via NET/IB/0
8pxb:405:434 [1] NCCL INFO Channel 00 : 1[d0000] -> 2[4b000] [send] via NET/IB/0
8pxb:404:430 [0] NCCL INFO Channel 01 : 3[51000] -> 0[cb000] [receive] via NET/IB/0
8pxb:404:430 [0] NCCL INFO Channel 00 : 0[cb000] -> 1[d0000] via P2P/IPC/read
8pxb:404:430 [0] NCCL INFO Channel 01 : 0[cb000] -> 1[d0000] via P2P/IPC/read
8pxb:405:434 [1] NCCL INFO Channel 01 : 1[d0000] -> 2[4b000] [send] via NET/IB/0
8pxb:405:434 [1] NCCL INFO Connected all rings
8pxb:405:434 [1] NCCL INFO Channel 00 : 1[d0000] -> 0[cb000] via P2P/IPC/read
8pxb:405:434 [1] NCCL INFO Channel 01 : 1[d0000] -> 0[cb000] via P2P/IPC/read
8pxb:404:430 [0] NCCL INFO Connected all rings
8pxb:404:430 [0] NCCL INFO Channel 00 : 2[4b000] -> 0[cb000] [receive] via NET/IB/0
8pxb:404:430 [0] NCCL INFO Channel 01 : 2[4b000] -> 0[cb000] [receive] via NET/IB/0
8pxb:404:430 [0] NCCL INFO Channel 00 : 0[cb000] -> 2[4b000] [send] via NET/IB/0
8pxb:404:430 [0] NCCL INFO Channel 01 : 0[cb000] -> 2[4b000] [send] via NET/IB/0
8pxb:404:430 [0] NCCL INFO Connected all trees
8pxb:404:430 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
8pxb:404:430 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
8pxb:405:434 [1] NCCL INFO Connected all trees
8pxb:405:434 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
8pxb:405:434 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
8pxb:404:430 [0] NCCL INFO comm 0x7fe3b0002f70 rank 0 nranks 4 cudaDev 0 busId cb000 - Init COMPLETE
8pxb:405:434 [1] NCCL INFO comm 0x7ff8d4002f70 rank 1 nranks 4 cudaDev 1 busId d0000 - Init COMPLETE
8pxb:404:404 [0] NCCL INFO AllGather: opCount 0 sendbuff 0x7fe465a22c00 recvbuff 0x7fe465a23600 count 8 datatype 0 op 0 root 0 comm 0x7fe3b0002f70 [nranks=4] stream 0x563f866ee020
8pxb:405:405 [1] NCCL INFO AllGather: opCount 0 sendbuff 0x7ff97da22c00 recvbuff 0x7ff97da23600 count 8 datatype 0 op 0 root 0 comm 0x7ff8d4002f70 [nranks=4] stream 0x557557294390
8pxb:404:404 [0] NCCL INFO Launch mode Parallel
8pxb:405:405 [1] NCCL INFO Broadcast: opCount 1 sendbuff 0x7ff97da23600 recvbuff 0x7ff97da23600 count 1056 datatype 0 op 0 root 0 comm 0x7ff8d4002f70 [nranks=4] stream 0x557557294390
```

**Comment by sjeaugey** [comment]
So, rank 1 is waiting in a `ncclBroadcast`, to receive 1056 bytes from 0 (the root) but rank 0 is not calling `ncclBroadcast`. It would be interesting to see where rank 0 is blocked (for example using `gdb -p <pid>` then `thread apply all bt`).

**Comment by JuHyung-Son** [comment]
this is the log. pretty long

```
(gdb) thread apply all bt

Thread 12 (Thread 0x7fd07dfff700 (LWP 112)):
#0  0x00007fd31dcd8ef7 in __GI___sched_getaffinity_new (pid=-2012823256, cpusetsize=1, cpuset=0x2) at ../sysdeps/unix/sysv/linux/sched_getaffinity.c:36
#1  0x00007fd2e7134db5 in persistentThread (comm_=0x7fd088002f70) at proxy.cc:456
#2  0x00007fd31dfcd6db in start_thread (arg=0x7fd07dfff700) at pthread_create.c:463
#3  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=-2012823256, events=0x0, maxevents=2, timeout=500010743, set=0x1) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#4  0x0000000000000000 in ?? ()

Thread 11 (Thread 0x7fd087fff700 (LWP 110)):
#0  0x00007fd31dce9cb9 in __GI_ppoll (fds=0x0, nfds=140533611620016, timeout=<optimized out>, sigmask=0x7fd087ffeab0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
#1  0x0000000000000000 in ?? ()

Thread 10 (Thread 0x7fd0a1ffd700 (LWP 103)):
#0  0x00007fd31dfd7474 in __libc_read (fd=36, buf=0x7fd0a1ffce70, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fd24ceb415f in ibv_get_async_event () from /usr/lib/x86_64-linux-gnu/libibverbs.so.1
#2  0x00007fd2e7175da2 in wrap_ibv_get_async_event (context=context@entry=0x559abaf04850, event=event@entry=0x7fd0a1ffced0) at misc/ibvwrap.cc:220
#3  0x00007fd2e7127003 in ncclIbAsyncThreadMain (args=0x559abaf04850) at transport/net_ib.cc:70
#4  0x00007fd31dfcd6db in start_thread (arg=0x7fd0a1ffd700) at pthread_create.c:463
#5  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=36, events=0x7fd0a1ffce70, maxevents=16, timeout=503149684, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#6  0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7fd0a5ffe700 (LWP 102)):
#0  0x00007fd31dfd7474 in __libc_read (fd=34, buf=0x7fd0a5ffde70, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fd24ceb415f in ibv_get_async_event () from /usr/lib/x86_64-linux-gnu/libibverbs.so.1
#2  0x00007fd2e7175da2 in wrap_ibv_get_async_event (context=context@entry=0x559a40832b10, event=event@entry=0x7fd0a5ffded0) at misc/ibvwrap.cc:220
#3  0x00007fd2e7127003 in ncclIbAsyncThreadMain (args=0x559a40832b10) at transport/net_ib.cc:70
#4  0x00007fd31dfcd6db in start_thread (arg=0x7fd0a5ffe700) at pthread_create.c:463
#5  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=34, events=0x7fd0a5ffde70, maxevents=16, timeout=503149684, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#6  0x0000000000000000 in ?? ()
---Type <return> to continue, or q <return> to quit---

Thread 8 (Thread 0x7fd0a9fff700 (LWP 101)):
#0  0x00007fd31dfd7474 in __libc_read (fd=32, buf=0x7fd0a9ffee70, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fd24ceb415f in ibv_get_async_event () from /usr/lib/x86_64-linux-gnu/libibverbs.so.1
#2  0x00007fd2e7175da2 in wrap_ibv_get_async_event (context=context@entry=0x559a4458c3d0, event=event@entry=0x7fd0a9ffeed0) at misc/ibvwrap.cc:220
#3  0x00007fd2e7127003 in ncclIbAsyncThreadMain (args=0x559a4458c3d0) at transport/net_ib.cc:70
#4  0x00007fd31dfcd6db in start_thread (arg=0x7fd0a9fff700) at pthread_create.c:463
#5  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=32, events=0x7fd0a9ffee70, maxevents=16, timeout=503149684, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#6  0x0000000000000000 in ?? ()

Thread 7 (Thread 0x7fd14ac8c700 (LWP 98)):
#0  0x00007fd31dce9cb9 in __GI_ppoll (fds=0x7fd31dd05d36 <__GI___clock_gettime+86>, nfds=140536879562384, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
#1  0x00007fd14ac8be90 in ?? ()
#2  0x0000000000000064 in ?? ()
#3  0x0000559a3ecbc410 in ?? ()
#4  0x0000000000000063 in ?? ()
#5  0x000000640000000b in ?? ()
#6  0x0000000000004ceb in ?? ()
#7  0x00000000219c4490 in ?? ()
#8  0x0000000000000064 in ?? ()
#9  0x00007fd14ac8be90 in ?? ()
#10 0x0000000000000064 in ?? ()
#11 0x0000000000000064 in ?? ()
#12 0x0000000000000064 in ?? ()
#13 0x0000559a5369da80 in ?? ()
#14 0x0000000000000000 in ?? ()

Thread 6 (Thread 0x7fd18606e700 (LWP 97)):
#0  0x00007fd31dfd4065 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fd18606dd20, expected=0, futex_word=0x559a3caf3a40) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7fd18606dd20, mutex=0x559a3caf39f0, cond=0x559a3caf3a18) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x559a3caf3a18, mutex=0x559a3caf39f0, abstime=0x7fd18606dd20) at pthread_cond_wait.c:667
#3  0x00007fd2e70331dc in c10d::ProcessGroupNCCL::workCleanupLoop() () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so
#4  0x00007fd2ef21cbf4 in execute_native_thread_routine () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/src/c++11/shared_ptr_base.h:82
#5  0x00007fd31dfcd6db in start_thread (arg=0x7fd18606e700) at pthread_create.c:463
#6  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=1018116672, events=0x189, maxevents=0, timeout=503136357, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#7  0x0000000000000000 in ?? ()

Thread 5 (Thread 0x7fd1d7fff700 (LWP 96)):
#0  0x00007fd31dfd4065 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fd1d7ffeb70, expected=0, futex_word=0x559a3caf39b8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7fd1d7ffeb70, mutex=0x559a3caf39c0, cond=0x559a3caf3990) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x559a3caf3990, mutex=0x559a3caf39c0, abstime=0x7fd1d7ffeb70) at pthread_cond_wait.c:667
#3  0x00007fd2e703ec3b in c10d::ProcessGroupNCCL::ncclCommWatchdogInternal() () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so
#4  0x00007fd2e703fa41 in c10d::ProcessGroupNCCL::ncclCommWatchdog() () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so
#5  0x00007fd2ef21cbf4 in execute_native_thread_routine () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/src/c++11/shared_ptr_base.h:82
#6  0x00007fd31dfcd6db in start_thread (arg=0x7fd1d7fff700) at pthread_create.c:463
#7  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=1018116536, events=0x189, maxevents=0, timeout=503136357, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#8  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7fd2393c1700 (LWP 95)):
#0  0x00007fd31dce9cb9 in __GI_ppoll (fds=0x7fd2393c0fc0, nfds=94120945371200, timeout=<optimized out>, sigmask=0x7fd2393c0ed0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
#1  0x0000000000000000 in ?? ()
---Type <return> to continue, or q <return> to quit---

Thread 3 (Thread 0x7fd251901700 (LWP 91)):
#0  0x00007fd31dce9cb9 in __GI_ppoll (fds=0x7fd2edb6a298, nfds=140541288255120, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
#1  0x0000559a3d9707e0 in ?? ()
#2  0x00000000ffffffff in ?? ()
#3  0x0000559a3d9707e0 in ?? ()
#4  0x00000000fffffffe in ?? ()
#5  0xffffffff00000002 in ?? ()
#6  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7fd293dff700 (LWP 55)):
#0  0x00007fd31dfd3ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fd294416630) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fd294416678, cond=0x7fd294416608) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x7fd294416608, mutex=mutex@entry=0x7fd294416678) at pthread_cond_wait.c:655
#3  0x00007fd2969e66a9 in background_thread_sleep (tsdn=<optimized out>, interval=<optimized out>, info=<optimized out>) at src/background_thread.c:137
#4  background_work_sleep_once (ind=0, info=<optimized out>, tsdn=<optimized out>) at src/background_thread.c:229
#5  background_thread0_work (tsd=<optimized out>) at src/background_thread.c:374
#6  background_work (ind=<optimized out>, tsd=<optimized out>) at src/background_thread.c:412
#7  background_thread_entry () at src/background_thread.c:444
#8  0x00007fd31dfcd6db in start_thread (arg=0x7fd293dff700) at pthread_create.c:463
#9  0x00007fd31dcf671f in __GI_epoll_pwait (epfd=-1807653328, events=0x80, maxevents=0, timeout=503134931, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#10 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7fd31e403740 (LWP 50)):
#0  0x00007ffe405b56cb in ?? ()
#1  0x00007ffe405b5954 in clock_gettime ()
#2  0x00007fd31dd05d36 in __GI___clock_gettime (clock_id=4, tp=0x7ffe40579430) at ../sysdeps/unix/clock_gettime.c:115
#3  0x00007fd2edb5e13f in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#4  0x00007fd2edb9d0b3 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#5  0x00007fd2edbe9972 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#6  0x00007fd2edbea855 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#7  0x00007fd2edcd0961 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#8  0x00007fd2eda87263 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#9  0x00007fd2eda879f4 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#10 0x00007fd2eda89609 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#11 0x00007fd2edb0114e in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#12 0x00007fd30000d6c9 in ?? () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/../../../../libcudart.so.11.0
#13 0x00007fd2fffe1e2d in ?? () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/../../../../libcudart.so.11.0
#14 0x00007fd300031fc5 in cudaMemcpyAsync () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/../../../../libcudart.so.11.0
#15 0x00007fd2ae5f7b29 in at::native::_local_scalar_dense_cuda(at::Tensor const&)::{lambda()#1}::operator()() const [clone .isra.0] () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so
#16 0x00007fd2ae5f97f0 in at::native::_local_scalar_dense_cuda(at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so
#17 0x00007fd2afcb3e60 in at::(anonymous namespace)::(anonymous namespace)::wrapper___local_scalar_dense(at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so
#18 0x00007fd2afcb3ecd in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<c10::Scalar (at::Tensor const&), &at::(anonymous namespace)::(anonymous namespace)::wrapper___local_scalar_dense>, c10::Scalar, c10::guts::typelist::typelist<at::Tensor const&> >, c10::Scalar (at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so
#19 0x00007fd2dc4cd6c9 in at::_ops::_local_scalar_dense::redispatch(c10::DispatchKeySet, at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#20 0x00007fd2dd914790 in torch::autograd::VariableType::(anonymous namespace)::_local_scalar_dense(c10::DispatchKeySet, at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#21 0x00007fd2dd9148c0 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<c10::Scalar (c10::DispatchKeySet, at::Tensor const&), &torch::autograd::VariableType::(anonymous namespace)::_local_scalar_dense>, c10::Scalar, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&> >, c10::Scalar (c10::DispatchKeySet, at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#22 0x00007fd2dc558360 in at::_ops::_local_scalar_dense::call(at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#23 0x00007fd2dbea01cb in at::native::item(at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#24 0x00007fd2dc9f932d in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<c10::Scalar (at::Tensor const&), &at::(anonymous namespace)::(anonymous namespace)::wrapper__item>, c10::Scalar, c10::guts::typelist::typelist<at::Te---Type <return> to continue, or q <return> to quit---
nsor const&> >, c10::Scalar (at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#25 0x00007fd2dc428130 in at::_ops::item::call(at::Tensor const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#26 0x00007fd2dcdf9942 in int at::Tensor::item<int>() const () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#27 0x00007fd2dea2d50b in c10d::verify_params_across_processes(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<std::weak_ptr<c10d::Logger> > const&) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#28 0x00007fd2ed4fee82 in void pybind11::cpp_function::initialize<torch::distributed::c10d::(anonymous namespace)::c10d_init(_object*, _object*)::{lambda(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<std::shared_ptr<c10d::Logger> > const&)#39}, void, c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<std::shared_ptr<c10d::Logger> > const&, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, pybind11::sibling, pybind11::arg_v, pybind11::call_guard<pybind11::gil_scoped_release> >(torch::distributed::c10d::(anonymous namespace)::c10d_init(_object*, _object*)::{lambda(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<std::shared_ptr<c10d::Logger> > const&)#39}&&, void (*)(c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<std::shared_ptr<c10d::Logger> > const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, pybind11::sibling const&, pybind11::arg_v const&, pybind11::call_guard<pybind11::gil_scoped_release> const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#29 0x00007fd2ece69a44 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#30 0x0000559a3727bc96 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x7fd299cd38b0) at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:742
#31 PyCFunction_Call () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:772
#32 0x0000559a3723831f in _PyObject_MakeTpCall () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:159
#33 0x0000559a372c3b49 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fd239416e10, callable=0x7fd299cd38b0) at /tmp/build/80754af9/python_1573076469108/work/Include/cpython/abstract.h:125
#34 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559a386f5660) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4987
#35 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:3469
#36 0x0000559a37286c32 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4298
#37 0x0000559a37287bf3 in _PyFunction_Vectorcall.localalias.357 () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:435
#38 0x0000559a372013cc in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x559a53695b30, callable=0x7fd2999a8dc0) at /tmp/build/80754af9/python_1573076469108/work/Include/cpython/abstract.h:127
#39 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559a386f5660) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4987
#40 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:3500
#41 0x0000559a37286fb9 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4298
#42 0x0000559a37287bf3 in _PyFunction_Vectorcall.localalias.357 () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:435
#43 0x0000559a3728877b in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:104
#44 0x0000559a372889e3 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:887
#45 0x0000559a37288b7a in slot_tp_init () at /tmp/build/80754af9/python_1573076469108/work/Objects/typeobject.c:6753
#46 0x0000559a37238294 in type_call (kwds=0x7fd21093ca80, args=0x7fd23942b820, type=<optimized out>) at /tmp/build/80754af9/python_1573076469108/work/Objects/typeobject.c:989
#47 _PyObject_MakeTpCall () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:159
#48 0x0000559a372c06bd in _PyObject_Vectorcall (kwnames=0x7fd31d022d40, nargsf=<optimized out>, args=<optimized out>, callable=<optimized out>) at /tmp/build/80754af9/python_1573076469108/work/Include/cpython/abstract.h:125
#49 call_function (kwnames=0x7fd31d022d40, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4987
#50 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:3515
#51 0x0000559a3728713f in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4298
#52 0x0000559a37287bf3 in _PyFunction_Vectorcall.localalias.357 () at /tmp/build/80754af9/python_1573076469108/work/Objects/call.c:435
#53 0x0000559a372013cc in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fd31d1355b0, callable=0x7fd31d17d1f0) at /tmp/build/80754af9/python_1573076469108/work/Include/cpython/abstract.h:127
#54 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x559a386f5660) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4987
#55 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:3500
#56 0x0000559a37286c32 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4298
#57 0x0000559a37287a04 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:4327
#58 0x0000559a3731af5c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at /tmp/build/80754af9/python_1573076469108/work/Python/ceval.c:718
#59 0x0000559a3731b004 in run_eval_code_obj () at /tmp/build/80754af9/python_1573076469108/work/Python/pythonrun.c:1117
#60 0x0000559a37350304 in run_mod () at /tmp/build/80754af9/python_1573076469108/work/Python/pythonrun.c:1139
#61 0x0000559a37352c50 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1573076469108/work/Python/pythonrun.c:1055
#62 0x0000559a37352e41 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1573076469108/work/Python/pythonrun.c:428
#63 0x0000559a37353983 in pymain_run_file (cf=0x7ffe4057c738, config=0x559a386f4b20) at /tmp/build/80754af9/python_1573076469108/work/Modules/main.c:381
#64 pymain_run_python (exitcode=0x7ffe4057c730) at /tmp/build/80754af9/python_1573076469108/work/Modules/main.c:565
#65 Py_RunMain () at /tmp/build/80754af9/python_1573076469108/work/Modules/main.c:644
#66 0x0000559a37353bc9 in Py_BytesMain () at /tmp/build/80754af9/python_1573076469108/work/Modules/main.c:698
#67 0x00007fd31dbf6bf7 in __libc_start_main (main=0x559a37210720 <main>, argc=23, argv=0x7ffe4057c928, init=0x559a37354080 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe4057c918) at ../csu/libc-start.c:262
#68 0x0000559a372dce13 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

**Comment by sjeaugey** [comment]
Thanks. Thread 1 seems to be blocked in a CUDA call, which could mean there is a stuck (NCCL) kernel running on the GPU. Can you check with nvidia-smi whether the GPU of rank 0 is running 100%?

Other than that, nothing seems stuck. So given we don't see the trace of the NCCL broadcast being launched, it could mean the previous ncclAllReduce got stuck?

The log indicates that NCCL is only using one NIC (`mlx5_2`) in the end, probably because it's closer to the GPU in the PCI topology. When you say it works with only one NIC, which NIC is it? This is effectively running with just one NIC as well.

**Comment by JuHyung-Son** [comment]
when i checked it before, it used 100% gpu.
and yes i checked it uses 1 nic.

I have one more thing to check. do i have to diable ACSCtl?? I just read nccl trouble shooting guide and my nodes shows `SrcValid+` on some plx

**Comment by sjeaugey** [comment]
ACS is a problem when you have PCI-to-PCI transfers, e.g. GPU to GPU or GPU to NIC. In your case, GPU to GPU uses NVLink, and GPU to NIC goes through CPU memory (GPU Direct RDMA is not used), so in theory disabling ACS should not be needed on your system.

Back to my question, when you say
> also it works when I run with 1 node, and it worked with 1 nic on the node.

which NIC did work? Can you try setting for example NCCL_IB_HCA=mlx5_0 and see if it works? And if it does, confirm which NIC works and which doesn't?

**Comment by JuHyung-Son** [comment]
when i tried with NCCL_IB_HCA=mlx5_0,mlx5_1

pod1 uses 
```
│ task-420-bzbzn:28:53 [0] NCCL INFO Channel 00 : 3[51000] -> 0[cb000] [receive] via NET/IB/0                                                                                                                                                                                                         │
│ task-420-bzbzn:29:56 [1] NCCL INFO Channel 00 : 1[d0000] -> 2[4b000] [send] via NET/IB/0                                                                                                                                                                                                            │
│ task-420-bzbzn:28:53 [0] NCCL INFO Channel 01 : 3[51000] -> 0[cb000] [receive] via NET/IB/0                                                                                                                                                                                                         │
│ task-420-bzbzn:28:53 [0] NCCL INFO Channel 00 : 0[cb000] -> 1[d0000] via P2P/IPC/read                                                                                                                                                                                                               │
│ task-420-bzbzn:29:56 [1] NCCL INFO Channel 01 : 1[d0000] -> 2[4b000] [send] via NET/IB/0
```

and pod2 uses
```
│ task-421-87qq4:27:52 [0] NCCL INFO Channel 00 : 1[d0000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                  │
│ task-421-87qq4:27:52 [0] NCCL INFO Channel 01 : 1[d0000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                  │
│ task-421-87qq4:27:52 [0] NCCL INFO Channel 00 : 2[4b000] -> 3[51000] via P2P/IPC/read                                                                                                                                                                                                               │
│ task-421-87qq4:28:54 [1] NCCL INFO Channel 00 : 3[51000] -> 0[cb000] [send] via NET/IB/1/GDRDMA                                                                                                                                                                                                     │
│ task-421-87qq4:27:52 [0] NCCL INFO Channel 01 : 2[4b000] -> 3[51000] via P2P/IPC/read                                                                                                                                                                                                               │
│ task-421-87qq4:28:54 [1] NCCL INFO Channel 01 : 3[51000] -> 0[cb000] [send] via NET/IB/1/GDRDMA
```

and it hangs

**Comment by sjeaugey** [comment]
This is very confusing. Why would mlx5_2 sometimes use GPU Direct RDMA and sometimes not? This should be deterministic. Do you have different types of nodes or nodes configured differently?

Also by "pod" do you mean a different system, right? It is concerning that different pods have different topologies. This can result in issues we can't easily reproduce, plus it makes it hard to get good performance as the global performance will be the minimum of all pods.

Could you link hanks to the fact GPU Direct RDMA is used? If so, then you should indeed disable ACS.

**Comment by JuHyung-Son** [comment]
I think it`s because my node have 8 gpus and 3 nic on each node.
this is my topo and i have 10 nodes like this.

```
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	mlx5_0	mlx5_1	mlx5_2	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	NV12	NV12	NV12	NV12	NV12	NV12	PXB	NODE	SYS	0,2-63,128	0
GPU1	NV12	 X 	NV12	NV12	NV12	NV12	NV12	NV12	PXB	NODE	SYS	0,2-63,128	0
GPU2	NV12	NV12	 X 	NV12	NV12	NV12	NV12	NV12	NODE	PXB	SYS	0,2-63,128	0
GPU3	NV12	NV12	NV12	 X 	NV12	NV12	NV12	NV12	NODE	PXB	SYS	0,2-63,128	0
GPU4	NV12	NV12	NV12	NV12	 X 	NV12	NV12	NV12	SYS	SYS	PXB	65-127,193-255	1
GPU5	NV12	NV12	NV12	NV12	NV12	 X 	NV12	NV12	SYS	SYS	PXB	65-127,193-255	1
GPU6	NV12	NV12	NV12	NV12	NV12	NV12	 X 	NV12	SYS	SYS	NODE	65-127,193-255	1
GPU7	NV12	NV12	NV12	NV12	NV12	NV12	NV12	 X 	SYS	SYS	NODE	65-127,193-255	1
mlx5_0	PXB	PXB	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	SYS		
mlx5_1	NODE	NODE	PXB	PXB	SYS	SYS	SYS	SYS	NODE	 X 	SYS		
mlx5_2	SYS	SYS	SYS	SYS	PXB	PXB	NODE	NODE	SYS	SYS	 X 
```

I run pod which is in kubernetes.
and kubernetes assign gpus to the pods by nvidia-device-plugin. so assigned gpus on the pod are different when it restarts.

in my node, it uses nvidia peermem.
```
lsmod | grep -i peermem

nvidia_peermem         16384  0
nvidia              39104512  659 nvidia_uvm,nvidia_peermem,nvidia_modeset
ib_core               315392  11 rdma_cm,ib_ipoib,nvidia_peermem,iw_cm,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm
```

**Comment by sjeaugey** [comment]
Ok but do you have to create pods with only 2 GPUs? If you want to run on 4 GPUs, why run on two pods of 2 GPUs instead of one pod of 4 GPUs?

In any case, given GPU Direct RDMA is used sometimes, I'd either try to disable it to see if hangs disappear (NCCL_NET_GDR_LEVEL=0) or try to disable ACS.

**Comment by JuHyung-Son** [comment]
oh im just testing distributed learning system.

and sorry for confusing you.
I tried with NCCL_IB_HCA=mlx5_2 until not using GDRDMA. and when it uses only IB, it works.
as a result it only not works when using GDRDMA.

and yes it does not hang with NCCL_NET_GDR_LEVEL=0.
i ll disable acs with infra system manager tommorow.

Thank you so much

**Comment by JuHyung-Son** [comment]
after disabling ACS from BIOS.
this issue doe not appear anymore.
