### ISSUE TITLE
ncclCommInitRank hangs with MPI sub-communicator in the distributed mode

### ISSUE THREAD

**Issue by minsikcho** [NVIDIA/nccl#73]
Hello. This is the setup
- there are N nodes with 4 gpus each
- create N sub-communicator, so each sub-world size is 4 (matching #gpus on each node)
- call MPI_Bcast to fillup commId with the sub-communicator as in mpi_test.cu
- now the rank within the sub-communicator matches the sub-rank (cudaSetDevice has been called with this sub-rank in advance)
- call ncclCommInitRank 

Is there any problem with this procedure? What are the assumptions about the inputs to ncclCommInitRank?

This is a high-level code

      int color = rank / 4;  //rank : [0-15]

      MPI_Comm row_comm;
      MPI_Comm_split(MPI_COMM_WORLD, color, rank, &row_comm);

      int row_rank, row_size;
      MPI_Comm_rank(row_comm, &row_rank); //row_rank : [0-3]
      MPI_Comm_size(row_comm, &row_size);  //row_size : 4

      // NCCL Communicator creation      
      ncclGetUniqueId(&commId);      
      MPI_Bcast(&commId, NCCL_UNIQUE_ID_BYTES, MPI_CHAR, 0, row_comm);
      ret = ncclCommInitRank(&nccl_h, row_size, commId, row_rank);

**Comment by sjeaugey** [comment]
What you describe should work. We tried to reproduce the problem and it worked fine for us. Are you sure you are launching the processes correctly on the nodes so that processes within the same communicator are always on the same node ? Adding a call to MPI_Get_processor_name and printing which rank is on which node may help figuring that out.

Thanks !

**Comment by minsikcho** [comment]
I found that ranks were not correctly assigned to the machines as I thought.  Used rankfile to fix this.
Thanks!
