### ISSUE TITLE
distributed learning hangs when using more than 3 nodes.

### ISSUE THREAD

**Issue by JuHyung-Son** [NVIDIA/nccl#733]
i'm using nccl with pytorch ddp. torch 1.12, cuda 11.6, a100 gpu, infiniband GDRDMA in kubernetes cluster.

distributed learning works when i use 1 node or 2 node.
ex) 2 nodes with 4 gpu in each node, 2 nodes with 2 gpu in each node.

however when I use 3 nodes, it hangs and nccl timeout error occurs.
ex) 3 nodes with 2 gpu in each node, 3 nodes with 1 gpu in each node.

I disabled iommu and acs.
but not VT(SVM) for amd cpu. may this could be a reason for nccl hangs??

**Comment by sjeaugey** [comment]
Can you confirm everything works well with 2 nodes, with all combinations of nodes between the 3 nodes (A-B, A-C and B-C)? This sounds like a networking issue, which is usually related to specific nodes.

**Comment by JuHyung-Son** [comment]
I found it does not stop, but super slow..


below experiment is using 1 node, 4 pod, 1 gpu in each pod
```
ask-7677-54l6r:73:73 [0] NCCL INFO Bootstrap : Using eth0:172.17.75.36<0>
│ task-7677-54l6r:73:73 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
│ task-7677-54l6r:73:73 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB ; OOB eth0:172.17.75.36<0>
│ task-7677-54l6r:73:73 [0] NCCL INFO Using network IB
│ NCCL version 2.10.3+cuda11.6
│ task-7677-54l6r:73:333 [0] NCCL INFO NCCL_NET_GDR_LEVEL set by environment to SYS
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 00/02 :    0   1   2   3
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 01/02 :    0   1   2   3
│ task-7677-54l6r:73:333 [0] NCCL INFO Trees [0] 2/-1/-1->0->-1 [1] -1/-1/-1->0->1
│ task-7677-54l6r:73:333 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,fffffffd
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 00 : 3[4b000] -> 0[13000] [receive] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 01 : 3[4b000] -> 0[13000] [receive] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 00 : 0[13000] -> 1[51000] [send] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 01 : 0[13000] -> 1[51000] [send] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Connected all rings
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 00 : 2[98000] -> 0[13000] [receive] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 00 : 0[13000] -> 2[98000] [send] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Channel 01 : 1[51000] -> 0[13000] [receive] via NET/IB/0/GDRDMA
│ task-7677-54l6r:73:333 [0] NCCL INFO Connected all trees
│ task-7677-54l6r:73:333 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
│ task-7677-54l6r:73:333 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
│ task-7677-54l6r:73:333 [0] NCCL INFO comm 0x7f68b4002fb0 rank 0 nranks 4 cudaDev 0 busId 13000 - Init COMPLETE
│ task-7677-54l6r:73:73 [0] NCCL INFO Launch mode Parallel
│ use AdamW
│ Epoch: [0][1/1689] Data 1.166 (1.166) Elapsed 1m 37s (remain 2739m 13s) Loss: 4.891(4.891) MAE: 16.736(16.736) Grad: 6.6615  LR: 0.001000  sent/s 11
```

**Comment by sjeaugey** [comment]
I'm a bit confused, I thought this was running on 2 or 3 nodes but the log above is on one node. And even on one node, we're using the NIC which is not always ideal. Can you provide the log for all ranks in the job, not just rank 0?

Also, any reason to force NCCL_NET_GDR_LEVEL=SYS? What is the performance you're getting running the [NCCL perf tests](https://github.com/nvidia/nccl-tests) with and without that setting?

**Comment by JuHyung-Son** [comment]
NCCL_NET_GDR_LEVEL is just for experiment. I`m trying any options.

this is logs for all 4 pods.
i run 4 pods with 1 gpu on each pod in a node.

master
```
task-7700-94lc9:73:73 [0] NCCL INFO Bootstrap : Using eth0:172.17.80.45<0>                                                                                                                                                                                                                                                   
│ task-7700-94lc9:73:73 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             
│ task-7700-94lc9:73:73 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.45<0>                                                                                                                                                                                                   
│ task-7700-94lc9:73:73 [0] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         
│ NCCL version 2.10.3+cuda11.6                                                                                                                                                                                                                                                                                                 
│ task-7700-94lc9:74:74 [1] NCCL INFO Bootstrap : Using eth0:172.17.80.45<0>                                                                                                                                                                                                                                                   
│ task-7700-94lc9:74:74 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             
│ task-7700-94lc9:74:74 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.45<0>                                                                                                                                                                                                   
│ task-7700-94lc9:74:74 [1] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         
│ task-7700-94lc9:74:93 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0                                                                                                                                                                                                                                             
│ task-7700-94lc9:74:93 [1] NCCL INFO Setting affinity for GPU 1 to 7fffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000                                                                                                                                                                                    
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 00/02 :    0   1   2   3   4   5   6   7                                                                                                                                                                                                                                         
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 01/02 :    0   1   2   3   4   5   6   7                                                                                                                                                                                                                                         
│ task-7700-94lc9:73:89 [0] NCCL INFO Trees [0] 1/4/-1->0->-1 [1] 1/-1/-1->0->2                                                                                                                                                                                                                                               
│ ask-7700-94lc9:73:89 [0] NCCL INFO Setting affinity for GPU 0 to7fffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000                                                                                                                                                                                    
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 00 : 7[13000] -> 0[92000] [receive] via NET/IB/2/GDRDMA                                                                                                                                                                                                                          
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 01 : 7[13000] -> 0[92000] [receive] via NET/IB/2/GDRDMA                                                                                                                                                                                                                          
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 00 : 0[92000] -> 1[98000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7700-94lc9:74:93 [1] NCCL INFO Channel 00 : 1[98000] -> 2[4b000] [send] via NET/IB/2/GDRDMA                                                                                                                                                                                                                             
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 01 : 0[92000] -> 1[98000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7700-94lc9:74:93 [1] NCCL INFO Channel 01 : 1[98000] -> 2[4b000] [send] via NET/IB/2/GDRDMA                                                                                                                                                                                                                             
│ task-7700-94lc9:73:89 [0] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      
│ task-7700-94lc9:74:93 [1] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 01 : 0[92000] -> 2[4b000] [send] via NET/IB/2/GDRDMA                                                                                                                                                                                                                             
│ task-7700-94lc9:74:93 [1] NCCL INFO Channel 00 : 1[98000] -> 0[92000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7700-94lc9:74:93 [1] NCCL INFO Channel 01 : 1[98000] -> 0[92000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 00 : 4[cb000] -> 0[92000] [receive] via NET/IB/2/GDRDMA                                                                                                                                                                                                                          
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 00 : 0[92000] -> 4[cb000] [send] via NET/IB/2/GDRDMA                                                                                                                                                                                                                             
│ task-7700-94lc9:73:89 [0] NCCL INFO Channel 01 : 2[4b000] -> 0[92000] [receive] via NET/IB/2/GDRDMA                                                                                                                                                                                                                          
│ task-7700-94lc9:73:89 [0] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      
│ task-7700-94lc9:73:89 [0] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              
│ task-7700-94lc9:73:89 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 
│ task-7700-94lc9:74:93 [1] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      
│ task-7700-94lc9:74:93 [1] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              
│ task-7700-94lc9:74:93 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 
│ task-7700-94lc9:73:89 [0] NCCL INFO comm 0x7f4db0002fb0 rank 0 nranks 8 cudaDev 0 busId 92000 - Init COMPLETE                                                                                                                                                                                                                
│ task-7700-94lc9:74:93 [1] NCCL INFO comm 0x7f77cc002fb0 rank 1 nranks 8 cudaDev 1 busId 98000 - Init COMPLETE                                                                                                                                                                                                                
│ task-7700-94lc9:73:73 [0] NCCL INFO Launch mode Parallel                                                                                                                                                                                                                                                                    
│ use AdamW
```

second
```
task-7701-z5h6w:72:72 [0] NCCL INFO Bootstrap : Using eth0:172.17.80.63<0>                                                                                                                                                                                                                                                   
│ task-7701-z5h6w:73:73 [1] NCCL INFO Bootstrap : Using eth0:172.17.80.63<0>                                                                                                                                                                                                                                                   
│ task-7701-z5h6w:72:72 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             
│ task-7701-z5h6w:73:73 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             
│ task-7701-z5h6w:72:72 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.63<0>                                                                                                                                                                                                   
│ task-7701-z5h6w:72:72 [0] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         
│ task-7701-z5h6w:73:73 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.63<0>                                                                                                                                                                                                   
│ task-7701-z5h6w:73:73 [1] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         
│ task-7701-z5h6w:72:90 [0] NCCL INFO Trees [0] 3/-1/-1->2->5 [1] 3/0/-1->2->6                                                                                                                                                                                                                                                 
│ task-7701-z5h6w:72:90 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,fffffffd,00000000,00000000,ffffffff,fffffffd                                                                                                                                                                                                      
│ task-7701-z5h6w:73:91 [1] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] 4/-1/-1->3->2                                                                                                                                                                                                                                               
│ task-7701-z5h6w:73:91 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,fffffffd,00000000,00000000,ffffffff,fffffffd                                                                                                                                                                                                      
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 00 : 1[98000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                                          
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 01 : 1[98000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                                          
│ task-7701-z5h6w:73:91 [1] NCCL INFO Channel 00 : 3[51000] -> 4[cb000] [send] via NET/IB/1/GDRDMA                                                                                                                                                                                                                             
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 00 : 2[4b000] -> 3[51000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7701-z5h6w:73:91 [1] NCCL INFO Channel 01 : 3[51000] -> 4[cb000] [send] via NET/IB/1/GDRDMA                                                                                                                                                                                                                             
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 01 : 2[4b000] -> 3[51000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7701-z5h6w:72:90 [0] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 01 : 0[92000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                                          
│ task-7701-z5h6w:73:91 [1] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      
│ task-7701-z5h6w:73:91 [1] NCCL INFO Channel 01 : 4[cb000] -> 3[51000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                                         
│ task-7701-z5h6w:73:91 [1] NCCL INFO Channel 00 : 3[51000] -> 2[4b000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7701-z5h6w:73:91 [1] NCCL INFO Channel 01 : 3[51000] -> 2[4b000] via P2P/IPC/read                                                                                                                                                                                                                                       
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 00 : 2[4b000] -> 5[d0000] [send] via NET/IB/1/GDRDMA                                                                                                                                                                                                                             
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 01 : 6[e000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                                           
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 01 : 2[4b000] -> 6[e000] [send] via NET/IB/1/GDRDMA                                                                                                                                                                                                                              
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 00 : 5[d0000] -> 2[4b000] [receive] via NET/IB/1/GDRDMA                                                                                                                                                                                                                          
│ task-7701-z5h6w:72:90 [0] NCCL INFO Channel 01 : 2[4b000] -> 0[92000] [send] via NET/IB/1/GDRDMA                                                                                                                                                                                                                             
│ task-7701-z5h6w:72:90 [0] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      
│ task-7701-z5h6w:72:90 [0] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              
│ task-7701-z5h6w:72:90 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 
│ task-7701-z5h6w:73:91 [1] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      
│ task-7701-z5h6w:73:91 [1] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              
│ task-7701-z5h6w:73:91 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 
│ task-7701-z5h6w:73:91 [1] NCCL INFO comm 0x7f5334002fb0 rank 3 nranks 8 cudaDev 1 busId 51000 - Init COMPLETE                                                                                                                                                                                                                
│ task-7701-z5h6w:72:90 [0] NCCL INFO comm 0x7ff44c002fb0 rank 2 nranks 8 cudaDev 0 busId 4b000 - Init COMPLETE                                                                                                                                                                                                                
│ task-7701-z5h6w:73:95 [0] transport/net_ib.cc:881 NCCL WARN NET/IB : Got completion from peer 172.17.80.61<47067> with error 12, opcode 1, len 0, vendor err 129                                                                                                                                                             
│ task-7701-z5h6w:73:95 [0] NCCL INFO include/net.h:28 -> 2                                                                                                                                                                                                                                                                    
│ task-7701-z5h6w:73:95 [0] NCCL INFO transport/net.cc:389 -> 2                                                                                                                                                                                                                                                                
│ task-7701-z5h6w:73:95 [0] NCCL INFO proxy.cc:351 -> 2                                                                                                                                                                                                                                                                        
│ task-7701-z5h6w:73:95 [0] NCCL INFO proxy.cc:452 -> 2 [Proxy Thread]                                                                                                                                                                                                                                                         
│ [E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.                                                            │
│ terminate called after throwing an instance of 'std::runtime_error'                                                                                                                                                                                                                                                          
│   what():  NCCL error: unhandled system error, NCCL version 2.10.3                                                                                                                                                                                                                                                           
│ ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. It can be also caused by unexpected exit of a remote peer, you can check NCCL warnings for failure reason and see if there is connection closure by a peer
```

third
```
task-7702-xt59c:73:73 [1] NCCL INFO Bootstrap : Using eth0:172.17.80.61<0>                                                                                                                                                                                                                                                   │
│ task-7702-xt59c:72:72 [0] NCCL INFO Bootstrap : Using eth0:172.17.80.61<0>                                                                                                                                                                                                                                                   │
│ task-7702-xt59c:73:73 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             │
│ task-7702-xt59c:72:72 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             │
│ task-7702-xt59c:73:73 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.61<0>                                                                                                                                                                                                   │
│ task-7702-xt59c:73:73 [1] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         │
│ task-7702-xt59c:72:72 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.61<0>                                                                                                                                                                                                   │
│ task-7702-xt59c:72:72 [0] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         │
│ task-7702-xt59c:72:91 [0] NCCL INFO Trees [0] 5/6/-1->4->0 [1] 5/-1/-1->4->3                                                                                                                                                                                                                                                 │
│ task-7702-xt59c:72:91 [0] NCCL INFO Setting affinity for GPU 0 to 7fffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000                                                                                                                                                                                    │
│ task-7702-xt59c:73:89 [1] NCCL INFO Trees [0] 2/-1/-1->5->4 [1] -1/-1/-1->5->4                                                                                                                                                                                                                                               │
│ task-7702-xt59c:73:89 [1] NCCL INFO Setting affinity for GPU 1 to 7fffffff,fffffffe,00000000,00000000,ffffffff,fffffffe,00000000,00000000                                                                                                                                                                                    │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 00 : 3[51000] -> 4[cb000] [receive] via NET/IB/2                                                                                                                                                                                                                                 │
│ task-7702-xt59c:73:89 [1] NCCL INFO Channel 00 : 5[d0000] -> 6[e000] [send] via NET/IB/2                                                                                                                                                                                                                                     │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 01 : 3[51000] -> 4[cb000] [receive] via NET/IB/2                                                                                                                                                                                                                                 │
│ task-7702-xt59c:73:89 [1] NCCL INFO Channel 01 : 5[d0000] -> 6[e000] [send] via NET/IB/2                                                                                                                                                                                                                                     │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 00 : 4[cb000] -> 5[d0000] via P2P/IPC/read                                                                                                                                                                                                                                       │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 01 : 4[cb000] -> 5[d0000] via P2P/IPC/read                                                                                                                                                                                                                                       │
│ task-7702-xt59c:73:89 [1] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      │
│ task-7702-xt59c:72:91 [0] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      │
│ task-7702-xt59c:73:89 [1] NCCL INFO Channel 00 : 2[4b000] -> 5[d0000] [receive] via NET/IB/2                                                                                                                                                                                                                                 │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 00 : 4[cb000] -> 6[e000] [send] via NET/IB/2                                                                                                                                                                                                                                     │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 00 : 0[92000] -> 4[cb000] [receive] via NET/IB/2                                                                                                                                                                                                                                 │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 00 : 4[cb000] -> 0[92000] [send] via NET/IB/2                                                                                                                                                                                                                                    │
│ task-7702-xt59c:73:89 [1] NCCL INFO Channel 00 : 5[d0000] -> 2[4b000] [send] via NET/IB/2                                                                                                                                                                                                                                    │
│ task-7702-xt59c:73:89 [1] NCCL INFO Channel 00 : 5[d0000] -> 4[cb000] via P2P/IPC/read                                                                                                                                                                                                                                       │
│ task-7702-xt59c:73:89 [1] NCCL INFO Channel 01 : 5[d0000] -> 4[cb000] via P2P/IPC/read                                                                                                                                                                                                                                       │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 00 : 6[e000] -> 4[cb000] [receive] via NET/IB/2                                                                                                                                                                                                                                  │
│ task-7702-xt59c:72:91 [0] NCCL INFO Channel 01 : 4[cb000] -> 3[51000] [send] via NET/IB/2                                                                                                                                                                                                                                    │
│ task-7702-xt59c:73:89 [1] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      │
│ task-7702-xt59c:73:89 [1] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              │
│ task-7702-xt59c:73:89 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 │
│ task-7702-xt59c:72:91 [0] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      │
│ task-7702-xt59c:72:91 [0] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              │
│ task-7702-xt59c:72:91 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 │
│ task-7702-xt59c:73:89 [1] NCCL INFO comm 0x7f1bf0002fb0 rank 5 nranks 8 cudaDev 1 busId d0000 - Init COMPLETE                                                                                                                                                                                                                │
│ task-7702-xt59c:72:91 [0] NCCL INFO comm 0x7f294c002fb0 rank 4 nranks 8 cudaDev 0 busId cb000 - Init COMPLETE
```

fourth
```
task-7703-j5hpd:73:73 [1] NCCL INFO Bootstrap : Using eth0:172.17.80.4<0>                                                                                                                                                                                                                                                    │
│ task-7703-j5hpd:72:72 [0] NCCL INFO Bootstrap : Using eth0:172.17.80.4<0>                                                                                                                                                                                                                                                    │
│ task-7703-j5hpd:73:73 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             │
│ task-7703-j5hpd:72:72 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                             │
│ task-7703-j5hpd:73:73 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.4<0>                                                                                                                                                                                                    │
│ task-7703-j5hpd:73:73 [1] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         │
│ task-7703-j5hpd:72:72 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB ; OOB eth0:172.17.80.4<0>                                                                                                                                                                                                    │
│ task-7703-j5hpd:72:72 [0] NCCL INFO Using network IB                                                                                                                                                                                                                                                                         │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Trees [0] -1/-1/-1->7->6 [1] -1/-1/-1->7->6                                                                                                                                                                                                                                              │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,fffffffd,00000000,00000000,ffffffff,fffffffd                                                                                                                                                                                                      │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Trees [0] 7/-1/-1->6->4 [1] 7/2/-1->6->-1                                                                                                                                                                                                                                                │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,fffffffd,00000000,00000000,ffffffff,fffffffd                                                                                                                                                                                                      │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 00 : 5[d0000] -> 6[e000] [receive] via NET/IB/0/GDRDMA                                                                                                                                                                                                                           │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 01 : 5[d0000] -> 6[e000] [receive] via NET/IB/0/GDRDMA                                                                                                                                                                                                                           │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 00 : 6[e000] -> 7[13000] via P2P/IPC/read                                                                                                                                                                                                                                        │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Channel 00 : 7[13000] -> 0[92000] [send] via NET/IB/0/GDRDMA                                                                                                                                                                                                                             │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 01 : 6[e000] -> 7[13000] via P2P/IPC/read                                                                                                                                                                                                                                        │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Channel 01 : 7[13000] -> 0[92000] [send] via NET/IB/0/GDRDMA                                                                                                                                                                                                                             │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Channel 00 : 7[13000] -> 6[e000] via P2P/IPC/read                                                                                                                                                                                                                                        │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Channel 01 : 7[13000] -> 6[e000] via P2P/IPC/read                                                                                                                                                                                                                                        │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Connected all rings                                                                                                                                                                                                                                                                      │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 00 : 4[cb000] -> 6[e000] [receive] via NET/IB/0/GDRDMA                                                                                                                                                                                                                           │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 01 : 2[4b000] -> 6[e000] [receive] via NET/IB/0/GDRDMA                                                                                                                                                                                                                           │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 01 : 6[e000] -> 2[4b000] [send] via NET/IB/0/GDRDMA                                                                                                                                                                                                                              │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Channel 00 : 6[e000] -> 4[cb000] [send] via NET/IB/0/GDRDMA                                                                                                                                                                                                                              │
│ task-7703-j5hpd:72:91 [0] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      │
│ task-7703-j5hpd:72:91 [0] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              │
│ task-7703-j5hpd:72:91 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 │
│ task-7703-j5hpd:73:89 [1] NCCL INFO Connected all trees                                                                                                                                                                                                                                                                      │
│ task-7703-j5hpd:73:89 [1] NCCL INFO threadThresholds 8/8/64 | 64/8/64 | 8/8/512                                                                                                                                                                                                                                              │
│ task-7703-j5hpd:73:89 [1] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer                                                                                                                                                                                                                                 │
│ task-7703-j5hpd:72:91 [0] NCCL INFO comm 0x7f6ccc002fb0 rank 6 nranks 8 cudaDev 0 busId e000 - Init COMPLETE                                                                                                                                                                                                                 │
│ task-7703-j5hpd:73:89 [1] NCCL INFO comm 0x7fb264002fb0 rank 7 nranks 8 cudaDev 1 busId 13000 - Init COMPLETE
```

**Comment by JuHyung-Son** [comment]
`transport/net_ib.cc:881 NCCL WARN NET/IB : Got completion from peer 172.17.80.61<47067> with error 12, opcode 1, len 0, vendor err 129`
this looks like communication between pod2 and pod3 has a problem. i ll look into it.

is there anything i should look further??

**Comment by sjeaugey** [comment]
I'm not sure I understand how you launched the above experiments. It seems some GPUs can communicate through NVLink but others can't and use IB. Are you launching across multiple systems or within just one? If so, why are some GPUs using IB?

**Comment by JuHyung-Son** [comment]
I`m running above experiment in kubernetes. for not just 1 node. node have 8 a100 gpus with 3 ib nic. gpu-operator and network-operator is installed in k8s.

I assign 2 gpus to a pod. and create 4 pods. the reason i`m doing this is because I`m building distributed learning platform. so people can use without having much knowledge about k8s and distribted system.

**Comment by sjeaugey** [comment]
Well, using Infiniband instead of NVLink is going to divide your performance by a factor of 10. On top of that, if you use the two GPUs which do not have a local NIC, you're going to need to go through the CPU, which will divide performance by another factor.

To give concrete numbers, within a node you should get 230GB/s, and between nodes (3 or more), it should be 72 GB/s. Splitting the nodes into smaller parts, performance is going to be at best 24 GB/s and it could drop way lower going through the CPU.

Ignoring performance now, your problem could be that mlx5_1 is not configured correctly and unable to communicate with other nodes, hence the timeout when you try to use it.

**Comment by JuHyung-Son** [comment]
thank you for concrete reply.
 i`ll look into mlx5_1 problem and consider resource policy for better performance

**Comment by JuHyung-Son** [comment]
@sjeaugey I found something looks important clue.

i tried two experiments.

1. using one ib nic for shared rdma plugin

rdma config is as below
```
config.json: |
 {
 "configList": [{
 "resourceName": "shared_ib0",
 "devices": ["ib0"]
 },
```


2. using more than 2 ib nic for shared rdma plugin
config:
```
config.json: |
 {
 "configList": [{
 "resourceName": "shared_ib0",
 "vendors": ["15b3"]
 },
```

then with first setting. it works well within a node. but not works when using more than 2 node. (node means a server with 8 gpus)

with second setting. it does not work well. with 2 problems.
problem 1: one pod hang with error message: `task-646--1-mhpnk:91:123 [0] transport/net_ib.cc:881 NCCL WARN NET/IB : Got completion from peer 172.17.127.143<49577> with error 12, opcode 1, len 0, vendor err 129`
problem2: it's super slow.

So, I guess it is related with number of ib nic or ib nic setting.

**Comment by sjeaugey** [comment]
`error 12` is a timeout. It means the NICs can't talk to each other. Are all of your IB NICs connected to the same network?

**Comment by JuHyung-Son** [comment]
Is there a way to check they are in same network??

i think they are in same network but dont know how to check it
-- 
null

**Comment by JuHyung-Son** [comment]
it seems there is a problem between infiniband nic connection. I will check after fixing hardware issue

**Comment by sjeaugey** [comment]
Running `ibnetdiscover` (as root) is usually a good way to see what's visible from the NIC and check other NICs are there as well. Of course, you need root access for that.
