### ISSUE TITLE
NCCL Test Failing with newer NCCL versions for RoCE with Dual HCA inside VMs

### ISSUE THREAD

**Issue by apoorvemohan** [NVIDIA/nccl#749]
We are benchmarking our VM setup with `NCCL 2.14.3` using `nccl-test` and observe the following error when using 2 HCA (however when using 1 HCA, everything works fine). Also, we get this error when using any NCCL >2.11.4 version (including the latest version). 

[nccl-test-roce-error.log](https://github.com/NVIDIA/nccl/files/10004291/nccl-test-roce-error.log)

`COMMAND:`

```
/root/openmpi/bin/mpirun --allow-run-as-root -np 16 -host 192.168.100.100:8,192.168.100.101:8 -x NCCL_IB_DISABLE=0 -x NCCL_IB_HCA=mlx5_0,mlx5_1 -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 -x NCCL_DEBUG=INFO -x NCCL_DEBUG_SUBSYS=INIT,GRAPH,ENV,TUNING -x NCCL_SOCKET_IFNAME=enp10s0np0 -x NCCL_IGNORE_CPU_AFFINITY=1 -x NCCL_ALGO=Ring -x NCCL_TREE_THRESHOLD=0 -x LD_LIBRARY_PATH=/root/nccl-2.14.3-1/build/lib:$LD_LIBRARY_PATH -x LD_LIBRARY_PATH=/root/nccl-rdma-sharp-plugins/INSTALL/lib:$LD_LIBRARY_PATH -x NCCL_IB_PCI_RELAXED_ORDERING=1 -x NCCL_SOCKET_NTHREADS=2 -x NCCL_IB_GID_INDEX=3 -x NCCL_TOPO_FILE=/root/topo1.xml  -x NCCL_NET_GDR_LEVEL=0 --mca btl_base_verbose 100 --mca btl tcp,self --mca btl_tcp_if_include enp10s0np0 /root/nccl-tests/build/all_reduce_perf -c 0 -b 8 -e 8G -f 2 -g 1
```

`NCCL TOPOLOGY FIle:`

```
<system version="1">
  <cpu numaid="0" affinity="0000,00ffffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="ffff:ff:00.0" class="0x060400" vendor="0x104c" device="0x8232" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="2.5 GT/s" link_width="1">
      <pci busid="0000:08:01.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
      <pci busid="0000:08:02.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
      <pci busid="0000:08:00.0" class="0x020000" vendor="0x15b3" device="0x101d" subsystem_vendor="0x15b3" subsystem_device="0x0041" link_speed="16 GT/s" link_width="16">
      </pci>
    </pci>
    <pci busid="ffff:fd:00.0" class="0x060400" vendor="0x104c" device="0x8232" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="2.5 GT/s" link_width="1">
      <pci busid="0000:0a:03.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
      <pci busid="0000:0a:04.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
    </pci>
  </cpu>
  <cpu numaid="1" affinity="ffff,ff000000" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="85">
    <pci busid="ffff:fe:00.0" class="0x060400" vendor="0x104c" device="0x8232" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="2.5 GT/s" link_width="1">
      <pci busid="0000:0c:05.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
      <pci busid="0000:0c:06.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
      <pci busid="0000:0c:00.0" class="0x020000" vendor="0x15b3" device="0x101d" subsystem_vendor="0x15b3" subsystem_device="0x0041" link_speed="16 GT/s" link_width="16">
      </pci>
    </pci>
    <pci busid="ffff:fc:00.0" class="0x060400" vendor="0x104c" device="0x8232" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="2.5 GT/s" link_width="1">
      <pci busid="0000:0e:07.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
      <pci busid="0000:0e:08.0" class="0x030200" vendor="0x10de" device="0x20b2" subsystem_vendor="0x10de" subsystem_device="0x1463" link_speed="16 GT/s" link_width="16">
      </pci>
    </pci>
  </cpu>
</system>
```

`SYSTEM TOPOLOGY:`

```
root@vm-133:~# lspci -vt | grep -i "nvidia\|mel"
-+-[0000:0d]---00.0-[0e]--+-07.0  NVIDIA Corporation Device 20b2
 |                        \-08.0  NVIDIA Corporation Device 20b2
 +-[0000:0b]---00.0-[0c]--+-00.0  Mellanox Technologies MT28850
 |                        +-05.0  NVIDIA Corporation Device 20b2
 |                        +-06.0  NVIDIA Corporation Device 20b2
 |                        +-09.0  NVIDIA Corporation Device 1af1
 |                        +-0a.0  NVIDIA Corporation Device 1af1
 |                        +-0b.0  NVIDIA Corporation Device 1af1
 |                        +-0c.0  NVIDIA Corporation Device 1af1
 |                        +-0d.0  NVIDIA Corporation Device 1af1
 |                        \-0e.0  NVIDIA Corporation Device 1af1
 +-[0000:09]---00.0-[0a]--+-00.0  Mellanox Technologies MT28850
 |                        +-03.0  NVIDIA Corporation Device 20b2
 |                        \-04.0  NVIDIA Corporation Device 20b2
 +-[0000:07]---00.0-[08]--+-01.0  NVIDIA Corporation Device 20b2
 |                        \-02.0  NVIDIA Corporation Device 20b2
```

`ERROR:`

```
vm-133:52744:52787 [0] ibvwrap.c:160 NCCL WARN Call to ibv_modify_qp failed with error Connection timed out
vm-133:52744:52787 [0] NCCL INFO ib_plugin.c:297 -> 2
vm-133:52744:52787 [0] NCCL INFO ib_plugin.c:477 -> 2
vm-133:52744:52787 [0] NCCL INFO include/net.h:27 -> 2
vm-133:52744:52787 [0] NCCL INFO transport/net.cc:651 -> 2
vm-133:52744:52787 [0] NCCL INFO proxy.cc:991 -> 2

vm-133:52744:52787 [0] proxy.cc:1119 NCCL WARN [Proxy Service 4] Failed to execute operation Connect from rank 4, retcode 2

vm-133:52744:52782 [0] misc/socket.cc:538 NCCL WARN Net : Connection closed by remote peer vm-133<57347>
vm-133:52744:52782 [0] NCCL INFO misc/socket.cc:546 -> 6
vm-133:52744:52782 [0] NCCL INFO misc/socket.cc:558 -> 6
vm-133:52744:52782 [0] NCCL INFO proxy.cc:881 -> 6

vm-133:52744:52782 [0] proxy.cc:884 NCCL WARN Proxy Call to rank 4 failed (Connect)
vm-133:52744:52782 [0] NCCL INFO transport/net.cc:315 -> 6
vm-133:52744:52782 [0] NCCL INFO transport.cc:134 -> 6
vm-133:52744:52782 [0] NCCL INFO init.cc:790 -> 6
vm-133:52744:52782 [0] NCCL INFO init.cc:1089 -> 6
vm-133:52744:52782 [0] NCCL INFO group.cc:64 -> 6 [Async thread]
vm-133:52744:52744 [0] NCCL INFO group.cc:421 -> 3
vm-133:52744:52744 [0] NCCL INFO group.cc:106 -> 3
vm-133: Test NCCL failure common.cu:958 'internal error / '
 .. vm-133 pid 52744: Test failure common.cu:842

vm-132:7824:7867 [0] ibvwrap.c:160 NCCL WARN Call to ibv_modify_qp failed with error Connection timed out
vm-132:7824:7867 [0] NCCL INFO ib_plugin.c:297 -> 2
vm-132:7824:7867 [0] NCCL INFO ib_plugin.c:477 -> 2
vm-132:7824:7867 [0] NCCL INFO include/net.h:27 -> 2
vm-132:7824:7867 [0] NCCL INFO transport/net.cc:651 -> 2
vm-132:7824:7867 [0] NCCL INFO proxy.cc:991 -> 2

vm-132:7824:7867 [0] proxy.cc:1119 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 2

vm-132:7824:7854 [0] misc/socket.cc:538 NCCL WARN Net : Connection closed by remote peer vm-132<43545>
vm-132:7824:7854 [0] NCCL INFO misc/socket.cc:546 -> 6
vm-132:7824:7854 [0] NCCL INFO misc/socket.cc:558 -> 6
vm-132:7824:7854 [0] NCCL INFO proxy.cc:881 -> 6

vm-132:7824:7854 [0] proxy.cc:884 NCCL WARN Proxy Call to rank 0 failed (Connect)
vm-132:7824:7854 [0] NCCL INFO transport/net.cc:315 -> 6
vm-132:7824:7854 [0] NCCL INFO transport.cc:134 -> 6
vm-132:7824:7854 [0] NCCL INFO init.cc:790 -> 6
vm-132:7824:7854 [0] NCCL INFO init.cc:1089 -> 6
vm-132:7824:7854 [0] NCCL INFO group.cc:64 -> 6 [Async thread]
vm-132:7824:7824 [0] NCCL INFO group.cc:421 -> 3
vm-132:7824:7824 [0] NCCL INFO group.cc:106 -> 3
vm-132: Test NCCL failure common.cu:958 'internal error / '
 .. vm-132 pid 7824: Test failure common.cu:842
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[40716,1],4]
  Exit code:    3
  ```

**Comment by sjeaugey** [comment]
Did you check that each HCA in isolation worked fine (using `NCCL_IB_HCA`)?
Also, can HCA talk to each other ?

**Comment by apoorvemohan** [comment]
> Did you check that each HCA in isolation worked fine (using NCCL_IB_HCA)?

Yes, each HCA in isolation  (using `NCCL_IB_HCA`) is working fine. 

> Also, can HCA talk to each other ?

Across the VMs, `ib_write_bw` test (bi-directional) works for both HCA.

**Comment by sjeaugey** [comment]
Can you set NCCL_IB_HCA=mlx5_0 on one node and NCCL_IB_HCA=mlx5_1 on another node and see if it works?

You may want to write a wrapper script like:
select_different_hca.sh:
```
#!/bin/bash
if [ `hostname` == host1 ]; then
  NCCL_IB_HCA=mlx5_0 $@
else
  NCCL_IB_HCA=mlx5_1 $@
fi
```
Then run with:
```
mpirun -np ... ./select_different_hca.sh ./myapp
```

**Comment by apoorvemohan** [comment]
Nccl-test fails when testing across NICs. Please see the attached logs. 

[cross_nic_2.10.3.txt](https://github.com/NVIDIA/nccl/files/10042385/cross_nic_2.10.3.txt)
[cross_nic_2.14.3.txt](https://github.com/NVIDIA/nccl/files/10042386/cross_nic_2.14.3.txt)

**Comment by sjeaugey** [comment]
Ok so that confirms the two NICs can't talk to each other. You may want to try with `NCCL_CROSS_NIC=0` but that may result in lower performance so ideally you should configure your network to enable communication across subnets.

**Comment by apoorvemohan** [comment]
`NCCL_CROSS_NIC=0` fix the issue with a performance with the newer NCCL.

I am a bit confused. Why is this a problem only in newer NCCL versions?

**Comment by sjeaugey** [comment]
That's probably because newer NCCL found a way to achieve better performance, communicating across NICs. The default is to avoid communicating across NICs unless it brings better performance (or the users explicitely forbid it with NCCL_CROSS_NIC=0). So, if cross-NIC communication was working, your newer NCCL would have better performance than older NCCL (which we would expect).

**Comment by apoorvemohan** [comment]
I see.

With the `NCCL_CROSS_NIC=0` I observe ~30% degradation in the reported peak bandwidth with the newer NCCL. Shouldn't the newer NCCL perform at par with the older NCCL?

**Comment by sjeaugey** [comment]
Indeed it should not be the case. What is the peak bandwidth you're seeing? Can you dump graphs in both cases (NCCL_GRAPH_DUMP_FILE=graph.xml) and post them?

**Comment by apoorvemohan** [comment]
Here are the graphs for the two nccl versions:

[graph_2_10_3.xml.txt](https://github.com/NVIDIA/nccl/files/10071883/graph_2_10_3.xml.txt)
[graph_2_14_3.xml.txt](https://github.com/NVIDIA/nccl/files/10071884/graph_2_14_3.xml.txt)

**Comment by sjeaugey** [comment]
Can you also share the topology dump  (`NCCL_TOPO_DUMP_FILE=system.xml`) for each version? 
Something seems wrong with the topology; with 2.10.3 you end up with 2 rings@0.12GB/s using NIC 1 and one NIC@0.12GB/s using NIC 0. I would assume each NIC should have the same number of rings at least?
With 2.13 you end up with just 2 rings @0.12 GB/s using NIC 1. There must be a bottleneck somewhere in the topology which restricts the proper creation of rings.

**Comment by sjeaugey** [comment]
Actually the topology file you're injecting does define a bottleneck on the CPU-PCI connection:
```
    <pci busid="ffff:ff:00.0" class="0x060400" vendor="0x104c" device="0x8232" subsystem_vendor="0x0000" subsystem_device="0x0000" link_speed="2.5 GT/s" link_width="1">
```
Plus the graph show inter-node communication goes through the CPU. You should probably enable GPU Direct RDMA if NICs are connected to PCI switches. Otherwise (performance will be lower), you should not create an artificial bottleneck between the CPU and PCI switches.

**Comment by apoorvemohan** [comment]
As I compare the topo dump files for the two mccl versions, I see he following differences:

```
root@vm-132:~/nccl-rdma-sharp-plugins# diff /root/topo_dump_2_10_3.xml /root/topo_dump_2_14_3.xml
5c5
<         <gpu dev="0" sm="80" rank="0" gdr="0">
---
>         <gpu dev="0" sm="80" rank="0" gdr="1">
15c15
<         <gpu dev="1" sm="80" rank="1" gdr="0">
---
>         <gpu dev="1" sm="80" rank="1" gdr="1">
27c27
<         <gpu dev="2" sm="80" rank="2" gdr="0">
---
>         <gpu dev="2" sm="80" rank="2" gdr="1">
37c37
<         <gpu dev="3" sm="80" rank="3" gdr="0">
---
>         <gpu dev="3" sm="80" rank="3" gdr="1">
49c49
<         <net name="mlx5_1" dev="1" speed="100000" port="1" guid="0xb8089d0003723f04" maxconn="131072" gdr="0"/>
---
>         <net name="mlx5_1" dev="1" speed="100000" port="1" latency="0.000000" guid="0xb8089d0003723f04" maxconn="131072" gdr="0"/>
56c56
<         <gpu dev="4" sm="80" rank="4" gdr="0">
---
>         <gpu dev="4" sm="80" rank="4" gdr="1">
66c66
<         <gpu dev="5" sm="80" rank="5" gdr="0">
---
>         <gpu dev="5" sm="80" rank="5" gdr="1">
77c77
<           <net name="mlx5_0" dev="0" speed="100000" port="1" guid="0xb0089d0003723f04" maxconn="131072" gdr="0"/>
---
>           <net name="mlx5_0" dev="0" speed="100000" port="1" latency="0.000000" guid="0xb0089d0003723f04" maxconn="131072" gdr="0"/>
83c83
<         <gpu dev="6" sm="80" rank="6" gdr="0">
---
>         <gpu dev="6" sm="80" rank="6" gdr="1">
93c93
<         <gpu dev="7" sm="80" rank="7" gdr="0">
---
>         <gpu dev="7" sm="80" rank="7" gdr="1">
```

I am a bit confused as I am specifying `NCCL_NET_GDR_LEVEL=0` in the run command. However, for NCCL 2.14.3, the GDR flag gets set.

**Comment by sjeaugey** [comment]
`NCCL_NET_GDR_LEVEL` may be taken into account later. Why would you want to set it to 0 though? That would make performance much worse.

Now if that's because GDR doesn't work (efficiently at least), then you should probably set `link_speed="16 GT/s" link_width="16"` for the PCI switches we add to the topology. Otherwise NCCL will be struggling to find the best paths.

**Comment by apoorvemohan** [comment]
I figured out an issue with the topology file I was using. After fixing that, the difference in the peek bandwidth between the two versions of NCCL increased even further (~9GB/s with NCCL 2.14.3 vs ~14 GB/s with NCCL 2.10.3). 

[graph_dump_2_10_3.xml.txt](https://github.com/NVIDIA/nccl/files/10108239/graph_dump_2_10_3.xml.txt)
[graph_dump_2_14_3.xml.txt](https://github.com/NVIDIA/nccl/files/10108240/graph_dump_2_14_3.xml.txt)
[topo_dump_2_10_3.xml.txt](https://github.com/NVIDIA/nccl/files/10108241/topo_dump_2_10_3.xml.txt)
[topo_dump_2_14_3.xml.txt](https://github.com/NVIDIA/nccl/files/10108242/topo_dump_2_14_3.xml.txt)

**Comment by sjeaugey** [comment]
I'd need to dig further to confirm my suspicion, but I think the algorithm is struggling to find the optimal solution because the search is too wide, as GPU Direct RDMA is disabled, the combinations to search for are too large as we tried to reduce the search depth (to accelerate ncclCommInit) in recent versions.

When GPU Direct is disabled, communicating between the NIC and GPUs local to the NIC is actually worse than communicating with other GPUs on the same CPU socket. But that's also CPU/Memory dependent so it's hard to predict which will work better. 2.10 gets that right as ring 0 uses GPUs 0/1 when the NIC is close to GPUs 2/3, and similarly on the the second ring where it uses GPUs 6 and 7 when the NIC is attached to GPUs 4/5. NCCL 2.14 uses GPUs 4/5 which are local to the NIC hence cause reduced bandwidth.

With GPU Direct RDMA enabled, you'd get 24 GB/s, with both versions. I'd really recommend pursuing that path. The whole point of having NICs attached to PCI switches is to allow for direct NIC-GPU communication.

**Comment by apoorvemohan** [comment]
While you investigate the NCCL code, is it possible to force NCCL to use a specific graph file or modify the topology file in any specific way so that the newer NCCL versions can achieve a similar performance to what we get with the older NCCL versions?

**Comment by sjeaugey** [comment]
Yes if you set `NCCL_GRAPH_FILE=old_graph.xml` you should get the same performance.

**Comment by apoorvemohan** [comment]
> Yes if you set NCCL_GRAPH_FILE=old_graph.xml you should get the same performance.

Thanks, this worked.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're reviewing older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
