### ISSUE TITLE
Segmentation fault with cuda-7.5

### ISSUE THREAD

**Issue by Jerrynet** [NVIDIA/nccl#8]
I build nccl with cuda-7.5:
```
make CUDA_HOME=/usr/local/cuda-7.5 test
```
And run test with the following command:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./build/lib
./build/test/all_reduce_test
```
causes a segmentation fault:
```
# Using devices
Segmentation fault
```
But all tests run smoothly if I build ```nccl``` with cuda-7.0.
Is the current version of ```nccl``` not compatible with cuda-7.5?

**Comment by cliffwoolley** [comment]
I've seen a similar issue when libcuda.so is not in the LD_LIBRARY_PATH (on
one of my systems, only libcuda.so.1 was there, but the usual libcuda.so
symlink was absent).  Can you please check that?  If it turns out that's
your issue, you can either simply `ln -s libcuda.so.1 libcuda.so` in the
relevant directory or you can modify NCCL to dlopen libcuda.so.1 instead of
libcuda.so.

Thanks,
Cliff

**Comment by cliffwoolley** [comment]
Oh, and yes, NCCL is normally compatible with CUDA 7.5.  It actually is a
bit more complete on CUDA 7.5 than on 7.0, since 7.0 lacked some of the
necessary support for the fp16 'half' datatype.

**Comment by cliffwoolley** [comment]
Side note: assuming this is the same issue with libcuda.so that I'm referring to, we should fix the tests to fail more gracefully when the communicator cannot be created.  The segfault happens when we pass a NULL communicator to some subsequent routine.

**Comment by Jerrynet** [comment]
@cliffwoolley Thanks for the explanation.
I create a symlink to ```libcuda.so.1``` and now it works!
So it's the same issue with ```libcuda.so```.

**Comment by cliffwoolley** [comment]
Great!  Glad to hear it.  We'll leave this issue open to deal with the libcuda.so[.1] loading (perhaps we could try both variants before giving up) as well as to detect communicator creation failure in the test apps without segfaulting.  I believe @nluehr already has fixes pending for one or both of these issues.

**Comment by nluehr** [comment]
These issues are resolved in change sets caa40b8 and 2758353.
