### ISSUE TITLE
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

### ISSUE THREAD

**Issue by alicera** [NVIDIA/nccl#833]
I try to use pytorch to train.
I use two machine to train.
I use the docker 
I make sure each machine are connected with ping and it show the rank is fine

I meet the error whe training
what is the possible status, what should I do for machine setting?

ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

**Comment by AddyLaddy** [comment]
What are the nodes specs? 
How many GPUs per node?
What is CUDA driver and toolkit version?
Does it work on a single node?
What container and version are you using?

Can you compile and run the nccl-tests from: https://github.com/NVIDIA/nccl-tests

Can we see the full log with `NCCL_DEBUG=INFO`

**Comment by alicera** [comment]
Thanks for your nccl-tests

before the test

What are the nodes specs?     nodes = 2
How many GPUs per node?    4 GPUs per node
What is CUDA driver and toolkit version?  cuda 11.7 
Does it work on a single node?  yes, it work
What container and version are you using?     pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime


here is my command 
```
docker run -it --gpus all --rm -v $(pwd):/mnt --network=host --shm-size='6gb' pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

```
```
torchrun --nnodes=2 --node-rank=0 --master-addr="10.0.0.1" --master-port=1234 --nproc-per-node 4 test_ddp.py

torchrun --nnodes=2 --node-rank=1 --master-addr="10.0.0.1" --master-port=1234 --nproc-per-node 4 test_ddp.py
```


here is the error

```
[334] Initializing process group with: {'MASTER_ADDR': '10.0.0.1', 'MASTER_PORT': '1234', 'WORLD_SIZE': '8', 'LOCAL_WORLD_SIZE': '4'}
[335] Initializing process group with: {'MASTER_ADDR': '10.0.0.1', 'MASTER_PORT': '1234', 'WORLD_SIZE': '8', 'LOCAL_WORLD_SIZE': '4'}
[332] Initializing process group with: {'MASTER_ADDR': '10.0.0.1', 'MASTER_PORT': '1234', 'WORLD_SIZE': '8', 'LOCAL_WORLD_SIZE': '4'}
[333] Initializing process group with: {'MASTER_ADDR': '10.0.0.1', 'MASTER_PORT': '1234', 'WORLD_SIZE': '8', 'LOCAL_WORLD_SIZE': '4'}
Traceback (most recent call last):
  File "/mnt/DDP/yolov5/test_ddp.py", line 62, in <module>
    run()
  File "/mnt/DDP/yolov5/test_ddp.py", line 57, in run
    train()
  File "/mnt/DDP/yolov5/test_ddp.py", line 35, in train
    ddp_model = DDP(model, [local_rank])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1678411187366/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Proxy Call to rank 3 failed (Connect)
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 332 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 333 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 334 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 335) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test_ddp.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-02_05:23:57
  host      : mahcine
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 335)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```



here is the mini code

```
import argparse
import os

import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim


from torch.nn.parallel import DistributedDataParallel as DDP

class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(self.relu(self.net1(x)))


def train():
    local_rank = int(os.environ["LOCAL_RANK"])
    rank = int(os.environ["RANK"])
    model = ToyModel().cuda(local_rank)
    ddp_model = DDP(model, [local_rank])
    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    for i in range(10):
        print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) training...")

        optimizer.zero_grad()
        outputs = ddp_model(torch.randn(20, 10).to(local_rank))
        labels = torch.randn(20, 5).to(local_rank)
        loss = loss_fn(outputs, labels)
        loss.backward()
        print(f"[{os.getpid()}] (rank = {rank}, local_rank = {local_rank}) loss = {loss.item()}\n")
        optimizer.step()

def run():
    env_dict = {
        key: os.environ[key]
        for key in ("MASTER_ADDR", "MASTER_PORT", "WORLD_SIZE", "LOCAL_WORLD_SIZE")
    }
    print(f"[{os.getpid()}] Initializing process group with: {env_dict}")
    dist.init_process_group(backend="nccl")
    train()
    dist.destroy_process_group()


if __name__ == "__main__":
    run()
```


what do I miss for the setting ?

**Comment by AddyLaddy** [comment]
I think we'd need to see the `NCCL_DEBUG=INFO` log or even just `NCCL_DEBUG=WARN` in order to understand what's going wrong.
I'm not a Pytorch expert, but is each process initializing NCCL with a rank from 0-7 and on a different GPU for each rank?
What command do you use to launch a 4 GPU job on a single node?

Is there a Pytorch forum where you can find advice on running multiple node jobs?

**Comment by awelldone** [comment]
> 我尝试使用 pytorch 进行训练。 我用两台机器来训练。 我使用 docker 我确保每台机器都与 ping 连接并且它显示等级很好
> 
> 训练时遇到错误 what is possible status，机器设置应该怎么办？
> 
> ncclInternalError：内部检查失败。这是 NCCL 中的错误或由于内存损坏

你好， 你的问题解决了吗  我也碰到了这个错误 一模一样

**Comment by adi** [comment]
I think I found out the reason for the above issue. It seems NCCL has problems working in an IPV6 environment. If you just stop IPV6 altogether using:

```bash
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

the above error doesn't show up anymore and the distributed training is running as expected.

**Comment by ykk648** [comment]
seems network issue, I solved it by disable proxys

**Comment by Chtholly1** [comment]
> seems network issue, I solved it by disable proxys

Hi, could you please explain it in detail？

**Comment by ykk648** [comment]
@Chtholly1 多卡通信的问题，我这边是proxy中localhost的地址访问不到，你可以先用单卡测试，多卡多节点看报错信息，排查网络

**Comment by Chtholly1** [comment]
> @Chtholly1 多卡通信的问题，我这边是proxy中localhost的地址访问不到，你可以先用单卡测试，多卡多节点看报错信息，排查网络

我单机多卡能跑起来，机器之间也能ping的通，麻烦问下你说的这个方法具体怎么操作呢？

**Comment by ykk648** [comment]
@Chtholly1 我这边是单机问题，建议你根据报错信息排查网络和端口，可以写一个最简单的 torch/accelerate demo测试

**Comment by Corle-hyz** [comment]
I meet this problem too. It could not work even when I disabled the IPV6. Have you solved it?

**Comment by xsank** [comment]
> seems network issue, I solved it by disable proxys

How to disable proxys? thanks

**Comment by mali404** [comment]
I am facing similar issue. I am using torch version 1.11 and deepspeed version 0.6.5. Given below is the complete output after enabling "NCCL_DEBUG":
[2024-08-29 08:09:32,785] [WARNING] [runner.py:159:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-08-29 08:09:33,103] [INFO] [runner.py:457:main] cmd = /opt/conda/bin/python3.8 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 minGPT/minGPT/runFirstDeepSpeed.py --deepspeed True --deepspeed_config minGPT/minGPT/ds_config_basic.json
[2024-08-29 08:09:34,113] [INFO] [launch.py:96:main] 0 NCCL_VERSION=2.11.4
[2024-08-29 08:09:34,113] [INFO] [launch.py:96:main] 0 NCCL_DEBUG=INFO
[2024-08-29 08:09:34,113] [INFO] [launch.py:103:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2024-08-29 08:09:34,113] [INFO] [launch.py:109:main] nnodes=1, num_local_procs=4, node_rank=0
[2024-08-29 08:09:34,114] [INFO] [launch.py:122:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2024-08-29 08:09:34,114] [INFO] [launch.py:123:main] dist_world_size=4
[2024-08-29 08:09:34,114] [INFO] [launch.py:125:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2024-08-29 08:09:35,263] [INFO] [distributed.py:48:init_distributed] Initializing torch distributed with backend: nccl
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verifiedFiles already downloaded and verified

Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
done step 1/8, re-initialized 4 dead clusters
done step 1/8, re-initialized 4 dead clusters
done step 1/8, re-initialized 4 dead clusters
done step 1/8, re-initialized 4 dead clusters
done step 2/8, re-initialized 0 dead clusters
done step 2/8, re-initialized 0 dead clusters
done step 2/8, re-initialized 0 dead clusters
done step 2/8, re-initialized 0 dead clusters
done step 3/8, re-initialized 0 dead clusters
done step 3/8, re-initialized 0 dead clusters
done step 3/8, re-initialized 0 dead clusters
done step 3/8, re-initialized 0 dead clusters
done step 4/8, re-initialized 0 dead clusters
done step 4/8, re-initialized 0 dead clusters
done step 4/8, re-initialized 0 dead clusters
done step 4/8, re-initialized 0 dead clusters
done step 5/8, re-initialized 0 dead clusters
done step 5/8, re-initialized 0 dead clusters
done step 5/8, re-initialized 0 dead clusters
done step 5/8, re-initialized 0 dead clusters
done step 6/8, re-initialized 0 dead clusters
done step 6/8, re-initialized 0 dead clusters
done step 6/8, re-initialized 0 dead clusters
done step 6/8, re-initialized 0 dead clusters
done step 7/8, re-initialized 0 dead clusters
done step 7/8, re-initialized 0 dead clusters
done step 7/8, re-initialized 0 dead clusters
done step 7/8, re-initialized 0 dead clusters
done step 8/8, re-initialized 0 dead clusters
done step 8/8, re-initialized 0 dead clusters
done step 8/8, re-initialized 0 dead clusters
08/29/2024 08:09:51 - INFO - mingpt.model -   number of parameters: 1.000166e+07
[2024-08-29 08:09:51,477] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed info: version=0.6.5, git-hash=unknown, git-branch=unknown
done step 8/8, re-initialized 0 dead clusters
08/29/2024 08:09:51 - INFO - mingpt.model -   number of parameters: 1.000166e+07
08/29/2024 08:09:51 - INFO - mingpt.model -   number of parameters: 1.000166e+07
08/29/2024 08:09:51 - INFO - mingpt.model -   number of parameters: 1.000166e+07
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Added key: store_based_barrier_key:2 to store for rank: 0
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Added key: store_based_barrier_key:2 to store for rank: 3
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Added key: store_based_barrier_key:2 to store for rank: 2
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Rank 2: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Added key: store_based_barrier_key:2 to store for rank: 1
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Rank 1: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
08/29/2024 08:09:53 - INFO - torch.distributed.distributed_c10d -   Rank 3: Completed store-based barrier for key:store_based_barrier_key:2 with 4 nodes.
lab:14072:14072 [0] NCCL INFO Bootstrap : Using eth0:172.18.0.7<0>
lab:14072:14072 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
lab:14072:14072 [0] NCCL INFO P2P plugin IBext
lab:14072:14072 [0] NCCL INFO NET/IB : No device found.
lab:14072:14072 [0] NCCL INFO NET/IB : No device found.
lab:14072:14072 [0] NCCL INFO NET/Socket : Using [0]eth0:172.18.0.7<0>
lab:14072:14072 [0] NCCL INFO Using network Socket
NCCL version 2.11.4+cuda11.5
lab:14075:14075 [3] NCCL INFO Bootstrap : Using eth0:172.18.0.7<0>
lab:14074:14074 [2] NCCL INFO Bootstrap : Using eth0:172.18.0.7<0>
lab:14073:14073 [1] NCCL INFO Bootstrap : Using eth0:172.18.0.7<0>
lab:14074:14074 [2] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
lab:14074:14074 [2] NCCL INFO P2P plugin IBext
lab:14073:14073 [1] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
lab:14073:14073 [1] NCCL INFO P2P plugin IBext
lab:14074:14074 [2] NCCL INFO NET/IB : No device found.
lab:14073:14073 [1] NCCL INFO NET/IB : No device found.
lab:14074:14074 [2] NCCL INFO NET/IB : No device found.
lab:14073:14073 [1] NCCL INFO NET/IB : No device found.
lab:14074:14074 [2] NCCL INFO NET/Socket : Using [0]eth0:172.18.0.7<0>
lab:14074:14074 [2] NCCL INFO Using network Socket
lab:14073:14073 [1] NCCL INFO NET/Socket : Using [0]eth0:172.18.0.7<0>
lab:14073:14073 [1] NCCL INFO Using network Socket
lab:14075:14075 [3] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
lab:14075:14075 [3] NCCL INFO P2P plugin IBext
lab:14075:14075 [3] NCCL INFO NET/IB : No device found.
lab:14075:14075 [3] NCCL INFO NET/IB : No device found.
lab:14075:14075 [3] NCCL INFO NET/Socket : Using [0]eth0:172.18.0.7<0>
lab:14075:14075 [3] NCCL INFO Using network Socket
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 1/-1/-1->2->3 [2] 3/-1/-1->2->1 [3] 1/-1/-1->2->3
lab:14074:14863 [2] NCCL INFO Setting affinity for GPU 2 to ff,ffff0000,00000000
lab:14075:14865 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] 2/-1/-1->3->0 [2] -1/-1/-1->3->2 [3] 2/-1/-1->3->0
lab:14075:14865 [3] NCCL INFO Setting affinity for GPU 3 to ffffff00,00000000,00000000
lab:14073:14864 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] -1/-1/-1->1->2 [2] 2/-1/-1->1->0 [3] -1/-1/-1->1->2
lab:14073:14864 [1] NCCL INFO Setting affinity for GPU 1 to ffff,ff000000
lab:14072:14862 [0] NCCL INFO Channel 00/04 :    0   1   2   3
lab:14072:14862 [0] NCCL INFO Channel 01/04 :    0   3   2   1
lab:14072:14862 [0] NCCL INFO Channel 02/04 :    0   1   2   3
lab:14072:14862 [0] NCCL INFO Channel 03/04 :    0   3   2   1
lab:14072:14862 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 3/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 3/-1/-1->0->-1
lab:14072:14862 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Channel 00 : 3[400000] -> 0[100000] via direct shared memory
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Channel 02 : 3[400000] -> 0[100000] via direct shared memory
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14073:14864 [1] NCCL INFO Channel 00 : 1[200000] -> 2[300000] via direct shared memory
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Channel 02 : 1[200000] -> 2[300000] via direct shared memory
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14072:14862 [0] NCCL INFO Channel 00 : 0[100000] -> 1[200000] via P2P/IPC/read
lab:14072:14862 [0] NCCL INFO Channel 02 : 0[100000] -> 1[200000] via P2P/IPC/read
lab:14074:14863 [2] NCCL INFO Channel 00 : 2[300000] -> 3[400000] via P2P/IPC/read
lab:14074:14863 [2] NCCL INFO Channel 02 : 2[300000] -> 3[400000] via P2P/IPC/read
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Channel 01 : 0[100000] -> 3[400000] via direct shared memory
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14072:14862 [0] NCCL INFO Channel 03 : 0[100000] -> 3[400000] via direct shared memory
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14074:14863 [2] NCCL INFO Channel 01 : 2[300000] -> 1[200000] via direct shared memory
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Channel 03 : 2[300000] -> 1[200000] via direct shared memory
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14073:14864 [1] NCCL INFO Channel 01 : 1[200000] -> 0[100000] via P2P/IPC/read
lab:14073:14864 [1] NCCL INFO Channel 03 : 1[200000] -> 0[100000] via P2P/IPC/read
lab:14075:14865 [3] NCCL INFO Channel 01 : 3[400000] -> 2[300000] via P2P/IPC/read
lab:14075:14865 [3] NCCL INFO Channel 03 : 3[400000] -> 2[300000] via P2P/IPC/read
lab:14073:14864 [1] NCCL INFO Connected all rings
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Channel 01 : 1[200000] -> 2[300000] via direct shared memory
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Channel 03 : 1[200000] -> 2[300000] via direct shared memory
lab:14075:14865 [3] NCCL INFO Connected all rings
lab:14072:14862 [0] NCCL INFO Connected all rings
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Connected all rings
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Channel 01 : 3[400000] -> 0[100000] via direct shared memory
lab:14075:14865 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
lab:14075:14865 [3] NCCL INFO Channel 03 : 3[400000] -> 0[100000] via direct shared memory
lab:14072:14862 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Channel 01 : 2[300000] -> 3[400000] via P2P/IPC/read
lab:14074:14863 [2] NCCL INFO Channel 03 : 2[300000] -> 3[400000] via P2P/IPC/read
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Channel 00 : 2[300000] -> 1[200000] via direct shared memory
lab:14074:14863 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
lab:14074:14863 [2] NCCL INFO Channel 02 : 2[300000] -> 1[200000] via direct shared memory
lab:14075:14865 [3] NCCL INFO Channel 00 : 3[400000] -> 2[300000] via P2P/IPC/read
lab:14075:14865 [3] NCCL INFO Channel 02 : 3[400000] -> 2[300000] via P2P/IPC/read
lab:14075:14865 [3] NCCL INFO Connected all trees
lab:14075:14865 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
lab:14075:14865 [3] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
lab:14073:14864 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
lab:14073:14864 [1] NCCL INFO Channel 00 : 1[200000] -> 0[100000] via P2P/IPC/read
lab:14073:14864 [1] NCCL INFO Channel 02 : 1[200000] -> 0[100000] via P2P/IPC/read
lab:14072:14862 [0] NCCL INFO Connected all trees
lab:14072:14862 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
lab:14072:14862 [0] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
lab:14073:14864 [1] NCCL INFO Connected all trees
lab:14073:14864 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
lab:14073:14864 [1] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
lab:14074:14863 [2] NCCL INFO Connected all trees
lab:14074:14863 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/512
lab:14074:14863 [2] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
lab:14074:14863 [2] NCCL INFO comm 0x7f3cbc0090d0 rank 2 nranks 4 cudaDev 2 busId 300000 - Init COMPLETE
lab:14073:14864 [1] NCCL INFO comm 0x7f4e7c0090d0 rank 1 nranks 4 cudaDev 1 busId 200000 - Init COMPLETE
lab:14075:14865 [3] NCCL INFO comm 0x7fec700090d0 rank 3 nranks 4 cudaDev 3 busId 400000 - Init COMPLETE
lab:14072:14862 [0] NCCL INFO comm 0x7f817c0090d0 rank 0 nranks 4 cudaDev 0 busId 100000 - Init COMPLETE
lab:14072:14072 [0] NCCL INFO Launch mode Parallel
[2024-08-29 08:09:53,924] [INFO] [engine.py:278:__init__] DeepSpeed Flops Profiler Enabled: False
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/admin/.cache/torch_extensions/py38_cu115/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.1069345474243164 seconds
[2024-08-29 08:09:54,479] [INFO] [engine.py:1100:_configure_optimizer] Using DeepSpeed Optimizer param name adam as basic optimizer
[2024-08-29 08:09:54,484] [INFO] [engine.py:1108:_configure_optimizer] DeepSpeed Basic Optimizer = FusedAdam
[2024-08-29 08:09:54,485] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed Final Optimizer = adam
[2024-08-29 08:09:54,485] [INFO] [engine.py:795:_configure_lr_scheduler] DeepSpeed using client LR scheduler
[2024-08-29 08:09:54,485] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2024-08-29 08:09:54,485] [INFO] [logging.py:69:log_dist] [Rank 0] step=0, skipped=0, lr=[0.003], mom=[(0.9, 0.999)]
[2024-08-29 08:09:54,485] [INFO] [config.py:1059:print] DeepSpeedEngine configuration:
[2024-08-29 08:09:54,485] [INFO] [config.py:1063:print]   activation_checkpointing_config  {
    "partition_activations": false, 
    "contiguous_memory_optimization": false, 
    "cpu_checkpointing": false, 
    "number_checkpoints": null, 
    "synchronize_checkpoint_boundary": false, 
    "profile": false
}
[2024-08-29 08:09:54,485] [INFO] [config.py:1063:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
[2024-08-29 08:09:54,485] [INFO] [config.py:1063:print]   amp_enabled .................. False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   amp_params ................... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   autotuning_config ............ {
    "enabled": false, 
    "start_step": null, 
    "end_step": null, 
    "metric_path": null, 
    "arg_mappings": null, 
    "metric": "throughput", 
    "model_info": null, 
    "results_dir": null, 
    "exps_dir": null, 
    "overwrite": true, 
    "fast": true, 
    "start_profile_step": 3, 
    "end_profile_step": 5, 
    "tuner_type": "gridsearch", 
    "tuner_early_stopping": 5, 
    "tuner_num_trials": 50, 
    "model_info_path": null, 
    "mp_size": 1, 
    "max_train_batch_size": null, 
    "min_train_batch_size": 1, 
    "max_train_micro_batch_size_per_gpu": 1.024000e+03, 
    "min_train_micro_batch_size_per_gpu": 1, 
    "num_tuning_micro_batch_sizes": 3
}
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   bfloat16_enabled ............. False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   checkpoint_tag_validation_enabled  True
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   checkpoint_tag_validation_fail  False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   communication_data_type ...... None
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   curriculum_enabled ........... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   curriculum_params ............ False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   dataloader_drop_last ......... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   disable_allgather ............ False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   dump_state ................... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   dynamic_loss_scale_args ...... None
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_enabled ........... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_gas_boundary_resolution  1
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_layer_num ......... 0
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_max_iter .......... 100
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_stability ......... 1e-06
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_tol ............... 0.01
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   eigenvalue_verbose ........... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   elasticity_enabled ........... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   flops_profiler_config ........ {
    "enabled": false, 
    "profile_step": 1, 
    "module_depth": -1, 
    "top_modules": 1, 
    "detailed": true, 
    "output_file": null
}
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   fp16_enabled ................. False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   fp16_master_weights_and_gradients  False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   fp16_mixed_quantize .......... False
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   global_rank .................. 0
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   gradient_accumulation_steps .. 1
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   gradient_clipping ............ 1.0
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   gradient_predivide_factor .... 1.0
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   initial_dynamic_scale ........ 4294967296
[2024-08-29 08:09:54,486] [INFO] [config.py:1063:print]   loss_scale ................... 0
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   memory_breakdown ............. False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   optimizer_legacy_fusion ...... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   optimizer_name ............... adam
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   optimizer_params ............. {'lr': 0.003}
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0}
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   pld_enabled .................. False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   pld_params ................... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   prescale_gradients ........... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_change_rate ......... 0.001
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_groups .............. 1
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_offset .............. 1000
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_period .............. 1000
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_rounding ............ 0
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_start_bits .......... 16
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_target_bits ......... 8
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_training_enabled .... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_type ................ 0
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   quantize_verbose ............. False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   scheduler_name ............... None
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   scheduler_params ............. None
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   sparse_attention ............. None
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   sparse_gradients_enabled ..... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   steps_per_print .............. 10
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   tensorboard_enabled .......... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   tensorboard_job_name ......... DeepSpeedJobName
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   tensorboard_output_path ...... 
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   train_batch_size ............. 32
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   train_micro_batch_size_per_gpu  8
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   use_quantizer_kernel ......... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   wall_clock_breakdown ......... False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   world_size ................... 4
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   zero_allow_untested_optimizer  False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   zero_config .................. {
    "stage": 0, 
    "contiguous_gradients": true, 
    "reduce_scatter": true, 
    "reduce_bucket_size": 5.000000e+07, 
    "allgather_partitions": true, 
    "allgather_bucket_size": 5.000000e+07, 
    "overlap_comm": true, 
    "load_from_fp32_weights": true, 
    "elastic_checkpoint": false, 
    "offload_param": null, 
    "offload_optimizer": null, 
    "sub_group_size": 1.000000e+09, 
    "prefetch_bucket_size": 5.000000e+07, 
    "param_persistence_threshold": 1.000000e+05, 
    "max_live_parameters": 1.000000e+09, 
    "max_reuse_distance": 1.000000e+09, 
    "gather_16bit_weights_on_model_save": false, 
    "ignore_unused_parameters": true, 
    "round_robin_gradients": false, 
    "legacy_stage1": false
}
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   zero_enabled ................. False
[2024-08-29 08:09:54,487] [INFO] [config.py:1063:print]   zero_optimization_stage ...... 0
[2024-08-29 08:09:54,487] [INFO] [config.py:1065:print]   json = {
    "train_micro_batch_size_per_gpu": 8, 
    "optimizer": {
        "type": "Adam", 
        "params": {
            "lr": 0.003
        }
    }, 
    "gradient_clipping": 1.0, 
    "zero_optimization": {
        "stage": 0, 
        "allgather_partitions": true, 
        "reduce_scatter": true, 
        "allgather_bucket_size": 5.000000e+07, 
        "reduce_bucket_size": 5.000000e+07, 
        "overlap_comm": true, 
        "contiguous_gradients": true, 
        "cpu_offload": false
    }
}
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Loading extension module fused_adam...
Time to load fused_adam op: 0.10208964347839355 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.10210633277893066 seconds
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Loading extension module fused_adam...
Time to load fused_adam op: 0.10205554962158203 seconds
Using /home/admin/.cache/torch_extensions/py38_cu115 as PyTorch extensions root...
Emitting ninja build file /home/admin/.cache/torch_extensions/py38_cu115/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.09761643409729004 seconds
Loading extension module utils...
Time to load utils op: 0.10141587257385254 seconds
Loading extension module utils...
Time to load utils op: 0.10109829902648926 seconds
Loading extension module utils...
Time to load utils op: 0.10153412818908691 seconds
  0%|                                                 | 0/12500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "minGPT/minGPT/runFirstDeepSpeed.py", line 85, in <module>
    trainer.train()
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 173, in train
    run_epoch(train_loader, is_train=True)
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 132, in run_epoch
    loss = criterion(logits, y)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2945, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
TypeError: cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not tuple
  0%|                                                 | 0/12500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "minGPT/minGPT/runFirstDeepSpeed.py", line 85, in <module>
    trainer.train()
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 173, in train
    run_epoch(train_loader, is_train=True)
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 132, in run_epoch
    loss = criterion(logits, y)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2945, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
TypeError: cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not tuple
  0%|                                                 | 0/12500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "minGPT/minGPT/runFirstDeepSpeed.py", line 85, in <module>
    trainer.train()
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 173, in train
    run_epoch(train_loader, is_train=True)
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 132, in run_epoch
    loss = criterion(logits, y)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2945, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
TypeError: cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not tuple
  0%|                                                 | 0/12500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "minGPT/minGPT/runFirstDeepSpeed.py", line 85, in <module>
    trainer.train()
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 173, in train
    run_epoch(train_loader, is_train=True)
  File "/dli/minGPT/minGPT/mingpt/trainer.py", line 132, in run_epoch
    loss = criterion(logits, y)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2945, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
TypeError: cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not tuple
[2024-08-29 08:09:57,165] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 14072
[2024-08-29 08:09:57,165] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 14073
[2024-08-29 08:09:57,165] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 14074
[2024-08-29 08:09:57,165] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 14075
[2024-08-29 08:09:57,166] [ERROR] [launch.py:184:sigkill_handler] ['/opt/conda/bin/python3.8', '-u', 'minGPT/minGPT/runFirstDeepSpeed.py', '--local_rank=3', '--deepspeed', 'True', '--deepspeed_config', 'minGPT/minGPT/ds_config_basic.json'] exits with return code = 1

**Comment by WJ-Huang** [comment]
> > [@Chtholly1](https://github.com/Chtholly1) 多卡通信的问题，我这边是proxy中localhost的地址访问不到，你可以先用单卡测试，多卡多节点看报错信息，排查网络
> 
> 我单机多卡能跑起来，机器之间也能ping的通，麻烦问下你说的这个方法具体怎么操作呢？
请问你解决了吗？我也有同样的问题

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're [reviewing](https://github.com/NVIDIA/nccl/discussions/1761) older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
