### ISSUE TITLE
Azure MLOps Pipelining -- NCCL WARN [Rem Allocator] Allocation failed & include/alloc.h:48 

### ISSUE THREAD

**Issue by monajalal** [NVIDIA/nccl#844]
I am training DOPE (Deep Object Pose Estimation) from NVIDIA on Azure Cluster. I did made it distributed using PyTorch DistributedDataParallel myself using the script/train.py and going from there. Here's the gist for that and I am not sure if it is fully correct (if I have applied DDP) correctly.

Original train.py code: https://github.com/NVlabs/Deep_Object_Pose/blob/master/scripts/train.py 
DDP version of train.py modified by me: https://gist.github.com/monajalal/5b85c84db7c0f7a0f9250113da994d17

That said, I am using [Azure MLOps Pipeline Templates](https://github.com/Azure/mlops-templates) for this task and  I am using an Azure GPU cluster with 4 nodes and each node with 4 K80 GPUs. Checking the host-tools.log I do see that GPUs do have a lot of memory left while I get the nccl mem alloc failed and while I do get that message, the training keeps moving forward. It is funny that it happens even if I am setting the batch size for each GPU to 1.

I am using the entire FAT dataset from NVIDIA for training here and the object of interest is cracker box.

I cancelled the job but here's the log before I do so:
```
2023/05/16 19:24:26 WARNING mlflow.tracking.fluent: Exception raised while enabling autologging for sklearn: No module named 'sklearn.utils.testing'
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.4<0>
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO P2P plugin IBext
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NCCL_IB_PCI_RELAXED_ORDERING set by environment to 1.
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NET/IB : No device found.
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.4<0>
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda10.2
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_speed, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_width, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_speed, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_width, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_speed, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_width, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_speed, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_width, ignoring
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/000d3a02-42ea-000d-3a02-42ea000d3a02 is not a PCI device (vmbus). Attaching to first CPU
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Attribute coll of node net not found
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO === System : maxWidth 5.0 totalWidth 12.0 ===
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO CPU/0 (1/1/1)
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO + PCI[5000.0] - NIC/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO                 + NET[5.0] - NET/0 (0/0/5.000000)
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO + PCI[12.0] - GPU/100000 (0)
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO + PCI[12.0] - GPU/200000 (1)
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO + PCI[12.0] - GPU/300000 (2)
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO + PCI[12.0] - GPU/400000 (3)
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO ==========================================
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO GPU/200000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (0/5000.000000/LOC) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO GPU/300000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (0/5000.000000/LOC) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO GPU/400000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (0/5000.000000/LOC) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB) 
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO NET/0 :GPU/100000 (3/5.000000/PHB) GPU/200000 (3/5.000000/PHB) GPU/300000 (3/5.000000/PHB) GPU/400000 (3/5.000000/PHB) CPU/0 (2/5.000000/PHB) NET/0 (0/5000.000000/LOC) 
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 5.000000/5.000000, type PHB/PHB, sameChannels 1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Pattern 1, crossNic 0, nChannels 1, speed 6.000000/5.000000, type PHB/PHB, sameChannels 1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO  0 : NET/0 GPU/0 GPU/1 GPU/2 GPU/3 NET/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type NVL/PIX, sameChannels 1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Tree 0 : -1 -> 0 -> 1/8/-1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Tree 1 : 4 -> 0 -> 1/-1/-1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 00/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 01/02 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Ring 00 : 15 -> 0 -> 1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Ring 01 : 15 -> 0 -> 1
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Trees [0] 1/8/-1->0->-1 [1] 1/-1/-1->0->4
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Setting affinity for GPU 0 to 0fff
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 00 : 15[400000] -> 0[100000] [receive] via NET/Socket/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 01 : 15[400000] -> 0[100000] [receive] via NET/Socket/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 00 : 0[100000] -> 1[200000] via direct shared memory
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 01 : 0[100000] -> 1[200000] via direct shared memory
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Connected all rings
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 01 : 0[100000] -> 4[100000] [send] via NET/Socket/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 00 : 8[100000] -> 0[100000] [receive] via NET/Socket/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 00 : 0[100000] -> 8[100000] [send] via NET/Socket/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Channel 01 : 4[100000] -> 0[100000] [receive] via NET/Socket/0
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO Connected all trees
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 8/8/512
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
696b7901f9044f23b786795c0ef7257b000000:39:293 [0] NCCL INFO comm 0x14fc50001240 rank 0 nranks 16 cudaDev 0 busId 100000 - Init COMPLETE
696b7901f9044f23b786795c0ef7257b000000:39:39 [0] NCCL INFO Launch mode Parallel
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth
CPython
3.8.13
uname_result(system='Linux', node='696b7901f9044f23b786795c0ef7257b000000', release='5.15.0-1029-azure', version='#36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022', machine='x86_64', processor='x86_64')
training script path:  /mnt/azureml/cr/j/29c1643998874ef7b6bfd57858b8c0ea/exe/wd
start: 19:24:26.818894
manual seed set to 4646
opt.checkpoints = /mnt/azureml/cr/j/29c1643998874ef7b6bfd57858b8c0ea/cap/data-capability/wd/checkpoints
world size is:  16
global rank is 0 and local_rank is 0
is_distributed is True and batch_size is 1
os.getpid() is 39 and initializing process group with {'MASTER_ADDR': '10.0.0.4', 'MASTER_PORT': '6105', 'LOCAL_RANK': '0', 'RANK': '0', 'WORLD_SIZE': '16'}
device is cuda:0
MLflow version: 1.25.1
Tracking URI: azureml:URI
Artifact URI: azureml:URI
load data
train data size:  246000
training data len:  246000
batch size is:  1
training data: 15375 batches
load models
torch.cuda.device_count():  4
type opt.gpuids: <class 'list'>
gpuids are: [0, 1, 2, 3]
Training network pretrained on imagenet.

  0%|          | 0.00/548M [00:00<?, ?B/s]
  
100%|██████████| 548M/548M [00:02<00:00, 259MB/s]

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/socket.h:423 NCCL WARN Net : Connection closed by remote peer 10.0.0.4<52638>
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO include/socket.h:445 -> 2
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO include/socket.h:457 -> 2
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:229 -> 2

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)



696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)
Train Epoch: 1 [0/246000 (0%)]	Loss: 0.036680415272713
epoch is: 1 and train loss is 0.03668041527271271
...
epoch is: 1 and train loss is 3.1753609164297814e-06
Train Epoch: 1 [2700/246000 (18%)]	Loss: 0.000002425569619
epoch is: 1 and train loss is 2.4255696189356968e-06
...
epoch is: 3 and train loss is 1.1219314899335586e-07
Train Epoch: 3 [5800/246000 (38%)]	Loss: 0.006392419338226

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/socket.h:423 NCCL WARN Net : Connection closed by remote peer 10.0.0.4<44028>
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO include/socket.h:445 -> 2
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO include/socket.h:457 -> 2
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:229 -> 2

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] include/alloc.h:48 NCCL WARN Cuda failure 'out of memory'
696b7901f9044f23b786795c0ef7257b000000:39:298 [0] NCCL INFO bootstrap.cc:231 -> 1

696b7901f9044f23b786795c0ef7257b000000:39:298 [0] bootstrap.cc:279 NCCL WARN [Rem Allocator] Allocation failed (segment 0, fd 130)
epoch is: 3 and train loss is 0.006392419338226318
Train Epoch: 3 [5900/246000 (38%)]	Loss: 0.000000082420129
...
epoch is: 3 and train loss is 1.4848103546682978e-07
Train Epoch: 3 [13100/246000 (85%)]	Loss: 0.000000773773365
```

Here's my `Dockerfile`:

```
# check release notes https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
FROM nvcr.io/nvidia/pytorch:22.04-py3

##############################################################################
# NCCL TESTS
##############################################################################
ENV NCCL_TESTS_TAG=v2.11.0

# NOTE: adding gencodes to support K80, M60, V100, A100
RUN mkdir /tmp/nccltests && \
    cd /tmp/nccltests && \
    git clone -b ${NCCL_TESTS_TAG} https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    make \
    MPI=1 MPI_HOME=/opt/hpcx/ompi \
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \
    CUDA_HOME=/usr/local/cuda && \
    cp ./build/* /usr/local/bin && \
    rm -rf /tmp/nccltests

# Install dependencies missing in this container
# NOTE: container already has matplotlib==3.5.1 tqdm==4.62.0
COPY requirements.txt ./
RUN pip install -r requirements.txt

# RUN python -m pip install   azureml-defaults==1.41.0 \
#     mlflow==1.25.1 \
#     azureml-mlflow==1.41.0 \
#     transformers==4.18.0 \
#     psutil==5.9.0

# add ndv4-topo.xml
RUN mkdir /opt/microsoft/
ADD ./ndv4-topo.xml /opt/microsoft

# to use on A100, enable env var below in your job
# ENV NCCL_TOPO_FILE="/opt/microsoft/ndv4-topo.xml"

# adjusts the level of info from NCCL tests
ENV NCCL_DEBUG="INFO"
ENV NCCL_DEBUG_SUBSYS="GRAPH,INIT,ENV"

# Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
ENV NCCL_IB_PCI_RELAXED_ORDERING="1"
ENV CUDA_DEVICE_ORDER="PCI_BUS_ID"
ENV NCCL_SOCKET_IFNAME="eth0"
```

and here's my `requirements.txt` that I am using for Azure MLOps Pipeline Templates:
```
albumentations==1.3.0
ConfigParser==5.3.0
horovod==0.27.0
matplotlib==3.7.0
numpy==1.24.2
nvisii==1.1.72
Pillow==9.4.0
profiling==0.1.3
psutil==5.9.0
pyquaternion==0.9.9
pyrealsense2==2.53.1.4623
pyrender==0.1.45
pyrr==0.10.3
PyYAML==6.0
scipy==1.10.1
seaborn==0.12.2
simplejson==3.18.4
tensorboardX==2.6
torchvision==0.12.0
torch==1.11.0
tqdm==4.64.1
opencv-python-headless==4.1.2.30
transformers==4.18.0
mlflow==1.25.1
azureml-mlflow==1.41.0
```

**Comment by sjeaugey** [comment]
I'm not sure what other versions are available, but we're currently at NCCL 2.18. It's is fairly recent so I'm not sure it would be available, but 2.17.1 or 2.16.5 could be good versions to try.

I don't know how the workspace is setup and whether eth0 is accessible from the outside. But if it is, it should not be used for NCCL, as NCCL opens ports for inter-rank communication which are not secured. Most of the time when we see this kind of errors, it's due to services trying to open ports on all servers they can access and finding that NCCL open port and making that service fail. It should not break the application though, just generate WARNs.

Now if you think this is likely not the case, it could simply be that those calls are made by NCCL for a good reason, and you're just running out of memory. You may try setting `NCCL_P2P_PXN_LEVEL=0` to avoid those specific memory allocations; performance of small size alltoall operations might be affected negatively though (if that matters to your use case).

If you're still getting an out of memory issue after disabling PXN for P2P, then it could be that your application is not keeping enough memory for NCCL to operate. There might be a way to tell your application to use less memory or give more space for libraries. Recent versions of NCCL may also allocate all that memory during init (instead of during the first send/receive operation) which may work better with the framework. Which is another reason to try a newer version.

**Comment by monajalal** [comment]
@sjeaugey thanks a lot for your followup response.

Do I only need to change the NCCL version in the `train-env.yaml` below or do I need to change other things as well? For example, do I need to change the python, pytorch, rdma_core, cuda, nsight_compute, nsight_systems, or nccl_test as well below? Is there a comptability matrix I could follow? Let's say I want to use nccl 2.17.1.

```
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: nvidia_pytorch
build:
  path: ../../../data-science/environment/
tags:
  os: ubuntu
  os_version: 20.04
  hpcx: 2.10
  mpi: openmpi
  mpi_version: 4.1.2rc4
  ucx: 1.12.0
  cuda: 11.6.2
  cudnn: 8.4.0.27
  nccl: 2.12.10
  rdma_core: 36.0
  nsight_compute: 2022.1.1.2
  nsight_systems: "2022.2.1.31-5fe97ab"
  nccl_test: 2.11.0
  # azureml-defaults: 1.41.0
  # mlflow: 1.25.1
  azureml-defaults: 1.50.0
  mlflow: 2.3.2
  transformers: 4.18.0
```

**Comment by sjeaugey** [comment]
I haven't tried any of that myself. All I can say is that NCCL is backwards compatible so if you can replace NCCL by a newer version it should work.

If that's problematic, at least you can try running with `NCCL_P2P_PXN_LEVEL=0`. Maybe it will solve the problem.

**Comment by monajalal** [comment]
@sjeaugey Hi Sylvain, you are correct. I just changed the NCCL version to 2.17.1 and it worked. However, I am getting a network error. Is this also related to NCCL? I am using env:// for dist_url

```
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO Bootstrap : Using eth0:10.0.0.5<0>
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO P2P plugin IBext
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NCCL_IB_PCI_RELAXED_ORDERING set by environment to 1.
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NET/IB : No device found.
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.5<0>
5225797bbbfa41b58e9cac81360abc94000001:47:47 [3] NCCL INFO Using network Socket
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_speed, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0001-0000-3130-444531303244/pci0001:00/0001:00:00.0/../max_link_width, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_speed, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0002-0000-3130-444531303244/pci0002:00/0002:00:00.0/../max_link_width, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_speed, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0003-0000-3130-444531303244/pci0003:00/0003:00:00.0/../max_link_width, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_speed, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection : could not read /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/47505500-0004-0000-3130-444531303244/pci0004:00/0004:00:00.0/../max_link_width, ignoring
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Topology detection: network path /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/6045bd7e-4468-6045-bd7e-44686045bd7e is not a PCI device (vmbus). Attaching to first CPU
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO KV Convert to int : could not find value of '' in dictionary, falling back to 60
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Attribute coll of node net not found
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO === System : maxWidth 5.0 totalWidth 12.0 ===
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO CPU/0 (1/1/1)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO + PCI[5000.0] - NIC/0
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO                 + NET[5.0] - NET/0 (0/0/5.000000)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO + PCI[12.0] - GPU/100000 (4)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO + PCI[12.0] - GPU/200000 (5)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO + PCI[12.0] - GPU/300000 (6)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO + PCI[12.0] - GPU/400000 (7)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO ==========================================
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO GPU/100000 :GPU/100000 (0/5000.000000/LOC) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO GPU/200000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (0/5000.000000/LOC) GPU/300000 (2/12.000000/PHB) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO GPU/300000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (0/5000.000000/LOC) GPU/400000 (2/12.000000/PHB) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO GPU/400000 :GPU/100000 (2/12.000000/PHB) GPU/200000 (2/12.000000/PHB) GPU/300000 (2/12.000000/PHB) GPU/400000 (0/5000.000000/LOC) CPU/0 (1/12.000000/PHB) NET/0 (3/5.000000/PHB)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO NET/0 :GPU/100000 (3/5.000000/PHB) GPU/200000 (3/5.000000/PHB) GPU/300000 (3/5.000000/PHB) GPU/400000 (3/5.000000/PHB) CPU/0 (2/5.000000/PHB) NET/0 (0/5000.000000/LOC)
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Pattern 4, crossNic 0, nChannels 1, speed 5.000000/5.000000, type PHB/PHB, sameChannels 1
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO  0 : NET/0 GPU/4 GPU/5 GPU/6 GPU/7 NET/0
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Pattern 1, crossNic 0, nChannels 1, speed 6.000000/5.000000, type PHB/PHB, sameChannels 1
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO  0 : NET/0 GPU/4 GPU/5 GPU/6 GPU/7 NET/0
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Pattern 3, crossNic 0, nChannels 0, speed 0.000000/0.000000, type NVL/PIX, sameChannels 1
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Ring 00 : 6 -> 7 -> 8
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Ring 01 : 6 -> 7 -> 8
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Trees [0] -1/-1/-1->7->6 [1] -1/-1/-1->7->6
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Setting affinity for GPU 3 to 0fff
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Channel 00 : 7[400000] -> 8[100000] [send] via NET/Socket/0
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Channel 01 : 7[400000] -> 8[100000] [send] via NET/Socket/0
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Connected all rings
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Channel 00 : 7[400000] -> 6[300000] via direct shared memory
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Channel 01 : 7[400000] -> 6[300000] via direct shared memory
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO Connected all trees
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO threadThresholds 8/8/64 | 128/8/64 | 8/8/512
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO 2 coll channels, 2 p2p channels, 1 p2p channels per peer
5225797bbbfa41b58e9cac81360abc94000001:47:213 [3] NCCL INFO comm 0x14ec70001240 rank 7 nranks 16 cudaDev 3 busId 400000 - Init COMPLETE
NCCL version is:  (2, 10, 3)
MLflow version: 2.3.2
Tracking URI: azureml:URI
Artifact URI: azureml:URI
World size: 16
local rank is 3 and world rank is 7
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data_7/cifar-10-python.tar.gz
Failed download. Trying https -> http instead. Downloading http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data_7/cifar-10-python.tar.gz

  0%|          | 0/170498071 [00:00<?, ?it/s]
  0%|          | 509952/170498071 [00:00<00:34, 4973408.07it/s]
  3%|▎         | 5369856/170498071 [00:00<00:05, 30292895.97it/s]
  6%|▌         | 10510336/170498071 [00:00<00:04, 39722223.67it/s]
  9%|▉         | 15607808/170498071 [00:00<00:03, 44134683.65it/s]
 12%|█▏        | 20916224/170498071 [00:00<00:03, 47346544.93it/s]
 15%|█▌        | 25932800/170498071 [00:00<00:02, 48219144.33it/s]
 18%|█▊        | 31144960/170498071 [00:00<00:02, 49478225.78it/s]
 21%|██        | 36150272/170498071 [00:00<00:02, 49594746.51it/s]
 24%|██▍       | 41290752/170498071 [00:00<00:02, 50114658.72it/s]
 27%|██▋       | 46394368/170498071 [00:01<00:02, 50398280.09it/s]
 30%|███       | 51577856/170498071 [00:01<00:02, 50816752.04it/s]
 33%|███▎      | 56827904/170498071 [00:01<00:02, 51320451.98it/s]
 36%|███▋      | 61961216/170498071 [00:01<00:02, 50976453.02it/s]
 39%|███▉      | 67060736/170498071 [00:01<00:02, 50287582.50it/s]
 42%|████▏     | 72092672/170498071 [00:01<00:01, 50109766.08it/s]
 45%|████▌     | 77106176/170498071 [00:01<00:01, 49095767.34it/s]
 48%|████▊     | 82021376/170498071 [00:01<00:01, 48671364.32it/s]
 51%|█████     | 86892544/170498071 [00:01<00:01, 47545196.01it/s]
 54%|█████▍    | 91653120/170498071 [00:01<00:01, 47161788.29it/s]
 57%|█████▋    | 96468992/170498071 [00:02<00:01, 47452315.59it/s]
 59%|█████▉    | 101244928/170498071 [00:02<00:01, 47427661.77it/s]
 62%|██████▏   | 105990144/170498071 [00:02<00:01, 47410171.20it/s]
 65%|██████▍   | 110733312/170498071 [00:02<00:01, 46584731.58it/s]
 68%|██████▊   | 115395584/170498071 [00:02<00:01, 44587269.02it/s]
 70%|███████   | 119872512/170498071 [00:02<00:01, 43861346.97it/s]
 73%|███████▎  | 124271616/170498071 [00:02<00:01, 42668794.97it/s]
 75%|███████▌  | 128549888/170498071 [00:02<00:00, 42252685.08it/s]
 80%|███████▉  | 135838720/170498071 [00:02<00:00, 51047603.65it/s]
 85%|████████▍ | 144263168/170498071 [00:02<00:00, 60702249.91it/s]
 90%|████████▉ | 152733696/170498071 [00:03<00:00, 67747468.16it/s]
 94%|█████████▍| 161063936/170498071 [00:03<00:00, 72342864.86it/s]
 99%|█████████▉| 169494528/170498071 [00:03<00:00, 75891572.88it/s]
170499072it [00:03, 51834695.76it/s]                              
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
Extracting ./data_7/cifar-10-python.tar.gz to ./data_7
Files already downloaded and verified
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/opt/conda/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/conda/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 93, in <module>
    model = torchvision.models.resnet50(pretrained=True)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 331, in resnet50
    return _resnet("resnet50", Bottleneck, [3, 4, 6, 3], pretrained, progress, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/models/resnet.py", line 296, in _resnet
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress)
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

```

**Comment by sjeaugey** [comment]
That doesn't seem related to NCCL; looks like a network issue?

**Comment by monajalal** [comment]
a friend told me it could be because I have set dist_url for init_process_group to env:// but I used that based off pytorch doc for DDP. He said I may have to use file_based URI instead. I am also using eth0 I am not sure.

This is my Dockerfile. Is eth0 wrong for `NCCL_SOCKET_IFNAME`? I am not sure how I should figure the right value for my cluster.

```
# check release notes https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/index.html
FROM nvcr.io/nvidia/pytorch:22.04-py3

##############################################################################
# NCCL TESTS
##############################################################################
ENV NCCL_TESTS_TAG=v2.11.0

# NOTE: adding gencodes to support K80, M60, V100, A100
RUN mkdir /tmp/nccltests && \
    cd /tmp/nccltests && \
    git clone -b ${NCCL_TESTS_TAG} https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    make \
    MPI=1 MPI_HOME=/opt/hpcx/ompi \
    NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" \
    CUDA_HOME=/usr/local/cuda && \
    cp ./build/* /usr/local/bin && \
    rm -rf /tmp/nccltests

# Install dependencies missing in this container
# NOTE: container already has matplotlib==3.5.1 tqdm==4.62.0
COPY requirements.txt ./
RUN pip install -r requirements.txt


# add ndv4-topo.xml
RUN mkdir /opt/microsoft/
ADD ./ndv4-topo.xml /opt/microsoft

# to use on A100, enable env var below in your job
# ENV NCCL_TOPO_FILE="/opt/microsoft/ndv4-topo.xml"

# adjusts the level of info from NCCL tests
ENV NCCL_DEBUG="INFO"
ENV NCCL_DEBUG_SUBSYS="GRAPH,INIT,ENV"

# Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
ENV NCCL_IB_PCI_RELAXED_ORDERING="1"
ENV CUDA_DEVICE_ORDER="PCI_BUS_ID"
ENV NCCL_SOCKET_IFNAME="eth0"
ENV NCCL_P2P_PXN_LEVEL="0"
# ENV NCCL_SOCKET_IFNAME='lo'
ENV NCCL_IB_DISABLE="1"
```

I also have this in my `pipeline.yaml` file:

```
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# # <inputs_and_outputs>
# inputs:
#   training_images:
#     type: uri_folder
#     mode: download # pick ro_mount, rw_mount or download
#     path: azureml://datastores/workspaceblobstore/paths/azureml-vision-datasets/dogs/**
#     # path: azureml://datastores/workspaceblobstore/paths/azureml-vision-datasets/places2/train//**
#   validation_images: #TODO: Use different datasets for validation
#     type: uri_folder
#     mode: download # pick ro_mount, rw_mount or download
#     path: azureml://datastores/workspaceblobstore/paths/azureml-vision-datasets/dogs/**
#     # path: azureml://datastores/workspaceblobstore/paths/azureml-vision-datasets/places2/valid/**
# # </inputs_and_outputs>

outputs:
  checkpoints:
    type: uri_folder
    mode: upload
    path: azureml:cifar10_resnet50_model:1
    

# <jobs>
settings:
  # default_datastore: azureml:workspaceblobstore
  default_datastore: azureml:arddatalake
  continue_on_step_failure: true

jobs:
  train:
    type: command
    component: file:train.yaml
    compute: azureml:multinode-multigpu16
    resources:
      instance_count: 4 #number of nodes
    distribution:
      type: pytorch
      process_count_per_instance: 4 #number of GPUs per instance

    # NOTE: set env var if needed
    environment_variables:
      NCCL_DEBUG: "INFO" # adjusts the level of info from NCCL tests

      # NCCL_TOPO_FILE: "/opt/microsoft/ndv4-topo.xml" # Use specific topology file for A100

      # NCCL_IB_PCI_RELAXED_ORDERING: "1" # Relaxed Ordering can greatly help the performance of Infiniband networks in virtualized environments.
      NCCL_IB_DISABLE: "1" # force disable infiniband (if set to "1")
      # NCCL_NET_PLUGIN: "none" # to force NET/Plugin off (no rdma/sharp plugin at all)
      # NCCL_NET: "Socket" # to force node-to-node comm to use Socket (slow)
      NCCL_SOCKET_IFNAME: "eth0" # to force Socket comm to use eth0 (use NCCL_NET=Socket)
      # NCCL_SOCKET_IFNAME: "lo"

      # UCX_IB_PCI_RELAXED_ORDERING: "on"
      # UCX_TLS: "tcp"
      # UCX_NET_DEVICES: "eth0" # if you have Error: Failed to resolve UCX endpoint...
      NCCL_P2P_PXN_LEVEL: "0"

      CUDA_DEVICE_ORDER: "PCI_BUS_ID" # ordering of gpus  # do we need to uncomment this? why?

      TORCH_DISTRIBUTED_DEBUG: "DETAIL"

# </jobs>

```

**Comment by sjeaugey** [comment]
The IP interfaces can be listed using `ifconfig` or `ip -4 addr show scope global` (remove -4 if it returns nothing).

**Comment by monajalal** [comment]
@sjeaugey Sylvain, here's what I see, so was eth0 correct based on that? Not sure then why I get network error in multinode multiGPU setting with DDP when backend is NCCL

```
azureuser@NUMBER:~$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet NUMBER  netmask NUMBER  broadcast NUMBER
        ether 02:42:34:49:0b:f1  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet NUMBER  netmask NUMBER  broadcast NUMBER
        NUMBER  prefixlen 64  scopeid 0x20<link>
        ether NUMBER  txqueuelen 1000  (Ethernet)
        RX packets 6663965  bytes 9332760626 (9.3 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 131910  bytes 13157125 (13.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet NUMBER  netmask NUMBER
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 3509  bytes 671319 (671.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3509  bytes 671319 (671.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

azureuser@NUMBER:~$ ip -4 addr show scope global
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet NUMBER/19 brd NUMBER scope global eth0
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    inet NUMBER/16 brd NUMBER scope global docker0
       valid_lft forever preferred_lft forever

```

**Comment by sjeaugey** [comment]
Looks like this version of PyTorch is linked statically with NCCL 2.10.3. No matter what NCCL version you install, it will use the one it embeds.

How does it work with 2.10.3?  I don't see any error?

**Comment by AddyLaddy** [comment]
I don't see how that is a NCCL issue. Your PyT is probably built against a static version of libnccl.
I'm not a PyT expert but the forums suggest you need to rebuild it with:
```
export USE_SYSTEM_NCCL=1
```

Or find a container built with a newer version of NCCL

**Comment by monajalal** [comment]
@AddyLaddy Thanks for having a look. Why do you say this is not an NCCL error? It shows NCCL here:

```
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    model = nn.parallel.DistributedDataParallel(model, device_ids=[local_rank], output_device=local_rank)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 655, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/utils.py", line 112, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: Rank 10 successfully reached monitoredBarrier, but received errors while waiting for send/recv from rank 0. Please check rank 0 logs for faulty rank.
 Original exception: 
[../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:133] Timed out waiting 1800000ms for send operation to complete
34d0f284fac94434817d429e96547367000003:44:220 [2] NCCL INFO [Service thread] Connection closed by localRank 2
34d0f284fac94434817d429e96547367000003:44:44 [2] NCCL INFO comm 0x2c1e8620 rank 10 nranks 16 cudaDev 2 busId 300000 - Abort COMPLETE
```
I will also post it on PyTorch forum.

Could you kindly please tell me which NVIDIA PyTorch container has NCCL 2.17.1+?

Here's a list I have.

I was not able to use `#FROM nvcr.io/nvidia/pytorch:23.02-py3`
Because it requires GPUs with compute capability of 5+ and my cluster contains 4 nodes each with 4 K80 GPUs (CC=3.7)

Currently I am using this one `FROM nvcr.io/nvidia/pytorch:22.12-py3`

**Comment by AddyLaddy** [comment]
Ok it's likely that there isn't a K80 version with the latest NCCL library as CUDA has now dropped support for the Kepler architecture. The NCCL releases are only built and tested against the supported CUDA architectures at that time.
Why do you need the latest version of NCCL? Is there some issue with the version inside a container that still supports K80?

**Comment by monajalal** [comment]
@AddyLaddy I moved on using a cluster of two nodes each having 2 V100 and problem is gone. I also moved from US East 2 to US East.
