### ISSUE TITLE
Hang in ncclCommAbort after I upgrade NCCL to 2.16.5.

### ISSUE THREAD

**Issue by zpcalan** [NVIDIA/nccl#863]
Hi, developers of NCCL.
Lately I just upgraded my NCCL version to 2.16.5, and when I run my test case of process exiting, `ncclCommAbort` hangs.
But NCCL-2.7.6 does not have this issue. Any known issue about this?
Sorry that I have not printed the stack, I will upload it later.

**Comment by zpcalan** [comment]
The stack is shown below:
```
#0  0x00007fc349513d2d in __GI___pthread_timedjoin_ex (threadid=140471077381888, thread_return=0x0, abstime=0x0, block=<optimized out>) at pthread_join_common.c:89
#1  0x00007fc204d33e27 in commReclaim(ncclComm*) () from XXX
#2  0x00007fc204d345fd in ncclCommAbort () from XXX
```

**Comment by zpcalan** [comment]
Hi~
Any progress on this issue?

**Comment by awgu** [comment]
@zpcalan did you find any workaround?

**Comment by sjeaugey** [comment]
Sorry for not responding earlier. Recent versions of NCCL may need more inter-rank synchronization, even in the case of abort, to properly free resources.

Therefore within a node, you need all ranks to abort or we could free CUDA memory when other ranks are still using it, causing them to crash with illegal memory access, which could cause other issues to manage the recovery.

It would be good to confirm that this is what's happening here, where you're aborting only one rank and not others?

**Comment by zpcalan** [comment]
> Sorry for not responding earlier. Recent versions of NCCL may need more inter-rank synchronization, even in the case of abort, to properly free resources.
> 
> Therefore within a node, you need all ranks to abort or we could free CUDA memory when other ranks are still using it, causing them to crash with illegal memory access, which could cause other issues to manage the recovery.
> 
> It would be good to confirm that this is what's happening here, where you're aborting only one rank and not others?

I spawned n processes and one of them was killed during the training job. Then other n-1 processes would call `ncclCommAbort`.
So I can't `abort` all processes.

**Comment by sjeaugey** [comment]
That should be ok. If one process is destroyed, it will close all its connections and abort should be able to complete.

**Comment by zpcalan** [comment]
> The stack isn't telling me much. I'd need all threads (in gdb, run `thread apply all bt`); all I can see here is that we're indeed stuck in ncclCommAbort waiting for the proxy to complete.

Thank you~
I reproduce this issue and print stacks of threads that's relevant to NCCL:
```
Thread 9 (Thread 0x7eff9d7fe700 (LWP 52930)):
#0  0x00007f00fb086ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7effb063b158) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7effb063b108, cond=0x7effb063b130) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7effb063b130, mutex=0x7effb063b108) at pthread_cond_wait.c:655
#3  0x00007effb8c63435 in ncclProxyProgress(void*) () from XXX
#4  0x00007f00fb0806db in start_thread (arg=0x7eff9d7fe700) at pthread_create.c:463
#5  0x00007f00fada961f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7eff9dfff700 (LWP 52917)):
#0  0x00007f00fad9cbb9 in __GI___poll (fds=0x7eff9dffcab0, nfds=65, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007effb8c638e4 in ncclProxyService(void*) () from XXX
#2  0x00007f00fb0806db in start_thread (arg=0x7eff9dfff700) at pthread_create.c:463
#3  0x00007f00fada961f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7effb1ded700 (LWP 52909)):
#0  0x00007f00fb08a474 in __libc_read (fd=83, buf=buf@entry=0x7effb1dece70, nbytes=nbytes@entry=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007effd452245f in read (__nbytes=16, __buf=0x7effb1dece70, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#2  __ibv_get_async_event_1_1 (context=0x7eff240172c0, event=0x7effb1deced0) at ./libibverbs/device.c:459
#3  0x00007effb8c6a465 in wrap_ibv_get_async_event(ibv_context*, ibv_async_event*) () from XXX
#4  0x00007effb8c7e4d7 in ncclIbAsyncThreadMain(void*) () from XXX
#5  0x00007f00fb0806db in start_thread (arg=0x7effb1ded700) at pthread_create.c:463
#6  0x00007f00fada961f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
...
...
...
...
...
Thread 1 (Thread 0x7f00fb4a8740 (LWP 52538)):
#0  0x00007f00fb081d2d in __GI___pthread_timedjoin_ex (threadid=139636332558080, thread_return=0x0, abstime=0x0, block=<optimized out>) at pthread_join_common.c:89
#1  0x00007effb8c48e27 in commReclaim(ncclComm*) () from XXX
#2  0x00007effb8c495fd in ncclCommAbort () from XXX
```

 Hope this will help.

**Comment by sjeaugey** [comment]
Are you sure all other ranks have called ncclCommAbort (or exited)? It looks like the service thread (`ncclProxyService`) is not exiting because there are remaining ranks which still need it. The service thread cannot clean up all its memory and exit, otherwise there could be other ranks in the system using it as intermediate rank, which would be using that memory and would crash if it was destroyed too quickly. So we wait until others call ncclCommAbort as well, before we can free all resources and unblock the main thread.

**Comment by sjeaugey** [comment]
Ok, thanks for confirming. CC @KaimingOuyang.

**Comment by KaimingOuyang** [comment]
I can see the peer socket connections are not fully closed when you call abort.
I remember the same issue happened before. The solution is to add `shutdown` before close the socket. 
Could you please try 2.18.1 and see whether that solves the issue?

**Comment by zpcalan** [comment]
> I can see the peer socket connections are not fully closed when you call abort. I remember the same issue happened before. The solution is to add `shutdown` before close the socket. Could you please try 2.18.1 and see whether that solves the issue?

Thanks! And yes, I tried 2.18.1 and the issue disappeared.
Is this issue only happened in specific cases and is the impact significant? Because I can't reproduce it when I trained other network with relatively small communication traffic.

**Comment by KaimingOuyang** [comment]
This issue happened in Pytorch + NCCL in the first place. It depends on how the upper layer lib manages the process. For example, if there is a process duplication (e.g. fork), it can cause this issue. 

If you don't see the problem on other networks, I believe this issue you reported might also involve another bug that was fixed in v2.18.3. so I suggest you use NCCL version >= v2.18.3.

**Comment by zpcalan** [comment]
I upgrade NCCL to v2.18.3 and the issue disappeared. Thank you!
Issue closed.
