### ISSUE TITLE
run all_reduce_perf in 2machine, why hang at here?

### ISSUE THREAD

**Issue by FarmerLiuAng** [NVIDIA/nccl#876]
Hi, the command I use is `NCCL_DEBUG=INFO mpirun -np 2 -hosts master,worker ./build/all_reduce_perf -b 4M -e 4M -f 2 -g 8`
It works when I run mpi example. So, I think the problem is releted to my operation whith NCCL or nccl-tests.
The program hangs as the image shows below.
![image](https://github.com/NVIDIA/nccl/assets/40845317/423bd563-e3fb-4893-ac31-ee92844843a9)
Could you give  some advise?

**Comment by FarmerLiuAng** [comment]
Thanks for your reply! It works within a single node and it works running cpi example.

**Comment by sjeaugey** [comment]
Ok. I'm surprised it's stuck at that point. It would look like the bootstrap is hanging. Given we're using `bond0` for communication, could it be that interface doesn't work? Or the second node is not picking the same interface?

You should run with `mpirun -x NCCL_DEBUG=INFO` otherwise the environment variable is only active on the local node and we only see half the information we need.

**Comment by FarmerLiuAng** [comment]
I use `cat /proc/net/bonding/bond0` to check bond0, it seems all right.
![image](https://github.com/NVIDIA/nccl/assets/40845317/f5e67f42-a109-47f4-ba83-db363ae6f10a)

I use mpich but not openmpi. I tried to use "export NCCL_DEBUG=INFO" , use "-env" option and modify bashrc, but it just showed the local information. I don't know why the environment variable not work.

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're [reviewing](https://github.com/NVIDIA/nccl/discussions/1761) older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.
