### ISSUE TITLE
NCCL under docker in WSL - unable to connect machines under PyTorch

### ISSUE THREAD

**Issue by MartinPerry** [NVIDIA/nccl#929]
I have two windows machines on a company network. I have installed wsl2 (Ubuntu) and Nvidia pytorch docker image inside.

I run docker with:

`docker run --gpus all -p 1777:1777 -p 1778:1778 --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -it -v/mnt/d:/mnt nvcr.io/nvidia/pytorch:23.06-py3`

I run `torchrun` with this command:

master (a.b.d.d0) `torchrun --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr=a.b.c.d0 --master_port=1777 resnet.py`
slave (a.b.c.d1) `torchrun --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr=a.b.c.d0 --master_port=1777 resnet.py`

`a.b.c.d0` and `a.b.c.d1` are public IP4 addresses within my company network, both accessible from internet.  They are not `192.168.x.y` or `10.0.0.y`.

However, when I run this, I got NCCL error on slave:

`e57377aacbb6:1203:1227 [0] misc/socket.cc:480 NCCL WARN socketStartConnect: Connect to 172.17.0.2<38847> failed : Software caused connection abort`

I have tried to specify on both machines
`export NCCL_COMM_ID=a.b.c.d0:1778`

but after that I got on master:

```
d9beab19e6d2:1791:1791 [0] misc/socket.cc:237 NCCL WARN Net : No interface found in the same subnet as remote address a.b.c.d0<1778>
d9beab19e6d2:1791:1791 [0] bootstrap.cc:39 NCCL WARN NET/Socket : No usable listening interface found
```
and on slave:

```
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue.
```

I have tried on a.b.c.d0

`nc -l 1778`

and on a.b.c.d1

`nc a.b.c.d0 1778`

(I have also tried `1777 `port) and both machines communicate, eg. I can see messages being send.

How can I setup NCCL to communicate over network from docker that runs inside wsl2?

NCCL version: 12.1.0.106
NVIDIA Pytroch version: 23.06

**Comment by KaimingOuyang** [comment]
It seems you are not using the correct interface. Could you please set env `NCCL_SOCKET_IFNAME=xxx`? Please change `xxx` to your corresponding interface.

**Comment by MartinPerry** [comment]
The first error:

`e57377aacbb6:1203:1227 [0] misc/socket.cc:480 NCCL WARN socketStartConnect: Connect to 172.17.0.2<38847> failed : Software caused connection abort`

is with default NCCL behaviour. It corresponds to the network name given by `ip a` command. The second available name is a loop-back. `ip a` does not print any other networks within the docker.

**Comment by MartinPerry** [comment]
Inside docker container, I can see this, if I run `ifconfig`:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 23891  bytes 28088948 (28.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12574  bytes 856606 (856.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 14  bytes 824 (824.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 824 (824.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by KaimingOuyang** [comment]
`172.17.0.2` is a private ip right? Are you saying you are using this eth0 and can access/ping the private IP in another container?

**Comment by MartinPerry** [comment]
By default, it uses this incorrect private IP. That is why I have used `export NCCL_COMM_ID=a.b.c.d0:1778` with my public IP of master. However, that complains about incorrect subnet even though both computers are on the same subnet.

**Comment by MartinPerry** [comment]
I have found the issue being in `socket.cc` - `matchSubnet`. It won't go through:

```
if (family == AF_INET) {
    struct sockaddr_in* local_addr = (struct sockaddr_in*)(local_if.ifa_addr);
    struct sockaddr_in* mask = (struct sockaddr_in*)(local_if.ifa_netmask);
    struct sockaddr_in& remote_addr = remote->sin;
    struct in_addr local_subnet, remote_subnet;
    local_subnet.s_addr = local_addr->sin_addr.s_addr & mask->sin_addr.s_addr;
    remote_subnet.s_addr = remote_addr.sin_addr.s_addr & mask->sin_addr.s_addr;
    return (local_subnet.s_addr ^ remote_subnet.s_addr) ? false : true;
  }
```

since I have different IP and thus different subnets. However, this is and issue, since the computers are visible even though they are not in the same subnet. Why is this test needed? This is more of a question for NCCL team. Why isn't there a possibility to disable this test at all (using some variable similar to `NCCL_COMM_ID`), if I know what I am doing?

**Comment by sjeaugey** [comment]
I guess that's a limitation of `NCCL_COMM_ID`, as it determines which interface we'll use. As to how we could make it work, I don't know -- we'd need to spend time on this.

**Comment by pandyamarut** [comment]
I guess, this occurs because, NCCL communicator is using container ip for interface and is not able to accessible. If you start a container in host network mode and set the right : NCCL_SOCKET_IFNAME: it should work.

**Comment by chengchengpei** [comment]
Did you try ```--network host``` when running docker containers?

**Comment by stephenmsachs** [comment]
### Issue Cleanup: Helping Us Focus on Current Challenges

  We're [reviewing](https://github.com/NVIDIA/nccl/discussions/1761) older issues to ensure we prioritize the most relevant and active ones. Since this issue hasn't seen updates in over 6 months, we'll be closing it for now.

  ,*This change helps us focus our efforts on addressing any current issues our users are facing.* If this issue still affects you, please don't hesitate to reopen it with a quick update (e.g., "Still relevant on [version=X]").
  Thanks for your understanding and for contributing to NCCL.

**Comment by haodong2000** [comment]
> It seems you are not using the correct interface. Could you please set env `NCCL_SOCKET_IFNAME=xxx`? Please change `xxx` to your corresponding interface.

Perfectly works for me. Thank you! @KaimingOuyang
