### ISSUE TITLE
NCCL WARN Cuda failure 'invalid device function' and 'invalid device ordinal'

### ISSUE THREAD

**Issue by yjiangling** [NVIDIA/nccl#932]
Environment:

Framework: TensorFlow
Framework version: 2.4.0
Horovod version: 0.25.0
MPI version: 4.0.0
CUDA version: 11.0
NCCL version: 2.8.3
Python version: 3.6
OS and version: Ubuntu 18.04
GCC version: 7.5.0

Hi,
I'm using hovorod and TensorFlow2.4 to conduct parallel training on NVIDIA GeForce GTX 1080 Ti GPUs, I use this commond "
NCCL_DEBUG=WARN mpirun -n 2 python3 train.py", but it give the following error.

```
Prefer tf.tensor_scatter_nd_update, which offers the same functionality with well-defined read-write semantics.
2023-07-28 10:30:12.821361: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2023-07-28 10:30:13.311153: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2023-07-28 10:30:13.333620: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2023-07-28 10:30:13.540791: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2023-07-28 10:30:13.576494: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2023-07-28 10:30:13.751644: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8

administrator:18368:18405 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
**NCCL version 2.8.3+cuda10.0**

administrator:18369:18404 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]

administrator:18368:18405 [0] enqueue.cc:231 NCCL WARN Cuda failure 'invalid device function'

administrator:18369:18404 [1] enqueue.cc:231 NCCL WARN Cuda failure 'invalid device function'
[administrator:18369] *** Process received signal ***
[administrator:18369] Signal: Segmentation fault (11)
[administrator:18369] Signal code: Address not mapped (1)
[administrator:18369] Failing at address: 0xc5

administrator:18369:18404 [1] enqueue.cc:442 NCCL WARN Error : mixing different streams within a group call is not supported.

administrator:18368:18405 [0] enqueue.cc:442 NCCL WARN Error : mixing different streams within a group call is not supported.
[administrator:18368] *** Process received signal ***
[administrator:18368] Signal: Segmentation fault (11)
[administrator:18368] Signal code: Address not mapped (1)
[administrator:18368] Failing at address: 0x35
[administrator:18368] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f2a23f35980]
[administrator:18369] [ 0] [administrator:18368] [ 1] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f3987e37980]
[administrator:18369] [ 1] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(+0x14cf2c)[0x7f29bdb21f2c]
[administrator:18368] [ 2] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(+0x14cf2c)[0x7f3921a23f2c]
[administrator:18369] [ 2] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckESs12ncclResult_tRP8ncclComm+0x50)[0x7f29bdaffbb0]
[administrator:18368] [ 3] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x1e8)[0x7f29bdb014d8]
[administrator:18368] [ 4] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x71)[0x7f29bdabcdc1]
[administrator:18368] [ 5] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common11NCCLContext10ErrorCheckESs12ncclResult_tRP8ncclComm+0x50)[0x7f3921a01bb0]
[administrator:18369] [ 3] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0xf1)[0x7f29bdabd471]
[administrator:18368] [ 6] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZN7horovod6common13NCCLAllreduce7ExecuteERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x1e8)[0x7f3921a034d8]
[administrator:18369] [ 4] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(+0xb29f6)[0x7f29bda879f6]
[administrator:18368] [ 7] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteAllreduceERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseE+0x71)[0x7f39219bedc1]
[administrator:18369] [ 5] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZNK7horovod6common16OperationManager16ExecuteOperationERSt6vectorINS0_16TensorTableEntryESaIS3_EERKNS0_8ResponseERNS0_10ProcessSetE+0xf1)[0x7f39219bf471]
[administrator:18369] [ 6] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so(+0xb29f6)[0x7f39219899f6]
[administrator:18369] [ 7] /home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1832eff)[0x7f29f124ceff]
[administrator:18368] [ 8] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f2a23f2a6db]
[administrator:18368] [ 9] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f2a23c5361f]
[administrator:18368] *** End of error message ***
/home/ASR/.conda/envs/tensorflow2/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x1832eff)[0x7f395514eeff]
[administrator:18369] [ 8] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f3987e2c6db]
[administrator:18369] [ 9] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f3987b5561f]
[administrator:18369] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node administrator exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

I installed nccl2.8.3-1+cuda11.0 with the following cmds:
```
sudo dpkg -i nccl-repo-ubuntu1804-2.8.3-ga-cuda11.0_1-1_amd64.deb
sudo apt update
sudo apt install libnccl2 libnccl-dev
sudo cp /usr/lib/x86_64-linux-gnu/libnccl.so.2 /usr/local/cuda-11.0/lib64
sudo cp /usr/include/nccl.h /usr/local/cuda-11.0/include/

```
And I use command “dpkg -l | grep nccl” can see the libnccl2 and libnccl-dev information.
![1](https://github.com/NVIDIA/nccl/assets/42861880/79d1f848-1e54-44c6-b880-a6679f7264ba)

Or use "sudo apt search nccl" can get this information:
![5](https://github.com/NVIDIA/nccl/assets/42861880/b76bf3cb-2ba6-4f45-bc53-d99e3d6286c6)

And I also tested the nccl with the following steps:

```
1. git clone https://github.com/NVIDIA/nccl-tests.git
2. cd nccl-test
3. make MPI=1 MPI_HOME=/path/to/mpi CUDA_HOME=/path/to/cuda NCCL_HOME=/path/to/nccl
4. ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 6
5. mpirun -np 6 ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1
```

Everything is OK!
![2](https://github.com/NVIDIA/nccl/assets/42861880/8e0fa2da-c460-457c-ae7e-c723a5408980)
![3](https://github.com/NVIDIA/nccl/assets/42861880/657ccdfb-37a7-45aa-8345-29163489b51a)

I also followed the instructions use "/usr/local/cuda-11.0/bin/cuobjdump -arch sm_61 /usr/local/cuda-11.0/lib64/libnccl.so.2 | grep sm_61" to confirm there are sm_61 sections in the NCCL library (the compute capability of NVIDIA GeForce GTX 1080 Ti GPU is 6.1)
![4](https://github.com/NVIDIA/nccl/assets/42861880/b890f9c5-fa9e-467b-8b1e-a3e818367902)

I also reinstalled horovod 0.25.0 with HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/usr/local/cuda-11.0 HOROVOD_NCCL_HOME=/usr/local/cuda-11.0 pip install --no-cache-dir horovod, but it still give the same error. 

What's wrong? I have been confused for quite few days. Anyone can give me some help? Thanks a lot in advance!!! By the way, I installed nccl2.8.3+cuda11.0, but why the NCCL_DEBUG give NCCL version 2.8.3+cuda10.0 info? Although I have CUDA10.0 and CUDA11.0 on my machine, but I did't install this nccl version and can not find nccl in CUDA10.0 dir.

**Comment by sjeaugey** [comment]
Indeed the problem comes from the fact you're not using the NCCL version (with CUDA 11) but another one with CUDA 10 which may not have been compiled with sm60 support.

Maybe your DL framework (or horovod) comes with NCCL statically linked? If you're recompiling it yourself, maybe there is a NCCL library somewhere in `/usr`?

**Comment by yjiangling** [comment]
> Indeed the problem comes from the fact you're not using the NCCL package you installed (with CUDA 11) but another one with CUDA 10 which may not have been compiled with sm60 support.
> 
> Maybe your DL framework (or horovod) comes with NCCL statically linked? If you're recompiling it yourself, maybe there is a NCCL library somewhere in `/usr`?

Thanks a lot for the help, I carefully checked the nccl file with "locate nccl" and delete the old version files, and recompiled the horovod again, it works fine now. Thank U very much again!!!
![捕获](https://github.com/NVIDIA/nccl/assets/42861880/aa873f3d-989d-4a41-a65a-42a83fb26758)
