### ISSUE TITLE
NCCL 2.18.3: Socket recv failed while polling for opId=... / Cuda failure 'invalid argument'

### ISSUE THREAD

**Issue by maxhgerlach** [NVIDIA/nccl#957]
On some nodes of our cluster, I run into NCCL failures when I use a container based on CUDA 12.1 and NCCL 2.18.3. On the same nodes there are no problems if I instead use a container with CUDA 11.8 and NCCL 2.14.3. This is using a codebase derived from [Megatron-LM](https://github.com/NVIDIA/Megatron-LM).

In a failing job on two nodes, using 8 GPUs each, these `NCCL WARN` messages are produced:
```
Fri Aug 11 12:31:45 2023[1,0]<stdout>:tomte401:1850301:1881341 [0] transport.cc:154 NCCL WARN Cuda failure 'invalid argument'
Fri Aug 11 12:31:45 2023[1,0]<stdout>:tomte401:1850301:1881358 [0] proxy.cc:1485 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=3, closing connection
Fri Aug 11 12:31:45 2023[1,0]<stdout>:tomte401:1850301:1881358 [0] proxy.cc:1495 NCCL WARN [Service thread] Could not receive type from localRank 0, res=3, closed=0
Fri Aug 11 12:31:45 2023[1,0]<stdout>:tomte401:1850301:1881358 [0] proxy.cc:1519 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 3

Fri Aug 11 12:31:45 2023[1,3]<stdout>:tomte401:1850304:1881110 [3] transport.cc:154 NCCL WARN Cuda failure 'invalid argument'
Fri Aug 11 12:31:45 2023[1,3]<stdout>:tomte401:1850304:1881128 [3] proxy.cc:1485 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=3, closing connection
Fri Aug 11 12:31:45 2023[1,3]<stdout>:tomte401:1850304:1881128 [3] proxy.cc:1519 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 3

Fri Aug 11 12:31:45 2023[1,6]<stdout>:tomte401:1850309:1881317 [6] transport.cc:154 NCCL WARN Cuda failure 'invalid argument'
Fri Aug 11 12:31:45 2023[1,6]<stdout>:tomte401:1850309:1881330 [6] proxy.cc:1485 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=3, closing connection
Fri Aug 11 12:31:45 2023[1,6]<stdout>:tomte401:1850309:1881330 [6] proxy.cc:1495 NCCL WARN [Service thread] Could not receive type from localRank 0, res=3, closed=0
Fri Aug 11 12:31:45 2023[1,6]<stdout>:tomte401:1850309:1881330 [6] proxy.cc:1519 NCCL WARN [Proxy Service 0] Failed to execute operation Connect from rank 0, retcode 3

Fri Aug 11 12:31:47 2023[1,8]<stdout>:tomte523:1864511:1893770 [0] misc/socket.cc:29 NCCL WARN socketProgressOpt: Call to recv from 10.70.97.27<59218> failed : Connection reset by peer
Fri Aug 11 12:31:47 2023[1,8]<stdout>:tomte523:1864511:1893770 [0] proxy.cc:1485 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=6, closing connection
Fri Aug 11 12:31:47 2023[1,8]<stdout>:tomte523:1864511:1893770 [0] proxy.cc:1519 NCCL WARN [Proxy Service 1] Failed to execute operation Connect from rank 1, retcode 6
Fri Aug 11 12:31:47 2023[1,8]<stdout>:tomte523:1864511:1893757 [0] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer infi-tomte523.fal.linguee.internal<53545>
Fri Aug 11 12:31:47 2023[1,8]<stdout>:tomte523:1864511:1893757 [0] proxy.cc:1143 NCCL WARN Socket recv failed while polling for opId=0x7f221405f810

Fri Aug 11 12:31:46 2023[1,11]<stdout>:tomte523:1864515:1893580 [3] misc/socket.cc:29 NCCL WARN socketProgressOpt: Call to recv from 10.70.97.27<57306> failed : Connection reset by peer
Fri Aug 11 12:31:46 2023[1,11]<stdout>:tomte523:1864515:1893580 [3] proxy.cc:1485 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=6, closing connection
Fri Aug 11 12:31:46 2023[1,11]<stdout>:tomte523:1864515:1893580 [3] proxy.cc:1519 NCCL WARN [Proxy Service 1] Failed to execute operation Connect from rank 1, retcode 6
Fri Aug 11 12:31:46 2023[1,11]<stdout>:tomte523:1864515:1893568 [3] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer infi-tomte523.fal.linguee.internal<53993>
Fri Aug 11 12:31:46 2023[1,11]<stdout>:tomte523:1864515:1893568 [3] proxy.cc:1143 NCCL WARN Socket recv failed while polling for opId=0x7f300c05f6f0

Fri Aug 11 12:31:48 2023[1,14]<stdout>:tomte523:1864519:1893753 [6] misc/socket.cc:29 NCCL WARN socketProgressOpt: Call to recv from 10.70.97.27<48088> failed : Connection reset by peer
Fri Aug 11 12:31:48 2023[1,14]<stdout>:tomte523:1864519:1893753 [6] proxy.cc:1485 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=6, closing connection
Fri Aug 11 12:31:48 2023[1,14]<stdout>:tomte523:1864519:1893753 [6] proxy.cc:1519 NCCL WARN [Proxy Service 1] Failed to execute operation Connect from rank 1, retcode 6
Fri Aug 11 12:31:48 2023[1,14]<stdout>:tomte523:1864519:1893745 [6] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer infi-tomte523.fal.linguee.internal<41671>
Fri Aug 11 12:31:48 2023[1,14]<stdout>:tomte523:1864519:1893745 [6] proxy.cc:1143 NCCL WARN Socket recv failed while polling for opId=0x7f0994043640
```
* Three processes on the first node tomte401 produce `transport.cc:154 NCCL WARN Cuda failure 'invalid argument'`. 
* Three processes on the second node tomte523 produce `misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer infi-tomte523.fal.linguee.internal<...>`. This one sounds a little strange: Apparently it fails to connect to itself (just on the InfiniBand interface, infi-tomte523). Before that there's a message `Call to recv from 10.70.97.27<...> failed : Connection reset by peer`. Here 10.70.97.27 is the IP address of tomte401, the other host.

This isn't specific to the InfiniBand network, though. Experimentally, I've set `NCCL_SOCKET_IFNAME=bond0` (aggregated Ethernet links). Then I still run into the same problem, but the error message is now `NCCL WARN socketProgress: Connection closed by remote peer tomte523.fal.linguee.internal`.

Note that the error messages are fairly similar to some of those seen in https://github.com/NVIDIA/nccl/issues/952, also using NCCL 2.18 in Megatron-LM.

Given that on some other hosts the code works well even with NCCL 2.18, the problem may be specific to the servers or networking. But then, why would it never show with NCCL 2.14?

I've collected quite extensive logs with `NCCL_TOPO_DUMP_FILE=system.xml"`, `NCCL_DEBUG=INFO`, `NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH,TUNING`:

**Failing (NCCL version 2.18.3+cuda12.1)**
* [nccl2.18.3-rank0_NCCL_logs.txt](https://github.com/NVIDIA/nccl/files/12324461/nccl2.18.3-rank0_NCCL_logs.txt)
* [nccl2.18.3-rank8_NCCL_logs.txt](https://github.com/NVIDIA/nccl/files/12324477/nccl2.18.3-rank8_NCCL_logs.txt)
* [nccl2.18.3-system.xml.txt](https://github.com/NVIDIA/nccl/files/12324486/nccl2.18.3-system.xml.txt), showing just 1 GPU (I have this file for only one process)

**OK (NCCL version 2.14.3+cuda11.8)**, same hosts
* [nccl2.14.3-rank0_NCCL_logs.txt](https://github.com/NVIDIA/nccl/files/12324521/nccl2.14.3-rank0_NCCL_logs.txt)
* [nccl2.14.3-rank8_NCCL_logs.txt](https://github.com/NVIDIA/nccl/files/12324531/nccl2.14.3-rank8_NCCL_logs.txt)
* [nccl2.14.3-system.xml.txt](https://github.com/NVIDIA/nccl/files/12324548/nccl2.14.3-system.xml.txt), showing 4 GPUs

Would any other logs be useful to shed more light on this issue?

The nodes have the following topology:
```
$ nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	CPU Affinity	NUMA Affinity
GPU0	 X 	NV4	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	12-15,44-47	3
GPU1	NV4	 X 	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	8-11,40-43	2
GPU2	SYS	SYS	 X 	NV4	SYS	SYS	SYS	SYS	SYS	SYS	4-7,36-39	1
GPU3	SYS	SYS	NV4	 X 	SYS	SYS	SYS	SYS	SYS	SYS	0-3,32-35	0
GPU4	SYS	SYS	SYS	SYS	 X 	NV4	SYS	SYS	SYS	SYS	28-31,60-63	7
GPU5	SYS	SYS	SYS	SYS	NV4	 X 	SYS	SYS	SYS	SYS	24-27,56-59	6
GPU6	SYS	SYS	SYS	SYS	SYS	SYS	 X 	NV4	PHB	PHB	20-23,52-55	5
GPU7	SYS	SYS	SYS	SYS	SYS	SYS	NV4	 X 	SYS	SYS	16-19,48-51	4
NIC0	SYS	SYS	SYS	SYS	SYS	SYS	PHB	SYS	 X 	PIX
NIC1	SYS	SYS	SYS	SYS	SYS	SYS	PHB	SYS	PIX	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
```
I couldn't reproduce any NCCL 2.18.3 problem using nccl-tests, but here's the topo dump from `all_reduce_perf` using 16 GPUs on those two nodes: [nccl2.18.3-all_reduce_perf_system.xml.txt](https://github.com/NVIDIA/nccl/files/12324656/nccl2.18.3-all_reduce_perf_system.xml.txt)

**Comment by sjeaugey** [comment]
It looks like the original error is:
```
transport.cc:154 NCCL WARN Cuda failure 'invalid argument'
```
And the rest is all side effects: the service thread failing, then the main thread failing to connect to the service thread (which is local in most cases except when using PXN).

I'm failing to see why we'd fail there though. Is that error happening on each run or is it intermittent?

**Comment by maxhgerlach** [comment]
In all my subsequent tests, the error was reproducible on every run.

I also tried the following:
* Set `NCCL_IB_DISABLE=1` and run with socket networking only => no difference, error still occuring
* I built and ran [nvbandwidth](https://github.com/NVIDIA/nvbandwidth/) in the CUDA 12.1 / NCCL 2.18 container on the same host => runs through without errors 
  * (That was suggested as a diagnosis in #846, where the `transport.cc:154 NCCL WARN Cuda failure 'invalid argument'` error message was also seen.)

Do you have any suggestion what else we could look into to help understand what's going on here?

**Comment by PhdShi** [comment]
same error occurred when I train Megatorn-LM in NGC container 23.06 on multi H800 GPUs server with the warning `transport/nvls.cc:364 NCCL WARN Cuda failure 'invalid argument'`

**Comment by sjeaugey** [comment]
@PhdShi this is a different issue related to NVLS. Please open a new issue about that, thanks!

@maxhgerlach If you can add some debugging before the code that fails, it could be interesting to print the arguments to cudaMemcpyAsync, to see which argument is wrong (if any is obviously wrong). One thing that changed between 2.14 and 2.18 is the resource sharing code for ncclCommSplit. So instead of calling:
```
CUDACHECKGOTO(cudaMemcpyAsync(comm->channels[c].devPeers[sendPeer].send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
```
we now retrieve the address of `comm->channels[c].devPeers[sendPeer]` first, then perform the copy:
```
                CUDACHECKGOTO(cudaMemcpyAsync(&addr, &comm->channels[c].devPeers[sendPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost, comm->sharedRes->hostStream.cudaStream), ret, fail);
                CUDACHECKGOTO(cudaMemcpyAsync(&addr->send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
```
The first call works, so we're not completely broken, but maybe `addr` could be corrupted (or NULL) here.

Also, can you confirm you're not using `ncclCommSplit` when you detect NCCL supports it?

**Comment by PhdShi** [comment]
> @PhdShi this is a different issue related to NVLS. Please open a new issue about that, thanks!
> 
> @maxhgerlach If you can add some debugging before the code that fails, it could be interesting to print the arguments to cudaMemcpyAsync, to see which argument is wrong (if any is obviously wrong). One thing that changed between 2.14 and 2.18 is the resource sharing code for ncclCommSplit. So instead of calling:
> 
> ```
> CUDACHECKGOTO(cudaMemcpyAsync(comm->channels[c].devPeers[sendPeer].send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
> ```
> 
> we now retrieve the address of `comm->channels[c].devPeers[sendPeer]` first, then perform the copy:
> 
> ```
>                 CUDACHECKGOTO(cudaMemcpyAsync(&addr, &comm->channels[c].devPeers[sendPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost, comm->sharedRes->hostStream.cudaStream), ret, fail);
>                 CUDACHECKGOTO(cudaMemcpyAsync(&addr->send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
> ```
> 
> The first call works, so we're not completely broken, but maybe `addr` could be corrupted (or NULL) here.
> 
> Also, can you confirm you're not using `ncclCommSplit` when you detect NCCL supports it?

This is not an issue with version NCCL 2.18.3. It seems to be fixed by this commit 8ed014bae9f30d4470cdfa655f32d35ee5b3e7ca.
thanks!

**Comment by maxhgerlach** [comment]
> @PhdShi this is a different issue related to NVLS. Please open a new issue about that, thanks!
> 
> @maxhgerlach If you can add some debugging before the code that fails, it could be interesting to print the arguments to cudaMemcpyAsync, to see which argument is wrong (if any is obviously wrong). One thing that changed between 2.14 and 2.18 is the resource sharing code for ncclCommSplit. So instead of calling:
> 
> ```
> CUDACHECKGOTO(cudaMemcpyAsync(comm->channels[c].devPeers[sendPeer].send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
> ```
> we now retrieve the address of comm->channels[c].devPeers[sendPeer] first, then perform the copy:
>
>                CUDACHECKGOTO(cudaMemcpyAsync(&addr, &comm->channels[c].devPeers[sendPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost, comm->sharedRes->hostStream.cudaStream), ret, fail);
>                CUDACHECKGOTO(cudaMemcpyAsync(&addr->send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
>
> The first call works, so we're not completely broken, but maybe addr could be corrupted (or NULL) here.

Hi @sjeaugey, thanks for the advice and sorry for not getting back to you sooner.

I've managed to reproduce the problem on a local build of NCCL 2.18.3-1 with added argument logging (diff at https://github.com/NVIDIA/nccl/compare/v2.18.3-1...maxhgerlach:nccl:v2.18.3-1_maxhgerlach). 

Ranks 5 and 7 (out of 16) failed on this run. As you suspected, in both cases `addr` is `NULL` after the first `cudaMemcpyAsync`, so that the second call must fail. Logs for both failing ranks are below.

> Also, can you confirm you're not using ncclCommSplit when you detect NCCL supports it?

I will have to dive a bit deeper into the Python code here to understand how this is done in torch.distributed, which I'm not super familiar with. We're setting up several process groups for "3d parallelism" here, so it may actually be using `ncclCommSplit`.

BTW, we reproduced the error using two different pre-releases of PyTorch, [2.1.0a0+4136153](https://github.com/pytorch/pytorch/commit/41361538) and [2.1.0a0+b5021ba](https://github.com/pytorch/pytorch/commit/b5021ba9). Those match the versions shipped with [NGC containers](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/) 23-06 and 23-07, although we compiled the PyTorch packages ourselves and didn't actually use those containers.

----

Rank 5:
```
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Using network IB
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO comm 0xdf895650 rank 0 nranks 2 cudaDev 5 nvmlDev 5 busId a1000 commId 0x9a9c07adb315530 - Init START
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO === System : maxBw 12.5 totalBw 24.0 ===
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO CPU/6 (1/2/-1)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO + SYS[5000.0] - CPU/5
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO + PCI[24.0] - GPU/A1000 (0)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO CPU/5 (1/2/-1)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO + SYS[5000.0] - CPU/6
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO + PCI[24.0] - NIC/C2000
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO               + NET[12.5] - NET/0 (e0cce50003fd7010/1/12.500000)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO ==========================================
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO GPU/A1000 :GPU/A1000 (0/5000.000000/LOC) CPU/6 (1/24.000000/PHB) CPU/5 (2/24.000000/SYS) NET/0 (4/12.500000/SYS)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO NET/0 :GPU/A1000 (4/12.500000/SYS) CPU/6 (3/12.500000/SYS) CPU/5 (2/12.500000/PHB) NET/0 (0/5000.000000/LOC)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Setting affinity for GPU 5 to 03f00000,000003f0,00000000
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Pattern 4, crossNic 0, nChannels 1, bw 12.000000/12.000000, type LOC/SYS, sameChannels 1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO  0 : NET/0 GPU/0 NET/0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Pattern 3, crossNic 0, nChannels 1, bw 24.000000/12.000000, type LOC/SYS, sameChannels 1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO  0 : NET/0 GPU/0 NET/0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Tree 0 : -1 -> 0 -> 1/-1/-1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Tree 1 : 1 -> 0 -> -1/-1/-1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Channel 00/02 :    0   1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Channel 01/02 :    0   1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Ring 00 : 1 -> 0 -> 1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Ring 01 : 1 -> 0 -> 1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO P2P Chunksize set to 131072
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Channel 00/0 : 1[5] -> 0[5] [receive] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Channel 01/0 : 1[5] -> 0[5] [receive] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Channel 00/0 : 0[5] -> 1[5] [send] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] NCCL INFO Channel 01/0 : 0[5] -> 1[5] [send] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:153 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm=0xdf895650
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:154 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm->channels=0xdf8956e0
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:155 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm->channels[c].devPeers=0x7f022fe30400
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:156 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: &comm->channels[c].devPeers[sendPeer]=0x7f022fe30408
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:157 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm->sharedRes->hostStream.cudaStream=0x7efd98005550
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:159 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: addr=(nil)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:160 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: addr->send=(nil)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:161 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: &addr->send[connIndex]=(nil)
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:162 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: conn=0x7efd9804df28
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:163 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: &conn->conn=0x7efd9804df58
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:164 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: comm->sharedRes->hostStream.cudaStream=0x7efd98005550
Wed Sep  6 17:26:52 2023[1,5]<stdout>:
Wed Sep  6 17:26:52 2023[1,5]<stdout>:tomte249:86388:88864 [5] transport.cc:166 NCCL WARN Cuda failure 'invalid argument'    
```

Rank 7:
```
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Using network IB
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO comm 0xdff53b50 rank 0 nranks 2 cudaDev 7 nvmlDev 7 busId e1000 commId 0x44177c7a6970c9fa - Init START
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO === System : maxBw 12.5 totalBw 24.0 ===
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO CPU/4 (1/2/-1)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO + SYS[5000.0] - CPU/5
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO + PCI[24.0] - GPU/E1000 (0)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO CPU/5 (1/2/-1)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO + SYS[5000.0] - CPU/4
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO + PCI[24.0] - NIC/C2000
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO               + NET[12.5] - NET/0 (e0cce50003fd7010/1/12.500000)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO ==========================================
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO GPU/E1000 :GPU/E1000 (0/5000.000000/LOC) CPU/4 (1/24.000000/PHB) CPU/5 (2/24.000000/SYS) NET/0 (4/12.500000/SYS)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO NET/0 :GPU/E1000 (4/12.500000/SYS) CPU/4 (3/12.500000/SYS) CPU/5 (2/12.500000/PHB) NET/0 (0/5000.000000/LOC)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Setting affinity for GPU 7 to 3f00,00000000,3f000000
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Pattern 4, crossNic 0, nChannels 1, bw 12.000000/12.000000, type LOC/SYS, sameChannels 1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO  0 : NET/0 GPU/0 NET/0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Pattern 3, crossNic 0, nChannels 1, bw 24.000000/12.000000, type LOC/SYS, sameChannels 1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO  0 : NET/0 GPU/0 NET/0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Tree 0 : -1 -> 0 -> 1/-1/-1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Tree 1 : 1 -> 0 -> -1/-1/-1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Channel 00/02 :    0   1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Channel 01/02 :    0   1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Ring 00 : 1 -> 0 -> 1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Ring 01 : 1 -> 0 -> 1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO P2P Chunksize set to 131072
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Channel 00/0 : 1[7] -> 0[7] [receive] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Channel 01/0 : 1[7] -> 0[7] [receive] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Channel 00/0 : 0[7] -> 1[7] [send] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] NCCL INFO Channel 01/0 : 0[7] -> 1[7] [send] via NET/IB/0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:153 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm=0xdff53b50
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:154 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm->channels=0xdff53be0
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:155 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm->channels[c].devPeers=0x7f9e95630400
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:156 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: &comm->channels[c].devPeers[sendPeer]=0x7f9e95630408
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:157 NCCL WARN Inside ncclTransportP2pSetup()_a i=1 c=0 connIndex=0. Argument: comm->sharedRes->hostStream.cudaStream=0x7f9a6c005550
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:159 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: addr=(nil)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:160 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: addr->send=(nil)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:161 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: &addr->send[connIndex]=(nil)
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:162 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: conn=0x7f9a6c04df28
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:163 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: &conn->conn=0x7f9a6c04df58
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:164 NCCL WARN Inside ncclTransportP2pSetup()_b i=1 c=0 connIndex=0. Argument: comm->sharedRes->hostStream.cudaStream=0x7f9a6c005550
Wed Sep  6 17:26:52 2023[1,7]<stdout>:
Wed Sep  6 17:26:52 2023[1,7]<stdout>:tomte249:86390:88868 [7] transport.cc:166 NCCL WARN Cuda failure 'invalid argument'

```

**Comment by sjeaugey** [comment]
Actually I'm realizing the first cudaMemcpy to retrieve the value of `addr`  should not be an async operation. We need to make sure the memcpy completed before we use the value of `addr`. I'm not even sure how that would have worked so far ...

Can you try to make the first memcpy operations not async and see if it fixes the issue? I.e. apply this patch:
```
diff --git a/src/transport.cc b/src/transport.cc
index f4b8a2a6..29bf4325 100644
--- a/src/transport.cc
+++ b/src/transport.cc
@@ -150,7 +150,7 @@ ncclResult_t ncclTransportP2pSetup(struct ncclComm* comm, struct ncclTopoGraph*
                 struct ncclDevChannelPeer* addr;
                 conn->connected = 1;
                 /* comm->channels[c].devPeers[sendPeer]->send[connIndex] is a device memory access. */
-                CUDACHECKGOTO(cudaMemcpyAsync(&addr, &comm->channels[c].devPeers[sendPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost, comm->sharedRes->hostStream.cudaStream), ret, fail);
+                CUDACHECKGOTO(cudaMemcpy(&addr, &comm->channels[c].devPeers[sendPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost), ret, fail);
                 CUDACHECKGOTO(cudaMemcpyAsync(&addr->send[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
               } else if (ret == ncclInProgress) {
                 allChannelsConnected = false;
@@ -170,7 +170,7 @@ ncclResult_t ncclTransportP2pSetup(struct ncclComm* comm, struct ncclTopoGraph*
                 struct ncclDevChannelPeer* addr;
                 conn->connected = 1;
                 /* comm->channels[c].devPeers[recvPeer]->recv[connIndex] is a device memory access. */
-                CUDACHECKGOTO(cudaMemcpyAsync(&addr, &comm->channels[c].devPeers[recvPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost, comm->sharedRes->hostStream.cudaStream), ret, fail);
+                CUDACHECKGOTO(cudaMemcpy(&addr, &comm->channels[c].devPeers[recvPeer], sizeof(struct ncclDevChannelPeer*), cudaMemcpyDeviceToHost), ret, fail);
                 CUDACHECKGOTO(cudaMemcpyAsync(&addr->recv[connIndex], &conn->conn, sizeof(struct ncclConnInfo), cudaMemcpyHostToDevice, comm->sharedRes->hostStream.cudaStream), ret, fail);
               } else if (ret == ncclInProgress) {
                 allChannelsConnected = false;
```
I'm not saying this is the final solution; ideally we'd want to cache the value of the address in cpu memory to avoid the need for such CUDA transfers. But if that fixes the issue, it's a good hint as to what the problem is and how to fix it.

CC @KaimingOuyang

**Comment by maxhgerlach** [comment]
I can confirm that it looks as if your patch fixes the issue on my end. (https://github.com/NVIDIA/nccl/compare/v2.18.3-1...maxhgerlach:nccl:v2.18.3-1_maxhgerlach) Thank you very much for the quick response!

I first reproduced the issue again on the same hosts as yesterday, then retried linking NCCL with your patch, and this time the training commenced just fine.

Probably you've already seen it, but could there be a similar bug in `transport/nvls.cc`? https://github.com/NVIDIA/nccl/blob/559b70f86c190a0d8f67f0d7a0f2c9810dd1e8c7/src/transport/nvls.cc#L363

**Comment by sjeaugey** [comment]
Yes indeed. Thanks for the confirmation! We'll fix this asap.

**Comment by peiji1981** [comment]
hello, did you solve this problem?

> Yes indeed. Thanks for the confirmation! We'll fix this asap.

**Comment by sjeaugey** [comment]
Yes this is fixed in NCCL 2.18.6 and 2.19.3 (IIRC).

**Comment by Xiaoaier-Z-L** [comment]
when i use hostPID in container, it work; and when i disabled hostPID in container, it reproduce.
